### ISSUE TITLE
[filter set] can set filter work without converting values to strings?

### ISSUE THREAD

**Issue by Mithras** [ag-grid/ag-grid#1005]
At the moment params.value is always string in filterParams cellRenderer. That means that you hardly ever can reuse cellRenderer. For example:

```
const colDef: ColDef = {
    field: "booleanField",
    cellRenderer: (params: { value: boolean }) => params.value ? "Yes" : "No",
    filterParams: { cellRenderer: (params: { value: string }) => params.value === "true" ? "Yes" : "No" }
};
```

and that's how I want it to to be:

```
const cellRenderer = (params: { value: boolean }) => params.value ? "Yes" : "No";
const colDef: ColDef = {
    field: "booleanField",
    cellRenderer: cellRenderer,
    filterParams: { cellRenderer: cellRenderer }
};
```

Using valueGetter instead is not the same because the column might be editable or whatever.

**Comment by tloten** [comment]
This has been bugging me for a while too.
Another problem with it being a string is that sorting (of the items in the set-filter) is done based on alphanumeric sorting. So numbers will appear like:
`0
1
10
2
20
3`

**Comment by tystol** [comment]
+1

@ceolter I understand you store these values as keys in a js object for performance reasons, so they must be a string, but surely this js map can be setup so each object in the map contains the original 'sourceValue', which can then be passed into the cellRenderer? (havn't looked at the code, just spitballing)

**Comment by ceolter** [comment]
as @tystol  points out - the map contains simple true/false values, so eg if you have value of 'apple' it looks up if apple is selected as follows: ```selectedValuesMap['apple']``` which returns true if apple is selected.

so @tystol , because it's a lookup to true/false, its' not possible to tag on other values.

when developing this out, having strings as keys was the only way to get it working in a performance way. if you have 10,000 rows, that's 10,000 lookups every time the the filter changes.

it's not a simple fix - the setFilter is complex piece - but if i do get an idea on how to fix easily, i'll do. but for now, you will have to work around it.

@tloten you can provide your own filterParams.comparator to sorting.

**Comment by tystol** [comment]
@ceolter if I understand correctly, the performance benefit comes from using strings as keys in the map, but nothing to do with storing bool values directly inside the map, right? Again, haven't looked at the code (can you point me to this filter code?), but what about storing an object in the map rather than direct booleans, that contains both the boolean selected value, along with the source value? eg, when setting up the filter:
`selectedValuesMap['0.01'] = {selected:true, sourceValue:0.01};`
Then when you lookup to check if it is selected, it simply becomes `selectedValuesMap['0.01'].selected` (with some null checks).

**Comment by ceolter** [comment]
@tystol sounds feasible - i'd have to spend some time looking into it to make sure though

**Comment by tystol** [comment]
Something like this?
https://github.com/ceolter/ag-grid-enterprise/pull/45

**Comment by sudhir113** [comment]
Hello 
  i have isuue, how to import excel data in ag-grid in aurelia

**Comment by seanlandsman** [comment]
tracked by AG-129
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by mjattiot** [comment]
Hello guys,
We are using the set filter as well with our enterprise edition and we noticed a related issue. I am not sure if AG-129 will handle it so let me describe the issue:
- We have a set filter which use an array of integers for the filterParams.value parameter (it's an enumeration)
- We use cellrenderer to convert the enum to strings to display
- Internally ag grid convert the array of integers to an array of string which is fine for us
- However ! we usually store the state of filters when the getRow callback is raised. The callback parameter has a filterModel attribute set with the array of integers instead of strings. It's an issue because using setFilterModel with such an object won't work. We therefore need to save the state using getFilterModel instead of the getRow filterModel parameter. It's inconsistent.
- By the way if we convert our set filter value parameter to an array of string (ie ["0", "1", "2"]), getRow callback will still have an array of integer has a parameter ...

What's your advise on this one ? Our workaround is just to ignore getRow parameters and reuse the API to get the current filter model.

**Comment by tystol** [comment]
@seanlandsman Last time I looked at the ag-grid-pipeline page, it did contain the AG-129 ticket, so I was hopeful this would be looked at soon. But looking at the pipeline now, I see no mention of AG-129. Is this still on your roadmap to fix? set filters are very clunky as it stands right now, and more so when combined with valueFormatters.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by david-genger** [comment]
This is an issue for me as well, any update on this?
