### ISSUE TITLE
[grouping] Leave items 'outside' of a group if group key is empty

### ISSUE THREAD

**Issue by ceolter** [ag-grid/ag-grid#111]
If you turn on grouping every row is put into a group (if a row doesn't have a grouping field it's put in "undefined"). I'd like to be able to specify those rows that don't contain a grouping field be placed on the grid as a normal ungrouped row.

**Comment by JimmyBoh** [comment]
:+1:

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-44

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by apurvaojas** [comment]
Hi @ceolter,

is this feature is release [https://ag-grid.atlassian.net/browse/AG-44](https://ag-grid.atlassian.net/browse/AG-44 )

do we need to pass any configuration to make it work..?

**Comment by AG-Zoheil** [comment]
Hi @apurvaojas,

Thank you for your comment.

We'd be keen to look into this again for you, but as you can see this is quite an old issue from more than **six years ago**.

The grid has naturally advanced a lot since then. If you are still having problems, can we please ask you to open a new issue with a reproducible live scenario - you can use one of the plunker examples from our [documentation](https://ag-grid.com/javascript-data-grid/) as a starting point.

This would help our team support in the most efficient way, and also increase visibility for the wider AG Grid community in case of contributions and comments.

Much appreciated!

Kind regards,
Zoheil
