### ISSUE TITLE
[csv footers] CSV doesn't export row group footers

### ISSUE THREAD

**Issue by ataft** [ag-grid/ag-grid#1199]
It appears that footer nodes are not in the Row Model when grouping. I noticed this when doing a CSV Export and traced the issue [here](https://github.com/ceolter/ag-grid/blob/859c7d79351fb5b6f07e1b16586c780e7488657a/dist/lib/csvCreator.js#L119).  The footer rows are not included in the "inMemoryRowModel.forEachNodeAfterFilterAndSort(processRow)". See this fiddle, which also outputs the nodes to the console: 
https://jsfiddle.net/andytaft/n168v3hy/5/

Also, it's important that the CSV export use the cell renderers so that users are not confused by the export. Ag-grid is excellent and I get very few support calls for anything grid-related, but the support calls I do get are usually around the CSV export.

**Comment by ceolter** [comment]
hi Andrew, i'll leave this item open, but as a low priority, as the footers are used by very few people and it's not that easy for me to fix.

the problem is that the footers are a GUI item - when the grid is deciding what rows to show, it adds in footer rows to any groups that are open.

on the export, it is exporting everything, even closed groups, so it's exporting before the footers come into play. if it were to include the footers, then it would also exclude the contents of the closed groups.

it is fixable, with reworking how the export works, however it's a chunk of work, hence will leave this issue open and come back if i am more free sometime.

with regards the cellRenderers, it is not correct to use these for export, as they can return complex html, including html with logic. if you want to format for the export, then you should use processCellCallback (one of the export params)

**Comment by ceolter** [comment]
tracked by AG-145
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
