### ISSUE TITLE
[scroll] Select-Drag-Scroll not working (IE11)

### ISSUE THREAD

**Issue by takabanana** [ag-grid/ag-grid#1322]
In IE11, Drag-Select multiple cells and trying to scroll does not scroll (selection works, but does not scroll to select cells outside of the view, even if there are cells outside of the view).  Tried both vertically and horizontally.
Is this a known issue with IE11?  Any plans on getting it working?

See video:
http://screencast.com/t/sQ9kIdSds

**Comment by ceolter** [comment]
was not aware of this. the drag-scroll is something the browser does, not the grid. i don't know why it's not working for the grid.

will leave issue open, but considering it low priority.

**Comment by ceolter** [comment]
tracked by AG-160
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
