### ISSUE TITLE
[filter demo] - Fix demo, looks like number filter is broken

### ISSUE THREAD

**Issue by gauravjhs** [ag-grid/ag-grid#1428]
In https://www.ag-grid.com/example.php

Equal and Not Equal filter not working on Number columns(Monthly Breakdown -> Jan).

**Comment by AmitMY** [comment]
They actually do work, just not in the way that you would expect.
The `jan` column shows a number, and a currency. That number is a round formatted number, so for example if you try looking for `81081` which is shown on the table, you will find nothing, because this is just a cell rendered value, while if you look for the real value - `81081.49` you will find it.

**Comment by ceolter** [comment]
thanks @AmitMY

**Comment by AmitMY** [comment]
@ceolter I think closing this issue is a mistake.
I think the issue shows a problem with the main example.
Either there should be a custom filter there, or a text filter, but not the number one, as it will not "really" work for people who are trying the grid for the first time - and I remember that the example page is what sold me on it, so I would not take it lightly

**Comment by ceolter** [comment]
tracked by AG-178
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
This should be fixed now
