### ISSUE TITLE
[scroll] Allow the pinned column rendering with the scrollLag option

### ISSUE THREAD

**Issue by jare-talend** [ag-grid/ag-grid#1436]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Expected behavior**

Hi,

I use scrollLag to improve the performance during the scroll. I use the a left pinned column to show a index. During the scroll, the pinned column rendered when the scroll finished except that the user can't see where he is during the scroll. 

Can you add an option to allow the pinned column to render during the scroll with the scrollLag? This will be cheaper than whole rendering of all column.

**Comment by seanlandsman** [comment]
We've added this to our backlog to consider for a future release - thanks

**Comment by seanlandsman** [comment]
This issue is AG-52 - you can track the status of this on our backlog: https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
