### ISSUE TITLE
IHeaderParams does not pass context

### ISSUE THREAD

**Issue by maccuaa** [ag-grid/ag-grid#1474]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] support request

**Current behavior**

When trying to use third-party libraries (in my case [Material-UI](http://www.material-ui.com)), I can use it no problem in a CellRenderer because the [context is passed on](https://www.ag-grid.com/javascript-grid-context).  When I try to use a Material-UI component in an AgGrid Header Component it doesn't work because the context is not passed in the [params ](https://github.com/ceolter/ag-grid/blob/master/src/ts/headerRendering/header/headerComp.ts#L14) like it is in a [Cell Renderer](https://github.com/ceolter/ag-grid/blob/master/src/ts/rendering/cellRenderers/iCellRenderer.ts#L21). 

**Expected behavior**

The expected behavior would be for a Header Component to behave like a Cell Renderer.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

The ability to use third-party libraries that rely on context in a HeaderComponent just like you can in a CellRenderer.

**Please tell us about your environment:**

* **ag-Grid version:** 8.0.1
* **ag-Grid-React:** 8.0.0

* **Language:** all

**Comment by willhalling** [comment]
Hi @st-andrew 

Thanks for raising this. I've raised as a bug. You can check progress on our pipeline page [AG-250]:

https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
