### ISSUE TITLE
Get refreshVirtualPageCache() to load from the page that is currently visible 

### ISSUE THREAD

**Issue by Liooo** [ag-grid/ag-grid#1485]
```
[  ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It loads from the last loaded page.

**What is the motivation / use case for changing the behavior?**
Say I've got 10 virtual pages loaded, and editing a cell value on the first page, by which the order of the row changes to the very end of the dataset. When I call refreshVirtualPageCache it's gonna be the after the 10th request that the first page is updated and the edited row disappears.

**Comment by willhalling** [comment]
Hello @Liooo

I've raised this pull request. This should be added in a future release. You can check progress on our pipeline page (AG-273):

https://www.ag-grid.com/ag-grid-pipeline/

**Comment by Liooo** [comment]
@willhalling thank you!

**Comment by ceolter** [comment]
i don't follow - when you call refreshVirtualPageCache(), all the pages are refreshed. advise what is wrong with this?

**Comment by Liooo** [comment]
@ceolter 
Yea all the page is loaded either way, but I'm talking about the order of the loading. Better loaded from the currently visible page to make it seem faster.

Here's my actual use case. I have rows that are sorted by date column's value, and user can modify the date in the grid, which triggers refreshVirtualPageCache() and refetch the server side re-sorted data. Say now the grid has 10 virtual pages loaded in advance, and the user changes the date of the very first row of the first page, the user has to wait for 10 requests before seeing the first page updating and the updated row disappearing from the page (because currently the request starts from the one for the last page to the one for the first page). 
So it'd be nice if any of the following is possible.

- making ag-grid load the currently visible page first, then load the rest of the pages
- letting developers specify the order of the page update
- adding a method to update only specified pages

Sorting the pages here will do.
https://github.com/ceolter/ag-grid/blob/master/src/ts/rowModels/infinateScrolling/virtualPageCache.ts#L258

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
