### ISSUE TITLE
aggrid as webcomponent -> error in safari

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#1507]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
in safari I got the error "unable to find document.registerelement"

**Expected behavior**
your code should use customelement.define, cause the other is deprecated (see https://developer.mozilla.org/de/docs/Web/API/Document/registerElement)

* **ag-Grid version:** X.X.X
8.1.1

* **Browser:**
Safari 10

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
This issue has been raised as AG-310. You can track its progress in our pipeline (https://www.ag-grid.com/ag-grid-pipeline/) but we’ll also update this thread when actioned.

thanks

**Comment by jogibear9988** [comment]
Would it increase implementation if I create a pull request?

Should I check for customelement.define, if not available use registerElement?

**Comment by seanlandsman** [comment]
Hi @jogibear9988 - apologies for the delay!

Yes, if you can supply a PR we can review and accept - that would be great

**Comment by jogibear9988** [comment]
One Problem: webcomponents V1 need ES6 classes. Can we compile ag grid typescript to use es6 classes? Or maybe we should generate an extra ES6 Version?

You see here: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define the define method needs a constructor as second parameter

**Comment by jogibear9988** [comment]
Will it be possible, that we compile to a ES6 Version (wich then supports webcomponents V1)?

**Comment by jogibear9988** [comment]
Any news to this?

**Comment by seanlandsman** [comment]
@jogibear9988 sorry for the delay - I'm actively looking at this now

I'll update you on progress next week

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
