### ISSUE TITLE
Moving certain columns from the toolpanel throws error

### ISSUE THREAD

**Issue by ha-decodeit** [ag-grid/ag-grid#1517]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request 
```

**Current behavior**
Dragging columns from the toolpanel into the grid (and move them around a bit) sometimes throws the following error:
```
ag-grid-enterprise.js?ignore=notused41:24138 Uncaught TypeError: Cannot read property 'getActualWidth' of undefined
    at MoveColumnController.getNewIndexForColMovingRight (ag-grid-enterprise.js?ignore=notused41:24138)
    at MoveColumnController.workOutNewIndex (ag-grid-enterprise.js?ignore=notused41:24014)
    at MoveColumnController.attemptMoveColumns (ag-grid-enterprise.js?ignore=notused41:24085)
    at MoveColumnController.onDragging (ag-grid-enterprise.js?ignore=notused41:24055)
    at BodyDropTarget.onDragging (ag-grid-enterprise.js?ignore=notused41:23902)
    at DragAndDropService.onDragging (ag-grid-enterprise.js?ignore=notused41:21628)
    at DragService.onCommonMove (ag-grid-enterprise.js?ignore=notused41:11746)
    at DragService.onMouseMove (ag-grid-enterprise.js?ignore=notused41:11759)
```

**Expected behavior**
Dragging columns should never result in an error.

**Minimal reproduction of the problem with instructions**
In the [official ag-grid demo](https://www.ag-grid.com/example.php), drag the column _Extra Info 1_ from the toolpanel and move it around in the grid a few times. The above console error is thrown. 
It seems that in the demo this error only happens on the _Extra Info 1_ and _Extra Info 2_ columns, and in my application the same problem is present on some columns but not all.

* **ag-Grid version:** 
8.2.0

* **Browser:**
Chrome 57.0.2987.98

* **Language:** 
Typescript 2.2.1

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this - I've raised issue AG-319 our side for this.

We'll update this thread with any updates

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
