### ISSUE TITLE
insertItemsAtIndex results in duplicate row node ids when using virtual row model

### ISSUE THREAD

**Issue by egidijusj** [ag-grid/ag-grid#1530]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using virtual row model, calling `api.insertItemsAtIndex()` will add items with duplicate row node ids. While this is not a big problem in itself, it breaks other functionality that relies on `rowNode.id`, for example, `api.refreshRows()`

**Expected behavior**
`api.insertItemsAtIndex()` should not reuse existing ids for new items.

**Minimal reproduction of the problem with instructions**
1. Open https://jsfiddle.net/p0cqv89j/1/
2. Click `Add row at index` to insert new item to the grid at specified index. You can see in the second column that `node.id` is duplicated.
3. Click `Refresh row at index` to refresh row node at specified index. The newly added row with duplicate id will be moved under the existing row with the same id. You can inspect the DOM to verify this.

**Please tell us about your environment:**
This issue is reproducible in number of browsers and OSes

* **ag-Grid version:** X.X.X
8.2.0

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by seanlandsman** [comment]
Hi - issue AG-341 as been raised on our side for this. We'll update this thread with updates as soon as we have any

thanks

**Comment by egidijusj** [comment]
For anyone interested - currently we work-around this by calling `api.forEachNode(node => node.id = node.rowIndex.toString())` after every call of `api.insertItemsAtIndex()`.

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
