### ISSUE TITLE
Improve sizeColumnsToFit logic

### ISSUE THREAD

**Issue by Wykks** [ag-grid/ag-grid#1536]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
From the docs: sizeColumnsToFit make the currently visible columns fit the screen. The columns will scale (growing or shrinking) to fit the available width. 

**Expected behavior**
It would be great if we were able to tune the default behavior of sizeColumnsToFit.
Something like this : 
`sizeColumnsToFit(ResizeStrategy.default)`
Current behavior (keep the current proportion and just grow or shrink all columns at the same rate)
`sizeColumnsToFit(ResizeStrategy.valuesFirst)`
Which would prioritize column with large value and give less space to small column.
`sizeColumnsToFit(ResizeStrategy.valuesFirstWithoutHeader)`
Same but without taking header size in account (this is actually what I need)

**Minimal reproduction of the problem with instructions**
`sizeColumnsToFit(ResizeStrategy.valuesFirst)`, this is already doable like this (but not ideal) : 
```
columnApi.autoSizeAllColumns(); // which will grow or shrink every column to their content width
api.sizeColumnsToFit()` // which will grow or shrink every column at the same rate so the previously largest columns will still be the largest
// Done
```
`sizeColumnsToFit(ResizeStrategy.valuesFirstWithoutHeader)`, could be done the same way if `columnApi.autoSizeAllColumns()` was not taking header size into account

**Visual examples (better than my english)**

```
// Initial state
||               screen                 ||
|ColumnA   |ColumnB    |
|alongte...|value      |

// With current sizeColumnsToFit();
||               screen                 ||
|ColumnA           |ColumnB             |
|alongtextvalueh...|value               |
// ColumnA values are cut :( 

// With sizeColumnsToFit(ResizeStrategy.valuesFirst);
||               screen                 ||
|ColumnA                        |ColumnB|
|alongtextvaluehereforthecolu...|value  |
// Still cut, but that's better (and you may want to not cut headers)

// With sizeColumnsToFit(ResizeStrategy.valuesFirstWithoutHeader);
||               screen                 ||
|ColumnA                          |Co...|
|alongtextvaluehereforthecolumnnoA|value|
// Now all the value are directly readable, yay !
```
Of course, this only works with current rendered cells, it's up to the dev to call sizeColumnsToFit as needed (page change for example).

* **ag-Grid version:** 8.2.0

**Comment by seanlandsman** [comment]
Hi

Thanks for the feedback. These ideas seem reasonable to me - I've raised AG-344 to track this, but we'll update this thread too with updates as soon as we have any

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
