### ISSUE TITLE
stopEditing doesn't get called when focus shifts to another grid's cell

### ISSUE THREAD

**Issue by drew-wallace** [ag-grid/ag-grid#1541]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using ag-grid with react (ag-grid-react): Let's say I have Grid A and Grid B. Both grids are 4x4 filled with 0's. I double click the top left cell in Grid A. I change the current value to 1. I then double click the top left cell in Grid B and change it's value to 1. I press enter and Grid A's top left cell reverts back to 0 and Grid B's top left cell keeps it's new value.
**Expected behavior**

Ideally, when focus is lost on Grid A (regardless of where the new focus shifts to), Grid A's top left cell should have triggered a stopEditing call in order to preserve the value.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

If anyone were to have more than one grid on a page, and they wanted to edit more than one of those grids by selecting each cell specifically, then this bug would impact them.
**Please tell us about your environment:**

OS: macOS 10.11.6
IDE: VS Code 1.10.2
Package Manager: NPM 4.1.2
Node: 7.5.0
react: 15.4.2
* **ag-Grid version:** X.X.X

ag-grid: 8.2.0
ag-grid-react: 8.2.0

* **Browser:**

Chrome: 56.0.2924.87 (64-bit)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript: 2.2.1
ES6/7

**Comment by seanlandsman** [comment]
Hi

We have a high priority issue raised our side for this (AG-307)

I'll update this thread once i have an update

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
