### ISSUE TITLE
Visual order of rows doesn't match DOM elements - causes tabbing into the grid to enter at the wrong row

### ISSUE THREAD

**Issue by stephanjust** [ag-grid/ag-grid#1583]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```
(this could be labelled as a bug, but I assume it's by design)

**Current behavior**
The ordering of rows in the DOM doesn't match the visual rows. This doesn't cause issues for ag-grid itself because the rows are all placed as absolute elements with a fixed top offset and tabbing is handled by JS code. It does cause an issue however when you tab into the grid (we use input fields in our cell renderers allowing this to work), as this key event is still handled by DOM order/tabindex, causing the browser to focus the first row in the DOM (and that's quite often a row in the middle of the visual data set).
**Expected behavior**
The DOM should match the visual data.

**Minimal reproduction of the problem with instructions**
https://www.ag-grid.com/example.php inspecting the DOM while scrolling the grid.

**What is the motivation / use case for changing the behavior?**
Tabbing into the grid from another part of the page.

* **ag-Grid version:** 8.2.0
If https://www.ag-grid.com/example.php uses 9.0.0 it's still an issue.

* **Browser:**
"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"

* **Language:** all

**Comment by ceolter** [comment]
this is a tricky one to solve. thanks for raising. i have added 'tabbing into the grid' as a jira, it's number AG-419

two solutions i see:
+ when user tabs into the grid, somehow put the focus on the first row - which would be tricky if the user is scrolled down.
+ let the user decide somehow how to handle this. i think this is a can of worms, whatever we implement is bound to not work for everyone, as how you should tab into a grid that is scrolled half way down is open to user interpretation. eg if 1000 rows, and you are scrolled half way down, do you focus on row 500 (the first visible row) or row 1? and if row 500, what if the grid has some rows in the buffer? (the grid can draw a few rows extra, a buffer of rows above and below the viewport), then again what happens if a row is half visible?

because of the difficulties present, it may be better to document how to catch the tab event, and then let the user decide which row / cell gets the focus. it would be ag-grid's job to make sure this callback mechanism exists for the user.

**Comment by stephanjust** [comment]
> because of the difficulties present, it may be better to document how to catch the tab event, and then let the user decide which row / cell gets the focus. it would be ag-grid's job to make sure this callback mechanism exists for the user.

This sounds like a decent solution. I could currently think of people asking to always tab into the first row (total), into the first visual row (based on scrolling) and we probably have a use case for the last total row (as it's an input dummy that acts as a search field).

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
