### ISSUE TITLE
Moving a column also sort it.

### ISSUE THREAD

**Issue by dloprodu** [ag-grid/ag-grid#1595]
I'm using ag-grid in a Angular 4 project (version 9.0.3). The problem is when I move a column (with the mouse - drag & drop) then the grid sort the column too.

**Comment by seanlandsman** [comment]
Hi

I am unable to reproduce this - do you have a plunker I can take a look at?

thanks

**Comment by dloprodu** [comment]
At this moment no, but to reproduce the bug when you drop de column the mouse pointer must stay into de column header.

I can show you my template, I don't know if this can help you:

```
<ag-grid-angular                 
    [style.width.%]="100"
    [style.height.px]="_gridHeight" 

    class="ag-fresh ag-without-pagination-panel"

    [gridOptions]="_gridOptions"
    rowModelType="pagination"
    [paginationPageSize]="_pageSizeSelected"
    [datasource]="_datasource"
    [getRowNodeId]="getRowNodeId"

    animateRows
    enableServerSideSorting
    enableServerSideFilter

    enableColResize
    groupHeaders
    suppressDragLeaveHidesColumns
   
    toolPanelSuppressGroups
    toolPanelSuppressValues    

    [headerHeight]="_gridUtils.HEADER_HEIGHT"
    [rowHeight]="_gridUtils.ROW_HEIGHT"
    rowSelection="single"

    (gridReady)="onReady($event)"
    (paginationPageLoaded)="onRowDataChanged($event)"
    (gridSizeChanged)="onGridSizeChanged($event)"
    (selectionChanged)="onRowSelected($event)"
>

    <ag-grid-column colId="meassure" headerName="Meassure" field="meassure" [width]="150" filter="text"   [filterParams]="getDefaultFilterParams()"></ag-grid-column>
    <ag-grid-column colId="item"     headerName="Item"     field="item"     [width]="160" filter="text"   [filterParams]="getDefaultFilterParams()"></ag-grid-column>
    <ag-grid-column colId="os"       headerName="OS"       field="os"       [width]="120" 
                    [cellRenderer]="platformCellRender" 
                    [filterFramework]="getPlatformFilter()"  
                    [filterParams]="getPlatformFilterParams()"
    >
    </ag-grid-column>
    <ag-grid-column colId="country"  headerName="Country"  field="country"  [width]="120" 
                    [cellRenderer]="countryCellRender" 
                    [filterFramework]="getCountriesFilter()" 
                    [filterParams]="getCountryFilterParams()" 
                    [cellStyle]="{'text-align': 'center'}"
    >
    </ag-grid-column>
    <ag-grid-column colId="value"    headerName="Value"    field="value"    [width]="160" filter="text"   [filterParams]="getDefaultFilterParams()"></ag-grid-column>
    <ag-grid-column colId="year"     headerName="Year"     field="year"     [width]="120" filter="number" [filterParams]="getDefaultFilterParams()"></ag-grid-column>
    <ag-grid-column colId="month"    headerName="Month"    field="month"    [width]="120" filter="number" [filterParams]="getDefaultFilterParams()"></ag-grid-column>

</ag-grid-angular>
```

**Comment by AlexLnz** [comment]
HI, I can confirm this issue. Having it with ag-grid 8.0.0 then upgraded to 9.0.0 and 9.1.0 but still the same.

**Comment by AlexLnz** [comment]
Any news about this?

**Comment by seanlandsman** [comment]
Hi,

No, I'm afraid no updates - we are still unable to reproduce this

**Comment by AlexLnz** [comment]
Do you know why there is a difference at dragging the column (with / without the dragging rectangle)?
Is it a special mode? Maybe this will be a hint and I could investigate more.

**Comment by seanlandsman** [comment]
Looking at the head component code we can see the following:

this.eLabel.addEventListener('click', (event:MouseEvent) => {
                this.params.progressSort(event.shiftKey);
            });

So the grid is looking for click events for sorting - I guess good place to start would be to find out why a click is being sent when the column is being released

**Comment by AlexLnz** [comment]
Hm, I've nothing like that in my sample. Just a simple grid.

**Comment by seanlandsman** [comment]
Sorry - thats in the core grid code. Was meant to offer a point of where you could look until we are able to reproduce it ourselves

**Comment by AlexLnz** [comment]
I've added some debug code and the click handler above is called as soon as the mouse button is released over the header, after dragging the column. But only in the not-working variant.

The working variant displays this rectangle containing the column title. When releasing the mouse button it doesn't affect the column header. I guess that the clicked event goes to the moving rectangle instead of the column header, therefore nothing happens.

The question is why do I not get this rectangle while dragging?
Do you have any hint where to debug?

**Comment by raivis-v** [comment]
I also had the same issue in my project. In my case, the problem was with z-index. I increased z-index for ag-dnd-ghost element and problem was gone.

**Comment by AlexLnz** [comment]
@raivis-v Could you post a code sample how to do this?

**Comment by raivis-v** [comment]
Just put this code somewhere in your own css file
.ag-dnd-ghost{
  z-index: 5000;
}

Value depends on your actual project and what you have done in it. Could be much higher (or lower) in your case. Assuming you have the same issue I had.

**Comment by AlexLnz** [comment]
Hm, doesn't work for me. I did put it into the style sheet which belongs to the component where I use the ag-grid. I tried even bigger values, like 99999999 for z-index.

**Comment by raivis-v** [comment]
Ok then, it's not your case. Try to do element inspection while dragging column and look for ghost element if it's even there. It should appear as the last element in the DOM while dragging column.
![ghost](https://user-images.githubusercontent.com/29745468/27624107-f62ce598-5be7-11e7-82e6-759402769688.png)
If it is present, I think it should be something wrong with the styles. Try !important for z-index. I can't imagine anything else at the moment.

p.s.
Where did you get the second screenshot (not working one) in your previous posts? Is it from your own project or did you make sample from the scratch?

**Comment by AlexLnz** [comment]
It seems that there is no ghost element. When I drag a column all that changes is this:

![grid](https://user-images.githubusercontent.com/28703709/27624620-d30c9942-5be1-11e7-8396-9baa41231f21.png)

PS: My second screenshot is from our project. The same ag-grid in our production code, not demo.

**Comment by AlexLnz** [comment]
If the ghost object is the panel which appears normally during column dragging, which lies under the mouse cursor, then it is understandable why the mouse button release event is directed to the column header. Most probably it would have been directed to the ghost object's panel, if it was there. Then everything would be ok.

Question is why the "dragging panel" does not appear at all.

**Comment by raivis-v** [comment]
Yes, ghost element is the panel which appears while dragging column. Scroll down your DOM tree to the bottom so that "close body" tag is visible. Ghost should appear right above the close body tag (like in my screenshot). At least it does when using pure js version of the grid.

**Comment by AlexLnz** [comment]
Wow, it's actually placed at the end of the body!
So I have to place the CSS with the fix into index.html, not into the component. Now it works!
Thanks!

@seanlandsman Maybe it would be a good idea to increase the z-order of ag-dnd-ghost to a bigger value, as for example the 5000. The reason seems to be that we are using a UI framework, which provides windows having a greater z-order than ag-grid's drag n drop ghost.

**Comment by dloprodu** [comment]
In my case, I have problem with **ag-dnd-ghost** too. This element isn't correctly positioned.

My layout is composed by a fixed header and a body with position absolute and its own scroll.

![ag-bug](https://user-images.githubusercontent.com/664947/27818870-99716c46-608f-11e7-8985-0fb7106c4c7f.png)

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by yrral86** [comment]
I case someone else stumbles across this, we were seeing the same issue until we added
`.ag-dnd-ghost{
  position: absolute;
}`
