### ISSUE TITLE
[filter] - allow operands and sub queries

### ISSUE THREAD

**Issue by MolallaComm** [ag-grid/ag-grid#1603]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
You can currently set filters for multiple columns using:

let hardcodedFilter = {
    country: ['Ireland', 'United States'],
    age: {type: 'lessThan', filter: '30'},
    athlete: {type: 'startsWith', filter: 'Mich'},
    date:{type: 'lessThan', dateFrom: '2010-01-01'}
};

gridOptions.api.setFilterModel(hardcodedFilter);
gridOptions.api.onFilterChanged();

**Desired behavior**
The current code essentially ANDs all those conditions together - it would be great if you could do more complex filters - at least via the API - I can see how doing anything but AND via the current GUI would be problematic, but API or a new filter GUI in the Toolpanel could allow more advanced options - API only is sufficient for my needs at the moment:

// ActB gt 0 or ActP gt 0

let basicor = {
  ActB: {type: 'greaterThan', filter: '0'},
  ActP: {type: 'greaterThan', filter: '0'},
  Operand: 'or'
}

// ActB eq 0 and ActP eq 0 and (NumB gt 0 or NumP gt 0)

let complex = {
  ActB: {type: 'equal', filter: '0'},
  ActP: {type: 'equal', filter: '0'},
  Sub1: [{ NumB: {type: 'greaterThan', filter: '0' }, { NumP: {type: 'greaterThan', filter: '0' }, Operand: 'or' ]
  Operand: 'and'
}

I just put the subquery in an array to easily differentiate it - there might be a better way.  I'm migrating a project from infragistics silverlight grid to ag-grid and need this feature because we have quite a few complex filters saved away we'd like to keep.

It looks like this would be a small self contained change to rewrite doesFilterPass in filterManager.ts - which I might attempt assuming I can figure out how to build everything but wanted to check if there was an easier way and/or get feedback on my approach?  (One minor problem I see with above is if they had a column with Operand as the colId, that would be problematic but how likely is that).

**Comment by ceolter** [comment]
thank you for raising. i have created a JIRA for this AG-424, so it will get considered next times we decide what gets into a release.

in the mean time, it is possible to have your own complex filters using an API. we call this External Filter
https://www.ag-grid.com/javascript-grid-filter-external/

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
