### ISSUE TITLE
[touch] Scrolling Tool Panel on touch devices doesn't work

### ISSUE THREAD

**Issue by jonbcard** [ag-grid/ag-grid#1609]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Does not seem to be possible to scroll down with on the tool panel with touch gestures. Similar to:
https://github.com/ceolter/ag-grid/issues/418
https://github.com/ceolter/ag-grid/issues/1585

**Expected behavior**
Should be possible to scroll the tool panel to make hidden columns visible, or do other tool panel operations that might be hidden below the visible pane of content.

**Minimal reproduction of the problem with instructions**
Using agGrid demo, attempt to scroll the tool panel with device emulation in Chrome (or use a device).

**What is the motivation / use case for changing the behavior?**
User feedback

**Please tell us about your environment:**
Mobile devices tested: iOS, Android, Chrome device emulation

* **ag-Grid version:** 8.2.0

* **Browser:**
Any mobile browser

* **Language:** N/A

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this -  I've raised issue AG-432 our side for this. We'll update this thread once we have any updates.

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
