### ISSUE TITLE
ag-popup-editor top/left position inconsistent for rows near bottom of grid

### ISSUE THREAD

**Issue by jerryh91** [ag-grid/ag-grid#1629]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

For the dropdown fields of my project, I'm defining my editor component to extend AgEditorComponent and implementing isPopUp() to return true always. For most dropdowns, in rows near the top, the dropdown completely covers the cell and is positioned correctly. However, for dropdowns near bottom of grid, last 3 rows to be specific. The dropdown starts to shift up and the cell becomes more exposed.
Since I also may have error flyouts, the error flyouts are now covering up the dropdown menu and user unable to select any item because it's not visible.

Note: top position is same for 4th, 5th and all rows below that.
`<div class="ag-popup-editor" style="top: 145px; left: 559px;">`

Dropdown in 4th row
![dropdown4th5throw](https://cloud.githubusercontent.com/assets/3271989/25858369/3a991a26-34a1-11e7-83f9-0a8e1e03c278.png)
Dropdown in 5th row
![dropdown3rdrow](https://cloud.githubusercontent.com/assets/3271989/25858370/3aa2b2ca-34a1-11e7-972b-a1646615a124.png)

**Expected behavior**

Dropdown menu should be consistently positioned regardless of where the cell is located. 

**Minimal reproduction of the problem with instructions**

1. Set rowData to contain enough rows to fill the grid.
2. Set some column cellEditorFramework to be an angular 2 component that extends AgEditorComponent
3. In this editor component, implement isPopUp() and always return true. 
4. In the editor component template, implement standard html dropdown with at least 1 menu item.
5. Find in the grid the last ~3 rows visible have dropdown position inconsistent. 

**What is the motivation / use case for changing the behavior?**

Since I also have error flyouts in some of the dropdown fields,

 the error flyouts are now covering up the dropdown menu and user unable to select any item because it's not visible.

**Please tell us about your environment:**

Windows 7 Enterprise 64-bit.
npm 3.10.8

* **ag-Grid version:** X.X.X

ag-grid@8.1.1

* **Browser:**

Chrome: Version 57.0.2987.133
IE: 11
Firefox: 53.0.2 (32-bit)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.3

**Comment by ceolter** [comment]
i tried to recreate this with our demo - i change the editor to be the provide 'popupSelect' editor.

what i experienced was when the cell was to low, the popup went up, to stop the popup appearing off the browser.

the browser provided select though is not good here to demonstrate, as the grid places the select, but then when you click on the select, and the dropdown appears, then it's the browser that places the contents list, not the grid.

the grid will keep popups it controls within the bounds of the grid. this can be seen in our demo using the 'richSelect' (used on the country menu), when you edit a country in a row near the bottom, the popup is places so it does not overflow outside of the grid.

i did not check with angular component, however it should make no difference.

please can you describe how to recreate this using one of the online demo's in our docs? that will help us decide if it's expected behaviour or a bug.

**Comment by Robyn13** [comment]
I'm having the same issue. I am using angular 4 and creating an editor component with primgNG's datepicker and isPopup() is always returning true. When you select the editor in the last 4 rows the editor component always appears on the 5th to last row. 

![image](https://user-images.githubusercontent.com/22321100/31499019-1ed06a26-af29-11e7-87ba-7b0e151dd0cf.png)

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
