### ISSUE TITLE
Copy to clipboard does not work if suppressCellSelection is True (enterprise)

### ISSUE THREAD

**Issue by luanped** [ag-grid/ag-grid#1637]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Have an grid with supressCellSelection, enableRangeSelection and rowSelection='multiple', clicking a cell  (selects the row). When hitting ctrl + c, the sentToClipboard callback is never called.

**Expected behavior**
Have an grid with supressCellSelection, enableRangeSelection and rowSelection='multiple', clicking a cell  (selects the row). When hitting ctrl + c, the sentToClipboard callback is called.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 9.1.0 enterprise

* **Browser:**

Latest Chrome, using inside React

* **Language:** [TypeScript 2.3]

**Comment by luanped** [comment]
Furthermore, with the default copy behaviour, i.e. not using sentToClipboard -- if we select the row, and control click again to deselect the row leaving just the cell selected. the selected cell is copied twice.

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
