### ISSUE TITLE
Running ag-grid with ngupgrade causes protractor to hang

### ISSUE THREAD

**Issue by MrFrankel** [ag-grid/ag-grid#1654]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Running ag-grid in a ngupgrade app causes protractor to hang, this is due to a repeated setTimeout called by `periodicallyDoLayout`.

**Expected behavior**
Should check for zone and run in own zone.

I believe this is solved in ag-gird-angular but since we cant migrate our entire app to ag-grid-angular we have to use ag-grid in an ngupgraded app.

Thanks

**Comment by seanlandsman** [comment]
Hi

Do you have a repo you can provide that illustrates this problem?

**Comment by MrFrankel** [comment]
@seanlandsman Ill get one up ASAP, 
thanks

**Comment by MrFrankel** [comment]
@seanlandsman here is the previous thread on this.

https://github.com/ceolter/ag-grid-angular/issues/43

**Comment by MrFrankel** [comment]
@seanlandsman Here is a demo repo, simply follow the instructions in the Readme.
When running protractor it hangs waiting for angular. 
If you disable the `periodicallyDoLayout` the test runs.

https://github.com/MrFrankel/sample-app-angular-hybrid

**Comment by MrFrankel** [comment]
@seanlandsman  Hey, any news on this?

**Comment by seanlandsman** [comment]
Hi - sorry, I hadn't seen your update on 25 May

I've raised issue AG-616 our side to track this - I'll get to it as soon as possible

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
