### ISSUE TITLE
"No Rows" overlay is displayed when rowData set to null or undefined

### ISSUE THREAD

**Issue by rellis-of-rhindleton** [ag-grid/ag-grid#1665]
This is probably a bug? If not then maybe the docs just need to be tweaked.

**Current behavior**

`api.setRowData([])` --> no rows overlay  
`api.setRowData(null)` --> **no rows overlay**  

If rowData is null when the grid is first instantiated, the loading overlay is displayed.  But any time afterward setting rowData to null causes the no rows overlay to be displayed instead.

**Expected behavior**

`api.setRowData([])` --> no rows overlay  
`api.setRowData(null)` --> **loading overlay**  

**What is the motivation / use case for changing the behavior?**

The loading overlay is only automatically displayed for null rowData at instantiation, and that doesn't seem consistent. Of course using the api to manage overlays is simple and easy, but having setRowData(null) produce the loading overlay automatically would streamline my code even more.  :)

**Please tell us about your environment:**

Chrome on Windows 10. Both straight JavaScript and Angular 4/TypeScript. 

* **ag-Grid version:** 9.0.3, 10.0.1

* **Browser:** Chrome 58 
userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

* **Language:** ES5, TypeScript 2

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid we are not going to consider this for development, since as you mention, the overlay can be handled anyway through the api, and our perspective is that semantically null and [] represent the same for the grid (no data)

**Comment by noahrc** [comment]
If null and [] both represent no data, why does the behavior of null differ from [] when the grid is instantiated? It seems inconsistent and misleading to handle instantiation differently from later data changes. We initially set data to null in our grid, only to find out later that the loading state wasn't handled properly on state changes. It would be great if the loading vs. no data display behaved consistently and the hide and show methods weren't required.

**Comment by freewind** [comment]
Facing the same issue, have spent hours to figure out why the behavior is different

**Comment by raphaeltang** [comment]
if the data takes time to be retrieved, I do not want the grid to show user the no row overlay but the loading so the user knows it is being loaded. to display no row overlay when the data is being loaded is misleading.

**Comment by manish-hlth** [comment]
Hello @makinggoodsoftware , @rellis-of-rhindleton 

Though the API has the functions to show and hide the overlay, that doesn't seem to work when we programmatically set the `rowData` to null or undefined. Since `setRowData` internally hides any visible overlays. And, as a result, api call to show the overlay never displays the loading overlay on the page.

React code example:
```
setRowData(null);
gridApi && gridApi.showLoadingOverlay();
```
i am calling the show loading overlay, but it's never visible since `setRowData`  sets the grid's rowData to null and internally while updating the dataSource it hides the overlay.

Also, even if this works by applying setTimeout, page state won't be ideal as it'll show "No rows" on the grid and on top of that "loading" overlay, which is highly inconsistent.

Highly surprised to see this inconsistency.

Thanks,
Manish Kumar

**Comment by mkdudeja** [comment]
Hello @makinggoodsoftware , @rellis-of-rhindleton

Though the API has the functions to show and hide the overlay, that doesn't seem to work when we programmatically set the `rowData` to null or undefined. Since `setRowData` internally hides any visible overlays. And, as a result, api call to show the overlay never displays the loading overlay on the page.

React code example:
```
setRowData(null);
gridApi && gridApi.showLoadingOverlay();
```

I am calling the show loading overlay, but it's never visible since `setRowData` sets the grid's `rowData` to null and internally while updating the dataSource it hides the overlay.

Also, even if this works by applying setTimeout, page state won't be ideal as it'll show "No rows" on the grid and on top of that "loading" overlay, which is highly inconsistent.

Highly surprised to see this inconsistency.

Thanks,
Manish Kumar

**Comment by prostakov** [comment]
Hi

I've spent several hours as well...

`api.setRowData(null)` --> **should show loading overlay**.
`api.setRowData(undefined)` --> **should show loading overlay**.

`api.setRowData([])` --> **should show no rows overlay**.

Please consider reopening issue.

**Comment by divyagahlot99** [comment]
Having the same issue for hours. Don't know why this issue has been closed?

**Comment by yurakhomitsky** [comment]
Still have this issue when data is null.

Solved by using setTimeout

`setTimeout(() => {
          this.gridApi.showLoadingOverlay();
        });
      } else {
        setTimeout(() => {
          this.gridApi.hideOverlay();
        });`

**Comment by Gaspar1992** [comment]
I have the same bug with the latest version, why is it closed?

**Comment by AG-Zoheil** [comment]
Thank you to all those who have commented.

We are keen to look into this again, as you can see this is quite an old issue from 2017.

Although the grid has naturally advanced a lot since then, I can see from your comments that there are still some open questions. I have now reopened the issue, please allow us some time to evaluate and provide and update.

Much appreciated!

Kind regards,
Zoheil

**Comment by gandhis1** [comment]
It absolutely would. I ended up simulating this through a `useEffect` that calls into the grid API if my `loading` boolean changes. I wrapped that into a hook and use it everywhere.

**Comment by StephenCooper** [comment]
Thank you for all your feedback in this issue. We be updating the way our overlay works to simplify the workflow and make it more consistent.

By introducing a `loading` prop we will enable the loading overlay to be manually controlled irrespective of what rowData is being set to. 

You can track it with this reference:
AG-5497 [Overlay] Allow showing the loading overlay using a loading property

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!
