### ISSUE TITLE
Can not see pop-up editor components that protrude beyond the edge of the parent ag-grid.

### ISSUE THREAD

**Issue by kojisaiki** [ag-grid/ag-grid#1674]
(Sorry to my poor English.)

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
(I use ag-grid in Angular 2+.)
In the free plan (not in enterprise mode), I can not see pop-up editor components that protrude beyond the edge of the parent ag-grid-angular.

![image](https://cloud.githubusercontent.com/assets/10954150/26539656/a4748498-4488-11e7-9e69-78a74bb4fdbb.png)

The cause is style `overflow:auto` declared in css class `.ag-bl-full-height`.

**Expected behavior**
In enterprise mode, css class `.ag-bl-normal` is reflected instead of full-height one.
It does not declare `overflow:auto`.

So, by removing the style from `.ag-bl-full-height`, component will become visible all.

![image](https://cloud.githubusercontent.com/assets/10954150/26539900/b6918094-4489-11e7-9527-1a47ac6f241d.png)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

My original editor component is calendar.
Cause of cannot see a part of component, cannot select some dates.

![image](https://cloud.githubusercontent.com/assets/10954150/26540026/514a6006-448a-11e7-833a-ac4c72addae3.png)

**Please tell us about your environment:**

OS: Windows 7 64bit

* **ag-Grid version:** X.X.X

version: 9.1.0

* **Browser:**

Google Chrome 57.0.2987.133

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 2.0.3

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
