### ISSUE TITLE
render own checkbox but row selection checks it

### ISSUE THREAD

**Issue by jemantheiy** [ag-grid/ag-grid#1690]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a custom renderer on a cell that renders a checkbox input that when clicked it performs another action versus what the row selection does.  However, when a row is selected it checks the check box in that renderer.  This started when I upgraded from version 6 to 9.  I would expect the checkbox to trigger a row selection, but not the other way around.  I even have checkboxselection to false.  

**Expected behavior**

I expect if I have checkbox selection set to false and render my own component  that I can operate without ag grid changing any state.  

**Minimal reproduction of the problem with instructions**

create a cell renderer with a input type of checkbox, turn checkboxselection to false and enable row selection.  when you click the row, the checkbox is toggled to on.

**What is the motivation / use case for changing the behavior?**

we use the check box to set a default and row selection to select what option they want.  

**Please tell us about your environment:**

linux, node js, react
* **ag-Grid version:** X.X.X

9.1.0

* **Browser:**

crhome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
es6

**Comment by uvtzxpm** [comment]
Can you provide a demo, or some code?

You might just need an `event.preventDefault()` or `event.stopPropagation()` somewhere.

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
