### ISSUE TITLE
SizeColumnsToFit doesn't take borders in calculation

### ISSUE THREAD

**Issue by gama410** [ag-grid/ag-grid#1698]
**I'm submitting a ...
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I keep having a horizontal scrollbar on the grid after calling sizeColumnToFit. I have defined my own styles which add a border to the "ag-body-container class". When I remove these borders, the scrolls disappears so I suppose the width calculation doesn't take into account the borders...

**Expected behavior**
Not to have a scrollbar when using sizeColsToFit

**Minimal reproduction of the problem with instructions**
Add a border to the class ag-body-container and call the sizeColsToFit function

**What is the motivation / use case for changing the behavior?**
I causes an unnecessary horizontal scrollbar on the grid

**Please tell us about your environment:**
Windows 10, VSCode, NPM 5.0.3, Node 7.7.4

* **ag-Grid version:** X.X.X
ag-grid-aurelia 9.1.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.137 YaBrowser/17.4.1.919 Yowser/2.5 Safari/537.36"

* **Language:** 
Typescript 2.2

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
