### ISSUE TITLE
Ag-grid infinite scrolling, getRows params startRow and endRow are negative

### ISSUE THREAD

**Issue by dmngu9** [ag-grid/ag-grid#1742]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

- getRows params startRow and endRow are negative

**Expected behavior**

- startRow and endRow should not be negative.

**Minimal reproduction of the problem with instructions**

- I have infinite scrolling with Ag-grid working but i encounter a rare bug. If i hold 'page down' key to scroll down the table, while the data is still loading, I immediately 'page up' to scroll to the top and keep 'page up' key pressed, error shows that startRow and endRow is negative which causes request to database fail

![capture](https://user-images.githubusercontent.com/12367690/27845861-2f68e8c8-6176-11e7-99e1-832318f20f58.PNG)

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this - I've raised issue AG-590 our side to track this, but we'll update this thread with updates as soon as we have any

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by sbrice** [comment]
Hi - 
I'm still having this issue and cannot locate AG-590 in your pipeline. My package.json says...
"ag-grid": "^17.0.0",
"ag-grid-angular": "^17.0.0",
"ag-grid-enterprise": "^17.0.0",
