### ISSUE TITLE
Ctrl-Enter resets cell editor to blank in Chrome

### ISSUE THREAD

**Issue by Ellisthion** [ag-grid/ag-grid#1752]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Pressing control-enter in an editor clears the cell content and doesn't close the editor.

The control-enter triggers a keypress event after the keydown (which is closing the editor, as expected). CellComp.onKeyPress reads the charCode as 10 (instead of 13 for 'enter'), which is processed as a \n character.  This goes to Utils.isEventFromPrintableCharacter which incorrectly classifies the \n as printable. Then, because the user has 'input' a 'printable' character on a cell that's _not_ editing, it starts editing, using \n as the initially typed character.

**Expected behavior**
Pressing control-enter saves the changes normally and closes the editor

**Minimal reproduction of the problem with instructions**
Edit any basic text cell, type something, and hit control-enter. This is reproducible in the current live ag-Grid demo page.

**What is the motivation / use case for changing the behavior?**
I was trying to write a custom keyboard shortcut to make ctrl-enter fill all cells in the selected range (as per Excel). However, the source cell gets its value wiped.

**Please tell us about your environment:**
* Windows 7

* **ag-Grid version:** 11.0.0

* **Browser:**
Broken in Chrome 59
Works in Internet Explorer 11
Works in Firefox 54

* **Language:** all

**Comment by seanlandsman** [comment]
Hi,

Thanks for this - I've raised issue AG-605 our side to track this. We'll update this thread with updates as soon as we have any

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by JohnMasterson** [comment]
Just to confirm this was included in Version 15 which was released last week.

https://www.ag-grid.com/ag-grid-blog-15-0-0/

Regards, 

John
