### ISSUE TITLE
Loading overlay does not prevent clicking on rows, columns, filter buttons, etc.

### ISSUE THREAD

**Issue by VyvIT** [ag-grid/ag-grid#1755]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Loading overlay does not prevent clicking on rows, columns, filter buttons, etc.

**Expected behavior**
Loading overlay does should prevent clicking on rows, columns, filter buttons, etc.

**Minimal reproduction of the problem with instructions**
Go to [examples page](https://www.ag-grid.com/javascript-grid-overlays/?framework=react#gsc.tab=0) and click 'Show loading overlay'.
While overlay is active, user can click through overlay on row cells, reorder columns, apply filters, etc.
-->

* **ag-Grid version:**  Current

* **Browser:**
Chrome latest

**Comment by seanlandsman** [comment]
Hi,

i've raised a feature request for this our side AG-614. We'll update this thread with updates as soon as we have any

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by jayrungta** [comment]
Was this issue resolved? Can't find AG-614 anywhere on https://www.ag-grid.com/ag-grid-pipeline/
