### ISSUE TITLE
Grid option domLayout set to autoHeight causes detail component to be instantiated many times

### ISSUE THREAD

**Issue by gregbown** [ag-grid/ag-grid#1763]
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 
```

**Current behavior**
When using a Master/Detail component, setting the grid option domLayout to 'autoHeight', expanding a row will cause the detail constructor to run many times.  If the setting is removed, the  detail constructor will run only once as it should.

**Expected behavior**
A component constructor should run only once.

**Minimal reproduction of the problem with instructions**
When loaded the preview has the setting domLayout: 'autoHeight', so clicking on an athlete name cell will cause the described behavior. (See console logs) If one comments out the domLayout setting the same action will run the detail constructor only once as it should.
[See plnkr](https://plnkr.co/edit/S94PxG?p=preview)

**What is the motivation / use case for changing the behavior?**
If populating a detail with additional data, the data will be requested every time a component is created, causing unnecessary load and poor performance. Using the auto height feature described [here](https://www.ag-grid.com/javascript-grid-width-and-height/?framework=vue#gsc.tab=0) resolves having to manually calculate grid height every time a change is made.

**Please tell us about your environment:**
Windows 10, Chrome Version 56.0.2924.87, Angular 4.3.0, Typescript 2.4.1, Webpack 3.3.0, Node 6.10.2, npm 4.0.2, ag-Grid 11.0.0, ag-Grid Angular 11.0.0

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this -  I've raised AG-626 our side for this. We'll update this thread with updates as soon as we have any.

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by gregbown** [comment]
Not clear on the value of enterprise or posting bugs with ag-grid.  Things labeled as bugs remain despite 5 major releases and 6 months.  If more than one row is open the constructor of each open row is called three times. I took a few minutes to check the so called pipeline to no avail.
