### ISSUE TITLE
multi-column sorting with ctrl

### ISSUE THREAD

**Issue by ataft** [ag-grid/ag-grid#1767]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request 
```

**Current behavior**
Multi-column sorting is currently done with the Shift key

**Expected behavior**
I'm not sure about international standards, but the standard multi-select key is CTRL, not SHIFT. Perhaps this is something that could be configurable?

**What is the motivation / use case for changing the behavior?**
The CTRL key is a standard for multi-select. SHIFT is reserved for selecting everything in between the 2 items clicked...

**Please tell us about your environment:**
All

* **ag-Grid version:** X.X.X
11.0.0

* **Browser:**
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-677 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
