### ISSUE TITLE
no changes to column state should not return undefined when using getColumnState()

### ISSUE THREAD

**Issue by Dmon1Unlimited** [ag-grid/ag-grid#1769]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
 I have a react app that uses ag-grid. The sorting, filters as well as column state are exported onto server (I.e using your getFilterModel() command to save to a variable, and then send that data to server). This data is imported back at the start of the user session. For new users, who haven't exported their preferred filter/sort/columns state, what is imported back by default will be empty

I am effectively using getFilterModel() to get data, send it to server, and setFilterModel() to import from server and apply to grid.

with no filter/sort/column state set, what is exported is:
empty object for filter
empty array for sort
undefined for column state

when importing this empty data back, the empty object and array work fine with setFilterModel(), setSortModel(). but because column state is undefined, I will get an error when setting column state

**Expected behavior**
if there are no column changes, then obtaining column state via getColumnState() should work the same way as filter and sort (i.e. get an empty object or array). Hence applying an empty object/array via:
getColumnState( {} or [] )  should not throw an error

**Minimal reproduction of the problem with instructions**

It is a bit difficult to provide a minimal example with all my code.
but on ag-grid, with no changes to column state, call let temp = this.state.gridOptions.columnApi.setColumnState();

this should return undefined
then run this.state.gridOptions.columnApi.setColumnState(temp);
to cause error

do the same thing with getFilterModel and getSortModel, and you wont run into any issues

**What is the motivation / use case for changing the behavior?**
 more stable code. at the moment, I'm using an if statement to check if the column state is undefined (and only set column state if it is not undefined). An if statement shouldn't be needed just like it is not needed for filter or sort 

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**
 Chrome/Internet Explorer 11 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
