### ISSUE TITLE
Unable to right click on the hamburger menu filter

### ISSUE THREAD

**Issue by Keki91** [ag-grid/ag-grid#1787]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This happens on all browsers I've tested. (IE11, Firefox 54 and Chrome 59)

1. Open up filter hamburger menu
2. Attempt to right click on text box.
3. Filter menu will close and show a standard context menu

_Clicking in the textbox and using CTRL+V works correctly, but we've had a request from non-technical end users who don't know shortcuts._

**Expected behavior**
1. Open up filter hamburger menu
2. Attempt to right click on text box.
3. Standard textbox paste should be visible.

**Minimal reproduction of the problem with instructions**

Repro steps above work on any free grid - also enterprise demo on the AG Grid website when using hamburger option.

**What is the motivation / use case for changing the behavior?**

Support standard functionality within a browser

**Please tell us about your environment:**

Windows, any browser

* **ag-Grid version:** 11.0.0

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"

"Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; Tablet PC 2.0; rv:11.0) like Gecko"

* **Language:** all

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-655 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
