### ISSUE TITLE
Total Footer Row

### ISSUE THREAD

**Issue by ataft** [ag-grid/ag-grid#1791]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request
```

**Current behavior**
The concept of a grand total header/footer row was brought up originally in issue #45, which brought about the floating footer (now called Pinned Bottom Row). This worked OK when ag-grid didn't have pivoting and the built-in aggregation. However, with all the new features in ag-grid, implementing a total footer is difficult, prone to errors, and very susceptible to breaking changes in new releases.

If you want to create a total footer row as a Pinned Bottom Row, then you have to implement all of the aggregate functions. Aside from being a duplicated effort, data integrity is a concern. You also have to implement new renderers, rather than just interiting the column's original renderer.

Also, as pointed out in issue #1790, it doesn't appear as if you can create a total footer row when pivoting. 

**Expected behavior**
Set "gridOptions.enableTotalFooter = true;" to create a total footer row that uses all the default colDef.aggFunc's. We would still need control over the total aggregate function or renderer for some cases, e.g. when the row-level detail and total aggregates are average or count distinct.

**What is the motivation / use case for changing the behavior?**
I spent a lot of time implementing a custom pivot and total footer row in ag-grid 8.0. Migrating to 12.0.2 is now a huge task since there's no standardization around the total footer row concept. I would expect many or most ag-grid users show total footer rows, but all implement it in different ways. Since ag-grid does not know how people are implementing this, it's probably breaking in different ways for others as new releases come out. Pinned Bottom Rows are a good and necessary feature, but a default out-of-the-box Total Footer Row is necessary for many reasons.

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-678 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by leyryan33** [comment]
I would also benefit from having some sort of simple grid option to turn on a totals row as I am trying to have a totals row show up for a pivot table, so hopefully this gets into an upcoming release of ag-grid.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by adharbert** [comment]
Is this feature active now?  I see the pinned row, but nothing on how to show a column total

**Comment by pavanmehta91** [comment]
is that done?

**Comment by spiko-md** [comment]
> Thanks for raising this. I've raised AG-678 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

> We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

A search for AG-678 on the mentioned page produces no results, and this feature is not working either.

**Comment by francisu** [comment]
For anyone looking here, this article might help: https://ag-grid.zendesk.com/hc/en-us/articles/360015979971

**Comment by tielushko** [comment]
@francisu, I am unable to see the article, I think it's locked behind the enterprise support. I was wondering if you  would be able to post a sandbox by chance?

**Comment by tielushko** [comment]
@RuneSP Thanks for reaching out to me and sending a sample! I will give this one a try.
