### ISSUE TITLE
Custom Cellrenderer not refreshed when using virtual Rows

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#1800]
I've a custom cell renderer defined, and use virtual row model.

With the newest ag grid version, I've the problem that the custom cellrenderer is called, when the data is not arrived from the server. (params.data == undefined).

When I now scroll the rows out of the view, and then back, the custom cell renderer is called again with data, and the rows are shown. This did work before aggrid update, without scrolling out of view.

Maybe the problem is, that we set the count of rows, before the first data arrives (this is our first request)

**Comment by jogibear9988** [comment]
I've now tried. If I remove this.gridOptions.api.setInfiniteRowCount or if I move that call after setting the first data it works.
But it worked this other way before...

**Comment by jogibear9988** [comment]
Also when you use the Scrollbar and Move the Thumb via the Mouse, the values are not refreshed...

**Comment by seanlandsman** [comment]
Hi

If you have a repo that we can look at that illustrates this problem we'll be happy to take a look at this issue

**Comment by jogibear9988** [comment]
I'm looking to find a small example wich is not workin... It's not a so easy task...

**Comment by jogibear9988** [comment]
@seanlandsman atm i'm not able to create a small example. when I look into the code, I see, that I have not specified a valueGetter for the column, so the ValueService.getValue always reads undefined for the column.
and so the refreshCell call always has skipRefresh set to true.

So my data is only visible, when the CellRenderer has its data before it is executed.

Maybe we need a property that a cell should always be refreshed?

**Comment by jogibear9988** [comment]
if I implement valueGetter for the Column Definitions it works...

but I read the values like this:

            _deepValue(obj, path) {
                for (var i = 0, path = path.split('.'), len = path.length; i < len; i++) {
                    if (obj != null)
                        obj = obj[path[i]];
                    else
                        return null;
                };
                return obj;
            }

and 

    valueGetter: (p) => this._deepValue(p.data, memberName + "." + childMemberName),
                               
because I use complex objects. so this will affect performance

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by vepanimas** [comment]
@makinggoodsoftware, @jogibear9988 I faced the same issue. I use an Angular component for a custom CellRenderer. If I set `api.setInfiniteRowCount` to a non-zero value, a column with that renderer will be rendered unstable, because `params.data` would be undefined. I'll try to reproduce that, but for now I don't have any idea how to achieve that.
