### ISSUE TITLE
How to set tooltip for a column group header?

### ISSUE THREAD

**Issue by dereklin** [ag-grid/ag-grid#1807]
https://www.ag-grid.com/javascript-grid-column-properties/#gsc.tab=0

There is a way to set the column header tooltip, and there is a way to set tooltip even for the cell.  How to set tooltip for a column group header?

**Comment by dereklin** [comment]
Implemented a custom group header for now.  I think group header should just accept headerTooltip just like regular column headers

**Comment by seanlandsman** [comment]
Thanks for the PR - we have an issue open for this already (AG-393) but I'll make a note of the PR you've submitted and raise it with the team

We'll update this thread with updates as soon as we have any.

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by abu2sid** [comment]
Hi,
wanted to check if you had any update on this?
I need a custom tooltip which should work with an overflowing grid. 
https://plnkr.co/edit/kyE4JZ?p=preview
