### ISSUE TITLE
Wrong immutable.js compare

### ISSUE THREAD

**Issue by barriber** [ag-grid/ag-grid#1813]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
createTransactionForRowData compare immutable js with regular '!==' 
should use equals instead 

**Expected behavior**
should use equals instead 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 11.0.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
I'm afraid I'm not sure what you're referring to here

Is this the line you think is incorrect?

let dataHasChanged = existingNode.data !== dataItem;

If so, what makes you think it's wrong? 

thanks

**Comment by barriber** [comment]
I had 2 immutable.js objects that's for statement of  existingNode.data.equals(dataItem) returned true but if you compare existingNode.data === dataItem it returns 'false'

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
