### ISSUE TITLE
Infinite Scrolling stops working on about 1.3 Million rows

### ISSUE THREAD

**Issue by amir-alic** [ag-grid/ag-grid#1819]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Infinite Scrolling stops working on about 1.3 Million rows (my test is with 3 million rows)
Plunkr: https://plnkr.co/edit/RtbZlDQaU4iCKov0uDbG?p=preview

**Expected behavior**
I have a requirement to support up to 30 million rows.

**Minimal reproduction of the problem with instructions**
Just a basic Infinite Scrolling, clear example in Plunkr.

**What is the motivation / use case for changing the behavior?**
Correct behavior.

**Please tell us about your environment:**
Ag-grid in AngularJS

* **ag-Grid version:** 12.0.2

* **Browser:** Chrome

* **Language:** JavaScript

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-601 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
