### ISSUE TITLE
Posibility to Modify Header (add a remove column button)

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#1824]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
we have no possibility to modify

**Expected behavior**
I'd looking for a way, so I can change the header, to add a remove column button!

**Comment by scottkunkel** [comment]
look at getMainMenuItems
you can do something like this:
```
return function(params){
  items.push({
    name:'Remove',
    action:() => {
      callFunctiontoHideColumn(params.column);
    }
  });
}


```

**Comment by jogibear9988** [comment]
i do not use the mainmenu. i'd like to include a "x" button directly in the header.

maybe a columnHeaderTemplate fuction? like celltemplate.

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
