### ISSUE TITLE
filter lessThanOrEqual shows incorrect value

### ISSUE THREAD

**Issue by sklyarov-ivan** [ag-grid/ag-grid#1826]
**I'm submitting a ...** 
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
https://www.ag-grid.com/javascript-grid-filtering/#filter-and-events-example&gsc.tab=0
sort by Age column with filter value lessThen 15 gives me 5 records with empty age value (it is normal behavior)
sort by Age column with filter value lessThanOrEqual 15 gives me 18 records BUT records from 1st request isn't exist there

**Expected behavior**
1st request - returns 5 records
2ns request - returns 23 records (15 matches criteria == 15 and 5 matches criteria < 15)

**Environment:**
Ubuntu 16.04
Chrome 60.0.3112.78 (Official Build) (64-bit)

* **ag-Grid version:** 8.1.0
* **Language:** ES6, React

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-685 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
