### ISSUE TITLE
getRowClass is not called when row data is updated in deltaRowDataMode

### ISSUE THREAD

**Issue by SamuelBeliveau** [ag-grid/ag-grid#1836]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
1. Define a getRowClass function to apply css classes based on row data.
2. Set grid deltaRowDataMode to true.
3. Initialize grid with rows (getRowClass will be called)
4. Update one of the rows data (getRowClass is not called)

**Expected behavior**
getRowClass to be called, since it could very well depend on the row data to display css classes.

**Minimal reproduction of the problem with instructions**
See current behavior section.

**What is the motivation / use case for changing the behavior?**
I'd like to add a strikethrough line over the whole row based on row data attributes. These attributes could change over time, so I would expect the row to change based on that.

* **ag-Grid version:** 10.1.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

* **Language:** Typescript 2.3.4

**ADDENDUM** 
I know it has been discussed here: https://github.com/ag-grid/ag-grid/issues/1264, but I think that the addition of rowDeltaDataMode makes it really easy to trip on the bug. I don't want to go in the `cellClassRules` route, as it would be cumbersome to do so.

For the time being, I'll have to set rowDeltaDataMode to false and sadly go without the performance improvements.

**Comment by seanlandsman** [comment]
I've raised this with the team and we agree that this could & should be easier to use - we've raise AG-698 to track and cover this.

You can see the status of this here: https://www.ag-grid.com/ag-grid-pipeline/

**Comment by SamuelBeliveau** [comment]
Perfect, thank you.

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by jmwolfe** [comment]
@seanlandsman you commented that AG-698 was submitted, but its not in the changeLog or the backLog and it appears to still be an issue in ag-grid-angular 28.1.1  (in Angular 14.0 if it matters)
