### ISSUE TITLE
domLayout: 'autoHeight' does not work correctly if there are pinned columns

### ISSUE THREAD

**Issue by alesdrobysh** [ag-grid/ag-grid#1839]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If `domLayout: 'autoHeight'` is set and there is a pinned to the right then I am not able to scroll the page if the mouse pointer is over not pinned part of the table.

**Expected behavior**

I expect I am able to scroll the page when the mouse is over any part of the table.

**Minimal reproduction of the problem with instructions**

https://codepen.io/alesdrobysh/full/qXmpvB/

In the example above when the mouse is over  "Parent column" data cells then the page is not being scrolled.

**Please tell us about your environment:**

* **ag-Grid version:** 12.0.2

* **Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

* **Language:** ES5

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-702 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by JohnMasterson** [comment]
Just to confirm this was include in Version 15 which was released last week.

https://www.ag-grid.com/ag-grid-blog-15-0-0/

Regards, 

John
