### ISSUE TITLE
Theme cannot apply to Angular application when used in component style

### ISSUE THREAD

**Issue by Teamop** [ag-grid/ag-grid#1878]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm using angular-cli. If I want to use the theme, the only way is that put the theme in the .angular-cli.json, otherwise, put it in component styles, the theme just doesn't work.

**Expected behavior**

When import the theme in the component styles, the theme can still work.

**Minimal reproduction of the problem with instructions**

I have tried with the example application with angular-cli (https://github.com/ag-grid/ag-grid-angular-example/tree/master/angular-cli)

**What is the motivation / use case for changing the behavior?**

Just want to use ag-grid in some module, so don't want to import ag-grid theme in the whole stylesheet.

**Please tell us about your environment:**

* **Operating system:** win 7

* **Package manager:** npm 5.3

* **Angular version:** 4.3.6

* **ag-Grid version:** 13.1.0

* **Browser:** chrome, firefox

* **Language:** [TypeScript 2.4.2]

**Comment by petyosi** [comment]
The problem you describe is due to the way scoped styles work in Angular. Since ag-Grid is agnostic to the platform and creates DOM elements not through the Angular 2 API, the scoping attribute does not work for its contents. 

One way to work around the problem would be through the ::ng-deep selector:

```scss
$ag-icons-path: '~/ag-grid/src/styles/icons';

:host /deep/ {
    @import "~ag-grid/src/styles/ag-grid.scss";
    @import "~ag-grid/src/styles/theme-fresh.scss";
}
```

this seems to work when I tested it. Notice however, [that /deep/ and ::ng-deep is deprecated](https://angular.io/guide/component-styles).
