### ISSUE TITLE
Infinite scrolling not working appropriately when lastRow/item count is too large

### ISSUE THREAD

**Issue by jfuehner** [ag-grid/ag-grid#1887]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using infinite scrolling with the latest ag-grid (13.1.0) the grid behaves oddly when the row count passed into the successCallback is too large. If I call successCallback providing a lastRow/item count of 11,921 as an example things behave as expected. 

However, if I call the successCallback providing a lastRow/item count of 24,716,740 the scroll bar appears expanded as though there are not many items in the list. Additionally, when I start scrolling the grid acts as though infinite scrolling is trying to work as it will load new items but, when new items are loaded the scroll bar will jump to the top. Ultimately, this behavior never allows the user to scroll correctly...

**Expected behavior**
Would expect the infinite scrolling to behave regardless of the item count passed.

* **ag-Grid version:** 13.1.0

* **Browser:**
FireFox 38.1 & FireFox 52.1.1

**Comment by rmc-software** [comment]
Hi,

This isn't related to infinite scrolling but rather a limit imposed by browsers on the maximum div height. When this is exceeded scrolling will not work correctly.

As such this is not something we can address with ag-Grid.

**Comment by jfuehner** [comment]
I see, wouldn't it be reasonable when the max is reached you set the scrollbar to the maximum possible? Seems like that would be more acceptable than the behavior that is occurring currently...

**Comment by rmc-software** [comment]
I've discussed this with the team and we have accepted this enhancement and selected it for developement. Tracked by AG-748

**Comment by jfuehner** [comment]
Any ETA on when this issue will be addressed?

**Comment by jfuehner** [comment]
@rmc-software any ETA on this enhancement?

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
