### ISSUE TITLE
ag-grid Memory Build-up (Standard/Plain JavaScript)

### ISSUE THREAD

**Issue by jfuehner** [ag-grid/ag-grid#1891]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

Current behavior
I originally opened issue #1868 when using ag-grid with AngularJS. Said ticket was marked as a duplicate based on #1234. In reviewing #1234 it was recommended to try using ag-grid with plain JavaScript. I have since switched to using plain JavaScript and additionally upgraded to the latest version of ag-grid. In doing so I have seen a longer run-time before the browser crashes; however the browser still crashes.

Using plain JavaScript with the latest ag-grid I have seen my app's run-time go for as long as ~2 days before the browser crashes.  I am using ag-grid for an application where data is continually loaded into the grid. I've noticed that the FireFoxes memory slowly builds over time and will cause the browser to crash.

Starting the app yesterday (05-SEP) at ~1:15 EST the app started with memory allocation of ~115MB. The app this morning (06-SEP) at ~5:45 EST is now consuming ~800GB of memory. We load ~500 rows every 15 seconds or so; the grid has 22 columns, 2 of which utilize cellRenderer's but are only rendering icons in the cells.

Expected behavior
I would expect the browser not to crash...

    ag-Grid version: X.X.X
    ag-grid 13.1.0

    Browser:
    FireFox 38.1.0 and FireFox 52.2.0

**Comment by makinggoodsoftware** [comment]
Hi,

For security reasons moderm browsers have a cap on the maximum amount of memory they can allocate, this is so websites can not suck all of your computer memory just for the sake of it.

This also means that if you have a webapp that adds more data into the app as time goes by, the browser is going to crash.. Unfortunately there is no workaround here, but I am afraid this is not an ab-grid issue but a browser one.

I am going to close this since I can't see how can we help you I am afraid. All I can suggest is that you dont incrementally load more data in your app... Could you change your logic so that after a while you start to unload data ?

Hope this helps
