### ISSUE TITLE
Clear button doesn't respect with filterOptions

### ISSUE THREAD

**Issue by cdumas22** [ag-grid/ag-grid#1894]
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 

When you have the specific settings for a column
{
  filter: 'text',
  filterParams: {
    clearButton: true,
    filterOptions: ['equals'],
    defaultOption: 'equals'
  }
}

Issue 1 - The dropdown starts out as empty if you dont put defaultOption, and the filter defaults to contains. 
Issue 2 -  when you click the clear button it will switch the filter to contains even though that is not in the list of available values.

I would expect the filterOptions to only allow options specified in the passed in parameter and to default to the correct default filter type on clear.

* **ag-Grid version:** 13.1.0

**Comment by makinggoodsoftware** [comment]
Hi,

We have created AG-759 to track this issue this should be fixed in the next one or two releases.

Thanks for raising this.

**Comment by killyosaur** [comment]
As an FYI, if I change the data in the grid, the filter options are not being respected either.

**Comment by killyosaur** [comment]
A further dive into this bug (at least as far as I am seeing in our situation, but it might help determine what the underlying issue is), when the filter initializes, the filterParams are applied correctly. When a change is made to the grid, these are ignored on subsequent requests. So in our situation, if I haven't opened the filter yet, then changing the grid data does not affect the way the parameters are applied. Only after initialization is this an issue.

**Comment by seanlandsman** [comment]
Thanks for the follow up - I've raised it as a comment to the issue above

**Comment by makinggoodsoftware** [comment]
Hi,

Just to let you know that we have just delivered 13.3.1 which includes fixes related to this thread, for the full change log please check:

https://www.ag-grid.com/change-log/changeLogIndex.php

Thanks
