### ISSUE TITLE
onFilterChanged not in ifilter ts definition

### ISSUE THREAD

**Issue by jfstephe** [ag-grid/ag-grid#1896]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
onFilterChanged (shown in examples [here](https://www.ag-grid.com/javascript-grid-filtering/#gsc.tab=0)) is not in the type definition for ifilter.

**Expected behavior**
It should be

* **ag-Grid version:** Latest

* **Language:** [Typescript]

**Comment by seanlandsman** [comment]
onFilterChanged lives on the api, not on iFilter


thanks

**Comment by jfstephe** [comment]
Sorry, this was partly my fail and partly Visual Studio Codes...

It's not on 'IFilterComp', not IFilter:

        let filterComponent = this.gridOptions.api.getFilterInstance(filterParams.colKey);
        filterComponent.setModel(filterParams.filterModel);  // THIS LINE IS OK
        filterComponent.onFilterChanged();   // THIS LINE SHOWS onFilterChanged() doesn't exist on IFilterComp

Can you re-open please?

**Comment by seanlandsman** [comment]
Hi

That mehtod is a method I use in our internal BaseClass for filtering, and is not part of our published API.

You are assuming that whatever you retrieve through gridOptions.api.getFilterInstance(filterParams.colKey); is an instance of ag-grid BaseFilter but this is not the case when  using custom filters, which is why it's not on IFilterComp. It's not really for public consumption.

The safest approach is to call the this though the API 
thanks

**Comment by jfstephe** [comment]
Cool. Thanks for clarifying. I've changed to using the api method and things are less 'red' :-). Can I suggest changing the example (linked in the original post) to reflect this?

**Comment by seanlandsman** [comment]
I see what you mean - thanks

I've updated the docs to use the API instead of the component method

thanks for the feedback

**Comment by seanlandsman** [comment]
I see what you mean - thanks

I've updated the docs to use the API instead of the component method

thanks for the feedback

**Comment by jfstephe** [comment]
thanks :-)
