### ISSUE TITLE
Group rows using Flower nodes and Full Width Row is not working

### ISSUE THREAD

**Issue by skow4** [ag-grid/ag-grid#1904]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We are using the enterprise version of AG Grid with VueJS.
When using 'group' cellRenderer and returning true in the 'doesDataFlower' gridOption, the row is not able to be expanded.

**Expected behavior**
When using 'group' cellRenderer and returning true in the 'doesDataFlower' gridOption, the row should be able to be expanded.

Note that this functionality works in AG Grid version 9.1.0, but does not work when using the latest version.

**Minimal reproduction of the problem with instructions**
Create an AG Grid using the latest version of AG Grid
In gridOptions, create a property called 'doesDataFlower', which is a function. always return true.
In column definitions, specify a column that uses the 'group' cellRenderer

**What is the motivation / use case for changing the behavior?**
The current functionality isn't working as expected

**Please tell us about your environment:**
We use VueJS and AG-Grid Enterprise

* **ag-Grid version:** 9.1.0

* **Browser:**
Chrome, IE, Friefox

* **Language:** ES6

**Comment by seanlandsman** [comment]
Hi

Are you able to provide a repro for this?  If you want to you can do this in the Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

thanks

**Comment by instantaphex** [comment]
@skow4 I'm not sure if this will help, but I was having the same issue and was able to resolve it.  My setup is slightly different (Angular 5), but I was adding the doesDataFlower function after the gridReady event.  At one point this worked for me, but stopped at some point after some ugprades to ag-grid.
  After debugging through ag-grid source I realized that ag-grid was using that function when building the row nodes and that if it wasn't set before grid initialization, it wouldn't work.  Once I made sure the function was set before initialization of the grid, it worked perfectly.

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by lukeyt** [comment]
For anyone else stumbling on this trying to upgrade from an old version - the solution for me was that previously I was using a field that was not assigned to a value in my table data and this worked.  In the newer versions you need to use a field that exists in your row data.
