### ISSUE TITLE
Sorting Entire Row Groups

### ISSUE THREAD

**Issue by scottkunkel** [ag-grid/ag-grid#1907]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Unable to sort by group when setting
gridOptions.groupUseEntireRow = true;

**Expected behavior**
Clicking on the column should sort the grouped column as well

**Minimal reproduction of the problem with instructions**
https://www.ag-grid.com/javascript-grid-grouping/exampleGroupRowRendering.html
when allowing sorting on Country, clicking on the country should sort the existing group.
Alternatively allow a way to sort the groups

**What is the motivation / use case for changing the behavior?**
Ordering random data

**Please tell us about your environment:**
webpack

* **ag-Grid version:** X.X.X
13.1.2

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. Issue AG-732 has been raised our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by scottkunkel** [comment]
The issue cannot be found in the pipeline

**Comment by crarau** [comment]
@scottkunkel is the issue fixed or we don't know?

**Comment by scottkunkel** [comment]
No progress has been made on this issue.

**Comment by AndrewMoore10** [comment]
For anyone looking for this, here is what helped me: `defaultGroupSortComparator`
https://www.ag-grid.com/vue-grid/grouping/#default-group-order
