### ISSUE TITLE
colDef.cellRenderer ignored for PivotMode columns

### ISSUE THREAD

**Issue by ataft** [ag-grid/ag-grid#1913]
From the ag-grid demo page when pivoting the "Bought" column, you can see (highlighted in yellow) that the cellRenderer is ignored:

![image](https://user-images.githubusercontent.com/11670864/30387255-d0c34bfc-9860-11e7-8d80-7f77a962c74e.png)

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-786 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by ataft** [comment]
OK, I've opened a Zendesk ticket for this item so that I can be notified when it's complete. I don't like the process of checking the pipeline because then I have manage all the bugs and feature requests. If you're moving away from Github, you should figure out a way that people can subscribe to items in the pipeline...
