### ISSUE TITLE
The column header always be dragged

### ISSUE THREAD

**Issue by BrianHuGit** [ag-grid/ag-grid#1919]
**The column header always be dragged even though left key has already released**

![peek 2017-09-15 17-45](https://user-images.githubusercontent.com/9028425/30476873-f21a703a-9a3d-11e7-9575-20585fea81d1.gif)
note that there is a little tools on the left bottom corner shows the key I pressed

**Current behavior**
column always stuck on the cursor

**Expected behavior**
column header should be released after mouse left key up

**Minimal reproduction of the problem with instructions**
1. open the browser to access ag-grid official page https://www.ag-grid.com/example.php
2. press "crtl + a" to select all
3. drag the marked text, and release the text on a column header
4. mouse down to try to drag that column header
5. do not release the lef key, move the cursor to other place then release
6. the column header will stuck on the cursor

**Please tell us about your environment:**
I have already test different platforms and browsers, all of the combination have same issue.
Platform: Ubuntu, Windows, OS X
Browser: Chrome, Firefox, Safari

* **ag-Grid version:** X.X.X
Same as the official web version.
https://www.ag-grid.com/example.php

**Comment by john-hu** [comment]
We use click on any place to get rid of this issue.

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-827 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid that we have rejected this since it is too much of an edge case

Sorry for all the trouble

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
