### ISSUE TITLE
Keycreator gets a null value when getNodeChildDetails-Function is provided

### ISSUE THREAD

**Issue by web265p3** [ag-grid/ag-grid#1921]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Because I want to use expandable rows, I had to implement the getNodeChildDetail-Function:
```

    public getNodeChildDetails(record) 
    {
        if (record.Id) 
        {
            return {
                group: true,
                // the key is used by the default group cellRenderer
                key: record.Id,
                // provide ag-Grid with the children of this group
                children: [record.Id],              
                expanded: false
            };
        } 
        else 
        {

        }
    }
```
This works fine, but I figured out, that now a keyCreator I use for a "set"-filter does always retrieve null for the _value_ attribute of the params parameter.
This leads to the problem, that I can use either a set filter or expandable columns. But I need both features in my ag grid.

**Expected behavior**
Set the value attribute of the key creators params property to the current cell value.

**Minimal reproduction of the problem with instructions**
Just try to use a set filter, and an expandable row in one data table. 

**Please tell us about your environment:**
Angular 4

* **ag-Grid version:** 13.1.2

* **Browser:**
Chrome, IE 11

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
