### ISSUE TITLE
Popup editors aren't updating their position while the grid is scrolling

### ISSUE THREAD

**Issue by stephanjust** [ag-grid/ag-grid#1931]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting (could be intended)
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Popup editors are using absolut placement values within the grid that aren't updated upon scrolling. This means when focusing a cell with a popup editor and scrolling afterwards, the editor won't be above the original renderer anymore.

**Expected behavior**
Popup editors should behave exactly like non-popup editors regarding their placement and stay exactly at the spot where the original renderer was.

**Minimal reproduction of the problem with instructions**
https://www.ag-grid.com/javascript-grid-cell-editor/#gsc.tab=0
Your cell editing demo shows that quite well. Compare the behavior of the age and the gender/mood columns. The age column isn't a popup and scrolls out of the visual space even when focused. Gender/mood stay at their absolut position, leaving the original renderer visible.

**What is the motivation / use case for changing the behavior?**
A consistent behavior between popup editors and normal ones. Our popup renderers are dropdowns and date pickers whose base input field overlays the CellRenderer exactly, allowing for the illusion that they appear to be inside the cell.

* **ag-Grid version:** 10.0.1
Assuming your demos are up to date it's still happening

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-824 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are now changing the process and closing all items in github that have a ticket number since they can be tracked in our pipeline.

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by davidwneary** [comment]
Hi,

I'm getting the same error - has this been fixed in a recent release? 

I'm a little confused because from the pipeline, it looks like it's still in the backlog but the example here: https://www.ag-grid.com/example-angular-material-design/#example-material-design-1 looks like it has been fixed.

I'm on `19.0.0` and I'm experiencing the same issue.

Thanks

**Comment by davidwneary** [comment]
Scrap that - I've just seen it's because it's the page that's scrolling in the linked example, not the table itself. Do you know if this will be fixed any time soon?

**Comment by Rishanthakumar** [comment]
Hi,
Any update on this issue? I'm experiencing the same issue. 
Any help would much be appreciated.

**Comment by sachinshettigar** [comment]
@seanlandsman do you have any updates on when this feature will be added?

**Comment by 6apc1k** [comment]
Hello, are there any updates on this issue?

**Comment by likhitgatagat** [comment]
Hello,

any update on this issue? Issue is still there on latest avaialble release.

**Comment by spyro2000** [comment]
Same here. Popup is not fully visible but partly rendered outside the screen (right and bottom).

**Comment by Pushpak-bhoite** [comment]
@makinggoodsoftware  @seanlandsman  do you have any updates on this, or if you have updated doc, please share solution link for this. 

Best regards!
Pushpak
