### ISSUE TITLE
Excel export, encodes string with spaces as number causing excel to crash

### ISSUE THREAD

**Issue by benschenker** [ag-grid/ag-grid#2002]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When exporting to excel if a cell has the value ` 49` (note the space at the beginning) or any number with a space preceeding, the resulting spreadsheet will not open correctly (excel complains it is invalid) because ag-grid encodes that cell as a Number but the space makes it invalid in excel
**Expected behavior**

Improve checking of the cell value before declaring it is a number to the excel export
**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/oaRXIAHQ6pfDlJCuh4BK click download and note that excel will not open the file
Create an ag-grid with excel export that has a cell value of ` 49` (note the space at the beginning) and export it.  Excel will refuse to open this file. and if you inspect the xml you will see the value is encoded as a number incorrectly
**What is the motivation / use case for changing the behavior?**

When dealing with unvalidated data, extra spaces happen all the time and we have clients experiencing crashes because of this
**Please tell us about your environment:**

OSX 10.12.6
* **ag-Grid version:** 13.13.1

* **Browser:**

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3241.0 Safari/537.36"
* **Language:** TypeScript 2.2.1

**Comment by petyosi** [comment]
Thank you for the report. I have logged the issue as AG-974 in our internal tracker. The dev team will review it.

**Comment by makinggoodsoftware** [comment]
This is menitioned in the docs..

https://www.ag-grid.com/javascript-grid-excel/
[...]
dataType (optional): One of (string or number). In most cases this is not necessary since this value is guessed based in weather the cell content is numeric or not. This is helpful if you want to fix the type of the cell. ie. If your cell content is 003, this cell will be default be interpreted as numeric, and in Excel, it will show up as 3. But if you want to keep your original formatting, you can do so by setting this property to string.
[...]

See this plunkr...
https://plnkr.co/edit/8TlBtKnE7T73dL428Ovm?p=preview

**Comment by benschenker** [comment]
I saw the docs, the issue is that it incorrectly detects the value with a preceding space as a number and this results in an excel file that crashes excel.  Still seems like a bug to me.
