### ISSUE TITLE
Custom cellRenderer is called with undefined data when scrolling infinite grid

### ISSUE THREAD

**Issue by theodorejb** [ag-grid/ag-grid#2009]
**I'm submitting a**
```
[x] bug report
```

**Current behavior**
I'm using the following custom cell renderer with an "infinite" grid in an Angular 4.4 app:

```javascript
function officeCellRenderer(params) {
    let anchor = document.createElement('a');
    anchor.setAttribute('href', '/offices/?OfficeID=' + params.data.office.id);
    anchor.appendChild(document.createTextNode(params.data.office.name));
    return anchor;
}
```

This worked fine in ag-Grid 8.x, but after updating to ag-Grid 13.3.1, I started getting errors saying "TypeError: Cannot read property 'office' of undefined". The error occurs as soon as I scroll down far enough for ag-Grid to call my datasource `getRows()` function.

In order to work around the error, I'd have to add `if (!params.data) { return ''; }` to all my custom cell renderers.

**Expected behavior**
Custom cell renderer should not be called with undefined data.

**Minimal reproduction of the problem with instructions**
`rowModelType: 'infinite'`, columnDefs with above cellRenderer function on one of the columns.

**What is the motivation / use case for changing the behavior?**
It doesn't make sense to call the cell renderer if there is no data to render.

**Please tell us about your environment:**
Windows, Angular 4.4, Webpack 3.8

* **ag-Grid version:** 13.3.1

* **Browser:**
Chrome

* **Language:**
TypeScript 2.4

**Comment by rmc-software** [comment]
Yes you will need to return 'something' rather than null. Your approach is the recommended approach.

**Comment by theodorejb** [comment]
But why is the cell renderer function called in the first place without data?

**Comment by Giancarlos** [comment]
I was able to fix the issue I was having by returning null if params.data came in as null. The grid renders as expected. Not sure why the grid does that sorta black magic either.

```JavaScript
                if(params.data == null){
                    return null;
                }```

**Comment by Giancarlos** [comment]
Looks like it sends null to preload the cells the grid is going to fill in. If you return a string say 'test' instead of an empty string you'll briefly see all the cells that will be filled in that column display 'test' momentarily until the data is pulled back from the server. It's likely a way of clearing the grid for the purpose of sorting and filtering.

**Comment by ReinisV** [comment]
still unclear on why the cell renderer gets called without any data.
Is there a way to disable this so that the cell renderer gets called later, but always with data?

**Comment by ReinisV** [comment]
interestingly, this issue exists only on infinite scroll data model. 

I have two different types of data models used in my code.
For paged tables I have `clientSide`, where I control all of the data loading, filtering, sorting and paging logic and just give ready made data to the grid.
For infinite scroll tables I have `serverSide`, which is an enterprise feature, I still control all of the data loading, filtering and sorting logic, but paging is controlled by ag-grid, and it asks me for new pages when it needs them.

I noticed that `serverSide` is the same as `infinite`, just with extra grouping features and only available with enterprise subscription, so since I didnt use any of the grouping features, I figured I could just switch to `infinite`.
But when I did switch, I hit this issue.

So the moral of this story is -- if you already have an enterprise license and want to implement an infinite scroll grid, use `serverSide` data model instead of `infinite`, that will save you from writing a lot of `undefined` checks.
