### ISSUE TITLE
bug, 13.3.1, date filter doesn't set type to default option

### ISSUE THREAD

**Issue by kroshilina** [ag-grid/ag-grid#2018]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Default option for a date filter is not working.

**Expected behavior**

default filter option should be selected when the filter menu is open for the first time

**Solution:** dateFilter.js is missing a call to a super method. Adding a call to the super method fixes the issue:
    DateFilter.prototype.initialiseFilterBodyUi = function() {
        _super.prototype.initialiseFilterBodyUi.call(this); // this line is missing

**Minimal reproduction of the problem with instructions**
If column def has:
{...
            filter: 'date',
            filterParams: {
                defaultOption: BaseFilter.IN_RANGE,
            }
...}
"in range" is not selected when the grid in rendered

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

13.3.1
* **Browser:**

Chrome Version 60.0.3112.113 (Official Build) (64-bit)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
es6

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
