### ISSUE TITLE
API for custom filters does not work as expected

### ISSUE THREAD

**Issue by futbolistua** [ag-grid/ag-grid#2044]
I use latest version of ag-grid and I'm trying to write own filter using React. But `afterGuiAttached and onNewRowsLoaded` do not call any time. React component life cycle methods like `componentDidMount` calls only once when filter is opened firs time. `componentWillReceiveProps` does not call any times to

Could you help me understand what's wrong?

**Comment by futbolistua** [comment]
And another question. How to handle in custom filter that another filter is applied?

**Comment by futbolistua** [comment]
Anyone  can help me?

**Comment by futbolistua** [comment]
Up

**Comment by futbolistua** [comment]
Is this project alive?

**Comment by FucskoD** [comment]
Same here but for angular 2, implementing  afterGuiAttached(params: IAfterGuiAttachedParams):void but it never called, also with the lifecycle hook, the params is undefined.

**Comment by bgaillard** [comment]
Hi, we also encounter this problem with Angular 5 and Ag-Grid 14.x. 

As per the changelog https://www.ag-grid.com/change-log/changeLogIndex.php it seems that the `afterGuiAttached()` method has been removed for Cell Renderers. 

> In v13.0 we introduced the method afterGuiAttached() for the cell renderers. The purpose of this was to allow cell renderers to be created before the DOM existed which gave a marginal performance boost. This has caused issues for frameworks like React and Angular (which sometimes need the parent DOM element to exist before the component is created). For this reason we have reverted back to how things worked prior to v13.0.
>
> So in summary, v13.0 introduced afterGuiAttached(), **v13.1 takes afterGuiAttached() back out**.

We can also see this in the commits associated to version `1.13.1` here https://github.com/ag-grid/ag-grid/commits/13.1.0. 

The changelog indicates that the change is associated to Cell Renderers. But in our case the problem is associated to Grid Filters (i.e `AgFilterComponent`).

Perhaps the change in v 13.1.0 makes a bug appear here ?

Also in our case we used `afterGuiAttached` to retrieve a reference to the `hidePopup` function. 

```typescript
public afterGuiAttached?(params?: IAfterGuiAttachedParams): void {
        // Backups the hide popup callback function
        this.hidePopupCallback = params.hidePopup;
}
```

Because `afterGuiAttached` is not called anymore we cannot get a reference to the function, so now we are forced to do "ugly" things like that to close the popup.

```typescript
/**
 * Function used to hide the popup associated to the filter.
 */
private hidePopup(): void {

    // WARNING: This is an "ugly" workaroung needed because we updated Ag-Grid and it seems a bug prevent the 
    //          'afterGuiAttached(...)' function to be called. As a consequence we cannot get the 'hidePopup()' 
    //          callback function provided by the Ag-Grid framework.
    //
    // see https://github.com/ag-grid/ag-grid/issues/2044
    $('body').click();
}
```

Can anybody from the Ag-Grid team help us on this ? Why `afterGuiAttached` is not called ? Is this a wanted behavior ?

Thanks,

Baptiste

**Comment by makinggoodsoftware** [comment]
Hi,

Sorry about this, it is tracked in our pipeline with AG-1156:

https://www.ag-grid.com/ag-grid-pipeline/

You will be able to see the progress for this ticket from there

**Comment by bgaillard** [comment]
Hi @makinggoodsoftware, ok great, thanks a lot for your reactivity on this case !

**Comment by thisisthedave** [comment]
I also discovered that `afterGuiAttached` is not called for a filter component developed in Vue.js. I was able to track it down in the source to fact that `afterGuiAttached` is not listed in the `optionalMethodList` metadata for a `filter` component. You should be able to fix it like this: edit the file
```
    ag-grid\src\ts\components\framework\componentMetadataProvider.ts
```
and add `afterGuiAttached` to the `optionalMethodList` on line 78:
```
filter: {
    mandatoryMethodList: ['isFilterActive', 'doesFilterPass', 'getModel', 'setModel'],
    optionalMethodList: ['afterGuiAttached', 'onNewRowsLoaded', 'onFloatingFilterChanged'],
    functionAdapter: this.agComponentUtils.adaptCellRendererFunction.bind(this.agComponentUtils)
}
```
