### ISSUE TITLE
When press Tab while editing, grid checks "editable" callback of next cell before current cell applied

### ISSUE THREAD

**Issue by catahoc** [ag-grid/ag-grid#2048]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When press Tab while editing, grid checks "editable" callback of next cell before current cell new value is applied.

**Expected behavior**
When press Tab while editing, grid should first apply value, then perform lookup for next cell to be edited

**Minimal reproduction of the problem with instructions**
2 columns: 
* "country" - editable always
* "city" - editable when country is defined

Start editing "country". When you have entered desired country, press Tab. Instead of starting editing "city", editing starts on next cell

**What is the motivation / use case for changing the behavior?**
Please have a look at scenario in "Minimal reproduction of the problem with instructions"

**Please tell us about your environment:**
Windows, Intellij IDEA, npm, webpack

* **ag-Grid version:** 13.3.1
still reproduced in latest ag-grid

* **Browser:**
"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"

* **Language:** typescript 2.3.1

**Comment by Luxor** [comment]
+1

**Comment by catahoc** [comment]
Anniversary, 2048th issue =)

**Comment by catahoc** [comment]
Workaround, dirty but working (patching sources):
```typescript

import {RowRenderer} from 'ag-grid';

// https://github.com/ag-grid/ag-grid/issues/2048
(function patchRowRenderer() {
    const rowRenderer: any = RowRenderer;
    const original = rowRenderer.prototype.findNextCellToFocusOn;
    function patched(...args: any[]) {
        this.stopEditing();
        return original.apply(this, args);
    }
    rowRenderer.prototype.findNextCellToFocusOn = patched;
})();
```

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by catahoc** [comment]
Hi, makinggoodsoftware,
https://plnkr.co/edit/NFE6ZH162zku3NEbjWV0?p=preview

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for that, I have created a ticket AG-1342 that you can track in our pipeline, https://www.ag-grid.com/ag-grid-pipeline/.

We are aiming to get this fixed in the next 1/2 releases

Thanks

**Comment by ceolter** [comment]
just fixed this, will be in next release.

**Comment by JohnMasterson** [comment]
AG-1342 was included in Version 16.

Regards, 

John
