### ISSUE TITLE
Support for Semantic UI Theme

### ISSUE THREAD

**Issue by jadhavajay** [ag-grid/ag-grid#2064]
**I'm submitting a ...**

[x] feature request

**Current behavior**
The current release (14.2.0) supports improved themes, but did not have any [Semantic UI](https://semantic-ui.com/) based [theme](https://semantic-ui.com/usage/theming.html).

**Expected behavior**
Support for themes found in Semantic UI

**What is the motivation / use case for changing the behavior?**
Will be easier to use Ag-grid with projects using Semantic UI as a CSS Framework.

**Please tell us about your environment:**
N/A

* **ag-Grid version:** X.X.X
14.2.0

* **Browser:**
All

* **Language:**
All

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by padrefuture** [comment]
Did jadhavajay find a solution to Semantic-UI integration?

**Comment by padrefuture** [comment]
My workaround is now trying to make this grid look like Semantic-UI by customizing CSS. Im currently looking for a way to add an magnify glass icon to the input field (column search) to look similar to semantic-ui: https://react.semantic-ui.com/elements/input/ I noticed the advanced search has a placeholder.

Has anyone figured out how to do this? We are trying not to create a custom theme so that we dont run into trouble upgrading.
