### ISSUE TITLE
AG-grid anchor link in cell not getting Routed to another component

### ISSUE THREAD

**Issue by innov-richa76** [ag-grid/ag-grid#2078]
Current behavior
On click of the cell the it is not getting redirected to the proficiency page.
Expected behavior
On click of cell in Test column it should get redirected to the proficiency page.

Minimal reproduction of the problem with instructions
Here is the plunker with the issue
https://plnkr.co/edit/3s55ZmAgdlEQPfhawWvH?p=preview
What is the motivation / use case for changing the behavior?
N/A
Please tell us about your environment:
IDE:visual studio
ag-Grid version: 13.0.X
Language: [all | TypeScript 2.4]

**Comment by innov-richa76** [comment]
Can anyone suggest something on this? Appreciate your great help!

**Comment by makinggoodsoftware** [comment]
If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

===============

Hi your column has the following content

<a href="">Test</a>

That is not pointing to any link

**Comment by innov-richa76** [comment]
I want to redirect to the proficency page on click of Test column which is not happening with the routing. You can see the below cellrenderer method in which I am trying the same:
function testCellRenderer(){
  const element= document.createElement('span');
  let template='<a href="">Test</a>';
  element.innerHTML=template;
  element.addEventListener('click', ()=>{
    this.router.navigate('/proficiency-renderer');
  });
  return element;
}

**Comment by innov-richa76** [comment]
Hi,
Can anyone suggest something?

**Comment by iankitagarwal** [comment]
Hi,
@innov-richa76 , you are using this.router inside the function which is not valid for that scope. It("this") is undefined and therefore there is a console error. WHat you can do, you can just pass the router instance to the method and can use that. You have to remove <a> tag as well otherwise it will redirect the page. So just make it simple with span only and then add some sort of css to give feel of anchor tag to it.

import { Component } from '@angular/core';
import { DatePipe, DecimalPipe } from '@angular/common';
import { ColDef } from 'ag-grid-community';

import { MyLinkRendererComponent } from './my-link-renderer.component';
import { Router } from '@angular/router';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  columnDefs: ColDef[];

  rowData = [
    { 'car': 'Audi', 'releaseDate': '2018-01-04', 'price': 99000 },
    { 'car': 'Tesla', 'releaseDate': '2020-03-01', 'price': 49000 },
    { 'bus': 'MAN', 'releaseDate': '2015-02-02', 'price': 1234500 },
    { 'bus': 'Volvo', 'releaseDate': '2016-06-03', 'price': 2234500 }
  ];

  constructor(private dateFormatter: DatePipe, private numberFormatter: DecimalPipe,
    private router: Router) {
    const columns = ['car', 'bus', 'releaseDate', 'price'];
    this.setColumns(columns, this.router);
  }

  setColumns(columns: string[], router: Router) {
    this.columnDefs = [];
    columns.forEach((column: string) => {
      let definition: ColDef = { headerName: column, field: column, width: 120 };
     
        definition.cellRenderer = function (column) {
          const element = document.createElement('span');
          element.style.cssText = "color:blue;text-decoration:underline";
          let template = column.value;
          element.innerHTML = template;
          element.addEventListener('click', () => {
            router.navigate(['/car/' + column.value], { skipLocationChange: false })
          });
          return element;
        }
      
      this.columnDefs.push(definition);
    });
  }

  clickMe(event: any) {
    console.log("clicked");
  }

}
I know I am late. but it will help someone else too. :)
