### ISSUE TITLE
Testing ColumnDef of an ag-grid using karma jasmine is not working

### ISSUE THREAD

**Issue by innov-richa76** [ag-grid/ag-grid#2079]
Current behavior
1.On testing the ColumnDef  of an ag-grid using karma jasmine framework, i am getting the issue
"Error: Property Cell Renderer does not exist in Component".

2.How to test the column headers of the ag-grid using karma jasmine.
Note: the approach followed in ag-grid.com for testing the column headers is also giving issues , 
Here is the plunker with the issue
https://plnkr.co/edit/3s55ZmAgdlEQPfhawWvH?p=preview
What is the motivation / use case for changing the behavior?
N/A
Please tell us about your environment:
IDE:visual studio
ag-Grid version: 13.0.X
Language: [all | TypeScript 2.4]

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
