### ISSUE TITLE
Grid getting shrinking after updating data 

### ISSUE THREAD

**Issue by shaikjohnsaida** [ag-grid/ag-grid#2080]
I am new to ag grid, I got stuck in an issue when ag grid renders initially am detecting on grid ready event and calling sizeColumnsToFit to stretch the columns on my screen. 

But on updating the data(rowData value update, on react and redux) the columns are shrinking again, please find the attached screenshot.

**on intiall renders**
![123](https://user-images.githubusercontent.com/20972933/33345830-b2a8c356-d4b3-11e7-9361-9c2da1cb8a5d.png)

**after updating data**
![321](https://user-images.githubusercontent.com/20972933/33345844-bd300b5e-d4b3-11e7-92c0-e4441c20c65d.png)

how can I handle this..?

**Comment by makinggoodsoftware** [comment]
If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

===============

Hi, there is not enough information there, can you provide with the steps to follow in the grid to reproduce the error and let us know what the expected behaviour is?

Thanks

**Comment by orobsonpires** [comment]
Hi @shaikjohnsaida,

Have you found a solution for it? I am having the same issue. I am calling the sizeColumnsToFit from the onGridReady function at first, then I recall again on ngOnChanges, and the columns are shrinking before fit the space available.
