### ISSUE TITLE
AG-Grid- Overlays is not working on refresh of the Grid

### ISSUE THREAD

**Issue by innov-richa76** [ag-grid/ag-grid#2083]
Current behavior
On click of the Button Refresh, the Ag-grid is not loading the overlays.
Expected behavior
On click of Button Refresh, the Ag-grid should load the overlays.

Minimal reproduction of the problem with instructions
Here is the plunker with the issue
https://plnkr.co/edit/iz31eD9h2oUolbIdWF3y?p=preview
What is the motivation / use case for changing the behavior?
N/A
Please tell us about your environment:
IDE:visual studio
ag-Grid version: 13.0.X
Language: [all | TypeScript 2.4]

**Comment by makinggoodsoftware** [comment]
Hi,

This is working as expected, this is designed so that it will only show initially, note that you can invoke the showLoading and hide it manually though.

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
