### ISSUE TITLE
 newFilter.toUpperCase is not a function  at FilterManager 

### ISSUE THREAD

**Issue by hardav31** [ag-grid/ag-grid#2096]
\ag-grid\dist\lib\filter\filterManager.js 
when I start to write in filter input(Age) ,it throws error...

https://plnkr.co/edit/gGvG5TlzsSl1Ej6hfU1q?p=preview

**Comment by makinggoodsoftware** [comment]
If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Hi, there is not enough information there, can you provide with the steps to follow in the grid to reproduce the error and let us know what the expected behaviour is?

Thanks

**Comment by hardav31** [comment]
I have just sayed error...You should see in plunker ,(link I have already written above) :)
https://plnkr.co/edit/gGvG5TlzsSl1Ej6hfU1q?p=preview
when I start to write in filter input(Age) ,it throws error.....you can see it in console....
Thank you

**Comment by markchkhotua** [comment]
Hi all
Have this issue being fixed? 
We are facing it too
