### ISSUE TITLE
cellRendererFramework called even if pinnedRowCellRendererFramework is set

### ISSUE THREAD

**Issue by vlio20** [ag-grid/ag-grid#2100]
[x] bug report => search github for a similar issue or PR before submitting

If I have the following configuration:
```
pinnedRowCellRendererFramework: null,
cellRendererFramework: CustomCellRendererComponent,
```

It seems that the `cellRendererFramework` is also called on the pinned row. Can it be changed? (I am using Angular version of ag-grid:
```
"ag-grid": "14.2.0",
 "ag-grid-angular": "^14.2.0",
```

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
