### ISSUE TITLE
Material Theme - Select column : options are not visible

### ISSUE THREAD

**Issue by Trontin** [ag-grid/ag-grid#2106]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Options are not visible on select column

**Expected behavior**
Options should be visible on select column

**Minimal reproduction of the problem with instructions**
See on documentation : [https://www.ag-grid.com/javascript-grid-themes/material-theme.php#gsc.tab=0](https://www.ag-grid.com/example-runner/angular.php?section=javascript-grid-themes&example=theme-material&roboto=1&enterprise=1&generated=1&grid=%7B%22theme%22%3A%22ag-theme-fresh%22%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3Atrue%7D)

* **Browser:**
Chrome Version 62.0.3202.94 (64 bits), FF 57.0 (64 bits)

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
