### ISSUE TITLE
Row groups and sorting group nodes

### ISSUE THREAD

**Issue by kbanglore** [ag-grid/ag-grid#2107]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There's no way to sort groups when using rowGrouping on a column. When a column s clicked, the rows within the groups sort accordingly but not the groups themselves.

Also row groups (I'm talking about group nodes) are always sorted alphabetically 

**Expected behavior**
The comparator function for a column/setsortmodel on api should work correctly for group header sorting.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Bug

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X
13.X

* **Browser:**
Chrome

* **Language:** ES6

**Comment by namnn** [comment]
Any update on this please?

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
