### ISSUE TITLE
Immutable store updates

### ISSUE THREAD

**Issue by danielamram** [ag-grid/ag-grid#2109]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When working with ag-grid and immutable store, the cellRenderer of the changed rows not running,
And the cells stays with the previous render.

**Expected behavior**
Excpected cellRenderer function to be called after the immutable array changed for the relevant rows.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/CFb6oj2xtC8YNIfIvpgo?p=preview

Click on update items changing all the elements with immutables, and not running api.redrawRows.
Click on Update & Refresh changing all the elements with immutables, and running api.redrawRows.

When working with immutables it should render the changed rows.

* **ag-Grid version:** 14.2.0

* **Browser:**
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

* **Language:** [**all** | TypeScript 2.6.2 | ES6/7 | ES5]

Thank you.

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by DAVIDSUSAIRAJ** [comment]
Immutable store updates not working properly. Ex. If the same name in the first column automatically created one row. Alignment changing. How do i fixed that one. Anybody can help me.?
