### ISSUE TITLE
Set Filter Parameters Values Asynchronously doesn't work

### ISSUE THREAD

**Issue by aimad-majdou** [ag-grid/ag-grid#2110]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Instead of specifying a hardcoded list of values for filterParams.values I want to load the values asynchronously, I used a callback back function where I call a promise, which doesn't work and when I debug inside the callback function, the debugger never stops in the breakpoint, so I'm guessing that the callback function is never executed.

**Expected behavior**
Calling `params.success(data)` should populate the filterParams values with data I get from the promise call.

**Minimal reproduction of the problem with instructions**
This is the code I tried : 

```
filterParams: {
	values: function(params){
		myDataservice.loadAll("organization/user").then(function(data){
			params.success(data);
		})
	},
	newRowsAction: 'keep'
}
```
I also tried the same code from the documentation which doesn't work either :

```
filterParams: {
	values: function(params){
		setTimeout(function() {
			params.success(["value 1", "value 2"]);
		}, 5000);
	},
	newRowsAction: 'keep'
}
```

**Please tell us about your environment:**

OS: Windows 7
IDE: Webstorm 2017.2.2, Eclipse Neon.3 Release (4.6.3)
package manager: Yarn, Maven
HTTP server : Wildfly 10

* **ag-Grid version:** ag-grid-enterprise#5.0.3

* **Browser:**
"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
