### ISSUE TITLE
Field with point "." removes content of column

### ISSUE THREAD

**Issue by juanmi108** [ag-grid/ag-grid#2111]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Content of whole column missing.

**Expected behavior**
Content of column is not missing. 

**Minimal reproduction of the problem with instructions**
Set the field of a column definition to anything contining a point. eg. "Name.With.Point"

**What is the motivation / use case for changing the behavior?**
Not restricting the use of point for users

**Please tell us about your environment:**
Running on Angular 1. Happens in All Browsers

* **ag-Grid version:** 14.2.0

* **Browser:** Chrome, FF, IE, EDGE

* **Language:** [ES5]

**Comment by juanmi108** [comment]
Previously opened a issue #2069 this issue but I mistakely said that the problem ocurs with the Label of the Column, is the property 'field' of the column definition that has this problem.

**Comment by makinggoodsoftware** [comment]
Hi,

If you provide us with a plunkr with a clear scenario where this issue is highlighted we will create a bug ticket for this

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by juanmi108** [comment]
I created a plunker https://plnkr.co/edit/EJOfQeFmPMkn1Wbq7PC5?p=preview
