### ISSUE TITLE
pointer-events:none allows events?

### ISSUE THREAD

**Issue by Ketec** [ag-grid/ag-grid#2123]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```
Using ag-theme-material theme.

**Current behavior**
I noticed overlay uses pointer-events:none that allows all events
`<div class="ag-bl-overlay" ref="overlay"></div>`
Has `pointer-events: none;`

**Expected behaviour**
by HTML standard NONE should block events and ALL should allow them.
Is this intended behaviour?

**Comment by Ketec** [comment]
Ignore title change - i hit submit before i changed it.

**Comment by makinggoodsoftware** [comment]
Hi,

Not sure what you mean by this, cam you describe what is the issue you are seeing?

Thanks

**Comment by Ketec** [comment]
Late reply but the class `ag-bl-overlay` has `pointer-events: none;`
Which is odd because none by definition should block all user click etc events.  
Instead it allows all the events.  
Now when the overlay is active (`display: none` is removed) - overlay does not block anything.  
I had to add a custom css rule to that div with `pointer-events: all;` to get it to block the grid events.  

Also there are two divs with that class and ref="overlay". Only the inner one has a display property that gets toggled none/visible. If i override `ag-bl-overlay `class (to block events) the outer overlay would always be active and on top.

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved
