### ISSUE TITLE
getBusinessKeyForNode docs incorrect

### ISSUE THREAD

**Issue by bengillies** [ag-grid/ag-grid#2133]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Specifying a `getBusinessKeyForNode` property, as per [this line](https://github.com/ag-grid/ag-grid/blob/master/src/ts/rendering/rowComp.ts#L194) creates a `row-business-key` attribute on the row dom node.

**Expected behavior**
The docs at https://www.ag-grid.com/javascript-grid-callbacks/#gsc.tab=0 say that it will instead be used in the `row-id` attribute. It's not clear to me which behaviour is the correct one, but either the code or the docs need updating.

**Minimal reproduction of the problem with instructions**
See the `row-id` and `row-business-key` attributes here: https://plnkr.co/edit/Sw3fGOedk6SqGDmKONQv?p=preview

**What is the motivation / use case for changing the behavior?**
Clarity. The docs should match the behaviour.

**Please tell us about your environment:**
maxOS, vim, npm, nginx, react

* **ag-Grid version:** X.X.X
15.0.0

* **Browser:**
Tested in Chrome but should happen in all browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved
