### ISSUE TITLE
Unable to display multiple overlay template

### ISSUE THREAD

**Issue by arunw3** [ag-grid/ag-grid#2150]
I'm trying to show overlay template when the service URL fails in ag-grid.

But the overlay message is not displaying as expected.

I wanted to show `Service URL failed`message when the http request fails. And another overlay message `Please wait data is loading` when data is actually loading in the grid.

I'm unable to display the overlay message when the url gets failed. it always show's the first message

How do i fix this ?

This my link to the plunker project : https://plnkr.co/edit/MzpwnE0enLx2PVJOFUyn?p=preview

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
