### ISSUE TITLE
ag-grid onGridReady() function call multiple times.

### ISSUE THREAD

**Issue by SWGeekPD** [ag-grid/ag-grid#2157]
Can we call onGridReady() twice. I want to change the grid data on getContextMenuItems() action method call.

I used   (gridReady)="onGridReady($event)" on html. but it is not filling the data into grid when context menu clicked.
If I directly use [rowData], grid become unresponsive-hanged.

Please share any thoughts on this.

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
