### ISSUE TITLE
Performance Issues With ag-grid tree view

### ISSUE THREAD

**Issue by Nirav-Bhadradiya** [ag-grid/ag-grid#2165]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have ag-grid treeview with more than 1000 childs for first node. When i expand first node it takes too much time to render whole tree again, it happens with any child too when i try to expand/collapse any child it takes similar amount of time.

**Expected behavior**
It should not take much time it should be on the fly.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
We have seen that ag-grid developers redraw whole tree when we expand/collapse any node on the tree view that seems t o be an issue.

**Please tell us about your environment:**
I have created knockout widget from ag-grid enterprise trial version and binding tre view.

* **ag-Grid version:** X.X.X
14.1.1

* **Browser:**
Google chrome

* **Language:**
Knockout, javascript

**Comment by Nirav-Bhadradiya** [comment]
Is there  any update on this ?

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
