### ISSUE TITLE
When setting"marryChildren=true" in a group column they can separate when dragged in some cases

### ISSUE THREAD

**Issue by ToMer-K** [ag-grid/ag-grid#2180]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When dragging a sub column (= child of a group column) from pinned area to unpinned area the column breaks.   The same when dragging from unpinned area to a pinned area.

**Expected behavior**
The children columns should never separate.

**Minimal reproduction of the problem with instructions**
Drag one of the children columns in and out of the pinned area
[plunker](https://plnkr.co/edit/NHp5zWpCUvqGimbYPbuG?p=preview)

**What is the motivation / use case for changing the behavior?**
Columns under the same group should stay together because sometimes they are only readable when adjacent to the other group columns.

**Please tell us about your environment:**
Windows 10, PHP Storm, AngularJS

* **ag-Grid version:** 16.0.1

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"

* **Language:** ES5

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.

**Comment by prashantjain68** [comment]
I am experiencing similar behavior using the latest version.

I have 3 column groups with groupid ... colGroup1, colGroup2, colGroup3. 
all column groups have marryChildren = true
All child columns of colGroup1 have pinned = "left".

When I move the one of the columns of colGroup1 outside of the group, aggrid creates another instance of colGroup1 with instanceid = 1 and moves that column into the newly created column group.

In the console, I fired the command after the column move has ended ...
columnApi.getAllDisplayedColumnGroups()
I see 4 column groups. 2 of them being "colGroup1". Their instanceid's are 0 and 1.

**Comment by crazyjat** [comment]
I am also experiencing a similar issue with column groups. When I have `marryChildren: true` set on the ColGroupDef, I can still move the columns outside of that group. 

v 28.0.2
