### ISSUE TITLE
GridOptions TS interface does not have declaration of onRowDrag* events

### ISSUE THREAD

**Issue by iexela** [ag-grid/ag-grid#2181]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
`GridOptions` TS interface does not contain declarations of `onRowDrag*` events (onRowDragEnter, onRowDragMove, etc)

**Expected behavior**
`GridOptions` should have declaration of drag events.

* **ag-Grid version:** 16.0.1

* **Language:** Typescript

**Comment by makinggoodsoftware** [comment]
AG-2102 | Typescript - Improve typescript typings
-- | --

**Comment by makinggoodsoftware** [comment]
One common issue that we receive is around typescript typings and how they can be improved, note that we are aware of this, and we periodically improve them as these are reported.

To track all these issues we use a parked feature request since we consider it to be a never-ending one.

This is particularly true for events. The events are bound as properties in ag-grid dynamically to the gridOptions, and that is why we don't have typings for them just yet.

Note that we are planning to automate these, but we have no ETA for this yet.
