### ISSUE TITLE
MouseEvent undefined during SSR

### ISSUE THREAD

**Issue by abhipanda** [ag-grid/ag-grid#2187]
[x] bug report => agGridCheckbox.js causing "**MouseEvent undefined**" during SSR rendering causing runtime error

**Current behavior**
ReferenceError: MouseEvent is not defined at /app/node_modules/ag-grid/dist/lib/widgets/agCheckbox.js:173:42

* **ag-Grid version:** 16.0.1
* **Language:** ES5

**Comment by Budenniy** [comment]
Same issue with same setup using React ("ReferenceError: MouseEvent is not defined" when using asp.net core 2.0 SSR). Temporary workaround, as suggested - cutting [MouseEvent] via webpack using regex loader (probably renders checkbox read-only).
ag-Grid@16.0.1, react@15.6.1, webpack@2.5.1.

**Comment by igorsky78** [comment]
I'm getting same error. Any movement on fixing this issues or workaround?

**Comment by abhipanda** [comment]
I just did a hack in my server.js 

```
const dom = new JSDOM('<!doctype html><html><body></body></html>', { url: hostName }); 
global.MouseEvent = dom.window.MouseEvent;
```

**Comment by mixail-novikov** [comment]
My temporary workaround is 
```
// import { AgGridReact } from 'ag-grid-react';
const AgGridReact = typeof window === 'undefined' ? () => null : require('ag-grid-react').AgGridReact;
```

**Comment by melbayad** [comment]
Same problem here

**Comment by justan0therdave** [comment]
I think this is being fixed in the next release => [https://www.ag-grid.com/ag-grid-pipeline/](https://www.ag-grid.com/ag-grid-pipeline/)

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
