### ISSUE TITLE
customize the toolPanel

### ISSUE THREAD

**Issue by smile2014** [ag-grid/ag-grid#2194]
Hi,
Are you able to customize the toolPanel.   I  want add button in the toolPanel. Thanks (angular5)

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
