### ISSUE TITLE
Data parameter missing in renderer after grid refresh

### ISSUE THREAD

**Issue by dsozzi** [ag-grid/ag-grid#2195]
<!--
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm using the Infinite row model and implementing a simple renderer component on one column. When calling the `api.purgeInfiniteCache()` the renderer get recalled but inside the init method, the "data" key is missing.

Here is the renderer component taken from the documentation
```

     function MyCellRenderer () {}

        MyCellRenderer.prototype.init = function (params) {
            this.eGui = document.createElement('span');

            // after a refresh the params is missing data, value and valueFormatted keys
            this.eGui.innerHTML = params.data.title;
        };
        MyCellRenderer.prototype.getGui = function() {
            return this.eGui;
        };
        MyCellRenderer.prototype.refresh = function(params) {
            // return true to tell the grid we refreshed successfully
            return true;
        };

```
After the refresh, the params passed to init has some keys missing. (data, value and valueFormatted)

**Expected behavior**
The same object should be passed everytime there is a grid renderer

**Minimal reproduction of the problem with instructions**
1. use a grid with infinite scroll
2. implement the above renderer component on a column
3. call the `api.purgeInfiniteCache()` function and notice how the params received in the init function is missing some keys (such as data)

* **Language:**
ES5

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
