### ISSUE TITLE
Overlapping column data

### ISSUE THREAD

**Issue by desaroxx** [ag-grid/ag-grid#2203]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Material design theme's column data is overlapping with the column to it's right hand side, when column width is very small.

The overlapping text is visible in the following GIF:

![feb-09-2018 14-02-56](https://user-images.githubusercontent.com/1498400/36029148-3ff28856-0da2-11e8-8782-276dd7a85a7f.gif)

**Expected behavior**
Text can not bleed out of the column, therefore it would not overlap with other column's data.

**Minimal reproduction of the problem with instructions**
1. Open: https://plnkr.co/edit/9zkAA47wOxc0tPG8tCnZ
2. Press the "Run" button, so the ag grid UI is shown
3. Resize column "Game Name" so it's width is 0px
4. Verify that "Game Name" column's data is overlapping with "Country" column's data

**What is the motivation / use case for changing the behavior?**
Overlapping text is not readable and therefore the shown data becomes useless.

**Please tell us about your environment:**
macOS High Sierra 10.13.3
npm

* **ag-Grid version:** 16.0.1

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36"

* **Language:** ES5

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
