### ISSUE TITLE
routerLink not working with anchor tag  in cellrenderer ag-grid

### ISSUE THREAD

**Issue by purplehaze711** [ag-grid/ag-grid#2205]
I
```
           {
                headerName: "Opportunity Name",
                field: "OpportunityName",
                width: 200,
                cellRenderer: function(params) {
                    return '<a [routerLink]="/dashboard" (click)="alert("Test")">'+ params.value+'</a>'; 
               }
                
          
```

I want to give a router.navigate to an anchor tag in my cellrenderer function. But there's no event fired when i click on the link in the cell. neither router.navigate not routerlink is navigating to the page i want to. 

 **ag-Grid version:** 16.0.1

* **Browser:** IE

* **Language:** [all | TypeScript 2.6.2 | ES6/7 | ES5]

**Comment by ChandraTerli** [comment]
Were you able to make t work? I got the same problem.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by deepmirchandani** [comment]
I'm facing the same issue.

cellRenderer: function(params) {
                    return '<a (click)="goToCreateRecords();"'; 
               }

**Comment by ao** [comment]
This is because that element is dynamically added to the DOM after the internal binding events have already run.
You have to do something kind of like this:

```
constructor(private elRef:ElementRef) {}

ngAfterViewInit() {
  this.elRef.nativeElement.querySelector('button').addEventListener('click', this.onClick.bind(this));
}
```
