### ISSUE TITLE
Row Dragging issue with pinned right columns

### ISSUE THREAD

**Issue by Udeste** [ag-grid/ag-grid#2209]
**I'm submitting a ...** 
```
[x] bug repor
[ ] feature request
[ ] support request
```

**Current behavior**
Row dragging seems to not work properly if a pinned right column is defined. Basically if I try to drag a row at the end of the grid the auto-scroll stops working.

**Expected behavior**
The grid performs auto-scroll when the row is dragged at the bottom or at the top.

**Minimal reproduction of the problem with instructions**
Here is a plunker example: https://plnkr.co/edit/jtf18Z85RoTiGu2VGF2x?p=preview

If the `pinned: 'right'` is removed from the last column it works correctly.

* **ag-Grid version:** 16.0.1

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
