### ISSUE TITLE
setFilterModel() in async/callback set filter

### ISSUE THREAD

**Issue by Shadrongowes** [ag-grid/ag-grid#2212]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```
Original fix in AG-1171, reproduction of error in 16.0.0

**Current behavior**
**setFilterModel()** is unable to filter on a column when async/callback model is used for values, shown [ here ](https://www.ag-grid.com/javascript-grid-filter-set/#example-callback-async).
**setFilterModel()** initiates callback function in **values** attribute, but does not apply filter to column. Once callback is successful, **setFilterModel()** behaves as expected.

**Expected behavior**
Unopinionated filter applied to column's set filter.

or 

**setFilterModel()** initiates _values_ callback function, on success filter model is applied.

**Minimal reproduction of the problem with instructions**

*STEPS TO REPRODUCE* Method 1
1. Open https://embed.plnkr.co/213Oa6iAZVzMlddfq9CD/
2. Click Apply Filter using setFilterModel() button.
3. Observe (we expect the filter _'value 1'_ to be applied)
4. Wait 5s
5. Click Apply Filter using setFilterModel() button.
6. Observe (function behaves as expected)

*STEPS TO REPRODUCE* Method 2
1. Open https://embed.plnkr.co/213Oa6iAZVzMlddfq9CD/
2. Select Filter icon on Set filter col column
3. Wait for Set Filter to populate
4. Click Apply Filter using setFilterModel() button.
5. Observe (function behaves as expected)

Only applies filter after callback success.

**What is the motivation / use case for changing the behavior?**

We leverage ag-grid's asynchronous set filters. These provide significant speed increases and lower transmission payloads for our clients, a very valuable feature. However, we also invoke .setFilterModel in onGridReady to load cached and saved filter configurations. These two features are unable to operate in tandem. 

**Please tell us about your environment:**

Linux Red Hat 7
Spring Boot 1.3.3
npm
(Behavior is likely not system dependent)

* **ag-Grid version:** 16.0.0

* **Browser:** Google Chrome Version 61.0.3163.100 (Official Build) (32-bit) 

* **Language:** all

**Comment by Shadrongowes** [comment]
17.1.1 not fixed

**Comment by Bema** [comment]
I have the same issue but found a way around it. 

Instead of running `gridOptions.api.setFilterModel(models)`, we have to set each filter model individually using `filterComponent.setModel()`, see below:

```javascript
forEach(filterModel, (filter, fieldName) => {
    // get filter instance
    const filterComponent = this.gridOptions.api.getFilterInstance(fieldName);

    filterComponent.setModel({
        type: filter.filterType,
        values: filter.values
    });

    filterComponent.onFilterChanged();
 });
```
Our use case is that we remotely store the grid state (including filter models) so when users reload the application their changes are fully preserved, we extract the filter models using `gridOptions.api.getFilterModel()`, this method returns an object with the following signature:

```typescript
{
    [fieldName]: {
        filterType: string;
        values: []
    }
}
```
`filterComponent.setModel()` expects an object with property `type` instead of `filterType`, which is a undesired discrepancy. 

Unfortunately I won't have time to figure why  `gridOptions.api.setFilterModel(models)` won't work, I did try to rename `filterType` to `type` but it still won't work. 

As an enterprise feedback: It would be great to have a single way to subscribe to the grid's state and also a way to easily set its initial state (filters, sorting etc), to be able to do that we had to subscribe to several events and invoke several methods which is unfortunately pretty time consuming and the use case is very common nowadays.

**Comment by stereosteve** [comment]
Here is a crappy work-around.

Assuming you have a variable `gridState` like:

```
const gridState = {
  filterModel: {
    brand: {filterType: 'set', values: ['CompanyA', 'CompanyB']},
    model: {filterType: 'set', values: ['MakeA', 'MakeB']},
  }
}
```

You can force the values to load before calling `setFilterModel`:

```js
        let ps = Object.keys(gridState.filterModel).map(k => {
          const m = this.gridApi.getFilterInstance(k).model;
          return m && m.filterValuesPromise;
        });
        Promise.all(ps).then(() => {
          this.gridApi.setFilterModel(gridState.filterModel);
        });
```

I haven't really tested this much and it seems pretty hacky.  In the long run I think developing a custom set filter is going to be easier for me than trying to make the built-in set filter work in this situation.

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks

**Comment by bbohling** [comment]
This still does not work. Example: https://angular-438dcc.stackblitz.io

**Comment by makinggoodsoftware** [comment]
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by makinggoodsoftware** [comment]
As in the other thread...

Hi guys,

Let me have a look at the scenarios provided, we will let you update you as soon as possible.

Thanks for all the feedback!

**Comment by makinggoodsoftware** [comment]
#2709 Duplicate
