### ISSUE TITLE
Columns pinned to right creates empty space between the columns

### ISSUE THREAD

**Issue by Varshamathukumalli** [ag-grid/ag-grid#2215]
Hi,

I have created a ag-grid with few columns pinned to right and suppose i have only two columns which are not pinned then ag-grid is creating space between pinned columns and non-pinned columns.
In the below URL,  Total Column is pinned to right and Athlete, country are non pinned columns and find the space between country and total columns. 
Plunker: https://plnkr.co/edit/Icz25Fe45U1ShLX0XsdM?p=preview
Ideally that space shouldn't exist and the pinned columns should re-adjust among the available columns.
Kindly Provide us a way to solve this.

Regards,
Varsha Mathukumalli

**Comment by Koen967** [comment]
Hello Varsha,

If I understand correctly you don't want to have an empty space between pinned columns to the left and to the right. To make sure the columns use the entire width of the grid you can call the sizeColumnsToFit() method on the gridAPI.
I've added this method to you plunker in the bottom of the main.js file on row 77: https://plnkr.co/edit/9SkxiCOzMmOdOVRlyBkf?p=preview
Is this what you were looking for?

Kind regards,

Koen van Helvoort.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Note that this is parked as of this time, just because of its complexity, which means that even though we are aware of this issue, we don't have any easy solution as of this time

This is the reference and summary of the relevant issue:

AG-2160 - Column pinning - Allow pinning to only happen when there isn't enough space in the viewport

**Comment by jamend** [comment]
As a workaround for this, I added a flex width column before the pinned column to take up the blank space:
`{ "colId": "_spacer", "flex": 1 }`

**Comment by maimooni** [comment]
What I did as a workaround was to find the last unpinned column and change its definition to `flex: 1`, so it takes all the available space to the pinned columns. 
I could not use the `applyColumnState` because it doesn't have the `minWidth` option and where there was no gap, the column was too small, therefore I had to change the column definition directly, so something like:

```
...
const index = columnDefs.findIndex((colDef) => colDef.colId === lastUnpinnedColumn.colId);
columnDefs[index].minWidth = 110;
columnDefs[index].flex = 1;
this.gridOptions.api!.setColumnDefs(columnDefs);
...
```

**Comment by empressmoon** [comment]
I faced same issue and as I see it is not yet fixed by ag-grid. Working workaround for me is overriding styles:

```
.ag-center-cols-clipper, .ag-header-viewport {
    flex: unset;
}
```

I am customizing table anyway so this one line of css fixes the issue perfectly 👌
