### ISSUE TITLE
bad selection if click on the cell and move on the same time

### ISSUE THREAD

**Issue by jare-talend** [ag-grid/ag-grid#2220]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
With one grid with multiple selection, If I click on another cell that the selected row and in the same time, I move my mouse quickly on another row, ag-grid set the class ag-row-focus on the row clicked and not the class ag-row-selected.

![ag-grid](https://user-images.githubusercontent.com/20772261/36552449-34d77ee2-17fa-11e8-8fb5-28d42d844f33.gif)

**Expected behavior**
set the class ag-row-selected instead of ag-row-focus when we mouseup.

**Minimal reproduction of the problem with instructions**
We can reproduce this on this plunker (demo on the row selection) 

https://plnkr.co/edit/?p=preview

**What is the motivation / use case for changing the behavior?**
bad selection

**Please tell us about your environment:**
all environnement 
* **ag-Grid version:** X.X.X
ag-grid v16

* **Browser:**
all browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
