### ISSUE TITLE
IE11 Print bug when grid is scrolled horizontally (column header and data misaligned)

### ISSUE THREAD

**Issue by NielsSkovgaard** [ag-grid/ag-grid#2222]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Printing in Internet Explorer 11 when an ag-grid is scrolled horizontally towards the right -- then headers and content are not aligned in the Print Preview / Print. Works in Chrome, but not IE11.

**Expected behavior**

In IE11 Print/Print Preview, column headers and grid content should be aligned under each other.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/yvoDwQbus595FyyfRztr?p=preview

Open the above Plnkr in IE11 (just open the right side in it's own window), then scroll to the right, and then open Print Preview and see that column headers and column data are not aligned.

Screenshots:
![before print preview](https://user-images.githubusercontent.com/19378280/36594569-ec3979f6-189e-11e8-84a3-cc9b08f218b7.png)
![print preview](https://user-images.githubusercontent.com/19378280/36594570-ec5a6f9e-189e-11e8-9b79-fd20b1fab6cd.png)

**What is the motivation / use case for changing the behavior?**

Being able to print a horizontally scrolled grid where column headers and column data are aligned correctly.

**Please tell us about your environment:**

Windows 10

* **ag-Grid version:** 16.0.1

* **Browser:** Internet Explorer 11

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
