### ISSUE TITLE
Toggling a column visibility outputs 'columnVisible' to the console

### ISSUE THREAD

**Issue by stoyandamov** [ag-grid/ag-grid#2226]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Every time I toggle a column's visibility from the tools panel the console logs 'columnVisible'

**Expected behavior**
Column's visibility should toggle and nothing should be logged on the console

**Minimal reproduction of the problem with instructions**
Change any column's visibility and observe as the console logs 'columnVisible'

**What is the motivation / use case for changing the behavior?**
It's a annoying bug which adds noise to the console's log

**Please tell us about your environment:**
MacOS, WebStorm, npm, node

* **ag-Grid version:** 16.0.1 (enterprise)

* **Browser:**

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
