### ISSUE TITLE
Getting error while specifying cellRendererFramework component within detailCellRendererParams

### ISSUE THREAD

**Issue by mskhanse** [ag-grid/ag-grid#2227]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Getting following error while specifying cellRendererFramework component `"cellRendererFramework": CheckboxCellComponent` for `[detailCellRendererParams]="detailCellRendererParams"` in `ng-grid-angular` with `[masterDetail]="true"`

Below framework component is working fine for `gridOptions` but throwing error for `detailGridOptions`

> ag-grid: you are specifying a framework component but you are not using a framework version of ag-grid for : cellRenderer at ComponentResolver.getComponentToUse

```
detailCellRendererParams = {
    detailGridOptions: {
    frameworkComponents: {
        "checkboxCellComponent": CheckboxCellRenderer
      },
      columnDefs: [
        {
          "field": "isActive",
          "cellRendererFramework": CheckboxCellRenderer
        }
    ]}
};
```

Checkbox Renderer Component

```
import { Component, AfterViewInit } from '@angular/core';
import { ICellRendererAngularComp } from 'ag-grid-angular';

@Component({
  selector: 'checkbox-cell',
  template: `<mat-checkbox [ngModel]="params.value" (change)="onChange($event)"></mat-checkbox>`
}) 
export class CheckboxCellRenderer implements ICellRendererAngularComp {

  private params: ICellRendererParams;

  constructor() { }

  agInit(params: ICellRendererParams): void {
    this.params = params;
  }   

  onChange(event) {
    this.params.data[this.params.colDef.field] = event.checked;
  }

  refresh(params: ICellRendererParams): boolean {
    return true;
  }
}
```

* **ag-grid-angular version:** 16.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 16.0.1

* **Angular version:** 5.0.0

* **Language:** 
Angular
TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
