### ISSUE TITLE
agDateColumnFilter does not take effect

### ISSUE THREAD

**Issue by andymartin** [ag-grid/ag-grid#2229]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When configuring a date column to use agDateColumnFilter, the selector opens but the filter never takes effect.

**Expected behavior**

Filter should take effect after value is entered.

**Minimal reproduction of the problem with instructions**

```
var historyGridOptions = {
    columnDefs: [
        { headerName: "Timestamp", field: 'Timestamp', filter: 'agDateColumnFilter' },
        { headerName: "User Name", field: "UserName" },
        { headerName: "Machine Name", field: "MachineName" },
        { headerName: "Type Name", field: "TypeName" },
        { headerName: "Property Name", field: "PropertyName" }
    ],
    enableFilter: true,
    enableSorting: true,
    enableColResize: true,
    suppressCellSelection: true
};

function configurePropertyHistoryGrid(data) {
    historyGridOptions.rowData = data;

    var div = document.getElementById('property-history-grid');
    div.innerHTML = '';
    new agGrid.Grid(div, historyGridOptions);
}
```

**What is the motivation / use case for changing the behavior?**

Filter log by date of timestamp (which is a javascript datetime).

**Please tell us about your environment:**

Windows, VS2017, bower, IIS

* **ag-Grid version:** X.X.X

v16.0.1

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by shinkle-orbytel** [comment]
Seconded... this feature is completely broken.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
