### ISSUE TITLE
large css output size when using scss

### ISSUE THREAD

**Issue by dominikg** [ag-grid/ag-grid#2230]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

css output when building with scss contains many rules with duplicated content and rules that are only needed for a few usecases 
* 50 levels of indentation
* rtl support
* bootstrap theme duplicates icons
* each icon rule contains a lot of duplicated elements

**Expected behavior**
* optimized generated rules
* no duplications
* configuration options to remove rules only relevant for specific features
** switch to disable rtl
** variable for max indentation level

**Minimal reproduction of the problem with instructions**

build css with scss
src/styles.scss
```
$ag-icons-path: "../node_modules/ag-grid/src/styles/icons/";
@import "../node_modules/ag-grid/src/styles/ag-grid";
@import "../node_modules/ag-grid/src/styles/ag-theme-bootstrap";
```

the current behavior can also be observed in the official dist css:
https://github.com/ag-grid/ag-grid/blob/master/dist/styles/ag-grid.css
https://github.com/ag-grid/ag-grid/blob/master/dist/styles/ag-theme-bootstrap.css

**What is the motivation / use case for changing the behavior?**

reduce css bundle size of an angular-cli based spa that uses ag-grid

**Please tell us about your environment:**

* **ag-Grid version:** 16.0.1

* **Browser:**

* **Language:** scss

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
