### ISSUE TITLE
Pagination provides wrong total row count when used with Enterprise row model

### ISSUE THREAD

**Issue by aleksandrs-oks** [ag-grid/ag-grid#2231]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

We use enterprise row model with enterprise datasource. We subscribe to the grid's onPaginationChanged to update our custom paginator data.
In case when the datasource provides 0 results, the api.paginationGetRowCount() method returns 1

**Expected behavior**

As we understand from the docs, paginationGetRowCount -The total number of rows
We expect, that when the datasource is empty, api.paginationGetRowCount() should return 0, but not as it does for us.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/9cD0sC?p=preview

**What is the motivation / use case for changing the behavior?**

We are showing search results in the grid with our customized paginator. And we need to show how many search results user has in the paginator . when user finds nothing we want to show, that there are no results. But now user sees, that he has found 1

**Please tell us about your environment:**

Windows 7, VS Code, npm, Angular2,

* **ag-Grid version:** X.X.X

 "ag-grid": "^16.0.1",
    "ag-grid-angular": "^16.0.0",
    "ag-grid-enterprise": "^16.0.1",

* **Browser:**

Chrome ("Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36")

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
