### ISSUE TITLE
Master Detail no expanding row

### ISSUE THREAD

**Issue by jimboharrison** [ag-grid/ag-grid#2235]
**I'm submitting a ...**
`
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request 

**Current behavior**
Hi, I am using Aurelia to implement the in memory model ag-grid. I am attempting to implement the master detail pattern with no table inside the detail cell, just some custom html... From what I can see, simply enabling 'masterDetail' on the gridOptions should be enough to allow for the expanding of rows. My problem is that adding the setting to the gridoptions doesn't seem to change anything.

**Expected behavior**
I would expect by simply setting **masterDetail: true** that the rows could be expanded. I understand this is an enterprise feature and to prove that other enterprise features are working I have adding exporting to excel with no problems.

**Minimal reproduction of the problem with instructions**
Although hard to reproduce my current dev version since in aurelia, I have created a plunkr with similar behaviours via my stackoverflow quesiton: https://stackoverflow.com/questions/49107968/ag-grid-master-detail-not-allowing-expanding-row

**Please tell us about your environment:**
using Windows 10 with NPM and aurelia CLI

* **ag-Grid version:**
 ag-grid v16.0.1

* **Browser:**
Have tried on browsers : Chrome, IE, Edge

* **Language:** 
Typescript, aurelia

**Comment by vbutrim** [comment]
Is there any update from ag-grid community? 
Have the same issue, I guess..

**Comment by andrey-kokoev** [comment]
having same issue for the last 2 days

**Comment by reignmaker** [comment]
@oprodev did you specify `cellRenderer` for the first column? As stated in the docs (in the first exmple) you must specify it as `cellRenderer: 'agGroupCellRenderer'` otherwise it won't render needed controll.

**Comment by makinggoodsoftware** [comment]
Hi guys,

It does sound like you found a solution for this, I am going to close it now, but feel free to open a new issue if you think this is still a problem

Thanks

**Comment by robruiz** [comment]
reignmaker is AWESOME!

**Comment by DominikSammerLocoso** [comment]
Hi!

I had the same issue. What I am trying to reach is to create a grid that is able to display two childs under one parent. Something like the following plunker: [https://plnkr.co/edit/yuBkW4Rxzx5yKcNGRh64?p=preview].
The thing here is, I am trying to reach that with a serverside datasource. But when I implement that i do not get the arrow to open the details, it looks like that:
![1](https://user-images.githubusercontent.com/41911485/54606805-15314b00-4a4d-11e9-888c-4056f3c92c86.PNG)

Actually I do not understand why because in this Artnumber column I added the cellRenderer "agGroupCellRenderer".
The column was defined like that: 
```
const columnDefinition = new AgGridColumn();
            if (gridConfig.listConfiguration.childLists && gridConfig.listConfiguration.childLists.length > 0 && !addedCellRenderer) {
                this.masterDetail = true;
                columnDefinition.cellRenderer = 'agGroupCellRenderer';
                this.detailCellRendererParams = {
                    childConfiguration: gridConfig.listConfiguration.childLists
                };
                addedCellRenderer = true;
            }

            columnDefinition.colId = gridColumnContract.columnName;
            columnDefinition.headerName = gridColumnContract.labelMls;
            columnDefinition.field = gridColumnContract.columnName;
```

My grid is using a customized cell renderer that was defined like that in the html template:

```
<ag-grid-angular
    #gridElement
    [masterDetail]="componentService.masterDetail"
    [detailCellRenderer]="detailCellRenderer"
    [detailCellRendererParams]="componentService.detailCellRendererParams"
... some other grid configs
  >
  </ag-grid-angular>

```
And this componentService.detailCellRenderer is updated in this component service like that:
`this.detailCellRenderer = 'myDetailCellRenderer';`

My detailCellRenderer was specified in the frameworkComponents before:
```
this.frameworkComponents = {
      customLoadingOverlay: LapsDatagridLoadingComponent,
      lapsPartialMatchFilter: LapsPartialMatchFilter,
      lapsDetailCellRenderer: LapsDatagridDetailCellRendererComponent
    };
```
And this detail cell renderer is doing nothing else than displaying data:
`<div>hi</div>

<div *ngFor="let detailGridConfiguration of lapsDatagridConfiguration" id="detailGrid">
  <div>{{ detailGridConfiguration.listConfigurations[0].id}}</div>
  
    <ag-grid-angular
                 #agGrid 
                 style="width: 100%; height: 50%;"
                 id="detailGrid"
                 class="full-width-grid"
                 [columnDefs]="colDefs"
                 [rowData]="rowData"
             >
            </ag-grid-angular>
    <br/>
</div>`

I am using the following versions of ag grid:
    "ag-grid-angular": "^20.1.0",
    "ag-grid-community": "^20.1.0",
    "ag-grid-enterprise": "^20.1.0",

What am I doing here wrong?

**Comment by developerpnal** [comment]
Facing same issue as @DominikSammerLocoso - I've set agGroupCellRenderer for first column in master grid, still that action button is not showing.

Below are the versions that I have in my package.json file 

"ag-grid": "18.1.2",
"ag-grid-angular": "19.0.0",
"ag-grid-community": "19.0.0",
"ag-grid-enterprise": "19.0.0",

I also tried by updating above packages to their latest version but still not working.

**Comment by DominikSammerLocoso** [comment]
Hi!

I found a solution for that problem.
It seems that that action button is only showing when the masterDetail property of the grid is set to true in the correct time. What I mean with correct time, I was trying to create the grid dynamically by loading the not only the rows but also the columns and the grid configuration with a server side resource. In my code the masterDetail property ( [masterDetail]="componentService.masterDetail" ) was true but that was the case when the grid was created and already showed. That is too late. What you have to do is setting this masterDetail property to true before the grid is shown.
I solved it by adding an ngIf to the html declaration of the grid so that the grid is not shown as long as the master detail property was not declared:
<ag-grid-angular
*ngIf="componentService.masterDetail !== null"
(gridReady)="onGridLoaded($event)"
.... >

To load the data of the grid I added the (gridReady) event and inside the method I am loading the data of the grid. 

All other things stayed the same and suddenly everything worked well.

Unfortunally that behaviour isn't that good as I think. When I bind a value I am expecting the grid to recognize changes also when it was already created. I was thinking of a case that the grid is dynamically loaded and the user want to decide wether the details can be shown or not. In the current implementation the only way to make that possible would be a complete recreation of the grid. So there is a solution but not an ideal one. Maybe we could fix that in the future.

**Comment by epiphanizer** [comment]
I had missing icons but not the same problems mentioned up here. If you are in Angular, make sure that you are importing the icon assets before build from the /node_modules path within your angular.json. That helped me get the icons to show when they were missing.

**Comment by waratah** [comment]
Must be first column AND the column must exist in the data (I copied name as the column name, when I switched to serviceNumber it appeared)

**Comment by jackdh** [comment]
I found that you had to make sure that the cell has some data in it. Simply adding `valueGetter: () => "X"` was enough.

**Comment by Vacarov** [comment]
> @oprodev did you specify `cellRenderer` for the first column? As stated in the docs (in the first exmple) you must specify it as `cellRenderer: 'agGroupCellRenderer'` otherwise it won't render needed controll.

Yes, this works! The question is: is this a normal think to do so ?  Probably not!

As I understand the purpose of 'agGroupCellRenderer' is slightly different and it refers to the groups, but detailCellRenderer is not a group. My opinion that is better to not clue the fields/attribute when there are different purposes, because immediately others issues:
What if the cellRenderer has already something else, for example a custom component from the user ?
