### ISSUE TITLE
v 17.0.0 new tool panel floods console log with misspelled warnings

### ISSUE THREAD

**Issue by coopernyc** [ag-grid/ag-grid#2239]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Misspelled and I think unnecessary warnings in console log

![image](https://user-images.githubusercontent.com/11201225/37177611-fab7f3e6-22ed-11e8-8305-76a35b1a73ea.png)

**Expected behavior**
I think it should not log at all. Seems like debug information for developers

**Minimal reproduction of the problem with instructions**
npm i ag-grid@17.0.0

**What is the motivation / use case for changing the behavior?**
noticed other console.log when selectingAll in ToolPanel in new code that unnecessary floods the console. I think it relates to #2226 

**Please tell us about your environment:**
Win, npm

* **ag-Grid version:** 17.0.0
issue in most recent version

* **Browser:**
Electron App, Chromium

* **Language:** [all | TypeScript 2.7.1 | ES6/7 | ES5]

**Comment by jakeboone02** [comment]
#2243 fixes the misspelling

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks

**Comment by jakeboone02** [comment]
The extraneous logging is fixed, but the misspelling is still there.  See https://github.com/jakeboone02/ag-grid/blob/latest/src/ts/widgets/component.ts#L138 where "count" should be "could".
