### ISSUE TITLE
Export to CSV/Excel in pivot mode in Enterprise model

### ISSUE THREAD

**Issue by invisor** [ag-grid/ag-grid#2247]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I can't download data that exported to CSV

**Expected behavior**
I want to download data from table via Excel/CSV export

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/iEdd4NMRv4LJx5cQ5jdK?p=preview - example from your docs as is
1. Enable pivot mode
2. Try to export to CSV via context menu
3. Getting error in console
<img width="1680" alt="2018-03-13 15 25 14" src="https://user-images.githubusercontent.com/10770118/37330250-0ffda33e-26d3-11e8-8ea3-eeaa92261dc0.png">

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Operating systems: macOS High Sierra 10.13.3, Windows 10
IDE: VS Code
Package manager: npm

* **ag-Grid version:** 16.0.1-17.0.0
Both of this versions are not working correctly

* **Browser:**

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
