### ISSUE TITLE
add comment in cells

### ISSUE THREAD

**Issue by gbelmm** [ag-grid/ag-grid#2251]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

please add comment in cells
**Expected behavior**
 
![commentinsert01](https://user-images.githubusercontent.com/731936/37437440-04c362de-27cc-11e8-932b-a3ba775e08a9.png)

**Comment by gbelmm** [comment]
??

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

At the moment is very difficult to create popups in ag-grid that stick to the row, we are working in building a new feature to allow you to have popups that stick to the cell, so you will be able to do stuff similar to the comments in excel

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Note that this is parked as of this time, just because of its complexity, which means that even though we are aware of this issue, we don't have any easy solution as of this time

This is the reference and summary of the relevant issue:

AG-1754	Rendering - tooltip/dropdown renderer elements showing behind the grid	BACKLOG
AG-1617	Allow complex tooltip/renderer components in ag-grid to stick to the row as the user scrolls	BACKLOG

**Comment by althaf004** [comment]
Is this feature available in ag-grid
