### ISSUE TITLE
SetFilterModel isnot working on Filter Instance in react ag grid

### ISSUE THREAD

**Issue by lohiyabh** [ag-grid/ag-grid#2256]
**I'm submitting a ...**  (check one with "x")
```
SetFilterModel isnot working on Filter Instance in react ag grid
```

**Current behavior**
Code example from ag grid react documentation is not working -

 var countryFilterComponent = this.gridApi.getFilterInstance("country");
    countryFilterComponent.selectNothing();
    countryFilterComponent.selectValue("Ireland");
    countryFilterComponent.selectValue("Great Britain");
    this.gridApi.onFilterChanged();

selectValue is not there with countryFilterComponent. 

Do we need to set something to get this?

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

can you please explain why we are not able to set "selectValue" on a selected filter  instance? is it an enterprise feature?

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

17.0.0

* **Browser:**

all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React js

**Comment by lohiyabh** [comment]
Hi Team,

It would be great if you can please look into the above issue?

Just to reiterate the above issue, Column filtering is mentioned as the core feature of react ag grid as per the documentation but while we trying ti use setModel() on column instance like this for example -
-
    var countryFilterComponent = this.gridApi.getFilterInstance("country");
    var model = ["Algeria", "Argentina"];
    countryFilterComponent.setModel(model);

we are not able to call setModel() on countryFilterComponent

In fact countryFilterComponent does not have any property as Model to it

is this a enterprise feature?

Regards,
Bharat Lohiya
+91-8380080074

**Comment by Bema** [comment]
You should be passing to setModel an object with `type` and `values` properties.


```javascript
countryFilterComponent.setModel({
   type: 'set',
   values: ['Brazil', 'Ireland', 'South Africa', 'Australia', 'England'] 
})
```

**Comment by Kfir-Miller** [comment]
+1

**Comment by Kfir-Miller** [comment]
was this issue solved ?

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by bbohling** [comment]
i am seeing this behavior (`setSortModel` can be set programmatically but not `setFilterModel`) in an angular 6 app as well. will see about creating an example.

**Comment by makinggoodsoftware** [comment]
As the other two thread, let us have a look, we will update the issues as soon as possible.

Thanks!

**Comment by makinggoodsoftware** [comment]
#2293 Duplicate
