### ISSUE TITLE
ag-grid pinned column keep resizing 

### ISSUE THREAD

**Issue by vishalgajjar** [ag-grid/ag-grid#2265]
**I'm submitting a ...**  (check one with "x")
```
[x] support request 
```

**Grid's pinned column on the right is keep resizing back and forth**

Steps:
1. Zoom out browser window to 67%
2. Have enough number of rows to fill the grid height
3. Pin the column to right side

**Grid's pinned column should not keep resizing in the certain resoluation**

Here is the plukr for reproducing the issue 

https://plnkr.co/edit/Xfaz2dJMP5P77abGvNHt?p=preview

**Angular4, Java, Webstorm, Gulp **

*ag-Grid version: v14.2.0** 

* **Chrome Version 65.0.3325.162**

* **Language: TypeScript :2.0.3**

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
