### ISSUE TITLE
Ag-grid React. Custom header not detecting touch events

### ISSUE THREAD

**Issue by eurrizaga** [ag-grid/ag-grid#2267]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using a custom header component in Ag-grid React, said component seems to ignore touch events in Chrome DevTools Device mode, as well as 2 different touch devices I've used to test it. Both column dragging and resizing seem to be working as expected, though
**Expected behavior**

Allowing to capture events on the header would allow to run custom sort and filtering functions on a custom header component.
**Minimal reproduction of the problem with instructions**

This behaviour can be reproduced from ag grid website's examples
1 - Go to https://www.ag-grid.com/javascript-grid-header-rendering/
2 - Open Chrome Devtools (F12)
3 - Toggle device toolbar (Ctrl+Shift+M)
4 - Scroll to the React Header rendering example
5 - Attempt to use sort functions provided by the example

As far as I've noticed this only seems to be a problem in React, since the Angular example seems to be working

**What is the motivation / use case for changing the behavior?**

Using custom header functions.

**Please tell us about your environment:**

Ubuntu 16.04

* **ag-Grid version:** 17.0.0

* **Browser:**

Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Mobile Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2180 - React. Custom header not detecting touch events [likely because of synthetic events]

**Comment by Agent-R-QT** [comment]
Hello, the issue appears to no longer in the pipeline however in Vue using ag-grid version 31.3.2, and also in the [link provided in the original comment](https://www.ag-grid.com/javascript-grid-header-rendering/) this issue is still persistent. As this is a few years since this was closed I'll give the same info as the opened one:
I'm submitting a ... (check one with "x")

[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question

Current behavior

On mobile, and when using Chrome Dev Tools Ag Grid custom header components are ignoring touch events. This causes custom buttons/click functionalities added to header components to not be accessible outside desktop.
Expected behavior

The ability to handle touch events inside of header components. To then allow for things such as:
- Custom sorting trigger detection
- Custom menu/dropdown implementations
- Any other functionality that would use a click event as the trigger/source

Minimal reproduction of the problem with instructions

This behaviour can be reproduced from ag grid website's examples
1 - Go to https://www.ag-grid.com/javascript-grid-header-rendering/
2 - Open Chrome Devtools (F12)
3 - Toggle device toolbar (Ctrl+Shift+M)
4 - Scroll to the React Header rendering example
5 - Attempt to use sort functions provided by the example

What is the motivation / use case for changing the behavior?

I have an implementation that uses a component that takes over most of the header functionalities, currently this does not work on mobile.

Please tell us about your environment:

    **Operating System:** macOS Sonoma 14.5 + iOS 17.5.1

    **ag-Grid version:** 31.3.2

    **Browser:** Chrome


    Language: [all | TypeScript X.X | ES6/7 | ES5]
    all

**Comment by sabahang** [comment]
@Agent-R-QT the link you have tagged doesn't take me to any specific examples. 

Could you please send an anchor link? Alternatively send us the link to JS plnkr from the example with steps to reproduce 

Thanks
