### ISSUE TITLE
Horizontal Columns and Hide Column Headers

### ISSUE THREAD

**Issue by 8gentile** [ag-grid/ag-grid#2273]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

There is no option to turn the grid on its side and have the columns displayed vertically. When trying to emulate this treatment with a column of "labels" and another column of "values", there is no option to hide the column headers only ("hide" hides the whole column).
**Expected behavior**

It would be nice to have a param in the column defs called "hideColumnHeader". It would also be nice to have an option on the grid called "enableHorizontalColumns".

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
