### ISSUE TITLE
Infinite row model + enableServerSideSorting causes two requests initially

### ISSUE THREAD

**Issue by egidijusj** [ag-grid/ag-grid#2275]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using `rowModelType="infinite"` and `enableServerSideSorting="true"` as AgGridReact props causes two requests to be issued initially one after another

**Expected behavior**

Should issue single request to server initially

**Minimal reproduction of the problem with instructions**

Reproduced here: https://plnkr.co/edit/tnTK5S268p4SEfuJn3Il?p=preview
The header above the grid contains count of requests made.

**What is the motivation / use case for changing the behavior?**

Bug causes more load on server than is actually required

**Please tell us about your environment:**

Ubuntu

* **ag-Grid version:** 17.0.0

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0

* **Language:** all

**Comment by pajamu** [comment]
Also interested...

**Comment by kakabomba** [comment]
same bug with angular component
`"ag-grid": 17.1.1`
`"ag-grid-angular": 17.1.0`

**Comment by pshurygin** [comment]
This is still an issue with version 18.0.1.
Our datasource requests could be really heavy and time-consuming, so this issue is really painful.

**Comment by pshurygin** [comment]
One way to workaround this issue is to debounce getRows() function with a small parameter(like 50ms). It works but effectively adds a 50ms delay on every datasource call.

Another way is to set datasource via grid api only after grid is initialized. This adds a delay on initialization and requires some additional logic to be added for every grid in the app.

Neither solution is great, so a fix would be really appreciated.

**Comment by ckrasi-acx** [comment]
Setting datasource after initialization indeed solves the problem. And not as much boilerplate code needs to be written - in my case I replaced `[datasource]=datasource` with (gridReady)="$event.api.setDatasource(datasource)". Works fine.
Nevertheless, waiting fot this issue to be fixed.

**Comment by lukemartin** [comment]
We are also experiencing this problem, and as a result have had to disable server-side sorting altogether.

**Comment by dagi12** [comment]
Affects me to. Setting datasource after gridReady callback solves the problem.

**Comment by tomasreichmann** [comment]
I have a very similar issue. We use getRows to get both rows and columnDefs on the first block load. This works great without enableServerSideSorting: true. When server side sorting is enabled, it checks if columnDefs have been updated and reruns getRows, because sorting might have been affected by the change in columnDefs. So all changes in sorting always make two requests. We update colDefs to reflect complex sorting rules. I found no way to stop a redundant getRows execution. 

Would it be possible to add option to suppress resetingRowCache when colDefs are updated?
E.g. resetRowCacheOnColDefsUpdate: true | false.
Is it likely someone would merge my PR if I added it?

**Comment by sebastianvcruz** [comment]
I also ran into this problem and I got it solve by setting `gridOptions.enableServerSideSorting = true;` after `params.successCallback(rowsThisPage, lastRow);` at the end of the getRow function.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2190 - Infinite row model + enableServerSideSorting ensure only one request is made initially
