### ISSUE TITLE
Reverse arrow direction of sorting

### ISSUE THREAD

**Issue by mattwmj** [ag-grid/ag-grid#2281]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
down arrow ascending sort
up arrow descending sort

**Expected behavior**
up arrow ascending sort
down arrow descending sort

**Minimal reproduction of the problem with instructions**
https://www.ag-grid.com/javascript-grid-sorting
click any sorting example

**What is the motivation / use case for changing the behavior?**
Users prefer same sort arrow direct with MS Windows and MS Office

**Please tell us about your environment:**
Windows, Webpack, tomcat

* **ag-Grid version:** 
17.0.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by petyosi** [comment]
Thanks for raising this, you are correct. An in-depth discussion about the correct icons can be found here: https://ux.stackexchange.com/questions/37564/use-up-or-down-arrow-to-represent-sort-ascending-at-table-header 

I am logging this as AG-1691 in our internal bug tracker.

**Comment by tflavin** [comment]
@petyosi I see that you swapped the asc/desc icons here: https://github.com/ag-grid/ag-grid/commit/ad2884a5d790473c46b49a0b49907c270b54889d, and that this was done for baltham-icons, icons, and material-icons.

However, it looks like only the baltham-icons were incorrect as described by this issue. 
The asc/desc arrow is the opposite direction compared to the icons and material-icons sets.

So, since those were also swapped as part of this bug, I believe that the icons in those two sets are now incorrect:

> **Current behavior**
> down arrow ascending sort
> up arrow descending sort
> 
> **Expected behavior**
> up arrow ascending sort
> down arrow descending sort

For reference:
https://github.com/ag-grid/ag-grid/blob/master/src/styles/balham-icons/asc.svg
https://github.com/ag-grid/ag-grid/blob/master/src/styles/balham-icons/desc.svg

https://github.com/ag-grid/ag-grid/blob/master/src/styles/icons/asc.svg
https://github.com/ag-grid/ag-grid/blob/master/src/styles/icons/desc.svg

https://github.com/ag-grid/ag-grid/blob/master/src/styles/material-icons/asc.svg
https://github.com/ag-grid/ag-grid/blob/master/src/styles/material-icons/desc.svg

**Comment by petyosi** [comment]
Thanks for the heads up @tflavin - you are correct. Fixing this.
