### ISSUE TITLE
AG Grid Loading issue with different bundler / loaders

### ISSUE THREAD

**Issue by tipsanemonk** [ag-grid/ag-grid#2285]
Hi,

I've been trying to include `agGrid` to my application which uses requirejs and gulp. I'm trying to use the angular 1.x version and  I've included `agGrid` to be bundled with the final minified `application.js` but I've been getting the following error.  

`Error: Mismatched anonymous define() module: function ()`

![capture](https://user-images.githubusercontent.com/7473278/38136871-f19c7572-343e-11e8-887c-87b3df6befa8.PNG)

![capture](https://user-images.githubusercontent.com/7473278/38136977-83e71f36-343f-11e8-8107-61bcf3822eef.PNG)

This seems more like a conflict with requirejs.  Any solution?

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
