### ISSUE TITLE
Unable to resize window automatically if we unselect a column using Tool Panel(pivot mode)

### ISSUE THREAD

**Issue by arunpalani-vbi** [ag-grid/ag-grid#2304]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

After Unselecting a column from pivot, Resizing the browser fits the table to the dom size.
**Expected behavior**

It should fit to size after unselecting from pivot menu(without resizing the browser window)
**Minimal reproduction of the problem with instructions**

[https://plnkr.co/edit/mhTQryYWPdTkyzkzdPmG?p=preview](https://plnkr.co/edit/mhTQryYWPdTkyzkzdPmG?p=preview)
**What is the motivation / use case for changing the behavior?**

we are having OEM Ag-grid license, we had this requirement for many of our customers.
**Please tell us about your environment:**

Windows 10 Pro x64 / Visual Studio Code
* **ag-Grid version:** X.X.X

Ag-Grid 17(Enterprise) (ag-grid-react)
* **Browser:**

Chrome 65.0.3325.181
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Jsx/React

**Comment by makinggoodsoftware** [comment]
Hi,

Unfortunately we can't tell what your issue is given your description. 

This ticket is going to nbe flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
