### ISSUE TITLE
Cell Editor not working

### ISSUE THREAD

**Issue by goel-sunny** [ag-grid/ag-grid#2305]
Cell editor both customize and user define is not working , I have try all the samples in my project none of them working ,

define editable = true and cellEditor = agTextCellEditor and customize one but none of them working.

I am using angular 2+ , I have also specify in FrameworkComponent option and also in the app.module.ts file in the ag-grid-module component option ,

I have read and execute the all steps carefully but none was working for me.

One more question is ag-grid-angular is using any native compiled code ( like when we install the ng-angular-grid it also build something natively using node-gyp tool )

so is it using any native call or functionality in case of cellEditor feature.

Please reply fast .

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
