### ISSUE TITLE
Tree Table With Infinite Scrolling?

### ISSUE THREAD

**Issue by jayrungta** [ag-grid/ag-grid#2307]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently, infinite scrolling and tree tables are not supported together, or if they are there is no documentation that suggests so.

**Expected behavior**

Tree tables can be used with infinite scrolling.

**What is the motivation / use case for changing the behavior?**

In my use case, I have a tree table which needs to have infinite scrolling. That is due to the fact that there is a lot of data.
Can someone tell me if this is possible? If not, consider this a feature request. I am open to hacks/workaround suggestions too that could make this possible.

**Comment by isaacsanders** [comment]
Does the Enterprise Row Model not work for this?

**Comment by Brightness99** [comment]
@jayrungta I have the same issue. Did you find a solution?

**Comment by jayrungta** [comment]
@Brightness99 this is going to be added in the next release to the enterprise/server-side row model. Should be out by next week is my guess. Can't wait!

**Comment by thedanchez** [comment]
Is this issue closed? I am using AG Grid SSRM Tree Data (v30) and I am trying to configure infinite scrolling for it but I do not see the server side datasource making requests for infinite scrolling capabilities. 

For example, I only ever receive one single request with `startRow`/`endRow` when I expand a tree group in the grid but I never receive another request when scrolling through that group because the current expectation appears to be that you have to return all the child group data up-front and not in a partial manner. 

If this is not resolved can this issue please be reopened? Or if it is, can someone please post documentation on how to get infinite scroll working with AG Grid SSRM Tree Data?

**Comment by AG-Zoheil** [comment]
Hi @thedanchez,

Thank you for your comment.

We'd be keen to look into this again, but as you can see this is quite an old issue from **more than five years ago**. The grid has naturally advanced a lot since then. 

Based on your description, this page in our documentation should provide good guidance: https://ag-grid.com/javascript-data-grid/server-side-model-tree-data/.
However, if you are still having problems, can we please ask you to open a new issue with a reproducible live scenario - you can use one of the plunker examples from our [documentation](https://ag-grid.com/javascript-data-grid/) as a starting point.

This would help our team support in the most efficient way, and also increase visibility for the wider AG Grid community in case of contributions and comments.

Much appreciated!

Kind regards,
Zoheil
