### ISSUE TITLE
Broken behavior in documentation - user cannot start editing cell

### ISSUE THREAD

**Issue by catahoc** [ag-grid/ag-grid#2308]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
See example in "Controlling keyboard while editing" section
https://www.ag-grid.com/javascript-grid-cell-editing/
Using angular/react user cannot start editing cell

**Expected behavior**
Expected behavior should be to inc/dec value in cell

* **Browser:**
Chrome

I'm omitting most New issue fields, because defect is reproduced on official docs page

**Comment by catahoc** [comment]
I bet it is not documentation issue, its regression bug

**Comment by catahoc** [comment]
Oh shit, looks like I misunderstood feature a bit :(

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
