### ISSUE TITLE
"getModelAsString" for custom filters injected with "filterFramework" is never called

### ISSUE THREAD

**Issue by sparqueur** [ag-grid/ag-grid#2309]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm using the angular version of ag-grid.
I've created a custom Filter
```typescript
export class AgBooleanColumnFilter implements IFilterAngularComp {
    ...
    public text: boolean = null;
    ...
    getModelAsString(): string {
        return this.text !== null ? "" + this.text : "";
    }
    ...
}
```

When I inject it in my table using '**filterFramework**', **getModelAsString** is not called and the floating filter is editable :
```typescript
            {
                ...
                filterFramework: AgBooleanColumnFilter,
                ...
            }
```

When I inject it in my table using 'filter', everything is fine (**getModelAsString** is called and the floating filter is not editable) :
```typescript
            {
                ...
                filter: 'AgBooleanColumnFilter',
                ...
            }
         ...
        frameworkComponents = {
            AgBooleanColumnFilter: AgBooleanColumnFilter
        }
```
**Expected behavior**

Custom filter **getModelAsString** should be called when injecting the filter with **filterFramework**

**Minimal reproduction of the problem with instructions**

Create a custom filter with a **getModelAsString** method. Inject it in your table using **filterFramework**

**What is the motivation / use case for changing the behavior?**

I expect the same behavior using **filter** and **filterFramework**

**Please tell us about your environment:**

Angular version of ag-grid
Windows 10, VScode, np

* **ag-Grid version:** X.X.X

"ag-grid": "^17.0.0",
"ag-grid-angular": "^17.0.0",

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by supreethaPavank** [comment]
getModelAsString was not getting fired for the ag-grid community version 19.0.0 , however when I updated the version to 19.1.4 , it started working

**Comment by kashpatel** [comment]
I could still see this issue in "ag-grid-community": "^22.1.1". I have custom filterComponent in angular and getModalAsString does not get called at all.

If I use the work around as as suggested above, then it works.
```
 {
    ...
    filter: 'AgBooleanColumnFilter',
     ...
 }
 
in Grid options:
frameworkComponents = {
     AgBooleanColumnFilter: AgBooleanColumnFilter
}
```

Does not work with colDef.filterFramework
```
{
     ...
     filterFramework: AgBooleanColumnFilter,
     ...
}
```

I tracked down the issue to following line in code. The variable (called "promise") returned by this.userComponentFactory.newFloatingFilterComponent is undefined. It is defined when I use above workaround.
 
https://github.com/ag-grid/ag-grid/blob/master/community-modules/core/src/ts/filter/floating/floatingFilterWrapper.ts#L223
