### ISSUE TITLE
Column Grouping Collapsed/Expanded state is inverted

### ISSUE THREAD

**Issue by nitro52** [ag-grid/ag-grid#2317]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using column grouping the ag-header-expand icons do not match the expand/collapse states of the actual grid. 

For example the DOM elements taken from your demo when the coloum group is collapsed (not showing children) looks like this

```
<div class="ag-header-group-cell-label" ref="agContainer">
	<span ref="agLabel" class="ag-header-group-text">Performance</span>
	<span ref="agOpened" class="ag-header-icon ag-header-expand-icon ag-header-expand-icon-expanded">
		<span class="ag-icon ag-icon-expanded"></span>
	</span>
	<span ref="agClosed" class="ag-header-icon ag-header-expand-icon ag-header-expand-icon-collapsed ag-hidden">
		<span class="ag-icon ag-icon-contracted"></span>
	</span>
</div>
```

But this reflects that the group should be expanded based on the collapse element ("ag-header-expand-icon-collapsed") containing the "ag-hidden" class

**Expected behavior**
The behaviour should be inverted to match the class names or the class names changed to match the behaviour.

**Minimal reproduction of the problem with instructions**
can be seen on the current demp page https://www.ag-grid.com/example.php with the Performance column group (but the actual icons used have been inverted to reflect expected behaviour)

**What is the motivation / use case for changing the behavior?**
Aligns icons used to match expected behaviour

**Please tell us about your environment:**
Not applicable

* **ag-Grid version:** X.X.X
running 13.2.0 but also tested 17.0.0

* **Browser:**
Not applicable

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
