### ISSUE TITLE
Cannot set autoHeight as boolean (Angular)

### ISSUE THREAD

**Issue by ErwSim** [ag-grid/ag-grid#2318]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When setting autoHeight to true I have following error
`Types of property 'autoHeight' are incompatible.
          Type 'boolean' is not assignable to type 'number'.`

**Expected behavior**
autoHeight to be boolean not a u number

**Minimal reproduction of the problem with instructions**
Add autoHeight: true in the coldef
Example: 
`{
        headerName: 'Action',
        field: 'action',
        autoHeight: true,
        cellRenderer: params => {
          const eDiv = document.createElement('div');
          eDiv.innerHTML = '' + params.value + '';
          return eDiv;
        }
      },`

**What is the motivation / use case for changing the behavior?**
Use of autoHeight

**Please tell us about your environment:**

- Linux Debian 9.1
- Angular 5.2.10

* **ag-Grid version:** 0.17.1

* **Browser:**
navigator.userAgent
"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"

* **Language:** Angular 5.2.10

**Comment by chintans** [comment]
https://github.com/ag-grid/ag-grid/blob/ef2075f75953b064c5fca17601c8ac8170619da7/src/ts/entities/colDef.ts#L122

It should be boolean as per the documentation at https://www.ag-grid.com/javascript-grid-column-properties/

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
