### ISSUE TITLE
Tool panel CSS still active despite [toolPanelSuppressSideButtons]="true"

### ISSUE THREAD

**Issue by crumhorn** [ag-grid/ag-grid#2319]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If you disable the side panel, the CSS for it is still active (shows up in blue with ag-theme-blue for example)

To reproduce, simply set the following either via code or in your template:

`[toolPanelSuppressSideButtons]="true"`

Now look at the grid, you'll see blue borders on the right where the tool panel would be if it was visible.

`[showToolPanel]="false"` seems to have no effect on it, it still shows the blue borders.

**Expected behavior**

Tool panel CSS should not be "active" unless the toolpanel is showing.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 17.0.0

* **Language:** Typescript 2.2

**Temporary workaround**

Adding this to your CSS (adjust for theme) will hide them, and the toolbar sill looks fine once opened.

`.ag-theme-blue .ag-tool-panel {
    border-right: 0;
    border-left: 0;
}`

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
