### ISSUE TITLE
[Bug] [Memory leak] Non-deterministic memory leak when using React cell renderers

### ISSUE THREAD

**Issue by hzub** [ag-grid/ag-grid#2323]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When using `cellRendererFramework` in column definition and putting React components there, I've encountered a following scenario: React components get mounted **twice** upon grid initialization, but demounted only **once** when grid is destroyed - which causes half of them to remain in memory and take up the space.
This behavior, however, is caused **only** when we're trying to render React components in one of leftmost columns of the grid. The bug **does not** occur when we're choosing last columns of the grid as the container for our React component cells. This is super weird, but it indicates that bug might be related to some race condition.
Exact configuration, scenario and even a short movies are in "reproduction" section below.

**Expected behavior**
React components serving as cell renderers are mounted properly upon initialization and unmounted completely upon grid destruction.

**Minimal reproduction of the problem with instructions**

The dataset:
```
[
  {
    "Id": "0",
    "testField": "quis aliqua do",
    "testField2": "dummy1"
  },
  {
    "Id": "1",
    "testField": "commodo proident ut",
    "testField2": "dummy2"
  },
  {
    "Id": "2",
    "testField": "nisi dolor ut",
    "testField2": "dummy3"
  }
]
```

The column definition **which cause** the memory leak (scenario 1):
```
const columns = [
  {
    field: 'testField',
    headerName: 'Lorem ipsum',
  },
  {
    field: 'testField2',
    headerName: 'Test field',
    cellRendererFramework: () => <div>Example</div>,
  },
];
```

The column definition **which doesn't cause** the memory leak (scenario 2):
```
const columns = [
  {
    field: 'testField',
    headerName: 'Lorem ipsum',
  },
  {
    field: 'someDummyField',
    field: 'Foo bar',
  },
  {
    field: 'anotherDummyField',
    field: 'Foo baz',
  },
  {
    field: 'testField2',
    headerName: 'Test field',
    cellRendererFramework: () => <div>Example</div>,
  },
];
```

Field and headers names, labels etc. doesn't matter here. What does matter (and is weird) is the column order.

Memory leak visible in scenario 1 (movie, .mov in ZIP):
[aggridscenario1.mov.zip](https://github.com/ag-grid/ag-grid/files/1923159/aggridscenario1.mov.zip)

Memory leak not occuring in scenario 2 (movie, .mov in ZIP):
[aggridscenario2.mov.zip](https://github.com/ag-grid/ag-grid/files/1923163/aggridscenario2.mov.zip)

*Info that might be relevant:* 
- ag-grid is placed with help of `<AgGridReact />` component.
- data is set by props.
- columns are set by props, but until they appear there - first they're initialized in `gridReady()` event.
- i'm using `columnApi.setColumnState()` to set proper columns widths/visibility, which is called just after setting the columns

**Please tell us about your environment:**

macOS High Sierra 10.13.3, Chrome 65.0.3325.181

* **ag-Grid version:** 17.1.1

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

* **Language:** ES6/7

**Comment by cigriggs** [comment]
Currently evaluating ag-grid and stumbled across this issue. Still present in v18.

- ag-Grid version: 18.0.1
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
- Language: ES6

**Comment by biels** [comment]
Same thing here

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
