### ISSUE TITLE
Bug Render cell filter (example demo)

### ISSUE THREAD

**Issue by 7carlosz** [ag-grid/ag-grid#2325]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

filtering by rendered value does not work

**Expected behavior**

filter correctly by the rendered value

**Minimal reproduction of the problem with instructions**

Demo Page principal
https://www.ag-grid.com/example.php

![captura1](https://user-images.githubusercontent.com/32103511/38952579-8c0d2718-4322-11e8-80b8-22a74e8d2c8b.PNG)

![captura2](https://user-images.githubusercontent.com/32103511/38952679-d4b3a94c-4322-11e8-8ae0-79ec77a73230.PNG)

![captura3](https://user-images.githubusercontent.com/32103511/38952621-b386e9a0-4322-11e8-84db-911fc87e9ffa.PNG)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 17.1.1

* **Browser:**

* **Language:** [all | TypeScript 2.8.1 | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
