### ISSUE TITLE
Grouping rows below data instead of above

### ISSUE THREAD

**Issue by johnyousif** [ag-grid/ag-grid#2327]
Is there a way to enable a grouping row to be at the bottom of the data rather than at the top ie. the children rows flow upwards out of the group row rather than downwards?

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
