### ISSUE TITLE
GridApi hidePopupMenu() does not work

### ISSUE THREAD

**Issue by henry-ham** [ag-grid/ag-grid#2330]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
calling gridApi.hidePopupMenu() does not change anything.

**Expected behavior**
it should hide context menu in header

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 17.1.X

https://plnkr.co/edit/1wEDwMdw7bTthnYI8PzZ?p=preview
added the function calling in onGridReady()

* **Browser:**

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular

**Comment by makinggoodsoftware** [comment]
Hi,

Unfortunately we can't tell what your issue is given your description. 

This ticket is going to nbe flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
