### ISSUE TITLE
Column menu should be rendered in document.body instead of grid container

### ISSUE THREAD

**Issue by dtassone** [ag-grid/ag-grid#2345]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using the column menu, create your react filter implementation. 
Add a classic date picker in your custom filter
=> the date picker renders in the Body element hence a click in the calendar cause the ag grid column menu to close

**Expected behavior**

Aggrid column menu to stay open

**Minimal reproduction of the problem with instructions**

Implement a custom filter react component that uses a date picker
open the filter and the date picker calendar
click one day, the calendar AND the date picker disappear

**What is the motivation / use case for changing the behavior?**

The ag grid column menu should be rendered in the body as it currently cause this issue but also all sort of issues linked to z-index and overflow when having multiple small grids.

**Please tell us about your environment:**

* **ag-Grid version:** 16.0.1

* **Browser:** Chrome 65

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

![datepicker](https://user-images.githubusercontent.com/936978/39257972-b7d689ec-48aa-11e8-95e4-12615264a11a.gif)

**Comment by makinggoodsoftware** [comment]
If you work with dates in ag-grid, and you customize your date editor.

https://www.ag-grid.com/javascript-grid-date-component/

ag-grid Out of the box date picker
Let's start all by saying that if you use the out of the box ag-grid date editor, this will use your browser default date picker if you use chrome, otherwise, you can use gridOptions.browserDatePicker = true

browserDatePicker: This is only taking into consideration if there isn’t a date component provided. By default the grid will use the browser date picker in Chrome and a plain text box for all other browsers (this is because Chrome is the only browser providing a decent out of the box date picker). If this property is true, the browser date picker will be used regardless of the browser type.
If you do so, you will have a drop-down date picker provided from your browser, except if you use IE-11 (more on that later)

If you create your own date picker
Note that if you decide to go for a CUSTOM editor, and you want to make it so that is a dropdown, (ie it shows in a popup), this won't be likely to work on the date filter menu, since when you click anywhere in the date popup, it will close it.

 

This is a known bug, and is tracked in the pipeline with:

AG-1891	Filters - Add a mechanism for keeping the filter menu open
https://www.ag-grid.com/ag-grid-pipeline/

If you want to have a custom popup for a date cell editor you can still use a custom editor

https://www.ag-grid.com/javascript-grid-cell-editing/#datepicker-cell-editing-example

We would recommend you this approach and then, for the date component (used in the column filter column) to let ag-grid use its out of the box one.

 

But I use IE11 and IE doesn't provide date pickers
In this case, we are afraid that for the column menu is going to be very difficult for you to integrate a popup date picker (unless you can stop the click propagation), and then we need to revert to the already mentioned bug AG-1891

Note that we are hoping to have a solution for this soon

Facebook Twitter LinkedIn Google+
