### ISSUE TITLE
Browser Console overwhelmed with "'forPrint' has been deprecated."

### ISSUE THREAD

**Issue by ctokareff** [ag-grid/ag-grid#2348]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
browser's console is full of
ag-grid: Since v17.1.0 domLayout: 'forPrint' has been deprecated. Please use instead auto height

however I do not set domLayout option with any value just as documentation suggests - I need default behavior with scroll bars that was always working for me till latest update

**Expected behavior**
Please restore previous functionality and stop spamming me with errors in console

**Minimal reproduction of the problem with instructions**

I'm using ag-grid and ag-grid-angular
possible root cause: I have following binding in ag-grid-angular tag:
[style.height]="gridHeight" [style.width]="gridWidth"

**What is the motivation / use case for changing the behavior?**
1) previous releases were working just fine
2) I am not setting any domLayout value - why don't you set it correctly?

**Please tell us about your environment:**
VS code, Angular 5, ag-grid enterprise 17.1, ag-grid-angular 17.1

* **ag-Grid version:** X.X.X

* **Browser:**
latest Chrome and Edge

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.4.x

**Comment by CamAnNguyen** [comment]
Seems duplicate [#2316](https://github.com/ag-grid/ag-grid/issues/2316)

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
