### ISSUE TITLE
Error: argument 'scope' is required (colDef.autoHeight: true && angularCompileRows:true)

### ISSUE THREAD

**Issue by ElVisPL** [ag-grid/ag-grid#2352]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Having both options: autoHeight for column and angularCompileRows set to true, causes error from angular: Argument 'scope' is required

**Expected behavior**
Fixing dependencies?

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/nLqcsIyTls7kmDxIMoIP?p=preview
Remove autoHeight: true from one of columns or angularCompileRows 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

17.1.1

* **Browser:**

All browsers
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
