### ISSUE TITLE
Custom params for loadingOverlay and noRowsOverlay components

### ISSUE THREAD

**Issue by namnn** [ag-grid/ag-grid#2375]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

No optional params can be passed to custom overlay components

**Expected behavior**

Has something similar to cellRendererParams for overlayFrameworks which can be obtained inside agInit()

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Customise overlay component - optimise code reuse

**Please tell us about your environment:**

* **ag-Grid version:** 17.1.1

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
