### ISSUE TITLE
Custom Floating Filter not working properly

### ISSUE THREAD

**Issue by varunrramani** [ag-grid/ag-grid#2377]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using custom floating filter component, when the column is not in the view during initializing of the grid i.e. we need to horizontally scroll to see the column. If using a component another than just input field, when focusing on the component, it doesn't work as expected. For example if the component is a drop down, when clicking on it to open the drop down to select an option, the drop down doesn't open. Same thing happens for Autocomplete as well. Also note I am using Angular Material components in the filter components.

**Expected behavior**
The components should work as they would work in normal scenarios or as they are working when the column was visible during grid initialization.

**Minimal reproduction of the problem with instructions**

Add a custom floating filter component with mat-select or mat-autocomplete to a column which can be seen after horizontally scrolling the grid after grid initialisation.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 7, application started from Visual Studio Code console using npm

* **ag-Grid version:** X.X.X
"ag-grid": "~17.1.1",
"ag-grid-angular": "~17.1.0",

* **Browser:**
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript: 2.5.3

**Comment by varunrramani** [comment]
Any update on this?

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
