### ISSUE TITLE
Typings for drag events are missing documented properties

### ISSUE THREAD

**Issue by flakey-bit** [ag-grid/ag-grid#2382]
**I'm submitting a**
```
[ x] bug report
```

**Current behavior**
Typings exposed by `gridOptions.d.ts` for drag events (e.g. `onRowDragEnd`) are missing documented properties (e.g. `api: GridAPI`) according to https://www.ag-grid.com/javascript-grid-events/#properties-and-hierarchy. 

**Expected behavior**
TypeScript typings for drag events should include documented properties

**What is the motivation / use case for changing the behavior?**
Access to documented properties (e.g. `api`)

* **ag-Grid version:** 
v17.1.1

* **Language:**
TypeScript

**Comment by flakey-bit** [comment]
Possibly `RowDragEvent` should be used?

**Comment by makinggoodsoftware** [comment]
One common issue that we receive is around typescript typings and how they can be improved, note that we are aware of this, and we periodically improve them as these are reported.

To track all these issues we use a parked feature request since we consider it to be a never-ending one.

AG-2102	Typescript - Improve typescript typings
This is particularly true for events. The events are bound as properties in ag-grid dynamically to the gridOptions, and that is why we don't have typings for them just yet.

Note that we are planning to automate these, but we have no ETA for this yet.
