### ISSUE TITLE
enableRowGroup does not work when the lockPostion=true

### ISSUE THREAD

**Issue by liux** [ag-grid/ag-grid#2384]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I set the 'lockPostion' and 'enableRowGroup' properties with true, but the 'enableRowGroup' property does not work.

**Expected behavior**
I expect the first column always stay at first and can not be changed by UI, But can be grouped by UI.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/jW1NrtHobZtlPlCbH4Cp?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X
ag-grid-enterprise.js  17.1.1
we have a License.

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
