### ISSUE TITLE
updateRowData not working after calling setRowData

### ISSUE THREAD

**Issue by deepaprp** [ag-grid/ag-grid#2390]
i am using gridOptions.api.setRowData option to reset the complete grid. ie reset the data from UI and load fresh data.

using Javascript AJAX call to fetch data and using setRowData to load the new data in the screen.

After loading this, unable to use the gridOptions.api.updateRowData function. i am getting the exception while try to update the data.

**ag-Grid: could not find data item as object was not found**

**Comment by Motassem-MK** [comment]
Same here, although my objects has a unique "id" property, I found this mentioned in the documentation but was not well explained.

**Comment by oprodev** [comment]
Also had this issue, the key here is that updateRowData expects the row objects by reference (must pass === check). So you cannot just create an object with identical properties to the row and use that in the updateRowData transaction. You have to manually loop thru EVERY row using forEachNode, check for the properties you need, then pass that node.data in the transaction. Then internally ag grid loops thru every row AGAIN to do basically the exact same thing. The stupidity of this astounds me.

**Comment by cintolas** [comment]
How does this work with UpdateRowData using the add transaction?  I am getting the same error.  Of course it can't find the data item.  It doesnt exist yet.   The only part of the transaction that works properly is the update, and i am not sure why

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by hari2m** [comment]
> Also had this issue, the key here is that updateRowData expects the row objects by reference (must pass === check). So you cannot just create an object with identical properties to the row and use that in the updateRowData transaction. You have to manually loop thru EVERY row using forEachNode, check for the properties you need, then pass that node.data in the transaction. Then internally ag grid loops thru every row AGAIN to do basically the exact same thing. The stupidity of this astounds me.

How to do the object comparison on our own? the updateRows expects an object with update property with array right. Is there an API that we can call to validate on certain fields? I need to update the row but the row has multiple fields changed, but there are some fields that will not change, how to handle updte in that situation.
