### ISSUE TITLE
Hidden column reappears after removed from column group.

### ISSUE THREAD

**Issue by Sparkenstein** [ag-grid/ag-grid#2397]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have few column hidden by setting 'hide' property of coldefs. I created a button, which on clicked, group the grid by given these hidden columns. The manual grouping of column works, but when I remove the column from top toolbar, it reappears in the grid.

**Expected behavior**

The columns which were hidden previously, should remain hidden.

**Minimal reproduction of the problem with instructions**
Visit Plunkr : [hide column issue](https://plnkr.co/edit/C5MwkqiCR7OhyFHfOLku?p=preview) OR reproduce it yourself:
hide any columns in the grid by setting 'hide' : true in column definition. create a button anywhere. 
call a function `onclick="groupBy()"` on button
in JavaScript:
```
function groupBy(){
  gridOptions.columnApi.setRowGroupColumns(['age']); // Change the 'age' to your column name.
}
```
After the grid shows grouped rows, remove the grouped column from top toolbar. the hidden column will get visible again.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10
VSCode

* **ag-Grid version:** 17.1.1 (in plunkr)

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi I might have missed something in your plunker, but I can't see how to reproduce it there, if you think this is still an issue, would you mind creatin another plunker where is more obvious?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by msurendra4** [comment]
i too get same issue mentioned

I save the grouped columns and try to set using 'setRowGroupColumns' (and suppressMakeColumnVisibleAfterUnGroup set to false ) grouped columns are reappearing again
