### ISSUE TITLE
Master - Detail Grid Child row word wrap

### ISSUE THREAD

**Issue by Sivasubramni** [ag-grid/ag-grid#2398]
**I am requesting for a feature to have word wrap in the child rows for Master-Detail grid**  

[ ] feature request

**Current behavior**
Based on the example given, [Example](https://www.ag-grid.com/javascript-grid-master-detail/#example-simple) by ag-Grid, i could create master-detail grid. But the child rows has very large text that can be displayed as a description. Currently its not showing as wrap-text.
Actually all the references i went through are dealing with row height. But it increases the height of the height with offset and all, but not the individual row child.

**Expected behavior**
Child rows in the master details grid should have option to enable word wrap in children. It can be any solution, a new feature, or any tweaks in the code to increase the height of child rows individually.

**What is the motivation / use case for changing the behavior?**
It is a description field in the child rows. That should be shown as paragraphs. 

**Please tell us about your environment:**

* **ag-Grid version:** 17.0.0

* **Browser:**
Chrome
* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

Unfortunately we can't tell what your issue is given your description. 

This ticket is going to nbe flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
