### ISSUE TITLE
Phone Predictive Text messes up filters

### ISSUE THREAD

**Issue by davidhenley** [ag-grid/ag-grid#2399]
When using the floatingFilter, if I want to type in "Sampleproduct", using any cell phone using predictive text (tested with iPhone and Galaxy Android), unless I type super fast, I get SSaSamSampSamplSample....etc. The floatingFilter text input is acting weird. This doesn't happen on any other text input.

Can you guys look into this?

Expected:

Sampleproduct

Actual

SSaSamSampSamplSample...

**Comment by makinggoodsoftware** [comment]
Hi,

Unfortunately we can't tell what your issue is given your description. 

This ticket is going to be flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by davidhenley** [comment]
What do you mean? The phone predictive text on Android and iOS when you
type in the filter for instance Apple, you get AApAppApplApple

This is confirmed on multiple phones.

Also I am an Enterprise customer.

*David Henley*
615-438-3334

**Comment by makinggoodsoftware** [comment]
Hi David,

Since you are a customer, would you mind creating this issue in Zendesk?

We are able to provide much efficient support from there since that is where all the team looks at first to provide support.

Is that OK?

**Comment by makinggoodsoftware** [comment]
Closing this as we assume this is not an issue anymore
