### ISSUE TITLE
Autoheight not working with AGGrid react component 

### ISSUE THREAD

**Issue by aamitsharma2705** [ag-grid/ag-grid#2405]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 

**Current behavior**
We are using autoHeight= true for auto height for columns, currently its working for static html and plain component. But ts failing in case of React component.

Supporting plunkr :
[Autoheight not working with react component](https://plnkr.co/edit/eAs69BWKLScDjLlnyqqR?p=preview)
 
**Expected behavior**
Should work with react component too.

**Minimal reproduction of the problem with instructions**
Supporting plunkr :
[Autoheight not working with react component](https://plnkr.co/edit/eAs69BWKLScDjLlnyqqR?p=preview)

**What is the motivation / use case for changing the behavior?**
Need to use dynamic rowheight on required columns, Possibly via usage of autoheight =true of columns property

**Please tell us about your environment:**
Windows

* **ag-Grid version:** X.X.X
17.1.1

* **Browser:**
Chrome, IE

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7 | ES5

**Comment by bguidinger** [comment]
We are also experiencing this with 18.1.0.  Any update?

**Comment by makinggoodsoftware** [comment]
Hi,

This seems to be working in our end:

https://www.ag-grid.com/javascript-grid-row-height/#auto-row-height

If you think this is still an issue, could you provide a reproducible scenario for it?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by bsara** [comment]
@makinggoodsoftware I believe that the reason that you're not seeing the issue in your example is because you are not providing a custom renderer that renders a react component. I've verified that this issue occurs when there is a custom cell renderer in react. After some debugging, it seems that when you guys create the invisible row in order to find the height to set, the react components supplied via cellRendererFramework (I haven't checked just cellRenderer) aren't rendered, causing the invisible cell created to be empty, this makes it so that the height can't be set because your invisible cell has no height.
