### ISSUE TITLE
Column group destroyed when none of it's column are visible.

### ISSUE THREAD

**Issue by Owlman145** [ag-grid/ag-grid#2406]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If you hide all columns of a group, then columnApi.getColumnGroup(groupId) returns null and/or crashes the page.
Thus cannot get children to set them back to visible.
**Expected behavior**

Column group still exist when but with hide state true.

**Minimal reproduction of the problem with instructions**

1. Create a grid with multiple column groups.
2. Hide all the child of a group using various methods (e.g. columnApi.setColumnVisible())
3. Call columnApi.getColumnGroup(groupId) in an attempt to get children of groups to set them back to visible.

**What is the motivation / use case for changing the behavior?**

I have many columns which display data based on selection in another grid. Sometimes these will contain data from certain groups but not others. I don't want to show all the groups if possible, so would like to be able to hide a whole group. As there are no setColumnGroupVisible(), the next way I tried to do this was to get the column group and set all the children to visible. I do have a workaroud for this, (using columnApi.setColumnVisible() using the hardcoded ids of the group columns), but would using a more flexible solution.

**Please tell us about your environment:**

* **ag-Grid version:** 16.0.0, 17.1.1

* **Browser:** Chrome/66.0.3359.181

* **Language:** javascript ES6 / Ember 2.12.2

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
