### ISSUE TITLE
Active sorting and filtering not kept with updateRowData(transaction)

### ISSUE THREAD

**Issue by twmarr** [ag-grid/ag-grid#2423]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using updateRowData(transaction), active sorting and filtering is not kept.

**Expected behavior**

I expect the active sorting and filtering to be kept.
**Minimal reproduction of the problem with instructions**

Set a filter on a column.
Sort a column.
Create a transaction that removes rows and adds rows.
Call updateRowData(transaction)
The filter is not kept and the sorting is not kept.

**What is the motivation / use case for changing the behavior?**

When updating a table, I need the sorting and filtering to be maintained.

**Please tell us about your environment:**

Windows 10
Bower
Ionic V1
AngularJS

* **ag-Grid version:** X.X.X
16.0.0

* **Browser:**

Chrome Version 67.0.3396.62 (Official Build) (64-bit)
Firefox Version 60.0.1 (64 bit)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Javascript

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
