### ISSUE TITLE
Wrong cell positions (top/lef) using angular cached routes

### ISSUE THREAD

**Issue by ddegan** [ag-grid/ag-grid#2425]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm using AgGrid in a Angular  (v 5.2.3) application that has two tabs. In both tabs users can create instances of ag grid tables. To improve loading performance switching from one table to the other the angular routes are cached. 
The problem is that when you return to one tab that has a table, and this table has been scrolled either vertically or horizontally before leaving the tab, the table doesn't render correctly. In particular seems that the table tries to scroll to the top but the absolute positions of the cells are the old ones, so there are blank holes in the table, until you scroll.

The only event that the grid emits once you return to a cached tab is the "gridSizeChanged" but calling to method such as "refreshCells" or "redrayRows" seems not to have effect. 
Actually I bypassed the problem triggering a scroll of +1 px and then another of -1 px. I was woundering if there's some method of the api that can trigger the recomputation of the cell positions.

**Expected behavior**

Returning to the cached tab I expect that the table renders correctly remembering the last state.

**Minimal reproduction of the problem with instructions**

To reproduce the bug, just create two Angular routes and use a CustomReuseStrategy (that implements RouteReuseStrategy) to chache the routes. Then create a grid on one page, scroll vertically or horizontally, navigate away and return to the original page. You will notice the issue.

**What is the motivation / use case for changing the behavior?**

Fixing the issue would let to use cached routes to improve the application performance.

**Please tell us about your environment:**

* **ag-Grid version:** 17.1.1

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

Mozilla/5.0 (Windows NT 10.0; Win64; x64; ServiceUI 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.6.2

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
