### ISSUE TITLE
Checkbox is not re-rendering properly 

### ISSUE THREAD

**Issue by rajsek** [ag-grid/ag-grid#2431]
Hi Ag-grid Team,
We are using ag-grid react in our application, Thought that updating the rowData & passing as props to react-ag-grid will rerender the respective cells.
But we are facing the below two worried issues
1) cellClass is not dynamically updating the correct CSS class based on row Data values But when scroll down and come back, I could able to see the correct CSS class.
2) Similarly, I Default select checkbox's isRowSelectable is also not updating based on row data change.

and the interesting part is the cell values are getting the update but the style & checkbox is not updating properly 
Could you please help me on this ?
If possible, help to debug the checkbox and CSS change deduction..

Note: Removing *deltaRowDataMode* or set it as false is updating the UI checkbox and CSS state properly properly..

**Comment by ashrafhadden** [comment]
Yeah, I'm having the same issue with my React cellRenderer components not re-rendering on receiving new props. I believe it's because somehow ag-grid is mounting its React cell renderer components to the React root div thus breaking the core Virtual DOM tree hierarchy and props inheritance. I posted about it here #2587

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
