### ISSUE TITLE
Issue with the colDef.d.ts type definitions

### ISSUE THREAD

**Issue by sukhminderx** [ag-grid/ag-grid#2432]
Hi,

I am using typescript and ag grid. There is an issue with the types defined in **colDef.d.ts.**
I need to define an object of type **ColDef** and in **valueFormatter**, I want to pass a string such as
_"valueFormatter" : "someString"_
This would give an error.
The reason being as defined in the **colDef.d.ts,** 
_valueFormatter?: (params: ValueFormatterParams) => string | string_

The bitwise operator is taking precedence and the type of valueFormatter becomes 
_( (params: ValueFormatterParams) => string) | 'undefined_

I believe it should be:
**valueFormatter?: ((params: ValueFormatterParams) => string) | string**

By this, valueFormatter could be assigned a string value.
Please let me know your views.

**Comment by makinggoodsoftware** [comment]
One common issue that we receive is around typescript typings and how they can be improved, note that we are aware of this, and we periodically improve them as these are reported.

To track all these issues we use a parked feature request since we consider it to be a never-ending one.

AG-2102	Typescript - Improve typescript typings
This is particularly true for events. The events are bound as properties in ag-grid dynamically to the gridOptions, and that is why we don't have typings for them just yet.

Note that we are planning to automate these, but we have no ETA for this yet.

**Comment by SUSHEELsikarwar** [comment]
Its almost 2 years and still this has not been fixed. Ag-grid is a powerful library and such silly errors are not acceptable. Please improve the typings. I am using ag-grid version 22.1.2 and still facing the same issue.
