### ISSUE TITLE
setFunctionsReadOnly only works with pivot mode

### ISSUE THREAD

**Issue by choisel** [ag-grid/ag-grid#2434]
Hello everyone,

The setFunctionsReadOnly method only works when the grid is in pivot mode. You can check this with the read only example at the bottom of this page https://www.ag-grid.com/javascript-grid-tool-panel/

Just uncheck pivot mode in the tool panel and you will notice the misbehavior.

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
