### ISSUE TITLE
LocaleText - resetColumns - Broken

### ISSUE THREAD

**Issue by J-Strong** [ag-grid/ag-grid#2437]
From your documentation (https://www.ag-grid.com/javascript-grid-internationalisation/) you allow the grids text to be defined. All the options are working great, except "resetColumns".

![image](https://user-images.githubusercontent.com/21131708/41441530-e56a9a6a-6fe7-11e8-9f7b-078bb5d32ce8.png)

From the image you can see all the options are added except 'resetColumns'

I am using ag-grid version 17.0.0 in an Angular v5.2.3 app.

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
