### ISSUE TITLE
slow rendering 500ms timeout layoutInterval - VueJS

### ISSUE THREAD

**Issue by ng5** [ag-grid/ag-grid#2439]
I've noticed an issue whenever grid was put inside tabs or other Vue container, it only renders 1st column of the grid, remaining columns are displayed after about half a second delay. 

For example below code in single file component that renders 2 custom component. appgrid and plot2d. 
appgrid is a custom component i've written that uses aggrid without vuejs wrapper. Pure javascript version.  Same issue happens even if I use vue aggrid component.

After debugging I found that timer event is fired with default layoutInterval of 500ms, nothing happens until this is timed out. I changed this to 1ms by specifying gridOptions and this fixed the delay. 

However I would like to know why this timer is fired, is it being fired because Virtual DOM technology of VueJS, ReactJS & other similar frameworks.

==========  Only 1st column is displayed then remaining columns display after 500ms delay ====
```
<template>
  <div>
    <tabs>
      <tab name="Tab1">
        <appgrid></appgrid>
      </tab>
      <tab name="Tab2">
        <plot2d></plot2d>
      </tab>
    </tabs>
  </div>
</template>

```

However If I remove tabs etc and directly render grid it works smoothly.

```
<template>
  <div>
        <appgrid></appgrid>
        <plot2d></plot2d>
  </div>
</template>

```

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
