### ISSUE TITLE
Detail grid does not Auto Height under 300 px

### ISSUE THREAD

**Issue by giraud-d** [ag-grid/ag-grid#2454]
**Documentation followed**

https://www.ag-grid.com/javascript-grid-width-and-height/#auto-height
https://www.ag-grid.com/javascript-grid-master-detail/

**Current behavior**

I adapted an exemple of documentation on Plunker : https://plnkr.co/edit/E12fiIi6wJQlcbPt2eYG

As you can see Detail does not *(completly)* auto height under 300 px.

![auto-height-300px](https://user-images.githubusercontent.com/15327857/41721593-9f590bae-7566-11e8-8fa9-a2ba60303b47.PNG)

**Expected behavior**

Auto height under 300 px

**Comment by svanetten1976** [comment]
Yeah @giraud-d I'm running into this same issue as well. I have a master-detail grid that sometimes only has 4-5 rows and it looks ridiculous when its 300 pixels tall. You ever find a solution to this?

**Comment by robindenton-ag-grid** [comment]
Hi,

Note that ag-grid doesn't provide support through GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

In any case, you should be able to find more information in the following links:

https://www.ag-grid.com/javascript-grid-master-detail/#detail-row-height

This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by malamoney** [comment]
Considering masterDetail is a commercial feature, I'd figure this issue would get more attention.

**Comment by kiril-matev** [comment]
Hi @giraud-d 

Thanks for bringing this up.

This extra whitespace displayed under the collapsed master row is not a bug, but is caused by the min-height placed on the grid. This is done so that grid messages such as 'No rows to display' can be displayed correctly in the body of the grid when there are no rows.

To override this minimum height, remove the min-width styles as follows:
      .ag-center-cols-container, .ag-center-cols-clipper {
        min-height: 0px !important;
      }

Once you apply this style removing the minimum height, note that there's no more extra space under the master row:
https://plnkr.co/edit/Nc7G5AQMiZ5wQIek

Thank you for your time in bringing this up!
