### ISSUE TITLE
Row with group fields = null doesn't render value in auto group column even though the value exists

### ISSUE THREAD

**Issue by jimioh** [ag-grid/ag-grid#2484]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a grid that uses row grouping and has an autoGroupColumnDef defined with field set to 'Name' which isn't a columnDef with rowGroup: true. I  render a row that isn't grouped (ie. in the rowdata object the fields relating to rowGroup: true columnDefs are set to null as in docuemntation). In the auto group column cell for the non-grouped row the value is empty.

**Expected behavior**
 I want to render a row that isn't grouped and for the auto group column cell for the non-grouped row to be populated with the value of the 'Name' property of the row data object.

**Minimal reproduction of the problem with instructions**
I tried using the example plunkr to recreate but I couldn't even get row grouping to work on it.
**What is the motivation / use case for changing the behavior?**
I want to be able to display a non grouped row cell value in the auto group column
**Please tell us about your environment:**
Windows 10, Visual Studio 2014, NPM Package manager

* **ag-Grid version:** 18.0.1

* **Browser:**
Google Chrome lates

* **Language:** Typescript

**Comment by robindenton-ag-grid** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but we will reopen it if we are provided with a reproduction scenario as specified above

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by jfcere** [comment]
> I tried using the example plunkr to recreate but I couldn't even get row grouping to work on it.

I've stumbled into a similar issue where I wasn't able to get row grouping to work following the Ag-Grid "Get Started" tutorial.

I found out I was importing `AllCommunityModules` from `@ag-grid-community/all-modules` instead of `AllModules` from `@ag-grid-enterprise/all-modules`...

```typescript
// modules import for `ag-grid-enterprise` that enables row grouping
import { AllModules } from '@ag-grid-enterprise/all-modules';

@Component({ ... })
export class ExampleComponent {
  readonly modules = AllModules;
}
```

```html
<ag-grid-angular
  ...
  [modules]="modules"
></ag-grid-angular>
```
