### ISSUE TITLE
Pinned Row Cell Renderer is reinstantiated instead of calling `refresh` method

### ISSUE THREAD

**Issue by denniske** [ag-grid/ag-grid#2489]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

When a pinned row with a pinnedRowCellRenderer is refreshed it is recreated instead of calling the refresh method.

**Expected behavior**
The refresh method of the CellRenderer should be called.

Look into the console in this example 
https://plnkr.co/edit/sgEGGTZxRven3mfWaZA3

```
INIT
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
INIT
Refresh normal and pinned rows
REFRESH
INIT
```
There should be two times "REFRESH" instead of one "REFRESH" and one "INIT".

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 18.1.0

* **Browser:** Chrome

* **Language:** TypeScript 2.7.2

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2192 - Pinned Row Cell Renderer is instantiated instead of calling `refresh` method
