### ISSUE TITLE
setDatasource doesn't refetch the data again 

### ISSUE THREAD

**Issue by gwojtaszczyk-neurosys** [ag-grid/ag-grid#2494]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```
**Current behavior**
I use Ag-grid with category tabs and infinite scrolling. When I add something to the API i would like to refetch the lists again as an item may belong to several lists. Invoking setDatasource or purgeInfiniteCache doesn't invoke getRows again

**Expected behavior**
Without a bug the data inside the grid (as I understand) should be fetched again from the API (getRows method)

**What is the motivation / use case for changing the behavior?**
I'd like to have a possibility to load the data again when using infinite scrolling

**Please tell us about your environment:**
Ubuntu 17.10, PhpStorm, yarn, webpack

* **ag-Grid version:** 18.0.1, Ag-grid for React

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36

* **Language:** ES6/7

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
