### ISSUE TITLE
vertical scroll not reacting to touch events

### ISSUE THREAD

**Issue by alexus85** [ag-grid/ag-grid#2500]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
While on mobile ( or even desktop browser with mobile mode active), the grid is only scrolling horizontally, not vertically. Everything is working as expected when I turn off sticky column.

**Expected behavior**
The grid should allow user scroll both vertically and horizontally on mobile.

**Minimal reproduction of the problem with instructions**
https://stackoverflow.com/questions/51332874/ag-grid-vertical-scroll-not-working-on-mobile

**What is the motivation / use case for changing the behavior?**
Users able t o scroll the table vertically on mobile.

**Please tell us about your environment:**
WebStorm, Node 8.9.3, Mac OS Sierra 

* **ag-Grid version:** 16.0.1
I'm using ag-grid version 16.0.1. I've tested one of the most recent versions (18.1.1), and was able to scroll vertically, however (as mentioned in SO), I'm not able to upgrade to a newer version just yet. 
So I'd really appreciate if there was a way to fix this issue without having to upgrade anything.

* **Browser:**
Chrome 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
