### ISSUE TITLE
AgGrid error after compilation/optimization

### ISSUE THREAD

**Issue by thegelko** [ag-grid/ag-grid#2502]
**I'm submitting a ...
[X] bug report 
[ ] feature request
[ ] support request

**Current behavior**
Grid it's not displayed after compilation. Error in console:
 `Cannot read property 'AG_GRID' of undefined`   (Chrome)
`"d.ComponentType is undefined"`  (Firefox)
compile code line-error:
```
 e.prototype.retrieve = function(e) {
                var t = this.translateIfDeprecated(e);
                return this.frameworkComponents[t] ? {
                    type: d.ComponentType.FRAMEWORK,
                    component: this.frameworkComponents[t],
                    source: D.REGISTERED
                } : this.jsComponents[t] ? {
                    type: d.ComponentType.AG_GRID,
                    component: this.jsComponents[t],
                    source: D.REGISTERED
                } : this.agGridDefaults[t] ? this.agGridDefaults[t] ? {
                    type: d.ComponentType.AG_GRID,      <<<<-------------------
                    component: this.agGridDefaults[t],
                    source: D.DEFAULT
                } : null : (Object.keys(this.agGridDefaults).indexOf(t) < 0 && console.warn("ag-grid: Looking for component [" + t + "] but it wasn't found."),
                null)
            }
```

**Expected behavior**
to work  (same pre-compilation behavior)

**Please tell us about your environment:**
win10, vsCode,  Angular6 App
_Dependencies_
...
    "@angular/common": "6.0.0",
    "@angular/compiler": "6.0.0",
    "@angular/core": "6.0.0",
...
    "ag-grid": "^18.1.0",
    "ag-grid-angular": "^18.1.0",
_devDependecies_
"@angular/cli": "^6.0.8",
"@angular-devkit/build-angular": "~0.6.0",
"@angular/compiler-cli": "^6.0.1"
"@types/node": "9.4.0",
"typescript": "^2.7.2"

* **ag-Grid version:** 18.1.0
* **Browser:** all
* **Language:** [TypeScript 2.7.2]

**Comment by thegelko** [comment]
any idea?

**Comment by robindenton-ag-grid** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but we will reopen it if we are provided with a reproduction scenario as specified above

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
