### ISSUE TITLE
When using nested columnGroups (two levels deep or more) top level column moving breaks with certain combinations of marryChildren and hide

### ISSUE THREAD

**Issue by baseten** [ag-grid/ag-grid#2515]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We have a grid with nested column groups going two levels deep. We have set `marryChildren` to `true` for every column group at every level. By default, the lowest group has only a single column visible by default so `hide` is set to true on the other columns. When this is the case we can no longer move the top level columns to reorder them. If more than one column at the lowest level is visible by default the bug does not occur. If `marryChildren` is not set to `true` at the group closest to the bottom of the hierarchy, then the bug will not occur (but when more than one of its children is visible, these children may be moved between parents which cannot occur in our use case)

**Expected behavior**
Top level groups should be movable no matter what combination of `marryChildren` and `hide` is used on their descendants.

**Minimal reproduction of the problem with instructions**
[Minimal reproduction here](https://plnkr.co/edit/KyUhOg9XRsWi3oNaNyCH?p=preview)

**What is the motivation / use case for changing the behavior?**
Make column moving function correctly

**Please tell us about your environment:**
Mac OS v10.12.6

* **ag-Grid version:** X.X.X
v18.1.1

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
