### ISSUE TITLE
Master/Detail Expansion does not work with a filter on a column

### ISSUE THREAD

**Issue by ajpopal** [ag-grid/ag-grid#2533]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am using master detail data grid and have enabled filters on each column in the master view. If no filter is set, it works fine thus I can expand each row to display the details view of each row. As soon as a filter is set on an arbitrary column, the detail view is not expandable anymore. 

See the comments in https://github.com/ag-grid/ag-grid/issues/1324 below.

**Expected behavior**

It is desired that the detail view is expandable altough a filter is active.

**Minimal reproduction of the problem with instructions**

Setup of a master detail grid, such as in https://www.ag-grid.com/javascript-grid-master-detail/. Enable filter on the ag-grid. Set a concrete filter in the master view on a column and check if the details view is expandable.

**What is the motivation / use case for changing the behavior?**

Our use case is that the user searches for one or serveral objects/records in the (master) data grid by applying one or several filters. In the master view only important attributes are shown. In case of relevant objects in the master view the user selects/expands the according rows in order to see further related objects.

**Please tell us about your environment:**

Windows, Idea 2018, npm: 5.6.0
* **ag-Grid version:** X.X.X
"ag-grid": "18.1.2",
ag-grid-angular": "18.1.0",

* **Browser:**

Chrome/68.0.3440.75

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

typescript: 2.7.2

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
