### ISSUE TITLE
tabToNextCell return wrong value in edit mode

### ISSUE THREAD

**Issue by tonyjiang88215** [ag-grid/ag-grid#2550]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I use the tabToNextCell return value to determine if there is any next editable cell. When I use floatingBottom, when the last editable cell in the middle area is in edit mode, press tab, tabToNextCell will return true, and the focus will be positioned in the first row of the floatingBottom area. However, I am in the source code rowRenderer.ts line 1117, which returns true if the next cell is editable. This makes me wonder, in the edit state, if the current cell is already the last editable cell, what will be returned by calling tabToNextCell.

**Expected behavior**

If the current cell is already the last editable cell and is currently in edit mode, then calling TabToNextCell should return false

**Minimal reproduction of the problem with instructions**

There is a row of data in the middle area and the floatingBottom area. Set the floattingBottom line through colDef to be uneditable, start editing the last cell in the middle area, and then press the tab key.

**What is the motivation / use case for changing the behavior?**

The return value of tabToNextCell can be used to determine if there is a next editable cell.

**Please tell us about your environment:**

Mac OS Sierra 10.12.6

* **ag-Grid version:** X.X.X

18.1.2

* **Browser:**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.9.1

**Comment by robindenton-ag-grid** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but we will reopen it if we are provided with a reproduction scenario as specified above

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
