### ISSUE TITLE
Ag-grid filter by rendered data.

### ISSUE THREAD

**Issue by trd-renato** [ag-grid/ag-grid#2568]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Good day, I would like to ask if how can I filter by rendered data. I can't filter the data because it is a unicode. I hope you can help me with this. Thank you :)

**Comment by makinggoodsoftware** [comment]
Hi,

Note that ag-grid doesn't provide support through github.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via github)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

In any case you should be able to find more information in the following links:

https://www.ag-grid.com/javascript-grid-value-handlers/

Note that this issue is labeled with 'managed-by-community' meaning that ag-grid staff is going to ignore, but it'll be open for a few weeks just in case someone else from the community has a suggestion
