### ISSUE TITLE
rowIndex and rowPinned is missing in the getRowHeight

### ISSUE THREAD

**Issue by seeden** [ag-grid/ag-grid#2569]
I am using ag-grid-react

When I use getRowHeight I get just next keys for node

childrenMapped", "selectable", "selected", "mainEventService", "gridOptionsWrapper", "selectionController", "columnController", "valueService", "rowModel", "context", "valueCache", "columnApi", "gridApi", "group", "master", "expanded", "canFlower", "level", "data", "id", "childrenAfterFilter", "allChildrenCount", "firstChild", "lastChild", "childIndex", "oldRowTop", "rowTop

as you can see rowIndex and rowPinned are missing

my versions
    "ag-grid": "^18.1.2",
    "ag-grid-react": "^18.1.0",

FYI: rowIndex will be added in the future but during getRowHeight is not set

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but we will reopen it if we are provided with a reproduction scenario as specified above
