### ISSUE TITLE
Memory Leak with AG-Grid

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#2576]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
I've Parts wich are removed from the DOM but AG-Grid stays in Memory 

**Expected behavior**
AG Does not stay in Memory

**Please tell us about your environment:**
Windows, Custom HTTZP Server

* **ag-Grid version:** 18.1.2

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by jogibear9988** [comment]
<img width="1669" alt="43366174-a0d67a5c-9339-11e8-8df8-e14001662516" src="https://user-images.githubusercontent.com/364896/44116801-c9611056-a011-11e8-8f26-51a7cf292caf.png">

**Comment by makinggoodsoftware** [comment]
Hi,

Unfortunately we can't tell what your issue is given your description. 

This ticket is going to be flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
