### ISSUE TITLE
`columnResize` event, when dragged manually, doesn't include column, when finished == true

### ISSUE THREAD

**Issue by utyf** [ag-grid/ag-grid#2581]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[] feature request 
[] support request 
```

**Current behavior**
First of all, we use React wrapper. So, we set `onColumnResized` event handler:
```js
onColumnResized={ (event) => {
    console.log(
      'onColumnResized: ',
      event.source,
      event.finished,
      event.column && event.column.colId,
      event.column && event.column.actualWidth,
      event,
    );
  }
}
```
And manually resize a column:

![2018-08-15_15-29-04](https://user-images.githubusercontent.com/41217/44150964-d4ece60a-a0a9-11e8-8d50-a90da7bba9bd.png)

**Expected behavior**
Last `columnResize` event should have column property set.

**Please tell us about your environment:**
Operating system: OS X High Sierra

* **ag-Grid version:** 17.0.0 using with React wrapper
* **Browser:** Google Chrome 68
* **Language:** ES6/7

**Comment by RodSmithAG** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but we will reopen it if we are provided with a reproduction scenario as specified above

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
