### ISSUE TITLE
ag-grid single click edit enable causes overwrite other events for the cell in IE 11

### ISSUE THREAD

**Issue by sivaramalingam** [ag-grid/ag-grid#2584]
**when we enabled single click edit in ag-grid causes other events for the cell is not working in IE 11** 

**Current behavior**
I have added drag and drop for ag-grid it causes unable to edit the cell in single click. For this single click we enabled single click edit for that Grid. It creates many problems that was other events of that element like keypress, key down and etc., was not working. 

**Expected behavior**
All the cell events will be working even we enabled single click edit. 

**Please tell us about your environment:**

* **ag-Grid version:** 1.6

* **Browser:** IE 11

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] angular 2

**Comment by RodSmithAG** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but we will reopen it if we are provided with a reproduction scenario as specified above

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
