### ISSUE TITLE
.gitignore installed by bower ignore /dist directory inside ag-grid

### ISSUE THREAD

**Issue by jankoprowski** [ag-grid/ag-grid#2589]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
1. Install ag-grid by bower e.g. bower install ag-grid
2. Try to commit ag-grid dist/ directory into git repository

**Current behavior**
Bower download ag-grid repository .gitignore file which ignores dist/ directory and its content.
This cause I can't commit ag-grid.min.js file into my project.

**Expected behavior**
Bower should skip .gitignore file from ag-grid project.
I should be able to commit ag-grid.min.js file into my git repository.

**Please tell us about your environment:**
Linux
InteliJ IDEA
Bower

* **ag-Grid version:**
18.1.2

* **Browser:**
n/a

* **Language:**
ES5

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
