### ISSUE TITLE
No provision to manually set layout as similar to grid layout on no rows

### ISSUE THREAD

**Issue by prabhat112** [ag-grid/ag-grid#2590]
**I'm submitting a feature request  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
[](url)
![image](https://user-images.githubusercontent.com/19392220/44480990-ae60c600-a612-11e8-995a-cd3e3c22050b.png)

In the above image, the headers are faded and the grid has a faded grey color. 

**Expected behavior**

Provision to make the layout similar to the one below.
![image](https://user-images.githubusercontent.com/19392220/44481122-0a2b4f00-a613-11e8-9219-0df9183e6c29.png)

The above layout is shown when the backend sends an empty array. 
The above layout doesnt show when we do the below following too

`    
     
     this.rowData = [];    //approach 1

      this.overlayLoadingTemplate =   '<span>No Rows To Show</span>';  //approach 2
      this.gridOptions.api.showNoRowsOverlay();

      this.gridOptions.api.setRowData([]);    //approach 3
 }`

**Please tell us about your environment:**
Angular6, NGRX6, RXJS6, aggrid v18, typescript 2.7.2
* **ag-Grid version:** 18.1.2

* **Browser:**
chrome, IE11
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
