### ISSUE TITLE
In getRowStyle and getRowClass, rows that are groups have params.node.isSelected() always returning false

### ISSUE THREAD

**Issue by coreyog** [ag-grid/ag-grid#2591]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
https://plnkr.co/edit/sneTTkoOk666FVGhDBOr?p=preview
```
      getRowClass: (params) => {
        if (!params.node.data && params.node.isSelected()) {
          return 'complete-orgunit-row';
        }
        return '';
      }
```

**Current behavior**
`params.node.isSelected()` always returns false inside gridOptions.getRowClass or gridOptions.getRowStyle

**Expected behavior**
`params.node.isSelected()` should return true if the row is selected and should be usable to style a row in gridOptions.getRowStyle and gridOptions.getRowClass

**Please tell us about your environment:**
Linux Mint 19 x64, VSCode, Chrome

* **ag-Grid version:** 18.1.2

* **Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

* **Language:** Angular 6.1.4 / TypeScript 2.9.2

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

getRowStyle does not get called after row selection has changed, that is the core of the issue here. The reason for this is to not restyle the grid every time a selection changes.

However you have a workaround:

You will need to do it manually, listen to:

https://www.ag-grid.com/javascript-grid-events/
rowSelected	Row is selected or deselected.
selectionChanged	Row selection is changed. Use the grid API to get the new row selected.

And then force the redraw of the row:
https://www.ag-grid.com/javascript-grid-refresh/#redraw-rows

Hope this helps
