### ISSUE TITLE
Tree Data Issue

### ISSUE THREAD

**Issue by jiangyh1024** [ag-grid/ag-grid#2594]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

I am using Tree Data feature and I found that If I add a new row which has the same 'Hierarchy' as the existing one, the new row will not be added, and will throw a warning. ('duplicate group keys for row data, keys should be unique')
FOR EXAMPLE: 
  addNewGroup() {
    var newGroupData = [
      {
        id: getNextId(),
        filePath: ["Music", "wav", "hit_" + new Date().getTime() + ".wav"],
        dateModified: "Aug 23 2017 11:52:00 PM",
        size: 58.9
      }
    ];
    this.gridApi.updateRowData({ add: newGroupData });
  }

above is the example given by the document. If I remove 'new Date().getTime() ', it will throw a warning when calling 'addNewGroup()' twice

**Expected behavior**

Can it allow to add the same Row Data to the grid when using Tree Data feature?

**Please tell us about your environment:**

* **ag-Grid version:** 17.1.1

* **Browser:**

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular4

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but we will reopen it if we are provided with a reproduction scenario as specified above

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
