### ISSUE TITLE
aggrid inputs in table don't show the text when i try to filter in ipad or iphone devices

### ISSUE THREAD

**Issue by fosiwaka2** [ag-grid/ag-grid#2609]
When i try to filter in some column on some mobile devices like ipad or iphone, the inputs in aggrid don't show the text but they can filter anyway. I have noticed in my iphone and ipad with safari and chrome.

If you want to see this issue, you may enter the official website in 'demo' route with an iphone or ipad.

**Comment by thirtydot** [comment]
Include a screenshot! :roll_eyes:

<img src="https://i.stack.imgur.com/lHIRQ.png" width="300" />

https://stackoverflow.com/q/52122490/405015

**Comment by fosiwaka2** [comment]
how do i fix this problem?

**Comment by thirtydot** [comment]
Well, it's probably an ag-grid bug, so wait for them to fix it. Could be a while though!

Alternatively, debug the problem yourself. This probably isn't the only instance of text not being visible in inputs on Apple devices. See if you can find anything relevant.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but we will reopen it if we are provided with a reproduction scenario as specified above

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
