### ISSUE TITLE
Quick filter applying bug

### ISSUE THREAD

**Issue by DenRomanov** [ag-grid/ag-grid#2613]
**I'm submitting a ...**  (check one with "x")

[x] bug report => see 'Providing a Reproducible Scenario'

Hi. 
There is a trouble with filtering with apply button.

Current behavior: The text filter is not applied if user sends the second request quickly after the previous one. 

Expected behavior: The second quick filtering request should also be applied. 

Reproducible Scenario

1) Open an example of Button and Filter Events for React on Column Filter page
2) Click on Country header to open filter and left "Contains" as it is.
3) Input data in field and click Apply Filter button
4) Do the same operation number of times quickly. 
5) While you do this quickly the last request is not applied and we see the previous filtered result.

I use the following environment :
Mac OS 10.13.2 High Sierra
Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
IDE: VSCode
Language: ES6/7
Ag-grid version 17.1.1

Could you please help me with this?  Thank you in advance.

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
