### ISSUE TITLE
color for inactive pagination chevrons is almost the same as active pagination chevrons

### ISSUE THREAD

**Issue by dimitropoulos** [ag-grid/ag-grid#2618]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**

In the Balham theme, we have had users complain that grid pagination chevrons for inactive pagination states (if you're on page 1, the "move a page left" chevrons are inactive because you can't move left, same for the right chevrons on the last page) are _almost_ the same as the active states.  It's really hard to see the difference.

![screenshot_20180906_172802](https://user-images.githubusercontent.com/15232461/45186171-908e8600-b1fa-11e8-9a87-1e82cdbffc93.png)

**Expected behavior**

That's up to you guys, but I suggest you do something to better distinguish inactive buttons in this theme.  Perhaps make the active chevron darker?  maybe a grey-ed out background for the inactive ones?

**Please tell us about your environment:**

ag-grid.com

* **ag-Grid version:** 18

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.

**Comment by dimitropoulos** [comment]
I'm confused: are you saying that you don't perceive this to be a problem?

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid that we recognize there is an improvement to be made there, but since this is configurable and because we want to have a lean backlog of issues, we have decided to close this issue.

Hope you understand our decision

**Comment by dimitropoulos** [comment]
would it change your mind if I put in the pull request?  seems like a silly thing to leave broken (I say broken because from the code it's clear that you intend there to be a visual difference between the two, but in implementation there is almost no difference (on many monitors and contrast levels and lighting conditions I would argue is no difference) between the two elements.

**Comment by makinggoodsoftware** [comment]
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback
