### ISSUE TITLE
selecting cells does not work in encapsulation: ViewEncapsulation.ShadowDom help

### ISSUE THREAD

**Issue by gbelmm** [ag-grid/ag-grid#2626]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
with encapsulation: ViewEncapsulation.None
![sep -11-2018 00-24-11](https://user-images.githubusercontent.com/731936/45336272-3b83a480-b559-11e8-9585-99f2fea057c8.gif)

with encapsulation: ViewEncapsulation.ShadowDom
 
![sep -11-2018 00-23-08](https://user-images.githubusercontent.com/731936/45336320-5eae5400-b559-11e8-9e1c-b8d691c9a473.gif)

* **ag-grid-angular version:** 19.0.0
"ag-grid-angular": "^19.0.0",
    "ag-grid-community": "^19.0.0",

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but we will reopen it if we are provided with a reproduction scenario as specified above

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
