### ISSUE TITLE
agGrid - Getting empty header when grid has child coulmns

### ISSUE THREAD

**Issue by shravanfx** [ag-grid/ag-grid#2628]
I am trying to add sub columns to one of the column in AgGrid and sub columns are adding properly.But I am seeing empty header for all the normal columns which are do not have the sub columns.

Please have a look on below plnkr code link and screen shot.

![image](https://user-images.githubusercontent.com/43250391/45508736-34f06980-b7b3-11e8-8cdb-68a62088bde3.png)
https://plnkr.co/edit/5OE5YyxdPUnsicTwtFNn?p=preview

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
