### ISSUE TITLE
Material themed pagination panel has broken css when AG-Grid is in a Gridster item

### ISSUE THREAD

**Issue by michaelblxck** [ag-grid/ag-grid#2632]
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'

Reproducible scenario:
Angular 6 app using GridsterJS with an AG-Grid with Material theming and pagination enabled inside of a Gridster item.

Current behavior:
Pagination panel's css is wacky. Buttons are out of place. The panel does not look as it does when AG-Grid is outside of a Gridster item. 

Expected behavior:
Panel should look as it does outside of a Gridster item. When I use the theme Fresh the panel looks correct.

Environment:
Angular 6 with bootstrap. Using Gridster and have a Gridster item with AG-Grid inside.

AG-Grid Version: 
19.0.0

Browser:
Firefox 60.0.2

Language:
Typescript

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but we will reopen it if we are provided with a reproduction scenario as specified above

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
