### ISSUE TITLE
Sticky column is rendered not as expected

### ISSUE THREAD

**Issue by vugar005** [ag-grid/ag-grid#2633]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[*] support request => see 'Requesting Community Support'
```

**Current behavior**
The sticky column is shown on right edge of table instead of nearest column.
This makes table ugly. Please see demo

**Expected behavior**
The sticky column should be rendered to nearest column.   

**Ag Grid version **
  "ag-grid": "^18.1.2",
    "ag-grid-angular": "^18.1.0",

Plunker: https://plnkr.co/edit/6L8bTAwkEV6R6Be4M1Qm?p=preview

Thanks in advance.

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
