### ISSUE TITLE
[AngularJS] Tempalted cells don't update when setting new row data

### ISSUE THREAD

**Issue by heneryville** [ag-grid/ag-grid#2639]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
When using the row API to update data, cells that use an angular template while `angularCompileRows` is on do not update if the data completely replaces the old object. e.g. [in this plunker](https://plnkr.co/edit/PSyxP15CTn48KHXXyvGB?p=preview), there are two buttons. The first doubles each row value by using `rowNode.setData({...newObject})`, the other will mutate rowNode.data, then call `rowNode.setData(rowNode.data)`. The second always works, but clicking the first button even once will cause a complete failure of all buttons afterwards.  This is because the data object is attached to the $scope, but is not re-attached if a new data object is provided. Thus mutations work, but replacing the object won't replace the object on the scope as well, meaning it's now detached from updates.

**Current behavior**
Calling `rowNode.setData({...newObject})` will cause this and all future cells to stop updating.

**Expected behavior**
Calling `rowNode.setData({...newObject})` will cause the cell to update and allow for future updates.

**Please tell us about your environment:**
Windows, Angular 1.5.x, 

* **ag-Grid version:** v
agGrid v19.0.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

* **Language:**  ES6

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-2106 - Angularjs - templated cells don't update when setting new row data

Note that this is parked as of this time, just because of its complexity, which means that even though we are aware of this issue, we don't have any easy solution as of this time

For the time being, all we can suggest is to follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
