### ISSUE TITLE
setDataValue can't affect the cell value when a cell is in edit mode

### ISSUE THREAD

**Issue by husm** [ag-grid/ag-grid#2647]
I have a scenario below.
There are two columns which are col-A and col-B, and these two columns can be edited.
When I change the value in col-A, col-B should be changed accordingly. I can't use `cellValueChanged` event because I need to change the col-B as soon as I type the key in Col-A, so I use a custom editor component to listen to the `input` event and use `setDataValue` to change the value of Col-B. It works well if only col-A is in edit mode. But when I set the `gridOptions.editType = fullRow`, then the col-B is also in edit mode and the `setDataValue`  does not work anymore.  Here is the code https://stackblitz.com/edit/angular-a5jggc

Any help will be of great appreciate.

**Comment by makinggoodsoftware** [comment]
Hi,

Unfortunately we can't tell what your issue is given your description. 

This ticket is going to nbe flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
