### ISSUE TITLE
ag-grid-community 19.0.0 getDisplayedRowCount wrong value

### ISSUE THREAD

**Issue by antonpo** [ag-grid/ag-grid#2654]
getDisplayedRowCount() gets total number instead of displayed.

    <ag-grid-angular
        #agGrid
        id="myGrid"
        [rowData]="rowData"
        class="ag-theme-balham"
        [columnDefs]="columnDefs"
        [gridOptions]="gridOptions"
        [autoGroupColumnDef]="autoGroupColumnDef"
        [enableSorting]="true"
        [enableFilter]="true"
        [floatingFilter]="true"
        [suppressRowClickSelection]="true"
        [groupSelectsChildren]="true"
        [debug]="true"
        [rowSelection]="rowSelection"
        [enableColResize]="true"
        [rowGroupPanelShow]="rowGroupPanelShow"
        [pivotPanelShow]="pivotPanelShow"
        [enableRangeSelection]="true"
        [pagination]="true"
        [defaultColDef]="defaultColDef"
        (paginationChanged)="onPaginationChanged($event)"
        (gridReady)="onGridReady($event)">
    </ag-grid-angular>

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but we will reopen it if we are provided with a reproduction scenario as specified above

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by dreamershl** [comment]
The API should standardise the output. 
There are 3 functions, getDisplayedRowCount(), getFirstDisplayedRow(),getLastDisplayedRow().  The last 2 uses the "rowRenderer" to return the actual rendered rows. But the first one getDisplayedRowCount() uses the "rowModel" to return the total count of the provided row datas. In fact, in code, most time, we want to know the total rendered (displayed) row count for the optimisation.  Suggest to change the getDisplayedRowCount().

![image](https://user-images.githubusercontent.com/1271739/48748387-bc75bf80-ecb1-11e8-9ee7-b727421836b5.png)

**Comment by kiransiluveru777** [comment]
Any update on this issue
