### ISSUE TITLE
fix type for ColDef.floatingFilterComponentFramework

### ISSUE THREAD

**Issue by derBiggi** [ag-grid/ag-grid#2655]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

The floatingFilterComponentFramework type is currently set to ```{new (): any}```
There was already a similar issue for other ComponentFramework-Fields, see #2073

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-2102 - Typescript - Improve typescript typings

Note that this is parked as of this time, just because of its complexity, which means that even though we are aware of this issue, we don't have any easy solution as of this time

For the time being, all we can suggest is to follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
