### ISSUE TITLE
When using Apply button, filter can be applied even when Apply button has not been clicked.

### ISSUE THREAD

**Issue by cmsheffield** [ag-grid/ag-grid#2657]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Steps to reproduce:**

1. Use the example here https://www.ag-grid.com/javascript-grid-filtering/#apply-function, using an Apply button for a filter.
2. In the Athlete column, enter a value to filter by, but *do not* apply the filter.
3. Enter a filter value on the Age column (e.g. 23) and apply it.
4. Notice the first filter is also applied, even though Apply was never clicked for that filter.

**Current behavior**
The first filter is applied, even though the Apply button was never clicked for that filter.

**Expected behavior**
The filter should not be applied until the user decides to apply it by clicking the Apply button.

**Please tell us about your environment:**
MacOS, Atom

* **ag-Grid version:** 17.1.1

* **Browser:**
All recent versions of all browsers, (Mac and Windows)

* **Language:** ES6

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:


Filters | AG-1336 | Change the way the model is stored in ag-grid so that when applyButton:true it doesn't return intermediate state
-- | -- | --


You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
