### ISSUE TITLE
Auto Height Dom Layout Rendering Vertical Scroll Bar with Tiny Travel

### ISSUE THREAD

**Issue by andystroz** [ag-grid/ag-grid#2666]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Setting `this.gridOptions.domLayout = 'autoHeight';` properly sizes my css component to the size of the grid with all rows displayed. However, it does not remove the vertical scroll bar completely and gives it a very small travel. The [grid auto height example](https://www.ag-grid.com/javascript-grid-width-and-height/) on your website has the same problem as well.

**Expected behavior**

I would like to option to completely remove the vertical scroll bar or a way to edit it in its current state to disable using that scrollbar / hiding it.

**Please tell us about your environment:**
I am using ag-grid community 19.0.0 

* **ag-Grid version:** 19.0.0

and ag-grid angular 19.0.0 in Angular 6.

* **Browser:**

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

* **Language:** [ Angular 6 | ES7 ]

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by andystroz** [comment]
The issue can be seen [here](https://plnkr.co/edit/?p=preview). As seen in the sample on your website the vertical scroll bar takes up almost all of the space leaving a small travel. Is it supposed to be this way or is there a way to remove it?

**Comment by subeesh** [comment]
this temporarily solved the issue for me
`.ag-body-viewport.ag-layout-auto-height {
  overflow: hidden !important;
}`

**Comment by subeesh** [comment]
I added this to my CSS. `!important` overrides the ag-grid style

**Comment by Sarah4VT** [comment]
I'm having the same issue. If I apply the temporary fix mentioned above, then I never get a scrollbar when the available height is less than the full height of the grid.

**Comment by teuf22** [comment]
+1

**Comment by crespo5** [comment]
I'm having the same issue.

The solution of @subeesh solved the problem temporally, yes, but @Sarah4VT is right, never get a scrollbar when the available height is less than the full height of the grid.

@makinggoodsoftware , can you reopen the issue and fix this? It gives a dirty look for the grid. @andystroz provide you a reproducible scenario and you have not paid attention, 
normal ... I understand ... we do not use a paid version, it seems that the community always stay out when we have a problem. You are on the right path.

**Comment by i-amn** [comment]
@makinggoodsoftware please reopen this issue as it is easily reproducible when we are giving domLayout='autoheight' to grid.
