### ISSUE TITLE
Keyboard accessibility for a button in a cell (focus using TAB or ARROWS and click using ENTER or SPACE)

### ISSUE THREAD

**Issue by vitaliusvs** [ag-grid/ag-grid#2667]
How to implement this? 
ag-grid using react.

Similar question: https://github.com/ag-grid/ag-grid/issues/813

**Comment by makinggoodsoftware** [comment]
Hi,

Unfortunately we can't tell what your issue is given your description. 

This ticket is going to nbe flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by vitaliusvs** [comment]
I found no working sample with a button in a grid which would be usable using keyboard.

**Comment by vitaliusvs** [comment]
Is this how you handle most of the issues?

**Comment by makinggoodsoftware** [comment]
Hi,

Sorry for the frustration! We were for a long while not processing issues in github as we only had the resources to do support for our customers

From two weeks ago we have processed over 1year plus of tickets and we are adapting how we do this as we go.

We have added stale bot to help us process issues that are really support questions unattended, and based on this feedback we have extended the stale period to 25 days to flag as stale, then 5 more to close.

Note that the moment you answer after is flagged as stale, the tage is also automatically removed

**Comment by makinggoodsoftware** [comment]
Also, just to offer some guidance in this issue, I think you want to have a look at in your init method to get a hold of the grid API, then you are going to have to capture these key presses yourself and call the relevant API methods to keep the navigation flow

Hope this helps

https://www.ag-grid.com/javascript-grid-api/
