### ISSUE TITLE
Drag and drop ghost label does not have the correct css style

### ISSUE THREAD

**Issue by manifold001** [ag-grid/ag-grid#2672]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I used a custom theme for my ag-grid table.  My table has rows draggable. When a row is dragged, the ghost label and text is show under the grid component as the label's z-index is not set.  My custom theme override the `_ag-theme-common.scss`, so there're css styles like `.custom-theme-name.ag-dnd-ghost` defined in my custom theme, but when I inspect ag-grid table, the overridden `ag-dnd-ghost` is not picked up.

**Expected behavior**

When a row is dragged, the ghost label and text should be above the grid with correct css styles. The overridden `.custome-theme-name.ag-dnd-ghost` style should be applied. 

I found the bug reason is that the `getTheme()` method on `environment`, cannot return my custom ag-grid theme name. 
```typescript
    private createGhost(): void {
        this.eGhost = _.loadTemplate(DragAndDropService.GHOST_TEMPLATE);
        _.addCssClass(this.eGhost, this.environment.getTheme());
        this.eGhostIcon = <HTMLElement> this.eGhost.querySelector('.ag-dnd-ghost-icon');

        this.setGhostIcon(null);
       ...
   }
```

`getTheme()` method uses a RegExp to detect predefined themes but not custom theme
```typescript 
let themeNames = ['fresh', 'dark', 'blue', 'bootstrap', 'material', 'balham-dark', 'balham'];
const themes = themeNames.concat(themeNames.map(name => `theme-${name}`));
const themeClass = new RegExp(`ag-(${themes.join('|')})`);
```

**Please tell us about your environment:**

**ag-Grid version:** 
18.1.2

**Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

**Language:** 
 TypeScript: 2.7.2

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
