### ISSUE TITLE
AgGrid with ( floatingFilter: true: ) has problem when user tries to type point or decimal number

### ISSUE THREAD

**Issue by cristofer951** [ag-grid/ag-grid#2676]
I am using aggrid with filter as number,  but when user type a point or decimal number in the input to filter, that point are getting disappeared automatically.

could you please explain me, what is this event?

Thanks for your help.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```\
Current behavior
The header name does not gets translated

Expected behavior
I expect the header name to be the translated value

Environment:
Javascript

ag-Grid version: 19.0.0

Browser:
Chrome 69.0.3497.100

Language: Typescript

**Comment by makinggoodsoftware** [comment]
Hi,

I have just tried this in our demo, and it seems to be working fine..

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by cristofer951** [comment]
Hi 

The problem is with the FloatingFilter, in that input delete the point
![image](https://user-images.githubusercontent.com/10167981/46500198-e2213500-c7e7-11e8-8c7c-30140528dc36.png)


The other input file is working fine.
![image](https://user-images.githubusercontent.com/10167981/46500266-10067980-c7e8-11e8-97d5-6c27d6aa798d.png)


Thanks for your help

Regards,
