### ISSUE TITLE
`gridApi.getModel()` return type is incorrect when using client-side row model

### ISSUE THREAD

**Issue by prichey** [ag-grid/ag-grid#2677]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[] feature request
[] support request
```

**Current behavior**
`gridApi.getModel()` returns type `IRowModel`, even if row model is Client-side Row Model. TS hints that `Property 'rowsToDisplay' does not exist on type 'IRowModel'` even though it does exist for `ClientSideRowModel`.

**Expected behavior**
`IRowModel` should reflect all row models.

* **ag-Grid version:** 18.1.1

* **Browser:** "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

* **Language:** TypeScript 2.8.3

Thanks!

**Comment by makinggoodsoftware** [comment]
One common issue that we receive is around typescript typings and how they can be improved, note that we are aware of this, and we periodically improve them as these are reported.

To track all these issues we use a parked feature request since we consider it to be a never-ending one.

AG-2102	Typescript - Improve typescript typings
This is particularly true for events. The events are bound as properties in ag-grid dynamically to the gridOptions, and that is why we don't have typings for them just yet.

Note that we are planning to automate these, but we have no ETA for this yet.

**Comment by tim-phillips** [comment]
AG-2102 was completed, but this issue was not included. 

https://www.ag-grid.com/ag-grid-changelog/

**Comment by javierfuentesm** [comment]
@makinggoodsoftware  im still seeing the same issue with ts , even though it is working 
<img width="561" alt="image" src="https://github.com/ag-grid/ag-grid/assets/19244527/8d104750-5d5f-442e-bf95-599d2cdb7457">
