### ISSUE TITLE
CSS height expanding

### ISSUE THREAD

**Issue by zbaylin** [ag-grid/ag-grid#2687]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
When I write a basic table in react-ag-grid and include any CSS theme, the table keeps growing vertically. If I don't include a CSS theme, this issue doesn't occur.

This can be seen here: ![Image of issue](https://thumbs.gfycat.com/PoliticalMasculineAnemone-size_restricted.gif)

I'm using bucklescript bindings for ag-grid, but I can be 100% that this is not the issue.

Here is my example code:

```reason
open AgGrid;
[%raw {|require('ag-grid-community/dist/styles/ag-grid.css')|}];
[%raw {|require('ag-grid-community/dist/styles/ag-theme-bootstrap.css')|}];
let component = ReasonReact.statelessComponent("Basic");

let make(children) {
  ...component,
  render: (self) => {
    <div
      className="ag-fresh"
      style=ReactDOMRe.Style.make(~height="100px", ())
      >  
      <AgGrid
        suppressColumnMoveAnimation=true
        columnDefs=([|
          {"headerName": "First Name", "field": "firstname"},
          {"headerName": "Last Name", "field": "lastname"},
        |])
        rowData=([|
          {"firstname": "Zach", "lastname": "Baylin"}
        |])
        >
      </AgGrid>
    </div>;
  }
}
```

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
