### ISSUE TITLE
AgGrid props typings messing up autocomplete in webstorm

### ISSUE THREAD

**Issue by emattias** [ag-grid/ag-grid#2688]
https://github.com/ag-grid/ag-grid/blob/52a2318b81b77fd920bccbd3b3ef57448ee56f2e/packages/ag-grid-react/lib/agGridReact.d.ts#L9

The row above makes Webstorm IDE not autocomplete props. Is that row needed? If it needs to be able to take in arbitrary props maybe make it be a generic and the user can send in the custom types them selves. (That is if it is even needed. I am not using any custom props atleast, and I am not sure ag-grid even support that! 😅)

**Comment by makinggoodsoftware** [comment]
One common issue that we receive is around typescript typings and how they can be improved, note that we are aware of this, and we periodically improve them as these are reported.

To track all these issues we use a parked feature request since we consider it to be a never-ending one.

AG-2102	Typescript - Improve typescript typings
This is particularly true for events. The events are bound as properties in ag-grid dynamically to the gridOptions, and that is why we don't have typings for them just yet.

Note that we are planning to automate these, but we have no ETA for this yet.
