### ISSUE TITLE
rowDoubleClicked event does not work on iPad

### ISSUE THREAD

**Issue by holzapfelnet** [ag-grid/ag-grid#2697]
**I'm submitting a ...**
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
I created an Angular 6 application with the current version of ag-grid. I added an event handler for the 
rowDoubleClicked event. If I use a desktop browser (e.g. Chrome) to access the application, the rowDoubleClicked will be invoked when I double click on a row.

If I use a iPad, the rowDoubleClicked event does not work. I added 

`<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">`

at the top of the html file to prevent the double click to zoom behavior. However, the rowDoubleClicked event will not be invoked. 

* **ag-Grid version:** 19.0.0

* **Browser:** Safari mobile on iPad (iOS 11.2.5)

* **Language:** TypeScript 2.7.2

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
