### ISSUE TITLE
[React] Custom Header component function params are not properly updated

### ISSUE THREAD

**Issue by pgn-vole** [ag-grid/ag-grid#2699]
When providing a custom param which is a function to a React custom header component which is a function it is not always updated . The function checking if the the underlying component should be updated doesn't seem to be correct as it checks the function name is identical instead of the function reference, therefore the updated param is not passed down.
https://github.com/ag-grid/ag-grid/blob/52a2318b81b77fd920bccbd3b3ef57448ee56f2e/packages/ag-grid-react/src/agGridReact.ts#L179-L180

A typical use case in the react world is doing something like 

```javascript
 {
        ...
        headerComponentFramework: GridCustomHeader,
        headerComponentParams: {
          onCustomHeaderEvent: this.handleCustomHeaderEvent.bind(this, column) // The function name will always be the same although the function is actually not. 
        }
}
```

With that example property to `onCustomHeaderEvent` will never be updated in the GridCustomHeader component instance.

versions :
```
 "ag-grid": "18.1.2",
 "ag-grid-enterprise": "18.1.2",
```

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
