### ISSUE TITLE
Header Components: unable to reorder columns (IHeaderComp.getGui() called twice)

### ISSUE THREAD

**Issue by jvmccarthy** [ag-grid/ag-grid#2702]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
Plunkr: https://plnkr.co/edit/WmGidGy48VbXuBKh?p=preview

This is a simplified fork of the custom header example at https://www.ag-grid.com/javascript-grid-header-rendering/

**Current behavior**
Unable to reorder columns.

I tried creating the `HTMLElement` inside of `getGui()` instead of in `init()`, and column moving was disabled. Because `getGui()` was called twice, click handlers were bound to the wrong element instance, preventing expected functionality like column reordering.

From the plunkr, open the debug console to observe that `init()` is called once per column while `getGui()` is called twice,

```text
init() called athlete
getGui() called athlete
getGui() called athlete
init() called age
getGui() called age
getGui() called age
...
```

**Expected behavior**
The Header Component interface, `IHeaderComp`, is documented to have `getGui()` called once. From https://www.ag-grid.com/javascript-grid-header-rendering/,

```javascript
    // gets called once, you should return the HTML element
    getGui(): HTMLElement;
```

`getGui()` should only be called once, otherwise the documentation should be updated to explain that the element should be created in `init()` because `getGui()` could be called multiple times.

Also, the documentation does a good job of explaining responsibilities for column header components. I recommend clarifying that the grid is also responsible for column reordering. When I was facing this issue, it wasn't obvious to me if I had to provide that functionality for custom headers.

* **ag-Grid version:** 19.0.0

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

* **Language:** ES5

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2163 - Website - fix docs so that is obvious that getGui is not called once, is called many times
