### ISSUE TITLE
rowDoubleClicked event does not work on iPad

### ISSUE THREAD

**Issue by holzapfelnet** [ag-grid/ag-grid#2707]
**I'm submitting a ...**
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
I created an Angular 6 application with the current version of ag-grid. I added an event handler for the 
rowDoubleClicked event. If I use a desktop browser (e.g. Chrome) to access the application, the rowDoubleClicked will be invoked when I double click on a row.

If I use an iPad, the rowDoubleClicked event does not work. I added 

`<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">`

at the top of the html file to prevent the double click to zoom behavior. However, the rowDoubleClicked event will not be invoked. 

An example can be found here:

https://plnkr.co/edit/4kb7oxFu2hWXJG7weC6G?p=preview

**Current behavior**
The rowDoubleClicked event will not be invoked using an iPad.

**Expected behavior**
The rowDoubleClicked event will be invoked using an iPad.

* **ag-Grid version:** 19.0.0

* **Browser:** Safari mobile on iPad (iOS 11.2.5)

* **Language:** TypeScript 2.7.2

**Comment by makinggoodsoftware** [comment]
Hi

Thanks for the reproducible scenario

I am afraid that this is not an ag-grid issue

https://css-tricks.com/annoying-mobile-double-tap-link-issue/

I am going to flag this as managed by the community and ag-grid-engaged, just because I don't think we can/should do anything from our end.

You can try to see if any of the workaround for ios and double click can suit you in your end.

**Comment by holzapfelnet** [comment]
Hi, thanks for the information. 

Maybe you can add this information to your website (https://www.ag-grid.com/javascript-grid-touch), because when I read the provided information about touch support, it sounds to me as if the grid would work properly on touch devices like the iPad.

**Comment by jason2211** [comment]
I realize this is a little old and a closed issue now, but if someone has the same issue, I was able to get around it by creating a directive that simulated a double click when two single clicks occurred near the same time.  It is important to make sure this only runs on Safari on mobile.  The code below uses the ngx-device-detector.

`import { Directive, OnDestroy } from '@angular/core';
import { AgGridNg2 } from 'ag-grid-angular';
import { Subscription } from 'rxjs';
import { DeviceDetectorService, BROWSERS } from 'ngx-device-detector';

@Directive({
  selector: 'ag-grid-angular'
})

/**
 * Safari Mobile will not emit the double click event if there are certain CSS styles in use, this
 * directive will attempt to emulate the double click event by subscribing to the click event and
 * keeping track of the time between the clicks. 
 *  
 * https://github.com/ag-grid/ag-grid/issues/2707
 */
export class AgGridMobileDoubleClickDirective implements OnDestroy {
  private readonly doubleClickTime: number = 300; // time in ms

  private onRowClickSubscription: Subscription;
  private lastClickTime: number;
  private lastRowIndex: number;

  constructor(agGrid: AgGridNg2, deviceService: DeviceDetectorService) {
    // only add subsciption if we are on mobile safari, otherwise it will fire the double click twice
    if (deviceService.isDesktop() || deviceService.browser != BROWSERS.SAFARI) return;

    this.onRowClickSubscription = agGrid.rowClicked.subscribe(
      event => {
        const currentTime = (new Date()).getTime();

        if (this.lastClickTime && (currentTime - this.lastClickTime) <= this.doubleClickTime && event.rowIndex === this.lastRowIndex) {
          agGrid.rowDoubleClicked.emit(event);
          this.lastClickTime = null;
        } else {
          this.lastClickTime = currentTime;
          this.lastRowIndex = event.rowIndex;
        }
      }
    );
  }

  ngOnDestroy() {
    if (this.onRowClickSubscription)
      this.onRowClickSubscription.unsubscribe();
  }
}`

**Comment by javuls** [comment]
Hey

I tried your fix @jason2211 but still could not get it to work.

Could you maybe tell me what specifically you did to make ag grid detect it?

Thanks!

**Comment by jason2211** [comment]
@javuls Hi.  Since the directive has the selector of ag-grid-angular it should automatically apply to all of your grids as long as you have the directive declared in your module.

The directive looks to see if the browser is Safari on Mobile, if it is, it subscribes to the grid's row click event then keeps track of the time between single clicks.  If it detects two of them in without 300ms it will emit the grid's double click event.

In your code, all you need to do is make sure you have a method attached to the double click event.

<ag-grid-angular  [gridOptions]="gridOptions" [columnDefs]="columnDefs"
  [rowData]="items"(gridReady)="onGridReady($event)" **(rowDoubleClicked)="onRowDoubleClick($event.data)"**>
</ag-grid-angular>

I recently upgraded my project to use v21.1 and this directive still worked on an iPad.

Hope this helps.  It can be a pain to debug on iOS if you don't have a mac available.

Jason

**Comment by javuls** [comment]
D'oh! That's what I was missing. Thank you for bearing with me. 

I created the function for it but I don't believe the directive is ever subscribing to agGrids rowClick event in the directive. 

Reason why I think is because I commented out the browser check if statement in the 'AgGridMobileDoubleClickDirective ' and I tried testing to see if I can get a console log from the directive.
 
I got no response from the desktop browser nor the ios simulator.

**Comment by jason2211** [comment]
@javuls 
Here it is implemented in a plunker:  https://next.plnkr.co/edit/uXWKTHvu1eWWkSPx

I did have to update AgGridNg2 to AgGridAngular in the directive's constructor since the grid team change the name in the later version.

You can comment out the browers detection and should see a console log for when it emulates the double click.  You'll also get two double click events in the EventLog display (one for the ag-grid and another for the emulated).  If you run on a iPad device, then you only should see one double click event in the EventLog display.  

Tested in Safari on iPad running iOS 12.3.1.

Good luck!

**Comment by javuls** [comment]
for some reason the line 
'import { AgGridAngular } from 'ag-grid-angular';'

says that the import doesn't exist, what version are you using ?

**Comment by jason2211** [comment]
I'm using v21.  If you are using an older version you can replace AgGridAngular with AgGridNg2

**Comment by jamesatfish** [comment]
This action (the tap of the cell to display the post) is triggered by our grid library ag-grid-angular.  I have updated the library version to the latest build (v24), will re-test once pushed to the staging server.
