### ISSUE TITLE
Firefox - ag-grid Balham theme zoom removes some row borders at 110% and 120%

### ISSUE THREAD

**Issue by tekdahl** [ag-grid/ag-grid#2714]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://www.ag-grid.com/example.php#/
- open the demo page in Firefox
- ensure the balham theme is selected
- zoom to 110% or 120% 
- notice that some rows have now lost their top/bottom borders

**Current behavior**
  - at zoom levels 110% or 120% firefox removes some row borders seemingly at random

**Expected behavior**
  - borders shouldn't randomly disappear
rationale:
  - setting zoom to 133% brings the borders back and this behavior doesn't exist in other browsers

**Please tell us about your environment:**
linux mint 19

* **ag-Grid version:** X.X.X
19.0.0 Balham theme

* **Browser:**

"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.

**Comment by tekdahl** [comment]
I submitted it so you're aware of the bug. Closing bugs you don't intend to fix is an odd workflow unless you're claiming that grid borders disappearing at random is the intended behavior on specific levels of zoom in Firefox.
