### ISSUE TITLE
ag-grid : autoscroll to selected row is not working in enterprise

### ISSUE THREAD

**Issue by i-amn** [ag-grid/ag-grid#2720]
https://i.stack.imgur.com/EnLCq.png - image
 
As you can see in the image.

When the grid loads , the 2nd and 3rd grid selection not displayed on the screen.

But when i scroll down to the grid i can see it is selected. this problem occurs in enterprise because (the row is not on the screen in the viewport and at that time as enterprise shows 100 rows at a time). anyone handle this situation

for each node i am selecting the row like this but it is not auto visible on the screen

```
setTimeout(() => {
        if (node.selectedChildNode) {
          params.api.forEachNode((item: any) => {
            if (item.data === node.selectedChildNode) {
              item.setSelected(true, true);
            }
          });
        }
      }, 0);
```

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
