### ISSUE TITLE
Infinite loop after invoking RowNode.setRowHeight with string argument

### ISSUE THREAD

**Issue by MaximGrise** [ag-grid/ag-grid#2721]
[X] bug report

**Providing a Reproducible Scenario**
Quite simple, use a GridOptions argument like the example below, and click a row.

```javascript
onRowClicked: function(params) {
    params.node.setRowHeight(200 + params.node.rowHeight + 'px')
}
```

**Current behavior**

Infinite loop in ClientSideRowModel.prototype.getRowIndexAtPixel

**Expected behavior**

1) No infinite loop please ;) 
2) Clearly defined argument types in the Docs.

**Please tell us about your environment:**

ag-grid-enterprise v19.0.0

* **Browser:**

Reproduced on chome/firefox/edge.

* **Language:**

Only typeless languages I guess, since setRowHeight takes an Numeric only.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by MaximGrise** [comment]
Why is this closed? Isn't the description clear enough? Take any of your own plunkr example (do you need a link to your own site?) and add the snippet I provided. What exactly is missing from this ticket other than your plunkr? 

You have a browser-freezing infinite loop on a simple api call and I told you clearly how to reproduce it, you really need me to do your job by setting up a plunkr?
