### ISSUE TITLE
Safari Mac OS Problem with the UI

### ISSUE THREAD

**Issue by chuanhhoang** [ag-grid/ag-grid#2728]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I am evaluating ag-grid but there is a problem with Ag-grid on Safari on Mac OS X Mojave. The filter is incorrectly displayed. When typing in the text, it is dragged below so I couldn't see the text.
The link is a screenshot of the problem.
[Problem](http://recordit.co/I1d16BOo0l)

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by chuanhhoang** [comment]
Yes, please take a look at the screen recording above. Please open this link:
https://www.ag-grid.com/example.php#/
 on Safari, just type anything into the filter of the name column, you'll see text will see the text be hidden.

**Comment by chuanhhoang** [comment]
Please open this link https://www.ag-grid.com/example.php#/ on Safari (MacOS) and type anything into the filter of the name column. The text is dragged down so you cannot see it there.
http://recordit.co/I1d16BOo0l
