### ISSUE TITLE
AutoSizeColumn making a flickering effect when grid renders

### ISSUE THREAD

**Issue by deepender87** [ag-grid/ag-grid#2773]
Hi
I am doing the autoSizeColumn for a particular column on grid ready event, I can notice a glitch or flickering effect when grid gets renders. This flicker is happening as grid is trying to resize the column while rendering. How i can fix this, please let me know if there is any work-around of it.

Code snippet:

  ```
  onGridReady(event: GridReadyEvent) {
    this.gridApi = event.api;
    this.gridParams = event.columnApi;
    this.autoSizeAxisColumn();
  }

private autoSizeAxisColumn() {
    if (this.gridParams) {
      this.gridParams.autoSizeColumn('nameCol');
    }
  }
```

**Comment by makinggoodsoftware** [comment]
Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by hosseind2** [comment]
actually I have this issue too
when we call the this.gridApi.sizeColumnsToFit function, the columns get wider then back to prev size for few ms
