### ISSUE TITLE
Updating Viewport datasource doesn't refresh AgGrid content

### ISSUE THREAD

**Issue by ATrogolo** [ag-grid/ag-grid#2783]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

**Here the Plunkr with a live example: [Example Code](https://next.plnkr.co/edit/V5Kqv2R03ozf7R92)**
_This Plunkr code has been created with [create-react-app](https://github.com/facebook/create-react-app)._ 
To run the code install:
```javascript
create-react-app testProject
```
Copy & paste Plunkr files 
Run `yarn install`, then: `yarn start`

**Current behavior**
I'm using AgGrid Enterprise edition with `Viewport` DataSource. I've found a bug while setting a new datasource to an instance of AgGrid. 
If the datasource provides data with the same size (setting it in `setRowCount()`) the grid doesn't refresh data: it doesn't call `setViewportRange()` method.  
What happens is that old rows are deleted, but the grid remains empty. 

**Expected behavior**
I'd like to see new data fetched from the new setted datasource. 

**Please tell us about your environment:**
**OS:** Windows 10
**IDE:** VSCode v.1.29.0 
**Web Framework:** React 
**Package manager:** Npm 
**Bundler:** Webpack v.4.19

* **ag-Grid version:** 19.0.0

* **Browser:**
**Chrome:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
**Firefox:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
**MS Edge:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

* **Language:** [TypeScript 3.14]

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by ATrogolo** [comment]
Hi @makinggoodsoftware, 
I've opened another issue here: https://github.com/ag-grid/ag-grid/issues/2792
