### ISSUE TITLE
Do you support vertical tables?

### ISSUE THREAD

**Issue by tolerance-go** [ag-grid/ag-grid#2787]
I checked the document to find the relevant API, I don't know if there is any function to change the direction of the table

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Note that this is parked as of this time, just because of its complexity, which means that even though we are aware of this issue, we don't have any easy solution as of this time

This is the reference and summary of the relevant issue:



AG-2091	Columns - allow the grid to be configured vertical rows/headers on left

**Comment by ADITYA-PRATAP** [comment]
Hi 
is this issue is resolved AG-2091

**Comment by AG-Zoheil** [comment]
Hi @ADITYA-PRATAP,

Can you clarify your requirement a bit further - what are you after?

Thanks!
