### ISSUE TITLE
Please add support for groupIncludeHeader and groupIncludeTotalHeader

### ISSUE THREAD

**Issue by rfrancisco** [ag-grid/ag-grid#2791]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
It's great that you have 'groupIncludeFooter' and 'groupIncludeTotalFooter', but when we have long results it's not very user-friendly to have the users scroll to the end to see the grand-totals. It would be extremely useful if you could also add support for 'groupIncludeHeader' and 'groupIncludeTotalHeader'. 

As a workaround is there anything i can do to move results to the header?

Edit: groupIncludeHeader is not entirely necessary since we can emulate that using the group row itself, but groupIncludeTotalHeader is important because it allows to have grand-totals event when there is nothing being grouped.

**Comment by jamartinezac** [comment]
I am looking for this feature/workaround as well

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by kiril-matev** [comment]
Hello,

Thank you for bringing this up with us. 

We have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-2953 Allow easily adding a sub/grand total row at the top/bottom pinned/unpinned, even when not using grouping**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!
