### ISSUE TITLE
agSelectCellEditor overwrite cell when dropdown did not contains displayed value

### ISSUE THREAD

**Issue by tranboa** [ag-grid/ag-grid#2796]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When you are using the agSelectCellEditor for FullRowEditing all the displayed value in that row will be changend automaticly when different dropdown lists did not contain that cell value.

**Expected behavior**
I would expect that the value wont change and could add to the dropdown list or all values from that column could displayed at that list.

**Please tell us about your environment:**
Windows 10 Enterprise, Vsiual Studio Code, Angular 6, NPM

* **ag-Grid version:** X.X.X
"ag-grid": "^18.1.2", "ag-grid-angular":"^18.1.0", "ag-grid-enterprise": "^18.1.1",

* **Browser:**
Chrome: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "~2.9.2"

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by tranboa** [comment]
Hi,

the ag grid homepage also shows this issue on the example page. Heres a quick step to reproduce this issue:

1. Open this link https://www.ag-grid.com/javascript-grid-cell-editing/#example-full-row-editing
2. On the Full Row Editing example double click the first row-"Make"
3. The name will automaticly change to AAA instead of keeping the name

@makinggoodsoftware so its more a bug right?

**Comment by raviprajna** [comment]
I am also facing the same issue .

**Comment by gportela85** [comment]
this was fixed in v20

**Comment by vuciv** [comment]
I am still having this issue in v23... Was this fixed?

**Comment by OriolRF** [comment]
I have the same issue. Version 23. Any solutions?
