### ISSUE TITLE
RendererCellRenderer invoke "setValue " cannot pass refresh judge!!

### ISSUE THREAD

**Issue by tolerance-go** [ag-grid/ag-grid#2842]
I'm submitting a ... (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
[] documentation fix request
```

```js

class RendererCellRenderer extends React.PureComponent<IInputCellRendererParams> {

  ....

  computedValue = changeFields => {
    const { colDef, node, context, setValue } = this.props;
   ....
   setValue(nextValue);
  };




  // refresh = params => {
  //   console.log(params, this.props.value);

  //   return true;

  //   // if (params.value !== this.props.value) {
  //   //   const diff = params.value - this.props.value;
  //   //   if (diff > 0) {
  //   //     console.log('bigger');
  //   //   } else if (diff < 0) {
  //   //     console.log('small');
  //   //   }
  //   // }

  //   // return params.value !== this.props.value;
  // };

  render() {
    return this.props.value;
  }
}

export default RendererCellRenderer;
```

When setValue is invoked actively, refresh cannot be updated if it is defined, even if it always returns true! Please help me. How can I solve this problem.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Note that this is parked as of this time, just because of its complexity, which means that even though we are aware of this issue, we don't have any easy solution as of this time

This is the reference and summary of the relevant issue:

AG-2369 | Stateless react components don't work with delta row data
-- | --
