### ISSUE TITLE
Problem with IE

### ISSUE THREAD

**Issue by Axay001** [ag-grid/ag-grid#2852]
I have started project in angular 7 with ag-grid. I have followed documentation and it's working properly in chrome but It is not working in IE.

Here is the documentation,
https://www.ag-grid.com/angular-getting-started/

**Current behavior**
![ag-grid-ie](https://user-images.githubusercontent.com/16620933/50470202-9c829b80-09d5-11e9-9aa8-e6c9296fdc86.png)

I am not getting any error in IE and also grid is not working.

**Expected behavior**
![ag-grid-chrome](https://user-images.githubusercontent.com/16620933/50470230-b15f2f00-09d5-11e9-84ca-794c19d64fc7.png)

In chrome it's working properly so I am expecting same behavior in IE.

**Please tell us about your environment:**
I want to use ag-grid in IE11.

* **ag-Grid version:** X.X.X
I am using 19.1.2

* **Browser:**
IE

* **Language:** 
Typescript

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
