### ISSUE TITLE
[v20] Two different horizontal scrolls when I have custom horizontal scroll size

### ISSUE THREAD

**Issue by MaKCbIMKo** [ag-grid/ag-grid#2911]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I have custom scroll styles/sizes and I specify `scrollbarWidth` parameter as well. But in that case second horizontal scroll appears with default styles.
I have specified custom scroll style for `.ag-body-horizontal-scroll-viewport`, but second scroll appears at `.ag-center-cols-viewport`
(in case with v19 -> everything works just fine).

**Expected behavior**
There is no second horizontal scroll at all.

**Please tell us about your environment:**
Windows 10, VS Code, Angular, Angular-cli, Typescript version 3.2.2

* **ag-Grid version:** 20.0.0

* **Browser:** N/A

* **Language:** TypeScript 3.2.2

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by jiangyh1024** [comment]
@makinggoodsoftware I can reproduce this too. please see the plunker. scrolling to the end, there is a horizontal scroll bar even though 'suppressHorizontalScroll: true,' is set. I found that the 

```
.ag-center-cols-viewport {
    width: 100%;
    overflow-x: auto;
}
```
'overflow-x: auto;' caused this problem

https://next.plnkr.co/edit/C5Nl3sNhpaUgaaOE

**Comment by MaKCbIMKo** [comment]
@jiangyh1024 - exactly!

For me I specified the following to solve that:

```
.ag-center-cols-viewport {
    overflow: hidden;
}
```

And yes, in v.19 - I didn't have such problem at all.

**Comment by MaKCbIMKo** [comment]
@makinggoodsoftware - can we re-open this ticket?

**Comment by gerardqueralt** [comment]
Hi,
We also have the same problem.  Meanwhile, we fix it setting 'overflow: hidden'

**Comment by MarijkeM** [comment]
Still having this problem....

**Comment by joshuadmatthews** [comment]
Also still having this problem.

**Comment by viktormmarkov** [comment]
I encountered a similar problem,,
managed to solve it by specifying the scrollbar height to be the same as the scrollbacr width

Apparantly ag-grid uses the variable to caclulate the height of the cols-viewport element and if there is a difference in size, the horizontal bar appears

**Comment by Llorx** [comment]
Reopen. Problem still persits.

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for your comment.

We'd be keen to look into this again, but as you can see this is quite an old issue from **nearly five years ago**. You can see in a related issue (4078) that we have been struggling to reproduce this.

In any case the grid has naturally advanced a lot since then. If you are still having problems, can we please ask you to open a new issue with a reproducible live scenario on our latest/current version - you can use one of the plunker examples from our [documentation](https://ag-grid.com/javascript-data-grid/) as a starting point.

This would help our team support in the most efficient way, and also increase visibility for the wider AG Grid community in case of contributions and comments.

Much appreciated!

Kind regards,
Zoheil

**Comment by haskelcurry** [comment]
Same here, 2023.

**Comment by j71h** [comment]
Issue still persists and manifested itself when upgrading from 29.3.5 to 30.2.1 (i.e. in version 29 there where only single scrollbars and in version 30 double). No code changes where made in between.

![image](https://github.com/ag-grid/ag-grid/assets/19264820/20356830-c0db-4449-a68e-7d5ae7fdbda1)

"Fixed" by adding this to my styling overrides

``` css
.ag-body-viewport {
  overflow-y: hidden;
}
.ag-center-cols-viewport {
  overflow-x: hidden;
}
```

**Comment by HarmoniousHarmony** [comment]
@j71h  I can confirm that this has also occurred in our application too ( after upgrading to version 30), we have enterprise package and this is the second time our app breaks by upgrading to a newer version.

**Comment by AG-Zoheil** [comment]
Hi all,

Thanks for reporting this. In line with my previous comment, are you able to provide a reproducible example (e.g. a plunker or codesandbox) where we can replicate this issue?

Much appreciated!

**Comment by syuziepetrosyan** [comment]
```
    [suppressHorizontalScroll]="true" //horizontal fixing
    [scrollbarWidth]="0" //vertical fixing
```

Those two options somehow helped me

**Comment by VismaTobbe** [comment]
Same in v31.0.0, both vert and horz scrollbars are duplicated. 
Duplicates are commented as `<!--AG-FAKE-VERTICAL-SCROLL-->` and `<!--AG-FAKE-HORIZONTAL-SCROLL-->`

**Comment by j71h** [comment]
Reporting back that the "fix" I came up with has the side effect that mouse scrolling does not work :(

**Comment by HarmoniousHarmony** [comment]
@j71h Can confirm 😅, that's a shame that ag-grid doesn't want to address this issue while they releasing version 31 and asking for a working example over and over as if this is some open source hobby project made by someone in their free time.

**Comment by kiril-matev** [comment]
Hi all,

This issue was originally opened in 2019 when using custom classes for scrollbar styles. Unfortunately, this wasn't reported with a reproduction which includes the custom CSS classes applied. As we had no context, this issue was never investigated. 

I would highly recommend against modifying CSS classes to patch a scrollbar issue because you're potentially causing other issues and generating further confusion for other users who use a different browser, OS, scrollbar visibility configuration, AG Grid scrollbar configuration that your modification may not cover. Also, these patches can cause further issues when you upgrade to a new version of AG Grid which changes the scrollbar implementation or resolves the original issue. 

We appreciate your desire to help and your contributions but this isn't a reliable approach to resolving an issue which isn't even reported with any of the necessary details.

We are keen to investigate this scrollbar issue - please report it with a test case as described below:
1/ A live example which reproduces the issue - a link to any example on our website, or a custom made plunker or a ZIP of your project
2/ The OS you're using
3/ The browsers this issue can be reproduced in (with browser version numbers)
4/ The scrollbar settings you're using (for Mac - System Preferences > General > Show scroll bars)

We're looking forward to your responses so we can proceed.

**Comment by j71h** [comment]
@kiril-matev 

I'm happy to provide you with all the details except bullet number 1, due to that my company does not allow me to share code and I have no time to try to reproduce this issue in throw away code.
Perhaps some of the other people with the issue have the time to spend....

Br, Johan

**Comment by j71h** [comment]
https://github.com/ag-grid/ag-grid/issues/7324

**Comment by kiril-matev** [comment]
Thank you for this response @j71h. I've just responded in the new github issue you opened.

We can see there's an issue based on your input and screenshots provided for users on this thread. This is why we're very interested to gather reproductions of this issue all the scenarios where this issue occurs and are ready to proceed with an investigation. 

I would encourage all other users on this thread to come forward and submit bug reports by providing items 1-4 in my earlier message.

Please do not rely on other users reporting the issue instead of you. As their AG Grid configuration, browser and OS scrollbar visibility settings is **most probably** not the same as yours, resolving another user's issue may not resolve the issue for you. 

We are keen to resolve the issue in all scenarios where it appears and we need all the use cases where this behavior is reproducible. This is why in order to ensure we resolve your particular issue, please come forward and submit bug reports by providing items 1-4 as listed in my earlier message.

We're looking forward to hearing from you and are ready to investigate based on the live reproduction examples you provide.

**Comment by gportela85** [comment]
@VismaTobbe @j71h I'll continue the discussion about the double scrollbars in #7324 as this issue has been closed and the current issue doesn't seem to be the same as the one initially reported, well, it's the same issue but it happens for completely different reasons on v30+.
