### ISSUE TITLE
Horizontal scroll is broken in Internet Explorer 11

### ISSUE THREAD

**Issue by Hliebov** [ag-grid/ag-grid#2970]
**Current behavior**
In IE 11 (11.904.16299.0)
1. Drag a horizontal scroll using mouse pointer to the right. Scroll returns back. 
2. Click or arrow controls of the horizontal scroll. No scrolling.

**Expected behavior**

1. Horizontal scroll doesn't return back if you drag it with mouse pointer.
2. Arrow controls for horizontal scroll allow to scroll.
**Please tell us about your environment:**

* **ag-Grid version:** 20.0.0

* **Browser:**

IE 11 (11.904.16299.0)
* **Windows** 10
* **Language:** [TypeScript 2.9.2]

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by casperbohnenbaum** [comment]
Have you found a solution for this issue?  

We have the same problem:
ag-Grid version: Enterprise 20.0.0
Browser:Internet Explorer 11
Version: 11.706.17134.0IC  / Version: 11.1716.15063.0
Windows 10
only javascript

Horizontal scroll bar only works, if you don't click on the right or left beside the bar.
If you do so, the bar always jumps back to the left side, the content scrolls left, if you drag the bar to the right, but it is not possible to scroll back to the left!.
Scroll arrows (left and right) generally do not work for horizontal scrolling.
