### ISSUE TITLE
AgGridVue_1.kebabProperty is not a function

### ISSUE THREAD

**Issue by ArthNRick** [ag-grid/ag-grid#2974]
this error happens several times during the execution of the system, you know what it can be?

![image](https://user-images.githubusercontent.com/17991046/53357484-c6d8d280-390c-11e9-9f64-e825f9067ad3.png)

**Comment by seanlandsman** [comment]
Do you have a reproducible example of this that we can use to investigate?

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by ArthNRick** [comment]
https://github.com/ArthNRick/ag-grid-test

Hello. I'm using a dotnet application, I created the project using vue with typescript, so I added ag-grid to it. [Here](https://github.com/ArthNRick/ag-grid-test) is an example of the project (dotnet core required). The error does not prevent the running of the system, the data is loaded into the table and the filters work, but the console is flooded with errors during grid events
