### ISSUE TITLE
polymer3 with webpack: agGrid is not defined

### ISSUE THREAD

**Issue by reximus** [ag-grid/ag-grid#2985]
**I'm submitting a ...** (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
On page load exception:
```
agGridPolymer.js:10 Uncaught ReferenceError: agGrid is not defined
    at Function.get properties [as properties] (agGridPolymer.js:10)
    at ownProperties (properties-mixin.js:90)
    at Function.get _properties [as _properties] (properties-mixin.js:165)
    at Function.get observedAttributes [as observedAttributes] (properties-mixin.js:117)
    at Module../node_modules/ag-grid-polymer/src/agGridPolymer.js?babel-target=es6 (agGridPolymer.js:168)
    at __webpack_require__ (bootstrap:19)
    at Module../node_modules/ag-grid-polymer/index.js?babel-target=es6 (index.js:1)
    at __webpack_require__ (bootstrap:19)
```

**Expected behavior**
Page loaded without errors

**Suggestion:**
Would be nice to import agGrid object/namespace in explicit way.
https://github.com/ag-grid/ag-grid/blob/855e7422a3721e72ede9054f0472259dff8675df/packages/ag-grid-polymer/src/agGridPolymer.js#L10

**Please tell us about your environment:**
* **ag-Grid version:** 20.1.0
* **Language:** ES6
* **Polymer 3**
* **Webpack version:** 4.28.4
* **Browser:** Chrome 72.0.3626.119

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by PavanInala** [comment]
> **I'm submitting a ...** (check one with "x")
> 
> ```
> [x] bug report => see 'Providing a Reproducible Scenario'
> [] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
> [] support request => see 'Requesting Community Support'
> ```
> 
> **Current behavior**
> On page load exception:
> 
> ```
> agGridPolymer.js:10 Uncaught ReferenceError: agGrid is not defined
>     at Function.get properties [as properties] (agGridPolymer.js:10)
>     at ownProperties (properties-mixin.js:90)
>     at Function.get _properties [as _properties] (properties-mixin.js:165)
>     at Function.get observedAttributes [as observedAttributes] (properties-mixin.js:117)
>     at Module../node_modules/ag-grid-polymer/src/agGridPolymer.js?babel-target=es6 (agGridPolymer.js:168)
>     at __webpack_require__ (bootstrap:19)
>     at Module../node_modules/ag-grid-polymer/index.js?babel-target=es6 (index.js:1)
>     at __webpack_require__ (bootstrap:19)
> ```
> 
> **Expected behavior**
> Page loaded without errors
> 
> **Suggestion:**
> Would be nice to import agGrid object/namespace in explicit way.
> https://github.com/ag-grid/ag-grid/blob/855e7422a3721e72ede9054f0472259dff8675df/packages/ag-grid-polymer/src/agGridPolymer.js#L10
> 
> **Please tell us about your environment:**
> 
> * **ag-Grid version:** 20.1.0
> * **Language:** ES6
> * **Polymer 3**
> * **Webpack version:** 4.28.4
> * **Browser:** Chrome 72.0.3626.119

Same issue I am facing, is there any solution for this?

**Comment by superted17** [comment]
Did anyone ever get a solution to this? I'm trying to build a version of ag-grid that doesn't include everything (the enterprise bundle is nor 4 megabytes minified) but I'm running into the agGrid is not defined issue. I'd happily contribute some docs detailing how to build agGrid if someone could give me some help
