### ISSUE TITLE
Wrong row height calculation when set rowHeight in grid options and set autoHeight on a column definition

### ISSUE THREAD

**Issue by poloop** [ag-grid/ag-grid#2986]
**I'm submitting a ...**
```
[x] bug report
```

**Reproducible Scenario**
_ set rowHeight in grid options smaller than rowHeight provide by the theme
_ set autoHeight: true to a column definition

**Current behavior**
if content's height is smaller than the rowHeight provide to grid options, the row's height is set with the min row height set in the HARD_CODED_SIZES object defined in environment.ts

**Expected behavior**
if content's height is smaller than the rowHeight provide to grid options, the row's height should be set with it or the one defined in our theme's sass variables.

**Please tell us about your environment:**
win10, vscode, npm, IIS, Vue 2.5.17

* **ag-Grid version:** X.X.X
ag-grid-community: 20.1.0
ag-grid-vue: 20.1.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"

* **Language:** [ES6/7]

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by poloop** [comment]
Hello @makinggoodsoftware ,

Could you please reopen the issue, bellow the plunker:

[https://plnkr.co/edit/vQ83ya5jj0rhd4w9zjkl?p=preview](https://plnkr.co/edit/vQ83ya5jj0rhd4w9zjkl?p=preview)

The autoHeight property set to true avoid have the row height set with the rowHeight property provide in the grid options when the resize of the cell height is not necessary.

This bug appears with the version 20.x (I update the framework from 19.1.4)

It seems the method gridOptionsWrapper.getRowHeightForNode in clientSideRowModel.ts called at line 159 is called without 'allowEstimate' parameter which force to have minRowHeight calculate by getDefaultRowHeight() and that method get the property from the theme with environment.getSassVariable(theme, 'rowHeight') ([L-1553 gridOptionsWrapper.ts](https://github.com/ag-grid/ag-grid/blob/855e7422a3721e72ede9054f0472259dff8675df/packages/ag-grid-community/src/ts/gridOptionsWrapper.ts#L1553)).
And the method getSassVariable from [environment.ts (L-36)](https://github.com/ag-grid/ag-grid/blob/855e7422a3721e72ede9054f0472259dff8675df/packages/ag-grid-community/src/ts/environment.ts#L36) avoid to have our custom row height.

Sorry for my english, I hope to be clear in my explanations.

Thank you for your reply,

Best regards

**Comment by IndProgo** [comment]
Same bug in 20.2.0. In the example, rowHeight set to 600, but with autoHeight it is ignoring minimum height set by rowHeight (as it worked in versions before 20. It is a breaking change.)

https://plnkr.co/edit/OaX7E0y5ey4yW8yfARDg?p=preview

thanks
