### ISSUE TITLE
 AG-1485  & AG-2628 Crash

### ISSUE THREAD

**Issue by 7carlosz** [ag-grid/ag-grid#2996]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
editing cell and pressing the key navigate down the event is not captured by the function suppressKeyboardEvent

 
  

**Current behavior**

Editing over a pop-up window when you press browse down can not continue editing as it jumps to the next record

**Expected behavior**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

20.1.0

* **Browser:**

Chrome Versión 67.0.3396.99

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript - Angular 7

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
