### ISSUE TITLE
reactNext={true} doesn't work with api.autoSizeColumns

### ISSUE THREAD

**Issue by v-i-n-y-a** [ag-grid/ag-grid#3005]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm using agGrid with serverSideModel and make api.autoSizeColumns(columnIds) after
getting new Rows it works fine but with reactNext={true}  (that fixed another error) 
it stops to work for the custom components, before it was working fine.
  
`
const Configuration = {
    // Sorting
    sortable: true,
  
    // Filter config
    filter: true,
    floatingFilter: true,
    rowHeight: 70,
    // Filter bu default
    defaultColDef: {
      width: 150,
      filter: 'agTextColumnFilter',
      // always should be 'keep' for Server Side Model
      // it let's you to see the filter afther the new rows upload
      // otherwise doesn't work
      filterParams: {
        filterOptions:['equals', 'contains', 'startsWith', 'endsWith'],
        newRowsAction: 'keep',
        debounceMs: 1000,
        suppressAndOrCondition: true
      },
      resizable: true,
      sortable: true,   
    },
  
    // Resizing by drag and drop 
    resizable: true,
  
    // ----- Server Side Model  Properties -----
    // getting data useing server side model
    // 'clientSide' by default
    rowModelType: 'serverSide',
  
    // fetch 100 rows per at a time
    cacheBlockSize: 50,
  
    // wait when scrolling will be finished
    blockLoadDebounceMillis: 1000,
  
    // sideBar
    sideBar: false,
  
    //selection
    rowSelection: "multiple",
    suppressRowClickSelection: true, // if true, clicking rows doesn't select (useful for checkbox selection)
     suppressColumnVirtualisation: true
  }`

**Please tell us about your environment:**
React 16.7.0, 
"ag-grid-community": "^20.0.0",
 "ag-grid-enterprise": "^20.0.0",
 "ag-grid-react": "^20.0.0",

Chome, MacOS Sierra, 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web 
Chome Version 72.0.3626.109 (Official Build) (64-bit)

* **Language:** | ES6/7 

**I've found a problem**

I'm resizing the table columns right after 
`
params.successCallback(rows, lastRow)
`

and it works if I'll put setTimeout 500, my suggestion  params.successCallback(rows, lastRow) should return the promise, so you can modify columns right after it.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
