### ISSUE TITLE
Cannot read property 'clientX' of undefined

### ISSUE THREAD

**Issue by bruenor41** [ag-grid/ag-grid#3015]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
Randomly happens this crash :

```
==================== STACK: ====================
TypeError: Cannot read property 'clientX' of undefined
    at PopupService.push.../../node_modules/ag-grid-community/dist/lib/widgets/popupService.js.PopupService.calculatePointerAlign (xxxxx/ui/vendor.js:123538:18)
    at PopupService.push.../../node_modules/ag-grid-community/dist/lib/widgets/popupService.js.PopupService.positionPopupUnderMouseEvent (xxxxx/ui/vendor.js:123520:23)
```

It happens in calculatePointerAlign located in popupService.js. Somehow input event with name 'e' is undefined and reading it's properties does the crash. 

I cannot reproduce it, it happens occasionally if I scroll over page. I have enabled tooltip on columns,  maybe it has something to do :

```
      column.tooltip = (params) => {
        return params.valueFormatted || params.value;
      };
```

**Please tell us about your environment:**
Ubuntu 16.04 LTS

* **ag-Grid version:** 20.1.0

* **Browser:**
Chrome  63.0.3239.132

**Comment by nlaplante** [comment]
I opened an issue in their ZenDesk platform about this.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by bruenor41** [comment]
Well... thank you for you time, I understand, that without use case it is
hard to fix.

**Comment by mdallman2570** [comment]
I can repro:

Steps are as such:

Use ng-show to hide grid on initial load.
Have cursor hovering over the area the grid will eventually display.
When grid eventually shows (ng-show dynamically set to true) ag-grid will begin calculation of pointer location.  
Pointer will be set to 0,0 and an error will occur:
ag-grid-enterprise.min.js:177 Uncaught TypeError: Cannot read property 'clientX' of undefined
    at e.calculatePointerAlign (ag-grid-enterprise.min.js:177)
    at e.positionPopupUnderMouseEvent (ag-grid-enterprise.min.js:177)
    at ag-grid-enterprise.min.js:495
    at e.then (ag-grid-enterprise.min.js:14)
    at e.createTooltipComponent (ag-grid-enterprise.min.js:495)
    at e.showTooltip (ag-grid-enterprise.min.js:495)
