### ISSUE TITLE
Custom filter components are remounting and loosing their state on filtering if any of visible columns has custom cell renderers 

### ISSUE THREAD

**Issue by AdeonMaster** [ag-grid/ag-grid#3017]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
Custom filter components are remounting and loosing their state on filtering if any of visible columns has custom cell renderers. It's happens only if `reactNext` property is passed to grid.

**Plunker example:** https://next.plnkr.co/edit/o3wUMxKOrYfqxHpW?open=Hello.js&deferRun=1&preview

**Please tell us about your environment:**
* **ag-grid-community:** 20.1.0
* **ag-grid-enterprise:** 20.1.0
* **ag-grid-react:** 20.1.1

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

* **Language:** [ES6/7]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-2905  - Custom filter components are remounting and loosing their state with reactNext


Note that this is parked as of this time, just because of its complexity, which means that even though we are aware of this issue, we don't have any easy solution as of this time

For the time being, all we can suggest is to follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
