### ISSUE TITLE
Angular Form validation Not working in Modal Pop Up - After AG Grid Resizing

### ISSUE THREAD

**Issue by siddhesh1983** [ag-grid/ag-grid#3027]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[X] support request => see 'Requesting Community Support'
```
Issue Description 

I am facing a very strange issue with Modal pop up form validation. Details as below.

1) Project has a base page where angular template is defined as below. It also has AG Grid

2) template loaded in the modal pop up is emailFailureActivityClosureTemplate. it is angular component.

3) Modal pop up is opened using

@ViewChild('emailFailureActivityClosureTemplate') elementEmailFailureClosureView: ElementRef;
this.modalRef = this.modalService.show(this.elementEmailFailureClosureView,config );

4) emailFailureActivityClosureTemplate is a simple form group with below HTML in component

-- Template 

<ng-template #emailFailureActivityClosureTemplate>
    <app-email-failure-activity-closure (onclose)="onClose($event)" [emailReport]='emailReportParam'></app-email-failure-activity-closure>
</ng-template>

-- Component HTML 

 <div>

    <form [formGroup]="failureActivityClosureForm" (ngSubmit)="closeFailureActivity()" class="mycustomfrm" novalidate>

        <div class="container" style=" margin-top: 3%">

              <div class="form-row">
                      <div class="form-group col-md-12" 

                      [ngClass]="{'has-error':(failureActivityClosureForm.get('closureComments').touched || 
                      failureActivityClosureForm.get('closureComments').dirty) && 
                      failureActivityClosureForm.get('closureComments').valid}"

                      >
                        <label for="activityClosureComments" class="required-field">Closure Comments</label>

                       <textarea type="text" [ngClass]="{'is-invalid': !failureActivityClosureForm.valid}" 
                          formControlName="closureComments" 
                          class="form-control form-control-md"                            
                          placeholder="Please enter closure comments."  [(ngModel)]="failureComments" >

                        </textarea>

                      <span *ngIf="(failureActivityClosureForm.get('closureComments').touched || 
                      failureActivityClosureForm.get('closureComments').dirty) &&
                      failureActivityClosureForm.get('closureComments').errors">
                      <span *ngIf="failureActivityClosureForm.get('closureComments').errors.required" class="hasError">
                      Required
                      </span>
                      </span>

                      </div>
              </div>

              <div class="form-row">
                      <div class="col-md-12" style="padding-right: 1%; padding-bottom: 2%">
                          <button class="btn btn-sm  pull-right cstm_cncl" type="button" (click)="onCancelClick()" style="margin-right: 11px;min-width: 85px;">
                              Cancel
                          </button>

                          <button class="btn btn-sm   btn-primary pull-right" type="submit" style="margin-right: 11px;min-width: 85px;"
                              [disabled]="!failureActivityClosureForm.valid">
                              Save Comments</button>
                      </div>
              </div>

        </div>       

    </form>

  </div>

5) Form validator is plugged in  angular component as 

this.failureActivityClosureForm = this.fb.group({
     
      'closureComments': ['', [Validators.required, Validators.minLength(3)]],
     
    });  

**Current behavior**

When the base page AG Grid is present without any scroll, the form validation in the pop up works fine. However , when the AG Grid columns in base page are resized, the pop up opens up but, validation in pop up stops working. 

**Expected behavior**

Validation should work in pop up.

**Please tell us about your environment:**

Visual Studio code for angular 4

* **ag-Grid version:** // ag-grid v17.1.1

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 |] ES5

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
