### ISSUE TITLE
Appending your scrollbar calculator to body can fail sometimes

### ISSUE THREAD

**Issue by smithk58** [ag-grid/ag-grid#3032]
I already have a work around for the below issue, but I thought I would report it anyways in case you were interested in noting this as a low priority thing in your tracker.

**I'm submitting a ...**
```
[*] bug report
```

**Current behavior**
If someone unluckily adds certain styles to their body, your auto scrollbar calculation can break. For example, I had display: flex; on mine and that causes your scrollbar calculation to always return 0 in Firefox.
**Expected behavior**
You should maybe append your scrollbar width calculator to something you have more control over (somewhere inside your actual grid might be safer?).

**Please tell us about your environment:**

* **ag-Grid version:** 20.0.0

**Comment by gportela85** [comment]
Can you provide an example? I tried creating a grid within a page with `<body style="display: flex">` and the scrollbar width was calculated correctly

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
