### ISSUE TITLE
Utils.getScrollbarWidth() return 0 in Mac Chrome

### ISSUE THREAD

**Issue by dreamershl** [ag-grid/ag-grid#3034]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Utils.getScrollbarWidth() can't get the actual scrollbar width. It cause the horizontal scrollbar invisible. 
Please refer to https://gist.github.com/sttk/164f82cef5d9c5ab218211fff6d68e5d#mac-os-x for the detail

**Expected behavior**

Suggest to add a default value as 20 if the return value is 0

**Please tell us about your environment:**

* **ag-Grid version:** 20.2.0

* **Browser:** Chrome Version 72.0.3626.121 (Official Build) (64-bit)

* **Language:** all

**Comment by gportela85** [comment]
This is the correct behavior, it will return `0` because MacOS hides the scrollbar by default and a space for scrollbar should not be reserved.
If your system preferences are set to `Show scroll bars:` `always` or `Automatically base on mouse or trackpad` and your device requires scrollbars, then it will show the scrollbar correctly.
