### ISSUE TITLE
Angular (5+) - onRowDoubleClicked simply doesn't work

### ISSUE THREAD

**Issue by kobibentata** [ag-grid/ag-grid#3041]
I'm submitting a 
[X] bug report
[] feature request
[] support request

Angular 7
Ag-grid 20.1.0
Typescript: 3.3.3
Chrome: 73.0.3683.86
(Win 10, 64-bit)

Re-production:
- Add onRowDoubleClicked to the grid options
- Display the grid on page
- Double click a row in the grid

Expected behavior:
The grid will catch the double click event, when triggered by the user interaction, and will run the corresponding code

Current behavior:
Nothing happens when the user double clicks a row

Sample code:
<ag-grid-angular [gridOptions]="gridOptions" ...>

this.gridOptions = {
     ...,
     onRowDoubleClicked: (event) => { console.log("row double click event:", event); }
}

**Comment by seanlandsman** [comment]
Hi

I've tried to reproduce this using both your config as well as binding directly onto the grid component (`(rowDoubleClicked)="onDoubleClick($event)"`) but am unable to.

Do you have a repro of the problem I can use to investigate?

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
