### ISSUE TITLE
Vue dynamic import failure during SSR - SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by abhipanda** [ag-grid/ag-grid#3046]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

Getting 

import { Component, Prop, Vue } from 'vue-property-decorator';
^^^^^^

SyntaxError: Unexpected token import

**Expected behavior**
No error during SSR

* **ag-Grid version:** **20.0.2**

Solution is to change all ES6 module to CommonJS module.

**Comment by rileytaylor** [comment]
This occurs when trying to use AgGrid while testing with Jest as well. For anyone running into problems only with jest, you can do the following in jest config:

```json
transformIgnorePatterns: [
    "node_modules/(?!(ag-grid-vue)/)"
],
```

Our webpack config is transpiling this for us for normal app usage (babel), but it would be nice if ag-grid could handle that for us. 

I also wonder why `vue-property-decorator` has to be peer installed... is there a reason you guy's aren't compiling it into the component? We don't use it anywhere else, but peer dependencies for anything but frameworks can become headaches if multiple libraries want different versions of the same dependency.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by nkostic** [comment]
> This occurs when trying to use AgGrid while testing with Jest as well. For anyone running into problems only with jest, you can do the following in jest config:
> 
> ```json
> transformIgnorePatterns: [
>     "node_modules/(?!(ag-grid-vue)/)"
> ],
> ```
> 
> Our webpack config is transpiling this for us for normal app usage (babel), but it would be nice if ag-grid could handle that for us.
> 
> I also wonder why `vue-property-decorator` has to be peer installed... is there a reason this isn't being compiled into the component library? We don't use it anywhere else, but peer dependencies for anything but frameworks can become headaches if multiple libraries want different versions of the same dependency.
> 
> The solution does not _have_ to be using CommonJS. A proper babel setup will solve most peoples issues here, but perhaps AgGrid should handle this for us.

I have the same issue while testing with jest even when using a shallowMount, tried transformIgnorePatterns as you described above, but I still can't get this error to go away:

```
import { Component, Prop, Vue } from 'vue-property-decorator';
^^^^^^
 SyntaxError: Unexpected token import
```

Any other suggestions how can this be omitted/handled ?

**Comment by asbermudez** [comment]
@nkostic Same issue here, did you find a solution? I am not able to find this specific error anywhere else than here...

**Comment by weskor** [comment]
Got the same issue. @nkostic @asbermudez did you find a solution?

**Comment by asbermudez** [comment]
@weskor No, didn't manage to fix it. Sorry.

**Comment by weskor** [comment]
@asbermudez after spending some time on the `jest.config` the following seemed to work for me.
```
module.exports = {
    preset: '@vue/cli-plugin-unit-jest/presets/typescript-and-babel',
    transformIgnorePatterns: [
        '<rootDir>/node_modules/(?!vee-validate/dist/rules|@ag-grid-community/vue)'
    ],
    testMatch: [
        '**/*.spec.ts'
    ],
    collectCoverage: true,
    collectCoverageFrom: [
        '**/services/**/*.ts',
        '**/store/**/*.ts',
        '**/ui/components/*/**.vue',
        '**/ui/views/*/**.vue',
        '!**/store.ts',
        '!**/*.mock.ts',
        '!**/*.types.ts',
        '!**/index.ts'
    ]
};
```
