### ISSUE TITLE
[react] rowDataChangeDetectionStrategy format

### ISSUE THREAD

**Issue by emmanueltouzery** [ag-grid/ag-grid#3047]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The [documentation says](https://www.ag-grid.com/react-more-details/#react-row-data-control) we can specify the row data control for react like so:

    rowDataChangeDetectionStrategy='IdentityCheck'

If I do that in our typescript code base, I get:

```
 error TS2322: Type '"NoCheck"' is not assignable to type 'ChangeDetectionStrategyType | undefined'.

153                 rowDataChangeDetectionStrategy='NoCheck'
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/ag-grid-react/lib/agGridReact.d.ts:10:5
    10     rowDataChangeDetectionStrategy?: ChangeDetectionStrategyType;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from property 'rowDataChangeDetectionStrategy' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<AgGridReact> & Readonly<AgGridReactProps> & Readonly<{ children?: ReactNode; }>'

```

**Expected behavior**
It's possible that our system is no properly set up, but I wonder whether maybe the documentation is not outdated regarding `rowDataChangeDetectionStrategy`.

* **ag-Grid version:** 20.2.0

* **Language:** TypeScript 3.4.1

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
