### ISSUE TITLE
Cannot read property 'clientX' exception

### ISSUE THREAD

**Issue by mdallman2570** [ag-grid/ag-grid#3054]
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'

**Current behavior**
When grid loads, custom tooltip is set to coordinate 0,0 and never disappears because an exception has been thrown.
**Expected behavior**
Custom tooltip appears under cursor and disappears when moved.

REPRO Steps:

1. Have grid hidden using ng-show in AngularJS
2. Place cursor in location where grid will eventually display
3. set ng-show to 'True' dynamically and have grid appear.
4. ag-grid will then attempt to calculate tooltip location but throw this error: 
ag-grid-enterprise.min.js:177 Uncaught TypeError: Cannot read property 'clientX' of undefined
    at e.calculatePointerAlign (ag-grid-enterprise.min.js:177)
    at e.positionPopupUnderMouseEvent (ag-grid-enterprise.min.js:177)
    at ag-grid-enterprise.min.js:495
    at e.then (ag-grid-enterprise.min.js:14)
    at e.createTooltipComponent (ag-grid-enterprise.min.js:495)
    at e.showTooltip (ag-grid-enterprise.min.js:495)

5. Custom tooltip will appear in upper left most corner and cannot be removed.  Page must be reloaded.

**Please tell us about your environment:**
Windows 10

* **ag-Grid version:** X.X.X
v20.1.0

* **Browser:**
Chrome/73.0.3683.86

**Comment by jpwrunyan** [comment]
FYI, this problem also exists when implemented using React. When testing on Safari, I cannot reproduce the problem (yet). It appears highly sensitive to the mouse pointer location and the timing of mouse move events.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
