### ISSUE TITLE
suppressKeyboardEvent not working. Ag-grid-community version 19.0.0

### ISSUE THREAD

**Issue by sachinwadi** [ag-grid/ag-grid#3069]
Hello,
I am defining colDef something like this:

{
                headerName: "Direct Cap Rate",
                field: "financials.directcaprate",
                editable: true,
                valueParser: "Number(newValue)",
                filter: "agNumberColumnFilter",
                type: "numericColumn",
                valueFormatter: this.amountCellRenderer,
                enableCellChangeFlash: true,
                cellClassRules: { "ag-cell-data-changed": this.highlightLastUpdatedFields },
                suppressKeyboardEvent: this.supressInvalidKeystrokes
            }

and callback function:

private supressInvalidKeystrokes(params) {
        const allowedChars = "-.0123456789";
        if (allowedChars.indexOf(params.event.key) >= 0) {
            return false;
        }
        return true;
    }

This callback gets called when key is pressed but invalid key(e.g. alphabates here) are not getting blocked

**Comment by NeKJ** [comment]
If I guess correctly, and your intention is to block any key except the ones tat are in `allowedChars` array, then I think you have a bug in your code. supressInvalidKeystrokes() should return `true` if `indexOf` returns -1 and `false` otherwise in order to do what I guess you want it to.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
