### ISSUE TITLE
Blocking Arrow Keys in CellRendererFramework text editor

### ISSUE THREAD

**Issue by svanetten1976** [ag-grid/ag-grid#3077]
[X] bug report => see 'Providing a Reproducible Scenario'

As of version 20, it appears that a keydown event listener on a cellRendererFramework React component can no longer stopPropagation() of left/right arrow keyboard events before those events hit the grid itself. These are the two relevant snippets:

In React component:
    findDOMNode(this.textField).addEventListener('keydown', this.onKeyDown)

   onKeyDown = event => {
    const arrowKeys = [37, 39]
    if (arrowKeys.includes(event.keyCode)) {
      event.stopPropagation()
      return false
    }
  }

And in the grid configuration:
  suppressKeyboardEvent = params => {
    const { isEditing } = this.props

    const component =
      params.colDef &&
      params.colDef.cellRendererFramework &&
      params.colDef.cellRendererFramework.WrappedComponent &&
      params.colDef.cellRendererFramework.WrappedComponent.name
        ? params.colDef.cellRendererFramework.WrappedComponent.name
        : ''

    const event = params.event
    const key = event.which
    const arrowKeys = [37, 39]
    if (isEditing && arrowKeys.includes(key) && component) {
      return true
    }

    return false
  }

If I remove suppressKeyboardEvent from the grid configuration, pressing a left or right arrow key inside my text editor jumps to the next cell. If I leave the suppressKeyboardEvent in place, the arrow keys have no impact inside the editor and the onKeyDown method of the editor is not heard until after that suppressKeyboardEvent gets called. Fun stuff

Using ag-grid 20.2.0 and react 16.6.3. Setting up those keydown listeners in custom cellRendererFramework text editors used to work in prior versions of ag-grid. Any ideas? -- Steve

**Comment by ntnskrds** [comment]
@svanetten1976 You are right ! contrary to what is documented here (https://www.ag-grid.com/javascript-grid-cell-editor/#option-1-stop-propagation) a keypress or keydown listener installed on the renderer/editor component will get the event only *after* the grid has responded to it (I suspect because the grid installs its internal listeners in the capture phase). Thus you are only left with suppressKeyboardEvent if you want to block arrow key navigation. However suppressKeyboardEvent is plagued with another issue as of 20.2 (#3078) . It does stop cell navigation but also (quite unfortunately) seems to cancel (preventDefault) the event. As a result you are left with  focus in an editor component (say an input box), caret blinking in it and all but non-functional arrow keys i.e. you can't use them to move the caret around, change the selection etc. etc.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
