### ISSUE TITLE
onCellValueChanged changing cell class/style doesnt work for first time update, but works from the second time.

### ISSUE THREAD

**Issue by asmaqsoodali** [ag-grid/ag-grid#3084]
**I'm submitting a request to check the below issue / bug
onCellValueChanged changing cell class/style doesnt work for first time update, but works from the second time.
```
eg ->
onCellValueChanged={params => { 

                       //changing cell style by using cellStyle property
                        params.column.colDef.cellStyle = {color: 'red', backgroundColor: 'green'};
                        params.api.refreshCells();

                        //changing cell style by using cellClass property
                        if(params.column.colDef.cellClass == "editable_col"){
                            params.column.colDef.cellClass = "edited_col";
                            params.api.refreshCells();
                        }
        
                    }}

```
In both of the above scenarios, cell class and style changes upon updating/changing cell value for second time and doesn't work for first time change/update.

**Using Ag Grid for React in Chrome browser**

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by rananaresh86** [comment]
Did anyone get this working. OnCellvalueChange I want to add/remove class to some other column instead of current being edited.
Is that possible , Please share.

Thanks

**Comment by lsamruth** [comment]
@asmaqsoodali  @rananaresh86 i was able to make it work by using `cellClass` find below code.

`cellClass = (params) => {
        if (params.node.eventService && params.node.eventService.firedEvents) {
            console.log(params.node.eventService.firedEvents);
            if (params.node.eventService.firedEvents.cellChanged) {
                return 'cell-value-changed';
            }
        }
    }`
