### ISSUE TITLE
Cell renderers flicker when reactNext is enabled with infinite scroll row model

### ISSUE THREAD

**Issue by spryor** [ag-grid/ag-grid#3095]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Issue:
When I set `reactNext` to true, cellRenderers appear to flicker during infinite scrolling. The flicker appears to occur when a new row block is requested.

Expected behaviour:
I would expect no flickering.

I need to enable reactNext since I'm performing custom logic using hooks in a custom column header component. If I remove reactNext the flickering goes away but my header components fail since I'm calling useContext inside them. The context isn't actually available so the header crashes and renders nothing.

Versions:
AgGrid 20.2.0 
React: 16.8.6 
Google Chrome

**Comment by spryor** [comment]
Any chance for some assistance here?

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by T-L0yAL** [comment]
@spryor did you find any resolution?  I'm running into the same issue.  Also, without scrolling and just using useContext in a cellRenderer, when the context changes all the cell renderers flicker...

**Comment by galenlong** [comment]
Here's a plunkr that reproduces the issue: https://plnkr.co/edit/DFUgTC2c9pEt3JrSn5qb?p=preview

Whenever the columnDefs change, all cells rendered with a custom React component flicker. If reactNext is set to false, the flickering stops.

**Comment by dcjones1** [comment]
I'm facing the same issue. When using a custom React cell renderer, I get these flickers when columnDefs change. When scrolling, the custom renderers also flicker while rest of the table does not. When I rewrote one of the cell renderers in plain Javascript, the flickering stops, however I have two renderers that are significantly more complex and would be a difficult refactor to plain JS.
