### ISSUE TITLE
cellClass results are appended with deltaRowDataMode: true

### ISSUE THREAD

**Issue by DominicTobias** [ag-grid/ag-grid#3108]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

Yes, on behalf of a large enterprise customer. No Zend Desk access but I will try and get it.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are

Generate a changing class, e,g,:

```js
cellClass: () => `class-${Math.random().toString(36).substring(7)}`
```

**Current behavior**

Observe that on change it keeps appending new classes instead of replacing them (class-randomstring):

![appendclass](https://user-images.githubusercontent.com/760314/56965394-1d54ce00-6b55-11e9-9547-253ef88b24df.gif)

In this case it breaks behaviour since the green Buy class etc is still applied.

**Expected behavior**

Custom cell classes should be REPLACED not APPENDED.

**Behaviour is as expected without using deltaRowDataMode**, but this isn't a good option for us.

**Please tell us about your environment:**
Windows 7

* **ag-Grid version:** X.X.X
19.0.0

* **Browser:**
Chrome 72

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by DominicTobias** [comment]
Here's a demo of issue, click Re-render a few times, notice how the color stops being what it says it should be due to adding both classes and therefore always being green:

https://next.plnkr.co/edit/0JlFOxfRED4pVWDC

**Comment by makinggoodsoftware** [comment]
Hi,

This is how cellClass is meant to work, from our docs:

cellClass: All new classes are applied. Old classes are not removed so be aware that classes will accumulate. If you want to remove old classes, then use cellClassRules.

https://www.ag-grid.com/javascript-grid-cell-styles/#refresh-of-styles

Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Note that this is parked as of this time, just because of its complexity, which means that even though we are aware of this issue, we don't have any easy solution as of this time

This is the reference and summary of the relevant issue:





AG-2430 | Add a new way to style cells, similar to cellClass, but applying the classes absolutely ie cellClassAbsolute
-- | --

**Comment by DominicTobias** [comment]
Thanks @makinggoodsoftware I'll try with cellClassRules. I have to say that if it's by design then I think that's strange, it's not how I would imagine it should work and goes against design practices I can think of! Imagine if React components retained state from previous renders!
