### ISSUE TITLE
Infinite loop with maxBlocksInCache=1 with Infinite Row Model

### ISSUE THREAD

**Issue by MatthieuCoelho** [ag-grid/ag-grid#3129]
Hi,
I'm submitting a bug report, when using Infinite Row Model and maxBlocksInCache=1 will always create an infinite loop when scroll is between two page.

To reproduce :
 ```
 <AgGridReact
               rowModelType={"infinite"}
                maxBlocksInCache={1}
                cacheBlockSize={2}
            />
```
If the grid can show 2 elements we have that :
```
ITEM 1
ITEM 2
```

Then if I scroll, I expect to see :
```
ITEM 2
ITEM 3
```

But It won't work because cache must contains 2 blocks :
```
"BLOCK 1 : ITEM 1, ITEM 2",
"BLOCK 2 : ITEM 2, ITEM 3"
```
 but maxBlocksInCache is only 1 so it will keep looping.

If I put maxBlocksInCache = 2 it will works, but then if I call refreshInfiniteCache() it will do 2 requests to the server and I want to avoid that.

Version : 
```
ag-grid-community: 20.2.0
```

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
