### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getColSpanningList' of null

### ISSUE THREAD

**Issue by ilmsolutions** [ag-grid/ag-grid#3134]
When initiating start editing cell, get the above error. The error occurs only when the grid has horizontal scroll. The function in which the error occurs is getRenderedCellForColumn (https://github.com/ag-grid/ag-grid/blob/714ced17a4e62f52d319792670d4e0240afe1145/packages/ag-grid-community/src/ts/rendering/rowComp.ts#L1408).  
It seems that the cells which are not visible have the cell component reference as null. 

Here is the stack trace:
rowComp.js:1186 Uncaught TypeError: Cannot read property 'getColSpanningList' of null
    at rowComp.js:1186
    at Array.filter (<anonymous>)
    at t.getRenderedCellForColumn (rowComp.js:1186)
    at t.getComponentForCell (rowRenderer.js:886)
    at t.startEditingCell (rowRenderer.js:865)
    at e.startEditingCell (gridApi.js:814)
    at listgrid.tsx:327
    at Array.forEach (<anonymous>)
    at Object.updrow [as handler] (listgrid.tsx:325)
    at HTMLSpanElement.<anonymous> (listgrid.tsx:261)

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by pfosser** [comment]
Hi @makinggoodsoftware , this is a plunker that reproduces the problem.
https://plnkr.co/edit/aEJKx9POpuNOhc8eA9F2?p=info

When tabbing through the cells in editmode, if some columns on the right are virtual, the error gets printed to the console.

Hope this helps.
