### ISSUE TITLE
Unexpected behavior with autoSizeColumn 

### ISSUE THREAD

**Issue by celestale** [ag-grid/ag-grid#3144]
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request
```

**Current behavior**
`gridColumnApi.autoSizeColumn(colId)` having different behavior. 

In a grid that contains short/long data row messages. When data rows with long overflowing messages are visible (in the viewport), `autoSizeColumn(colId)` will fit and show a horizontal scrollbar. Then later, when scrolled to a shorter data row messages that did not overflow the grid, `autoSizeColumn(colId)` went on to hide the horizontal scrollbar, causing the previous long overflowing messages (which are actually not visible in the viewport due to scrolling) to have ellipsis due to overflow-x.

**Expected behavior**
`autoSizeColumn(colId)` should check all data rows, if there are overflowing messages, it should always show the scrollbar. Currently it is only checking on visible rows. The behavior was changed in this version.

* **ag-Grid version:**
`ag-grid-angular: =20.2.0`
`ag-grid-community: =20.2.0`

* **Language:** TypeScript 3.4.3

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
