### ISSUE TITLE
21.0.0 issue with React components

### ISSUE THREAD

**Issue by apuntovanini** [ag-grid/ag-grid#3177]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Code**
```javascript

import styled from 'styled-components';

const Wrapper = styled.div``

class Renderer extends PureComponent<any> {
  render() {
    const { value } = this.props;
    return (
      <Wrapper>
        <Avatar size="small" enableTooltip={false} borderColor="transparent" />
        <span className="ml-1">{value}</span>
      </Wrapper>
    );
  }
}

const columnDefs = [{
  ... // other props,
  cellRendererFramework: Renderer,
}]
```

**Current behavior**
In a grid with custom Header and Cell renderers (React), with new 21.0.0 version, when scrolling right or down, grid returns an error

```javascript
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

**Expected behavior**
With previous version, same code didn't throw this error.

* **ag-Grid version:** 21.0.0

**Comment by seanlandsman** [comment]
Can you provide a reproducible example I can look at? Github repo, plunker etc?

**Comment by apuntovanini** [comment]
https://guidu.netlify.com/examples.html?groupId=data&packageId=data-manager&exampleId=Basic

If you scroll left/down rapidly it throws the error

**Comment by djgable** [comment]
After upgrading, I am experiencing the same thing when I click to "expand" a column group.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by seanlandsman** [comment]
If you provide an example I can run & debug (as specified above) I'll be happy to take a look at this issue.

The example above proves it's a problem, but it's not really something I can use to test any possible fixes for it

**Comment by emjaksa** [comment]
https://plnkr.co/edit/r3wUORCGeF4imnSiaGPc?p=preview

It happens when you use reactNext

**Comment by seanlandsman** [comment]
@emjaksa thanks

Until a fix is ready, you can specify the following to prevent this error:

```componentWrappingElement='div'```

**Comment by seanlandsman** [comment]
This change has been rolled back in 21.0.1 - we'll re-introduce this once a fix has been implemented for this issue

thanks for reporting it

**Comment by apuntovanini** [comment]
Thank you @seanlandsman, and thanks @emjaksa for providing repro example! Suggested patch works for us
