### ISSUE TITLE
Column property "type: 'numeric'" causes column header title to disappear instead of adding ellipse 

### ISSUE THREAD

**Issue by jmitchell0528** [ag-grid/ag-grid#3216]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
- Set a column def header with the property 'type: "numeric"'. When the grid is loaded with a title too large, the header title completely disappears. This does not happen with normal left aligned header titles, the over flow is hidden with an ellipse.

**Current behavior:**
- When the column property 'type' is set to 'numeric' for one of the columns and the header title length is too long, it is not shown in the grid. The header title is gone and only appears if the grid is resized.

![image](https://user-images.githubusercontent.com/24928482/60049284-9a9f4980-9693-11e9-9e16-20eb1d49b4d9.png)

**Expected behavior:**
- When the title of the column header is too long, I expect it to be shown with a hidden overflow and ellipse.

![image](https://user-images.githubusercontent.com/24928482/60049127-41371a80-9693-11e9-9a8d-fa3efcbc8fe7.png)

**Please tell us about your environment:**

- ag-Grid version: 20.2.0

- Browser: Chrome

- Language: Angular 7

**Comment by PeterSteen01** [comment]
I'm seeing the same issue for version 20.2.0 with angular 6. Anybody find a solution for this ?

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by jmitchell0528** [comment]
Hello @davis4acca 

Thanks for the response, I updated ag-grid from version 20.2.0 to 21.0.1 and that seemed to fix my problem. I did a Plunker as instructed and tried to replicate the issues I was having but ended up with the opposite issue of the column header overflowing instead of disappearing. I suppose it could just be an ag-grid 20.2.0 problem with using the 'Numeric' type, but as I said, upgrading the version seemed to fix the issue. 

You can view the Plunker link below to see the column header issue in version 20.2.0. Resize the third column by moving it in the left direction, it should overflow into the second column.

https://plnkr.co/edit/n6GheATJWZMmA7VQ0iKc?p=preview
