### ISSUE TITLE
Grid mutates data which leads to redux error

### ISSUE THREAD

**Issue by deser** [ag-grid/ag-grid#3230]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When I pass data to ag-grid and make any column editable, ag-grid mutates data inside which leads to next redux error: "Invariant Violation: A state mutation was detected between dispatches, in the path `some_path`. This may cause incorrect behavior".

**Expected behavior**
ag-grid cell editor doesn't mutate rowData.

**ag-Grid version:** 
"ag-grid": "18.1.2",
"ag-grid-react": "18.1.0"

**Comment by deser** [comment]
UPD: 
The same issue with:
```
"ag-grid-community": "21.0.1",
"ag-grid-react": "21.0.1",
```

**Comment by scottdfedorov** [comment]
As awful as this is, I don't think they'll consider this a bug. The whole documentation around redux is woefully inadequate because it completely ignores editing data, but alas, its not a bug.

The solution is to set a "valueSetter" function for each column definition. Create a function that calls your dispatch and then assign that to EVERY editable column "editable: true, valueSetter: myFunction".

Yeah....

**Comment by deser** [comment]
Nice;)

**Comment by scottdfedorov** [comment]
Left a better answer on how I tackled the problem on StackOverflow:
https://stackoverflow.com/questions/56269113/aggrid-in-react-redux-app-is-modifying-underlying-data
