### ISSUE TITLE
Memory leak when using cellRenderer function

### ISSUE THREAD

**Issue by catahoc** [ag-grid/ag-grid#3236]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/gVAS8HdfOZyZl9BbATSI

* use default grid sample
* add cellRenderer function and use it in one of columns
* generate and set new data using setInterval (10ms)

**Current behavior**
memory is consumed more than released (despite the GC) - memory leak

**Expected behavior**
memory is frequently consumed and released in equal volume

**Please tell us about your environment:**
Windows 7

* **ag-Grid version:** 21.0.1
Most recent at the moment of creating plunkr and issue

* **Browser:**
"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"

**Comment by catahoc** [comment]
I think the root cause is that AgComponentUtils.adaptCellRendererFunction is invoked on each cell render and instasntiates new class in memory

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi Alexander,

We have investigated your issue and while there may be a potential memory leak, it does not seem to be substantial. Please find the gif attached.

![Jul-11-201911-55-24](https://user-images.githubusercontent.com/24587174/64424679-9df67e80-d0a1-11e9-8283-f1c73dbdf712.gif)



Regards,
Davis

**Comment by catahoc** [comment]
Hi, thanks for response,
* in real grid you don't have 1 column, you have 50+ columns
* it is not necessarily a web page. sometimes it is application which is opened for days or even weeks

I cannot agree with you, because we faced actual OOM in our application during long-run test (keep app opened for 2-3 days. The fix - replacing functional cellRenderer with component cellRenderer - solved an issue.

I also think that it is not so hard to fix on your side - just don't call adaptCellRendererFunction on each render. You can compute it once at the grid init

**Comment by mainfraame** [comment]
@catahoc, I’ve realized these people clearly don’t give a crap as long as the issue is closed out and put into that black box (zendesk).

You guys are about as good as kendo when it comes to customer service and community engagement. Look where that got them.

**Comment by mainfraame** [comment]
@davis4acca ”it does not seem to be substantial”. 🤦‍♂️

**Comment by kiril-matev** [comment]
Hello catahoc!

Thank you for reporting this - much appreciated!

We have taken another look at this and reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5052 Memory leak when using cellRenderer function**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

We will not update this thread when this item is selected for implementation and we ask you to track the progress using the number of this issue (AG-5052) on our development pipeline here:
https://www.ag-grid.com/ag-grid-pipeline/

This way you can see whether this item is selected for implementation on the NEXT RELEASE tab.

I would recommend signing up for ag-Grid new release notifications. This way you'll know as soon as a new version is out and you can check whether this specific item (AG-5052) was implemented on the changelog page:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us.

**Comment by kiril-matev** [comment]
Hi @catahoc,

I wanted to follow up on this.

I've spent some time investigating the memory leak you reported earlier originally logged under:
https://github.com/ag-grid/ag-grid/issues/3236

In order to isolate plunker from this, I extracted the plunker sample code your provided above into a separate HTML file:
[memoryLeakSample.zip](https://github.com/ag-grid/ag-grid/files/6555670/memoryLeakSample.zip)

Using this HTML file I was not able to reproduce the issue you reported - I see no increase in memory usage over time (multiple hours between snapshots, multiple tests). 

I'm keen to investigate this further to confirm a potential issue and need your help to proceed. Can you please follow the steps below?

Please follow the steps below:
0. Close all instances of Chrome 
1. Open Chrome in incognito mode
2. Open attached memoryLeak.html file in Chrome
3. Take memory snapshot and note its size
4. Wait a few hours
5. Take memory snapshot and note its size

Do you see any increase in memory usage? Please share your findings here.

Looking forward to your response.

**Comment by camposfyi** [comment]
> Hi, thanks for response,
> 
> * in real grid you don't have 1 column, you have 50+ columns
> * it is not necessarily a web page. sometimes it is application which is opened for days or even weeks
> 
> I cannot agree with you, because we faced actual OOM in our application during long-run test (keep app opened for 2-3 days. The fix - replacing functional cellRenderer with component cellRenderer - solved an issue.
> 
> I also think that it is not so hard to fix on your side - just don't call adaptCellRendererFunction on each render. You can compute it once at the grid init

Using 

> Hi, thanks for response,
> 
> * in real grid you don't have 1 column, you have 50+ columns
> * it is not necessarily a web page. sometimes it is application which is opened for days or even weeks
> 
> I cannot agree with you, because we faced actual OOM in our application during long-run test (keep app opened for 2-3 days. The fix - replacing functional cellRenderer with component cellRenderer - solved an issue.
> 
> I also think that it is not so hard to fix on your side - just don't call adaptCellRendererFunction on each render. You can compute it once at the grid init

Using a class component fixed it for you? I have an application with up to a million rows and this is causing severe memory issues. Using a class based component for a cell renderer didn't help though.
