### ISSUE TITLE
AG-GRID EDGE browser not showing both scrollbar 

### ISSUE THREAD

**Issue by srjkrl20011991** [ag-grid/ag-grid#3246]
Ag-grid horizontal and vertical scroll bar is working fine for chrome and IE but not in EDGE browser.

Current behaviour.
Scroll bar is not visible

**Expected behavior**
Need to show scrollbar

* **ag-Grid version:** X.X.X
"version": "20.1.0"

* **Language:** REACT

![image](https://user-images.githubusercontent.com/31344825/60715911-c7791980-9f3b-11e9-843e-4e953ceee736.png)

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
