### ISSUE TITLE
'firstDataRendered' event fires BEFORE data is rendered for grids having rowModelType="infinite"

### ISSUE THREAD

**Issue by naibinh** [ag-grid/ag-grid#3263]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- Open https://plnkr.co/edit/q0yZGe5wgciyORKDXTL1?p=preview
- Open Chrome devtool
- Custom message 'onFirstDataRendered' in printed before data rows rendered.

**Current behavior**
onFirstDataRendered incorrectly fires BEFORE data is rendered when rowModelType="infinite". 

**Expected behavior**
onFirstDataRendered should only fire AFTER the data is rendered, so that user can know do custom action properly.

**Please tell us about your environment:**
MacOS Mojave

* **ag-Grid version:
20.0.0, 21.0.1

* **Browser:**
Latest Chrome

Similar issue https://github.com/ag-grid/ag-grid/issues/2662

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

We have investigated this issue and determined that this is not a bug.
 **The method name is misleading maybe as 'render' might be interpreted to mean rendered by the Browser, but this means rendered internally for the grid ( about to pass DOM elements to the browser)**

**Comment by naibinh** [comment]
@AhmedAGadir 
So you mean there is no event to notifty something like first data rendered?

**Comment by jsdevtom** [comment]
Hi @AhmedAGadir,

In that case, would you please update https://www.ag-grid.com/javascript-grid-resizing/#resize-after-data by mentioning that you cannot detect first data (browser)rendered at the section when using virtual scroll?:

> In the second case however you can only reliably use `firstDataRendered` as the row data will be made available, and hence rendered, after the grid is ready.

**Comment by kiril-matev** [comment]
Hello,
 
Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8812 When using infinite row model, onFirstDataRendered event is fired before data is rendered**
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!
