### ISSUE TITLE
Row height reset stopped working on custom cell renderes (19.1.2 -> 21.0.1)

### ISSUE THREAD

**Issue by MacGyver27** [ag-grid/ag-grid#3264]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Current behavior**
When grid gets resized or initialised I used `api.resetRowHeights()` to fix the height of cells and worked also for custom cell renderers. After upgrading from 19.1.2 to 21.0.2 it stopped working for custom cell rendereres registered via frameworkComponent: `cellRendererFramework: SwitchesNameRendererComponent`

**Expected behavior**
Row height adapted also for custom cell rendereres as used to be before 21 version.

**Please tell us about your environment:**
Happens everywhere..

* **ag-Grid version:** 21.0.2

* **Browser:**
Chrome/75.0.3770.100

* **Language:** [all]

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3068 | cellRenderer + autoHeight not working in the latest version

**Comment by MacGyver27** [comment]
Thank you for quick and prompt response, can try to test it? is it maybe released as aplha version or something??
Thanks, Michal

**Comment by erlichg** [comment]
Still happening on release 21.2.0.
AG-3068 is closed but still encountering this.

**Comment by davis4acca** [comment]
Note: When using a React Cell Renderer component with autoHeight, the grid api method resetRowHeights() must be called after the React component has been rendered. One suggestion on how this can be achieved is by using a timeout.

This is because React is asynchronously creating the components when it is initialised, however the grid needs the components created synchronously to know how big the components are. Hence, the solution is to use a timeout and call the api method, so that React isn't returning components asynchronously when calculating the row heights.

https://next.plnkr.co/edit/AILhmSvs68S5qnYy?preview

Regards,
Davis

**Comment by erlichg** [comment]
I tried that. Didn't work.
Only when I removed the reactNext parameter from the table, the suggestion with the timeout worked.
I'm on react 16. Do I need reactNext?

**Comment by leroydev** [comment]
For me it doesn't autosize rowheights too while using `reactNext={true}`.
I need to use `reactNext={true}` though, because without it, when using Material-UI V4 components inside cells, it will break the Material-UI styling.

Is there a way to use autoHeight with `reactNext={true}`? Note that I'm on `ag-grid-community` and `ag-grid-react` version 21.2.2
