### ISSUE TITLE
transform: translateY not calculating correctly when row height changed

### ISSUE THREAD

**Issue by Remilyonos** [ag-grid/ag-grid#3301]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```
**Requesting Community Support**

**Current behavior**
When assigning a rowHeight of 100 in grid options the resulting value for translateY is incremented by 28 for each row. Example 0, 28, 56 ...

However, when using getRowHeight in an anonymous method such as 
      getRowHeight: (params) => {
        return 100;
      },
The transform behaves correctly.

**Expected behavior**
The value for translateY should be incremented by the value for the new row height. Example, if row height is 50 the values for translateY should be 0, 50, 100 ...

**Please tell us about your environment:**
OS: MacOS
IDE: Webstorm 

* **ag-Grid version:** X.X.X
21.0.1

* **Browser:**
Chrome 75.0.3770.142

* **Language:** 
TypeScript 3.4

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
