### ISSUE TITLE
Horizontal scroll appear when call sizeColumnsToFit in big scale

### ISSUE THREAD

**Issue by Danatlol** [ag-grid/ag-grid#3319]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
Set 175% scale in display settings and 110% scale in Chrome v.76.
Than call sizeColumnsToFit() method.
Horizontal scroll appearing (seems its related to rounding of pxls).
![image](https://user-images.githubusercontent.com/22576150/63097418-0954a100-bf79-11e9-861c-1747482175ae.png)
![image](https://user-images.githubusercontent.com/22576150/63097450-1ec9cb00-bf79-11e9-9a67-3f082af55e11.png)

**Current behavior**
Horizontal scroll appeared

**Expected behavior**
No horizontal scroll, columns sized appropriate

**Please tell us about your environment:**
Windows X

* **ag-Grid version:** 20.0.0
Using Angular 7

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

* **Language:** TypeScript 3.2.4

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
