### ISSUE TITLE
[Style] Wrong '.ag-row-group-leaf-indent" if overriding the $cell-horizontal-padding SASS variable

### ISSUE THREAD

**Issue by ThomasKientz** [ag-grid/ag-grid#3322]
If you override the SASS variable `$cell-horizontal-padding`, the style of `ag-row-group-leaf-indent` is not correct anymore (margin-left is wrong) .

Currently 
```
// ag-theme-base.scss
.ag-row-group-leaf-indent {
    margin-left: $icon-size + $grid-size * 3;
}
```
```
// ag-grid-community/src/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss
$cell-horizontal-padding: $grid-size * 3 !default;
```

I think, changing to this will fix the issue.
```
// ag-theme-base.scss
.ag-row-group-leaf-indent {
    margin-left: $icon-size + $cell-horizontal-padding;
}
```

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
