### ISSUE TITLE
Filter doesn't show full list

### ISSUE THREAD

**Issue by jcmoore0** [ag-grid/ag-grid#3331]
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
When $grid-size is 8px, and there are only a few items (no overflow),  the filter list doesn't display all items.   This is possibly because ag-grid-virtual-container is calculating height based on item count and grid size.   When the grid-size is compact (4px), all items will display properly.

**Expected behavior**
When $grid-size is 8px, and there are only a few items (no overflow),  the filter list should display all items.

* **ag-Grid version:** 
v21.1.1

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
