### ISSUE TITLE
Keyboard inaccessible column controls

### ISSUE THREAD

**Issue by aardrian** [ag-grid/ag-grid#3340]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

I am not a customer, but I am evaluating ag-Grid for a client, a potential ag-Grid customer.

**Requesting Community Support**

I understand this will be closed if inactive for one month. However, as a non-customer I have no other way to report bugs.

**Providing a Reproducible Scenario**

1. Go to the [ag-Grid page promoting its accessibility](https://www.ag-grid.com/javascript-grid-accessibility/).

2. Scroll to the bottom and find the only demo on the page, [opening the Plunker in its own window](https://www.ag-grid.com/example-runner/vanilla.php?section=javascript-grid-accessibility&example=accessibility&enterprise=1&generated=1&grid=%7B%22theme%22%3A%22ag-theme-balham%22%2C%22noStyle%22%3A0%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3A1%7D) (I provide that link for ease of accessing it, but still do step 1 so you have the latest ag-Grid-sanctioned accessible demo).

3. Using a keyboard (`Tab` key), attempt to find or activate the hamburger control that allows you to pin a column, size a column, reset a column, or filter a column.

**Current behavior**
No hamburger controls receives keyboard focus.

**Expected behavior**
The hamburger control should receive focus when a user `Tab`s through the grid.

**Please tell us about your environment:**

* **ag-Grid version:** Whatever is the version in your live demo.

* **Browser:**
  * Windows 10, Internet Explorer 11
  * Windows 10, Chrome 76
  * Windows 10, Firefox 69

* **Language:** Whatever is the language in your live demo.

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.


This is the reference and summary of the relevant issue: AG-2472    Context/Column Menu - Focus menu when it is invoked, and allow keyboard navigation

**Comment by kiril-matev** [comment]
Hi @aardrian,

Thanks for bringing this up.

AG Grid has made big improvements in accessibility support since you opened this issue almost 3 years ago, and I encourage you to try this out in our latest version.

The specific issue you brought up is about focusing the column menu button in the column header. Currently, the column menu button isn't focusable using the keyboard and can be opened using the CTRL+ENTER keyboard shortcut. Try this out - please focus a column header cell and press CTRL+ENTER to see this in action. 

The reason the column menu button isn't focusable separately (by pressing TAB when focusing a column header cell) is that this would prevent users from quickly navigating across the column header cells by pressing the TAB key. If the column menu hamburger button is individually focusable by pressing TAB, this would effectively double the number of TAB key presses to move across column header cells, which we'd like to avoid.

This keyboard navigation behavior is the same as the one in Excel. When you activate filtering in Excel the filter button is displayed in the column header cell, but it isn't individually focusable when pressing the TAB key. Instead, focusing a column header and pressing the TAB key moves focus to the next column header cell. You can open the filter popup inside a column header cell using a keyboard shortcut - ALT+DOWN ARROW key.

AG Grid currently uses the CTRL+ENTER shortcut to open the column menu when a column header cell is focused. However, in order to make this more discoverable for users which are used to Excel we have entered a feature request to add support for ALT+DOWN ARROW key to open the column menu.

You can track this requirement in the product pipeline with this reference:
**AG-6713 [Accessibility] Allow column menu to be opened pressing ALT+DOWN ARROW key (just like Excel)**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

**It's important to clarify that our product pipeline is available publicly and you can look up the status of any item there:**
https://www.ag-grid.com/pipeline/

I would encourage you to keep track of the feature requests we've opened at this link, as we don't update individual github issues once a feature request is implemented or a bug resolved. This is why we close GitHub issues with this message, in order to avoid any confusion and point our users to the right place where they can get an update for feature request/bugs.

All completed items are listed in our changelog here:
https://www.ag-grid.com/changelog/

Thank you for reaching out to us with this requirement - we appreciate your time!
