### ISSUE TITLE
Setting grid filtering after setting row data no longer works in 21.2.0

### ISSUE THREAD

**Issue by crumhorn** [ag-grid/ag-grid#3345]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Filtering does not happen.

**Expected behavior**
Same as before version 21.2.0, that filters are applied to the grid.

**Please tell us about your environment:**
Windows 7

* **ag-Grid version:** X.X.X
21.2.0

* **Browser:**
Chrome Version 76.0.3809.100 (Official Build) (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Here's a plunkr:

[https://plnkr.co/edit/J35TEIjnswfmgzvYWpmd?p=preview](https://plnkr.co/edit/J35TEIjnswfmgzvYWpmd?p=preview)

all I did was take the existing one from https://www.ag-grid.com/javascript-grid-filter-api/ and added two lines after setRowData();

```
this.setCountryModel();
this.gridApi.onFilterChanged();
```

In the plunkr, clicking the button that applies the same filter (setCountryModel) does actually apply the filter. But doing it right after setRowData in the code does not work.

We have initial filters on every grid in our application, and all of them are now broken. The only way I managed to re-apply a filter that was initially set was to make some change to it that was not in the initial filtering. We have reverted back to the previous version of Ag-Grid for now.

**Comment by ceolter** [comment]
Two problems here: 1) example is wrong (should be calling instance.applyModel) and 2) Set Filter was incorrectly using the un-applied model.

Both fixed now and will be included in a patch release later this week.

Further info:

1) example is wrong

The provided filters have a new method applyModel(). It is explained on the Set Filter page here:
https://www.ag-grid.com/javascript-grid-filter-set/#set-filter-api

"Is important to note that when updating the set filter through the API is up to the developer to call filterInstance.applyModel() and then gridOptions.api.onFilterChanged() at the end of the interaction with the filter."

This method was introduced as the wrong model was getting used in filters. For example imagine two filters A and B. Both filters have 'apply button' active. User goes in an updates filter A but does NOT hit apply. Then user opens up filter B and updates it and hits 'apply' on filter B only. Result: The grid was running the filter and using the latest UI changes for both filter A and filter B.

The fix (in a previous release) was to have filters make a copy of the model when apply is pressed, so when the grid is filtering, the filters can use the copy of the filter made last time the filter was applied.

The impact of this is the Apply action needs to be done, regardless of the apply button used in the UI or not.

So for the set filter API methods, once done changing the UI state, then applyModel() needs to be called.

The example referred to above is now updated, so that applyModel() is called in the right place. The documentation is also updated to explain what applyModel() is and when it should be called. The website will be updated when the patch release is released.

2) Set Filter incorrectly using wrong model.

On implementing 1 above, a bug is in ag-Grid Set Filter. The filter is currently using the UI state rather than the applied model.

This is now fixed, the set filter makes a copy of the model when apply is pressed.

**Comment by ceolter** [comment]
For reference, the ag-Grid JIRA fixing this issue is AG-3271
