### ISSUE TITLE
ag-Grid: unknown menu item type copyWithHeadersCopy

### ISSUE THREAD

**Issue by tihomir22** [ag-grid/ag-grid#3357]
I'm submitting a
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request 
[] support request 
```
Current behaviour : I'm testing the AG-Enterprise edition to buy for our company and use it on daily basis, we were developing a custom contextual menu to add few features when something weird happened. We read the docs and they say that we can use their keywords like "copy" , "export" to add included functions, so i needed the "copyWithHeadersCopy" and i added it to my contextual config array. There is a short example of my contextual menu.

```
    return [
      "copy",
      "copyWithHeadersCopy",
      "paste",
      "separator",
      "contractAll",
      "expandAll",
      "separator",
      "autoSizeAll",
      "resetColumns",
      { custom item },
      { custom item },
      { custom item }
]
```

Expected behaviour : I expect to use the copy with Headers function from AG-GRID on my custom contextual menu without problems.

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.3
Node: 10.16.0
OS: linux x64
Angular: 8.1.3
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.3
@angular-devkit/build-angular      0.801.3
@angular-devkit/build-ng-packagr   0.801.3
@angular-devkit/build-optimizer    0.801.3
@angular-devkit/build-webpack      0.801.3
@angular-devkit/core               8.1.3
@angular-devkit/schematics         8.1.3
@angular/animations                8.2.4
@angular/cdk                       8.1.4
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.1.4
@ngtools/webpack                   8.1.3
@schematics/angular                8.1.3
@schematics/update                 0.801.3
ng-packagr                         5.5.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2
```

"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
