### ISSUE TITLE
updateRowData not updating cellrenderer value

### ISSUE THREAD

**Issue by SwatiMaheshwari** [ag-grid/ag-grid#3362]
**I'm submitting a bug

I have added getrowid and deltarowmode: true
Current behaviour. updateRowData doesnot update grid cell with renderer
Expected behaviour. it should update

**Please tell us about your environment:**
windows

* **ag-Grid version:** 20.0.2

* **Browser:**chrome

* **Language:** typescript, angular

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
