### ISSUE TITLE
Icons not displaying (squares are displayed instead)

### ISSUE THREAD

**Issue by yveslange** [ag-grid/ag-grid#3376]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I have activated the filter and sortable options. When hovering the header with the mouse, all icons are replaced by `squares` (check screenshot)

**Expected behavior**
The icons should displays !

**Please tell us about your environment:**
I have installed the latest NPM package:
```
npm install --save ag-grid-community
```

Here is my `index.html`
```
<script src="/node_modules/ag-grid-community/dist/ag-grid-community.min.noStyle.js"></script>
<link rel="stylesheet" href="/node_modules/ag-grid-community/dist/styles/ag-grid.css" />
<link rel="stylesheet" href="/node_modules/ag-grid-community/dist/styles/ag-theme-balham.css"/>
<link rel="stylesheet" href="/node_modules/ag-grid-community/dist/styles/webfont/agGridClassicFont.css"/>
<link rel="stylesheet" href="/node_modules/ag-grid-community/dist/styles/webfont/agGridBalhamFont.css"/>

+instanciating the grid as in the get started page
```

* **ag-Grid version:** 21.2.1

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"

* **Language:** all

![Capture](https://user-images.githubusercontent.com/17984393/64863695-c9471380-d635-11e9-868b-8c19d34701c9.PNG)

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by Prontsevich** [comment]
I have the same issue when trying to customize my app. I'm using Angular material on my project. I created 2 custom themes for material and want to customize ag-grid according to selected theme.
Everything work except icons.

my theme.scss:
```scss
@import '~@angular/material/theming';

@include mat-core();

.dark-orange {
  @import 'colors/dark-orange';
  @include angular-material-theme($orange-dark-theme);

  @import '~ag-grid-community/src/styles/ag-grid.scss';
  @import '~ag-grid-community/src/styles/ag-theme-balham-dark/sass/ag-theme-balham-dark.scss';
}

.light-orange {
  @import 'colors/light-orange';
  @include angular-material-theme($orange-light-theme);

  @import '~ag-grid-community/src/styles/ag-grid.scss';
  @import '~ag-grid-community/src/styles/ag-theme-balham/sass/ag-theme-balham.scss';
}
```

**Comment by ImranAhmed** [comment]
I have the exact same issue, I am using Clarity design not Material but my CSS for switching themes is same as above. All icons appear as squares!

**Comment by olu1987** [comment]
I had a The same issue using ag-grid-react. In my case it turned out that my base css was setting the font-family for my app using the !important override which was preventing the ag-grid font family from rendering within the table. In any case I would suggest you guys check to ensure that you are actually using the ag-grid fonts within the table and then if not you need to find out exactly why to fix the icons issue.

**Comment by yveslange** [comment]
Seems to work now. 

- I'm not important the fonts anymore
- I'm importing the CSS file sheet directly into the component rather than in the index.html

**Comment by user1385** [comment]
Is this issue resolved?
i have exactly the same issue and i don't see any answer...
anyone to help please?

**Comment by mayankthakur0007** [comment]
I was also facing the same problem, try importing it in component as well as in the index.html file
Worked for me!!

**Comment by mayankthakur0007** [comment]
> Is this issue resolved?
> i have exactly the same issue and i don't see any answer...
> anyone to help please?

I was also facing the same problem, try importing it in component as well as in the index.html file
Worked for me!!

**Comment by MaksimEpifanau** [comment]
Changing the 
![image](https://user-images.githubusercontent.com/72190678/116070679-9714e900-a695-11eb-8c0c-50c4660d1409.png)

To
![image](https://user-images.githubusercontent.com/72190678/116070760-aa27b900-a695-11eb-93a6-52fbb609a183.png)

Helped me out!

**Comment by heympriyesh** [comment]
> Changing the ![image](https://user-images.githubusercontent.com/72190678/116070679-9714e900-a695-11eb-8c0c-50c4660d1409.png)
> 
> To ![image](https://user-images.githubusercontent.com/72190678/116070760-aa27b900-a695-11eb-93a6-52fbb609a183.png)
> 
> Helped me out!

Thanks, it works for me.

**Comment by alvinAdler** [comment]
> Changing the ![image](https://user-images.githubusercontent.com/72190678/116070679-9714e900-a695-11eb-8c0c-50c4660d1409.png)
> 
> To ![image](https://user-images.githubusercontent.com/72190678/116070760-aa27b900-a695-11eb-93a6-52fbb609a183.png)
> 
> Helped me out!

You are a hero! I was setting the font style using the all selector ("*") in my main CSS. Changed it to HTML tag only and it worked like magic.

**Comment by SanketBeladiya** [comment]
its not work for me what should i do
