### ISSUE TITLE
When the data source contains illegal data, all ag-grid functions are not available.

### ISSUE THREAD

**Issue by JinHe-PerkinElmer** [ag-grid/ag-grid#3387]
I'm submitting a bug report:

**Current behavior**
If the ag-grid data source contains illegal data, for eg: Infinity or NaN (illeagal data result from some calculated logic), then the ag-grid selection, filter, sort fuctions don't work.

**Expected behavior**
I think the illegal data should't block ag-grid functions. Maybe it should throw an exception or an error.

**Please tell us about your environment:**
Windows PC

* **ag-Grid version:** 

     "ag-grid": "^18.1.2",
    "ag-grid-react": "^18.1.0",

* **Browser:**

"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36"

* **Language:** 

ES6/7

**Comment by icedjello** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
