### ISSUE TITLE
[toolpanel] Feature request: Toolpanel enhancements

### ISSUE THREAD

**Issue by JannesMeyer** [ag-grid/ag-grid#340]
Hi Niall,

We have plans for a few extra configuration options in a project:
- Hide value columns in the toolpanel
- Hide pivot columns in the toolpanel
- Have folders in the column picker to allow for predefined categorization of columns (This would break drag and drop column ordering)
- Show a separate box for drag and drop column ordering
- Only show a certain set of columns initially

Is this an area you already have plans for or would be accepting contributions to?

I realize that we could just do the column configuration outside of the angular grid world and pass the results as columnDefs. But because you already started on the toolpanel, why not work together on this?

This image illustrates what I imagine as the end result:

![columnpicker](https://cloud.githubusercontent.com/assets/704336/8906129/ea4e0372-3463-11e5-9847-d8f0f5f7a5a1.png)

Jannes

**Comment by ceolter** [comment]
i do have plans to extend this tool panel, but i don't have immediate plans (ie in the next few weeks). i'm always anxious of having others help me, because the project is 'all in my head' and without automates tests. in addition to this, people tend to implement what makes sense for them, rather than considering the grid as a reusable component.

having said that, yes i'm interested in doing some joint work here, as it should be pretty standard work. this toolbar can be so much better, and a real differentiation against other grids.

let me have a think about where things are going.

two items i want to do are a) have the columnController sharable between grids, so more than one grid can be working off the same set of columns (ie resize or  reorder in one grid, changes are in all grids, would be very useful for stacking grids, one on top of the other) and then b) have dockable filters, so you can have the (eg) 4 most common filters always showing in the toolpanel - this is probably in addition to the column managment, however it would need to fit in to the toolpanel, and what you are suggesting to me sounds like making the toolpanel a more generic sidebar with options on what to present to the user.,

**Comment by JannesMeyer** [comment]
Thanks for the answer! It sounds like you don't like the idea of grouping columns in the column picker. Do you have any other ideas or plans for cases where there are potentially 20-30 columns to select from?

Yes, it might make the toolpanel a little more generic, because not all data is shown initially, but as far as I understand that can be done without grouping as well (by setting `hide: true` on the column).

**Comment by ceolter** [comment]
No plans yet.

Where would you define the group? Is this the same group as the header group (as currently used)?

also, to show the group, would mean the 'List' component would need to be extended to be a tree. but this is what the grid is. maybe the grid can be used as the component here. but that would be a BIG change, something I'd really like to be personally heavily involved in.

**Comment by JannesMeyer** [comment]
Hi Niall,

Thanks again for the reply!

We're not using header groups in this particular case, but I also think it would be two different concerns being mixed. So in my opinion they should be different properties.

In regards to how to specify that grouping, I would definitely do it the same way as header groups.

```js
{
  headerName: 'Foo',
  field: 'bar',
  columnGroup: 'Group 1'
}
```

All ungrouped columns should show up in an "Other" group or something similar. And if there are no groups at all, it could just become a flat list without groups.

You are right that the grid component itself would make sense for the column picker. That is actually exactly what I would use if we decide against making that change! (I would do it outside of the toolpanel, though, because I don't fancy maintaining a fork of this excellent component).

**Comment by lenient** [comment]
@ceolter Same requirement of Hide value columns in the ToolPanel.

**Comment by a497988** [comment]
Is there any other way of that you know of to do this now? I have been able to successfully keep the checkboxes if I create it using 'groupColumnDef' the only problem is I need to specify another column to group on and then I get that group by header with the arrow. If I use the groupSupressRow it removes the checkbox column since I am no longer 'technically' grouping.

Any other suggestions as to if this is possible with current functionality? 
Or Given that you have a day job, and are busy, any sort of time-table for this feature?

**Comment by ceolter** [comment]
> I need to specify another column to group on and then I get that group by header with the arrow

sorry, i don't understand this?

re timeline, for the grid-panel re-vamp, either end of this year or Q1 next year. i'm very busy with Angular Connect preparation at the moment.

**Comment by a497988** [comment]
Sorry let me see if I can clarify:

If I use the groupColumnDef feature and create a column with a checkbox inside of it for selection, I also need to use the cellRenderer on another one of the columns I am defining and set it to group.

So column 1:
groupColumnDef - 'checkboxColumn'

column2:
Has to have the cellRenderer:group set, and then I also need to set the groupKeys['column2'].

Basically I want to have a column with checkboxes, but not have that column appear in the tool panel, and I didn't know if there was some workaround currently to do this.

**Comment by ceolter** [comment]
@a497988 i understand and fair request. no there is no workaround. sorry.

**Comment by kevpogo** [comment]
+1

**Comment by abhishek2016** [comment]
Hi Niall,
            Is the issue fixed now? I don't want to show the tool panel at all in my aggrid which gives the user to show and hide columns in grid. Unfortunately that will display the columns like id which is bit confidential.
![ag-grid-issue](https://cloud.githubusercontent.com/assets/22194775/18511572/0d583a60-7aa2-11e6-92ad-abe264db99e0.PNG)

**Comment by ceolter** [comment]
@abhishek2016 
you can stop the column menu from showing the column selection by setting suppressMenuColumnPanel=true (grid property)

**Comment by abhishek2016** [comment]
Hi Niall,
             I got to know by googling that I can use property 'suppressMenuColumnPanel' for hiding column panel. But how to hide tool panel? I don't wan't to use property 'suppressMenuMainPanel' as it hides all other options like 'Autosize All Columns', etc.

**Comment by ceolter** [comment]
@abhishek2016 customise the menu. see the docs on how you can alter the default list of items and remove the toolpanel option.

**Comment by etiennecrb** [comment]
Hi Niall,
Again, thanks for your amazing work. We've just updated from 4.x to 6.x and we are astonished by the quantity and the quality of the work you've done in the past months.

Our team faces a quite similar issue, we would like to hide some columns from the tool panel. Is this a feature you plan to add in a near future or should we find a workaround?

**Comment by ceolter** [comment]
@etiennecrb 
```astonished``` :) - you'll give me a big head!!!

i implemented 'suppressToolPanel' on column def yesterday. will be in a release we plan today / tomorrow.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-59

**Comment by prinks17** [comment]
Hello,

Is there a way by which I can add additional features to ToolPanel?
![toolpanel](https://user-images.githubusercontent.com/26967548/28769376-dcb71068-75f8-11e7-8a37-1042b04cee7b.png)


So, the idea is, since we don't have anything else in tool panel apart for show/hide column feature, wanted to use the available space to add some buttons for some specific actions to be done on the grid based on business requirement. 

So is there an option to customize tool panel.

Thanks & Regards,
Priyanka

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by SaikiranReddyAnugu** [comment]
Hi,
I have a checkbox column, is there a way to hide that column from toolpanel
