### ISSUE TITLE
Infinite loop in ClientSideRowModel.getRowIndexAtPixel

### ISSUE THREAD

**Issue by zerg960** [ag-grid/ag-grid#3413]
I'm submitting a bug report.

# Current behavior
There's an infinite loop in [rowModels/clientSide/clientSideRowModel.getRowIndexAtPixel](https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid-community/src/ts/rowModels/clientSide/clientSideRowModel.ts#L495) if

- The row model is not empty
- The pixel to match is somewhere between the first and last rows
- Row heights are changed using the setRowHeight row node API
- The table has not been laid out again by calling the grid API onRowHeightChanged (the call is on a setTimeout handler, but has not occurred yet)
- The pixel to match falls outside of the bounds of all rows within the table.

# Expected behavior
There shouldn't be an infinite loop.

Changing:
```
if (this.isRowInPixel(currentRowNode, pixelToMatch)) {
    return midPointer;
}
```

to return midPointer if the binary search pointers are right next to each other, appears to fix the issue. I will not be submitting a pull request, or tracking this issue.

# Please tell us about your environment:
* ag-Grid version: 21.0.1
I've checked the repository, this issue is still valid in the current version.
* Browser: All
* Language: All

I encountered this issue while using ag-grid-enterprise with React while using the .min.js file published in npm.

### Stack trace:
```
  | e.getRowIndexAtPixel | @ | ag-grid-enterprise.min.js:753
  | e.ensureRowHeightsValid | @ | ag-grid-enterprise.min.js:753
  | t.ensureRowHeightsValid | @ | ag-grid-enterprise.min.js:159
  | t.ensureAllRowsInRangeHaveHeightsCalculated | @ | ag-grid-enterprise.min.js:117
  | t.workOutFirstAndLastRowsToRender | @ | ag-grid-enterprise.min.js:117
  | t.redraw | @ | ag-grid-enterprise.min.js:117
  | t.redrawAfterScroll | @ | ag-grid-enterprise.min.js:117
  | (anonymous) | @ | ag-grid-enterprise.min.js:33
  | e.forEachSnapshotFirst | @ | ag-grid-enterprise.min.js:14
  | e.dispatchToListeners | @ | ag-grid-enterprise.min.js:33
  | e.dispatchEvent | @ | ag-grid-enterprise.min.js:33
  | t.checkBodyHeight | @ | ag-grid-enterprise.min.js:537
  | t.checkViewportAndScrolls | @ | ag-grid-enterprise.min.js:537
  | t.onCenterViewportResized | @ | ag-grid-enterprise.min.js:537
  | (anonymous) | @ | ag-grid-enterprise.min.js:14
  | setTimeout (async)
```

### Function:
```
e.prototype.getRowIndexAtPixel = function (e) {
    if (this.isEmpty())
        return -1;
    var t = 0
        , n = this.rowsToDisplay.length - 1;
    if (e <= 0)
        return 0;
    if (C._.last(this.rowsToDisplay).rowTop <= e)
        return this.rowsToDisplay.length - 1;
    for (; ;) {
        var o = Math.floor((t + n) / 2)
            , r = this.rowsToDisplay[o];
        if (this.isRowInPixel(r, e) || o == n && false)
            return o;
        r.rowTop < e ? t = o + 1 : r.rowTop > e && (n = o - 1)
    }
}
```

### Local Scope:
```
e: 985 // pixelToMatch
n: 27 // topPointer 
o: 27 // midPointer 
r: {... rowIndex: 27, rowTop: 961, rowHeight: 23 } // currentRowNode
t: 28 // bottomPointer
```

Row 26 covers pixels 918 - 941
Row 27 covers pixels 961 - 984 // top pointer & midPointer
Row 28 covers pixels 1004 - 1047 // bottom pointer

**Comment by dogle-scottlogic** [comment]
We have the same issue with the same version of ag-grid. Seems to be a result of setting a row height of 0

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by dogle-scottlogic** [comment]
Hi.
The issue is, as @zerg960 correctly identified, in the `getRowIndexAtPixel` function, specifically with the following code
```typescript
while (true) {

            const midPointer = Math.floor((bottomPointer + topPointer) / 2);
            const currentRowNode = this.rowsToDisplay[midPointer];

            if (this.isRowInPixel(currentRowNode, pixelToMatch)) {
                return midPointer;
            } else if (currentRowNode.rowTop < pixelToMatch) {
                bottomPointer = midPointer + 1;
            } else if (currentRowNode.rowTop > pixelToMatch) {
                topPointer = midPointer - 1;
            }

        }
    }
```
when the row height is 0, `isRowInPixel` will always return false, and as you have this inside a while(true) loop it will loop infinitely.

Plunker: https://next.plnkr.co/edit/0UALzGMylJPaa7tN
