### ISSUE TITLE
more expressive filter capabilities

### ISSUE THREAD

**Issue by MolallaComm** [ag-grid/ag-grid#3420]
Several years ago, i entered issue 1603 which got converted into AG-424 and eventually marked as fixed- only problem is only a small part of the issue was addressed (you added support for AND or OR instead of always AND between all the filtered columns) - but you didn't address arbitrarily complex filters at all unfortunately.  To give an example of the filtering functionality needed in ag-grid, check out the angular2-query-builder project or the following plunkr:

https://next.plnkr.co/edit/vtzerj4oFQLB6ukcxb9D?p=preview&preview

I can understand how this would probably be a fairly involved change and touch a lot of code/documentation so wouldn't blame you for not being overly enthusiastic about even entertaining it, but it would be a good feature to have and now that you have the option of having filters in the side panel, you'd even have a UI area to do it in.

We use odata as our backend and it fortunately *does* allow arbitrarily complex queries that can easily map to/from this type of ruleset approach.  We are contemplating just turning filters off in ag-grid and using angular2-query-builder with your grid - but wanted to mention the project as the plunkr visually demonstrates very well the kind of functionality we'd like to see natively in ag-grid some day.

Also, FWIW, one of your competitors mimics the same exact behavior albeit I'm sure their grid isn't nearly as robust or featureful as yours.

https://js.devexpress.com/Demos/WidgetsGallery/Demo/FilterBuilder/WithDataGrid/Angular/Light/

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Note that this is parked as of this time, just because of its complexity, which means that even though we are aware of this issue, we don't have any easy solution as of this time

This is the reference and summary of the relevant issue:





AG-2558 | Filters - Allow more than one AND/Or conditions for the filters
