### ISSUE TITLE
Icon Mapping Not Working for Custom toolPanel Framework Component

### ISSUE THREAD

**Issue by staufferl16** [ag-grid/ag-grid#3469]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
When I initialize the agGridReact React component, specifying a custom framework component to add to the toolPanel bar and custom icon mapping for the custom toolPanel, the bar correctly renders with desired functionality and appearance.  However, the custom icon does not appear even after ensuring that the class name matches what appears in the DOM.

Code steps below:

1. Add custom toolPanel to toolPanel list:
```javascript
const sideBar = {
  toolPanels: [
    {
      id: "filters",
      labelDefault: "Filters",
      labelKey: "filters",
      iconKey: "filter",
      toolPanel: "agFiltersToolPanel"
    },
    {
      id: "columns",
      labelDefault: "Columns",
      labelKey: "columns",
      iconKey: "columns",
      toolPanel: "agColumnsToolPanel",
      toolPanelParams: {
        suppressPivots: true,
        suppressPivotMode: true
      }
    },
    {
      id: "custom-charts",
      labelDefault: "Charts",
      labelKey: "custom-charts",
      iconKey: "charts",
      toolPanel: "customGridChartPanel"
    }
  ],
  defaultToolPanel: "filters"
};
```

2.  Declare icon mapping for the custom tool panel:
```javascript
const customChartIconClass = "ag-icon-charts";

const iconMapping = {
  [customChartIconClass]: "<i class='fe fe-chart'></i>"
};
```

3.  Initialize AgReactComponent with custom details:
```javascript
render() {
  return (
    <AgGridReact
          animateRows
          pagination
          ......
          sideBar={sideBar}
          icons={iconMapping}
          frameworkComponents={{ customGridChartPanel: CustomGridChartPanel}}
    />
}
```

4. Component renders with all desired functionality, but the desired icon does not show.

**Expected behavior**
The icon mapping is applied to the toolPanel component, and the desired icon appears on the toolPanel's tab.

**Please tell us about your environment:**
I'm using a mac and developing a web app for Chrome browsers.  I'm using yarn for package management, webpack for module bundling, and node for serving up the application.  No IDE, just using Sublime Text.

* **ag-Grid version:**
ag-grid-react: 21.1.0
ag-grid-enterprise: 20.2.0
ag-grid-community: 20.2.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

* **Language:**
 ES5

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code **in a plunker** and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
