### ISSUE TITLE
Floating filter text input handler doesn't allow text to be modified after Enter has been pressed

### ISSUE THREAD

**Issue by shutupmarley** [ag-grid/ag-grid#3480]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
In a scenario where floating filters are enabled and the filter type is set to text, we type our filter criteria and hit enter. The filter runs. We go to modify the floating filter text and any input is reverted back to the original filter criteria about half a second later. The only way to change or clear the filter text is to open the dropdown, clear the text input, and click "Apply."
See here: https://kapwi.ng/c/zh3ZHWgh

**Expected behavior**
The floating filter text input handler should be fully functional and the text input should be able to be modified multiple times. Users should not have to use the dropdown input to clear the floating filter input as this defeats the purpose of having a floating filter input.

* **ag-Grid version:** 21.2.2 (enterprise)

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

* **Language:** React 16.10.2

**Comment by firstredpepper** [comment]
Agreed - this is not intuitive. Does anyone have a workaround until the bug is fixed?

Ticket on StackOverflow here: https://stackoverflow.com/questions/58694853/ag-grid-column-filter-not-showing-new-values

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
