### ISSUE TITLE
SerializedNumberFilter is missing in the export

### ISSUE THREAD

**Issue by totszwai** [ag-grid/ag-grid#3490]
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

Regression?
- https://github.com/ag-grid/ag-grid/issues/1995

Just try to import the following will fail in the latest 21.2.2

```
import { SerializedNumberFilter } from 'ag-grid-community';
```

In fact, greping `SerializedNumberFilter` from `node_modules/ag-grid-community` returns nothing. No breaking change was mentioned in the release note.

Installed versions were:
```
    "ag-grid-angular": "^21.2.2",
    "ag-grid-community": "^21.2.2",
```

**Comment by rb-mwindh** [comment]
Same issue here. Class disappeared without warning :-(

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi Yan,

We tried to reproduce this but we couldn't.

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Since it is impossible to use in this case any web based tool to provide with a reproducible scenario, I would suggest that you send us whatever is that you can so you can investigate further. Some suggestions are:

- github

- zip files

- code fragments


Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

Thanks



Davis‍
