### ISSUE TITLE
Charts - Aggregation fails on cells with NULL

### ISSUE THREAD

**Issue by stevro** [ag-grid/ag-grid#3493]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I was curios about the charts and discovered that when creating charts from a cell range with cells that have NULL as value, the following error occurs in the aggregation process:

```
ag-grid-enterprise-21.2.2.js:45964 Uncaught TypeError: Cannot read property 'value' of null
    at ag-grid-enterprise-21.2.2.js:45964
    at Array.forEach (<anonymous>)
    at ag-grid-enterprise-21.2.2.js:45957
    at Array.forEach (<anonymous>)
    at ChartDatasource.aggregateRowsByDimension (ag-grid-enterprise-21.2.2.js:45956)
    at ChartDatasource.getData (ag-grid-enterprise-21.2.2.js:45824)
    at ChartModel.updateData (ag-grid-enterprise-21.2.2.js:45433)
    at ChartController.updateForGridChange (ag-grid-enterprise-21.2.2.js:45258)
    at ChartController.init (ag-grid-enterprise-21.2.2.js:45238)
    at ag-grid-enterprise-21.2.2.js:5506
```

**Expected behavior**
If cell data is empty or null the aggregation function should return 0 or '' (blank). Probably determined by the cell data type.

* **ag-Grid version:** 21.2.2

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
