### ISSUE TITLE
[Angular] Cannot select a cell when preventDefaultOnContextMenu is true

### ISSUE THREAD

**Issue by zburkhardt-zz** [ag-grid/ag-grid#3501]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Cell does not become focused (selected) when you click on it if preventDefaultOnContextMenu is set to true. Clicked and focus events are still triggered and the row itself becomes selected, however the actual focus/select never occurs for the specific cell. If I remove this setting then cell selection works as expected.

Another interesting behavior I have noticed regarding this is that if I double click to edit a cell and then hit ESC or click elsewhere to close the edit popup the cell now has focus and I can click other cells to focus them, use the keyboard, etc. But once I click outside of my table I can no longer click on the table to gain focus again unless I double click a cell to begin editing it.

Also, when preventDefaultOnContextMenu is true if you also have the enableCellTextSelection set to true you will not be able to click/drag to select any text in a cell. It seems that these browser events are not propagating whenever preventDefaultOnContextMenu is enabled.

**Expected behavior**

Cell should become focused upon clicking on it. The cell should be outlined so that you can see that it is focused and you should be able to interact with the cell/table via the keyboard (e.g. arrowing between cells, deleting the contents of a cell, entering edit mode for a cell, etc.)

**Minimal reproduction of the problem with instructions**
Using this simple ag-grid causes the issue:
<ag-grid-angular
style="width: 500px; height: 500px;"
class="ag-theme-material"
preventDefaultOnContextMenu="true"
[rowData]="rowData | async"
[columnDefs]="columnDefs"
rowSelection="multiple">

By simply removing preventDefaultOnContextMenu="true" the issue goes away and I can once again select cells by clicking on them and navigate/edit via the keyboard.

**What is the motivation / use case for changing the behavior?**
Without being able to select cells the user is unable to use any keyboard keys to navigate, delete, edit cells. Also, visually you cannot see which cell is active.

**Please tell us about your environment:**

MacOS Mojave 10.14.6, IntelliJ, npm 6.10.1,

* **ag-Grid version:** 22.0.0

* **ag-grid-angular version:** 22.0.0

* **Browser:** all

* **Language:** all

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by zburkhardt-zz** [comment]
Absolutely. Here is the plunker that reproduces the issue using one of the angular examples from the documentation. https://plnkr.co/edit/BcuP1g38MBafcYfvqLlx?p=preview

All I had to do to reproduce the issue is add preventDefaultOnContextMenu="true" to the ag-grid-angular element in the app.component.ts template.

After adding the above configuration I can no longer click on a cell to give it focus. The row still gets selected but the specific cell never seems to receive the click event. From my understanding, preventDefaultOnContextMenu should disable the default context menu that comes up when right clicking, but all other table/cell interactions should continue to work as expected.

Let me know if you need any addition information/details.

**Comment by zburkhardt-zz** [comment]
Clarification. From my investigation, the cell still receives the click events. However, the cell never receives focus. This has many potential negative impacts, but one being that you cannot use the keyboard to begin editing in a cell since the cell is never focused.
