### ISSUE TITLE
AutoGroupColumnDef shows valueGetter field and not valueFormatter field

### ISSUE THREAD

**Issue by alexyhkim** [ag-grid/ag-grid#3538]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

```js
idColumn = {
    headerName: "ID",
    rowGroup: true,
    valueGetter: idValueGetter,
    valueFormatter: firstNameValueFormatter
}

autoGroupColumnDef = {
  headerName: "First Name"
}
```
The auto group column def will show the ID as value in group row, when it should be the first name instead. So there is no way to display a different field for group row, than the field it was grouped by.

**Comment by AhmedAGadir** [comment]
Hi,

Unfortunately we can't tell what your issue is given your description. 

This ticket is going to nbe flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
