### ISSUE TITLE
Pasting empty strings ('') from clipboard will edit two grid cells

### ISSUE THREAD

**Issue by juvo87** [ag-grid/ag-grid#3550]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Pasting empty strings ('') from clipboard will edit two grid cells in a row. It edits the focused cell (single selection) and the cell next to it. 

It can be reproduced in ag-Grid versions: 22.0.0, 21.2.2, 21.2.1, 21.2.0

Example Grid: https://www.ag-grid.com/example.php

Steps to reproduce: 
1) Focus cell in column 'Game Name', for example "Chess" in row 1 
2) Delete cell value and leave cell editor
3) Copy this cell to clipboard (Ctrl+C)
4) Select cell below, for example "Bul" in row 2
5) Insert copy (Ctrl+V)

**Expected behavior**

Ctrl+V should only edit the selected cell.

Docs: 
> Press keys Ctrl+V while focus in on the grid with a single cell selected. The paste will then proceed starting at the selected cell if multiple cells are to be pasted.

It works like expected in ag-Grid version 21.1.0. This issue doesn't occur when using range selection.  

**Please tell us about your environment:**

Windows 10, Webstorm IDE, Yarn/NPM

ag-Grid version: 22.0.0
ag-Grid enterprise + Angular 8

Browser: Chrome 78

Language: Typescript 3.5.3

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3703

Regression Pasting empty strings ('') from clipboard will edit two grid cells

**Comment by paulsung-keys** [comment]
I'm facing this issue and do not see AG-3703 in the pipeline anymore. Has this been fixed?

**Comment by brendellya** [comment]
Same.  I see the changelog says this feature is done.  However, I'm seeing on our current project and it's still a problem on the ag-grid website. 

You see where I pasted the value "20" into the cell, and the cell beneath has an empty string.

![image](https://user-images.githubusercontent.com/1074495/223564446-28e76051-bc86-4f57-a61a-9e72250dbd27.png)

**Comment by StephenCooper** [comment]
> Same. I see the changelog says this feature is done. However, I'm seeing this issue on our current project and it's still a problem on the ag-grid website.
> 
> You see where I pasted the value "20" into the cell, and the cell beneath has an empty string.
> 
> ![image](https://user-images.githubusercontent.com/1074495/223564446-28e76051-bc86-4f57-a61a-9e72250dbd27.png)

@brendellya please open a new issue with a code reproduction to help us investigate and track this.

**Comment by brendellya** [comment]
Just an update for my solution.  I was having a issue due with the prescribe methods because our grid instance only accepts numbers or null values, and we have various pattern validations.  So using only one of the process methods was not helpful.  The processDataFromClipboard expects to return `string[][] | null` instead of `number[][] | null`.  However, I found that using both methods together worked for me.  This may or may not be a factor for others, but I'm will note my solution here, for reference.

I found that if I use `processDataFromClipboard` to iterate over all pasted data and remove empty values (this process runs first and can cancel all pasted data with null).  I can return a new data set with valid strings that have a length.  If you are submitting strings to the backend, you can stop there.  For converting to strings to numbers or different format the `processCellFromClipboard` will return `any` type of data on a per cell basis.  

The fact that these methods can be used to together was not explained on the documentation.  And I would suggest that even if the issue is finally fixed, it may be a good idea to let developers know that they have more flexibility with processing pasted data using this combination.  

Finally, I believe what's happening is due to how the data is copied.  If you click into the excel cell then you will only copy the data inside.  However if you click the cell or cells, the pasted data will add a tabs as well as a newline/return which is causing the empty string value beneath.  It's not visible in the actual clipboard, but it's visible when you paste into a notepad or doc file.  Hope this helps other devs.

**Comment by StephenCooper** [comment]
Hi @brendellya,

You may actually benefit from the follow property that can be set on gridOptions: `suppressLastEmptyLineOnPaste `

> Set to true to work around a bug with Excel (Windows) that adds an extra empty line at the end of ranges copied to the clipboard.

https://ag-grid.com/javascript-data-grid/grid-options/#reference-clipboard-suppressLastEmptyLineOnPaste
