### ISSUE TITLE
JavaScript heap out of memory for react-scripts build (React Web)

### ISSUE THREAD

**Issue by matthewdschulman** [ag-grid/ag-grid#3552]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

When I try to do a production build (react web) of ag-grid, I get this error:

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x37c7e7dcfc7d]
    1: StubFrame [pc: 0x37c7e7dd119d]
Security context: 0x3df4d619d9d1 <JSObject>
    2: SourceMapGenerator_serializeMappings [0x3df42d5c2121] [/Users/matthewschulman/Development/Trove/trove_web_app/node_modules/terser/node_modules/source-map/lib/source-map-generator.js:~312] [pc=0x37c7e8e695bc](this=0x3df42986d8a9 <SourceMapGenerator map = 0x3df4f5fda451>)
    3: SourceMapGenerator_toJSON [0x3df42d5c...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20191204.131746.5782.0.001.json
Node.js report completed
 1: 0x1000664d8 node::Abort() [/usr/local/Cellar/node/11.14.0/bin/node]
 2: 0x100066b6d node::OnFatalError(char const*, char const*) [/usr/local/Cellar/node/11.14.0/bin/node]
 3: 0x10018059b v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/11.14.0/bin/node]
 4: 0x10018053c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/11.14.0/bin/node]
 5: 0x1004439c4 v8::internal::Heap::UpdateSurvivalStatistics(int) [/usr/local/Cellar/node/11.14.0/bin/node]
 6: 0x10044544f v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/Cellar/node/11.14.0/bin/node]
 7: 0x100442d20 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/Cellar/node/11.14.0/bin/node]
 8: 0x100441aca v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/Cellar/node/11.14.0/bin/node]
 9: 0x100449a38 v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/Cellar/node/11.14.0/bin/node]
10: 0x100449a84 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/Cellar/node/11.14.0/bin/node]
11: 0x10042a2fb v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/Cellar/node/11.14.0/bin/node]
12: 0x100608dca v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/Cellar/node/11.14.0/bin/node]
13: 0x37c7e7dcfc7d
14: 0x37c7e7dd119d

I've tried a bunch of workarounds such as increasing the memory allocation, but nothing seems to work. Any ideas? Thanks.

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
