### ISSUE TITLE
Double click in the column group border should be adjusted to the length of the group header

### ISSUE THREAD

**Issue by ezequiel89** [ag-grid/ag-grid#3569]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Double click in the column border only adjust the column data and the columns header into the column group. The column group header is not affected with the double click like the ag-grid demo.

Before https://ibb.co/pjkTHQK
After https://ibb.co/wgQp1mc

**Current behavior**
Double click in the column border only adjust the column data and the columns header into the column group. The column group header is not affected with the double click like the ag-grid demo.

**Expected behavior**
Double click in the column group border should be adjusted to the length of the group header.

**Please tell us about your environment:**
Windows
https://www.ag-grid.com/example.php#/

* **ag-Grid version:** 21.2.2

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

I will mark this ticket as managed-by-community so that our community can potentially provide you with a workaround
