### ISSUE TITLE
Different imports

### ISSUE THREAD

**Issue by skywalker-ua** [ag-grid/ag-grid#3586]
On this page you have not updated code in CodePen https://www.ag-grid.com/react-grid/

**Comment by shuheb** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hi,

Thank you for your message. This is in our backlog now and we are tracking it with the following reference and description.

AG-3704 - React getting started guide stackblitz example is using module import instead of package import

You can follow the status of feature requests, bugs and releases using our pipeline:

https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
