### ISSUE TITLE
 v22.1.1 Could not find a declaration file for module './dist/ag-grid-enterprise.cjs.js'. 'xxxx/node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.cjs.js' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by tuphampro** [ag-grid/ag-grid#3589]
Could not find a declaration file for module './dist/ag-grid-enterprise.cjs.js'. 'xxxx/node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.cjs.js' implicitly has an 'any' type.

![image](https://user-images.githubusercontent.com/19162524/71506152-572bcf00-28b2-11ea-9ebf-e5688c31dee1.png)

**Comment by shuheb** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Since it is impossible to use in this case any web based tool to provide with a reproducible scenario, I would suggest that you send us whatever is that you can so you can investigate further. Some suggestions are:

- github

- zip files

- code fragments


Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

Thanks

**Comment by roblugt** [comment]
I have the same issue using Typescript 3.7.5

**Comment by Liero** [comment]
In order to reproduce it, you need to set `noImplicitAny: true` in tsconfig.

**Comment by Liero** [comment]
@shuheb: you really shouldn't close the issue so fast. This is enterprise feature and we pay for it. Bug was reported and you haven't even tried to look at it
