### ISSUE TITLE
Columns go wrong when a second table is added to the DOM

### ISSUE THREAD

**Issue by MicMicMon** [ag-grid/ag-grid#3591]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Environment:**
Angular, latest versions 8.2.14

* **ag-Grid version:** 22.1.1

**Current behaviour.**

I create my grid and call `forceAdjustColumns`, so everything goes ok:
![image](https://user-images.githubusercontent.com/37897072/71545385-bbba5d00-298a-11ea-8cab-0f02394b4eb1.png)

Now, because of an operation, another grid is dynamically added to the DOM.

`forceAdjustColumns` is called on the new grid, and it displays ok.

But in the process, the **first** grid, that was there before, is now screwed up (notice the red part, the columns have been wrongly resized):

![image](https://user-images.githubusercontent.com/37897072/71545467-90843d80-298b-11ea-8bae-b7a3e8526d32.png)

Now, if I manually issue a `forceAdjustColumns` to the first grid, it goes back to ok. But it means I have to manually do that for each grid each time I add a new grid on the screen.

Is that a bug, or I'm doing something wrong with the API? As far as I know, the two grids do not share any resource.

**Comment by shuheb** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Since it is impossible to use in this case any web based tool to provide with a reproducible scenario, I would suggest that you send us whatever is that you can so you can investigate further. Some suggestions are:

- github

- zip files

- code fragments

Thanks

**Comment by MicMicMon** [comment]
Sorry, I'm not sure how to build that plunker to make it easy for you. Do you have a base plunkr I can tweak?

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
