### ISSUE TITLE
Theming broken in 22.1.1

### ISSUE THREAD

**Issue by MicMicMon** [ag-grid/ag-grid#3593]
When several SCSS themes are imported, the first import bleeds on the other theme.

My code is:
```
@import "@ag-grid-community/all-modules/dist/styles/ag-grid.css";
@import "@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss";
@import "@ag-grid-community/all-modules/dist/styles/ag-theme-material/sass/ag-theme-material.scss";
```

Then if I use the material theme, I get a wrongly themed grid (weird mix between balham & material):

![image](https://user-images.githubusercontent.com/37897072/71741363-05111d80-2e5f-11ea-81e4-3923ead72130.png)

If I comment out the balham.scss import, I get the correct grid:

![image](https://user-images.githubusercontent.com/37897072/71741409-26720980-2e5f-11ea-820e-7459fdf4f4c6.png)

Which seems to indicate the SCSS variables & stuff have scope & collision issues.

Reversing the two display the same behaviour (if material is imported first, then balham, a balham-themed grid will be a weird mix).

So, for now, I can only use a single theme through my app because of that.

**Comment by shuheb** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Since it is impossible to use in this case any web based tool to provide with a reproducible scenario, I would suggest that you send us whatever is that you can so you can investigate further. Some suggestions are:

- github

- zip files

- code fragments


Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

Thanks
