### ISSUE TITLE
Column should ensure displayName is in string format

### ISSUE THREAD

**Issue by KatiaUQTR** [ag-grid/ag-grid#3594]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**

Either bug or error of use. I am creating dynamically column names and some of them were dates and years. With year column names, they are saved as numbers and not string so their displayName is a number and not a string and will break some functions such as:

Function:
`PrimaryColsListPanel.prototype.filterColumns `

Error:
displayName.toLowerCase() is not a function

`            var displayName = comp.getDisplayName();
            return displayName !== null ? displayName.toLowerCase().indexOf(_this.filterText) >= 0 : true;`

**Expected behavior**

When saving the displayName or getting the displayName, a toString would make it safe.

**Comment by shuheb** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Since it is impossible to use in this case any web based tool to provide with a reproducible scenario, I would suggest that you send us whatever is that you can so you can investigate further. Some suggestions are:

- github

- zip files

- code fragments


Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

Thanks
