### ISSUE TITLE
server side row model causes multiple api calls in different scenarios.

### ISSUE THREAD

**Issue by hammad-zia-95** [ag-grid/ag-grid#3627]
[x] bug report
[] feature request
[] support request
```
**Current behavior**
Whenever setColumnState(), setSortModel(), setFilterModel(), setPivotMode() are called,
getRows() method of IServerSideDatasource is called each time which causes alot of repetition
 and overhead. 

**Expected behavior**
There should be a way to prevent the grid from calling getRows() method of IServerSideDatasource
whenever layouts are being set using setColumnState(), setSortModel(), setFilterModel() etc. There
should be a mechanism to fire this event manually after the layout state has been set. When we are
dealing with millions of records, there is a lot of overhead if there is an api call after each
set state method.

**Please tell us about your environment:**
Operating system: Windows 10
IDE: VS Code

* **ag-Grid version:** ag-grid-enterprise": "22.0.0"

* **Browser:**
Google Chrome v79.0.3

* **Language:** 
Angular v8.2.14
TypeScript v3.4.5

**Comment by AhmedAGadir** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
