### ISSUE TITLE
Floating Filter documentation for AGGrid is wrong

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#3639]
I get this error:

![image](https://user-images.githubusercontent.com/364896/73274719-50acb200-41e6-11ea-97d6-922ea088bb48.png)

But the Documentation here https://www.ag-grid.com/javascript-grid-floating-filter-component/ is not yet fixed

**Comment by icedjello** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by jogibear9988** [comment]
Look at your Page:

https://www.ag-grid.com/javascript-grid-floating-filter-component/

see:

<img width="819" alt="Bildschirmfoto 2020-01-31 um 08 07 35" src="https://user-images.githubusercontent.com/364896/73519263-d310be00-4400-11ea-8aa8-52ad73e90e89.png">

and now llok at the error...

the onFloatingFilterChanged named here is wrong.

maybe you can provide migration guide when you do breaking changes.

**Comment by jogibear9988** [comment]
@icedjello I added infos, maybe you can look again
