### ISSUE TITLE
Column tool panel not visible

### ISSUE THREAD

**Issue by monis001** [ag-grid/ag-grid#3647]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
If reporting a bug make sure to state.

**Current behaviour**. : Not able to open column tool panel 
**Expected behaviour.** :  It should open column tool panel 

* **ag-Grid version:** **22.1.1**

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript : 3.5.3
Angular 8

I am trying enterprise feature (by installing enterprise edition and it shows red flag in console ) in my local specific to **Columns Tool Panel** and I am getting this 
![ag-grid1](https://user-images.githubusercontent.com/46885793/73657775-ffeefa80-46b8-11ea-8be8-1ae074e0e68a.png)

**Comment by ImranAhmed** [comment]
I hit the same issue with Filters Tool Panel. Would love to evaluate the enterprise edition before we have to make a call between this and DevExtreme. Please advise on how to resolve this.

**Comment by ImranAhmed** [comment]
OK, looks like I resolved it. The [documentation ](https://www.ag-grid.com/javascript-grid-side-bar/)  is wrong. The Angular example has following in HTML markup. Remove this and side panels should work. 

`[modules]="modules`

**Comment by seanlandsman** [comment]
@monis001 If you're using modules you need to include the `@ag-grid-enterprise/column-tool-panel` - please see here (https://www.ag-grid.com/javascript-grid-modules/#modules) for full documentation

@ImranAhmed the examples you reference do need this property as we use this to supply the modules required:

`public modules: Module[] = AllModules;`

In your case are you perhaps using the non-modules based package `ag-grid-enterprise`? This might explain what you're seeing

**Comment by ImranAhmed** [comment]
@seanlandsman Yep, I tried the enterprise version.

**Comment by shuheb** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
