### ISSUE TITLE
processGroupHeaderCallback never called

### ISSUE THREAD

**Issue by prashantjain68** [ag-grid/ag-grid#3648]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
In the export to CSV params, specify a function for the param processGroupHeaderCallback. Put a break point when csv export is in process. You will notice that it is never called.

Grep the source for "processGroupHeaderCallback" keyword. You will find zero instances.
I also stepped into the source code for "gridApi.getDataAsCsv(params)" and I see "processHeaderCallback" and "processCellCallback" used but no reference/ use of processGroupHeaderCallback.

If reporting a bug make sure to state.

Current behaviour.
processGroupHeaderCallback not called during csv export.

Expected behaviour. If possible back this up with our docs/examples if possible
processGroupHeaderCallback should be called during csv export.
https://www.ag-grid.com/javascript-grid-export/

**Please tell us about your environment:**
Mac, VSCode, nodejs

* **ag-Grid version:** X.X.X
12.1.x

* **Browser:**
Chrome 80

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
JavaScript

**Comment by shuheb** [comment]
Hi,

It looks like you are using v12, is that correct?

If so, can you try upgrading to the latest version and see if this fixes your issue. 

If this doesn't solve your issue, can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are

A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
A plunker
If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

Select the framework that is appropriate to you from the drop-down
Open it in plunker. (Use the button plunker in our example)
Add your changes so that the behaviour is reproduced
Save and Freeze the plunker(On the top left corner)
Send us the link to the plunker(You can copy the URL from the browser)
If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by Krishnakanth94** [comment]
@prashantjain68   can you upgrade and try the Ag-grid version to the latest.It's working for me.

**Comment by aruprakshit** [comment]
I have this, but I see group header callback not being called.

```js
const defaultExportParams = {
  autoConvertFormulas: true,
  skipColumnGroupHeaders: false,
  processGroupHeaderCallback: (params) => {
    console.log('processGroupHeaderCallback', params);

    return params.value;
  },
  processCellCallback: (params) => {
    console.log('processCellCallback', params);

    return params.value;
  },
};

export default defaultExportParams;
```
