### ISSUE TITLE
"agSetColumnFilter" breaks application 

### ISSUE THREAD

**Issue by simkessy** [ag-grid/ag-grid#3652]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

```
import { ColDef } from "ag-grid-community";
import "ag-grid-enterprise";

  const columnDefs: Array<ColDef> = [

    {
      headerName: "Severity",
      field: "enforcement",
      filter: "agSetColumnFilter",
      width: 150}
]
```

I tried changing the filtering on my grid to use "agSetColumnFilter" but that lead to this error: 

`TypeError: Object prototype may only be an Object or null: undefined
next-server.js:67
message:"Object prototype may only be an Object or null: undefined"
stack:"TypeError: Object prototype may only be an Object or null: undefined\n    at setPrototypeOf (<anonymous>)\n    at extendStatics (/Users/me/code/bextools/apps/stl/node_modules/ag-grid-enterprise/dist/lib/setFilter/setFilter.js:8:16)\n    at __extends (/Users/me/code/bextools/apps/stl/node_modules/ag-grid-enterprise/dist/lib/setFilter/setFilter.js:11:9)\n    at /Users/me/code/bextools/apps/stl/node_modules/ag-grid-enterprise/dist/lib/setFilter/setFilter.js:37:5\n    at Object.<anonymous> (/Users/me/code/bextools/apps/stl/node_modules/ag-grid-enterprise/dist/lib/setFilter/setFilter.js:343:2)\n    at Module._compile (internal/modules/cjs/loader.js:959:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)\n    at Module.load (internal/modules/cjs/loader.js:815:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:727:14)\n    at Module.require (internal/modules/cjs/loader.js:852:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anon...`

**Expected behavior**
 I thought it would enable excel like filtering 

**Please tell us about your environment:**
MacOSx 

* **ag-Grid version:** X.X.X
 ag-grid-community                         ^20.1.0 
 ag-grid-enterprise                         21.1.0 
 ag-grid-react                             ^20.1.1  

* **Browser:**
Chrome

* **Language:** [all | TypeScript 3 | ES6/7]

**Comment by shuheb** [comment]
Hi,

It looks like you are using different versions for enterprise, community and the react wrapper.

I would recommend upgrading to the latest on all of these so that they are the same version, and see if this fixes your issue.

If you still have the issue after you've moved all the ag-grid includes to use the same (latest) version,  please provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
