### ISSUE TITLE
Problem with context menu and tool panel

### ISSUE THREAD

**Issue by xaru123** [ag-grid/ag-grid#3654]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

**Expected behavior**
Hello. i have problem like in https://github.com/ag-grid/ag-grid/issues/3647.
I have a key and that why i dont have red error in console
But i try example from documentation. And nothing happens.
Example 1 from here https://www.ag-grid.com/javascript-grid-tool-panel-columns/.

Current behaviour. : Not able to open column tool panel, context menu
Expected behaviour. : It should open column tool panel, context menu

ag-Grid version: 22.1.1
Browser:
Chrome
Language: [all | Vue.js | ES6/7 | ES5]
![2020-02-06_23-27-51](https://user-images.githubusercontent.com/32548935/73966746-73eb0600-4938-11ea-8a6b-053e9b9bc2c4.png)

![2020-02-06_23-28-38](https://user-images.githubusercontent.com/32548935/73966765-7baaaa80-4938-11ea-9095-25491c0cf9c7.png)

**Comment by shuheb** [comment]
Hi,

It seems that you are missing a few imports. Note that if you are using the modules way of installing ag-grid (https://www.ag-grid.com/javascript-grid-modules/#ag-grid-modules), you will require only the following imports:
@ag-grid-enterprise/all-modules
@ag-grid-community/vue

Note that to import the Vue Wrapper, you will need to do as so:

import {AgGridVue} from '@ag-grid-community/vue'

You would not need these imports:
- @ag-grid-enterprise/column-tool-panel (this is given by all-modules)
- ag-grid-community
- ag-grid-vue

If this doesn't solve your issue, can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
