### ISSUE TITLE
Missing exports for /filter/provided

### ISSUE THREAD

**Issue by ar41bald** [ag-grid/ag-grid#3657]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
[Here](https://stackblitz.com/edit/ag-grid-angular-hello-world-pdxec8) is an example of the bug.
![image](https://user-images.githubusercontent.com/12528704/74131718-44acf100-4be5-11ea-882f-10e7092697c0.png)

**Current behavior**

Starting from the version ^22.0.0 there is no possibility to import anything from `ag-grid-community/dist/lib/filter/provided` as **there are no exported** _.js_ files

**Expected behavior**

Import from the `ag-grid-community/dist/lib/filter/provided` should work as previously as there are no breaking changes regarding this.

**Please tell us about your environment:**

Windows 10, Intellij IDEA, npm

* **ag-Grid version:** X.X.X

```
ag-grid-community: ^22.0.0
```

* **Browser:**

Chrome/79.0.3945.130

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7, ES5

**Comment by shuheb** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
