### ISSUE TITLE
error when navigating from cell component

### ISSUE THREAD

**Issue by vlio20** [ag-grid/ag-grid#3664]
Hi,
I have the following template for `ICellRendererAngularComp`:
```
<button [matMenuTriggerFor]="menu" mat-icon-button>
  <mat-icon>more_vert</mat-icon>
</button>

<mat-menu #menu="matMenu">
  <button [routerLink]="['../', state.employee.id, 'update']" mat-menu-item>
    <mat-icon>edit</mat-icon>
    <span>Edit</span>
  </button>
</mat-menu>
```

When  clicking the `routerLink` button the following error is thrown:
`Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?`

The workaround that I used to make it work is to change the template to:
```
<button [matMenuTriggerFor]="menu" mat-icon-button>
  <mat-icon>more_vert</mat-icon>
</button>

<mat-menu #menu="matMenu">
  <button (click)="navTo(['../', state.employee.id, 'update'])" mat-menu-item>
    <mat-icon>edit</mat-icon>
    <span>Edit</span>
  </button>
</mat-menu>
```

and within the component:
```
  navTo(path: string[]): void {
    this.ngZone.run(() => this.router.navigate(path, {relativeTo: this.route}));
  }
```

It seems like the `ICellRendererAngularComp` is running outside a zone

**Comment by nerumo** [comment]
it's still an issue in the latest version, please reopen

**Comment by appimpact** [comment]
Still an issue with version 25.0.1.

Here is an example:
![image](https://user-images.githubusercontent.com/34662138/108180335-ecb59e00-7106-11eb-97db-e8980512871a.png)

You can see a form partially rendered  below the grid.
This happened after column with routerLink directive inside of it was clicked.

Once the cell with routerLink is used, occasionally entire UI gets broken with "Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?

It is very hard to catch kind of bug as it happens very rarely but it still happens.

**Comment by vitale232** [comment]
@appimpact I'm encountering something similar in `25.1.0` using Angular Material `11.1`. Did you ever find a workaround?

**Comment by nitoloz** [comment]
Having same problem with `24.1.0` and using  `this.zone.run(() => ...)` workaround, but it's quite error-prone and looks wrong to copy-paste in every single place where `cellClick` callback is used.

**Comment by vitale232** [comment]
@nitoloz What errors are you encountering? 

I ended up using the `NgZone` solution as well, but I kept the `routerLink` directive in place (even though it fails) to ensure I get the accessibility of a native anchor. I haven't had problems since

**Comment by nitoloz** [comment]
@vitale232 sorry for a delayed reply. I'm using aggrid for the PWA and have it running on both web and mobile. I'm mainly performing navigation to details pages on `(cellClicked)`. When using on web it's all perfectly fine, but once switching to mobile (especially Android tablets) sometimes navigation isn't performed or like "half-way through", meaning that details page starts loading, but some angular CD is missing. At this point rotating tablet helps and page finally loads, so it's not about resolvers or anything like that I assume

For me it looks like ag-grid emits `(cellClicked)` output outside of ng-zone, because once I wrapped all callbacks connected to `(cellClicked)` into `this.zone.run(() =>... );` it starts working perfectly, but I don't think that's an intended behaviour.

By the way I'm also using `"@angular/core": "9.1.13"` + `"@angular/material": "9.2.4"` additionally to `"ag-grid-angular": "^24.1.0"`
