### ISSUE TITLE
Excel Export Line Number and Column Alphabets font size is bigger

### ISSUE THREAD

**Issue by ngramprabhu** [ag-grid/ag-grid#3676]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
By default, excel export from AgGrid is setting the font as "Calibri" and size as "14".  I tried to change the font using below config.  Headers and Cell contents changed as per given font and size. But line numbers and Column Albhabets (A,B,C...) are still in Calibri with 14 size. 

This makes a odd zoom behavior when looking at excel.

`excelStyles={[{
                    id: 'header',
                    font: {
                        fontName: "Arial",
                        size: 10,
                    },
                }`

Current behaviour: Line Numbers and Column Alphabets are not considering excelStyles Config.
Expected behaviour. Line Numbers and Column Alphabets should consider excelStyles Config.

**Please tell us about your environment:**

* **ag-Grid version:** 21.2.2

* **Browser:** Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AhmedAGadir** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by oakstreetrec** [comment]
@ngramprabhu did you figure this out?

the same thing is happening to me. one clue that isn't in your original post: the reason that using excelStyles to change output header and cell font size isn't a complete solution is because it seems that somehow the exported file also messes around with the 'Normal Style' in your excel sheet. that's what changes the row and column ids to 14 point. you can make the output file look normal by not doing any of the excelStyles stuff and, in the exported excel file, right click on 'Normal' in the Styles area and change the font size back to normal.

see here: https://dm.certent.com/help/Content/D_Draft/Format/excel_normal_style.htm#:~:text=Setting%20the%20Normal%20Style%20for,default%20font%20and%20Font%20size.

so the question is, why do ag-grid exported excel files have this reset 'normal style'??

**Comment by qimuxi1990** [comment]
I witnessed the same as @oakstreetrec , and we should have a solution here. Either avoiding reset 'normal style' or providing an id so we can set our preferred style, like 'header'.

**Comment by gportela85** [comment]
@qimuxi1990 @oakstreetrec the problem is being fixed, check the next release.

**Comment by qimuxi1990** [comment]
@gportela85 Great thanks for your update. I'll upgrade after the next release and take a look.
