### ISSUE TITLE
onFilterChanged ag-grid deprecated

### ISSUE THREAD

**Issue by MahmoudAbdAlKareem** [ag-grid/ag-grid#3683]
Versions:
    "ag-grid-community": "^22.1.1",
    "ag-grid-react": "^22.1.1", 

Your docs here: https://www.ag-grid.com/javascript-grid-filter-external/ are using deprecated API without any clarification about the alternatives of this API. 

And following the docs that you wrote the grid is not working as expected,  I implemented                   

isExternalFilterPresent={isExternalFilterPresent}
doesExternalFilterPass={doesExternalFilterPass} 

and doesExternalFilterPass is never called. even If return true on isExternalFilterPresent, and after calling  gridApi.onFilterChanged(); 

browser: chrome latest version.

**Comment by AhmedAGadir** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by adnetv** [comment]
I'm having the same problem. I'm doing a server-side row model for a React-node app and the isExternalFilterPresent and onFilterChanged both get triggered, but doesExternalFilterPass does not. Is it supposed to work only with client side? I've been researching this like crazy and there's nothing I could find on github/docs/stack-overflow that could help.

**Comment by julietkb** [comment]
Any updates on this?

**Comment by adnetv** [comment]
@julietkb  https://github.com/ag-grid/ag-grid/issues/3700 there’s another solution for it. The problem is it is not supposed to be used with server-side, they just need to clarify that in the docs
