### ISSUE TITLE
Filtering for integer column with value 0 not working (other values do work)

### ISSUE THREAD

**Issue by Vortilion** [ag-grid/ag-grid#3702]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
ColumnDef:

> 
    {
        field: 'agKontoTyp',
        hide: true
    }

filtering via AngularJS-Function, where "filters" is a JS-Object which can contain multiple values:

> 
    function submitFilter(gridOptionsApi, filters) {
            gridOptionsApi.setFilterModel(null);

           [...]

            if (filters.account) {
                gridOptionsApi
                    .getFilterInstance('agKontoTyp')
                    .setModel({type: 'equals', filter: filters.account});
            }

            [...]

            gridOptionsApi.onFilterChanged();
        }

**Current behavior**
If I filter for column with field 'agKontoTyp' which contains an Integer via an external filter (Button with ng-click-bound AngularJS-Function) for a column with value 0, it always displays all rows, as if there was no filtering at all. Other numbers (1 or 2 e.g.) work as expected.

**Please tell us about your environment:**
Windows 10, Intellij IDEA, Tomcat 8.46, AngularJS 1.6.x

* **ag-Grid version:** X.X.X
20.1.0 (also tested it with 22.1.1)

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36 Edg/80.0.361.62"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by AhmedAGadir** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
