### ISSUE TITLE
Column header frozen when drug out of grid on iOS

### ISSUE THREAD

**Issue by ipipwong01** [ag-grid/ag-grid#3712]
Hi 

I am facing the problem when ag grid community perform at Safari 13.0.5 (Mac OS)
![image](https://user-images.githubusercontent.com/40753468/76208088-f9b0e880-6239-11ea-8c86-000094322133.png)
And also safari 13 on ios and ipados 
its same problem happen on both google chrome device

I am using ag grid community version 22.1.1
Please help to solve this problem 

Thanks

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by ipipwong01** [comment]
hi Davis,

Can you show me some example for describe my scenario?
i haven subscribe the enterprise version. Will do it after i implement success from community edition
