### ISSUE TITLE
Rows not rendering with default rowHeight

### ISSUE THREAD

**Issue by Novice052** [ag-grid/ag-grid#3725]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
My app does not specify a rowHeight for my rows.  The documentation states that the default height is 25px.  On some machines, the rows are rendered correctly, on others, the rows are squashed together appearing as though rowHeight were set to 0 or 1px.

**Expected behavior**
Per the [documentation](https://www.ag-grid.com/javascript-grid-row-height/):
"By default, the grid will display rows at 25px."

**Please tell us about your environment:**
Windows 10, WebStorm, React, Babel, Webpack

* **ag-Grid version:** 21.0.1

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"

* **Language:** [all | ES6/7 | ES5]
![squashedRows](https://user-images.githubusercontent.com/8519859/77003845-520f7680-691b-11ea-88f0-8fa895789c82.PNG)

**Comment by shuheb** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
