### ISSUE TITLE
ag-react-grid unable to update state after cell edit

### ISSUE THREAD

**Issue by stephtea** [ag-grid/ag-grid#3734]
ag-react-grid v.23.0.0

Upon editing a cell in the grid, you are no longer able to update any parent component's react state. Once a react state property is updated, the cell's changes get reverted and an error is thrown.

The error received is **Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering.**

Setting the state in react triggers a re-render of the component, it is possible it is related to the grid being re-rendered by react after a cell is edited.

It is also referenced here: https://github.com/ag-grid/ag-grid/issues/3680

**Comment by shuheb** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by stephtea** [comment]
Reproduceable scenario is found in the linked issue https://codesandbox.io/s/ag-grid-formik-fieldarray-integration-cjcie

Or for a more simplistic reproducible scenario, edit **_any cell_** and then try to edit **_any react state prop_** inside ag-react-grid v.23.0.0.

Please reopen @shuheb

**Comment by shuheb** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:
AG-4049: ag-react-grid unable to update state after cell edit 

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by seanlandsman** [comment]
@stephtea 

I'm looking at this issue now - does this warning cause actual issues in your application(s)? From the repo provided it doesn't appear to actually impact the normal working operation of it.

I'm not suggesting this isn't something that needs to be fixed but rather am trying to determine the seriousness of it.

thanks

**Comment by stephtea** [comment]
@seanlandsman In my situation, it was blocking the use of editing cells. I'll try to come up with another example.

**Comment by stephtea** [comment]
@seanlandsman In order to get around the issue, I reworked my code and used an external dialog on cell press. When turning back on editing, the error is still thrown, but it is not blocking the functioning of editing anymore. I would say in summary, in certain scenarios it is blocking, but atleast for mine, it is not. I'll see if I can dig up the version in which it was blocking, but it may be lost.

**Comment by seanlandsman** [comment]
thanks, that would be helpful but I understand if it's no longer possible
