### ISSUE TITLE
Ag grid checkbox multiple selection using ctrl or shift + click is taking too long

### ISSUE THREAD

**Issue by mmariyuva** [ag-grid/ag-grid#3761]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
If we have more grids (10 ag grids) with cell editable & multiple cell renderers in same page then Ag grid checkbox multiple selection using ctrl or shift + click is taking too long.

Checkbox selection delay is related to the amount of time keyboard key pressed.
<Press ctrl or shift key(not released upto some time<5sec>) + mouse click>
 In chrome browser console it shows "[Violation] 'keydown' handler took <N>ms".

**Facing this issue after ag grid upgrade to latest version (from 22.1.1 to 23.0.2)**. Previous version(ag-grid 22.1.1) checkbox selection is working fine & mouse click event didn't wait for keydown event completion

**Please tell us about your environment:**
IntelliJ (latest), npm(latest), node(latest)

ag-Grid version:
ag-grid-community: 23.0.2 + Angular 9

Browser:
Chrome 80

Language:
Typescript 3.8.3

**Comment by icedjello** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
