### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by wmira** [ag-grid/ag-grid#3762]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'

```
**Providing a Reproducible Scenario**

**Current behavior**

If you destroy an ag-grid instance, you would expect every resources it uses gets cleaned up. It seems it is not the case and it is continuing to build up memory. This is apparent on web apps that loads and destroys a view with ag-grid within the same html view and then destroying the instance after the user has decided to close the grid.

If you took the snapshot after hitting destroy. You would notice huge data still left in memory. RowNodes, eventhandlers etc.

Plunker 
https://plnkr.co/edit/tTxAAaaypyBRCwQL?preview

**Expected behavior**
Resources should have been cleaned up

**Please tell us about your environment:**
Windows, Linux, Chrome browser

* **ag-Grid version:** 23.0.2

* **Browser:**

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Javascript

**Comment by icedjello** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG-4075: Memory leak when destroying the grid

**Comment by wmira** [comment]
@icedjello I'm curious why this was closed given that the issue is still there.

**Comment by mainfraame** [comment]
@wmira im curious too... I’m starting to explore alternatives tomorrow’s with product owners at my company. I’ve dealt with two years of this nonsense and realize better open source alternatives are available (specifically for react).

**Comment by kiril-matev** [comment]
Hi wmira, mainframe,

Thank you for bringing this up. 

Let me explain our process on GitHub issues here so you can more effectively follow the status of the issues you've open.

@wmira: Responding to the specific memory leak issue you referenced - as mentioned in the comment from icedjello above, this issue was logged as AG-4075. It was resolved in ag-Grid v23.1 which was released on May 1st, 2020. We provide the reference to the JIRA item above (AG-4075) for two reasons:
1) You open our pipeline page, look up this item and see if it is scheduled for the next release:
https://www.ag-grid.com/ag-grid-pipeline/
2) Following a release (please sign up for release notifications on ag-grid in github), you can look up this item (AG-4075) in the changelog to see if it was fixed in that new version:
https://www.ag-grid.com/ag-grid-changelog/

This way we provide you the key to tracking the progress of this item through our development process and getting an updated status at any one point. 

This is why soon after we log an item in our backlog, we close the corresponding github issue - because we've already logged this item and provided a reference for you to look it up. At this point, we do not follow up on individual Github issues to update them when a bug has been resolved. The rationale for this is that we've already provided the item key (AG-4075) for anybody to see if this has been fixed in a later release of ag-Grid using the two links I listed above (pipeline and changelog).

This is why the status of a GitHub issue (open/closed) doesn't reflect whether this is an active(unresolved) bug in ag-Grid - it only reflects whether it was processed by our support team. Once the issue is processed and a reference is provided, you can simply look up the issue in our pipeline/changelog using the reference we've provided.

Also, you don't need to look up GitHub issues looking for any specific problem you're having - it's much more reliable to just open a new GitHub issue and report your specific issue. We will do the rest - investigate it, log it, and give you the reference to track it on our pipeline/changelog pages. I think this is where our support team adds a lot of value, because we have the bandwidth to investigate each issue reported and definitively establish whether it's an issue we've already logged, or it's a new issue.

This is why whenever you have an issue, just submit a new GitHub issue following the template we recommend to report an issue and we will investigate/reproduce/log a new issue or link to an existing issue. We're keen to do this extra work to ensure that we're tracking your issue correctly and we can resolve it, instead of you looking up and down different GitHub issues trying to figure out for yourself which one covers your use case best.

We value your input and I hope this explanation helps to explain why GitHub issues are closed after a while - because we've transferred the corresponding issue report to our own JIRA system which is exposed through the pipeline and changelog pages on our website. This integration with our JIRA system allows you you can look up any item and see when it's scheduled for implementation or which version it was implemented in. This way we can provide you the latest status on a specific item, which we believe provides a higher level of service.

@mainfraame: I hope this clarifies our process and why it's a better way of tracking issues. If you have any problems using ag-Grid, please submit GitHub issues following our template - we'll investigate, reproduce, log and give you the JIRA reference (such as AG-4075 above), so you can get an update at any point on its progress through our development process.
