### ISSUE TITLE
downloaded bundles, es6 import, pagination icons are empty squares

### ISSUE THREAD

**Issue by dongxuHuang** [ag-grid/ag-grid#3781]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Download /dist from gitlab
Import js from `ag-grid-community.js`
Import css as
```
@import "./helpers/ag-Grid/css/ag-grid.css";
@import "./helpers/ag-Grid/css/ag-theme-alpine.css";
```
HTML
```
<div id="aggrid" style="margin: 1rem; height: 100%; width:100%;" class="ag-theme-alpine">
</div>
```
Pagination true.

**Current behavior**

Icons for pagination are blank squares.

**Expected behavior**

Correct arrow icons I guess..

**Please tell us about your environment:**

babel core: 7.6.4
babel/code-frame: 7.5.5

* **ag-Grid version:**  Release 23.0.2

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

![Screen Shot 2020-04-14 at 3 03 13 PM](https://user-images.githubusercontent.com/44783908/79263872-9ed66680-7e61-11ea-9772-6007d8f161c3.png)

This is the agGridAlpineFont.css. The agGridClassicFont.css looks like this too. 

![Screen Shot 2020-04-14 at 3 07 38 PM](https://user-images.githubusercontent.com/44783908/79264016-d47b4f80-7e61-11ea-996f-0da4611d52ec.png)

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by dongxuHuang** [comment]
Thanks Davis.

Here is my [Plunker](https://plnkr.co/edit/B9rQWPIsgYu4axG0).

I think the issue is probably with the css files downloaded from Git, for example: https://github.com/ag-grid/ag-grid/blob/master/community-modules/all-modules/dist/styles/agGridAlpineFont.css

**Comment by davis4acca** [comment]
Hi,

All the plunker's icons look just fine:
![image](https://user-images.githubusercontent.com/24587174/79580236-a0ea3080-80c0-11ea-8ec5-bb08a6efeb4e.png)


Note, the reason why you are seeing the boxes in your code editor or your browser when looking at the below link is that both your browser and your code editor down have the font styles loaded so they default to render an empty box.

:  https://github.com/ag-grid/ag-grid/blob/master/community-modules/all-modules/dist/styles/agGridAlpineFont.css

We don't think this is a BUG. We will mark this issue closed. 
If you do think this is not the case please create a new ticket with a plunker that shows clear steps on how to reproduce your issue.

Regards,
Davis

**Comment by dongxuHuang** [comment]
Thank you Davis, I will try your suggestions.
