### ISSUE TITLE
None of the events(onRowClick, onRowSelected etc) fires after opening context menu one time

### ISSUE THREAD

**Issue by manishkrai** [ag-grid/ag-grid#3797]
Hi,

I am using custome context menu in ag-grid. I observed that once I open context menu after right click on row after this no event fires (rowSelected, rowClicked) even context menu popup closed after left clock.

[getContextMenuItems]="getContextMenuItems"
(rowSelected)="onRowSelected($event)"
(rowClicked)="onRowClick($event)"

Scenario to reproduce -
1. Handle Event (rowClicked)="onRowClick($event)" or (rowSelected)="onRowSelected($event)".

2. Left click on any row/cell anytime, These events are firing.

3. Now right click on any cell to open context menu. Now close the context menu without any selection by left click.. Now try left click on any row/cell above events are not firing.

Note:- I also tried - (cellContextMenu)="cellContextMenu($event)".. This is only firing first time when we open context menu through right click. Now close by left click, Again do right click to open context menu.. Its opening but cellContextMenu event is not firing.

ag-grid-angular, Version - 20.1.0

Manish

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by manishkrai** [comment]
Expected Behaviour - rowClicked event should fire after every left click.
Actual Behaviour - rowClciked are firing until context menu is not opened(means no right click yet). Now right click to open context menu, discard contect menu selection by left click. Now, again do left click any times, rowCllick is not firing.
[sample plunk](https://plnkr.co/edit/eqlaa1PmHd7BPuED)

**Comment by manishkrai** [comment]
> Hi,
> 
> Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?
> 
> Accepted reproducible scenarios are
> 
> * A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
> * A plunker
> 
> If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:
> 
> * Select the framework that is appropriate to you from the drop-down
> * Open it in plunker. (Use the button plunker in our example)
> * Add your changes so that the behaviour is reproduced
> * Save and Freeze the plunker(On the top left corner)
> * Send us the link to the plunker(You can copy the URL from the browser)
> 
> If reporting a bug make sure to state.
> 
> Actual behaviour.
> Expected behaviour. If possible back this up with our docs/examples if possible
> 
> Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario
> 
> If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact [info@ag-grid.com](mailto:info@ag-grid.com) for access. This is our primary channel for Support.

Please check below plunker
https://plnkr.co/edit/eqlaa1PmHd7BPuED

**Comment by manishkrai** [comment]
Please find below plunker

https://plnkr.co/edit/eqlaa1PmHd7BPuED
