### ISSUE TITLE
ag-grid-react noRowsOverlay shown instead of the loadingOverlay

### ISSUE THREAD

**Issue by croraf** [ag-grid/ag-grid#3811]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
X

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- initialize ag-grid react component 
- let the initial data be null/undefined
- this shows loadingOverlay
- after the data is fetched and set to the actual data, the overlay is removed and the data is shown
- put data again to null/undefined on the same ag-grid table instance (re-fetching of data)
- the table should show loadingOverlay again, but instead it shows noRowsOverlay

**Current behavior**
On the second and subsequent setting of data to null/undefined it shows noRowsOverlay.

**Expected behavior**
On the second and subsequent setting of data to null/undefined it should show loadingOverlay, as in the initial setting.

**Please tell us about your environment:**
Ubuntu, 

* **ag-Grid version:** 22.1.1

* **Browser:**

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by croraf** [comment]
@makinggoodsoftware Is https://plnkr.co/edit/zrFfVfwHJpuhl72F ok?

1. On initial load "loading" overlay is correctly shown.
![image](https://user-images.githubusercontent.com/19698636/81008630-8d2a2280-8e53-11ea-9f6a-b9d5fbd01d9c.png)

2. On subsequent reloads "no rows" overlay is shown. This is incorrect. "Loading" overlay should be shown on reloads also, if the data is `undefined` or `null`.
![image](https://user-images.githubusercontent.com/19698636/81008749-bba7fd80-8e53-11ea-92b3-85839f6897c1.png)
