### ISSUE TITLE
Why are you closing memory leak issues?

### ISSUE THREAD

**Issue by wmira** [ag-grid/ag-grid#3836]
ag-grid has some memory leak issues. Why are the bug reports on memory leak being closed?

**Comment by rmc-software** [comment]
Reopened https://ag-grid.atlassian.net/browse/AG-4075.

Note this doesn't happen when using modules, we'll investigate why it's happening with the bundled version also.

**Comment by mainfraame** [comment]
@rmc-software can u explain AG-4241 then? FYI, I am still experiencing the bug you supposedly solved with AG-4241; another memory leak. This issue was supposedly solved with 24.1.0, but it’s not. 

This is the fourth memory leak issue I’ve experienced since v20+ with your product and this time it’s caused a 2 month delay to production. 

The previous post by @wmira has a point.  If you want current customers to stay, you need to allow these issues to stay open and let the community discuss them along side your developers. Unlike your ticketing system, GitHub allows discussions to take place and you can easily identify changes that go into fixing issues.  That’s why you need a way to tie your AG-XXXX tickets to GitHub issues; and treat GitHub issues as first class citizens. It’s like asking someone to look at your jira tickets; it’s just nonsense. No one can access any detail on the work performed; we are only left with a brief description (that often changes). This leaves me (and I’m sure many others) feeling like your dev team operates out of a black box.

**Comment by kiril-matev** [comment]
Hi mainframe,

Thank you for bringing this up and letting us respond to your concerns.

Responding to the specific memory leak issue you referenced:
I'm sorry to hear that memory leaks have had an impact on your project delivery timeline. I would suggest reporting any issues as soon as possible so we can assist and avoid any delays to your project. 

Memory leak issues have many different facets and sometimes one might think that a memory leak reported by another user covers their own use case while actually that's not the case. This is why I would encourage you to open a separate github issue with the full details on how to reproduce the memory leak you're experiencing. We will then work with you to reproduce the issue and file it under an existing issue or create a new one if needed.

Based on your comment it seems that the changes we made to address AG-4241 have not helped in your case. Perhaps the issue was reported for a scenario that was similar but sufficiently different from yours which is why you're still seeing an issue even after AG-4241 was resolved. In order to speed up the issue reporting/verification/resolution process, I would recommend to submitting a separate github issue for your specific scenario even if there's an issue about a similar-sounding scenario. Only this way you can be sure that if we log an issue it will resolve the exact issue you are seeing.

With this said, I'm keen to get the details necessary to reproduce the memory leak issue so we can resolve it. Please open a new github issue for it so we can track it separately.

Responding to your general comments on process:
1) We have a way to tie AG-XXXX tickets to github issues - we add a label to the issue indicating the name of the AG-XXXX issue. See this issue for example and note the label pointing to an AG-XXXX issue:
https://github.com/ag-grid/ag-grid/issues/4295

2) We treat Github issues as first-class citizens - this is because we treat Github issues with the same priority as those reported on our support system. We have investigated all the issues reported on GitHub and (where needed) added them to our internal system to be addressed in future versions of ag-grid. Our product team then works to resolve these issues regardless of where they were reported.

3) There's no need to look at our JIRA tickets - please just submit a separate GitHub issue following the template we recommend to report an issue and we will do all the work from that point on - we will investigate/reproduce/log a new issue or link to an existing issue. We're keen to do this extra work to ensure that we're tracking your issue correctly and we can resolve it, instead of you looking up and down different issues trying to figure out for yourself which one covers your use case best.

Please let me know if you have any further questions and submit a new GitHub issue for the memory leak you're experiencing - I'm keen to work with you to reproduce/log/resolve that as soon as possible.
