### ISSUE TITLE
 Selecting rows via shift + click does not fire selectionChanged event in ag grid version 23

### ISSUE THREAD

**Issue by mmariyuva** [ag-grid/ag-grid#3863]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
- While pressing Shift or Ctrl keys (not released & select checkboxes) to select rows, the "selectionChanged" event is not triggered & selected row count not updated.
- Selected count is updated after released the key.

**Expected behavior**
"selectionChanged" event should trigger & selected row count should be updated when selecting rows via Shift or Ctrl keys (if keys are not released also).

**Providing a Reproducible Scenario**

Stackblitz demo for both ag-grid versions
ag-grid 23.0.2 - https://stackblitz.com/edit/angular-aggrid-23-rowselection
ag-grid 22.1.1 - https://stackblitz.com/edit/angular-aggrid-22-rowselection

**Facing this issue after ag grid upgrade from 22.1.1 to 23.0.2 version**. Previous version(ag-grid 22.1.1) "selectionChanged" event triggered & selection count updated, while pressing(not released upto some time<5sec>) Shift or Ctrl key.

**Please tell us about your environment:**
IntelliJ (latest), npm(latest), node(latest)

**ag-Grid version:**
ag-grid-community: 23.0.2 + Angular 9

**Browser:**
Chrome 80

**Language:**
Typescript 3.8.3

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hi,

We investigated your issue and the stackblitz examples you sent and found that the behaviour is the same on both, so we are unable to reproduce your issue. We've attached a screenshot at the bottom to show this - v23 is on the left and v22 is on the right. We tested this on the latest version of chrome: Version 83.0.4103.97.

I would suggest testing this in the latest version of chrome and seeing if the issue persists. If it does feel free to create a new issue with a reproducible scenario.

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

![image](https://user-images.githubusercontent.com/37620997/84487035-1a079d80-ac96-11ea-94d9-be992f196b6c.png)

**Comment by mmariyuva** [comment]
Hi @shuheb,

I have tested with latest version of Chrome browser (Version 83.0.4103.97) but I am facing the same issue, "selectionChanged" event invoked after shift key released.
