### ISSUE TITLE
Fill handle doesn't change the row colour on range selection.

### ISSUE THREAD

**Issue by amanshu-kataria** [ag-grid/ag-grid#3934]
**I'm submitting a ...**
```
[x] bug report
```
**Reproducible Scenario**
[Plunker Example](https://plnkr.co/edit/5mQY9Zt94KiaWQDN)

1. Select a cell in age column.
2. Drag it using fill handle to rows with the other colour.

**RowClassRules:**
Blue if age > 23
Yellow if age <= 23

**Current behavior**

Fill handle doesn't change row colour when a cell is dragged vertically.
![Screenshot 2020-07-02 at 3 29 13 PM](https://user-images.githubusercontent.com/13014093/86354084-07292d00-bc86-11ea-9d52-495f4655a9bb.png)

**Expected behavior**

Fill handle should change class/colour(if applicable) when cell is dragged vertically if `rowClassRules` is applied.
![Screenshot 2020-07-02 at 5 07 42 PM](https://user-images.githubusercontent.com/13014093/86354391-99c9cc00-bc86-11ea-9a7e-9af6d4b13a49.png)

**Please tell us about your environment:**

OS: MacOS

* **ag-Grid version:**
ag-grid-angular: ^23.2.0
ag-grid-community: ^23.2.1
ag-grid-enterprise: ^23.2.1

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

* **Language:** [TypeScript 3.7.5]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
We're reproduced the issue you reported as a bug and we've added it to our backlog with the following reference:
AG-4375 RowClassRules are not refreshed when a cell is updated via the fill handle

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

Until this issue is addressed, please use cellClassRules instead of rowClassRules to achieve the same result. This approach is illustrated in the plunker below.
https://plnkr.co/edit/dZ2HRJ9BkfKCcJ4X

**Comment by gportela85** [comment]
fixed in the latest branch

**Comment by LouisMoore-agGrid** [comment]
Hello!

Thank you for the context you provided - this really helps us understand your requirements. 

We have added this to our backlog and we are tracking it with the following reference and description:

AG-4375 RowClassRules are not refreshed when a cell is updated via the fill handle

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

Until this is addressed, please use cellClassRules instead of rowClassRules to achieve the same result. This is illustrated in the plunker below.
https://plnkr.co/edit/dZ2HRJ9BkfKCcJ4X

I recommend checking the status of this item in our public product pipeline once a month. You'll be able to see when it's scheduled for implementation when it appears on the tab called NEXT RELEASE here:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
