### ISSUE TITLE
Header overlap over editable row.

### ISSUE THREAD

**Issue by chaitanya1248** [ag-grid/ag-grid#3948]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

When a new row is added dynamically to empty grid, the header overlaps new item added.

ag-grid-react

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
Header row overlaps first row in grid.

**Expected behavior**
Editing should be made fully visible.

**Please tell us about your environment:**
MacOS

* **ag-Grid version:** 
23.2.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

* **Language:** 
[React/JSX]

<img width="1099" alt="Screen Shot 2020-07-07 at 5 20 40 PM" src="https://user-images.githubusercontent.com/20464756/86850373-cc086e80-c076-11ea-87b0-1f236679a6ab.png">

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
