### ISSUE TITLE
XSS vulnerability in simple cellRenderer with valueFormatter

### ISSUE THREAD

**Issue by SumBeam** [ag-grid/ag-grid#3953]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

See this example: https://plnkr.co/edit/2yXmEokMvGriUCs9

Imagine that `createRowData` contains data from a server which accepts user input. By using cellRenderer with a simple function and valueFormatter together, you are able to target the [loadTemplate](https://github.com/ag-grid/ag-grid/blob/fe50182e5542b4616d2ef41a03a38836a83daeae/dist/lib/utils.js#L665) function which executes the script since it is using the innerHTML property. This could lead to XSS injection. This is only the case when you are returning a [string/number/boolean](https://github.com/ag-grid/ag-grid/blob/066683a1cd707906435b03178178522020bfa2a9/community-modules/core/src/ts/components/framework/agComponentUtils.ts#L54)

**Expected behavior**

No XSS vulnerability :). I've seen a previous issue (#1961) and they talked about using textContent instead of innerHTML

* **ag-Grid version:** 23.2.1

* **Browser:** Chrome, Safari, Firefox (on OSx), I did not test Windows

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

I have raised this with the dev team, we think is best to leave parsing out all the risk code on the client-side for this use case.

We would not make any changes on this area

I will keep this ticket open for a few more days if you would like to further discuss this though

Hope this makes sense

**Comment by SumBeam** [comment]
Hi,

thanks for your reply.

In the case that the dev team is not going to fix this, can you maybe add something to the documentation about this? I think it's good to inform the people about this risk.

It was a surprise to us and we discovered it during a security-test on our software. We fixed it by using the advanced cellRendered implementation, instead of the method I described above.

Thank you

**Comment by manojsubbarayalu** [comment]
Hi,
We are a licenced user, we are getting this issue when we are running our application against nexus. This is the blocker for us to release our application. When this could be resolved and published?

Thank you

**Comment by makinggoodsoftware** [comment]
Hi guys, 

Just checking up on here after a while, as mentioned above we are not sure how we could prevent these warnings and offer the ability to inject dynamic content as we do.

I would recommend, if you are a customer, reach to us via zendesk, in the meantime, I am going to close this as I can't see how we can make any progress.

Thanks for all the feedback

**Comment by burgalon** [comment]
@makinggoodsoftware The AgGrid docs specifically says that valueFormatter is not for HTML, hence the output should be escaped for html entities

https://www.ag-grid.com/javascript-data-grid/value-formatters/

```
A cell renderer allows you to put whatever HTML you want into a cell. This sounds like value formatters and a cell renderers have cross purposes, so you may be wondering, when do you use each one and not the other?

The answer is that value formatters are for text formatting and cell renderers are for when you want to include HTML markup and potentially functionality to the cell. So for example, if you want to put punctuation into a value, use a value formatter, but if you want to put buttons or HTML links use a cell renderer. It is possible to use a combination of both, in which case the result of the value formatter will be passed to the cell renderer.
```

This seems like a big vulnerability, which I'm not sure why is it not reported in npm audit and fixed by AgGrid.

**Comment by kiril-matev** [comment]
Hi @burgalon et al,

Thanks for following up on this and for using AG Grid.

I'd like to clarify the use of **default cell renderers** and **custom cell renderers** and how this relates to rendering HTML code as HTML content or a string.

Please open this sample:
https://plnkr.co/edit/8eNX2Smysu7IOu9x

Note:
1) There are two columns bound to the same data property
2) The data property value for the first row contains HTML code
3) The **custom cell renderer** column renders HTML content (producing the page alert), while the **default cell renderer** column display the same HTML content as a string (and doesn't display an alert).

**Discussion:**
When you're using the default cell renderer (i.e. not providing your own cellRenderer), the provided content is escaped. This is because the default cell renderer is used for text only, not HTML. This is why in the example below if you look at the **Default cell renderer** column, the HTML value in the top grid cell is rendered as a string - it is escaped for safe rendering inside the default cell renderer.

However, when you're providing a custom cell renderer the intention is to display HTML code. This is why when using a custom cell renderer the cell content isn't escaped. As you're using a custom cell renderer you're in full control of the content displayed, and this includes the need to escape content as needed.

The use of a valueFormatter is unrelated to whether the default of a custom cell renderer is used. This is why the use of a valueFormatter is unrelated to whether content gets escaped or not. 

You point out the documentation states:
https://www.ag-grid.com/javascript-data-grid/value-formatters/#value-formatter-vs-cell-renderer

Quoting from the section above:
The answer is that value formatters are for text formatting and cell renderers are for when you want to include HTML markup and potentially functionality to the cell. So for example, if you want to put punctuation into a value, use a value formatter, but if you want to put buttons or HTML links use a cell renderer. It is possible to use a combination of both, in which case the result of the value formatter will be passed to the cell renderer.

Please note the last sentence - "It is possible to use a combination of both, in which case the result of the value formatter will be passed to the cell renderer." This covers the case where a valueFormatter is used together with a custom cell renderer and this is a valid use case. The valueFormatter doesn't escape HTML content because if you're using a custom cell renderer your intention is to render HTML content. 

As you're in full control of the custom cell renderer and the content that gets passed to it, you need to escape it if you do not want any HTML content to be rendered. In that case your HTML code will render as a string, making this equivalent to a default cell renderer, defeating the purpose of using a custom cell renderer in the first place. This is why if you don't want to render HTML content, simply use the default cell renderer.

There would be a XSS vulnerability if the **default cell renderer** displayed HTML content without escaping it. However, in this case, only the **custom cell renderer** displays the alert message, which is expected behavior as it's supposed to display HTML content instead of escape it.

I hope this clarifies why this behavior isn't a XSS vulnerability and the rendering of HTML content in default and custom cell renderers.

Thank you for bringing this up - we appreciate your time!

**Comment by burgalon** [comment]
@kiril-matev this is experienced in ag-grid react - https://embed.plnkr.co/plunk/fbtYhl replace ColumnDefinition with
```              {
                  headerName: "Ag grid Testing Header 1 With Long text",
                  field: "value",
                   headerComponent: "CustomHeader",
                   valueFormatter: () => `><img src=x onerror=prompt(document.domain)>`
              },```

**Comment by burgalon** [comment]
I have a more precise reproduction of this - this happens when valueFormatter returns an array:
```
            valueFormatter: () => [`><img src='' onerror="alert()">`],
```

**Comment by kiril-matev** [comment]
Hi @burgalon,

Thanks for your response.

Please note that the example I included above using v26.2 doesn't have this issue - the default cellRenderer doesn't render the HTML content.

The sample you've sent which has this issue is using AG Grid v13.1.1, released on Sep 08, 2017, which over 4 years ago.

Please upgrade to newer versions of AG Grid to resolve issues and to ensure your application supports newer browser versions.

I updated your example to use AG Grid 14.0 (released Nov 02, 2017) and this issue is no longer present:
https://plnkr.co/edit/5DjjIjC6JZeQM49x

In general, when you find an issue, first try to reproduce it with the latest version of AG Grid. If the issue cannot be reproduced in the latest version of AG Grid, please upgrade to this version or to an earlier version which resolves the issue you're experiencing. This way you'll be able to address the issue more quickly.

Thanks again for your time!

**Comment by burgalon** [comment]
indeed it seems like this bug exists up to v25, and fixed in v26

**Comment by burgalon** [comment]
https://stackblitz.com/edit/ag-grid-react-hello-world-bkpx8e?file=package.json

**Comment by burgalon** [comment]
actually the bug exists in v26 as well

**Comment by burgalon** [comment]
2nd correction ;) v26 looks okay i guess

**Comment by kiril-matev** [comment]
Hi @burgalon,

I can confirm that this issue was resolved in v25.2 and remains fixed in the latest version of AG Grid.

As I mentioned before - in general, please try to reproduce any issues with the latest version of AG Grid. If the issue cannot be reproduced in the latest version of AG Grid, please upgrade to this version to resolve the issue you're experiencing. This way you'll be able to address issues more quickly.

I hope this discussion provides the necessary detail and confirms that this works as expected.

Thanks for looking into this and tracking this issue!

**Comment by burgalon** [comment]
this is a pretty major issue in very recent versions. Can you please report it to the npm audit service?

**Comment by mpontreau** [comment]
Hello,

This vulnerability seems to still exists in version 29 and 30 of ag-grid:
![image](https://github.com/ag-grid/ag-grid/assets/124345951/d1b02712-9e0f-4212-8563-e523f95c9165)

**Comment by AG-Zoheil** [comment]
Hi @mpontreau,

Please see this reply which already addresses this:

https://github.com/ag-grid/ag-grid/issues/3953#issuecomment-973112665.

Thank you.
