### ISSUE TITLE
Cell renderer unit tests are failing in vue after upgrade to version 23.2

### ISSUE THREAD

**Issue by jja-financial-com** [ag-grid/ag-grid#3954]
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
We are using ag-grid as part of our Vue project. Recently we upgraded from version 20.2 to 23.2 and from then onwards, the cell renderer unit tests are failing. We use jest for unit testing.
Upon analysis, it seems that the cell renderers are not being created and mounted in the test environment, and in its place, an empty string is being rendered. 

We created a sample application with a test as described in the documentation of ag-grid which can be found at repository [ag-grid-test](https://github.com/jijojames18/ag-grid-test). The `master` branch has version 23.2 and the only other branch `ag-grid-version-20.2` has ag-grid version 20.2. Switch between the branches and try running the unit test after executing `npm i`

**Current behavior**
The same test fails in the latest version even though the test and code are the same because the cell renderers are not being created and mounted in the test environment,

**Expected behavior**
The test should pass in all versions

**Please tell us about your environment:**
Node: v10.14.2
All other dependencies can be found at [package.json](https://github.com/jijojames18/ag-grid-test/blob/master/package.json)

* **ag-Grid version:** X.X.X
23.2.1

* **Browser:**
N.A

* **Language:** 
all

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
