### ISSUE TITLE
ag-grid-react turn off the static markup. "autoHeight" invalid

### ISSUE THREAD

**Issue by ydostyle** [ag-grid/ag-grid#3955]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- https://codesandbox.io/s/dank-butterfly-g0igi

Current behaviour.

I disable static markup.multiline text can't adaptive height and if open static markup..rolling too fast will static markup and react-component all displayed on the page.I do a background color in the demo, to show the rolling too fast in both content on the page. 

fix:
```
.ag-react-container > :not(:first-child) {
    display: none !important;
}
```

**Expected behavior**

turn off the static markup.autoHeight valid

**Please tell us about your environment:**

* **ag-Grid version:** 23.2.1

* **Browser:** chrome

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this issue.

We have added this as a bug to our backlog and we are tracking it with the following reference and description:
**AG-4485 Row AutoHeight is broken when using disableStaticMarkup=true**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

I recommend checking the status of this item in our public product pipeline once a month. You'll be able to see when it's scheduled for implementation when it appears on the tab called NEXT RELEASE here:
https://www.ag-grid.com/ag-grid-pipeline/

For more information on when can you expect your ticket to be fixed please check:
https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket-

Thanks again for bringing this up with us.
