### ISSUE TITLE
Printing second time, does not work for Safari.

### ISSUE THREAD

**Issue by Tomas-DB** [ag-grid/ag-grid#3968]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Default documentation plunker:
 https://www.ag-grid.com/javascript-grid-for-print/#example-for-print-complex

* On Safari, click the print button in plunker.
* In print dialog click "cancel"
* Click the print button in plunker again.
* Safari throws their default alert: "This website is trying to print. Do you want to print this webpage?"
* Click print in the alert.
* Table contents is not printable anymore.

**Please tell us about your environment:**
macOS Catalina

* **ag-Grid version:** X.X.X
23.2.0

* **Browser:**
Safari

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

Thank you for submitting this.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-4457 Printing in Safari after cancelling a print creates an invalid blanked file**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

I recommend checking the status of this item in our public product pipeline once a month. You'll be able to see when it's scheduled for implementation when it appears on the tab called NEXT RELEASE here:
https://www.ag-grid.com/ag-grid-pipeline/

For more information on when can you expect your ticket to be fixed please check:
https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket-

Thanks again for bringing this up with us.

Thank you.
