### ISSUE TITLE
rangeSelectionChanged event is emitted with "finished: true" when only one cell was selected and mouse button didn't up yet

### ISSUE THREAD

**Issue by AlexeyGalimov** [ag-grid/ag-grid#3970]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When first cell of range is selected, rangeSelectionChanged event emits before the mouse is up with finished: true. Because of this it's impossible to manage of ranges selection without this first "fake" emission. And build conditions based on finished property.

1. Mouse down
2. rangeSelectionChanged emits {... type: "rangeSelectionChanged", started: false, finished: true, …}
3. Mouse up

**Expected behavior**
1. Mouse down
2. Mouse up
3. rangeSelectionChanged emits {... type: "rangeSelectionChanged", started: false, finished: true, …}

**Please tell us about your environment:**
Win10, yarn, WebStorm

* **ag-Grid version:**
23.2.1

* **Browser:**
Google Chrome 83.0.4103.116

* **Language:**
TypeScript 3.8.3

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
