### ISSUE TITLE
keyCode' of null error when you hit enter key on the last row(enterMovesDownAfterEdit=true)

### ISSUE THREAD

**Issue by MVelez94** [ag-grid/ag-grid#3981]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
Parent of https://github.com/ag-grid/ag-grid/issues/3899

**Providing a Reproducible Scenario**
https://plnkr.co/edit/OhwQnO7b0mL1pZAZ

**Current behavior**
On enabling `enterMovesDownAfterEdit`, a console error appears when editing a cell in the last row.

**Expected behavior**
No errors.

I also want to help in the resolution of this issue if accepted.

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this issue.

We have added this to our backlog as a bug and we are tracking it with the following reference and description:
**AG-4494 [Regression] Editing a cell in the last row with enterMovesDownAfterEdit=true throws an exception**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

I recommend checking the status of this item in our public product pipeline once a month. You'll be able to see when it's scheduled for implementation when it appears on the tab called NEXT RELEASE here:
https://www.ag-grid.com/ag-grid-pipeline/

For more information on when can you expect your ticket to be fixed please check:
https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket-

Thanks again for bringing this up with us.

Regards,
Kiril

**Comment by belgiancoder** [comment]
This issue does not appear to be solved, OP already has a plunker so I'm not posting a new one.
