### ISSUE TITLE
REGRESSION 23.1.1 => 23.2.1: ag-header-cell not respecting maxWidth

### ISSUE THREAD

**Issue by jpike88** [ag-grid/ag-grid#3994]
- [x] bug report

Don't mark this as 'community managed' as leave it to rot please, it's a clear regression and would appreciate acknowledgement that you have at least entered this into zendesk.

ag-header-cell is no longer respecting maxWidth, it's just fitting to width of content.

ag-cell is however respecting maxWidth as normal.

Before:
<img width="380" alt="Screen Shot 2020-07-31 at 3 56 52 PM" src="https://user-images.githubusercontent.com/9585787/89013433-7443e700-d346-11ea-9ad1-bc3bef24ba0e.png">

After:
<img width="374" alt="Screen Shot 2020-07-31 at 3 57 03 PM" src="https://user-images.githubusercontent.com/9585787/89013442-7ad25e80-d346-11ea-958e-ad1a32c8ae4b.png">

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email.

We've looked into this and it seems to be working on our end.

https://plnkr.co/edit/yXXEopIbYvIHV0Vk

The athlete column's header and data cells cannot extend past the colDef's max width (100px).

could you please fork the example and reproduce your issue so that we can investigate further?


Regards,

Ahmed

**Comment by jpike88** [comment]
I've adjusted my styling to suit it
