### ISSUE TITLE
How do you set the license in ag-grid-react

### ISSUE THREAD

**Issue by bluefire2121** [ag-grid/ag-grid#3995]
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'

I'm an enterprise customer. I tried reaching out to the Zendesk help team and I thought I had the issue fixed, but it isn't. 
I've tried placing the LicenseManager in index.tsx (the bootstrap file). I've tried placing it in the actual component where I am deploying the grid. None of those things seem to work. What am I doing wrong?

The Zendesk team kept sending me back to this page which is not helpful: https://www.ag-grid.com/javascript-grid-set-license/#react

Here's what I tried:

import { AgGridReact } from 'ag-grid-react';
 import { AllModules } from '@ag-grid-enterprise/all-modules';
import 'ag-grid-community/dist/styles/ag-grid.css';
import 'ag-grid-community/dist/styles/ag-theme-balham.css';
import 'ag-grid-enterprise';
import  { LicenseManager } from '@ag-grid-enterprise/core';
LicenseManager.setLicenseKey("License Omitted for Github");

**Comment by marpy18** [comment]
I just do:

import {LicenseManager} from "ag-grid-enterprise";
LicenseManager.setLicenseKey("my-license-key");

**Comment by bluefire2121** [comment]
When I app the key to index.tsx there aren't any issues, but when I go to use an enterprise feature in the Ag-grid, I get the console warning. 

I place the license key in index.tsx.

import { AgGridReact } from 'ag-grid-react'; 
In a separate component file. 

I also
import 'ag-grid-enterprise';
In that component file.

No luck.

The license key I have has spaces in it. It's also an intranet app. Could either of those be the problem?

**Comment by LouisMoore-agGrid** [comment]
Hi,

Apologies for issues you've faced in zendesk. Please give us a ticket number so we can look into this.

You're seeing this issue because you're mixing two ways of referencing ag-grid and importing modules and packages.

Please follow the steps below to address this:
1. Remove the following line:
"import 'ag-grid-enterprise';" 
2. Replace "import { AgGridReact } from 'ag-grid-react';" with "import { AgGridReact } from '@ag-grid-community/react';"

Going forward, please submit a support ticket if you need further help as we prioritise questions in our support system over questions on github. This way as a paying customer you can get help faster.

**Comment by bluefire2121** [comment]
The ticket number was: 13268.

I'll continue to use the enterprise support going forward. 

Regards

**Comment by bluefire2121** [comment]
And the reason this is confusing is because the example shows the opposite of what is suggested here.

https://www.ag-grid.com/react-grid/

It says to use:
import { AgGridReact } from 'ag-grid-react';

**Comment by LiamDotPro** [comment]
Hey did you figure this out in the end?

**Comment by dssagar93** [comment]
> I just do:
> 
> import {LicenseManager} from "ag-grid-enterprise";
> LicenseManager.setLicenseKey("my-license-key");

Thanks. This worked.

**Comment by totszwai** [comment]
@dssagar93 where did you put those 2 lines? Anywhere within the app?
