### ISSUE TITLE
Tab key not working on custom floating filter input field

### ISSUE THREAD

**Issue by Ankita-G-Mudgal** [ag-grid/ag-grid#3997]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
We are using ag-grid as part of our react  project but all the components used are developed using web-components (polymer lit-elements). For filtering purpose we created a custom floating text filter and added event-listener for 'input' & 'keydown' event but the tabbing is not working on the filter input fields.

**Current behavior**
Tabbing not working on filter input fields 

**Expected behavior**
Tabbing should work properly on filter input fields (using tab key focus should be on next floating filter input field )

**Please tell us about your environment:**
Node : 12.18.2

* **ag-Grid version:** 23.2.1

* **Browser:**
NA

* **Language:** all

**Comment by LouisMoore-agGrid** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are

A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.

A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

Select the framework that is appropriate to you from the drop-down

Open it in plunker. (Use the button plunker in our example)

Add your changes so that the behaviour is reproduced

Save and Freeze the plunker(On the top left corner)

Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
