### ISSUE TITLE
Tooltip not visible for editable cells when opened with empty value.

### ISSUE THREAD

**Issue by santhoshda** [ag-grid/ag-grid#4003]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
Tooltip not visible for the cells that are empty on open and edited after open.

**Expected behavior**
Tooltip should be visible for the cells that are empty on initial load

**Please tell us about your environment:**
VSCode

* **ag-Grid version:** X.X.X
23.2.1

* **Browser:**
Chrome

* **Language:** [all]

* **Evidence:**
[Plunk](https://plnkr.co/plunk/wMJ2b7LXOEqaX1cZ)
Here goto the last row. it is empty. Edit the cell and hover over the cell, tooltip not visible.
If we resize the browser window and do a full scroll, then the tooltip is visible.
Note: usingbrowsertooltips works fine. But I dont want that.

**Comment by LouisMoore-agGrid** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are

A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.

A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

Select the framework that is appropriate to you from the drop-down

Open it in plunker. (Use the button plunker in our example)

Add your changes so that the behaviour is reproduced

Save and Freeze the plunker(On the top left corner)

Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by santhoshda** [comment]
I already added the plunk in the issue
https://plnkr.co/plunk/wMJ2b7LXOEqaX1cZ

**Comment by LouisMoore-agGrid** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by santhoshda** [comment]
Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request/bug in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG-4422

Custom tooltip doesn't disappear when pressing ENTER to finish editing the cell
