### ISSUE TITLE
agLargeTextCellEditor doesn't trigger onCellKeyDown or onCellKeyPress events

### ISSUE THREAD

**Issue by vdurante** [ag-grid/ag-grid#4004]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

When using agLargeTextCellEditor, the onCellKeyDown and onCellKeyPress events are not triggered.

Here is the [example](https://plnkr.co/edit/K4ZTGEqn8zuWtEEC). Just check dev console when editing Athlete column or another column

**Expected behavior**

When using agLargeTextCellEditor, the onCellKeyDown and onCellKeyPress should be triggered.

**Please tell us about your environment:**

* **ag-Grid version:** 23.2.1 Angular

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.52

* **Language:** TypeScript 3.9.6

**Comment by LouisMoore-agGrid** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello vdurante!

Thank you for the context you provided.

We've reproduced this as a bug.

We have added this to our backlog and we are tracking it with the following reference and description:
**AG-4518 [Events] cellKeyDown and cellKeyPress events don't fire when using agPopupTextCellEditor or agLargeTextCellEditor**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

I recommend checking the status of this item in our public product pipeline once a month. You'll be able to see when it's scheduled for implementation when it appears on the tab called NEXT RELEASE here:
https://www.ag-grid.com/ag-grid-pipeline/

For more information on when can you expect your ticket to be fixed please check:
https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket-

Thanks again for bringing this up with us.

**Comment by vdurante** [comment]
@kiril-matev @LouisMoore-agGrid thank you!

If anyone else faces this issue, I will leave this workaround code to help:

```ts
// I am using on angular

onCellEditingStarted: (e) => {
  const isLargeEditor = e?.colDef?.cellEditor === "agLargeTextCellEditor";

  if (!isLargeEditor) {
    return;
  }
  
  // get input element
  let eInput = (e as any).api.rowRenderer.rowCompsByIndex[e.rowIndex]
    .cellComps[e.colDef.field].cellEditor.cellEditor.eTextArea.eInput;

  var textArea = eInput as HTMLTextAreaElement;

  // bind any event
  textArea.addEventListener("keypress", (ev: KeyboardEvent) => {
    // event handling
  });
},
```
