### ISSUE TITLE
groupIncludeFooter (and groupIncludeTotalFooter) not working with RowModelType of serverSide

### ISSUE THREAD

**Issue by BarCatFigaro** [ag-grid/ag-grid#4009]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
groupIncludeFooter and groupIncludeTotalFooter does not properly work when we are using a server-side model (as mentioned in the following stack overflow post: https://stackoverflow.com/questions/63261665/aggrid-groupincludefooter-not-working-with-rowmodeltype-of-serverside). There is no aggregation footer shown.

See https://plnkr.co/edit/3sZUX4tniRwRHN1r

**Expected behavior**
The aggregation footer should be shown for groupIncludeFooter and groupIncludeTotalFooter, similar to when using the client-side model shown here: https://plnkr.co/edit/en9fRQKx5YnPxFEq

* **ag-Grid version:** 23.2.1

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36

* **Language:** [all]

**Comment by LouisMoore-agGrid** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request/bug in our backlog.

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:
AG-687 | [SSRM] Add support for group footers and group total footer

**Comment by kiril-matev** [comment]
Hello!

AG Grid 30 adds support for group footer rows when using server-side row model as part of AG-687.
https://www.ag-grid.com/javascript-data-grid/server-side-model-grouping/#row-group-footers

Adding support for group total footer when using server-side row model is separated in a new requirement:
**AG-8439 [SSRM] Add support for group total footer when using server-side row model**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
