### ISSUE TITLE
Filter 'in range' does not work with numbers

### ISSUE THREAD

**Issue by CherifKods** [ag-grid/ag-grid#4015]
**The scenario:**

Open : https://www.ag-grid.com/example.php
Choose a column with numbers: example : May Column
Click on the filter icon that exists besides the header name column
Choose 'In range' from the filter list
Choose a the range and fill the two inputs : from...to example : from 30 to 60

**Current behavior**
Following the scenario above will not filter the list and we will always have an empty list.

**Expected behavior**
Following the scenario above, the grid will display minimum 31 rows that have cells values between 30 and 60 in the May column.

**Example :** 
https://www.ag-grid.com/example.php
The current behavior is reproduced and exists in the ag-grid demo.

**Environment:**

* **Operating system :** Windows 10,
* **IDE:** Visual studio code,
* **Package manager:** npm 6.9.0

* **ag-Grid version:**
V23.2.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36

* **Language:**
**Typescript**: 3.5.3

**Comment by LouisMoore-agGrid** [comment]
Hi,

In the demo link you've provided this seems to work as expected. The May column doesn't contain any data with values between 30 and 60, changing the range to between 30 and 10000 shows that it is working correctly.

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are

A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.

A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

Select the framework that is appropriate to you from the drop-down

Open it in plunker. (Use the button plunker in our example)

Add your changes so that the behaviour is reproduced

Save and Freeze the plunker(On the top left corner)

Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
