### ISSUE TITLE
aggrid is breaking after angular 10 upgrade and unable to compile 

### ISSUE THREAD

**Issue by kmanikandanmca2008** [ag-grid/ag-grid#4020]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

YES, We are customer of Aggrid.

**Current behavior**
 Getting error on ng build cmd .

![image](https://user-images.githubusercontent.com/16201678/90119166-db19c500-dd76-11ea-84a7-7d8c2933b774.png)

**Expected behavior**
It should just work fine since the version 20.2.0 is compatible with angular9+.

* **ag-Grid version:** 20.2.0

**Comment by kmanikandanmca2008** [comment]
We have upgraded to latest version with enterprise so it is working fine. But i dont know why i still get huge lib size in my angular10 project.
1.5MB & 1.7 MB for both enterprise & community respectively.
![image](https://user-images.githubusercontent.com/16201678/90472453-2f89bf80-e13e-11ea-80e3-d988dc02603b.png)

**Comment by LouisMoore-agGrid** [comment]
Hello!

We agree with you that the size of packages in ag-Grid has increased to accommodate improved functionality. We have solved this challenge by introducing a modular approach to loading ag-Grid to allow you to minimize the bundle size. 

This modular approach was introduced in ag-grid v22, and I would recommend using that instead of the (old) packages approach you're using to load ag-grid.

Please see a full explanation on how to use the modules approach here:
https://www.ag-grid.com/javascript-grid-packages-modules/

If you need any further help please log onto our support system and submit a support ticket.
