### ISSUE TITLE
Text truncation inside the cell does not work properly in IE11 browser

### ISSUE THREAD

**Issue by pbeleckis** [ag-grid/ag-grid#4030]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Using a slightly modified plunker from ag-grid documentation (https://www.ag-grid.com/javascript-grid-row-height/#auto-row-height)
Link to modified plunker: https://plnkr.co/edit/aBDSVF4nRzyTvAN0

**Current behavior**
Long words are not truncated properly while column is set to **autoHeight=true*. No ellipsis is visible in IE11 browser
![image](https://user-images.githubusercontent.com/50491863/90613857-9b3d5c80-e212-11ea-93a4-59404d863f6b.png)

**Expected behavior**
Long words should be truncated properly and ellipsis should be visible to make the behavior consistent throughout all browsers.
Screenshot taken in Chrome browser:
![image](https://user-images.githubusercontent.com/50491863/90614097-e3f51580-e212-11ea-845a-852543b38497.png)

**Please tell us about your environment:**
Windows 10

* **ag-Grid version:** 23.2.0

* **Browser:**
IE 11 Version 11.778.18362.0

* **Language:** React 16.13.1

**Comment by LouisMoore-agGrid** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this issue.

We have added this to our backlog and we are tracking it with the following reference and description:
**AG-4574 No ellipsis shown for long text value in Internet Explorer 11**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can check whether this item is selected for implementation by taking a look at the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

I would recommend signing up for automatic release notifications using the instructions here. Then, following a release, check whether the item was implemented by looking for it in the changelog page.

For more information on when can you expect your ticket to be fixed please check:
https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket-

Thanks again for bringing this up with us.
