### ISSUE TITLE
Grid freezes due to infinite loop when scrolling and master-detail row is open

### ISSUE THREAD

**Issue by maciekgajewski** [ag-grid/ag-grid#4036]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

A grid with 500+ rows, using masterDetail=true.
One of the rows has the detail pane open. When scrolling trough the grid, and the open row is about to get into view, the broser freezes.

It gets stuck in an infinite loop in ` ClientSideRowModel.prototype.getRowIndexAtPixel`

bottomPointer = topPointer+1, but the condition  `if (this.isRowInPixel(currentRowNode, pixelToMatch))` fails.
The loop never exists.

**Expected behavior**
The grid does not freeze.

**Please tell us about your environment:**
Ubuntu, React.js

* **ag-Grid version:** 23.2.1

* **Browser:**
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36"

* **Language:**  ES6/7
![Screenshot_2020-08-21_10-57-00](https://user-images.githubusercontent.com/1903794/90872538-15015180-e39d-11ea-8816-6730201150ba.png)

**Comment by LouisMoore-agGrid** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are

A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.

A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

Select the framework that is appropriate to you from the drop-down

Open it in plunker. (Use the button plunker in our example)

Add your changes so that the behaviour is reproduced

Save and Freeze the plunker(On the top left corner)

Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
