### ISSUE TITLE
getContextMenuItems callback is never updated/goes stale (React)

### ISSUE THREAD

**Issue by fgblomqvist** [ag-grid/ag-grid#4041]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
If you pass a callback function to `getContextMenuItems`, and then later update that function (e.g. on re-render, to prevent closure from going stale), AgGridReact does not update its reference. It will keep calling the original function that was passed in (if any).

**Expected behavior**
AgGridReact should be _reactive_ and always call the function that is in the prop rather than keeping some internal outdated reference. By inspecting the component in Chrome, you can see that AgGridReact receives the new function (as it should), but it's clearly not executing it.

* **ag-Grid version:** 23.2.1

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

* **Language:** TypeScript 3.9

**Comment by LouisMoore-agGrid** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are

A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.

A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

Select the framework that is appropriate to you from the drop-down

Open it in plunker. (Use the button plunker in our example)

Add your changes so that the behaviour is reproduced

Save and Freeze the plunker(On the top left corner)

Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by fgblomqvist** [comment]
@makinggoodsoftware This should be revisited now that you handle these tickets more properly. This same issue plagues other callbacks/similar features, such as `setServerSideDatasource`. That one should be a prop instead and be updated whenever the prop updates (like in all things React).

**Comment by vasin-dimitry** [comment]
I have same issue. Any solution?

**Comment by fgblomqvist** [comment]
The only workaround I found was to only access refs (e.g. useRef) inside any functions passed-in to the AgGrid component. That way you can update their value without requiring the function to be re-declared.

However, I do hope AgGrid recognizes this as an actual issue sooner or later. I'm very tempted to just write my own React component wrapper for the grid since the one they provide is so subpar and they don't care about feedback.

**Comment by aviram83** [comment]
it's also happen in isRowMaster.
any function is copied so it's isolated, instead they should pass a reference

**Comment by fgblomqvist** [comment]
@seanlandsman @gportela85

**Comment by aviram83** [comment]
There is a workaround I have found.
My functions in the `getContextMenuItems` are referring to function from the React's Context API
so it's possible to define in the [AG Grid context ](https://www.ag-grid.com/documentation/javascript/context/) a reference to application's context (using useContext) and using the callback params, which contain the updated context.

**Comment by vasin-dimitry** [comment]
> There is a workaround I have found.
> 
> My functions in the `getContextMenuItems` are referring to function from the React's Context API
> 
> so it's possible to define in the [AG Grid context ](https://www.ag-grid.com/documentation/javascript/context/) a reference to application's context (using useContext) and using the callback params, which contain the updated context.

I achieved quite same result with reducer. But the problem is that I also had to place component state into the reducer instead of using usestate in the place where it has to be (the component). It's a big issue, that they don't update functions passed to grid on every render. The state is staled.
