### ISSUE TITLE
DateFilter inRangeInclusive should include end date time

### ISSUE THREAD

**Issue by jfcere** [ag-grid/ag-grid#4046]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Will do if I have to but the problem is pretty straight forward.

**Current behavior**

Currently, when using `agDateColumnFilter` with `inRange` filterOption and `inRangeInclusive: true` the end date returned in the `dateTo` property of the `FilterModel` have the time set to `00:00:00` which make the last end date exclusive although the option `inRangeInclusive` is set to `true`.

For example selecting a range from `2020-01-01` to `2020-01-31` with `inRangeInclusive: true` currently return the following values in `FilterModel`:

```javascript
{
  dateFrom: "2020-01-01 00:00:00",
  dateTo: "2020-01-31 00:00:00",
  filterType: "date",
  type: "inRange"
}
```

**Expected behavior**

When using `agDateColumnFilter` with `inRange` filterOption and `inRangeInclusive: true` the end date returned in the `dateTo` property of the `FilterModel` should have the time set to `23:59:59` since it's inclusive.

For example selecting a range from `2020-01-01` to `2020-01-31` with `inRangeInclusive: true` should return the following values in `FilterModel`:

```javascript
{
  dateFrom: "2020-01-01 00:00:00",
  dateTo: "2020-01-31 23:59:59",
  filterType: "date",
  type: "inRange"
}
```

**Additional Information**

I'd like to add that the problem is not so much the fact that `inRangeInclusive: true` doesn't include the last selected date as a _whole_ with the time (since I can intercept it and manipulate that dates) but that when you do select a range of date the time is shown in the filter input "with" the time and it is misleading!

![image](https://user-images.githubusercontent.com/6987084/91555264-ab35fa00-e8fe-11ea-9fad-1f32d1ec5bbe.png)

Is there a way to format the result of the range selected to be displayed in the filter input to, let say, remove the `00:00:00` time annotation to display something like `2020-01-01 - 2020-01-31`?

**Please tell us about your environment:**

Operating system: Windows 10 Professional 64 bit
Package manager: NPM

**ag-Grid version:**

@ag-grid-community/angular: 23.2.1
@ag-grid-enterprise/all-modules: 23.2.

**Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36

**Language:**

TypeScript 3.8.3

**Comment by LouisMoore-agGrid** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are

A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.

A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

Select the framework that is appropriate to you from the drop-down

Open it in plunker. (Use the button plunker in our example)

Add your changes so that the behaviour is reproduced

Save and Freeze the plunker(On the top left corner)

Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by zeroregard** [comment]
This is actually still a problem, 3 years later. Do you really need a Plunkr example? I can provide you one if it's necessary.

**Comment by zoheil-ag** [comment]
Hi @zeroregard,

Thanks for getting in touch. Naturally, there've been a lot of changes to the grid over the last 3 years including to our filters, e.g. I'm not sure some of the remarks about time display are still 100% accurate.

If you still have something that is not working right or missing, can you please open a new Github issue with a reproducible scenario (e.g. plunker) of the current AG-Grid version and we'd be more than happy to take a look?

Thank you for your understanding.

Kind regards,
Zoheil
