### ISSUE TITLE
Ag-Grid does not show/hide columns when there is no row data

### ISSUE THREAD

**Issue by nbmsv2** [ag-grid/ag-grid#4050]
**Version:**
"@ag-grid-community/angular": "^23.2.1",
"@ag-grid-enterprise/all-modules": "^23.2.1",

**Expected behaviour:** invisibleColumn should not be visible.

**What happenes:** invisibleColumn stays visible in the grid. In the "Columns" view, invisibleColumn is set to be hidden. Toggling the view of the column or other additional columns from the "Columns" view fixes the issue. Calling autoSizeAllColumns() also fixes the issue.

![image](https://user-images.githubusercontent.com/69467815/91839529-7f44ac80-ec4f-11ea-87a2-f6b7f0506bef.png)

```
import { Component } from '@angular/core';
import { GridOptions } from '@ag-grid-enterprise/all-modules';

@Component({
  selector: 'app-positions-component',
  template: '<style>:host { display: block; width: 100%; height: 100%; }</style><ag-grid-angular class="ag-theme-balham positions-grid"  [columnDefs]="columnDefs" [rowData]="rowData"  [gridOptions]="gridOptions" style="width:100%;height: 100%;"></ag-grid-angular>'
})
export class PositionsComponent {
  public gridOptions: GridOptions;
  columnDefs = [ { field: 'invisibleColumn' } ];
  rowData = [];

  constructor() {
    this.gridOptions = {
      onGridReady: (params: any) => { this.gridReady(params); },
      sideBar: { toolPanels: ['columns']},
      rowData: this.rowData,
    };
  }

  gridReady(params: any) {
    this.gridOptions.columnApi.getAllColumns().forEach(col => {
      col.setVisible(false);
    });

    //// janky fix to make AgGrid redraw columns. For some reason it doesn't rerender while no rows are shown..
    //this.gridOptions.columnApi.autoSizeAllColumns();
    //// we have to do this twice, as the first one does not auto size hidden columns that will appear after autoSizeAllColumns run..
    //this.gridOptions.columnApi.autoSizeAllColumns();
  }
}
```

**Comment by LouisMoore-agGrid** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are

A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.

A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

Select the framework that is appropriate to you from the drop-down

Open it in plunker. (Use the button plunker in our example)

Add your changes so that the behaviour is reproduced

Save and Freeze the plunker(On the top left corner)

Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
