### ISSUE TITLE
When searching "select all" only affects visible filter options

### ISSUE THREAD

**Issue by MikeBombardi** [ag-grid/ag-grid#4051]
Bug Report

Current behavior
On https://www.ag-grid.com/example.php

open the Set Filter on the Country column
type 'Ge' into the search field
Uncheck Select All
Only Argentina and Germany are unselected (the currently visible ones). All other items are still selected.
Expected behavior
I expect all items to be unselected.

Attempted to use the solution from issue #1559 
Adding the parameter (selectAllOnMiniFilter : false) as lindicated. This did not trigger the expected behavior

This behavior worked previously as expected in version 21.0.1 without the need for the added parameter, rolled back from 23.2.0 to verify.

ag-Grid version:
v23.2.0 on https://www.ag-grid.com/example.php

**Comment by kiril-matev** [comment]
Hi Mike,

Thank you for bringing this up.

Please open our changelog and search for 'selectAllOnMiniFilter':
https://www.ag-grid.com/ag-grid-changelog/

You'll note that the behavior implemented by this property was made default behavior in v22:
**AG-3383 SetFilter: Remove selectAllOnMiniFilter and have it as default behaviour** 
Property selectAllOnMiniFilter no longer used, its the default behaviour for Set Filter.

This change was made in order to make the SELECT ALL checkbox in the set-filter context-aware (applying only to selected items in the set filter), as it's shown in the popup appearing alongside other set filter items.

Users work with the set filter in two ways:
(1) moving from a larger dataset to a smaller one (filtering specifically for the items they need), OR
(2) moving from an empty dataset (where nothing is selected and the grid is empty) to a dataset containing the records they need.

If your users need to de-select all items (not just the ones matching the mini-filter) using the behavior you described in v21, it sounds like they need use case (2) as described above. We support this use case with a new property called **defaultToNothingSelected**, which allows you to start with all the set filter options de-selected the first time you open the filter, so you can add the selected items to include in the result set. You can use this process multiple times allowing you to create a union of different sets based on different filter conditions.

Please see this illustrated in the section Default State section:
https://www.ag-grid.com/javascript-grid-filter-set-filter-list/#default-state

This is why I would recommend if you'd like to cater to users using use case (2), please use this property and implement the behavior as shown in the documentation section above.

Thank you.
