### ISSUE TITLE
Drag column group bug

### ISSUE THREAD

**Issue by peakandyuri** [ag-grid/ag-grid#4053]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
Use translation software to describe the problem. There may be grammatical or lexical errors.

GIF operation from the [ag-grid website demo](https://www.ag-grid.com/example.php)
![GIF](https://user-images.githubusercontent.com/26075324/91941501-e768c080-ed2b-11ea-85cc-9d5f8545ecfd.gif)
First lock the columns that are outside the visible area, then drag the column group
**Current behavior**
Many columns disappear

* **Browser:**
chrome 85

**Comment by LouisMoore-agGrid** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this.

We have reproduced this behavior as a bug.

We have added this to our backlog and we are tracking it with the following reference and description:
**AG-4566 Pinning a column wider than the grid makes unpinned columns inaccessible**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can check whether this item is selected for implementation by taking a look at the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/


I would recommend signing up for automatic release notifications. Then, following a release, check whether the item was implemented by looking for it in the changelog page.
https://www.ag-grid.com/ag-grid-changelog/

For more information on when can you expect your ticket to be fixed please check:
https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket-

Thanks again for bringing this up with us.

**Comment by kiril-matev** [comment]
Hello!

I just wanted to follow up on your earlier request with us.

We are reorganizing our product backlog and have consolidated this requirement under a different development item. 

Going forward, the functionality you requested in this ticket will be tracked by:
**AG-3915 [Column Pinning] Allow horizontal scrolling of pinned column area if pinned column area wider than the viewport**

Please use this new reference to look up the status of this item in our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Please let me know if you have any questions.
