### ISSUE TITLE
onAnimationQueueEmpty being called prematurely

### ISSUE THREAD

**Issue by carlos-duetto** [ag-grid/ag-grid#4058]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
When rendering a table with multiple custom cell renderers onAnimationQueueEmpty is called before all cells are actually rendered. I can verify this because we have a spinner that hides once animationQueueEmpty is called and I can see some cells still being painted.

**Expected behavior**
onAnimationQueueEmpty should be called once all cells have finished rendering

**Please tell us about your environment:**
macOS sierra 10.13.3, Windows 10 VMs 

* **ag-Grid version:** X.X.X
ag-grid-react 23.0.0
ag-grid-community 23.0.0

* **Browser:**
FF, Chrome, IE11 and IE12 (VMs)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6 with React JSX

**Comment by LouisMoore-agGrid** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are

A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.

A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

Select the framework that is appropriate to you from the drop-down

Open it in plunker. (Use the button plunker in our example)

Add your changes so that the behaviour is reproduced

Save and Freeze the plunker(On the top left corner)

Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
