### ISSUE TITLE
Returning NaN from getRowHeight causes an infinite loop (again)

### ISSUE THREAD

**Issue by waterfoul** [ag-grid/ag-grid#4062]
I'm submitting a ... (check one with "x")

[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
Customers of ag-Grid

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

Requesting Community Support

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

Providing a Reproducible Scenario
Create a function which returns NaN / Not A Number and pass it into the getRowHeight property of the AgGrid React component

I'm not sure why #4047 got closed without any real investigation. The instructions above is more than adequate to reproduce it. I cannot make a plunkr because the moment you add getRowHeight={() => NaN} to the react component in the plunkr the browser freezes

Current behavior
The browser enters an infinite loop

Expected behavior
Not entirely sure, An error would be acceptable but it shouldn't infinite loop

The issue is caused by the ClientSideRowModel.prototype.getRowIndexAtPixel method. When the row height is set to NaN the exit condition for the while true loop (this.isRowInPixel(currentRowNode, pixelToMatch)) is always false, leading to a pegged cpu and unresponsive tab

Please tell us about your environment:
Linux, Yarn, Create React App

ag-Grid version: 23.0.2

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36

Language: TypeScript 3.9.7

**Comment by waterfoul** [comment]
@LouisMoore-agGrid Please actually do a cursory investigation this time

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this.

We have reproduced this issue as a bug.

We have added this to our backlog and we are tracking it with the following reference and description:
**AG-4658 When getRowHeight returns NaN, the page freezes**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

I would recommend signing up for automatic release notifications for ag-Grid. Then, following a release, check whether the item was implemented by looking for it in the changelog page.

Thanks again for bringing this up with us.

Regards,
