### ISSUE TITLE
Multiple Selection with infinite scroll not working when shift clicking on a checkbox

### ISSUE THREAD

**Issue by jason2211** [ag-grid/ag-grid#4096]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Requesting Community Support**

This only happens on the infinite scroll with multple selection enabled, and a checkbox column.  After the initial load (before any selection is made) if you hold shift and click on a checkbox it will show the box as checked but will not included the row in the getSelectedRows api call.  

https://plnkr.co/edit/5VyVHyRR2Fp3HfrN

This is a little difficult to explain in words so I created the below video showing the functionality.

https://1drv.ms/v/s!AtzVFC3e7388mJwXiRpwP_gIu708zA?e=NQhkLC

**Current behavior**
UI shows the checkbox selected but not the row and API does not include row in selected items.

**Expected behavior**
Whenever the checkbox is checked it should have the associated row selected.

**Please tell us about your environment:**
Tested using infinite scroll example plunker modified to include checkbox and multple selection

* **ag-Grid version:** 24.0.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

* **Language:** Angular / TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello Jason!

Thank you for reporting this.

We've reproduced this issue as a bug.

We have added this to our backlog and we are tracking it with the following reference and description:
**AG-4656 [Row Selection] Infinite row model doesn't allow to select multiple rows when pressing SHIFT + clicking rows**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

I would recommend signing up for automatic release notifications for ag-Grid. Then, following a release, check whether the item was implemented by looking for it in the changelog page.

Thanks again for bringing this up with us.
