### ISSUE TITLE
Not able to access button inside Ag-grid cell via Keyboard.

### ISSUE THREAD

**Issue by amashar** [ag-grid/ag-grid#4114]
I have an action button inside one cell in my ag-grid.

while accessing it via keyboard with the tab key, it does focuses the cell, but doesn't focus the button, hence I can't trigger the button action function.

**Comment by pbeleckis** [comment]
You need to handle focus by yourself.
Take a look at **davis4acca** [reply](https://github.com/ag-grid/ag-grid/issues/3777)

**Comment by Romko775** [comment]
@pbeleckis can you provide an example? It is easy to say that, but no example provided here or at stack

**Comment by pbeleckis** [comment]
> @pbeleckis can you provide an example? It is easy to say that, but no example provided here or at stack

Unfortunately have no example for you. Had no need to handle focus of other components inside the ag-grid cell.

**Comment by bswan0002** [comment]
For anyone who lands here as frustrated as I did earlier today, here's a solution I developed which doesn't require focus management overhauls and which I believe satisfies a11y requirements with good UX when using keyboard navigation.

Example shown is for ag-grid-react where TableLink is a custom cellRenderer component:

```tsx
import { useEffect } from "react"
import { ICellRendererParams } from "@ag-grid-community/core"
import { Link, useNavigate } from "react-router-dom"

type Props = { id: string; cellParams: ICellRendererParams }

export const TableLink = ({ id, cellParams }: Props) => {
  const navigate = useNavigate()

  const keyboardNavigate = (event: KeyboardEvent) => {
    if (event.code === "Enter") navigate(`./${id}`)
  }

  const linkId = `link-${id}`

  useEffect(() => {
    cellParams.eGridCell.setAttribute("aria-activedescendant", linkId)
    cellParams.eGridCell.addEventListener("keydown", keyboardNavigate)

    return () => {
      cellParams.eGridCell.removeEventListener("keydown", keyboardNavigate)
    }
  }, [])

  return (
    <Link aria-label={`user ${id} details`} id={linkId} to={`./${id}`}>
      {id}
    </Link>
  )
}
```

Setting [aria-activedescendant](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-activedescendant) on the parent grid cell to reference the rendered link id causes screen reader to correctly read the aria-label and announce the element as a link (tested on MacOS VoiceOver), even though it's the normal AG Grid keyboard focus on the cell. Then I simply add eventListener on the cell as well so that hitting enter is the same behavior as if the focus was on the link itself.

**Comment by chriswilty** [comment]
> Setting [aria-activedescendant](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-activedescendant) on the parent grid cell to reference the rendered link id causes screen reader to correctly read the aria-label and announce the element as a link (tested on MacOS VoiceOver), even though it's the normal AG Grid keyboard focus on the cell. Then I simply add eventListener on the cell as well so that hitting enter is the same behavior as if the focus was on the link itself.

While this seems to work with NVDA, it's not a given that screenreaders will do the correct thing, because `aria-activedescendent` is valid for grid role but not gridcell role. Additionally, I found NVDA by default enters browse mode, which swallows arrow key events such that the focus indicator remains stuck on the first cell (even though focus itself does move). I needed to explicitly enter focus mode (modifier-key + spacebar) to _see_ the focus indicator actually follow focus, however, that makes the announcement a lot more verbose as it announces the full location of the cell in the grid as well as announcing the link. Still, a lot better than AgGrid gives us out of the box 🏆

**Comment by bswan0002** [comment]
> While this seems to work with NVDA, it's not a given that screenreaders will do the correct thing, because `aria-activedescendent` is valid for grid role but not gridcell role.

Ack, good call out. Hopefully someone can chime in with a more semantically correct solution.

**Comment by SyntaxColoring** [comment]
Riffing on @bswan0002's solution, is something like this any better? Basically, any time the cell container `<div>` is focused, forcibly move focus to the inner `<Link>` (or button, or whatever you have) instead.

```typescript
import { type CustomCellRendererProps } from "ag-grid-react";
import { useEffect, useRef } from "react";
import { Link } from "react-router-dom";

// Ideally add your TData/TValue/TContext here.
interface Props extends CustomCellRendererProps {
  id: string;
}

export function ComparisonCellRenderer(props: Props): JSX.Element {
  const { id, eGridCell } = props;

  const innerElementRef = useRef<HTMLAnchorElement>(null);

  useEffect(() => {
    const handleFocus = (event: FocusEvent) => {
      if (event.target === eGridCell) {
        innerElementRef.current?.focus();
      }
    };

    eGridCell.addEventListener("focus", handleFocus);
    return () => {
      eGridCell.removeEventListener("focus", handleFocus);
    };
  }, [eGridCell]);

  return (
    <Link ref={innerElementRef} aria-label={`user ${id} details`} id={linkId} to={`./${id}`}>
      {id}
    </Link>
  );
}
```

This feels like an impolite thing to do to screen readers, but maybe we're at the point where it's the lesser evil.

-----

>  Additionally, I found NVDA by default enters browse mode, which swallows arrow key events such that the focus indicator remains stuck on the first cell (even though focus itself does move). I needed to explicitly enter focus mode (modifier-key + spacebar) to see the focus indicator actually follow focus

I think I'm also seeing this. I'm not sure whether it's expected for NVDA to enter browse mode, but given that it *does* enter browse mode, don't we expect to see that "stuck" focus indicator? The focus indicator stays where the browser focus is, on the interactable element, while the browse mode cursor goes off to wherever. (My understanding from https://www.accessibility-developer-guide.com/knowledge/screen-readers/desktop/browse-focus-modes/.)
