### ISSUE TITLE
Column sort blocked after pinning or unpinning it by drag

### ISSUE THREAD

**Issue by Romko775** [ag-grid/ag-grid#4135]
If you pin column by dragging it to 'left' section and try to sort you will see that sorting is blocked and header title has click box on it

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down- Open it in plunker. (Use the button plunker in our example)- Add your changes so that the behaviour is reproduced- Save and Freeze the plunker(On the top left corner)- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is flagged with waiting-for-repro.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by Romko775** [comment]
I`v investigated and found that when you remove divider from last column by styles it make lot of issues, for example

```
.ag-theme-balham .ag-header-row .ag-header-cell:last-child {
  &:after {
    width: 0;
  }

  &:focus:after {
    width: calc(100% - 8px);
    pointer-events: none;
    background-color: transparent;
  }
}
```
so I`ve added `pointer-events: none;` to fix this
