### ISSUE TITLE
Infinite scroll CTRL+END / CTRL+HOME 

### ISSUE THREAD

**Issue by Romanow88** [ag-grid/ag-grid#4139]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Plunkr: https://plnkr.co/edit/EeDRAZ8LKoPCklUn

**Reproducible Scenario**
Use infinite scroll / server side data ;
Set the the result count;
Select first row;

**Current behavior**
Hit CTRL + END (goes to last result);
Hit CTRL + HOME !(does nothing)!;

**Expected behavior**
Hit CTRL + END (goes to last result);
Hit CTRL + HOME should navigate to the first result (as it does for client data).

**Please tell us about your environment:**
Windows 10, IDEA 2020.2, NPM, Tomcat 8

* **ag-Grid version:** X.X.X
24.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"

* **Language:**
TypeScript 3.8.3

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by LouisMoore-agGrid** [comment]
Hi,

We've had a look at your example but haven't been able to reproduce the issue on our end. This gif shows the behaviour we saw after following the steps provided:
![home key + infinite row model inv](https://user-images.githubusercontent.com/56586582/96704110-94a2a100-138b-11eb-8f06-6b93e58d8020.gif)
As you can see, this seems to work as expected on our end. Note that this issue is getting closed, but you are welcome to create a new issue if you can provide us with a reproducible scenario.

Thanks

**Comment by Romanow88** [comment]
@LouisMoore-agGrid hey, thanks for checking this! 

I have made a recording showing this in the linked plunkr. Please note the recorded keypresses in the gif.

Hope this helps!

https://drive.google.com/file/d/1-XPisKp9JLTWQ6GeO5-XmY41fta4J5QQ/view?usp=sharing
