### ISSUE TITLE
Memory leak when page at background

### ISSUE THREAD

**Issue by elantion** [ag-grid/ag-grid#4141]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
When user switch current page to background, ag-grid will keep executing `AnimationFrameService.prototype.cancelTask`
function. This will cause `cancelledTasks` variable going bigger and bigger. Function `AnimationFrameService.prototype.executeFrame` should used for clearing `cancelledTasks`. But `AnimationFrameService.prototype.schedule` skip this execution when `this.useAnimationFrame` is false.
So, this logic will sure cause memory leak.

**Current behavior**

Memory leak

**Expected behavior**

Not have memory leak

**Please tell us about your environment:**

Not relevant

* **ag-Grid version:** X.X.X

23.2.1

* **Browser:**

Not relevant

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Not relevant

**Comment by elantion** [comment]
If someone want to skip this issue, you can set `suppressAnimationFrame: true` to temporary ignore this problem.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is flagged with waiting-for-repro.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by elantion** [comment]
Sorry, for security reson, I can't visit plunkr in my company. You can easily reproduct this problem with default options. And of course, you can close this issuse that is not satisfy your post rule.

**Comment by makinggoodsoftware** [comment]
Hi,

Alternatively, you could let us know if we can reproduce this in one of our examples..


https://ag-grid.com/documentation-main/documentation.php 


Would this help?

**Comment by makinggoodsoftware** [comment]
Hi,

We are going to close the issue, but by all means, if you find a reproducible scenario, feel free to reopen and we will investigate

Thanks

**Comment by mainfraame** [comment]
@makinggoodsoftware its pretty trivial. If you have data fetching in the background which sets rowData, your grid builds up RAFs (request animation frames) that all get fired once the tab becomes visible/active again. I experienced this bug in my code and had to add disabling logic for auto fetching data when a tab is in the background.
