### ISSUE TITLE
[Bug 24.1.0] Tool Panel Style Breaks on Columns

### ISSUE THREAD

**Issue by mizaoyu** [ag-grid/ag-grid#4151]
https://github.com/ag-grid/ag-grid/blob/3ed885a9cde6742d5c2469093f02b424d9c2bb05/community-modules/core/dist/styles/ag-grid.css#L986

Is this new line in css in 24.1.0 correct? After I update to 24.1.0, The columns panel in tool panel will only show 1 column, the scrolling is disabled with "overflow: hidden" and the padding of the parent div also doesn't seem correct. After remove this `height: 100%`, change overflow to auto and add padding to the parent locally, it works correctly.

The column selection panel in the column menu has the same problem.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

---

Note that this issue is flagged with waiting-for-repro.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
