### ISSUE TITLE
Infinite scroll CTRL+END / CTRL+HOME (new scenario)

### ISSUE THREAD

**Issue by Romanow88** [ag-grid/ag-grid#4157]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

This is a follow-up to #4139 with more data to reproduce the issue (recording of the problem).

Plunkr: https://plnkr.co/edit/EeDRAZ8LKoPCklUn

**Reproducible Scenario**
Use infinite scroll / server side data ;
Set the the result count;
Select first row;

**Current behavior**
Hit CTRL + END (goes to last result);
Hit CTRL + HOME !(does nothing)!;

**Expected behavior**
Hit CTRL + END (goes to last result);
Hit CTRL + HOME should navigate to the first result (as it does for client data).

I have made a recording showing this in the linked plunkr. Please note the recorded keypresses in the gif.

https://drive.google.com/file/d/1-XPisKp9JLTWQ6GeO5-XmY41fta4J5QQ/view?usp=sharing

**Please tell us about your environment:**
Windows 10, IDEA 2020.2, NPM, Tomcat 8

* **ag-Grid version:** X.X.X
24.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"

* **Language:**
TypeScript 3.8.3

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hello!

Thank you for the context you provided so far - this really helps us understand your requirements.

This has been raised before, and we are already tracking it in our pipeline with the following reference and description:

AG-4647: [Infinite Row Model] Selected cell loses focus when scrolled far out of view

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can check whether this item is selected for implementation by taking a look at the NEXT RELEASE tab of the product pipeline:

https://www.ag-grid.com/ag-grid-pipeline/

Thanks again for bringing this up with us.

Note that I am now closing this ticket, if anything changes feel free to reopen this ticket.

Regards,

Shuheb
