### ISSUE TITLE
applied filter passing the filter states object

### ISSUE THREAD

**Issue by bhardwajashutosh9520** [ag-grid/ag-grid#4178]
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
- I select the filter from drop-down options of columns and get the object of filtered states in "onChangeFilter()" and saved that object in redux state and we are persitsing that object and we want to add those filter states that are already saved in redux state on reload the page , for this we are using "onFirstDataRendered" and passing the redux state object in 
"params.api.setFilterModel()" It works but when we select more filters then we get the error i.e. "TypeError: Cannot add property areEquivPropertyTracking, object is not extensible"

**Current behavior**
- Adding more filters , It gives error  "TypeError: Cannot add property areEquivPropertyTracking, object is not extensible"

**Expected behavior**
- adding more filters easily update the filter state without occured any error . 

**Please tell us about your environment:**
O.S.- Ubunut 18.04.3 LTS , IDE - Visual studio code  

* **ag-Grid version:** 
24.0.0


* **Language:** [ ES6/7 | Next.js]

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

---

Note that this issue is flagged with waiting-for-repro.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
