### ISSUE TITLE
column reordering not maintained when columnKeys provided (exportDataAsExcel)

### ISSUE THREAD

**Issue by FoleyTim** [ag-grid/ag-grid#4185]
**I'm submitting a ...**  (check one with "x")
```
[X bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
``
**Current behavior**
when the excel is exported the columns are in the default order, not the reordered order

**Expected behavior**
after reordering my columns I expect my reordering will be reflected in my exported excel file because allColumns is set to false, but after I added columnKeys param they are now in the default order.

to reproduce use these params:
		const params = {
			skipHeader: false,
			skipFooters: true,
			skipGroups: false,
			columnKeys: ['1','2','3'],
			allColumns: false,
			onlySelected: true,
			columnGroups: true,
			fileName: 'example'),
			sheetName: 'example'
		};


**Please tell us about your environment:**
Vscode, windows

* **ag-Grid version:** X.X.X
~22.1.1

* **Browser:**
Chrome

* **Language:** [TypeScript ]

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

---

Note that this issue is flagged with waiting-for-repro.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
