### ISSUE TITLE
`columnVisible` event is not called when `suppressColumnStateEvents` is true

### ISSUE THREAD

**Issue by abhimediratta** [ag-grid/ag-grid#4235]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
The `columnVisible` event is not called when columns are toggled in the columns tool panel, when the `suppressColumnStateEvents` is set to true.

**Expected behavior**
The `columnVisible` event should be called when columns are toggled in the columns tool panel, when the `suppressColumnStateEvents` is set to true.

**Please tell us about your environment:**
Windows, npm, VSCode

* **ag-Grid version:** 24.1.0
Yes, this is an issue in the latest version.

* **Browser:**
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.11 Safari/537.36 Edg/88.0.705.9`

* **Language:** ES6

* **Plunker:** https://plnkr.co/edit/mbXqrbH8knb1vcTH?preview

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by abhimediratta** [comment]
Thanks for looking into it

**Comment by kiril-matev** [comment]
Hello!

Thank you for this question.

When changing the visibility of a column via the UI (e.g. columns tool panel), the columnVisible event is not fired if gridOptions.suppressColumnStateEvents = true as shown here:
https://plnkr.co/edit/2jgIavvJb20Vcgbf

According to our documentation pages here:
https://www.ag-grid.com/javascript-grid-properties/#reference-columns

**suppressColumnStateEvents**
Set to **true** to suppress column events being raised when columnApi.applyColumnState(state) and columnApi.resetColumnState() are invoked, or when changing Column State by updating Column Definitions.
Default: **false**

Changing column visibility in the column tool panel updates the column state via API. This state change falls under the effect of the suppressColumnStateEvents=true property setting and this is why columnVisible isn't fired in this case. 

This is why the fact that columnVisible event isn't fired is expected behavior as you have set suppressColumnStateEvents=true.

Please let us know if you have any questions.
