### ISSUE TITLE
Problem in RTL check in small screens

### ISSUE THREAD

**Issue by NaNgets** [ag-grid/ag-grid#4252]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

When using CHROME in a VERY small screen while using RTL, the `isRtlNegativeScroll` check in https://github.com/ag-grid/ag-grid/blob/b62eae1af374bdc2fab278f04c77cce131096be9/community-modules/core/src/ts/utils/dom.ts#L221 doesn't work well, because when using `scrollLeft = 1` it doesn't stick it at 0, the value changes to something small like 0.4~, I assume it's a bug in Javascript but nevertheless, it messes the RTL check.

I reproduced the problem when creating the template in the console and changing the size of the screen when testing:
![image](https://user-images.githubusercontent.com/16867977/102771738-15334d00-438f-11eb-8671-febd99bdbbd0.png)

I was able to fix it by adding a style `zoom: 0.1;`, which works excellent for RTL and doesn't change anything in LTR.
So I assume adding a style to this template element will fix it.

This is in the latest AG-GRID, in the latest CHROME browser, in RTL, in a small screen.

Thanks!

**Comment by gportela85** [comment]
If you check the code, it shouldn't matter if you get a scrollLeft of `1` or `0.4` or `0.000000000001`, because the comparison is `template.scrollLeft === 0;`. Here we are only looking if the scroll is a negative value. If you believe the scrollLeft value should be negative, then this is a BUG in the browser itself.

However, there were two bugs reported with RTL scroll that have been patched in the development branch and are part of the next release. (AG-4804 and AG-4759)
