### ISSUE TITLE
React Button which is in a cell is always return first state value which is defined as useState (even if changed)

### ISSUE THREAD

**Issue by spider58** [ag-grid/ag-grid#4260]
please check below sample.

Here you can see a "increment counter" button which is incrementing a state value.

https://codesandbox.io/s/ag-grid-react-hooks-problem-forked-zj4vr?file=/src/index.js

But when i click a button inside of grid, i can't see current value of state. Always returning first defined value (which is defined by useState)

**Notice**: This state doesn't defined for each row. I have only 1 state for component and i want to access value of state from cellbutton's click event.

is this a bug?

**Comment by seanlandsman** [comment]
What you're seeing here are stale values - this happens when old values are "closed" over and not updated. There are a number of ways that this can occur but in your case I'd suggest using the functional form of `setState` and using a ref to capture the latest value of counter.

See https://codesandbox.io/s/ag-grid-react-hooks-problem-forked-lfelb?file=/src/index.js:0-3279 for a version that uses these approaches.

This isn't really a grid issue, but rather a general js closure issue which occurs more often with hooks (and callbacks) - see https://reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function for more information

**Comment by seanlandsman** [comment]
You could also use a dynamic callback approach: https://codesandbox.io/s/ag-grid-react-hooks-problem-forked-m7f8o?file=/src/index.js
