### ISSUE TITLE
[bug 25.0 react] noRowsOverlayComponentParams do not update

### ISSUE THREAD

**Issue by Paul6552** [ag-grid/ag-grid#4279]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
[Here it is - click me](https://codesandbox.io/s/react-functional-component-forked-1ubyn?file=/src/index.js)

**Current behavior**
Custom overlay does not change the value.

**Expected behavior**
When you open the codesandbox and you click on the button, the custom-overlay prop should change.
This worked perfectly fine with version 23.1.1

**Please tell us about your environment:**
Linux, nodejs, typescript

* **ag-Grid version:** X.X.X
25.0.0

* **Browser:**
Firefox and chrome

Another side information:
You mentioned on the changelog that bug "**AG-4724**" should be fixed with version 25.0 **but it is not**. Because of your "behavior" to close github issues and leave it in zendesk, I will not open again the same issue. Therefore please have a look here, everything is described here: [ISSUE auto height not working](https://github.com/ag-grid/ag-grid/issues/4138)

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as these properties are not meant to be reactive... If anything I would look into using the context react API

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by Paul6552** [comment]
@makinggoodsoftware Again a "feature".

It worked until the version 23.1.1. After this version the behavior changed. So this for sure not a feature request

**Comment by kiril-matev** [comment]
Hi Paul,

I discussed this once again with the product team to clear out any confusion. We've never officially supported the behavior you've described. It was supported earlier (in v23.1.1) but it was never intended as a feature we support and maintain over time. This is why when this was removed there was no alternative provided, because it wasn't an official feature we delivered in ag-Grid.

I'm sorry about the fact this impacts functionality you've been using. We do make changes to the product and some of this earlier functionality is no longer available because it was never intended to be supported in the first place. So in this case I hope this message provides clarity and a way forward to implement this in a different way because this avenue is no longer supported.
