### ISSUE TITLE
Horizontal Scrolling Issue

### ISSUE THREAD

**Issue by andreachirico11** [ag-grid/ag-grid#4283]
**I'm submitting a ...** 
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'

**Providing a Reproducible Scenario:**
[Link to Sample](https://plnkr.co/edit/XK78av1uM6gQAv0m?preview)

**Current Behaviour**
Horizontal scrollbar flickers when resizing page 

**Please tell us about your environment:**

- Browser: Chrome 87.0.4280.141
- angular/core: 10.1.1,
- ag-grid-angular:  24.1.0
- ag-grid-community": 24.1.0

**Comment by Soarex16** [comment]
Duplicate of https://github.com/ag-grid/ag-grid/issues/4231

**Comment by Soarex16** [comment]
As mentioned in https://github.com/ag-grid/ag-grid/issues/4231 this issue is fixed in ag-grid 25.
But do not rush to update, check that all the previous functionality is not broken.

**Comment by andreachirico11** [comment]
OK thanks for the answer

**Comment by danielmalaton** [comment]
I'm now using v31 and still facing the same issue

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10550**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
