### ISSUE TITLE
SSRM - Tree Data - applyServerSideTransaction not work on non-group rows

### ISSUE THREAD

**Issue by ErickPetru** [ag-grid/ag-grid#4293]
**I'm submitting a ...**
```
[X] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[ ] support request => see 'Requesting Community Support'
```

**Current behavior**
I'm using the updated **Server-Side Row Model** from **25.0.0** in **Tree Data** mode. Then I'm trying to add via a _Transaction_ a new row inside a child.

If the child row is already a group (i.e. has a `childStore` inside it), everything works as expected. But if the row is not a group yet (no `childStore` inside it) the `applyServerSideTransaction` results in `{ status: "StoreNotFound" }` and nothing more happens.

It even doesn't matter if the grid `serverSideStoreType` is `"partial"` or `"full"`.

**Expected behavior**

The target node should automatically have a `childStore` created and its `group` attribute set to `true`. The transaction should be applied successfully, with the new row being added. The just created `childStore` should be automatically set to `"loaded"` state, so if the parent is expanded the child is already there to be shown.

Note that I'll be integrating this tree with real-time updates via _WebSockets_. So I just can't purge the grid and re-request all rows in that route, I need to add on-the-fly the data that I'll receive from the _WebSockets_ message using `applyServerSideTransaction`.

**My environment:**
* **Plunker:** https://plnkr.co/edit/ZKAOSyntpgyxcGY7?preview
* **ag-Grid version:** 25.0.0
* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
* **Language:** Doesn't matter

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by RonitMaity** [comment]
Hi @makinggoodsoftware , do we have any progress on this issue ?

**Comment by kiril-matev** [comment]
Hi @ErickPetru,

Thank you for raising this with us.

The behavior you've reported isn't a bug because it's documented as a known limitation of the current implementation of transactions. Please see this section in our documentations:
https://www.ag-grid.com/documentation/javascript/server-side-model-transactions/#targeting-stores

Quoting from this page: “When updating grouped data, a transaction needs to be targeted against the group. This is done by using the transaction's route attribute. The group must be open for the add to happen.”

We have added a feature request to implement this in the future:
**AG-5069 [SSRM][Transactions][Tree Data] Allow adding a child row under a leaf row, turning the leaf row into a group row**

However, you can implement this by making the node you want to add children to a group node at the start and expanding it. This way it will be an open group you can add children to - see this implemented here:
https://plnkr.co/edit/zvr2QNtwNWwnHKgQ

Also, the server-side row model is an ag-Grid Enterprise feature. As an ag-Grid Enterprise user you're entitled to access to our support system - I would suggest submitting any questions there in the future, so we can help you faster.

Thanks again for using ag-Grid.

**Comment by karolszymanski** [comment]
Hello everyone,

I have also struggled that issue for very long time and couldn't find any working solution or workaround BUT **In ag-grid 31 it works just fine.** 
[https://ag-grid.com/angular-data-grid/server-side-model-updating-transactions/](https://ag-grid.com/angular-data-grid/server-side-model-updating-transactions/)

Enjoy!

**Comment by Athelian** [comment]
I have this problem in 34.1.0 React. 

In my case, I am trying to turn a root level row node (not a leaf) into a group row node.

Following @kiril-matev's advice may work for leaf nodes, but in my case, the only transaction I can run is with an empty route:
```
params.api.applyServerSideTransaction({
  route: [],
  update: [
    {
      ...node.data,
      group: true,
    },
  ],
})
```
meaning that every single root node is set to a group, which defeats the purpose.

It works for leaf nodes because the store already exists for the node and we can target it with a route, but we can't do so in my case.
