### ISSUE TITLE
SortChangedEvent do not have a source property indicating whether it's triggered by user or ColDefs update.

### ISSUE THREAD

**Issue by connorlufei** [ag-grid/ag-grid#4332]
This is a great pain for me as in my case I need to distinguish sortChangedEvent triggered by user or column definition update and acting differently. Adding a flag when setColDefs is very cumbersome as I need to actually figure out if the column definition update will trigger a sortChangedEvent and how many times it will trigger. That seems very much code to do.

**Comment by makinggoodsoftware** [comment]
Hi,

We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs, and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

To allow GitHub users to provide feedback we are going to flag this ticket as community-engaged, which means that concerns and/or opinions around this feature request are welcomed and you can expect as well to hear back from us with updates.

We have linked the feature request in our system to this ticket so they will be taken into consideration when is selected for development.

Note that because we prioritize enterprise customer support, it might take us some time to update this ticket.

This is the reference and summary of the relevant issue:

___

AG-2013 | [Events] Add source to all events in ag-grid
-- | --
