### ISSUE TITLE
Cell navigation / interaction: keyboard position does not equal focused cell position

### ISSUE THREAD

**Issue by gueste** [ag-grid/ag-grid#4394]
**I'm submitting a bug report (regression)**

**Steps to reproduce**
1. Sort a grid with at least 2 columns in reverse insertion order. Newly added rows therefore will appear on top.
2. Focus a cell in any column
3. Insert new rows via JS, without losing the focus on the cell

**Current behavior**
Per inserted row, cell focus moves up one row. 
When you then use the keyboard to
- navigate left / right to the next cell
- or to press enter to trigger an action on the focused cell
... then the wrong rowIndex will be used.

For example: 
- After focusing a cell, 3 rows have been inserted via JS, causing cell focus to move up 3 rows. When you then press left or right via keyboard, to navigate to the left or right column, then the focus moves down 3 rows instead of only changing the column and keeping the same rowIndex.
- Same thing happens if you press enter to trigger a cell action - it will be triggered for the wrong cell (= not for the focused one)

**Expected behavior**
The "current rowIndex" used for keyboard-related cell-actions should equal the one of the currently focused cell.
My current workaround is to re-apply the currently focused cell "onModelUpdated". (getFocusedCell + setFocusedCell)

**Why is this a regression?**
In ag-grid v22 it worked like described in the expected behavior, I did not need the workaround. 
It is the last version that I know of where it worked like expected.

**Please tell us about your environment:**
Windows 10

* **AG Grid version:** 25.1.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.

* **Language:** TypeScript 4.0.3

**Comment by gueste** [comment]
Calling "onCellFocused" manually in non-public focusController with param forceBrowserFocus set to true during onModelUpdated has the same effect as my other workaround via the regular API.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

---

Note that this issue is flagged with waiting-for-repro.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
