### ISSUE TITLE
Issue in Scroll bars in Version : 24.1.0

### ISSUE THREAD

**Issue by kamleshbiswal07** [ag-grid/ag-grid#4423]
<img width="42" alt="Screenshot 2021-03-29 at 9 29 38 PM" src="https://user-images.githubusercontent.com/20790087/112865296-4336d480-90d6-11eb-8401-52d32cc01c2b.png">

We are facing the issue of Scrollbars on migrating to version: 24.1.0. We are using Flex Layout on laying out the Ag-Grid.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

---

Note that this issue is flagged with waiting-for-repro.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
