### ISSUE TITLE
SetRowData is slow with large data set even though pagination set to 10 items per page

### ISSUE THREAD

**Issue by ianadavies** [ag-grid/ag-grid#4440]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Hi There,

My application is using Angular 11.
I have a simple grid with about 4000 rows of data that I want my users to be able to search.
If have pagination enabled and items per page is set to just 10 

Current behaviour.

when I call `gridApi.setRowData(items)` it is very slow ~ 6 seconds.
If I check `gridApi.getDisplayedRowCount()` the number of displayed rows is the length of my array ~ 4000

Expected behaviour. 
`gridApi.setRowData` should be fast as I only want to display 10 items at a time. 
`gridApi.getDisplayedRowCount()` should return 10.

Windows 10, angular, node, nopm.

* **AG Grid version:** 
25.1.0

* **Browser:**
Chrome

* **Language:** 
Typescript

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by winfa** [comment]
@ianadavies I think I was facing the same issue. After checking the code, I found the page loading slowly because it was checking each row's height when you set ag-grid table as autoHeight. So, one of the solution is to manually set the table's height, then setRowHeight will not been called here.

![image](https://user-images.githubusercontent.com/1180249/120200302-c4395600-c256-11eb-8fe4-a1e1d3057e09.png)
