### ISSUE TITLE
JAWS reads incorrect number of rows in table

### ISSUE THREAD

**Issue by BenHagadorn** [ag-grid/ag-grid#4442]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

I am using ag-grid in a Polymer/JavaScript framework.  I have a table with both column headers and filtering set up.  Our application is used by the US Federal Government and must meet all the 508 accessibility guidelines.  When I navigate into the grid using the keyboard, JAWS (or any other assistive technology) incorrectly reads the number of rows displayed in the table. 

![ag-grid](https://user-images.githubusercontent.com/82463414/114584723-ee0bce80-9c50-11eb-99c0-ead584ea36b2.png)

When the user enters the first (and only) row of data, JAWS reads: "Column 1, Row 2".  I would expect JAWS to read "Column 1, Row 1".

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

This is expected behavior. As per the **WCAG-ARIA** specification, the aria-rowindex attribute is set for each row in the grid regardless of whether it's a column header row or a data row. This is why when displaying a single column header row it is labelled as the row with aria-rowindex=1, and your first data row is in this case aria-rowindex=2.

If you're using a multi-level column group in the headers, you'll have additional header rows announced before the data rows, as in this sample here, where you have 2 levels of header rows followed by a data row:
https://plnkr.co/edit/2wGTbjvobVr7Y69e

You can see this documented here (specifically the section on aria-rowindex):
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Row_Role

Quoting from this section:
_For example, if a table has 1,500 rows, but only the header and rows 47 and 52 are in the DOM, aria-rowindex="1" would be set on the header row, and aria-rowindex="47" and aria-rowindex="52" would be set on the 47th and 52nd row, respectively._

I hope this clarifies this is expected behavior and that you're in compliance with accessibility standards.

Thank you for letting us clarify this point.
