### ISSUE TITLE
Resetting the columns will cause order problems

### ISSUE THREAD

**Issue by xuehaiouyang** [ag-grid/ag-grid#4494]
**Current behavior**

Sequential execution
`gridOptions.api.setColumnDefs([{headName: "1", field: "1"}
,{headName: "2", field: "2"}
,{headName: "3", field: "3"}])`
`gridOptions.api.setColumnDefs([{headName: "4", field: "4"}
,{headName: "2", field: "2"}
,{headName: "3", field: "3"}])`
![截屏2021-05-28 下午2 24 15](https://user-images.githubusercontent.com/22770979/119939401-668bdc00-bfc0-11eb-94d7-068ebf8a7073.png)

**Expected behavior**

The correct header sequence is “4、2、3”，but “2、3、4”
**Please tell us about your environment:**

mac os 10.15.7, vs code ,npm ,http
* **AG Grid version:** X.X.X

25.3.0
* **Browser:**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
react, ES6

**Comment by kiril-matev** [comment]
Hi @xuehaiouyang,

Thanks for submitting this.

When Column Definitions are provided for existing Columns, the order of the Columns inside the grid is not changed to match the order of the newly provided Column Definitions. This is by design so that any reordering of the columns a user does to the grid is not lost when the Column Definitions get updated.

If the desired behaviour is that Columns should be ordered to match the new set of Column Definitions, set the grid property applyColumnDefOrder=true.

This is documented here:
https://www.ag-grid.com/javascript-grid/column-updating-definitions/#applying-column-order

Please see this implemented in this sample, which set this property:
https://plnkr.co/edit/kaAt9NFlQ2VRzjLf

As applyColumnDefOrder=true, clicking the button above the grid sets the same columns in reverse order.

Thank you for getting in touch!
