### ISSUE TITLE
Missing grid property stopEditingWhenGridLosesFocus in documentation 

### ISSUE THREAD

**Issue by giorgitus** [ag-grid/ag-grid#4525]
Documentation request 

I can not find stopEditingWhenGridLosesFocus but if used it works properly.

Can you insert into the official documentation

**Comment by skydever** [comment]
I think it is deprecated, but I can't find any info in the changelog 😞 

I geht the output `AG Grid: since v25.2.2, the grid property 'stopEditingWhenGridLosesFocus'.` in the console. When I look at the source code details of the warning I see a `checkForDeprecated` function, so I assume it is deprecated.

Will it be removed in future releases? Is there a replacement for it?

**Comment by makinggoodsoftware** [comment]
Hi,

We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs, and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

To allow GitHub users to provide feedback we are going to flag this ticket as community-engaged, which means that concerns and/or opinions around this feature request are welcomed and you can expect as well to hear back from us with updates.

We have linked the feature request in our system to this ticket so they will be taken into consideration when is selected for development.

Note that because we prioritize enterprise customer support, it might take us some time to update this ticket.

This is the reference and summary of the relevant issue:

___


AG-5466 | When using removed property stopEditingWhenGridLosesFocus, the console warning message isn't correct
-- | --


___

Note that the property name has changed stopEditingWhenGridLosesFocus was renamed to stopEditingWhenCellsLosesFocus

**Comment by skydever** [comment]
thx @makinggoodsoftware ... but I think there is a typo, I found `stopEditingWhenCellsLoseFocus`

**Comment by makinggoodsoftware** [comment]
Hi,

My mistake, yes there was a typo! @skydever Thanks! As you mention the correct property is stopEditingWhenCellsLoseFocus
