### ISSUE TITLE
[FILTER] Nested object value does not get to the valueFormatter in filterParams

### ISSUE THREAD

**Issue by githubuser234** [ag-grid/ag-grid#4526]
**I'm submitting a ...** 
```
[x] bug report
```

If you use nested object data for the grid, the `params` input in `valueFormatter` callback in `filterParams` for `'agSetColumnFilter'` does not deliver the right `value`.

![grafik](https://user-images.githubusercontent.com/83961121/122224854-cfc28900-ceb4-11eb-9260-dbe473e16f02.png)

**Providing a Reproducible Scenario**
https://plnkr.co/edit/zX52zwNAWLtYBQOo

Here, the data has nested objects:
![grafik](https://user-images.githubusercontent.com/83961121/122224995-f1237500-ceb4-11eb-95cf-30d580fdc961.png)

The `valueFormatter` in `colDef` works as expected, but the `valueFormatter` in `filterParams` doesn't get the right nested object in `params` input.
![grafik](https://user-images.githubusercontent.com/83961121/122225137-17e1ab80-ceb5-11eb-941e-b6ff5fd7c9b2.png)

**Current behavior**
In `filterParams.valueFormatter`, `params.value` does not correspond to the right data but to the string `'[Object object]'`.

**Expected behavior**
In `filterParams.valueFormatter`, `params.value` should correspond to the right data, analogously to `params` input in upper `valueFormatter`.

**Please tell us about your environment:**

* **AG Grid version:** 25.3.0

* **Browser:**
Firefox, Chrome

* **OS:**
Windows 10

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by Jukien** [comment]
Hello,

I have the same issue. Can we reopen it, please?

"ag-grid-angular": "^26.0.0",
"ag-grid-community": "^26.0.0",
"ag-grid-enterprise": "^26.0.1",

**Comment by ochrstn** [comment]
I have the same issue:

```
"ag-grid-community": "^27.1.0",
"ag-grid-enterprise": "^27.1.0",
"ag-grid-react": "^27.1.0",
```

**Comment by icedjello** [comment]
As described in the docs, the purpose of a valueFormatter is: 

_A function or expression to format a value, should return a string. Not used for CSV export or copy to clipboard, only for UI cell rendering. See [Value Formatters](https://www.ag-grid.com/javascript-data-grid/value-formatters/)._ 

From: https://www.ag-grid.com/javascript-data-grid/column-properties/#reference-columns-valueFormatter 

Values formatted in this way cannot be consumed via the filter, in order to achieve this you must use a valueGetter: 

https://www.ag-grid.com/javascript-data-grid/column-properties/#reference-columns-valueGetter 

I have created an example here to show you how you can achieve your use-case: 

https://plnkr.co/edit/xx4XvB9nrEyZgEbX 

I hope this helps,
