### ISSUE TITLE
cellEditor with Vue Composition API

### ISSUE THREAD

**Issue by lordrepha1980** [ag-grid/ag-grid#4569]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

How can i write a cellEditor/cellRenderer with Vue composition API. I dont find an example.

**Comment by enguyen807** [comment]
I would like to know this as well. The documentation is using Vue2 and requires components to be wrapped in Vue.extend. I'm able to render a component in the CellEditorFramework column def but the problem I'm running in to is that I'm not sure how to pass existing row data to the component.

**Comment by kiril-matev** [comment]
Hello!

Thank you for bringing this up with us. 

Currently grid components using vue-property-decorator are not supported in AG Grid. We have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-5699 [Framework] Add support for grid components that use vue-class-component and/or vue-property-decorator**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by kiril-matev** [comment]
Hi @lordrepha1980,

Thank you for reporting this.

It seems you haven't selected Vue 3 in the AG Grid documentation examples as you're referenceing **Vue.extend**.

Please open this link and ensure you've selected Vue 3:
https://www.ag-grid.com/vue-data-grid/component-cell-editor/#example-component-editor 

Please let me know if this helps resolve this issue.

**Comment by seanlandsman** [comment]
@lordrepha1980 @enguyen807 

Please see the updated documentation here: https://www.ag-grid.com/vue-data-grid/component-cell-editor/

There is now an example for both cell renderer and cell editors using the composition API

**Comment by vks-financial-com** [comment]
Looks like the examples with composition API in renderers are gone. Is there any relevant working example in the current documentation?

**Comment by seanlandsman** [comment]
You can find documentation for older versions under our archives - for example the documentation for 30.0.0 can be found here: https://www.ag-grid.com/archive/30.0.0

**Comment by khkramer** [comment]
Why would examples for the current version of Vue be found in older versions of ag-grid documentation? Doesn't make sense.
