### ISSUE TITLE
Export Excel - Server Side tree data

### ISSUE THREAD

**Issue by AhmedFay** [ag-grid/ag-grid#4600]
When I export the server-side model that use tree data to excel it appears for the group column in excel the group key instead of the value, can you check it in this example in ag-grid website?

[https://www.ag-grid.com/javascript-grid/server-side-model-tree-data/#example-tree-data](url)

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by AhmedFay** [comment]
Hi @AG-Zoheil , 
yes, it seems the issue has been fixed and enhanced, but I am not sure in which version, 

thank you

![image](https://github.com/ag-grid/ag-grid/assets/34749560/a28d08cb-bb3d-4612-be19-d0ec863a6181)

**Comment by Punit0431** [comment]
@AhmedFay @AG-Zoheil can you please  share the verssion?

**Comment by AG-Zoheil** [comment]
Hi @Punit0431,

As the issue was never identified in this Github thread, it would hard for us to pinpoint when it was fixed.

We've made some changes to the logic in v28 so I'd definitely upgrade to that one if you are still on an older version than that. But beyond that I would highly recommend you upgrade to the latest available version (30.2.0) in any case to benefit from all our fixes and news features.

Thanks
