### ISSUE TITLE
getRowHeight callback can not access the cell DOM, it's really hard to calculate dynamic content height like images.

### ISSUE THREAD

**Issue by LeiZeng** [ag-grid/ag-grid#4615]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
https://embed.plnkr.co/plunk/WU036udJAHFLqpTr

If reporting a bug make sure to state.

**Current behavior**

getRowHeight callback can not access the cell DOM, it's really hard to calculate dynamic content height like images.
The height of the images can not be calculated.

**Expected behavior**

I need a way to calculate row height where the cell contains dynamic image.
Provide cell DOM reference maybe a way,  or please let me know if there is a way.

**Please tell us about your environment:**

VSCode

* **AG Grid version:** X.X.X

 "ag-grid-community": "^25.2.1"

* **Browser:**

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES7

**Comment by hugop95** [comment]
I had a similar issue, where I am loading images in my cells and the height computed would not often be correct, as the grid would compute it before the image was loaded (and as such having a height of 0). 

I am using Angular, the way I fixed that problem was by having a state management service that stores a very simple map that links each image URL to its dimensions (height and width). 

Each time an image has finished loading, its dimensions are stored in the service, and the grid is asked to refresh that particular row (using the api's method `setRowHeight(null))`. When that row is redrawn, it finds the dimensions of the image that will be shown in the state service, and add the appropriate height style attribute to it in the css.

Note:  I am using v25.3.0 (and autoHeight in my case, although maybe this can prove to be useful with the getRowHeight callback).

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
