### ISSUE TITLE
Row height not being adjusted with autoHeight + cellRenderer

### ISSUE THREAD

**Issue by croraf** [ag-grid/ag-grid#4625]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Check this plnkr: https://plnkr.co/edit/zqMWDEylT2tAxWPC?preview

- last column is defined as "autoHeight" column
- it also uses a cellRenderer which defines its height as 100px fixed (I also set minHeight to 100px, and I also tried to use fit-content with nested components having larger height)

**Current behavior**
The height of each row is the default.

**Expected behavior**
The last column should define the height of each row to be 100px.

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
25.3.0 React

* **Browser:**
Chrome.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**NOTE**
I tried to apply a workaround with setTimouet and api.resetRowHeights() but doesn't help.

**Comment by hugop95** [comment]
I had a similar issue, where I am loading images in my cells and the height computed would not often be correct, as the grid would compute it before the image was loaded (and as such having a height of 0). 

I am using Angular, the way I fixed that problem was by having a state management service that stores a very simple map that links each image URL to its dimensions (height and width). 

Each time an image has finished loading, its dimensions are stored in the service, and the grid is asked to refresh that particular row (using the api's method `setRowHeight(null))`. When that row is redrawn, it finds the dimensions of the image that will be shown, and add the appropriate height style attribute to it in the css (before it even reloads).

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Thank you for your email and for the context you’ve provided.

We looked into your scenario and built a sample to help you implement this behavior:

https://plnkr.co/edit/CmHfWPV4Ywd4MR4l

This can be solved by ugrading to version 26. Autoheight + react cell renderer now works.

I will now close this ticket
