### ISSUE TITLE
Resize with manual and then double click, with colResizeDefault='shift', disables 'flex=1' behaviour for last column

### ISSUE THREAD

**Issue by YossiSaadi** [ag-grid/ag-grid#4629]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**https://plnkr.co/plunk/i7zNNQ4QesXNxexL**

**Current behavior**
Resizing before-last-column (B) manually, and then resizing the same column by double-click, causes the last column to be resized, and disables the flex=1 for the last column(c)

**Expected behavior**
Resizing another column won't cause the last column to lose its ability to flex on all width

* **AG Grid version:** 25.3.0

* **Browser:** all

* **Language:** all

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by LouisMoore-agGrid** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request.

Column Cs flex is disabled because it is indirectly resized when column B is resized using shift resize and when a column is resized, its flex is automatically disabled. This is mentioned [here](https://www.ag-grid.com/javascript-data-grid/column-sizing/#column-flex) in our docs. This occurs even when a column has the resizable property set to false, as shift resize takes precedence over the resizable column property.

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as there may be some way to mitigate this and hopefully someone from the community can help you with a workaround/fix.
