### ISSUE TITLE
Inaccurate type definition for GetContextMenuItemsParams['node']

### ISSUE THREAD

**Issue by headhancho** [ag-grid/ag-grid#4654]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
type definition for `GetContextMenuItemsParams['node']` does not reflect possibility of `null` value when right clicking over an empty grid (see console output in [plunk](https://plnkr.co/edit/lzb3LhQPa1TiS9hi)). This makes it very easy to miss that edge case and led developers to build methods that throws exception at run time.
https://github.com/ag-grid/ag-grid/blob/latest/community-modules/core/src/ts/entities/gridOptions.ts#L742
```ts
export interface GetContextMenuItemsParams {
    ...
    node: RowNode;
    ...
}
```

**Expected behavior**
type definition should reflect possibility of `null`.
```ts
export interface GetContextMenuItemsParams {
    ...
    node: RowNode | null
    ...
}
```

**Please tell us about your environment:**

* **AG Grid version:** 25.3.0

* **Browser:** N/A

* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs, and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

To allow GitHub users to provide feedback we are going to flag this ticket as community-engaged, which means that concerns and/or opinions around this feature request are welcomed and you can expect as well to hear back from us with updates.

We have linked the feature request in our system to this ticket so they will be taken into consideration when is selected for development.

Note that because we prioritize enterprise customer support, it might take us some time to update this ticket.

This is the reference and summary of the relevant issue:

___

AG-5737 | Inaccurate type definition for GetContextMenuItemsParams['node']
-- | --

**Comment by headhancho** [comment]
That's great, thanks guys!
