### ISSUE TITLE
Horizontal scrollbar is not scrollable using TouchPad

### ISSUE THREAD

**Issue by kiransiluveru777** [ag-grid/ag-grid#4657]
**Horizontal scrollbar is not scrollable using TouchPad**

**Description:**
For Example, the Vertical scroll bar is scrollable when scrolled using Two fingers up and down on Touchpad. Whereas some when we have a horizontal scrollbar in the ag-grid table when I try to scroll horizontally using Two fingers left to right on Touchpad not scrolling. But When I drag the scrollbar using the cursor It is scrolling.

For Example in this link, there is a horizontal scrollbar that scrolls using Touchpad.
https://www.w3schools.com/howto/howto_css_menu_horizontal_scroll.asp

**Current behavior:** Horizontal scrollbar is not scrollable using TouchPad 
**Expected behavior:** Horizontal scrollbar should scroll using TouchPad with fingers.

**Environment:**
"ag-grid-community": "^25.3.0"
"ag-grid-react": "^25.3.0"
OS: Windows 10
Browser: Chrome Version 93.0.4577.63 (Official Build) (64-bit)

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

Note that we don’t take feature requests from Github, we only do this for registered customers via our dedicated support portal.

In any case, we appreciate the feedback.

Please keep an eye on our pipeline as this might appear there.

https://www.ag-grid.com/ag-grid-pipeline/

Thanks for your feedback

____


If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by kiril-matev** [comment]
Hello!

Thank you for bringing this up with us. 

We have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-7164 [Touch] Allow using touch to scroll the grid horizontally**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
