### ISSUE TITLE
Incorrect display of special character in tooltip of grid header.

### ISSUE THREAD

**Issue by gloammer** [ag-grid/ag-grid#4701]
**Current behaviour.**
If we set 'enableBrowserTooltips: true' in grid options and specify special character (for example ' & < > and etc.) for 'headerTooltip' in column definition, ag-grid will display the character encoding in the tooltip.

**Expected behavior.**
Tooltip will display the character.

**Environment:**
Windows OS

**AG Grid version:**
"ag-grid-angular": "26.1.0"
"ag-grid-community": "26.1.0"

**Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36

**Language:** TypeScript 4.1.5, ES6/7

**Example:**
![issue123](https://user-images.githubusercontent.com/42317406/135893609-682b52b4-109f-4ffd-b4a1-f79ee8f24cab.png)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by mistic100** [comment]
@sandovaledwin @makinggoodsoftware The issue stills exists. Yes it is indeed caused by `enableBrowserTooltips`. It is a good thing it protects against XSS but it shouldn't blindly escape everything. I my case I have an apostrophe in my headerTitle and it shows as `&#39;`.

For the record this issue appears and dissappears regularly on each release of AgGrid. I found old issues about that on version 18, fixed in version 20, broken again in 20.1, etc.

As an enterprise customer I will open a ZenDesk ticket, but this is a real issue.

**Comment by gportela85** [comment]
@gloammer @mistic100 this issue has been fixed by AG-5987 and can be checked in the AG Grid pipeline https://www.ag-grid.com/pipeline/

**Comment by mistic100** [comment]
Thank you for the update

**Comment by Akshay-Mario** [comment]
@gportela85 AG-5987 is not shown in pipeline, If it is fixed Please provide the version from which the fix is available
