### ISSUE TITLE
Get column sort model/state

### ISSUE THREAD

**Issue by nanandn** [ag-grid/ag-grid#4702]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

* **AG Grid version:** X.X.X
"ag-grid-community": "26.0.0",

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36'

Is there a way to get the current column sort state/model from the grid. I want to be able to save the sort/filter/page state in the URL for bookmarking. What's the best way to achieve this?

Thanks
Anand

**Comment by sandovaledwin** [comment]
Hi Anand,

I had implemented a similar behavior using the ag-grid API.

The next statement will help you to get the current state of your grid:

const savedState = **gridOptions.columnApi.getColumnState()**;

And you can load the saved state using the next statement:

**gridOptions.columnApi.applyColumnState({ state: savedState });**

For more information you could read the next documentation:
https://www.ag-grid.com/javascript-data-grid/column-state/

In order to save the state you could achieve this using the LocalStorate: 
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by sandovaledwin** [comment]
@nanandn Thanks to you, it was a pleasure to help!
