### ISSUE TITLE
 Narrator is not announcing the correct grouping for column grouping present inside a master-detail grid

### ISSUE THREAD

**Issue by shkaranam** [ag-grid/ag-grid#4750]
**I'm submitting a ...**  
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
 Plunker : https://plnkr.co/edit/j60jRKhMSh51A82s?preview

**Current behavior**
Narrator is not announcing the correct grouping for Header-1, Header-2, Header-3 headers present in detail grid. Narrator is announcing "Header-1 as 1 of 9 and Header-3 as 3 of 9" which is incorrect.

**Expected behavior**
Narrator should announce Header-1 as 1 of 3 and Header-2 as 2 of 3 and so on.

**Please tell us about your environment:**
Operating System: Windows 10 
IDE: Visual Studio Code
Screen Reader : Narrator, NVDA(2021.1)

* **AG Grid version:**
24.1.0

* **Browser:**
Chromium Edge Version: 92.0.902.78 (Official build) (64-bit)
Chrome Version: 88.0.4324.150 Official Build) (64-bit)

* **Language:** [TypeScript 3.8.2]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

As you're using master/detail functionality you are an AG Grid Enterprise user and you have access to our support portal. In the future please open support tickets there in order to get help.

It seems you're reporting a variation of the behavior you submitted here:
https://github.com/ag-grid/ag-grid/issues/4751

By default, the column groups Header1, Header2, Header3 are expanded. This is why in the announcement you're getting when focusing Header1 you have the total number of columns used in the announcement including the number of child columns.

This is correct because it reflects the expanded state of the Header1, Header2, Header3 and is equal to number of items the user can navigate through by pressing the DOWN ARROW key before reaching the end of the list.

When Header1, Header2, Header3 are expanded, using an announcement that uses a total count of 3 when actually there's more will be confusing to the user and prevent them from navigating the list. 

When you collapse Header1, Header2, Header3, the announcement is updated and uses a total count of 3, as there's only 3 items in the list.

This is why the current behavior is correct and generates the appropriate announcements.

Thank you for bringing this up.
