### ISSUE TITLE
When using groupIncludeTotalFooter=true, the total is included in pivot chart

### ISSUE THREAD

**Issue by anton-simola-finnos** [ag-grid/ag-grid#4762]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**
(We are customers but I don't know how to get access to ZenDesk :S )

**Providing a Reproducible Scenario**

Current behaviour:
When using the groupIncludeTotalFooter=true option of the grid, and then using the pivot with charts, then total is being included as one of the bars in the chart.

![image](https://user-images.githubusercontent.com/64903002/140952493-ff81d6b2-a316-4b12-86c8-58b444b0cb9d.png)

![image](https://user-images.githubusercontent.com/64903002/140951461-227dc50f-8c8e-41fc-8cc6-c31345152bd5.png)
(the last bar is the total of the whole group)

Expected behaviour: In my opinion the total should not be included, as it does not really provide value and skews the chart. Another option would be to have feature toggle for the current behaviour. 

**Please tell us about your environment:**

* **AG Grid version:** 25.2.1

* **Browser:**

Edg/95.0.1020.44
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 4, Angular 12

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6051 When using integrated charts to chart all rows in a grid, grand/group total footer rows shouldn't be included**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
