### ISSUE TITLE
Column Header tooltip for each AutoGroup column with groupDisplayType - 'multipleColumns'

### ISSUE THREAD

**Issue by ppatliakevych** [ag-grid/ag-grid#4768]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hello everyone,

I`m trying to display some custom data in column header tooltips and I faced a problem with multiple autoGroup columns. I need a way to display a column specific data for each autoGroup column in header tooltips without using Custom Tooltip Component. AutoGroupColDef sets common headerTooltip for all autoGroup columns but I need to set particular data per autoGroup column header.
How can I do it? Could you provide a headerTooltipValueGetter or so to be able to specify custom data for autoGroup columns? Thank you in advance!

**Current behavior**
In autoGroupColDef we can specify one headerTooltip for all autoGroup columns.

**Expected behavior**
In autoGroupColDef we can specify unique headerTooltip for every autoGroup column.

* **AG Grid version:** X.X.X
 "ag-grid-community": "25.3.0",

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36'

* **Language:**: "typescript": "4.1.3"

**Comment by ppatliakevych** [comment]
The issue was sent to official helpdesk

**Comment by Maratatasan** [comment]
Hello GitHub,

To Display Column Header tooltip for each AutoGroup column without making a custom tooltip  you will have to use **groupDisplayType: 'custom'**

We built an  example to demonstrate this: [https://plnkr.co/edit/QHlaVlF6vGD9IIvN](https://plnkr.co/edit/QHlaVlF6vGD9IIvN)

Some useful doc links: 
- [Custom Group Columns](https://www.ag-grid.com/javascript-data-grid/grouping-custom-group-columns/)
- [Header Tooltips](https://www.ag-grid.com/javascript-data-grid/column-headers/#header-tooltips)


Note that this issue will get closed soon, but you are welcome to create a new issue if you think this issue is still not resolved

**Comment by ppatliakevych** [comment]
Hi Maratasan,

Thanks for your answer. I`m wondering if there a possibility to set a group headerTooltip while using  groupDisplayType: 'multipleColumns'? 

Best regards,
ppatliakevych
