### ISSUE TITLE
Custom detail cell renderer row height problem with detailRowAutoHeight=true

### ISSUE THREAD

**Issue by barbarossusuz** [ag-grid/ag-grid#4780]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I just added detailRowAutoHeight=true to AgGridReact in the example in the link: https://www.ag-grid.com/javascript-data-grid/master-detail-custom-detail/#custom-detail-with-grid

- here reproduced example: https://plnkr.co/edit/6a5RqbO2jhUPQpRD

**Current behavior**
When creating custom detail cell renderer with "detailRowAutoHeight=true" in the parent the row height decreasing constantly

**Expected behavior**
There was no such problem in version 23, it broke when upgraded to version 26

* **AG Grid version:** 26.2.0

* **Browser:**
Chrome/90.0.4430.93 
Safari/537.36

* **Language:** React / ES6

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by LouisMoore-agGrid** [comment]
Hi,

Thanks for your message.

We've had a look at the scenario you've described but have found the behaviour to be as expected. This happens when the detail component's top most element hasn’t been set a height, this is mentioned in the docs [here](https://www.ag-grid.com/react-data-grid/master-detail-height/#auto-height):

"_If you are providing your own Detail Cell Renderer, then you need to make sure the top most element of the Detail Cell Renderer has the correct height, as this is what the grid checks and matches the row height to this. So make sure the CSS on the top most element is set so that its height is correct._"

The reason this wasn't an issue in v23 is because the detailRowAutoHeight feature wasn't added until v25 of the grid.

We’ve updated the example to set a height for the react container element which contains the custom detail, this prevents the issue you're seeing on your end:

https://plnkr.co/edit/mLqC3C3zbKnITvXy

Hope this helps,

Louis

**Comment by Vilash1990** [comment]
Hi @LouisMoore-agGrid , I am not sure where did you set the height for the top most element of the Detail Cell Renderer in here https://plnkr.co/edit/mLqC3C3zbKnITvXy?preview.

I am using angular-ag-grid and custom ag-grid for details grid. Somehow I am not able to expand when I set detailsAutoHeight to true. Otherwise it just taking the static height that I am providing for the details grid. If the number of rows beyond the static hight, then I am unable to see the rows and i am not seeing scroll bar also in the detail grid. I see the scroll bar in the master grid though if it reaches beyond his hight.

any help would be appreciated

**Comment by Sid0325** [comment]
@Vilash1990  same issue im getting were you able to solve this issue any hack or idea?

**Comment by Khizarkhan07** [comment]
hi @LouisMoore-agGrid , I am conditionally rendering two things. 
One is my loader whose height is 100px
and other is a chart when data is fetched the chart is shown its height is 200px.
But the autoHeight being picked up is always of loader since it was rendered first, any possible resolution of it?
Thanks!

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for your comments. The original response by AG Grid was from more than two years ago regarding versions that are well out of date now. Countless bug fixes and feature enhancements have gone into the grid since then.

We'd be happy to look into this again, but could we please ask that you open a new issue with a reproducible scenario if you are still experiencing problems in our latest version (`v31`).

Many thanks!

**Comment by satejbidvai** [comment]
> hi @LouisMoore-agGrid , I am conditionally rendering two things. One is my loader whose height is 100px and other is a chart when data is fetched the chart is shown its height is 200px. But the autoHeight being picked up is always of loader since it was rendered first, any possible resolution of it? Thanks!

Were you able to fix this by any chance? If yes, a brief explanation of what you did would be very helpful as I'm also having a  similar issue since a week. Thanks!

**Comment by pthibodeaux** [comment]
Experiencing the same issue regarding the height. We have a need to alter the height based on the data.
Is this just a limitation when using "custom-detail" - that the height is always fixed?
Our application is angular, ag-grid version is 32
I can set the specific height using "detailRowHeight", but using "detailRowAutoHeight" does not do anything.
