### ISSUE TITLE
componentDidMount in Detail triggers more times if embedFullWidthRows is enabled

### ISSUE THREAD

**Issue by jtoming830** [ag-grid/ag-grid#4800]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
### Providing a Reproducible Scenario
https://plnkr.co/edit/XM8Ik0Jv9XCXKUAF
Please, note that Detail renderer contains useEffect with empty deps - works like old school componentDidMount. This effect logs in console `name` from row data. 

Open console and expand any detail. 

### Expected behaviour
Name is printed once (so componentDidMount triggered once)

### Current behavior
Name is printed 3 times (so componentDidMount triggered 3 times)
`reactUi` didn't help but it works fine if you remove `embedFullWidthRows`. 

### Please tell us about your environment
MacBook Pro (2019 16-inch), MacOS Big Sur 11.4

* **AG Grid version:** 26.1.0

* **Browser:**
Chrome 95.0.4638.69

* **Language:** React 16

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by Maratatasan** [comment]
Hello,  GitHub!

Thank you for bringing this up with us. 

You can see in our documentation that this is expected behaviour:

If you are mixing Embed Full Width Rows and Custom Detail, then be aware the Detail Panel will get rendered three times as follows:

Pinned Left Columns
Pinned Right Columns
Pinned Centre Columns


link to docs: https://www.ag-grid.com/javascript-data-grid/master-detail-other/#example-embed-custom-detail

In our opinion, this would be a feature request.

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

Now that this has been resolved, please note that soon we will be closing the GitHub issue and not updating it. 

Thanks again for bringing this up with us - we appreciate your time!
