### ISSUE TITLE
setFilterModel zero not working

### ISSUE THREAD

**Issue by kavika-1** [ag-grid/ag-grid#4811]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
We use setFilterModel for various scenarios including save/restore grid state with filters, as well as setting hard-coded defaults.  Setting greaterThan 0 no longer works, and getFilterModel / setFilterModel fail on this as well.

**Provide a Reproducible Scenario**
Plunker: https://plnkr.co/edit/BCdoswM3kH4jhCeS?preview
(https://www.ag-grid.com/react-data-grid/filter-api/#get--set-all-filter-models as-is)

Steps to repro:  
1. Add filter "Gold" greater than 0
2. Verify filter works - sort ascending, will start at 1
3. Click "Save Filter Model"
4. Click "Restore Saved Filter Model"

Current behavior: filter is removed, and the gold zeros return
Expected behavior: filter is kept

Notes:
* It appears the filter doesn't work for zero.  If the filter is set to "greater than 1" is saves and restores properly.
* If the ag-grid version is changed to 26.1.0 in the plunker, the filter works.  Thus it appears to be something changed between 26.1.0 and 26.2.0

**AG Grid version:** 26.2.0
Works still in 26.1.0

**Browser:**
n/a (chrome)

**Language:** [all | TypeScript X.X | ES6/7 | ES5]
See plunker

**Comment by icedjello** [comment]
Hello!

Thank you for reporting this - much appreciated!

We have added this bug to our backlog and we are tracking it with the following reference and description:

**AG-6086 - [Regression] When setting an in-range filter with 0 as a lower bound, the filter is not applied**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See the next release date and whether this item is selected for implementation on the NEXT RELEASE tab of the product pipeline:

https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using the instructions here. This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on the changelog page.

For more information on when can you expect your ticket to be fixed please check:

https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket-

Thanks again for bringing this up with us.

Regards,
