### ISSUE TITLE
Columns orders change when a valuegetter callback function is applied

### ISSUE THREAD

**Issue by linhares87** [ag-grid/ag-grid#4852]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Reproducible Scenario**
https://stackblitz.com/edit/ag-grid-react-callback-test?file=index.js

**Current behavior**
When the valuegetter with a callback changes or the header of the column, all the column definitions is changed, causing a column reorder for example.

**Expected behavior**
When the valluegetter change or the column header, the  colunm definition should remain the same, just change the definitions that was really changed.

**Please tell us about your environment:**
Stackblitz

* **AG Grid version:** 26.0.1

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44'

* **Language:** all

**Comment by shuheb** [comment]
Hi @linhares87 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:

AG-6247 When pivoting and updating a state variable in React, a secondary column header name isn't updated and its location in the column order is reset

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See the next release date and whether this item is selected for implementation on the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using the instructions here. This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on the changelog page.

Thanks again for bringing this up with us.

**Comment by unitytotheunity** [comment]
@shuheb This behavior also appears to happen when using the `valueFormatter` prop with an in-line function definition, like so:

```
<AgGridColumn
  field="fieldName"
  valueFormatter={params => formatCurrency(params.value)}
/>
```

**Comment by linhares87** [comment]
We have some updates about this situation, 

According to the helpdesk:

This is not a bug, to keep the column order after updating the column headerName, you must enable the property maintainColumnOrder.

See our documentation on this: React Data Grid: Updating Column Definitions

I've implemented this in the sample you've provided:
https://stackblitz.com/edit/ag-grid-react-callback-test-fx55qx?file=index.js 

For this simple example worked.

But we have also a more complex situation, where we used Pivot columns

https://stackblitz.com/edit/ag-grid-react-callback-test-srbjwv?file=index.js

To reproduce:
- Activate the Pivot Mode
- Add the country column in the "Column Labels"
So, when you click in change factor, the column name doesn't change anymore, and the columns are re-ordered

For this we are following:
