### ISSUE TITLE
[v26 regression] With autoHeight when resizing columns the height jumps and ends collapsed

### ISSUE THREAD

**Issue by croraf** [ag-grid/ag-grid#4855]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
https://plnkr.co/edit/n1XfecOoA655MXWc

 (try resize couple of times)

**Current behavior**
When resizing, the height jumps. And sometimes the rows end up collapsed to the height of one line.
![image](https://user-images.githubusercontent.com/19698636/147846692-2856c4a5-eb68-45a8-8fc4-7500e878add8.png)

**Expected behavior**
The height should not jump when resizing, and should not collapse to the height of one line.
![image](https://user-images.githubusercontent.com/19698636/147846689-c882cf93-bc62-47b9-ae08-74d8f375b095.png)
https://plnkr.co/edit/JiyS6XNTzMrWleA5  (v25.3.0)

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
community: 26.2.1
react: 26.2.0

* **Browser:**

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

NOTE: Seems to be introduced similarly as #4853

**Comment by croraf** [comment]
Removing:

```
const onColumnResized = (params) => {
    params.api.resetRowHeights();
  }
```

in the new version seems to solve the issue and works properly.
But, am not sure if it has some other consequences. 

Anyways should be described in breaking changes if this is expected.

**Comment by kiril-matev** [comment]
Hi @croraf!

Thank you for reporting this - much appreciated.

The row auto-height rendering logic was changed in AG Grid v26.0 as part of:
**AG-5607 Enhance Row Auto Height Support**

As part of this change row height changes are detected by the grid which refreshes the rows automatically without having to call gridApi.resetRowHeights() in the onColumnResized event handler as before. Actually keeping the calls 
 to gridApi.resetRowHeights() causes rows to render twice, producing the flicker you reported. 

This information was logged as part of MORE INFORMATION but not as a breaking change - thank you for noticing this omission. I've now corrected this and updated the to log this information specifically as a BREAKING CHANGE.

I'm including this information below for full context:
The row auto-height behavior has been changed. When a column uses auto height (colDef.autoHeight=true), there is no need to call gridApi.resetRowHeights() in the onColumnResized event handler anymore to force the rows to update their row height after a column resize operation, as the grid will automatically resize the rows when it detects a height change.

From v26.0 onward, keeping these calls to gridApi.resetRowHeights() causes flicker as rows render themselves twice instead of once. Please remove calls to gridApi.resetRowHeights() in onColumnResized event handler to avoid flicker in row re-rendering. 

Thanks for reporting this - we appreciate your time!

**Comment by croraf** [comment]
Great!
