### ISSUE TITLE
The grid property suppressColumnStateEvents is currently unDocumented

### ISSUE THREAD

**Issue by TomOConnor95** [ag-grid/ag-grid#4857]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
**Requesting Community Support**

**Current behavior**

There is no documentation for `suppressColumnStateEvents`
I only managed to find this by coming across one of the release notes when searching in google for resetColumnState
https://www.ag-grid.com/changelog/?fixVersion=19.0.0

I managed to find some old cods for the `suppressSetColumnStateEvents`
http://54.222.217.254/javascript-grid-properties/

I then found another changelog entry where the name was changed from `suppressSetColumnStateEvents` to `suppressColumnStateEvents`
https://www.ag-grid.com/changelog/?fixVersion=24.0.0

But this new name is not documented anywhere.
Not knowing about this caused me to lose a considerable amount of time (~ 1 Day) trying to manually silence certain events during reset.

**Expected behavior**

In the Grid Properties section of the docs, I'd expect to see the `suppressColumnStateEvents` listed, with a description of what it does
https://www.ag-grid.com/javascript-data-grid/grid-properties/

I'd also expect some documentation to be added to the Column State page to let the user know that this is an option they can set if they are applying/saving table state
https://www.ag-grid.com/javascript-data-grid/column-state/

**Please tell us about your environment:**
Just related to doc so environment doesn't matter

* **AG Grid version:** 26.2.0

This is an issue in the latest docs

* **Browser:**
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by kiril-matev** [comment]
Hello @TomOConnor95,

Thank you for raising this.

Follow the steps below:
1. Open
https://plnkr.co/edit/HYBsPOcBBdiWzqv2
2. Open console
3. Reorder a column

1/ Note that the grid shows a console warning when the suppressColumnStateEvents property is used indicating that property doesn’t have any effect since v25. As setting this property has no effect (in AG Grid v25 and later), it wasn’t documented in newer versions of AG Grid v25 and later. 

2/ Note the grid shows the source of the event in the event params. As per the console warning displayed, if you’d like to suppress events related to column state change, find out in the params inspect the source property whether this is in response to a change done via API or via the user.

Thank you for bringing this up - we appreciate your time!

**Comment by TomOConnor95** [comment]
Thanks you :)
