### ISSUE TITLE
[Accessibility][Screen reader] Filter list options are read twice by NVDA

### ISSUE THREAD

**Issue by pushkumar** [ag-grid/ag-grid#4896]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

Column filter list options are read twice by NVDA

**Expected behavior**

 filter list options should be narrated once

**Please tell us about your environment:**

Microsoft Windows 11 Enterprise 10.0.22000

* **AG Grid version:** X.X.X

AG Grid version: Latest

* **Browser:**

Chrome 97.0.4692.99

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

![Screenshot (70)](https://user-images.githubusercontent.com/96237444/151924184-88f58ee0-0085-4145-a44f-6842a8ebe6dd.png)

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello @pushkumar !
 
Thank you for bringing this up with us. 
 
We have added this in our backlog to track this requirement and implement it in the future.
 
You can track it with this reference:
**AG-6386 [Accessibility] Allow screen readers to announce set filter item text just once instead of twice**
 
You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!
