### ISSUE TITLE
`null` values will be filtered when (Blank) was checked in set-fliter. 

### ISSUE THREAD

**Issue by popo1221** [ag-grid/ag-grid#4914]
I'm submitting a bug report

AG Grid version: 26.2.0
React 17

`null` values will be filtered by (Blank) was checked in set-fliter. 

https://github.com/ag-grid/ag-grid/blob/ecae4f3a7d8e4a5a0ffaf193156290f15bbe120d/enterprise-modules/set-filter/src/setFilter/setFilter.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L456

The `null` in appliedModelValues will be changed to "NULL".

https://github.com/ag-grid/ag-grid/blob/ecae4f3a7d8e4a5a0ffaf193156290f15bbe120d/enterprise-modules/set-filter/src/setFilter/setFilter.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L500

So, `this.appliedModelValues[this.caseFormat(value)] === true` will be false.

And I found that the AG Grid version: 27.0.0 has changed the line to:
https://github.com/ag-grid/ag-grid/blob/36278f3ec78c4eb60ac2c5bd192be7a008fd8227/enterprise-modules/set-filter/src/setFilter/setFilter.ts#L459

**Comment by kiril-matev** [comment]
Hello @popo1221!

Thank you for getting in touch.

In order to help us respond more quickly, please follow the template provided when submitting a bug report. The template asks you to submit a sample reproducing the issue, a list of steps to reproduce and descriptions of actual/expected behavior.

The changes in code in AG Grid you've highlighted across versions do not point to a specific change in behavior. 

Based on your comments, it seems you're saying that null values are handled differently depending on the version used.

I've compared behavior in v26.2 and 27 and found they behave identically.

Steps to follow:
1. Open
v26.2 https://plnkr.co/edit/c7My33HKh7YmEn45
v27 https://plnkr.co/edit/YJDDsrk6V9VtiTzd
2. Open the floating filter for the column
3. Uncheck the BLANKS item

Actual & Expected: For both versions, the row with NULL value gets filtered out.

In order to help us progress this:
1/ modify this sample to reproduce the issue you've described 
2/ provide a list of steps to follow
3/ provide descriptions of actual/expected behavior

We're looking forward to looking into this.

**Comment by popo1221** [comment]
hi @makinggoodsoftware. 

Here is my steps: 
1. Open
     v26.2 https://plnkr.co/edit/c7My33HKh7YmEn45
      v27 https://plnkr.co/edit/YJDDsrk6V9VtiTzd
2. Open the floating filter for the column
3. _**Only check the BLANKS item.**_

The v26.2 verison's result is empty. But v27 version still has 3 empty rows.

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now identified this behavior is caused by this bug:
**AG-6046 [Regression] When de-selecting any non-blank set filter item, blank values also get filtered out  from the grid even though the (blanks) set filter item is selected**

As you've demonstrated in your sample, this bug is fixed in AG Grid v27.0.

**Please upgrade to v27.0 or later to resolve this issue.**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by popo1221** [comment]
Thanks for the reply. I'll try it.
