### ISSUE TITLE
ag-gird-angular,Quick Filter bug

### ISSUE THREAD

**Issue by xuxianshengsr** [ag-grid/ag-grid#4929]
```
this.gridApi.setQuickFilter('new filter text');
```
This API will ignore some letters `a`,`b`,`c`,`d`,`e`,`j`,`o`,`t`,`z`,The filtering function is bug.
The demo for quick filter of official documents also has this bug.

**Comment by xuxianshengsr** [comment]
For example, in the demo of the official documentation, entering the 'a b c d' filter will not have any response

**Comment by StephenCooper** [comment]
I can understand your confusion but the filter is not broken, let me explain what is going on. (I think we should probably update this example to make it clearer)

For the letters `a`,`b`,`c`,`d`,`e` and `z` they appear in every row due to the nature of the row data. This means that adding one of these letters does not filter any rows because they all match.

For the letters `j`,`o`,`t` its a bit more subtle. For Column E the row data is an object but as the columnDef only uses a `field` property and a `cellRenderer` and does not provided the method `getQuickFilterText` (like col D) the quick filter will get the built in `toString()` method.
```ts
    // this fails filter - it's working with a complex object, so the quick filter
    // text gets [object,object]
    {
      headerName: 'E',
      field: 'e',
      cellRenderer: BoldRenderer,
    },
```
So for column E the quick filter sees `[OBJECT OBJECT]` for every row which is why it then also looks like all the letters found in the word object appear not to produce and filter results. 

Once again I can totally understand your confusion and think we should take this opportunity to update this example to make it better.

Thanks for reporting!
