### ISSUE TITLE
How to use `rowDragText` with `rowDragEntireRow`?

### ISSUE THREAD

**Issue by Alaladdin** [ag-grid/ag-grid#4951]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/UyQbUclxFR21m7ZD

**Current behavior**
Text on the row being dragged is `1 row`/`n rows`

**Expected behavior**
Text on the row being dragged is taken from the result of the `rowDragText` function

* **AG Grid version:** 27.0.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.12 Safari/537.36

* **Language:** ES6 - VueJS 2

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by tokarskyibogdan** [comment]
Hey, is it going to be implemented?

**Comment by kiril-matev** [comment]
Hello @Alaladdin!

Thank you for bringing this up with us. 

The functionality you described wasn't part of the requirements when we built the entire row dragging feature. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-7206 [Row Dragging] Allow displaying the text returned in rowDragText when dragging entire row**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
