### ISSUE TITLE
After upgrading to 26.1.0, CellRenderer Refresh() is not being called after edit

### ISSUE THREAD

**Issue by Jlll1** [ag-grid/ag-grid#4993]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Currently, if you edit a cell, the renderer gets destroyed and then recreated, with the `Refresh()` method not being called.
See this [plunker](https://plnkr.co/edit/6PLIfdoBjZae3yw3)

**Expected behavior**
Until recently, I've been using Ag-Grid 24.1.0, where the CellRenderer would get refreshed, not recreated after editing the cell. Is there any way to get this behavior back?
Going back to the example above, the cell should have value "Refresh!" after editing

* **AG Grid version:** 26.1.0

* **Browser:**
Chrome

* **Language:** Typescript

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello @Jlll1!

Thank you for reaching out about this.

This change in behavior is a result of an intentional change we made in AG Grid 26.

Starting with AG Grid 26, the cell renderer is completely destroyed when cell editing starts. This is in line with how Components work in frameworks (Angular, React etc) - specifically, when you take the Component out of the DOM, that is in effect destroying the component. 

In this specific case, when cell editing starts (Cell Editor inserted into the Cell), the Cell Renderer is destroyed, and after the end of cell editing, a new instance of the cell renderer component is created. This is why the component init() method is called, and not the refresh() method because a cell renderer instance is created after the end of editing.

There's no way to get the old behavior back as this is a fundamental change in the way components are handled. As I mentioned above, the new behavior is in line with the way components work in frameworks so this should make component behavior more consistent across your application. Please adjust your cell renderer code accordingly.

Thank you for your time.

**Comment by Jlll1** [comment]
Thank you for your time and the clear explanation.
