### ISSUE TITLE
 Select Everything --> Left spacing

### ISSUE THREAD

**Issue by kellydena-TTMSTech** [ag-grid/ag-grid#5021]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
-Selecting all generates a white space on the left
![image](https://user-images.githubusercontent.com/68281684/160176602-78b974ef-e18a-470f-ab07-a5e3803c7031.png)
- Official documentation

**Expected behavior**
- No space left

 
* **AG Grid version:** 27.1.0

* **Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hi @kellydena-TTMSTech,

We've looked into this.

This behavior isn't a bug, but instead expected behavior. The reason is that when using a function to set whether a checkbox is displayed, AG Grid can't take for granted that all the rows in a column will have checkboxSelection: false. This would require going through all the visible rows at any one time and if all of them have checkboxSelection: false, then skip the cell indentation and in all other cases (when there's at least one  row with checkboxSelection: true) apply the indentation to all cells. 

Doing this as the user is scrolling would result in a performance hit and the cell content may shift in cases when you have say 200 rows without any checkboxes (causing cell indentation to not be applied) and then a single row with a checkbox - as soon as that row is brought into view, all cell values in the column will need to be indented, resulting in flicker and user confusion. 

This is why when checkboxSelection is supplied by a function call dynamically, AG Grid reserves the space for cell indentation to ensure there's room for a checkbox to be rendered and to deliver good scrolling performance and intuitive user experience.

You can achieve the same behavior by having a column locked always in the left-most position showing a selection checkbox.
https://plnkr.co/edit/lAQDLqeBWE0qTIjf 

I hope this helps.

Thank you for your time in raising this!
