### ISSUE TITLE
v27.1 breaks layout by misusing line-height

### ISSUE THREAD

**Issue by jezmck** [ag-grid/ag-grid#5025]
**I'm submitting a bug report**

Vertical padding has been replaced with line-height, which breaks the layout for non-plain-text elements.

Screenshots with ag-theme-material, but appears to be the same issue using alpine.

**Previous behavior** in 27.0.0
![Screenshot 2022-03-28 at 12 19 06](https://user-images.githubusercontent.com/89996/160387320-4913ea24-e398-4661-9ef6-5c1e688d1e2f.png)

**Current behavior** in 27.1.0
![Screenshot 2022-03-28 at 12 19 44](https://user-images.githubusercontent.com/89996/160387330-2f630b76-8579-4635-b85d-1bd5e725a605.png)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by jezmck** [comment]
I didn't get any notification of the label, so didn't do it.

**Comment by makinggoodsoftware** [comment]
Hi @jezmck 

No worries, if you have a repro, we will be happy to have a look!

Thanks

**Comment by jezmck** [comment]
You can compare these, the only difference is the version.

https://plnkr.co/edit/o4sFW6IZyYtLLODa (v27.0.0)
https://plnkr.co/edit/rWjnMOhPVvRavbBs (v27.1.0)

Note how in the second one, the image moves up because the top/bottom padding has been replaced with line-height.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello @jezmck!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6705 [Regression] When displaying non-plain-text elements in grid cells, they're displayed at a smaller vertical offset than needed**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by kiril-matev** [comment]
Hello @jezmck!

We discussed this was change in behavior is due to the updates we made to row height spacing to address issues. 

The example provided has a broken CSS styles - check the span that contains the image, and note it doesn’t fill the cell correctly. The only reason why it used to work, is because the line-height was set to 40px, which wasn’t correct and so this only worked relying on faulty behavior. As the old behavior relied on incorrect row height handling which is now addressed, we've closed this bug as rejected as this isn't a bug with AG Grid.

The correct way to implement this is to create a proper Cell Renderer and style it as shown in the sample below:
https://plnkr.co/edit/5NLKoyMvY0qXFWFy?open=main.js

Please use this approach.

Thank you for your time in bringing this up!

**Comment by jezmck** [comment]
Thanks anyway.
