### ISSUE TITLE
Angular styles not working properly

### ISSUE THREAD

**Issue by jamesdbruner** [ag-grid/ag-grid#5053]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I'm just trying to remove the border around the table. I put together a simple example on [stackblitz](https://stackblitz.com/edit/ag-grid-angular-hello-world-ie7zxh?file=src%2Fapp%2Fapp.component.scss) which shows off different ways I've tried to achieve this. I'm likely missing something super simple and would love to be shown the right way to do this but I looked through the docs and after some googling still can't figure out what I'm doing wrong here.

**Expected behavior**
I would expect to be able to style the grid with scss but my styles aren't be applied for some reason. I wish I could speak to the reason why but I'm really not sure.

**Please tell us about your environment:**
Stackblitz

* **AG Grid version:** 27.1.1
I'm also trying to use 24.0.0 in my actual project but for the sake of the repro, on stackblitz it's using 27.1.1

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by jamesdbruner** [comment]
I was able to fix it using `::ng-deep` which makes the styles global instead of being scoped to the component. I still find it odd that I wasn't able to remove the order through any of the ways I tried in the example above. I'd love to do this the *right* way but for now ng-deep fixes it for my use case.

**Comment by StephenCooper** [comment]
https://stackblitz.com/edit/ag-grid-angular-hello-world-ycanmv?file=src%2Fstyles.scss

You just need to move the styles from app.component.scss to the styles.scss file. The styles that you put in app.component.scss are scooped to only apply when used in the template of app.component.html. They do not match the grid because they actually end up having the following selector. Note the suffix which has the effect of scoping just to the app.component.html template.

```
.ag-theme-alpine.ag-root-wrapper[_ngcontent-cfy-c15] {
    border: 0;
}
```

By moving your styles to styles.scss they will not be scoped and are applied as global styles through out the app. If you do not want these to apply globally but instead just to a single grid then wrap your styles in a class that you only apply to the intended grid. 

```
.grid-no-border{
 .... your styles
}
```

```
<ag-grid-angular 
    class="ag-theme-alpine grid-no-border"
```

**Comment by jamesdbruner** [comment]
Hmm, I might be wrong here but isn't that just the same as using `::ng-deep` at that point since I'm essentially making those styles global? My hope was that I could write my styles in a `:host` selector and just this instance of the ag-grid component would be affected since we use ag-grid throughout our app I really don't want to style things globally. I realize I could increase the specificity in the style.scss file you mentioned I just didn't know if that's the recommended way of handling this type of thing as I'm fairly new to angular.

I really appreciate you replying and talking me through this, thank you! 🙏

**Comment by StephenCooper** [comment]
So yes `::ng-deep` has a similar effect and will only effect the components in the hierarchy below where it is specified. Just be aware there has been talk of deprecating it which is why I provided the alternative above.
