### ISSUE TITLE
Restoring a chart ignores custom chart-theme 

### ISSUE THREAD

**Issue by crc-fehler** [ag-grid/ag-grid#5056]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When using gridOptions.api.restoreChart with a custom chart-theme setted, the theme is ignored and the default them is aplied.

**Expected behavior**
The custom chart-theme should be aplied to the chart.

**Reproduce**
- open the Plunker: https://plnkr.co/edit/3n19uAkPxkkuedQn (fork of your example https://www.ag-grid.com/javascript-data-grid/integrated-charts-api-save-restore-charts/)
- create a chart
- click the button "save chart"
- notice that the custom theme is aplied
- click the button "clear chart"
- click the button "restore chart"
- notice that the default theme is aplied

**Environment:**
* **AG Grid version:** v27.1.0 Enterprice

* **Browser:** Firefox, Chrome

* **Language:** Javascript

**Comment by icedjello** [comment]
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6367 - [Regression] When using custom theme colors in the integrated chart and saving state, the custom theme colors aren't restored when state is reloaded** 

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item is selected for implementation on the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Regards,
