### ISSUE TITLE
[documentation] AgGrid 27.1.0 introduced `applyOrder:` to `applyColumnState`

### ISSUE THREAD

**Issue by wjaspers** [ag-grid/ag-grid#5111]
**I'm submitting a request for documentation**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Documentation does not explain the `applyOrder:` argument.
https://www.ag-grid.com/javascript-data-grid/column-state/

This option is hiding in the example code, but was not present in AgGrid 27.0.

**Expected behavior**
In previous versions of Ag-Grid when consumers of the grid call `columnApi.applyColumnState({ state: [columnState...] });`,
the order was applied.
Without knowledge of this new option, callers do not know they need to add it.

**Please tell us about your environment:**

* **AG Grid version:** 27.1.0+

* **Browser:**
Any

* **Language:** all

**Comment by kiril-matev** [comment]
Hi @wjaspers!

Thank you for contacting us about this.

You're right in saying that the applyOrder property has an important effect on column state behavior. It has been available and documented as part of the applyColumnState API method since AG Grid v24 so it wasn't introduced in v27.1.0

The applyOrder option is documented as part of the API documentation of the applyColumnState method here:
https://www.ag-grid.com/javascript-data-grid/column-state/#reference-state-applyColumnState

I hope this is useful.

Thank you for taking the time to bring this up!
