### ISSUE TITLE
Upgrading to 27.2.1 from 22.1.0

### ISSUE THREAD

**Issue by adnanal-hrbl** [ag-grid/ag-grid#5117]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Providing a Reproducible Scenario
-> **earlier version: 22.1.1**
-> **upgraded to latest version 27.2.1**
-> node modules for ag-grid-community throws error:
/grid/grid.scss
Module build failed: 
    **@return math.div($lhs, $rhs);**
               ^
      Invalid CSS after "    @return math": expected expression (e.g. 1px, bold), was ".div($lhs, $rhs);"
      in /node_modules/ag-grid-community/src/styles/mixins/_ag-theme-params.scss (line 315, column 17)
 -> I created a patch replace math.div with simple "/", then it worked. but getting many ui issues as tabs are not rendering properly and even custom pagination is not working
-> cell renderer is not rendering HTML value, taking only strings type

**AG Grid version: 27.2.1**

Browser:

Latest Chrome: 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Mobile Safari/537.36'
Language: all

**Comment by MBolin-ADCIP7F** [comment]
Same here.

**Comment by makinggoodsoftware** [comment]
As of Version 26 of AG Grid, Node-Sass will no longer work with AG Grid. 

This is due to Node-Sass being deprecated in favor of Dart-Sass, you can find out more about this [here](https://www.npmjs.com/package/node-sass).

For users upgrading from versions of AG Grid before 26 or new users, we would highly recommend using [Sass](https://sass-lang.com/). 

For more information regarding AG Grid and Sass and how themes and styles work, please visit our [documentation](https://www.ag-grid.com/javascript-data-grid/themes-customising/#sass-mixins-and-functions).

**Comment by adnanal-hrbl** [comment]
thanks for your quick response. will check with Sass and will update

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
