### ISSUE TITLE
[component] Allow providing component for overlay (not just string template)

### ISSUE THREAD

**Issue by MikaAK** [ag-grid/ag-grid#513]
For the overlays it would be very helpful to have them being passed to compile. For example say you have directives to show overlays then you could just set the overlayTemplate to `<my-directive></my-directive>` and be done with it.

**Comment by ceolter** [comment]
i wasn't expecting the overlays to be complex. true the overlay would then be able to take a directive. let me think about it. ideally i'd like to get away from compiling like this - as i'm trying to get ready for Angular 2 and Web Components . . . . . . so would be better if I could allow complete control given to the client, and then leave it to you to Angular 1.x Compile (or whatever, Angular 2 will be different). would be nice if i had a plugin archeticture, so that different systems could work here.

i think this is a 'nice to have' ???

**Comment by MikaAK** [comment]
Even if it took an element that would be very handy. The reason for this being that, say for example we have a directive that we use for loader icons, this includes animations etc because they are done with JS, without being able to use a directive our loader icons don't work :cry: It also makes translations a bit more difficult to bake in though there are workarounds to this.

**Comment by ceolter** [comment]
You can already provide your own overlay???? See the overlayLoadingTemplate property.

**Comment by MikaAK** [comment]
Yes but due to it being just pure html, it's annoying to have to recreate animations and in a more complex way then just using it from a directive we already have. It also removes the ability to use angular animations say via class name.

**Comment by ceolter** [comment]
I've just come back from Angular connect - where I learnt that the Angular team don't want you to do direct dom manipulation and won't don't intend for you to be using the compile service in Angular 2. That's not going to be good!!

**Comment by ceolter** [comment]
i am wondering - what if i added the ability for you to provide a dom element instead of html string for the overlay - would that work? that way, it would be generic, you could provide an angular bound element, or anything for that matter, my grid wouldn't care what framework you are using! thoughts?

**Comment by MikaAK** [comment]
That would be perfect! Being able to provide a dom element means it can have all the listeners and other things I might need.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-76

**Comment by AmrKaf** [comment]
@ceolter any update on this?

**Comment by makinggoodsoftware** [comment]
This should be done now
