### ISSUE TITLE
Params.data is not reactive when I provide getRowId prop

### ISSUE THREAD

**Issue by zhiyuanzmj** [ag-grid/ag-grid#5225]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The params.data is not update  when I provide getRowId prop , and update rowData.
[https://plnkr.co/edit/1Fx2NSnIPNMzpeFo?preview](https://plnkr.co/edit/1Fx2NSnIPNMzpeFo?preview)

**Expected behavior**
I hope in cellRenderer, params.data is reactive. 

* **AG Grid version:** 
latest

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by chefnoname** [comment]
Hello github!
 
Thank you for your email and for the context you’ve provided.
 
We looked into your scenario and built a sample to help you implement this behavior:
 
[https://plnkr.co/edit/JQYoXnaaSxpgB9D4](url)
 
**Note**: when **getList()** is called in the **totalValueRendererVue** it updates the **count** column as it is binded to it - not **actions** but you can set a headerName as I did to rename columns
 
Please use the sample above to implement this and let me know if you have any questions.
 
Regards,

**Comment by zhiyuanzmj** [comment]
Like this 
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/32807958/173595996-80cfef50-cf11-4c6e-aa09-3bf4924437d4.png">

**Comment by prempopatia** [comment]
we are using ag-grid v30.0.2 with vue v3, Whenever we are using getRowId parameter, our cell renderer does not update props value to new ones. in short, props reactivity is getting lose in cell renderer. We have tried many things but not able to make this thing work. 

@zhiyuanzmj have you found the solution? if yes, can you please tell me?

Opening this issue again because we are facing same issue and not able to proceed in task as this is important for our task.
