### ISSUE TITLE
Version 27.0 no longer renders HTML strings in CellRenderer

### ISSUE THREAD

**Issue by Azbola** [ag-grid/ag-grid#5226]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
A CellRenderer that returns an html string displays a string in the grid cell instead of rendering the html.
NOTE: setting suppressReactUi: true does not fix this
NOTE2: This is using AgGridReact, not the .js version

**Expected behavior**
A CellRenderer that returns an html string renders the html in the grid cell (this was the behaviour in v26)

**Please tell us about your environment:**
Any

* **AG Grid version:** 27.3.0

* **Browser:**
All

**Comment by JacobHaitsma** [comment]
I was surprised to learn this behavior exists. For what it's worth, I was able to get rendered HTML using the cell renderer. Would you happen to have a code example?

*Unfortunately*, I was also able to execute Javascript using this feature. This is an XSS vector and should *probably* be removed, or renamed to indicate it's unsafe.

https://plnkr.co/edit/p78TGrz7wdfeGrUc

**Comment by gportela85** [comment]
@Azbola Can you provide a working example?

**Comment by seanlandsman** [comment]
This is unfortunately a breaking change introduced in 27.x. To render html as actual html you'll need to provide a react component that returns jsx (or equivalent), or use a JS class based component that return and html element (not a string).

ie instead of:

`cellRenderer: () => '<div>Hello World</div>'`

you'll need to do something like this:

`cellRenderer: () => <div>Hello World</div>;`

Note that this isn't returning a string now, but rather JSX. You don't need to use JSX but you do need to return an HTML element when using React.
