### ISSUE TITLE
Problem with method ensureIndexVisible

### ISSUE THREAD

**Issue by logrox** [ag-grid/ag-grid#5235]
I ran into a problem with the ensureIndexVisible method.
Even if the row is visible, the table will be moved to the "middle" position.
I presented the problem on plnkr.co by clicking on the button described as "ensureIndexVisible"

[example](https://plnkr.co/edit/ylpqFnQqHeW0JtkA?open=main.ts)

**Comment by gportela85** [comment]
I'm not sure I understand what issue is, in your plunker, the method is passing `middle` as the second parameter, so the row will be positioned in the middle of the grid.

index.htm line 37 - `window.gridApi.ensureIndexVisible(rowIndex, 'middle');`

**Comment by logrox** [comment]
In fact, I did not specify what I meant.
In the documentation [Scrolling](https://www.ag-grid.com/javascript-data-grid/grid-api/#reference-scrolling), it says "if the row is already in view then the grid will do nothing. ".
In my example, however, it does, scrolls to that line, and it shouldn't because the line is visible at index 10

**Comment by gportela85** [comment]
I guess the docs could be a little more specific, `ensureIndexVisible` will do nothing if the row is already in view, but it will be force to move in this case because you passed `middle`. In that case, we understand that simply being visible is not enough, it has to be in the middle of the grid. 

Translate from code to english, one would be: 
- Ensure that index is visible
The other is: 
- Ensure that row is visible and in the middle of the grid.

There are ways you could go around this, for example, call ensureIndexVisible without passing `middle`, see if the grid scrolls, if it does, call again passing `middle`, otherwise just let it be. If you have a customer account, file a support ticket via zendesk for this.

Thanks
