### ISSUE TITLE
@microsoft/signalr high frequency streaming data unable to append in to ag grid

### ISSUE THREAD

**Issue by JimiShah1984** [ag-grid/ag-grid#5325]
I have tried few option but it didn't worked

1) use slice on rowData and assign it to new variable  & then push new row to that new variable 
And at the end  used 'setRowdata(newRowData)' but it didn't come/update ag-grid
2)If I used new or upcoming  row to set in setRowData then its display always single updated row which new row data coming from signalr
3)Also used gridApi.applyTransaction on merge data but didn't worked

Signlar stream gives huge amount of data for eg: in 1 minitues its give almost 10k records

**Comment by JimiShah1984** [comment]
I have tried appytransaction

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this behavior - much appreciated!

We're keen to look into this but we need to be able to reproduce the issue you've described.

Please provide the following (as per our bug template in Github):
1. A live example (plunker, stackblitz) or link to a repo showing the issue
2. A list of steps to follow to reproduce the issue
3. Descriptions of current behavior and expected behavior

We're looking forward to your response to we can investigate this further.

Thank you!
