### ISSUE TITLE
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification

### ISSUE THREAD

**Issue by JoshStockdaleWQ** [ag-grid/ag-grid#5371]
v28 breaks our build. Getting error: "Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification" on build for the React version. 

We think it has something to do with columnDefs. Here is the offending code: 

Object.defineProperty(target, key, {
                set: eval(setterJs),
                get: eval(getterJs),
                enumerable: !0,
                configurable: !1
            })

Attached is error from the browser side
![Screen Shot 2022-07-18 at 8 28 57 AM](https://user-images.githubusercontent.com/109152013/179512104-a5ba9774-0480-4aa8-846b-475c78cc5315.png)

**Comment by rmc-software** [comment]
I think this is a duplicate of this closed issue: https://github.com/ag-grid/ag-grid/issues/5336

**Comment by yagudaev** [comment]
Similarly, I saw something like this from a vite build.

```
npx vite build            
vite v3.0.2 building for production...
transforming (2797) ../node_modules/ag-grid-react/lib/reactUi/jsComp.jsUse of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
✓ 2920 modules transformed.
```

This caused a syntax error in the minified bundle and made the code crash as soon as you open it.

This sucks. It reminds me of the early Angular 1.0 that didn't account for modifications.

Anyway, looks like the code is in charts. So since I don't use charts, I'll switch to the modules approach and exclude it.

Hopefully, this will fix things 🤞. I'll report back.

**Comment by VismaTobbe** [comment]
> v28 breaks our build. Getting error: "Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification" on build for the React version.
> 
> We think it has something to do with columnDefs. Here is the offending code:
> 
> Object.defineProperty(target, key, { set: eval(setterJs), get: eval(getterJs), enumerable: !0, configurable: !1 })
> 
> Attached is error from the browser side ![Screen Shot 2022-07-18 at 8 28 57 AM](https://user-images.githubusercontent.com/109152013/179512104-a5ba9774-0480-4aa8-846b-475c78cc5315.png)

Same error in ^29.1.0 for our vitejs build. When doing ` import("../../../node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.auto.complete.esm.min.js")`

**Comment by cweekly** [comment]
> I think this is a duplicate of this closed issue: #5336

Actually @rmc-software, it's not a dup.
In [5336](https://github.com/ag-grid/ag-grid/issues/5336#issuecomment-1499254390)
@alantreadway said 
"The scenario you are encountering is about compilation/bundling rather than runtime, which is where this issue originated - so is a distinct issue."

I'm running into the same build-time "Use of eval in ..../ag-grid-enterprise.auto.esm.js is strongly discouraged as it poses security risks..."  in v29.3.3.

Please consider re-opening this issue and mitigating use of eval().
Thanks!

**Comment by StephenCooper** [comment]
As an fyi eval will be removed and not present in v30 which is due out in a few weeks time.

**Comment by alantreadway** [comment]
This is the more recently related issue: https://github.com/ag-grid/ag-grid/issues/6437
