### ISSUE TITLE
Cell copy & paste across row group is not working

### ISSUE THREAD

**Issue by nkdweb** [ag-grid/ag-grid#5373]
**Current behavior:** 

1) Consider more than one row groups, select the cells in one row group and another row group by using **Shift key** and copy (CTRL+C) the cell value from both row group.

2) Paste the copied cells to another column by the following scenarios

**Scenario 1:**
Step1: Click on the top of the cell in the row group of another column.
Step2: CTRL + V
Step3: It paste the cell value of only one row group and other copied row group is empty.

**Scenario 2:**
Step1: Select the number of cells to paste using **Shift key** on both row groups of another column.
Step2: CTRL + V
Step3: It paste the cell value of both row groups without any issue.

In older version of ag-grid 19.x copy & paste works in both the scenario's.

**Expected behavior:**

Step1: Click on the top of the cell in the row group of another column.
Step2: CTRL + V
Step3: It should paste the cell value to all row groups which are copied.

**Please tell us about your environment:** Windows, VSCode

* **AG Grid version:** 27.1.0

* **Browser:** Google Chrome

* **Language:** Angular 13.x 

![image](https://user-images.githubusercontent.com/2375291/179531454-e129405a-c4b5-414a-a403-e37beb8d798d.png)

**Comment by kiril-matev** [comment]
Hello @nkdweb !

Thank you for bringing this up with us. 

You're correct in saying the paste operation was previously supported in this scenario. However, as part of the changes in v25.2 to use the ClipboardAPI special handling for this scenario wasn't included and this isn't supported in v25.2 and later. We need to consider this scenario and implement this alongside current clipboard functionality.

We have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-7004 [Clipboard] Allow pasting cell ranges which include group row cells ignoring the group row cells**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by yogeshpaisodeGL** [comment]
Hi @kiril-matev,
Is AG-7004 resolved ?

Thanks!

**Comment by kiril-matev** [comment]
Hi @yogeshpaisodeGL,

Thanks for following up.

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

At this time AG-7004 is not implemented. 

**Please note that we will not update this github issue when this item is implemented.**

**The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thank you for your time!
