### ISSUE TITLE
ag-grid-column not working

### ISSUE THREAD

**Issue by lkotan** [ag-grid/ag-grid#5384]
### I am using vue 3 and typescript. When I try to use ag-grid-column I get an error

![error](https://user-images.githubusercontent.com/63057933/180148753-7524b587-40c6-4acb-8286-ba96f48da192.PNG)
![code](https://user-images.githubusercontent.com/63057933/180148758-35ec9341-3673-42bf-a3cd-007756c80557.PNG)

**Comment by StephenCooper** [comment]
We would recommend that you define your column definitions via the `columnDefs` property on `ag-grid-vue` instead of using the component `<ag-grid-column>`. We believe this results in cleaner code that is easier to maintain and should avoid this issue. 

https://ag-grid.com/vue-data-grid/column-definitions/

**Comment by seanlandsman** [comment]
Fixed by https://github.com/ag-grid/ag-grid/pull/4996 - will be available in our next release.

Note you'll also need to ignore this custom element in your webpack config:

```
    chainWebpack: config => {
        config.module
            .rule('vue')
            .use('vue-loader')
            .loader('vue-loader')
            .tap(options => {
                options.compilerOptions = {
                    ...(options.compilerOptions || {}),
                    isCustomElement: tag => tag === 'ag-grid-column'
                };
                return options;
            });
    }
```

**Comment by lkotan** [comment]
Thank you for your comments
