### ISSUE TITLE
Possibility to disable row deselection

### ISSUE THREAD

**Issue by staticdreams** [ag-grid/ag-grid#5385]
**I'm submitting a ...
```
[ ] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

* **AG Grid version:** 28.0.2

I'm looking to implement something similar to 

```
     node.setSelected(true);
     node.setRowSelectable(false);
```

but to maintain row selected AND disable so that the user is unable to unselect the checkbox next to it, basically forcing him/her to include certain rows into their selection, or rather implying that is row is compulsory. 

Is this feature available  (I have consulted the documentation and github repo already) or have I missed something?

Thanks

**Comment by rmc-software** [comment]
As it happens this feature has just been implemented and will be included in our next release scheduled on 3rd Aug (v28.1)

Reference:

**AG-6873 - [Row Selection] Allow displaying disabled (read-only) checkboxes instead of no checkboxes when the row is not selectable**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/
