### ISSUE TITLE
Can't find stylesheet to import @ag-grid-community/styles

### ISSUE THREAD

**Issue by jochenjonc** [ag-grid/ag-grid#5418]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I was performing the upgrade of the Sass styling to v28 but I constantly got the following error:
```
SassError: Can't find stylesheet to import.
  ╷
1 │ @use "ag-grid-community/styles" as ag;
  │ ^
```

I couldn't figure out what the problem was until I figured out that there was a separate module @ag-grid-community/styles that needs to be installed via npm.

In the documentation I could not find any reference to that additional module, not on any of these pages:

- https://www.ag-grid.com/angular-data-grid/global-style-upgrading-to-v28-sass/
- https://www.ag-grid.com/angular-data-grid/global-style-customisation-sass/
- https://www.ag-grid.com/angular-data-grid/modules/

**Expected behavior**
Maybe the extra npm install shouldn't be required, but then this is a bug because @ag-grid-community/core is missing a dependency.
Or the documentation is missing the fact that @ag-grid-community/styles needs to be installed separatly.

* **AG Grid version:** 28.0.2

* **Browser:** Chrome

* **Language:** SCSS

*  **Framework:** Angular v14

**Comment by StephenCooper** [comment]
Hi @jochenjonc 

Thank you for reporting this - much appreciated! We agree that this should be made clearer in our documentation and we will also look at the package dependencies. Apologies for the time lost in tracking down this issue. 

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7061 Can't find stylesheet to import @ag-grid-community/styles**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-7061) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by seanlandsman** [comment]
Hi,

Version 28.1.0 have AG-Grid has been released, which includes a fix for this issue.

Thank you for reporting this.
