### ISSUE TITLE
Checkbox on not selectable row reappears on scroll

### ISSUE THREAD

**Issue by aurelien-gaillard** [ag-grid/ag-grid#5433]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
[https://plnkr.co/edit/efxNgrJ2o52I7o2Q?open=index.tsx](https://plnkr.co/edit/efxNgrJ2o52I7o2Q?open=index.tsx)

I have modified the example found [here](https://www.ag-grid.com/react-data-grid/server-side-model-selection/?#reference-selection-isRowSelectable).
I have removed the `isRowSelectable` by a `onSelectionChanged` using `setRowSelectable`
The goal is that only rows with same number of gold medals can be selected together

**Current behavior**
After clicking on a row with 1 gold medal, the checkbox stays only for the other rows with 1 gold medal. So far so good.
The bug is that after scrolling a bit down, and back up, the rows that have more than 1 gold medal are still not selectable, but the checkbox is back visually

**Expected behavior**
The checkbox for not selectable row should not appear back after scrolling down and up. (when off window and back in view)

* **AG Grid version:** 28.1.0

* **Browser:**
Chrome

**Comment by aurelien-gaillard** [comment]
Expected behavior: checkbox visible only for row with gold = 1
<img width="482" alt="Screenshot 2022-08-04 at 23 14 56" src="https://user-images.githubusercontent.com/66209993/182954159-13acbb3c-b0ab-4056-a9d6-1fb08508a1b3.png">

Bug after scrolling down and back up (rows out of view and back to view) - All the checkboxes are visible again (the row remains not selectable, but user sees checkboxes)
<img width="465" alt="Screenshot 2022-08-04 at 23 15 23" src="https://user-images.githubusercontent.com/66209993/182954119-6fabc904-71f3-493c-b708-91ac9fbe06d9.png">

**Comment by StephenCooper** [comment]
Hi @aurelien-gaillard,

The method `setRowSelectable` on the RowNode is not intended for external use and will not work as you expect it to due to row virtualisation. This is why scrolling in and out causes the issue to appear. 

You should use the `isRowSelectable` callback approach as I see you had in your example, (just commented out).

We understand that the fact you can see the methods on the RowNode but we would recommend checking our [docs](https://ag-grid.com/javascript-data-grid/row-object/) for the methods that we note as being for public use. We are looking to improve the distinction between public and private methods with respect to RowNode in the future.
