### ISSUE TITLE
Why ignore browsers other than Chrome/Firefox?

### ISSUE THREAD

**Issue by FontEndArt** [ag-grid/ag-grid#5437]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

In Safari, the date filter for column headers doesn't work! But the official website demo is normal! Until I looked through the source code and saw it "**shouldUseBrowserDatePicker**"!

**Expected behavior**

Fix the current performance, support other browsers (such as Safari), and filterParams.browserDatePicker will be added to the official website documentation

**Please tell us about your environment:**  

Don't care!

* **AG Grid version:** 28.0.2

Don't care!

* **Browser:**

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15" = $1

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript >= 4.5

![image](https://user-images.githubusercontent.com/19547121/182794535-db7e838b-9d22-4008-af28-ed1f2cc97a56.png)
![image](https://user-images.githubusercontent.com/19547121/182794559-2eec9dfb-3929-41f8-a110-84d4385d2d6d.png)
![image](https://user-images.githubusercontent.com/19547121/182794598-e52d2e85-91db-45c1-8c89-684f0fcc8540.png)

**Comment by FontEndArt** [comment]
https://github.com/ag-grid/ag-grid/blob/latest/community-modules/core/src/ts/filter/provided/date/defaultDateComponent.ts

**Comment by kiril-matev** [comment]
Hello Ma!

Thank you for this.

The shouldUseBrowserDatePicker property was added as a precaution because there wasn't good support for the Date Input field in browsers other than Chrome and Firefox. However, more recently Safari have added partial support for Date fields that is equivalent to Firefox in July 2021.

This is why we agree that displaying a date picker for Safari will be valuable and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference and description:
**AG-7124 [Column Filter] Add support for displaying date picker for Safari browser**

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by FontEndArt** [comment]
I will keep watching, thanks~
