### ISSUE TITLE
Tab reloading

### ISSUE THREAD

**Issue by LukeA2023** [ag-grid/ag-grid#5448]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Created a filterable aggrid table with a download button to download filtered results. Upon switching tabs and switching back, the Aggrid table resets its view to the original dataframe however it does not change the input dataframe for the download. I believe it is because it is not rerunning because no new information is passed but how do I prevent the Aggrid table from showing unfiltered data despite it outputting filtered data

Current behaviour.
Displaying unfiltered data and outputting filtered data. 
Expected behaviour. If possible back this up with our docs/examples if possible
Displaying the same data that it is outputting 

**Current behavior**

**Expected behavior**

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this behavior - much appreciated!

We're keen to look into this but we need to be able to reproduce the issue you've described.

Please provide the following (as per our bug template in Github):
1. A live example (plunker, stackblitz) or link to a repo showing the issue
2. A list of steps to follow to reproduce the issue
3. Descriptions of current behavior and expected behavior

We're looking forward to your response to we can investigate this further.

Thank you!
