### ISSUE TITLE
Integrated charts value formatter

### ISSUE THREAD

**Issue by jagoral** [ag-grid/ag-grid#5452]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

On the ag-grid demo page the integrated charts the values respect `valueFormatter` option declared for the column. However in the current version on ag-grid, the plain `value` is presented. This is especially important when a finance chart is created and it's important to format the values for the end user.

<img width="1653" alt="image" src="https://user-images.githubusercontent.com/26148834/183290683-be6a06de-015c-49f4-b134-8851d5c81b17.png">

**Providing a Reproducible Scenario**
1. Open [plunkr](https://plnkr.co/edit/4BFhT4Jzhwp7n45L?open=index.tsx)
2. Select all data
3. Create an integrated chart (for example Bar -> Grouped chart)

**Current behaviour**
Values on Y axis and the tooltips are not formatted. 

**Expected behavior**
Values on Y axis and the tooltips uses same formatting as declared in `valueFormatter`  `numberGood` column option. 

**Please tell us about your environment:** macOs Big Sur

* **AG Grid version:** 28.1.0

* **Browser:** 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'

* **Language:** all

**Comment by StephenCooper** [comment]
Hello @jagoral 

Thank you for bringing this up with us. The functionality you described wasn't part of the requirements when we built this feature. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference: **AG-4479 [Chart] Allow displaying grid cell formatted value in the chart tooltip renderer**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-4479) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

**Comment by StephenCooper** [comment]
For reference the demo is using `chartThemeOverrides` to format the tooltips and labels. You can see examples of this on our documentation under [Chart Customisations](https://ag-grid.com/javascript-data-grid/integrated-charts-customisation/#top)

**Comment by jagoral** [comment]
Thanks @StephenCooper  :) I know the `chartThemeOverrides` option, but I couldn't figure it out how to override the tooltip properly. Is the source code of the demo publicly available?

**Comment by StephenCooper** [comment]
It's in this [file](https://github.com/ag-grid/ag-grid/blob/e8c321d07108418498e2af430f0e7c60857d6516/grid-packages/ag-grid-docs/documentation/src/mainPageDemo/Example.jsx#L852).
