### ISSUE TITLE
Bar series highlight draws over line series segments/points

### ISSUE THREAD

**Issue by juliancarrivick** [ag-grid/ag-grid#5475]
**I'm submitting a ...**  (check one with "x")

- [x] bug report => see 'Providing a Reproducible Scenario'
- [ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
- [ ] support request => see 'Requesting Community Support'

**Current behavior**
Bar series highlight now draws over line series, which regressed in ag-chart 6/ag-grid 28 (I think it is from AG-6887). This behaviour is demonstrated on the [gallery](https://www.ag-grid.com/javascript-charts/gallery/combination-of-different-series-types/).

When the line series point lies at the same x value you can't show the tooltip (deselect one of the series on the gallery example to see this)

**Expected behavior**
ag-chart 5/ag-grid 27 highlighted the bar chart sections, but the line segments were still visible & the tooltip was able to be activated by hovering over the visible point.

**Please tell us about your environment:**

* **AG Grid version:** 28.1.0 / ag-chart 6.1

* **Browser:** All browsers

* **Language:** N/A

**Comment by alantreadway** [comment]
Thank you for reporting this - we have been tracking several related issues in the 6.0.0 + 6.1.0 release and I'm glad to report they are being worked on now for inclusion in the next release:
- AG-7053 - [Charts] When hovering a grouped/stacked column series item in a combination chart, a line/area series get rendered over the non-hovered column series but behind the hovered columns.
- AG-7101 - [Charts] Combination chart markers which overlap columns/bars can't be selected/highlighted.

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-7053/AG-7101) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by juliancarrivick** [comment]
Great, thank you!
