### ISSUE TITLE
Disable Column Menu (suppressMenu) as long as any cell has been edited

### ISSUE THREAD

**Issue by vincentole** [ag-grid/ag-grid#5477]
Hello, I have the following situation:

I have difficulties configuring the column menu.
If you have any solution other than what I explain below I would be very happy to hear about it.

I am using SSRM and integrated the column filters manually.
Thus, whenever a filter is changed the new data is loaded from the backend.

The problem arises, when the user has made changes to the cells and then tries to filter to search for a product.
All changes will be lost.

Therefore, I want to disable the column filter (`suppressMenu`), when the user has edited any of the cells.
This is not that easy, since the `undoRedoStack` is cleared when the `colDef` is changed.

A partly working solution is to set a new `colDef` with `suppressMenu` enabled inside the `onCellEditingStarted` callback.
However, this does not comprise cell editing via the `fillHandler`. Thus, changing cells via the fill handler will leave the column filter enabled.

I tried to update the `colDef` inside the `fillOperation` function, however, the `undoStack.clear()` function is is invoked after the editing is applied. This means that the user cannot undo any of the fill handler changes.

I saw that there is a fill handler starts event. Is there a way to access it, similar to the `onCellEditingStarted` callback?

https://github.com/ag-grid/ag-grid/blob/deb61d9e5f12489539d96ea631d822cdd94da51e/community-modules/core/src/ts/undoRedo/undoRedoService.ts#L250

I will be very happy about help and suggested solutions.
Thank you and best regards,
vincentole

**Comment by kiril-matev** [comment]
Hello @vincentole!

Thanks for reaching out.

We use github issues for bug reports only. You've submitted a support question instead of a bug report and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.

Thank you for using AG Grid!
