### ISSUE TITLE
Support/feature request: alwaysFillRowBlankSpace in resizable-columns tables

### ISSUE THREAD

**Issue by omers4** [ag-grid/ag-grid#5498]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
The issue reproduces in every ag-grid table where the columns are resizable.
For example, [here ](http://54.222.217.254/example-runner/vanilla.php?section=javascript-grid-resizing&example=column-resizing&generated=1&grid=%7B%22theme%22%3A%22ag-theme-balham%22%2C%22noStyle%22%3A0%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3Anull%7D)
Resize the last column and see there is a blank space between the end of the row to the end of the container.

**Current behavior**
When we resize the last column to a smaller size than the container, the row is narrower than the container, which looks buggy because the border of the row is cut in the middle and the background color is also cut (there is a blank space between the row border and the container border).

![image](https://user-images.githubusercontent.com/23039408/185895893-65123530-3187-47f5-b3de-a304fd21e772.png)

**Expected behavior**
The row should look as if it ends in the end of the container and not before, even if the row is actually shorter.
For example, the border color and the hover behavior of the row should continue until the end of the container, even if the row ends before.
I tried different ways to do that by code (giving flex:1 to the last column for example), but couldn't find a way. Is there a way I missed of doing that?
If not, is it possible to add a dedicated boolean prop that controls it? for example, `alwaysFillRowBlankSpace`.
I'm sure it can help for many devs here.

Something like this:
![image](https://user-images.githubusercontent.com/23039408/185897089-e793d14b-247f-46f4-b5b7-983ee0e927cf.png)

**Please tell us about your environment:**
MacOS Monterey, WebStorm, yarn

* **AG Grid version:** X.X.X
28.1.0

* **Browser:**
All

* **Language:** all

Thank you very much! Omer

**Comment by kiril-matev** [comment]
Hi @omers4,

Thank you for reaching out.

Yes, the closest you can get to the appearance you need is to use flex:1 on last column. This way the last column will stretch to fill the remaining space in the viewport. However, as the column menu button is aligned to the right it will be far from the column header text.

Currently there's no way to achieve the exact functionality you've described and shown in the screenshot. We're not planning on implementing the suggested rendering because it makes it look like there is a column with an empty header text on the right, while there isn't one. This would confuse users who would try access the cells in this empty column and be surprised that no cells are getting focused when they click there.

This is why we believe the suggested row rendering will be confusing and undesirable for users.

I hope the current functionality of AG Grid can help you implement the needed functionality in your project. 

Thank you for your time!

**Comment by omer-shlifka** [comment]
Hi,
I already tried to do flex:1, but it doesn't help with the case the user is resizing the column to be smaller than container...
Do you have any other idea maybe on how to fix this?
Thanks

**Comment by kiril-matev** [comment]
Hi Omer,

Thanks for following up.

The AG Grid column layout cannot be customized in the way you've described. I hope you can use the functionality provided by AG Grid in your application.

Thank you!

**Comment by rmc-software** [comment]
Hi,

Here is a workaround that you can try: https://plnkr.co/edit/3lpkXRXmbxuZRlHQ

Hope this helps.
