### ISSUE TITLE
When I click on the row in ag-grid, the checkbox should not change, but the row should be selected

### ISSUE THREAD

**Issue by lkotan** [ag-grid/ag-grid#5514]
In the image below, when I click on any cell in the row, I want the row to be selected (for the user to focus on the row), but the value of the checkbox box should not change. The value of the checkbox should only change when the checkbox is clicked. Is there a way to do this?
`const rowClicked = (event: any): any => {
  event.node.isSelected() ? event.node.setSelected(false) : event.node.setSelected(true)
};`
![tag-ag-grid](https://user-images.githubusercontent.com/63057933/187151373-df230be3-65e6-42b1-8687-5e181de3d456.PNG)

**Comment by StephenCooper** [comment]
We use github issues for bug reports only. You've submitted a support question instead of a bug report and we're happy to let the AG Grid community respond here.

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
