### ISSUE TITLE
A11y: Invoke Parent button is not clickable

### ISSUE THREAD

**Issue by eviv3k** [ag-grid/ag-grid#5531]
The “Invoke Parent” button is not clickable under the attachments section using NVDA, JAWS, and Voiceover.

Please refer the below link for the live demo video of the issue
https://www.awesomescreenshot.com/video/10897273?key=e777b3dd6ccaa4e5de0987a1be18cc5d

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

* **AG Grid version:** 27.3.0

* **Browser:** All

* **Language:** [all]

**Comment by kiril-matev** [comment]
Hi @eviv3k,

Thanks for reaching out.

When using custom cell renderers, focus logic cannot be implemented as built-in by the grid because AG Grid doesn't know what's inside the custom cell renderer and has no way of knowing which element (in your case button) to focus when the cell gets focus. 
 
Only the developer who built the custom cell renderer has knowledge of which elements are interactive/meaningful to the user and should get focus. This is why the developer needs to provide logic to move focus through the elements inside the cell renderer when the cell is focused.

Please see how focus logic in a custom cell renderer is implemented here:
1. Open
https://stackblitz.com/edit/focus-cell-items-s6efhl?file=index.js
2. Click the top-left grid cell - Michael Phelps
3. Press TAB key
**Actual & Expected**: Button 1 in the COUNTRY column cell gets focused
4. Press TAB key
**Actual & Expected**: Button 2 in the COUNTRY column cell gets focused

Please follow the same approach to implement the necessary keyboard focus logic in your custom cell renderer.

Thank you for using AG Grid!
