### ISSUE TITLE
How to build ag-grid-react? or how to inject component after header row?

### ISSUE THREAD

**Issue by WesleyYue** [ag-grid/ag-grid#5545]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I'm using ag-grid-react, and I want to inject a button to add a new column, like the image below: 
![image](https://user-images.githubusercontent.com/5280818/189588906-b839fe18-f865-40eb-8446-145a5b5857c7.png)

It didn't seem like any of the exposed component allows me to do this, so I have been exploring two options:
1. Bring ag-grid into my monorepo and fork/modify it
2. Inject a component with appendChild by finding the ref of the ag-header-row element and creating another react root.

(1) seems cleaner so I'm trying that. I cloned ag-grid via git subtree to my repo, and I am trying to load it in my create-react-app. Here is what I have done so far:

1. git sub-tree add ag-grid
2. npm link the local ag-grid/grid-packages/ag-grid-react to my monorepo node_modules
3. make a modification to the files in community-modules/react/src
4. run `npm run build` in grid-packages/ag-grid-react
5. run `npm start` in my create-react-app monorepo

I have figured out that grid-packages/ag-grid-react copies the src from community-modules/react, but I can't figure out how to load the changes. Anytime I make a modification to community-modules/react/src and run the above steps, no changes propagate to my create-react-app. It almost feels like something is being cached but I can't figure out where.

**Comment by StephenCooper** [comment]
Hi @WesleyYue,

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/ If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
