### ISSUE TITLE
[bug] row background-color flicker when updating rows with sorting

### ISSUE THREAD

**Issue by Frozik** [ag-grid/ag-grid#5572]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/rayY1U0qnFh4ydyi

**Current behavior**
Background flicker on some updates - https://youtube.com/shorts/Y676uM7jR0A

**Expected behavior**
The background color of the rows should be consistent

**Please tell us about your environment:**
MacBook Pro (16-inch, 2021) Apple M1 Pro

* **AG Grid version:** 28.1.1
ag-grid-enterprise@28.1.3

* **Browser:**
Chrome Version 105.0.5195.125 (Official Build) (arm64)

* **Language:**
all

**Comment by StephenCooper** [comment]
Hi,

The sorting that is taking place during the updates causes this visual flicker. Maybe turning on the animate rows feature would give a better visual clue that rows are moving about? I do understand that this may not be your desired behaviour for your application.

However, due to the way rows are rendered and sorted following this update we would not be able to get the completely static background rows that you are after.
