### ISSUE TITLE
how to keep editing when Other Cell Focus

### ISSUE THREAD

**Issue by haomashroom** [ag-grid/ag-grid#5575]
![image](https://user-images.githubusercontent.com/14905047/191698240-fddb55d9-f362-4200-b539-cb4aee4ee29e.png)
I want custom components to control themselves！！！

**Comment by StephenCooper** [comment]
We use github issues for bug reports only. You've submitted a support question instead of a bug report and we're happy to let the AG Grid community respond here.

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.

<hr>

However, if you want the behavior that you describe, (which is not supported by the grid) you may need to look into making a custom cellRenderer that supports editing.
