### ISSUE TITLE
React AG Data Grid - Column Menu on right click

### ISSUE THREAD

**Issue by CorsinSauber** [ag-grid/ag-grid#5591]
By default the column menu of a ag grid table appears when you click on the menu icon in the column header, however the icon of this column menu is very large. Is there a way that the column menu appears on right click (similiar to the context menu in the cells)?

I had a look at the documentation, however i was not able to achieve this. https://www.ag-grid.com/archive/26.0.0/javascript-data-grid/column-menu/#customising-the-general-menu-tab

I assume it has to something with the postProcessPopup settings or with showColumnMenuAfterMouseClick(colKey, mouseEvent).
However I do not know how to implement it. Is there a example? Thanks

**Comment by StephenCooper** [comment]
Hi @CorsinSauber,

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.

**Comment by StephenCooper** [comment]
You may find this example helpful as it shows a custom header that uses react and handles right click, to show the menu. 
https://plnkr.co/edit/hkQY6zPGCJPYuOr5?open=index.tsx
