### ISSUE TITLE
Pin bottom custom aggFunc column value 

### ISSUE THREAD

**Issue by jigarGangwal12** [ag-grid/ag-grid#5633]
I have added one column to my ag grid and this is related to pivot. I want to pin this column value when the filter applies.

aggFunc: (params: any) => {
          var amtTotal = 0;
          params.values.forEach((value: { totalAmt: number }) => {
            if (value && value.totalAmt) {
              amtTotal += value.totalAmt;
            }
          });
          var total = (amtTotal / 100000);
          return {
            totalAmt: amtTotal,
            toString: () => { return (amtTotal) ? (total).toFixed(2) : '' }
          }
        },

I use this code to pinned bottom above column value 
 result["pivot_2"] = {
      totalAmt: 152,
      toString: () => { return '1565' }
    };

How can i pinned this column value in bottom please provide answer.

**Comment by StephenCooper** [comment]
Thanks for reaching out.

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
