### ISSUE TITLE
Where can I find the changelog for ag-charts?

### ISSUE THREAD

**Issue by spyro2000** [ag-grid/ag-grid#5667]
Sorry for bothering you, I just couldn't find the changelog for ag-charts (only for ag-grid as a whole). Every site is pointing to this repo instead. I'll just want to know e.g. the changes from 6.1.0 to 6.2.0. Could you provide me a link?

Many thanks. :)

**Comment by StephenCooper** [comment]
Hi @spyro2000,

No need to apologize because this is not clear and we are working to improve this. 6.2 of charts matches release 28.2 of the grid.

The chart 6.2 changes are listed under 28.2. So go to this link and put `Charts` into the search box. 

https://ag-grid.com/changelog/?fixVersion=28.2.0

**Comment by spyro2000** [comment]
Thank you!
