### ISSUE TITLE
Duplicated code in ag grid

### ISSUE THREAD

**Issue by ali0707** [ag-grid/ag-grid#5673]
I just imported the ag grid library export excel, I used the excel style everything is functional but
I had a problem in sonar that the code is duplicated  
So I tried to reduce it by creating a function to return the :
numberFormat: {
format: "#,##0.00"
}
And call it in the excelStyles
But the format of number in excel changed when i did the export 
Example:
It was returning 204,727,737.82 in excel
But when I tried to do it in the function 
It returns 
A weird number 204,727,7+E12

const excelStyles = [
   {
id: 'id1',
numberFormat: {
format: "#,##0.00"
}
   },{

id: 'id2',
**---> Repeated 15 time for example **
}
]

Any solution?
Thank you 😊

**Comment by StephenCooper** [comment]
Thanks for reaching out.

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. If you believe there is an issue then please provide a reproducible example for us to look at. We prefer plunker if possible based off one of our existing examples. 

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.

**Comment by ali0707** [comment]
@stephenCooper > Thanks for your message, 
And yes i have the license of ag grid
Ps:the problem not resolved yet

**Comment by StephenCooper** [comment]
Then I would recommend that you produce a reproducible code sample that will enable us to reproduce the error that you are seeing. Please provide the full error details to. Then raise this through your Zendesk account as this seems like it will require more work to resolve.
