### ISSUE TITLE
Full Table Editing ✍️

### ISSUE THREAD

**Issue by Sotatek-TiepLe** [ag-grid/ag-grid#5674]
```
[x] support request 
```
I hope to be able to edit directly, tab between input cells on the table
Selection is exactly where I want it to be. Instead of singleClick, dblClick

Look forward to your feedback. Thank !

![image](https://user-images.githubusercontent.com/88995057/195274723-6156e27c-889a-4aed-8757-1fa4cb7bd75e.png)

**Comment by StephenCooper** [comment]
Hello!

Thanks for reaching out.

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
