### ISSUE TITLE
closeOnApply does nothing if no "apply" button is present

### ISSUE THREAD

**Issue by sersorrel** [ag-grid/ag-grid#5678]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

If a filter lacks an "apply" button, `closeOnApply` has no effect. For repro, see [this plunker](https://plnkr.co/edit/PCVZ6aOQ7YkrLVPO?open=main.js&preview); the "athlete" column has both "reset" and "apply" buttons, and either of them will close the filter popup, but the "age" column has only a "reset" button, which will not close the filter popup.

**Expected behavior**

`closeOnApply` should, as documented, apply to "apply", "reset", and "cancel" buttons regardless of whether or not there is an "apply" button in the filter popup.

To be fair, the documentation is a little inconsistent about this:
- the [tests](https://github.com/ag-grid/ag-grid/blob/585596d7cdd761eadf138eba5c577d662ac23754/community-modules/core/src/ts/filter/provided/providedFilter.test.ts#L98) appear to only check the behaviour of the "apply" button
- the [jsdoc documentation](https://github.com/ag-grid/ag-grid/blob/138837af77eed91f921c6f813e20da136181d434/community-modules/core/src/ts/filter/provided/providedFilter.ts#L30-L36) only states that the popup "will be closed immediately when the Apply or Reset button is clicked" (no mention of "cancel")
- but the [online documentation](https://www.ag-grid.com/vue-data-grid/filter-provided/#apply-clear-reset-and-cancel-buttons) is pretty clear that the intended behaviour is that "the filter popup will be closed immediately when the filter is applied, reset or cancelled"

This actually contradicts the following comment in `onBtApply`:

https://github.com/ag-grid/ag-grid/blob/138837af77eed91f921c6f813e20da136181d434/community-modules/core/src/ts/filter/provided/providedFilter.ts#L309

IMO `onBtReset` and `onBtCancel` also need to check `this.providedFilterParams.closeOnApply` and call `this.close` if it's true.

**Please tell us about your environment:**

* **AG Grid version:** my project uses 28.1.1, but I assume the repro on plunker uses the latest version

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

* **Language:** n/a

**Comment by kiril-matev** [comment]
Hello,
 
Thank you for bringing this up with us. 
 
The current behavior is correctly described here:
https://www.ag-grid.com/vue-data-grid/filter-provided/#reference-IProvidedFilterParams-closeOnApply
 
However, as you pointed out the column filter documentation contradicts this because it doesn't mention the role of the APPLY button in the behavior of the RESET button as described above. This is why we added a feature request in our backlog to update the documentation to clarify this.
 
You can track it with this reference:
**AG-7455 [Docs] Update documentation on column filtering when closeOnApply=true and Apply button is shown**
 
You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!
