### ISSUE TITLE
Table's horizontal scroll is partially cut off when page is zoomed out

### ISSUE THREAD

**Issue by TheLegion** [ag-grid/ag-grid#5724]
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request
```

**Reproducible Scenario**

1. Open https://www.ag-grid.com/example
2. Change window width so there is a horizontal scroll in the table
3. Zoom out page (50% is perfect for reproducing)

**Current behavior**
Horizontal scroll doesn't fit in it's area and is partially cut off

**Expected behavior**
Horizontal scroll doesn't get cut off and is shown fully

**OS**: Windows 10
**AG Grid version:** 28.1.1
**Browser:** Google Chrome 106.0.5249.119
**Language:** all

**Comment by TheLegion** [comment]
It looks like this:

![image](https://user-images.githubusercontent.com/4846822/198257840-f43fcc29-d6fe-4152-b2aa-ed53a626d157.png)

Scroll becomes normal after the page is refreshed, but breaks again after zoom is changed.

**Comment by kiril-matev** [comment]
Hello @TheLegion!

Thank you for reporting this and using AG Grid - much appreciated!

You are correct - at this time, browser zoom isn't fully supported in all cases by AG Grid. We need to add this across all the elements of the grid to ensure it works correctly.

We have a feature request in our product backlog to track this work:
**AG-2550 [Cell Rendering] Add support for scaling and zoom in/out of the browser**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by TheLegion** [comment]
Hello @kiril-matev!

Thank you for an answer, I will watch for the new releases.
