### ISSUE TITLE
Cell content read out in SR as clickable even though they are just text

### ISSUE THREAD

**Issue by evgeniyefimov** [ag-grid/ag-grid#5736]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Just open link below with screen reader like NVDA or Voice Over in a **screen reader mode**.
https://plnkr.co/edit/vx1YhtiS3RyKNh6H?open=app%2Fapp.component.ts
Read text cell with screen reader like in a screenshot below (I used NVDA), screen reader announces cell as clickable.
![image](https://user-images.githubusercontent.com/11611433/199247295-6575625d-836c-4066-a0c4-5c0de7268618.png)

**Current behavior**
All text content in each cell is saying it’s clickable in SR (which they are not) - they are simply text content.

The root cause of this issue these two event listeners (keydown, mousedown)
![image](https://user-images.githubusercontent.com/11611433/199248104-37ef88e6-2f4b-49ca-a1be-666dde5d1ef3.png)

If we remove them, then screen reader reads text cells perfectly fine without announcing "clickable".

**Expected behavior**
Do not read text cells as "clickable"

**Please tell us about your environment:**

* **Screen Reader:** NVDA 2022.2.4

* **AG Grid version:** 28.2.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

* **Language:** TypeScript 4.3.5

**Comment by kiril-matev** [comment]
Hello @evgeniyefimov!

Thanks for reaching out and for using AG Grid.

You mentioned that the grid cells are text content - this isn't entirely correct. A HTML table of values contains text content while AG Grid is a highly interactive element that has individually focusable cell elements (with keyboard and mouse) inside a scrollable virtualized list. As each of the elements is focusable they need to have a mousedown event listener.

You mentioned that when the keydown and mousedown listeners are removed from a grid cell, it is no longer announced as clickable anymore. However, removing these event handlers prevents the cells from being styled as focused after being clicked with the mouse. As the cells can be individually focused when clicked, they are clickable and are correctly announced as such. 

This is why the behavior you're describing is expected behavior.

**Comment by evgeniyefimov** [comment]
Hi @kiril-matev 

Thanks for response.

From blind people's point of view these 'clickable' announcements are weird. That's why we use `suppressCellFocus` and `suppressContextMenu` options for our ag-grid, but events are still there even when we disable cell focus with keyboard and mouse (we use custom tab navigation). Would be great if ag-grid can detect if cell can be focusable or not and do not add mousedown event listeners if it's not.

**Comment by kiril-matev** [comment]
Hi @evgeniyefimov,

Thanks for this response.

I've built a test case to illustrate this:
Steps to repro:
1. Open NVDA
2. Open
https://plnkr.co/edit/xtTvhul3itZBm634?open=main.js&preview
3. Click above grid
4. Press INSERT+SPACE to enter focus mode
5. Press TAB key to focus ATHLETE column header
**Announcement**: column 1 clickable athlete
6. Press ARROW_DOWN key multiple times to move across column headers until you reach the top row cell
**Announcement**: clickable row 2 athlete column 1 clickable Michael Phelps

You're seeing this behavior because going into browse mode, NVDA is bypassing the AG Grid built-in focus handling and keyboard navigation and navigating the DOM of the grid without taking into account the specific element structure AG Grid uses. In this case, AG Grid has no control over what is being done and how an end-user interacts with the grid. 

At this point, NVDA is treating the grid as a plain text table which AG Grid isn't. AG Grid is a highly-interactive, virtualised container for elements representing rows and columns which supports multiple row and column containers for pinned columns/pinned rows/sticky group rows, etc which may render the cells of a single row across different virtualised containers. Navigating through these structures requires custom keyboard interaction logic which is provided as built-in by AG Grid to deliver accessibility support. The NVDA browse mode ignores this custom navigation logic and navigates the DOM directly as if it's a plain text table without any row/column virtualization, which is causing this behavior.

This is why we recommend not using browse mode in NVDA to ensure the end users get the full accessibility support provided as built-in by AG Grid.

Please let me know if you have any questions.
