### ISSUE TITLE
User entered operators(>,<,=,>=,<=) should be displayed on ag grid number filter

### ISSUE THREAD

**Issue by niyafra** [ag-grid/ag-grid#5761]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**

When the user enters the operators(>,<,=,<=,>=) in the ag grid number filter,the data gets filtered out but those operators get removed as i am replacing those because of the NaN issue

**Expected behavior**

When the user enters the operators(>,<,=,<=,>=) in the ag grid number filter,the data gets filtered out but i need those operators to be displayed in the number filter even after filtering

* **AG Grid version:** 28.1.1

**Comment by AndrewGlazier** [comment]
Hello!

Thanks for reaching out.

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
