### ISSUE TITLE
How can I change AG Grid's 'aria-label' in the Grid Cell?

### ISSUE THREAD

**Issue by cjduncana** [ag-grid/ag-grid#5799]
In the same spirit as https://github.com/ag-grid/ag-grid/issues/4209, I want to add a label in the Grid's cell for when I have non-text content.

For example, I have a column that shows operating systems if the item in the row supports them.
<img width="520" alt="Screenshot 2022-11-17 at 5 37 01 PM" src="https://user-images.githubusercontent.com/1977082/202574885-5f892cc0-a57b-43fa-8f21-22dd1c900fa6.png">

Right now, a screen reader can't read what's in the cell, so I want to provide a label, but I haven't found out how with React's AG Grid.

**Comment by kiril-matev** [comment]
Hello @cjduncana,

Thanks for reaching out.

You can add the appropriate accessibility-related attributes to announce non-textual content in grid cells using a custom cell renderer.

Please see this here:
1. Open
https://plnkr.co/edit/pa7xmOwECcAmqMOL?open=main.js
2. Open NVDA
3. Click a cell in the PRODUCT NAME column
**Actual & Expected**: Cell value announced
4. Press the RIGHT ARROW key to focus a cell in the COUNTRIES SOLD column
**Actual & Expected**: Country names announced 

In order to generate the announcement, we're using a custom cell renderer for the non-textual (image) columns. The custom cell renderer sets the accessibility attribute (aria-description) of the parent cell to the actual cell value. 

Please use the same approach to implement this in your project.

Thank you for your time and for using AG Grid!
