### ISSUE TITLE
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by yashwanth2714** [ag-grid/ag-grid#5826]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
* Project migration from Vue2 to Vue3.

**Current behavior**
We are getting the below error when creating a custom status bar component in our project.

![ag-charts-vue3](https://user-images.githubusercontent.com/36370530/204299654-7c6ccc6b-ff73-4bb3-91e1-e9de44bcb343.png)

**Expected behavior**
There should not be any errors.

We followed this example: https://www.ag-grid.com/vue-data-grid/component-status-bar/#example-custom-component

**Please tell us about your environment:**
O.S: Windows 10
IDE: VS Code
Package Manager: npm

* **AG Grid version:** 28.2.0

* **Browser:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'

* Vue: 3.2.37
* ag-grid-vue3: 28.2.0
* ag-charts-vue3: 6.2.0
* ag-charts-community: 6.2.0
* TypeScript: 3.7.3

**Comment by StephenCooper** [comment]
Hi @yashwanth2714,

As our example is working it is hard for us to advise what the issue is here. If you can provide a reproduction then we would be able to investigate this.

**Comment by yashwanth2714** [comment]
@StephenCooper  - Here is the repo link [https://github.com/rangaraajv/AG-Grid-Status-Bar](https://github.com/rangaraajv/AG-Grid-Status-Bar)

Status Bar is not working in that example.

**Comment by StephenCooper** [comment]
The SideBar is an enterprise feature and your repo is not including `ag-grid-enterprise`. I see that was included in your app though. 

```
    "ag-grid-community": "28.0.2",
    "ag-grid-vue3": "28.0.0",
```

**Comment by yashwanth2714** [comment]
@StephenCooper - We've updated the repo. Please check now.

Note: I removed the license key since it is a public repo. To reproduce the console error, add the license key.

**Comment by seanlandsman** [comment]
Hi,

There are a couple of things here - first off you're mixing major and minor versions of the ag-grid libaries. You should always ensure the major and minor versions match (ie ag-grid-community 28.2.x works with ag-grid-enterprise 28.2.x and ag-grid-vue 28.2.x).

Secondly the problem here is this warning in the console:

`runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Component provided template option but runtime compilation is not supported in this build of Vue. Configure your bundler to alias "vue" to "vue/dist/vue.esm-bundler.js".`

The solution create a file called `vue.config.js` in the root of your project with the following contents:

```
const path = require('path');

module.exports = {
    configureWebpack: {
        resolve: {
            symlinks: false,
            alias: {
                vue$: path.resolve(__dirname, 'node_modules/vue/dist/vue.esm-bundler.js'),
            }
        }
    }
};
```

thanks

**Comment by yashwanth2714** [comment]
Sure. I will keep it in mind. Thanks a lot for the solution!
