### ISSUE TITLE
p-inputnumber inside cell-editor component is not focusing while editing a cell in grid

### ISSUE THREAD

**Issue by gokul-18** [ag-grid/ag-grid#5829]
Framework-used:
Angular 13 and 14

**Steps to reproduce**
1)   add this to cell editor component of html.
<p-inputNumber [(ngModel)]="value9" inputId="currency-us" mode="currency" currency="USD" locale="en-US"   
      [pAutoFocus]="true">
     </p-inputNumber>
2)add this to cell edtor component of ts.
   ngAfterViewInit() {
       // focus on the input
       setTimeout(() => this.input.element.nativeElement.pAutoFocus = true);
   }
      
**Current behavior**
 I am using cell editor component and inside that I am using p-input number(prime ng component), I am using singleclickedit property, while clicking the cell its not focusing the P-inputnumber, I have used ngfterviewinit lifecycle hook also for appending autofocus, but still it not works.

**Expected behavior**
When I single click on the cell, it should be focus to the cell and user will start editing to the input(without clicking again form mouse or enter key).

**Please tell us about your environment:**
  Windows, visual studio code, npm.

* **AG Grid version:** 27.0.0

* **Language:** [all | TypeScript 4.5 | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
Hi @gokul-18 

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

We do not believe this is directly an issue with AG Grid. If you believe that it is AG Grid that is causing the issue then feel free to open with a reproduction so that we could investigate this as a bug. 

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/
