### ISSUE TITLE
QA: SSRM data filtering

### ISSUE THREAD

**Issue by mkosmida** [ag-grid/ag-grid#5851]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Is there a way to filter out data or hide some rows after the data is fetched from the server?
In my case I have no control over the external data source but I need to be able to filter out specific rows

Example:
datasource contains 10000 rows, my cacheBlockSize (using infinite scroll) is set to 100. Out of those 100 rows only 90 should be displayed on the grid. When the user scrolls another 100 rows are being fetched but they should be "attached" at position 91.
the current behavior will make ag-grid render the next portion of data at row 101 and leaves out "loading" rows
I want to either hide the extra rows or not render them at all

**Please tell us about your environment:**

* **AG Grid version:** any

* **Browser:** any

* **Language:** [all]

**Comment by StephenCooper** [comment]
Hi @mkosmida,

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

It looks like you have an AG Grid Enterprise license or are evaluating AG Grid Enterprise so please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
