### ISSUE TITLE
AgChartsReact Treemap Breaks After Changing Options with ag-charts-community@6.2.1 (latest)

### ISSUE THREAD

**Issue by drewwiens** [ag-grid/ag-grid#5859]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
SIMPLEST REPRODUCIBLE EXAMPLE: https://stackblitz.com/edit/react-ts-agchartsreact-treemap-bug?file=App.tsx
`Error: Cannot read properties of undefined (reading 'toFixed')` when options is changed, and the plot is non-functional after that

**Expected behavior**
No error. Reproduce by entering "ag-charts-community@6.2.0" into the "Enter package name" box in the lower left in the Stackblitz above

**Please tell us about your environment:**
Chrome browser

* **AG Grid version:** X.X.X
Error occurs with ag-charts-community 6.2.1. The error does not occur when we use ag-charts-community 6.2.0.

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

* **Language:** TypeScript

**Comment by alantreadway** [comment]
Hello Drew,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-7662 - [Charts] Treemap break when changing options in 28.2.1 / 6.2.1.

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Regards,
Alan
