### ISSUE TITLE
Question about DOM Virtualisation and detail rows

### ISSUE THREAD

**Issue by evgeniyefimov** [ag-grid/ag-grid#5868]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/6jXOc3mtAcbyPFZr

Hi. Is it possible to have DOM Virtualisation for detail rows? Pls, check a link above. As you can see there are a lot of rows and all of them have detail rows, the thing is that DOM virtualisation works properly fine for master rows, but even if a detail row is not visible it's kept in the DOM.

**Comment by StephenCooper** [comment]
We use github issues for bug reports only. You've submitted a support question instead of an issue and it looks like you should have an AG Grid Enterprise license or are evaluating AG Grid Enterprise so should be using support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.

However, you maybe looking for this:

https://ag-grid.com/angular-data-grid/master-detail-grids/#detail-grid-lifecycle

**Comment by StephenCooper** [comment]
I would suggest that you raise a support ticket for this Enterprise feature so that we can allocate time to investigating this further to help decide if this is expected behaviour or if it is a bug.
