### ISSUE TITLE
[Bug] Set Filter- get values function reference not changing

### ISSUE THREAD

**Issue by knevo** [ag-grid/ag-grid#5872]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behaviour.**
When changing the reference of a function in colDef.filterParams.values,
the function is not updated and instead the old reference of the function is being used.
[Plunkr](https://plnkr.co/edit/W5IKwbar9WzQ0Zgc?open=index.jsx)
Reproduce it by opening the country set filter, see the initial date log.
then change the date and open the country set filter again. 
You will see the initial date log instead of the new date

**Expected behaviour**
When the set filter values function is changed i expect ag grid to use the most recent function.

**Please tell us about your environment:**
MacOS, VScode, npm

**AG Grid version:** 28.1.0

**Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

**Language:** all

**Comment by StephenCooper** [comment]
Hi @knevo,

Thank you for bringing this up with us. I have added your use case to an existing request for this feature.  

You can track it with this reference:
AG-5854 [React] Make colDef.filterParams a reactive property

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!
