### ISSUE TITLE
autoSizeAllColumns + onFirstDataRenderer don't work properly in React 18

### ISSUE THREAD

**Issue by denisgursky** [ag-grid/ag-grid#5877]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
[codesandbox](https://codesandbox.io/s/ag-grid-autosize-react18-uidpv5?file=/src/_app.js)

**Current behavior**
I noticed this while upgrading to React 18. The same code works fine in React 17.  [codesandbox react 17](https://codesandbox.io/s/ag-grid-autosize-react17-7y17gs?file=/src/_app.js)

Columns are squeezed when there're a lot of grids on the page. The issue is less likely to appear when the number of grids is smaller.
![image](https://user-images.githubusercontent.com/6468871/207206111-a57f1e95-5b0d-4c34-bdc9-074eccb50aca.png)

**Expected behavior**

Columns should look more like this

![image](https://user-images.githubusercontent.com/6468871/207206494-91e44009-9935-4fbf-94fc-f1924f2d8785.png)

**Please tell us about your environment:**

MacOS, VS Code, Yarn, Next.js

* **AG Grid version:** X.X.X
28.2.1

* **Browser:**

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'
```

**Comment by StephenCooper** [comment]
It looks like this comes down to the new `createRoot` function. The grids work as expected in v18 with the following code in index.js

```
import { render } from "react-dom";
import { App } from "./_app";

render(<App />, document.getElementById("root"));

```

https://codesandbox.io/s/ag-grid-autosize-react17-forked-92m47v?file=/src/index.js

But does not work when the code is 

```
import {createRoot} from 'react-dom'
import {App} from './_app'

createRoot(
  document.getElementById('root')
).render(<App />)
```

I will raise a ticket for us to investigate this further.

**Comment by AndrewGlazier** [comment]
Hello,

This has been raised before, and we are already tracking it in our pipeline with the following reference and description:
AG-7518 - [React v18] Calling columnApi.autoSizeColumns(false) within onFirstDataRendered incorrectly ignores header cell width

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

I would recommend signing up for ag-Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Regards,
