### ISSUE TITLE
AgGrid React checkbox selection by default

### ISSUE THREAD

**Issue by vikzkr** [ag-grid/ag-grid#5882]
I have around 15k records usecase with row selection as checkbox and it's under a overlay menu , how to preserve the state of selected checkbox on menu closed.

On close of menu , and when I reopen, the selected checkbox should be marked

Using AgGrid enterprises version -21.2.2

**Comment by StephenCooper** [comment]
Hi @vikzkr, 

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license lease submit a support ticket: https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
