### ISSUE TITLE
The `readOnly` property of `filterParams` of `ColDef` can not be updated properly.

### ISSUE THREAD

**Issue by tngx** [ag-grid/ag-grid#5916]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**

The `readOnly` property of `filterParams` of `ColDef` can not be updated properly. I tried to set `filterParams: {readOnly: edit}` to the `defaultColDef` and/or `columnDefs`, where `edit` is a React state variable. The filters didn't become read-only when `edit === true` or become modifiable when `edit === false`. Please check the plnkr example below.

**Expected behavior**

When setting  `filterParams: {readOnly: true}` to the column definition, I expected that the filters become read-only, which was not the case.

**Please tell us about your environment:**

Please check this plnkr example: [https://plnkr.co/edit/rOGx6knbSfsZuGOE?open=index.tsx&preview](https://plnkr.co/edit/rOGx6knbSfsZuGOE?open=index.tsx&preview)

* **AG Grid version:** 28.2.0

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

* **Language:** [TypeScript 4.8.4 | ES5]

**Comment by StephenCooper** [comment]
Thank you for bringing this up with us. 

The functionality you described wasn't part of the requirements when we built this feature. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-5854 [React] Make colDef.filterParams a reactive property**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-5854) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by tngx** [comment]
Thanks Stephen for your quick reply! I think that feature would be very helpful, so I look forward to having this in the future release. Thanks a lot!
