### ISSUE TITLE
api.getServerSideGroupLevelState missing lastRowIndexKnown

### ISSUE THREAD

**Issue by aurelien-gaillard** [ag-grid/ag-grid#6014]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Current behavior**
`api.getServerSideGroupLevelState()[0].lastRowIndexKnown` is always undefined

**Expected behavior**
In version 28, it always returned a boolean

I used this feature to find the row count with `rowModelType: 'serverSide'`
The lastRowIndexKnown was the only option I found to know if the grid was in the initial loading status.
And `api.getDisplayedRowCount()` is returning 1 when the datasource is loading, while I need 0.

My previous implementation:
```js
const rowCount  = api.getServerSideGroupLevelState()[0]?.lastRowIndexKnown
      ? api.getDisplayedRowCount()
      : 0
```

* **AG Grid version:** 29.0.0

**Comment by AndrewGlazier** [comment]
Hi,

Thanks for reporting this - this was an unintended change from v28, as such I'm going to create a bug ticket.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-7836 - [SSRM] getServerSideGroupLevelState missing properties

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks for bringing this up with us.
