### ISSUE TITLE
「question」 how to export all database resource use aggrid'export csv

### ISSUE THREAD

**Issue by Valar103769** [ag-grid/ag-grid#6026]
current  is  server  pagination .page =2 perPage =10 , i  need  refetch data by set perPage =10000 , it  means  all database source  ,but  i  dot  want  modify current  row Data, it just to  download 

do you know  what  i say  , has  some  good  way  to  complete  it  ?  thanks

**Comment by StephenCooper** [comment]
We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
