### ISSUE TITLE
Drag/drop does not work as expected in safari

### ISSUE THREAD

**Issue by ka-ramba** [ag-grid/ag-grid#6034]
[X] bug report => see 'Providing a Reproducible Scenario'

**Current behavior**
The example page at: https://www.ag-grid.com/javascript-data-grid/drag-and-drop/ works OK in Chrome. But in Safari the dragged div is missing and only shows the content ( text in this case)

**Expected behavior**
Drag and Drop should work the same in all supported browsers.

Edit: Actually drag/drop on Safari is very broken. Often the the drag starts not in the cell the mouse is clicked. Try dragging the bottom cells in the above example ( last one with custom drag renderer) several times. Sometimes the value is shown while being dragged sometimes no indication on the screen at all. Other example also seem buggy. However the example "Two Grids" where the drag starts outside of the grid works much better that may point that the bug is in ag-grid not Safari

**Comment by ka-ramba** [comment]
I see a similar issue was reported back in 2019  https://github.com/ag-grid/ag-grid/issues/3454  and unfortunately was closed as not reproducible. Please look at the bottom example, it is very jarring

**Comment by StephenCooper** [comment]
Hi @ka-ramba,

I can reproduce what you are showing and I can see that this is consistent back to v26 of AG Grid which leads me to think that there has been a change in the Safari browser that we need to investigate.

Can you please confirm the version that you are using.

**Comment by ka-ramba** [comment]
for ag-grid package.json in Angular setting shows:  ^28.2.1
My OS: Ventura 13.1
Browser: Safari: Version 16.2 (18614.3.7.1.5)

**Comment by ka-ramba** [comment]
> I can reproduce what you are showing and I can see that this is consistent back to v26 of AG Grid which leads me to think that there has been a change in the Safari browser that we need to investigate.
> 
Just to give you some pointers since the issue was first reported back in 2019 https://github.com/ag-grid/ag-grid/issues/3454 it is unlikely that it was caused by recent Safari updates and may have existed prior to v26

**Comment by kiril-matev** [comment]
Hello @ka-ramba,

We looked into this with the product team and confirmed this is not a bug with AG Grid. Instead, this is a behavior specific to Safari that needs to be targeted in the custom renderer code. 

Browsers differ in how they display the "image" automatically created for the Drag Element. In this case, Safari does not take the color of the parent element (the row), into account. This is why you need to add a background-color to the custom dragSourceRenderer to ensure that Safari displays it. 

In order to fix this for Safari specifically, you need to create your own image and use dataTransfer.setDragImage() to set it.

See this implemented here:
https://plnkr.co/edit/Pe1J3myOS78OzTsT?open=main.js

Note that when you drag a row in Safari you can see the ghost element background color just like in Chrome.

Please use this approach to update your custom renderer code to support Safari.

Thank you for using AG Grid!
