### ISSUE TITLE
Inability to tab to previously focused cell, after clicking to change focus

### ISSUE THREAD

**Issue by Tristan2357** [ag-grid/ag-grid#6038]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

https://stackblitz.com/edit/ag-grid-angular-hello-world-6srwdg?file=src/app/app.component.ts
Steps to reproduce:

- Enter full row edit mode
- Change focused cell using a mouse click
- Try to refocus previously focused cell using tab/shift+tab

**Current behavior**

It is not possible to focus the cell using tab and the focus gets "stuck" in the previous cell

**Expected behavior**

 Tab should move focus correctly

**Please tell us about your environment:** Angular

* **AG Grid version:** 29.0.0 & 28.2.1

* **Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

* **Language:** all

**Comment by StephenCooper** [comment]
I have tried your example and can see the issue that you have reported. However, when I remove the custom editor component the error also goes. I.e when using the AG Grid editor there are no issues with navigating after changing the focus. 

So I believe that the issue lies in the handling in your custom editor. As such I am going to close this ticket as I do not believe there is an issue with AG Grid. 

If you disagree feel free to come back to me.
