### ISSUE TITLE
CSV export: flip x-axis and y-axis

### ISSUE THREAD

**Issue by riwu** [ag-grid/ag-grid#6058]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I have an AgGrid displaying data in the following format (first row is the column names):
```
Metric, Jan, Feb, ... Dec
metricA, 2, 5, ...
metricB, 4, 6, ...
...
```

When the user exports the grid into CSV, I want the format to be:
```
Date, metricA, metricB, ...
Jan, 2, 4, ...
Feb, 5, 6, ...
...
```

Is there a way to accomplish this via AgGrid's built-in csv export features?
I have looked into `processCellCallback`, `processHeaderCallback` but doesn't look like they can be used to accomplish this.

**Comment by StephenCooper** [comment]
Hello @riwu,

We use github issues for bug reports. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
