### ISSUE TITLE
Mobile click events not working with Angular Custom Headers

### ISSUE THREAD

**Issue by leafymiggs** [ag-grid/ag-grid#6060]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**

Mobile click events are not working with custom headers.  This can be seen with the first example on the angular component header documentation page:  https://www.ag-grid.com/angular-data-grid/component-header/

This is reproducible on a real Google Pixel phone, as well as Windows Chrome Mobile Emulation mode.  Clicking the header in the first example only works on desktop browsers.  Clicking the header on a mobile device, or in chrome mobile emulation does nothing.

**Expected behavior**

Mobile should work the same as desktop.

**Please tell us about your environment:**

Pixel 6, Chrome 
Windows 10, Chrome

* **AG Grid version:** X.X.X
28.2.0

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Mozilla/5.0 (Linux; Android 13; Pixel 6 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36

**Comment by StephenCooper** [comment]
Hi @leafymiggs,

This would be the expected behaviour as the touch events have not been handled by the custom header used in this example. We have not added all the matching behaviour as our provided header as then this example would be very complex. 

If you want to get an idea of how we support touch events in our provided header then you could take a look at this [component](https://github.com/ag-grid/ag-grid/blob/latest/community-modules/core/src/ts/headerRendering/cells/column/headerComp.ts#L186).

The idea of this example is to show how to setup a custom header but it is not our intention to make it support every required scenario.
