### ISSUE TITLE
Master - Detail Grid (Suppress Keyboard Navigation on Detail Grid)

### ISSUE THREAD

**Issue by VenkatSagi9** [ag-grid/ag-grid#6088]
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'

**Current behavior**
I am using ag-grid-enterprise for Mater Details Grid, I have a scenario like when I click on master grid row it should expand and display the detail grid. I tried to disable cell focus on details grid using suppressCellSelection options and disabled cell focus on  detailed grid body but still I can able to focus on details grid headers using tab key. I have added below code for current behavior. 

https://plnkr.co/edit/WvzrDn28WhjEHatR?open=main.js&preview

**Expected behavior**

I want to navigate between the master grid rows and bypass tab navigation on details grid headers/body.

Please tell us about your environment:
React

AG Grid version: ^28.2.1

Browser:
Chrome

Language: [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
Hi @VenkatSagi9,

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.

**Comment by NikitaIT** [comment]
Hi @VenkatSagi9, additional method provided in https://github.com/ag-grid/ag-grid/issues/6115#issuecomment-1431633089

> I think that you may be able to achieve what you want by implementing custom navigation. See this [example](https://ag-grid.com/javascript-data-grid/keyboard-navigation/#example-custom-keyboard-navigation).
