### ISSUE TITLE
Wrong calculation of the position of ag-dnd-ghost  when body has css zoom

### ISSUE THREAD

**Issue by adv-zl** [ag-grid/ag-grid#6095]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Current behavior
I set body style zoom to 80%. After this when I try to move column, library starts calculate position of .ag-dnd-ghost and exclude this changes in positions by zoom 80%. It causes wring position of this element and when I try to move last column, ag-dnd-ghost apeears to far to the left from my cursor.

https://plnkr.co/edit/kah3Z4MfirM2JQuT

Expected behavior

You have to add to  private positionGhost(event: MouseEvent) additional check if body has zoom style and then calculate correct position of ag-dnd-ghost.
![Plunker - Master Detail Grid Navigation Issue with Tab key 2023-01-28 12-03-23](https://user-images.githubusercontent.com/16443377/215260356-80d40653-0120-4d0b-8899-e0f91a99492e.png)

Please tell us about your environment:
React

AG Grid version: ^28.2.1

Browser:
Chrome

Language: [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
Hi @adv-zl,

Thank you for reporting this and using AG Grid - much appreciated!

You are correct - at this time, browser zoom isn't fully supported in all cases by AG Grid. We need to add this across all the elements of the grid to ensure it works correctly.

We have a feature request in our product backlog to track this work:
AG-2550 [Cell Rendering] Add support for scaling and zoom in/out of the browser

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!
