### ISSUE TITLE
How to limit the number of chart types (Chart Range) in Context menu?

### ISSUE THREAD

**Issue by SGMariaKap** [ag-grid/ag-grid#6105]
Hello, 

I am looking for a way to limit the number of chart types the user could select from in the Context Menu (Chart Range).
Apparently, the similar ticket has been closed, however I have not managed to find the answer to it. 

Thanks

_Originally posted by @makinggoodsoftware in https://github.com/ag-grid/ag-grid/issues/5212#issuecomment-1152353245_

**Comment by StephenCooper** [comment]
Hi @SGMariaKap,

We only use Github for bug reports. I am sure if you raise this via your Enterprise account that someone will be able to help you out on this Enterprise feature. 

I will add the managed-by-community label in the meantime.

**Comment by uvtzxpm** [comment]
I don't see a way to do it via ag-grid options, hopefully they add some config for it at some point.

So for now, you can patch ag-grid using something like [patch-package](https://github.com/ds300/patch-package) (assuming you use node_modules). For example, you could make a small patch to comment out some chart types [in here](https://github.com/ag-grid/ag-grid/blob/a37508fb3fafeffe172ccb5ffafef5344fa02ff2/enterprise-modules/menu/src/menu/menuItemMapper.ts#L273).

It's not as bad as it sounds, I've been forced to do some patches because they're a bit slow with bug fixes/releases lately. It just makes upgrading version a bit annoying if the code near your patch changes (have to remake patch).

**Comment by StephenCooper** [comment]
Please do not apply a patch when you can do this as follows. 

```
     {
      // custom item
      name: 'Chart Cust',
      action: () => {
        console.log('Checked Selected');
      },
       subMenu: [
                        'rangeColumnChart',
                        'rangeXYChart',
                        'rangeAreaChart',
                        'rangeHistogramChart',
                        'rangeCombinationChart'
                    ],
      icon:
        '<span class="ag-icon ag-icon-chart" unselectable="on" role="presentation"></span>',
    },
```

**Comment by StephenCooper** [comment]
While the above workaround works for the context menu it does not limit what chart types a user could pick from the Chart Tool Panel. This is where AG-7949 comes in. It will automatically match the chart context menu items to the configuration provided to `chartToolPanelsDef`.

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-7949) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!
