### ISSUE TITLE
how to calculate height ? 

### ISSUE THREAD

**Issue by Valar103769** [ag-grid/ag-grid#6118]
my calculate way always has deviation

```jsx
const multiHeader = columns.some((item) => item.children?.length)

<div
        style={{
          height: data?.length
            ? Math.min(
                (data?.length || 0) * 42 + (multiHeader ? 48 * 2 : 48),
                42 * 11 + (multiHeader ? 48 * 2 : 48)
              )
            : 400,
        }}
      >...</div>
```

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/36926073/216222373-5c21ff5f-28ef-4674-9eb7-8de556286a07.png">

**Comment by StephenCooper** [comment]
We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
