### ISSUE TITLE
Sort groups by another column

### ISSUE THREAD

**Issue by davidnormo** [ag-grid/ag-grid#6137]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

* **AG Grid version:** 28.2.1
* **Browser:** Chrome, Safari...
* **Language:** ES6/7

We have a requirement to sort the group rows by another column.

An example scenario we have a grid of products which we group by manufacturer name and issued date. We want to first sort the manufacturer group rows by price descending, then sort the issued date group rows by issued date, then sort the leaf nodes price. This would effectively give the user a view of the manufacturer with highest prices.

So far I've not found how to sort the group rows by another column, even sorting the group rows is a little problematic. 

1. The `comparator` function on the columnDef is only called with leaf node values
2. The `comparator` function on the autoGroupColumnDef is also only called with leaf node values
3. The `postSortRows` function again is only called with leaf node values

#125 looked hopeful but it seems others are also having trouble.

Thanks

**Comment by StephenCooper** [comment]
Hi @davidnormo,

We use github issues for bug reports only. You've submitted a support question instead of an issue.

I assume you have used this [doc](https://ag-grid.com/javascript-data-grid/grouping-group-order/) page to get to where you are currently. 

If you do reach out to support you will need to provide a reproduction the shows what you are trying to achieve and why its not possible with the current set of features. 

<hr/>

It seems like you have an AG Grid Enterprise license or are evaluating AG Grid Enterprise so please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
