### ISSUE TITLE
Adding new rows at bottom on paste, when the table is in descending order rewrites the first rows

### ISSUE THREAD

**Issue by rinconsebastian** [ag-grid/ag-grid#6140]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behavior in one of our examples in the docs: If you have a table enabled to add new rows at the bottom when pasting data that exceeds and, the table is in descending order. When you paste data the bottom rows are overwritten.
- using the above-provided plunker past the following three values at the bottom cell of the first column.
- values
a
b
c

- plunker: [Plunker](https://plnkr.co/edit/BGcE4EmcMrcNGY9h?open=app%2Fapp.component.ts&preview)

- the previous plunker is a fork of this [original example](https://www.ag-grid.com/angular-data-grid/clipboard/#example-pasting-extra-rows)

**Please tell us about your environment:**

OS: WIndows 11
IDE: Vs Code

* **AG Grid version:** 28.2.1 

* **Browser:** Chrome

* **Language:** [Angular| TypeScript| ES6/7 | ES5]
*

**Comment by StephenCooper** [comment]
I am not sure I can reproduce what you are describing. When I open the table and have it sorted, I can copy a row and paste it at the bottom or the top. 

You might need to provided a screen recording or exact steps to follow to reproduce the issue.

**Comment by kiril-matev** [comment]
Hi @rinconsebastian,

Please note this isn't a bug - this is expected behavior because of the way you've implemented your custom logic in processDataFromClipboard callback. You need to update your code to correct the behavior.

Here's a description of the behavior you've reported - please use this level of detail to provide test cases in the future when submitting issues.

Steps to follow:
1. Open
https://plnkr.co/edit/0AYw8on8wiZ1dMI0?open=main.js
2. SHIFT+CLICK the top 2 grid rows
3. Press CTRL+C
4. Click the last row
Actual & Expected: 4th row is MISSY FRANKLIN
5. Press CTRL+V
Actual: 
1/ Last row overwritten
2/ New row inserted at bottom of grid
3/ 4th row is NATALIE COUGHLIN
Expected: 
1/ Last row overwritten
2/ New row inserted at bottom of grid
3/ 4th row is MISSY FRANKLIN

This isn't an issue with AG Grid but caused by your code in **processDataFromClipboard** callback, which does the following:
1 - Intercepts the clipboard paste to add new rows, which will add the new row "Natalie Coughlin" in the correct spot (just before "Missy Franklin"
2 - Returns an array in the processDataFromClipboard which causes the row that is currently focused and the row below to be replaced.

So, the row is added to the correct place and then two rows at the bottom get replaced.

If you want just one row to be overwritten, please return only one item in the **processDataFromClipboard** callback. In other words, any row you add to the rowsToAdd array should be removed from the data array.

Thank you for your time and for using AG Grid!
