### ISSUE TITLE
Bug: Grid Role is incorrect

### ISSUE THREAD

**Issue by harish-prakash** [ag-grid/ag-grid#6157]
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request
```
**Current behavior**
The grid body has `role="treegrid"` attribute. It used to be `role="grid"` attribute till v28. Treegrid according to mdn is only meant for grids whose rows may be expanded but it doesn't make sense when a grid implementation has no groups.

Change seems to have been made in https://github.com/ag-grid/ag-grid/commit/7d2fc7841d474faac1f35907fe225b0191ea51b6

**Expected behavior**
Use `role="treegrid"` where there are groups and use `role="grid"` when there are no groups.

* **AG Grid version:** 29.0.0

**Comment by kiril-matev** [comment]
Hello @harish-prakash,
 
Thank you for bringing this up with us. 
 
The functionality you described wasn't part of the requirements when we built this feature as there are many potential scenarios where a grid is grouped but it doesn't look like grouped to the end-user. This is why we have added a feature request in our backlog to track this requirement and implement it in the future so the full set of potential scenarios can be considered.
 
You can track it with this reference:
**AG-8014 [Accessibility] Allow grouped grid to have role="treegrid" while flat grid has role="grid"**
 
You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!

**Comment by frank1russo** [comment]
I do not consider this a feature request. This is definitely a bug. A flat grid should not have a role of treegrid. That is wrong based on WCAG guidelines. Please consider changing it to a bug.
