### ISSUE TITLE
[css classes] cellClass with singleClickEdit duplicates classes on every focus

### ISSUE THREAD

**Issue by Bodom78** [ag-grid/ag-grid#617]
A grid with editable cells that have cellClass definitions duplicates the classes on every focus when singleClickEdit is enabled.

Here is a modified example from the site to highlight the issue: https://jsfiddle.net/tvtuz6sq/1/

Here is an example of the Firebug DOM inspector and multiple focuses: 

![cellclass-duplication](https://cloud.githubusercontent.com/assets/139152/12090518/c8da9ffc-b343-11e5-9a7b-1ebfd70bbbe8.jpg)

**Comment by ceolter** [comment]
thanks. will take a look.

**Comment by Bodom78** [comment]
@ceolter Further testing shows it happens regardless of singleClickEdit. 

Double clicking around multiple cells, slowly you will start to notice classes duplicating.

It's just more consistent with singleClickEdit enabled.

And welcome back from your holiday!

**Comment by ceolter** [comment]
@Bodom78  thanks for the welcome back!!!

As a workaround, you can consider using cellClassRules, as far as i remember, it is more robust with regards adding / removing classes.
```
eg cellClassRules = {
   'my-class-black-background': 'true' // expression is true, ie always use this class
}
```

**Comment by Bodom78** [comment]
@ceolter Excellent, cellClassRules works well. I overlooked that property and it will defiantly be useful down the road.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-95

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
