### ISSUE TITLE
agGrid. Highlighting the entire row when pressing the down (up) arrows and selecting a row with an event when pressing Enter

### ISSUE THREAD

**Issue by didoshakra** [ag-grid/ag-grid#6186]
agGrid.Is it possible to do something like this: 1. So that when moving through the rows with the down and up arrows, the row is highlighted (as when moving the mouse). 2. So that when the Enter key is pressed, an event occurs (like a mouse click) to which selectedRowState can be applied? Thank you very much.
In my opinion, it would be good if it worked by default when editable=false
This is especially useful when using the agGrid as a reference table when selecting data to populate another table, because operators mostly work with the keyboard, not the mouse.

**Comment by StephenCooper** [comment]
Hi @didoshakra,

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

It sounds like you should be able to achieve what you want through our grid api methods and events as outline in our documentation.

<hr>

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.

**Comment by didoshakra** [comment]
Thanks for the answer! I'm currently testing agGrid with languid use in development. But there are still a few things that I can't do in agGrid and it doesn't allow me to move forward. Because there should be a lot in the development of the table!

**Comment by StephenCooper** [comment]
I have a quick look and this should hopefully be a good starting point for your feature. https://plnkr.co/edit/8eUW61hgJ84ydAH5?open=main.ts

**Comment by didoshakra** [comment]
Thank you very much for the solution. This suits me, although I had a different idea: when moving, make a light highlight of the line, without its selection, as when moving with the mouse, but only when pressing Enter, take some actions, including selection. But at this stage it will satisfy me too. Thank you again! 
   p.s. Could I address one more question with you about positioning on a row after updating the data? Add as a new issue?
