### ISSUE TITLE
Ag-Grid Group column id's

### ISSUE THREAD

**Issue by liranhr** [ag-grid/ag-grid#6187]
Hi, I'm tryin to get all id's names from Row Group after clicking on 'Pivot mode' and it gives me just the name of 'Group'.

![image](https://user-images.githubusercontent.com/62378984/219942512-ae04061f-3629-40c9-8a9b-ce2a6b078ed6.png)
![image](https://user-images.githubusercontent.com/62378984/219942530-4f0966bb-e8e7-43ce-8571-ec20f08df4df.png)

There is any way to get the name of 'Item'?

**Comment by StephenCooper** [comment]
Hi @liranhr,

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. However, as this is an enterprise feature I would suggest using your AG Grid Enterprise license to submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
