### ISSUE TITLE
Changing multi select behavior

### ISSUE THREAD

**Issue by ameyms** [ag-grid/ag-grid#6217]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Current default behavior of AG-Grid's row selection feature is if the grid level checkbox is in "Indeterminate" state, and we click the checkbox, it goes into "All Selected" state. 
I want to change it so that on clicking the checkbox (while in indeterminate state), all selections should be cleared.
Is there a prop already for this behavior?

**Please tell us about your environment:**
Mac OS

* **AG Grid version:** 28.2.1

* **Browser:**
Chrome

* **Language:** TypeScript

**Comment by kiril-matev** [comment]
Hello @ameyms,

Thank you for bringing this up with us. 

The checkbox selection mode order you listed isn't currently supported by AG Grid. We have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-6831 [Selection] Allow checkbox to follow a different selection order - indeterminate->unchecked->checked**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
