### ISSUE TITLE
HTML errors

### ISSUE THREAD

**Issue by Elysiome** [ag-grid/ag-grid#6223]
```
[x] bug report
[] feature request
[] support request
```

# Introduction

While validating my HTML page with https://validator.w3.org/nu/#textarea, I noticed that the Ag Grid library had many HTML errors.

![HTML errors](https://user-images.githubusercontent.com/59090546/221816017-5b4f7923-ccd5-4dfc-8828-e36e0864d0ae.png)

# Reproducible scenario

Just use any grid.

# Possible solutions

- From error `3.1` to `3.12`: we could use `data-*` attributes that are valid and recommended.
- For the error `4`: we could use a `span` instead of a `div`.

# Environment

- **AG Grid version:** 29.1.0
- **Browser:** all
- **Language:** all

**Comment by kiril-matev** [comment]
Hello @Elysiome!

Thank you for using AG Grid and for reporting this!

As per your instructions, I provided a link to one of our website documentation examples to the HTML validator. However, it didn't output any issues.

Follow the steps below to reproduce this:
1. Open
https://validator.w3.org/nu/#textarea,
2. Focus the URL input
3. Paste https://www.ag-grid.com/examples/range-selection/range-selection/packages/vanilla/index.html
4. Click CHECK button
**Actual & Expected**: HTML is valid - test results only show 3 info boxes with advisories but no actual issues.

We ran the pages below from our documentation samples through the HTML validator but couldn't get the issues you listed:
https://www.ag-grid.com/examples/grouping-multiple-group-columns/show-opened-groups-many-columns/modules/vanilla/index.html
https://www.ag-grid.com/examples/tree-data/group-agg-filtering/modules/vanilla/index.html
https://www.ag-grid.com/examples/pivoting/state/modules/vanilla/index.html

As you can see the standalone AG Grid examples have valid HTML. This indicates the the invalid HTML appears to be in your application code and these issues get flagged in AG Grid instead.

Please provide a live example (a plunker, stackblitz, etc) which uses AG Grid so that when we run it through the HTML checker it produces the issues you listed.

Looking forward to your response.
