### ISSUE TITLE
columnApi.resetColumnState() is breaking function-based aggFunc, with no way to recover

### ISSUE THREAD

**Issue by jcairney-viv** [ag-grid/ag-grid#6227]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
We have an enterprise license, but do not have credentials to log in to Zendesk.

In our code we had a need to call `resetColumnState()` to overcome some changes to the column list which were not being picked up.  But we've had to look for another way since we just started using direct functions on the aggFunc property of columns, and those stop working whenever we call `resetColumnState()`.

I would like to be using the built-in string aggFuncs more, but because valueFormatter() doesn't run on aggregated values, I cannot (https://github.com/ag-grid/ag-grid/issues/2396).

**Plunker:** https://plnkr.co/edit/Z6tvwPZPdLDmhW8I?open=main.js

**Instructions:** Click the Kill Aggregations button in the Plunker.

This issue seems like a duplicate of AG-4122 (https://github.com/ag-grid/ag-grid/issues/3784), which your Change Log dashboard indicates was fixed in v23.1.0, but which appears to not be fixed.

**Current behavior**
Calling `gridOptions.api.columnModel.resetColumnState();` permanently breaks direct function-based aggregation.

I would expect `gridOptions.api.refreshClientSideRowModel('aggregate');` to restore the aggregates but it does not.

**Expected behavior**
Either function-based aggregates should work without intervention after calling `resetColumnState()`, or calling `refreshClientSideRowModel('aggregate')` should restore them to working.

* **AG Grid version:** 29.1.0

* **Browser:**

Chrome

* **Language:** ES6/7

**Comment by StephenCooper** [comment]
If you are having issues with your AG Grid Enterprise license, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you so that your request will get answered quicker.

**Comment by StephenCooper** [comment]
Raised internally with reference https://ag-grid.zendesk.com/agent/tickets/26303 if you want to track it when you get your access resolved.

**Comment by AndrewGlazier** [comment]
Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-8141 - api.resetColumnState() breaks columns with aggFuncs supplied as functions

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks for bringing this up with us.

Regards,
