### ISSUE TITLE
ValueGetter returns any

### ISSUE THREAD

**Issue by lifeiscontent** [ag-grid/ag-grid#6246]
The type seems correct, but is there anyway to stop having the no-implicit-any rule in ESLint complain for valueGetter in a column definition? We're having to cast every value to make it explicit in our react project

**Comment by NikitaIT** [comment]
1. Show where and how you see the error. I have never had this error in this place with `no-implicit-any rule`.
2. This shouldn't be a problem in your project. You can also define functions as methods. Then you won't need to specify the return value.

There is no quick good fix from ag-grid's side.
- in fact, any return value in the type system must be specified explicitly when defining
- perhaps we could make this value a separate generic parameter, but there is another reason for this - we want to call valueGetter somewhere explicitly, this is necessary in very rare editing cases, generally not applicable

### Low cost Solution

We can specify `unknown` instead of `any`, despite the fact that the return value is used after the call, by returning `any` we actually indicate that the function **must** return a type no less than `any`. This is impossible by definition, so functions should never return any. This is an undeniable typing error.

This applies to all ag-grid interfaces, not only ValueGetter.

**Comment by StephenCooper** [comment]
Can you provide an example of code that is requiring you to apply the cast?
