### ISSUE TITLE
Scroll-linked effects warning

### ISSUE THREAD

**Issue by fredz5** [ag-grid/ag-grid#6334]
In Firefox, a warning is displayed in the developper tool console when using the ag-grid horizontal scrollbar.

Step to reproduce:

- Open the FireFox developper tool console
- use the horizontal scrollbar and scroll to right (just scroll).

Here is the complete warning message in the console:

_This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features!_

The problem can easily be reproduced in Firefox on ag-grid official website and scrolling to right https://www.ag-grid.com/react-data-grid/scrolling-scenarios/

![Capture d’écran, le 2023-03-16 à 17 38 52](https://user-images.githubusercontent.com/10453927/225758465-047f29f8-8302-4752-b332-3faa3d85b115.png)

This warning don't seems to cause problem using ag-grid though

**Comment by StephenCooper** [comment]
Hi @fredz5,

This is fired due to the scroll linking between the grid body and the header cells. We listen for horizontal scroll events on the grid body to then keep the headers in line as they are implemented in separate dom trees. We are aware of the potential downsides to this approach but that is outweighed by the flexibility and features we can support with this approach. 

Thanks for reporting but as you say the grid works despite this warning.
