### ISSUE TITLE
Balanced groups with SSRM do not work

### ISSUE THREAD

**Issue by nwrahnema** [ag-grid/ag-grid#6342]
**I'm submitting a ...**
```
[x] bug report
```

According to the docs, https://www.ag-grid.com/angular-data-grid/grouping-unbalanced-groups/#example-balanced-groups, rows without group value should be grouped in a "(Blanks)" section. However, I am unable to recreate this when using SSRM: 
https://plnkr.co/edit/zx6sTIhsWu4PKCNj?open=main.ts, receiving the error ```AG Grid: null and undefined values are not allowed for server side row model keys```

**AG Grid version:** 29.1.0

**Comment by StephenCooper** [comment]
Hi @nwrahnema,

As the error suggests the SSRM does not support blank keys unlike in our grouping for Client Side Row Model due to the fact that keys are required to load data from the server and the blank values are not suitable for this. 

If you want further help with this enterprise feature then please use your AG Grid Enterprise license to submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.

**Comment by nwrahnema** [comment]
The docs are a bit misleading then (https://www.ag-grid.com/angular-data-grid/grouping-unbalanced-groups/). 
> The unbalanced group feature is not supported when using the Server SideRow Model (SSRM)
This somewhat implies that "balanced groups" are supported by SSRM
