### ISSUE TITLE
How to sticky header for layout :autoHeight

### ISSUE THREAD

**Issue by vaynevayne** [ag-grid/ag-grid#6421]
i know `layout:normal` can sticky header , 
but i use  `layout :autoHeight`  ,also need sticky header when long content, 

I use css to fix it, this is the implementation code, please help me to assess whether there are potential problems? Or are there other ways to do it?

```jsx
.ag-root.ag-layout-normal,
.ag-root.ag-layout-auto-height,
.ag-root-wrapper {
  overflow: unset;
}

.ag-header {
  position: sticky;
  z-index: 200;
  top: 3.5rem;
}
```

**Comment by StephenCooper** [comment]
Hi @vaynevayne,

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license please submit a support ticket: https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
