### ISSUE TITLE
Eval security risk warning when bundling with Vite

### ISSUE THREAD

**Issue by saschagysel** [ag-grid/ag-grid#6437]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

I am getting the following warning message by Vite (everytime) when trying to bundle AG Grid Enterprise in Vite (in a Laravel 10 installation) with the command "npm run build":

![image](https://user-images.githubusercontent.com/58490316/230430881-35346b1d-ca9f-471d-bd8a-e5c1b1ec3bb8.png)

It is still bundling ok and AG Grid is working, but the error is a bit concerning.

**Comment by dfravel** [comment]
I've been seeing this warning for at least a few weeks. I've ignored it since it doesn't seem to impact the build or the functionality, but we have a new person leading our DevOps team and he's raised this as a concern

FYI - current versions in package.json:

"ag-grid-community": "^29.2.0",
"ag-grid-enterprise": "^29.2.0",
"ag-grid-vue3": "^29.2.0",

**Comment by alantreadway** [comment]
Hi,

I can confirm that the the use of `eval()` in Standalone Charts is uninteresting from a security perspective, we're using it to 'compile' optimised get/set functions for change-detection based upon baked-in configuration options (specified as part of a TypeScript decorator), so there is zero chance this could be abused through any sort of user or even configuration input.

As this is likely to be an increasingly observed warning in the community, as of the next release of Standalone Charts (which is likely to be 30.0.0 (Grid) / 8.0.0 (Charts)) we will be replacing `eval()` with `new Function()`, which should also reduce the necessary CSP scope we require for Standalone Charts as well as removing this warning.

We have added this to our backlog and we are tracking it with the following reference and description:
AG-8451 - [Charts] Attempt to remove use of `eval()` due to increasing build tooling noise

You can track this item in our product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

I would recommend signing up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us,
Alan
