### ISSUE TITLE
showInLegend is not working as expected

### ISSUE THREAD

**Issue by Gnanavel76** [ag-grid/ag-grid#6440]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I tried to hide `iPad` legend in the following example: https://plnkr.co/edit/W1rfQH45VMEMzcJ5?open=index.jsx by setting `showInLegend: false` on that series definition. Instead of just hiding the `iPad` it also hides the previous series item defined in the series array (i.e., it hides the `iphone` and `mac` legend as well).

**Expected behavior**
Only the series with `showInLegende:false`  should be removed from the UI

**Comment by StephenCooper** [comment]
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-8339 [Charts] setting showInLegend=false on one series is affecting all series previous to it
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).
 
Thanks again for bringing this up with us.
