### ISSUE TITLE
React testing library test for editing cells returns undefined instead of new value.

### ISSUE THREAD

**Issue by IngridPr** [ag-grid/ag-grid#6447]
I'm submitting a  bug report in tests related to ag-grid and editable cells.

**Current behavior**
I have a very simple repo with a grid. It only has one editable cell. In a test I edit this cell. Give it a new value. After presssing enter the new value is not saved. "undefined" is assigned instead.

![image](https://user-images.githubusercontent.com/130447203/231113574-b6226cde-1cdc-4ff4-8628-682d6211881c.png)

**Expected behavior**
In a test I edit this cell. Give it a new value. After presssing enter the new value is saved. A span with new value in the grid is visible.

I made a very simple repo were this problem is reproduced: https://github.com/IngridPr/editing-cells-bug-in-tests
In general it's React, react testing library, ag-grid-community and jest.

* **AG Grid version:** 29.2.0
I believe this can be replicated on any version.

* **Browser:**
The problem is replicable only in tests. Browser behaviour is correct.

**Comment by AdrianRS22** [comment]
@IngridPr It's not a bug, you were trying to type in a div.. instead of the input 
<img width="341" alt="image" src="https://github.com/ag-grid/ag-grid/assets/46205253/786b65e9-b1c0-46cb-b6a8-c61c75ba61a7">
Tests pass
<img width="286" alt="image" src="https://github.com/ag-grid/ag-grid/assets/46205253/48a12f6c-35ca-4a91-ac90-ea44257ad97e">

**Comment by abanarase** [comment]
In case of multiple editable field how we can map those
