### ISSUE TITLE
Cell Renderer Data field not automatically inferring type

### ISSUE THREAD

**Issue by psecuresystem** [ag-grid/ag-grid#6464]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
In AG Grid v29.2.0, When defining column defs, the cellRenderer data field does not infer the type automatically.
```typescript
{
 field: 'sampleField',
 // Other fields,
 cellRenderer: ({ data }) => Component, // The data field is of type any even though I explicitly defined the coldef type to be 
                                                                // ColDef<TheType>
}
```

**Expected behavior**
I'm expecting the type of data to be automatically inferred as `TheType` that I specified

**Please tell us about your environment:**
- AG grid version: 29.2.0
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
- IDE: VSCode
- Language: Typescript 4.9.4

**Comment by StephenCooper** [comment]
Hi @psecuresystem,

Yes currently the `cellRenderer` property is typed as `any` due to the way this property can be used in multiple ways and across different frameworks. 

We have plans to improve this in future versions as it is unfortunate to have this typed as `any`.

**Comment by jakeleventhal** [comment]
Why is this issue closed if there are plans to address it

**Comment by StephenCooper** [comment]
Sorry yes, should have shared the issue number for future references. 

You can track it with this reference:
**AG-8530 Infer Types for cellRenderer if TData specified**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

**Comment by MartinRybergLaude** [comment]
Hi @StephenCooper,

I can't find this issue in neither the pipeline nor changelog. What happened to it?

**Comment by duhseekoh** [comment]
Not seeing that ticket in the changelog or pipeline. cellRendererSelector is correctly typed, but cellRenderer is not.

```
    cellRenderer?: any;
    /** Params to be passed to the `cellRenderer` component. */
    cellRendererParams?: any;
    /** Callback to select which cell renderer to be used for a given row within the same column. */
    cellRendererSelector?: CellRendererSelectorFunc<TData, TValue>;
```

Please re-open.

**Comment by sabahang** [comment]
Apologies, as this is part of another general ticket, the task wasn't publicly visible. Please use the new tracking number I have provided

**Comment by C-Hess** [comment]
It looks like it switched tracking numbers again?
