### ISSUE TITLE
Drag row blocks mouse scroll event.

### ISSUE THREAD

**Issue by Planit-Scheduler-Solutions** [ag-grid/ag-grid#6489]
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

**Current behavior**
When you drag a row and want to scroll vertical by the mouse the drag element block it.
If you try move the mouse fast(For catch time that the mouse pointer leaves the dragged element) and in the same time scroll the scroll works in the moments when the mouse is not on the dragged element. 

**Expected behavior**
When you drag an row the mouse vertical scroll need to work for change the grid view fast and exact.

**Please tell us about your environment:**
Angular 14

* **AG Grid version:** X.X.X
28.2.1

* **Browser:**
Chrome  112.0.5615.49

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Type script 4.6

You can reproduce it on yours main demo on the site
![screen-capture](https://user-images.githubusercontent.com/82387265/233023956-59137889-f8ca-440e-b3ed-25a36877f919.gif)

**Comment by zoheil-ag** [comment]
Hello @Planit-Scheduler-Solutions,
 
Thank you for bringing this up with us. 
 
The functionality you described wasn't part of the requirements when we built this feature. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.
 
You can track it with this reference:
**AG-8480 [SCROLLING] Support vertically scrolling with mouse wheel when using drag & drop functionality**
 
You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!

**Comment by zoheil-ag** [comment]
Hello @yakeer,

Thank you for following up.

At this point, we don't have a specific timeline for implementing this functionality.

In order to get the maximum output from our product team, we very rarely work on feature requests from different areas in isolation. Instead, for a specific release we focus on an entire area of the grid and we tackle a number of issues/feature requests logged against that area. If this functionality falls within the area we'll be working on, there's a chance it will get picked up. This is how it can potentially be implemented and included in a future release without further notice.

For now, please check our pipeline once a month for any updates on this:
https://www.ag-grid.com/ag-grid-pipeline/

We believe it's important to be transparent with you about this and we're sorry we cannot commit to implementing this behavior in the short term.

We hope you can use the current functionality provided by AG Grid until this becomes available at a later point.

Kind Regards,
Zoheil

**Comment by yakeer** [comment]
@StephenCooper,
In which version this bugfix included?

**Comment by yakeer** [comment]
So basically if this issue is fixed, and the Status is in Pipeline is "Backlog", it would be released into a future version?

I don't really understand the process here...

**Comment by AG-Zoheil** [comment]
Hi @yakeer,

**Backlog** simply means this item has been logged and that AG Grid is aware of it. It will be addressed by our product development team at a point in the future.

Once we have incorporated the item into a specific release plan/cycle the status will change to **Scheduled**.

**Comment by yakeer** [comment]
Any plans of adding this feature?
It's in the BackLog for over a year and a half now..
