### ISSUE TITLE
Column order is lost after rerender when columnDefs changes

### ISSUE THREAD

**Issue by dloibl** [ag-grid/ag-grid#6532]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
We noticed a regression when upgrading to latest ag-grid 29.3.3 (from 28.2.1). 
The issues occurs when the initial _columnDefs_ changes after rendering, e.g. when sliced, filtered or changed state.
```tsx
<AgGridReact columnDefs={columns.slice()} />
```
In this scenario the state of moved columns is lost after rerender, i.e. the order of the original columnDef is applied instead. 
Strangely all other column state like sorting, column width, filters work as expected, only the column order is affected.

Here is a minimal stackblitz demo to reproduce this scenario.
https://stackblitz.com/edit/ag-grid-react-hello-world-er54br?file=index.js
Just move a column and click the rerender button.

**Current behavior**
- Column order is lost after rerender

**Expected behavior**
- Keep column order, like any other grid state sorting, column width is kept as well.

* **AG Grid version:** 29.0.0
still an issue in latesst 29.3.3

* **Browser:**
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by StephenCooper** [comment]
Hi @dloibl,

This is the expected behaviour as there are other use cases where users want to provide a new set of columns and have the order match the newly provided columns. 

You can configure this with the following `maintainColumnOrder`. Alternatively use the `applyColumnState` function to apply hide show logic instead of filtering the list of columns provided to the grid.

flag https://ag-grid.com/javascript-data-grid/column-updating-definitions/#maintain-column-order

https://ag-grid.com/javascript-data-grid/column-state/
