### ISSUE TITLE
row-id and row-business-key are out of sync with grid's content after gridApi.refreshInfiniteCache() call

### ISSUE THREAD

**Issue by vladislav-bashkanov** [ag-grid/ag-grid#6534]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hi team,

`row-id` and `row-business-key` (v29.3.3) attributes are not updated after `gridApi.refreshInfiniteCache()` call, although grid refreshes cell's content properly.

**Providing a Reproducible Scenario**
Plnkr with expected initial behavior (v.25.0.1) https://plnkr.co/edit/8qjRHwlt6xXSJ6LY?open=app%2Fapp.component.ts
Plnkr where we noticed behavior change (v26.2.0) : https://plnkr.co/edit/vSMCsymtDltdliSU?open=app%2Fapp.component.ts
Plnkr with the latest version v29.3.3 (works the same as in 26.2.0)  https://plnkr.co/edit/Ifqhyy8320EYFEqb?open=app%2Fapp.component.ts

See IDs in the column
Click _print row ids_ button
Verify that they match with values in the column
Click _refresh_ button
Click _print row ids_ button
Expected : IDs match with values in the column
Actual : IDs do not match

**Current behavior**
`row-id` attributes are not updated after update caused by calling `gridApi.refreshInfiniteCache` 

**Expected behavior**
`row-id` attributes are in sync with real data in row nodes

**Please tell us about your environment:**
Window 10, Google Chrome Version 112.0.5615.138 (64-bit), npm, Angular project

* **AG Grid version:** 26.2.0

* **Browser:**
* Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript@4.6, Angular@14 , see plnkr demo with all libraries

**Comment by StephenCooper** [comment]
Hello Vladislav,
 
Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8495 row-id and row-business-key are out of sync with grid's content after gridApi.refreshInfiniteCache() call**
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).
 
Thanks again for bringing this up with us.
