### ISSUE TITLE
Screen reader focus is not moving in sequential order when navigating using Ctrl+alt+arrow keys.

### ISSUE THREAD

**Issue by msftedad** [ag-grid/ag-grid#6547]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
1.Open URL:[determined-blackburn-302cze - CodeSandbox](https://codesandbox.io/s/determined-blackburn-302cze)
2.Focus lands on the code editor as soon as page gets opened.
3.Press press CTRL+M from keyboard and then press 1 tab to move focus out of editor pane.
4.Press 6 tabs to land on ‘table control’. 
5.Navigate the table using table command Ctrl+alt+arrow keys.

If reporting a bug make sure to state.

**Current behavior**
Screen reader focus is not moving in sequential order when navigating using Ctrl+alt+arrow keys.

Observation: When navigated using table shortcut keys focus is skipping in between and moving to other column headers 

When focus is on first column header user navigates using table shortcut keys screen reader focus is moving to 6th column header by skipping other columns in between

**Expected behavior**
Screen reader focus should move in sequential manner while navigate the table using table command keys as ctrl+alt+arrow keys.

**Please tell us about your environment:**
OS Build: Version 21H2(OS Build 20348.469)
Screen Reader: Narrator, JAWS and NVDA

* **AG Grid version:** X.X.X
AG Grid version: ^25.1.0

* **Browser:**
Browser: Edge Version 95.0.1020.53 (Official build) (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6
![MAS4 2 3-Participant set up-commercial partner-table command is not working sequentially](https://user-images.githubusercontent.com/93735775/235903303-9fd5ff2c-d7a2-4965-ac69-84b6a2d0d2bf.png)
![MAS4 2 3-Participant set up-commercial partner-DOM screen shot](https://user-images.githubusercontent.com/93735775/235903307-eca2c26a-209b-4a79-9419-b984aad860b4.png)

**Comment by kiril-matev** [comment]
Hi @msftedad,

Thanks for reaching out.

You've reported this with version AG Grid v25.1, but the example you've provided uses AG Grid v28.1. We went through the steps you provided.

Steps to follow:
1. Open NVDA
2. Open https://codesandbox.io/s/determined-blackburn-302cze
3. Focus lands on the code editor as soon as page gets opened.
4. Press press CTRL+M from keyboard and then press 1 tab to move focus out of editor pane.
5. Press 6 tabs to land on ‘table control’.
6. Press Ctrl+ALT+RIGHT ARROW keys to move focus to the right column header cell
7. Listen to announcements
**Actual:** 
React App  document
table
Personnel Number  column header  Press ENTER to sort. Press CTRL ENTER to open column menu.  row 1  Personnel Number
Full Name  column 1
**Expected:** 
React App  document
table
Personnel Number  column header  Press ENTER to sort. Press CTRL ENTER to open column menu.  row 1  Personnel Number

8. Press Ctrl+ALT+RIGHT ARROW keys to move focus to the right column header cell
9. Listen to announcements
**Actual**:
Plan Setup  column header  Press ENTER to sort. Press CTRL ENTER to open column menu.  row 1  Plan Setup
Email Alias  column 2
**Expected**: 
Plan Setup  column header  Press ENTER to sort. Press CTRL ENTER to open column menu.  row 1  Plan Setup

The difference between actual and expected announcements is that the name of the first unpinned column is announced after the (focused) first pinned column, and the name of the second unpinned column is announced after the (focused) second pinned column.

Is this the issue you're reporting?

Looking forward to your response.

**Comment by msftedad** [comment]
HI @kiril-matev 
Irrespective of pinned and unpinned columns, Focus should go to first table header to last table header when we press Ctrl+alt+arrow keys.

**Comment by kiril-matev** [comment]
Hi @msftedad,

This isn't related to screen reader focus - the same behavior occurs when not using the screen reader. This issue is caused by the fact that the pinned columns take up more space than the width of the grid and thus prevent keyboard focus to the unpinned columns.

The pinned column area cannot be made scrollable at this time. This is tracked by 
**AG-3915 [Column Pinning] Allow setting maxWidth for pinned columns container - if pinned columns width exceeds the maxWidth they will be flex-ed inside the maxWidth**

However, you can avoid this issue by adding user logic to resize columns when pinned. This logic will ensure the pinned column area doesn't cover the entire grid width and that you can still access the unpinned columns. 

See this sample: 
https://plnkr.co/edit/TsxyiRuOcGAutQIp

In this example, pin multiple columns on the left and note they are resized down so there's always enough space left to display the unpinned columns. This way pinned columns never take up the full width of the grid and you can easily navigate to any of the unpinned columns on the right using the keyboard arrow keys.

Please use the approach shown in the sample above to resolve this.
