### ISSUE TITLE
V29 / Charts 7.3: Global EventTarget declaration overwrite internal typescript interface (breaks other libraries)

### ISSUE THREAD

**Issue by spyro2000** [ag-grid/ag-grid#6551]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**

- Import ag-charts > 7.x, e.g. 7.3 (i'm also importing ag-grid enterprise, but shouldn't matter)
- Import any typescript code working with native EventTargets e. g.  "reconnecting-eventsource": "^1.5.2"
- Try to build project

**Expected behavior**

ag-grid/ag-charts does not break other libraries

**Current behavior**

In `tooltip.d.ts` (of ag-charts-community) there is a global (!) interface declaration with name `EventTarget`.

![image](https://user-images.githubusercontent.com/8479925/235954991-568a6523-ec6d-4c45-b06f-8accab9bb391.png)

This overwrites the native EventTarget interface provided by typescript lib itself. See `lib.dom.d.ts` line 5120 ff. (Typescript 2.5.1):

![image](https://user-images.githubusercontent.com/8479925/235955875-9f0bf22c-9249-4509-8289-37c7279d5086.png)

Depending on import order this will break any build process importing any EventTarget-related Typescript code or extending classes/interfaces from it (**EventSource** extends _EventTarget_):

![image](https://user-images.githubusercontent.com/8479925/235956576-93eb5e36-5243-4426-be75-9b60cf145265.png)

**Suggested solution**

- Please don't use global declarations if possible
- Use your own namespace
- At least use different names not colliding with Typescripts own library
- Fallback: Make `classList` optional

**Please tell us about your environment:**
Angular 14.1, Win10x64

**AG Grid version:** 
29.3.3

**AG Charts version:** 
7.3.0

**Browser:**
n/a

**Language:**
Typescript 4.7.4, Lib 2.4.0 / 2.5.1

**Comment by StephenCooper** [comment]
Thank you for reporting this, we will fix this under: **AG-8506 [Charts] Remove global typescript definitions in zoom & tootlip**. 

Is this blocking you?

<hr>

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by alantreadway** [comment]
Thanks again for reporting this - the fix for AG-8506 has been made, and will be in the next major release of `ag-charts-community`, which we expect to be in the next month or so.

**Comment by spyro2000** [comment]
Hello @alantreadway,

many thanks. As this bug is breaking unrelated code, I was hoping for a bugfix release?
