### ISSUE TITLE
React: When sideBar option is specified with a configuration, it closes when editing the columnDefs

### ISSUE THREAD

**Issue by sscots** [ag-grid/ag-grid#6559]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When specifying a sideBar configuration object, the side bar will automatically close when modifying the columnDefs config object.

**Expected behavior**
The sideBar should stay open.

EXAMPLE: 
Open the sidebar, click to sort a column and you should see that the side bar closes by itself.
The first table shows the bug of the side bar being closed, with a sideBar config specified. The second table does not have the bug (the sidebar stays open) with the sideBar config set to "true".
https://plnkr.co/edit/OmJQmxe7r25e0Ql5?open=index.tsx&preview

**Comment by StephenCooper** [comment]
This is due to the following line of code. Each time the component re-renders this configuration is a new object so the grid treats it as a new implementation of the sideBar and so it resets to the provided state.

```
sideBar={{position: 'left', toolPanels: ['columns', 'filters']}}
```

If you pull the config out into a property and useMemo then the top example will work as well. 

https://plnkr.co/edit/0uGcJ2dwneaxjQqC?open=index.tsx

**Comment by sscots** [comment]
@StephenCooper Thanks that worked!
