### ISSUE TITLE
Empty grid if you put a decimal number in the rowHeight option

### ISSUE THREAD

**Issue by Senpai10** [ag-grid/ag-grid#6581]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I went from version 28.1.1 to version 29.3.4. I don't know if I'm the only one but I noticed a strange behavior with the rowHeight option.
When I set this option as a decimal number, for example

```
const gridOptions = {
    rowHeight: 65.5,
    rowModelType: 'serverSide';

    // other grid options ...
}
```

I have no data displayed. On the other hand with an integer like :

```
const gridOptions = {
    rowHeight: 65,
    rowModelType: 'serverSide';

    // other grid options ...
}
```

It works. My data is displayed in the grid.

I didn't have this problem with version 28.1.1
Am I the only one to have this problem ? Why no data is displayed if I put a decimal number for the rowHeight?

**Expected behavior**

Possibility to put a decimal number for the rowHeight option

**Please tell us about your environment:**

* **AG Grid version:** 29.3.4

* **Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

* **Language:** Javascript

**Comment by StephenCooper** [comment]
Thanks for reporting, I have raised this internally for further investigation.

If you have an active Enterprise License for your ServerSide grid you will find you get a faster response via your access to Zendesk.

**Comment by AndrewGlazier** [comment]
Hello,
 
Thank you for the context you provided - this really helps us understand your requirements.
 
We have added this to our backlog and we are tracking it with the following reference and description:
AG-8613 - [SSRM] rows do not render when rowHeight is decimal
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
You can see whether this item is selected for implementation on the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/
 
I would recommend signing up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).
 
For more information on when can you expect your ticket to be fixed please check:
https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket-
 
Thanks again for bringing this up with us.
