### ISSUE TITLE
Ag Grid: Balanced Groups is not working while using valueFormatter on column ag grid

### ISSUE THREAD

**Issue by dakshesh007** [ag-grid/ag-grid#6615]
While using valueFormatter with column and then we will group that column then balance group name is showin "" instead of (Blanks)

Here is example

Column with valueFormatter  : - https://plnkr.co/edit/SHrqxsxTz11KGU2F?open=app%2Fapp.component.ts
Expected behavior :- it should show Blanks instead of Empty string
![image](https://github.com/ag-grid/ag-grid/assets/82196060/0f2beb57-ba5d-4ed7-ba5d-8a33e0c40eb6)

Column without valueFormatter  https://plnkr.co/edit/?open=app%2Fapp.component.ts&preview
![image](https://github.com/ag-grid/ag-grid/assets/82196060/b5d6e870-78f9-40bc-8122-671a07c0805f)

**Comment by zoheil-ag** [comment]
Hello dakshesh007,
 
Thank you for bringing this up with us. 
 
The functionality you described wasn't part of the requirements when we built this feature. This is why we have added a feature request in our backlog to fully investigate all use cases in relation to this.
 
You can track it with this reference:
**AG-8632 [Row Grouping] Investigate row grouping when using a valueFormatter on the grouped column or auto-group column - Allow rows processed by valueFormatter to be grouped together as (Blanks)**
 
 
You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/
 
 
Meanwhile, as a workaround, I can suggest to use valueGetter instead of valueFormatter and see if that works for you. You can see an example of this being in use in the following plunker: https://plnkr.co/edit/Yii4fpB1aDMWVGkI?open=app%2Fapp.component.ts&preview.
 
You can read more about valueGetters in our documentation here: https://ag-grid.com/angular-data-grid/value-getters/
 
 
**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:**
https://www.ag-grid.com/ag-grid-changelog/
 
Thanks again for bringing this up with us - we appreciate your time!
