### ISSUE TITLE
Unexpected conversion of boolean to reference type when instantiating custom cell renderer class

### ISSUE THREAD

**Issue by clinthof** [ag-grid/ag-grid#6625]
**I'm submitting a ...**
```
[x] bug report 
[] feature request 
[] support request 
```

**Current behavior**
* When defining a custom checkbox renderer and assigning it in GridOption's components property, a constructor with an optional boolean property defaults to an empty object unless explicitly defined as a new instance and passed a boolean value. In other words,
`checkBoxRenderer: CheckBoxRenderer` results in `disabled = {}`, but
`checkBoxRenderer: (params: ICellRendererParams) => new CheckBoxRenderer(params, false)` works as expected.
Alternatively, `this.disabled = typeof disabled === 'object' ? false : disabled;` "fixes" this.
* [Here is a reproduction of the bug](https://stackblitz.com/edit/ag-grid-react-hello-world-3bjmkg?file=index.js) using code forked directly from the docs and modified to use ts.

**Expected behavior**
Unless I'm missing something, this shouldn't be setting any other argument values aside from the cell renderer's params (i.e., this optional boolean should remain a boolean).

**Environment:**

* **OS:** Windows 11
* **IDE:** VS Code
* **Package manager:** npm
* **AG Grid version:** v27.2.1
* **Browser:** Chrome v113.0.0.0
* **Language:** TypeScript v4.9.5
* **Framework:** React v17.0.2

**Comment by kiril-matev** [comment]
Hi @clinthof,

Thanks for reporting this.

In order to better handle the requirement to show boolean values using a checkbox in a grid cell, AG Grid v30 adds a built-in checkbox cell renderer. See this here:
https://www.ag-grid.com/javascript-data-grid/cell-rendering/#checkbox-cell-renderer

Using the checkbox cell renderer, you'll be able to show boolean values without having to build your own custom cell renderer for this purpose.

Note there's also a built-in checkbox cell editor which gets displayed when the cell is in edit mode:
https://www.ag-grid.com/javascript-data-grid/provided-cell-editors/#checkbox-cell-editor

Please review the cell data types feature (introduced in v30) which allows for automatic date type inference which automatically renders a checkbox for columns with boolean data type:
https://www.ag-grid.com/javascript-data-grid/cell-data-types/#top

Please upgrade to AG Grid v30 to use this built-in functionality so you won't have to use and support your own custom checkbox renderer.
