### ISSUE TITLE
Selection resets on state change

### ISSUE THREAD

**Issue by hankduan** [ag-grid/ag-grid#6635]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
After you set any selection (e.g. checkbox or just click a row), a state update will reset it

```
export default function ScreenTableScreen() {
  const agGridRef = React.useRef<AgGridReactType>(null);

  const [foo, setFoo] = React.useState(true);

  React.useEffect(() => {
    // whenever this runs, whatever checkbox state is set in ag-grid will get reset
    const x = setInterval(() => setFoo((foo) => !foo), 2000);
    return () => clearInterval(x);
  }, []);

  return (
    <Box className='ag-theme-alpine' sx={{ height: 500 }}>
      <AgGridReact
        ref={agGridRef}
        rowData={userData}
        columnDefs={[
          { field: 'status', checkboxSelection: true },
          { field: 'id' },
        ]}
        rowSelection='multiple'
        onSelectionChanged={() => {/* doesn't matter */}}
      />
    </Box>
  );
}
```

**Expected behavior**
checkbox/selection state should persist

**Please tell us about your environment:**
mac/http

* **AG Grid version:** X.X.X
This is broken in 29.3.5
But working in 28.2.0
I'm not sure which exact version broke it

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by StephenCooper** [comment]
I am not able to reproduce this, can you provide a Plunker for this that shows this happening?

**Comment by hankduan** [comment]
It's probably related to this:

https://plnkr.co/edit/7D86VGVTKyW97RXa?open=index.tsx

Note if you uncomment L29 (and comment L28) then it works. There's something that causes aggrid to not work when there is any kind of potential data change, even if it doesn't change

**Comment by balabanshik** [comment]
We also have the same problem. Here's what it looks like:
https://github.com/ag-grid/ag-grid/assets/3754196/58e7786b-0e3a-4f63-aa58-3c9f45a5bedc
I wish I had an isolated repro, but it happens to a single table in a larger application, and works fine with the rest of them.

### Details
#### Environment
The app is built using NextJS v13.0.
AgGrid v29.3.5

(we then upgraded AgGrid to v30.0.2 which required upgrading to NextJS v13.2)

The bug was not present in AgGrid v28.2.1, and only appeared after upgrading to v29.3.5

#### What happens
After selection changes, AgGrid correctly calls the callback. The callback sets state to store the selection for later use. When the state is changed, the selection disappears. If the line changing the state is removed, the selection remains.
The disappearing selection does not produce any side events.

**Comment by StephenCooper** [comment]
I would recommend applying the `debug` flag to your component when running into issues like this as it lists our when any prop changes and this can be helpful in diagnosing issues.

I suspect that you will see the following in your app with `debug` enabled

```
 agGridReact: [rowData] property changed
```
 You will want to have your rowData passed to the grid via either `useState` or `useMemo` and make sure that you are not applying any filtering directly on the component as this will cause a new instance of the array to be passed to the grid. 

This changed in v29 because we removed our DeepValueChecks which caught cases like this but with the unfortunate side effect of introducing a performance cost.

Please see https://ag-grid.com/react-data-grid/react-hooks/ for more details.

Alternatively for your selection issue, you could look at implementing `getRowId` callback and then the grid will maintain selection across rowData changes. https://ag-grid.com/react-data-grid/data-update-row-data/
