### ISSUE TITLE
When upgrading Ag Grid from 25.0.1 to 29.3.5, vertical scrolling became slower when enableRtl=true

### ISSUE THREAD

**Issue by bsuro10** [ag-grid/ag-grid#6637]
**I'm submitting a bug report**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
- Open Ag Grid Demo with enableRTL=false: https://www.ag-grid.com/example/.
- Scroll and notice the speed of scrolling.
- Open Ag Grid RTL document: https://www.ag-grid.com/angular-data-grid/rtl/.
- Scroll and notice that the scrolling is much slower than the demo due to enableRTL=true.

**Current behavior**
Scrolling vertical is slower when RTL mode enabled in Ag Grid 29.

**Expected behavior**
Scrolling vertical should be faster - the same as without RTL enabled.

**Please tell us about your environment:**
Operating system: Linux
IDE: WebStorm
package manager: NPM

* **AG Grid version:** 29.3.5
When using Ag Grid 25.0.1 the problem didn't occur -> After upgrading to Ag Grid 29 we started to notice the problem.

* **Browser:** Chrome 113.0.5672.93

* **Language:** TypeScript 4.3.5

**Comment by StephenCooper** [comment]
Hi @bsuro10,

How are you measuring the speed of the scroll? I have taken the RTL example and when I toggle `enableRtl` on and off I am not able to see the difference. Could you provide some more details so that we can try and reproduce what you are seeing. Or maybe a video that shows the difference when you toggle the flag?

https://plnkr.co/edit/SuuUjbWV06Vh1FhO?open=app%2Fapp.component.ts

**Comment by bsuro10** [comment]
> Hi @bsuro10,
> 
> How are you measuring the speed of the scroll? I have taken the RTL example and when I toggle `enableRtl` on and off I am not able to see the difference. Could you provide some more details so that we can try and reproduce what you are seeing. Or maybe a video that shows the difference when you toggle the flag?
> 
> https://plnkr.co/edit/SuuUjbWV06Vh1FhO?open=app%2Fapp.component.ts

Hey, thank you for replying.
I checked out your plnkr and I am still having the same issue.

To check the speed you can do the following step - with RTL enabled:
- Mark the last visible row and scroll ONE time (From end to end - 180 degrees)
- You will notice that you didn't reach the marked line.
- Disable RTL and repeat step 1 +2 - You will notice that you will reach the marked line and even further.

**Comment by StephenCooper** [comment]
Neither myself or my colleague have been able to reproduce the difference with RTL. We are using Chrome on latest version. So may need more details / video to see what is going on.

**Comment by kiril-matev** [comment]
Hello @bsuro10,

Thanks for reporting this potential issue.

I wasn't able to reproduce the difference in scrolling behavior you described for the cases when RTL is used and not used.

Here're the two test cases I used. 

Test case 1 - **with** enableRtl=true
1. Open
https://plnkr.co/edit/SuuUjbWV06Vh1FhO?open=app%2Fapp.component.ts&preview
2. Click the AGE column cell in the row shown at the bottom of the viewport
3. Scroll down 7 notches on the mouse wheel
Actual & Expected: Focused cell appears at the top of the viewport (as shown in GIF below)
![scroll_rtl](https://github.com/ag-grid/ag-grid/assets/60937283/67432772-b902-4c7c-86f1-c5caf07ada11)

Test case 2 - **without** enableRtl=true (same steps as above)
https://plnkr.co/edit/UyTHFEMpNwGUPa5I?open=app%2Fapp.component.ts
Actual & Expected: Focused cell appears at the top of the viewport (as shown in GIF below)

![scrolling_normal](https://github.com/ag-grid/ag-grid/assets/60937283/21e82d6b-80b7-4b15-bbb0-47ded17326bb)

Please provide an example and a detailed list of steps we can use to reproduce this. Also provide your browser version.

Looking forward to your response.

**Comment by bsuro10** [comment]
@StephenCooper 
@kiril-matev 


Hey!
I was a bit confused because now I can't see the difference, and the scrolling is way faster. However, I then realized that our Chrome had been updated to version 114.0.5735.110, while the issue was reported with version 113.0.5672.93.

After installing Chrome with the previous version (113.0.5672.93), I can confirm that the issue is present. This suggests that the Chrome version is the cause of the scrolling issue. Chrome 114 works fine, but Chrome 113 has issues.

Although the issue is resolved when upgrading Chrome, we still want to determine if it's a Chrome issue, an Ag Grid issue, or a combination of both that you guys could solve. We also would like support for previous versions of Chrome. (Which are not that old)

**Comment by kiril-matev** [comment]
Hi @bsuro10,

Thanks for this response - it makes sense now.
 
Chrome 113 was published as stable on May 2nd, 2023.
Chrome 114 was publishes as stable on June 7th, 2023.
 
**As per our documentation, an AG Grid version only supports the last two major versions of browsers at the time of the AG Grid version release:**
https://www.ag-grid.com/javascript-data-grid/supported-browsers/#desktop-browsers

The next major version of Chrome - 115 will be released as stable on July 18th, which is less than a month away. We're not planning a new AG Grid release until Chrome 115 is released.
 
This means that at the time our our next release (AG Grid 30.1 which will be in mid-July), only the two latest Chrome versions will be supported - versions 114 and 115. This is why Chrome 113 will no longer be supported in AG Grid 30.1 and we'd recommend users having any issues with Chrome 113 to upgrade to a newer version of Chrome which doesn't have this issue. 
 
If this issue is reproducible with any of the current versions of Chrome, we'll investigate and resolve it. However, due to our release schedule we won't be able to resolve this issue for Chrome 113 in the next month.
 
Please ask your customers to keep the version of Chrome updated. This is important not just for AG Grid but in order to avoid having security vulnerabilities exposed in older versions of Chrome being exploited.
 
Please let me know if you have any questions.

**Comment by bsuro10** [comment]
@kiril-matev 
@StephenCooper 

Hey,
I want to open this issue again because the problem is reproducing in Chrome 114.0.5735.91 (while 114.0.5735.110 works).

We are a big organization and distributing chrome to all stations across the organization can take months, and for now we only have chrome 114.0.5735.91 which have problems with the scrolling of the grid.

We do need you to resolve the issue since this chrome version should be supported with Ag Grid 29.3.0.

**Comment by zoheil-ag** [comment]
Hi @bsuro10,

Thank you for getting in touch.

The stable version of Chrome 114 was released on the 24th of May this year. Our grid version 29.3.0 was released on the 20th of April.

So at the time of the release of 29.3.0 we would have supported stable Chrome versions 113 and 112 (i.e. last two major versions).
Our next release after Chrome 114 (besides minor patches) was 30.0.0 on the 9th of June. This version of the grid would have support for Chrome 114 and 113.

Our next release (this month) will be 30.1.0. This version will again support the latest two major versions of Chrome (now 115 and 114).

We do not provide patches to older versions to provide support for new versions of Chrome (or other 3rd parties for that matter). You would need to upgrade to the latest AG-Grid version.

I hope the above clarifies what to expect from different versions of AG-Grid.

Thank you,
Zoheil
