### ISSUE TITLE
'!important' property in cell style

### ISSUE THREAD

**Issue by brokoder** [ag-grid/ag-grid#6644]
**I'm submitting a bug report ** 

Plunker - [link](https://plnkr.co/edit/SkNmBHBabCTswev2?open=main.js)

Need to add a cell style with !important. Tried but it is failing.
`
cellStyle: {
      // you can use either came case or dashes, the grid converts to whats needed
      backgroundColor: '#aaffaa !important', // light green
    }
`
it will work while 
`
cellStyle: {
      // you can use either came case or dashes, the grid converts to whats needed
      backgroundColor: '#aaffaa ', // light green
    } 
`

**Current behavior**
if we add a cell style with !important it is not adding that style

**Expected behavior**
it should be able to add the color along with the tag.

* **AG Grid version:**  Latest

* **Browser:** Chrome

* **Language:** All

**Comment by kiril-matev** [comment]
Hi @brokoder,

Thanks for reporting this.

This was logged as:
**AG-8679 CellStyles with `!important` are not applied to grid cells**

This was fixed in AG Grid 30.0, as shown in our changelog:
https://ag-grid.com/changelog/?searchQuery=8679

Please upgrade to this version to resolve this.

Thank you for your time!
