### ISSUE TITLE
Reset All filter button for 'singleColumn' row group display type.

### ISSUE THREAD

**Issue by Paveltrof86** [ag-grid/ag-grid#6653]
Hello!

Thank you for new feature  - filter: **'agGroupColumnFilter'**. It`s really useful point.

Could you tell me if it is planned to add functionality like setFilterModel(null) or Reset All button to reset all column groups with singleColumn type? Because at the moment, to reset the filters, I need to switch to each group.

PS I know about custom filter components. I just wanted to know if there will be something similar "out of the box".

![2023-05-23_19h26_13](https://github.com/ag-grid/ag-grid/assets/19744837/79c70805-c726-4194-bde8-4ada84d20edc)

Thank you!

**Comment by kiril-matev** [comment]
Hello @Paveltrof86,

Thank you for bringing this up with us. 

The functionality you described wasn't part of the requirements when we built this feature. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-8844 [Column Filters] Allow adding a button to reset all the group filters applied**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
