### ISSUE TITLE
Custom Column Types cannot extend other types.

### ISSUE THREAD

**Issue by h3adache** [ag-grid/ag-grid#6665]
**I'm submitting a**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

If reporting a bug make sure to state.

**Current behavior**
Defining a custom column type with another type does not seem to allow it to pick up definitions in that type.
```  
clstMoney: {
    cellRenderer: memo(MonetaryRenderer),
    flex: 1,
    minWidth: 100,
    type: 'rightAligned',
},
```

Instead you have to define it as:
```  
clstMoney: {
    cellClass: 'ag-right-aligned-cell',
    cellRenderer: memo(MonetaryRenderer),
    flex: 1,
    headerClass: 'ag-right-aligned-header',
    minWidth: 100,
},
```

**Expected behavior**
According to the [docs](https://www.ag-grid.com/react-data-grid/column-definitions/#default-column-definitions)

> Default columns and column types can specify any of the [column properties](https://www.ag-grid.com/react-data-grid/column-properties/) available on a column.

But this does not seem to apply to the [`type` option](https://www.ag-grid.com/react-data-grid/column-properties/#reference-columns-type)

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
```
 "@ag-grid-community/core": "29.3.4",
 "@ag-grid-enterprise/core": "29.3.4",
```

**Comment by kiril-matev** [comment]
Hello @h3adache,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-9693 [Column Type] Incorrect column typing - type within a type**

This issue will be fixed in the next release.

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
