### ISSUE TITLE
performance issue when using rowModelType="clientSide" after upgrade from v28.2.1 to v29.2.0

### ISSUE THREAD

**Issue by YuriyVel** [ag-grid/ag-grid#6691]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**: 
table with rowModelType="clientSide" becomes unresponsive or almost unresponsive (hovering on rows, scrolling, grouping)
(Tables with rowModelType="serverSide" remains work well)

**Expected behavior**: performant behaviour of table
**Example on codesandbox**: [unresponsive table ](https://codesandbox.io/s/epic-buck-2tw638)

* **IDE:** VS Code
* **Package manager:** yarn
* **Framework:** React v18.2.0
* **AG Grid version:**  v29.2.0
* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36'
* **Language:** ES6

**Comment by StephenCooper** [comment]
Try pulling your `defaultColDef` out into a `useMemo` hook instead of declaring directly on the component. This will prevent the default col def appearing like a new reference on each render. 

I have linked to an existing ticket where we are evaluating adding some protection against defining objects directly on the component. 

You can see the effect of defining objects on the component by adding the `debug` flag. Note the difference when you pull `defaultColDef` out with a useMemo.

**Comment by YuriyVel** [comment]
@StephenCooper, thanks much appreciated!
