### ISSUE TITLE
Disable table scroll animation

### ISSUE THREAD

**Issue by b-js** [ag-grid/ag-grid#6707]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Is there a way to disable table scroll animation?
I'm trying to sync position of a table scroll with the Gantt chart. Chart does not have smooth animation.
Also, I guess the animation increases the number of calls to the viewport-changed event I'm trying to bind to.

I tried ```suppressAnimationFrame=true``` but it didn't work.
Here is [Plunker](https://plnkr.co/edit/yj4OlrLZwb1TUs15?open=lib%2Fscript.js&preview)

* **AG Grid version:** X.X.X
29.3.5

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

**Comment by StephenCooper** [comment]
Sorry I do not understand which animation you are trying to disable based on the information you have provided. 

I assume it is not related to row animations as those are to do with when data is updating? 
https://build.ag-grid.com/vue-data-grid/grid-options/#reference-rendering-animateRows

**Comment by b-js** [comment]
I'm sorry I didn't explain enough.

During scrolling of ag-grid table it has small smooth scrolling animation, provided by animationFrameService. 
I want to receive some more discrete result without any animation to synchronize it with another control.
Please see example in "expected.mp4" attachment.



https://github.com/ag-grid/ag-grid/assets/47082596/6dd5a403-938d-47e3-90be-26329a27c3ff


https://github.com/ag-grid/ag-grid/assets/47082596/0deada26-a074-4b5f-a5d5-25a8deb19690

**Comment by kiril-matev** [comment]
Hi @b-js, 

Thank you for this additional context - much appreciated.

We'll take a look and follow up here.

**Comment by kiril-matev** [comment]
Hi @b-js,

We're keen to look at this "scrolling without any animation" behavior in more detail. 

Please provide a live example of the grid in your video which doesn't use scrolling animation.

**Comment by kiril-matev** [comment]
Hello,

Thank you for bringing this up with us. 

We have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-8805 [Scrolling] Allow preventing smooth scrolling and using immediate scrolling without animation**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
