### ISSUE TITLE
grid layout error when parents node layout is overflow: auto

### ISSUE THREAD

**Issue by cc616** [ag-grid/ag-grid#6712]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
If I run the demo in a new window, and refresh the page and scroll quickly, flash will show up and lead to the break down of the  whole page. Please refer to the video I attached.
But If I delete the 'overflow: auto' attribute in .main in layout.css file, the flash will disappear.

**Expected behavior**
Expect the page show up normally.

**Please tell us about your environment:**
this is my online code: https://codesandbox.io/s/optimistic-feather-srwiio?file=/src/layout.css

* **AG Grid version:** 26.0.0

* **Browser:**
Google Chrome 114.0.5735.90

**Comment by kiril-matev** [comment]
Hello @cc616,

Thank you for reporting this potential issue. We're keen to investigate it.

You mentioned you've attached a video but there's no video attached here and I couldn't reproduce the issue with the sample you sent.

Please follow the steps below:
1. Verify whether you can reproduce this issue with the latest version of AG Grid (you've said you're using AG Grid v26 and latest is v30)
2. If the issue is still reproducible with v30, provide a list of steps to reproduce the issue and attach a video showing the issue

Looking forward to your response.
