### ISSUE TITLE
Ag-Grid Filter excelMode: 'windows' with 'Add current selection to filter' option

### ISSUE THREAD

**Issue by sourabhazure** [ag-grid/ag-grid#6716]
I am using Ag-Grid angular with excelMode: 'windows' This is working as described in link 
https://www.ag-grid.com/angular-data-grid/filter-set-excel-mode/

But when i do filtering in Excel on Windows system.. and then try to search in the filter list.. it shows me "(Select All Search Results)" and additionally it gives option: "Add current selection to filter".
<img width="143" alt="image" src="https://github.com/ag-grid/ag-grid/assets/134994546/dd4aff0c-647a-4eba-9730-fdf0da496273">
<img width="143" alt="image" src="https://github.com/ag-grid/ag-grid/assets/134994546/5010824e-1589-4449-8cae-13946371313f">

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
Ag-Grid filter excelMode: 'windows' only give "(Select All Search Results)" as option

**Expected behavior**
Ag-Grid filter excelMode: 'windows' should give "(Select All Search Results)" and "Add current selection to filter" as options

**Please tell us about your environment:**
- VS Code
- Windows

* **AG Grid version:** X.X.X
28.2.0

* **Browser:**
Chrome

* **Language:** Angular 14 | TypeScript

**Comment by kiril-matev** [comment]
Hello @sourabhazure,

Thank you for bringing this up with us. 

The set filter option to "Add current selection to filter" you described isn't currently supported by AG Grid set filter excel mode. We have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-4483 [Column Filters] Add a new set filter option when using Excel-mode to add the currently selected items to the existing items instead of replacing them ("Add current selection to filter")**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
