### ISSUE TITLE
Is there Gauge chart?

### ISSUE THREAD

**Issue by rabeeshcharles** [ag-grid/ag-grid#6739]
![image](https://github.com/ag-grid/ag-grid/assets/30102705/470df005-4a47-4f21-9517-ad5200f3d9fb)

**Comment by kiril-matev** [comment]
Hello @rabeeshcharles,

Thanks for reaching out.

At this time AG Grid doesn't offer a gauge chart. 

See the chart series types here:
https://www.ag-grid.com/javascript-charts/overview/

**Comment by RiouTenkei** [comment]
Hi - Is there any plans to include a gauge chart in the near future with the launch of AG Charts?

**Comment by AG-DavidG** [comment]
Hello @RiouTenkei ,

Thank you for bringing this up with us. 

We have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
AG-10375 - [Charts] Add Gauge series type

You can follow the status of feature requests, bugs and releases using our pipeline:
https://charts.ag-grid.com/pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-10375) on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/

Thanks again for bringing this up with us - we appreciate your time!
