### ISSUE TITLE
Select All: select / deselect all option values - both hidden and shown

### ISSUE THREAD

**Issue by RonGootmanOasis** [ag-grid/ag-grid#6760]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I am using`agSetColumnFilter` (Set Filter) on my columnFilter. I have a pretty long list of options, by default all options are pre-selected. I would like to filter on a specific option so I use the minifilter to quickly find my specific option. I click on "Select All" and it only deselects the specific visible option, while the hidden options still remain selected.

**Expected behavior**
When click on the select all option, I would like it to select or deselect **all options** (both visible and hidden options) regardless of what is shown based on the minifilter input.

* **AG Grid version:** 29.2.0

**Comment by kiril-matev** [comment]
Hello @RonGootmanOasis,

Thanks for reaching out.

If you have a long list of options and you prefer to filter in matching items instead of filtering out non-matching items, set filterParams.defaultToNothingSelected=true.

See this documented here:
https://www.ag-grid.com/javascript-data-grid/filter-set-filter-list/#default-state
