### ISSUE TITLE
valueAxisDomain of Sparklines centred around 0, with values outside the valueAxisDomain 

### ISSUE THREAD

**Issue by gioxc88** [ag-grid/ag-grid#6764]
I would like to recreate the same effect that is possible in excel when using bar formatter:

- I specify a range for example [-5, 5] 
- The bar is centred around 0 
- Every value outside the range [-5, 5] fills the bar in one of the direction

To be more precise on last point. Say I have the value 10, in the bar it still shows as 5 (the maximum allowed), but the value shown is still 10.

It seems in Aggrid this is not possible. Even if I specify the valueAxisDomain  = [-5, 5], every value outside this range completely messes up the Bar size for all the other values.

Is there a solution ?

**Comment by zoheil-ag** [comment]
Hi @gioxc88,

Thank you for submitting this on Github.

Sparklines are an enterprise feature. As we do not provide support on Github but only take bug reports, I would encourage you to raise this via our support portal if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here, as it has been open for quite a while without any further interaction.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support and do NOT have an active AG Grid Enterprise licence, you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
