### ISSUE TITLE
Incorrect reading of unpinned headers by screen reader

### ISSUE THREAD

**Issue by radhwan** [ag-grid/ag-grid#6783]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Any table with columns pinned to left

The screen reader (accessibility tool) reads the wrong label. When the first columns are pinned, the reading of the unpinned columns is shifted and starts from the first column again.

 

**Current behavior**
 When the first columns are pinned, the reading of the unpinned columns is shifted and starts from the first column again.

**Expected behavior**
When the first columns are pinned, the reading of the unpinned columns should read the correct label.

**Please tell us about your environment:**

https://www.ag-grid.com/javascript-data-grid/column-pinning/#example-pinning 
Example visible here.

 **AG Grid version:** X.X.X
latest

**Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Language:** all

**Comment by kiril-matev** [comment]
Hello @radhwan,

Thanks for reporting this.

This behavior in screen readers is caused by the fact that the pinned columns in AG Grid aren’t rendered in sequence with un-pinned columns. Instead, they are rendered in separate containers for pinned columns. 

This is throwing off screen readers who expect that elements that are visually adjacent are adjacent in the DOM structure, which isn't the case.

This is documented as a known limitation here:
https://www.ag-grid.com/vue-data-grid/accessibility/#navigation-to-pinned-rowscolumns

Please log this as a known limitation due to the way screen readers handle elements in separate containers.
