### ISSUE TITLE
Custom tool panel will auto close and remounting when setState updated.

### ISSUE THREAD

**Issue by xhw0714** [ag-grid/ag-grid#6825]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
codesandbox link: https://codesandbox.io/s/distracted-hawking-ydqdvk?file=/src/App.js
example:
```javascript
// custom toolpanel
import React, { useEffect } from 'react';

export default (props) => {

  useEffect(() => {
    console.log('mount');
  }, []);

  return (
    <div style={{ textAlign: 'center' }}>
      <span>
        <h2 onClick={props.onClick}>
          <i className="fa fa-calculator"></i> {props.header}
        </h2>
      </span>
    </div>
  );
}

// index.jsx
const GridExample = () => {
  const containerStyle = useMemo(() => ({ width: '100%', height: '100%' }), []);
  const gridStyle = useMemo(() => ({ height: '100%', width: '100%' }), []);
  const [rowData, setRowData] = useState();
  const [header, setHeader] = useState('abc')
  const sideBar = useMemo(() => {
    return {
      toolPanels: [
        {
          id: 'customStats',
          labelDefault: 'Custom Stats',
          labelKey: 'customStats',
          iconKey: 'custom-stats',
          toolPanel: CustomStatsToolPanel,
          toolPanelParams: {
            header: header,
            onClick: () => {
              setHeader('cba')
            }
          }
        },
      ]
    };
  }, [header]);


  return (
    <div style={containerStyle}>
      <div style={{ height: '100%', boxSizing: 'border-box' }}>
        <div style={gridStyle} className="ag-theme-alpine">
          <AgGridReact
            rowData={rowData}
            sideBar={sideBar}
          ></AgGridReact>
        </div>
      </div>
    </div>
  );
};

```
to run this example you can see the tool panel will auto close and remounting when setHeader updated..

**Expected behavior**
keep the toolpanel visble. or can provide any solution for this?

* **AG Grid version:** X.X.X
v30.0.2

* **Browser:**
chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
react

**Comment by kiril-matev** [comment]
Hello,

Thank you for bringing this up with us. 

The functionality you described wasn't part of the requirements when we built this feature. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-7743 [Tool Panel] Allow the custom tool panel to be updated instead of recreated when tool panel parameters change**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
