### ISSUE TITLE
Ag-Grid sometimes not display value

### ISSUE THREAD

**Issue by shadoworion** [ag-grid/ag-grid#6833]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
https://codesandbox.io/p/sandbox/wizardly-rubin-fww8fw

**Current behavior**
For some reason ag-grid not display value in some cells

**Expected behavior**
To display value

**Please tell us about your environment:**
MacOS 13.4.1

* **AG Grid version:** 30.0.2

* **Browser:**
Microsoft Edge 113.0.1774.57

* **Language:**
React 18.2.0, Typescript 5.1.3

**Comment by StephenCooper** [comment]
Hi @shadoworion,

Could you please provide more details about what is not being displayed? It is not clear from your reproduction alone what the issue is.

**Comment by shadoworion** [comment]
> Hi @shadoworion,
> 
> Could you please provide more details about what is not being displayed? It is not clear from your reproduction alone what the issue is.

Same rows without "valueFormatter" and with. Value exists in both examples but for some reason without "valueFormatter" not displayed...

1:
<img width="960" alt="Знімок екрана 2023-07-14 о 12 48 48" src="https://github.com/ag-grid/ag-grid/assets/22725469/42261cf7-9f95-4deb-a415-8d0f86c1bf33">

2:
<img width="960" alt="Знімок екрана 2023-07-14 о 12 49 29" src="https://github.com/ag-grid/ag-grid/assets/22725469/6301c55b-eb86-4767-8828-a427155f8d88">

**Comment by StephenCooper** [comment]
Thanks for the extra context. I am struggling to update the CodeSandBox. Is it a private one? Could you share it publicly so that I can fork it?

**Comment by shadoworion** [comment]
> Thanks for the extra context. I am struggling to update the CodeSandBox. Is it a private one? Could you share it publicly so that I can fork it?

Done! It's public now

**Comment by StephenCooper** [comment]
Ok I can reproduce the bug and also can give you a workaround in the meantime. The issue relates to our auto inferring logic for `cellDataType`.

https://ag-grid.com/react-data-grid/cell-data-types/

If you are not intending to use `cellDataType` auto inference then you can set the following in your default col Def

```
cellDataType: false,
```

Alternatively set the following on your filename column to tell the grid this is a `text` column.

```
cellDataType: 'text',
```

The bug is that the filename contains a date and our inference logic then sets the column as a dateString incorrectly. We will raise this internally.

**Comment by StephenCooper** [comment]
fyi, this should be fixed in the next release which is due out next week.
