### ISSUE TITLE
AgGrid Enterprise ServerSide Row Model NodeJS OData

### ISSUE THREAD

**Issue by syed-saad-zahidi** [ag-grid/ag-grid#6837]
I'm using AgGrid Enterprise React with serverside row model. My backend Api is on NodeJS Server with sequalize and OData . Do i have to write customer filter for each columns like  in Agrid it is contains I have to convert it to substringof . Do i have to do it to all columns and filter type

**Comment by AG-Zoheil** [comment]
Hi @syed-saad-zahidi,

Thank you for submitting this on Github.

It looks like you are an enterprise user. As we do not provide support on Github but only take bug reports, I would encourage you to raise this via our support portal if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here, as it has been open for quite a while without any further interaction.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support and do NOT have an active AG Grid Enterprise licence, you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
