### ISSUE TITLE
Ag grid React export to Excel and Grand Totals

### ISSUE THREAD

**Issue by ppatliak** [ag-grid/ag-grid#6842]
**I'm submitting a ...**

[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

Hello, everyone!

I`m facing an issue with excel export. I`m using AgGrid with react framework, my grid has groupIncludeFooter: true and groupIncludeTotalFooter: true, and some cellClasses. My rows have zebra striping and everything works fine until I export my grid to Excel. My zebra striping is corrupted because of group footers are not included and I am wondering if there are a way to remove group footers before Excel export or another way to save my zebra striping. Thanks!


**Please tell us about your environment:**
Windows 10, Visual Studio Code, yarn

* **AG Grid version:** X.X.X
27.1.0

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript 4.1.3 | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi @ppatliak,

Thank you for submitting this on Github.

**Excel export** is an enterprise feature. As we do not provide support on Github but only take bug reports, I would encourage you to raise this via our support portal if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here, as it has been open for quite a while without any further interaction.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support and do NOT have an active AG Grid Enterprise licence, you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
