### ISSUE TITLE
MultiFilter Reset all filters?

### ISSUE THREAD

**Issue by ppatliak** [ag-grid/ag-grid#6843]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

Hello, everyone!
I have a column with multifilter and I`m wondering if there is a way to clear all filters of current column? I saw that ag grid supports "Reset" button under every MultiFilter part but that button only resets 1 part of the filter. And can we set position of filter buttons? Thanks!

**Please tell us about your environment:**
Windows 10, Visual Studio Code, yarn

* **AG Grid version:** 27.1.0

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript 4.1 | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi @ppatliak,

Thank you for submitting this on Github.

**Multi Filter** is an enterprise feature. As we do not provide support on Github but only take bug reports, I would encourage you to raise this via our support portal if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here, as it has been open for quite a while without any further interaction.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support and do NOT have an active AG Grid Enterprise licence, you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
