### ISSUE TITLE
As of AG Grid v30: any change to columnDefs (or defaultColDef) will destroy custom column filter components and clear their filter state

### ISSUE THREAD

**Issue by dturcotte** [ag-grid/ag-grid#6878]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

As of AG Grid v30: any change to `columnDefs` (or `defaultColDef`) will destroy custom column `filter` components and clear their filter state.

Reproduced here: https://plnkr.co/edit/rHWQA4njNKzNWRna?open=index.jsx
The above plunker started with one of the server-side examples here: https://www.ag-grid.com/react-data-grid/server-side-model-filtering/ and then included the custom `filter` component from here: https://www.ag-grid.com/react-data-grid/component-filter/ . Then I added a button to simply set a new array reference for `columnDefs` with the exact same content. 

Step 1: Add a filter for the "Athlete" column, for example, type in `Michael`. See that the filter is applied.
Step 2: Click the button above the grid that's labelled "Superficial column change". This button sets a new array reference for `columnDefs` with the same column content (simply `setColumnDefs(defaultColumns.slice())`)
Step 3: See that the filter on "Athlete" is gone.

This issue was introduced by this PR for AG-7227: https://github.com/ag-grid/ag-grid/pull/6613
It seems that the `Column.EVENT_COL_DEF_CHANGED` is being fired when anything at all changes about columns which causes the filter to be destroyed and the filter state reset.

**Expected behavior**

Prior to AG Grid v30, AG Grid was good at handling changes to column defs without being destructive. In the above reproduction steps, Step 3 should still have the "Athlete" filter applied.

It seems to me that the destroy logic that is happening should only occur if the original column is no longer in the updated columns. My opinion is that no matter what changes about columns, if "Athlete" is still in `columnDefs` then the filter state should not be eliminated. For example,  if I search for "Michael" and then add a new column "Age", there's no reason to clear my search for "Micheal".

**Please tell us about your environment:**

* **AG Grid version:** 30.0.3 (enterprise)

* **Browser:**

'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 5.1.6

**Comment by zoheil-ag** [comment]
Hi @dturcotte,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8835 [Regression] When setting a React state variable, any custom filters applied are reset**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
