### ISSUE TITLE
AgGrid Angular 30.0.5 - GroupRowInnerRenderer with material theme not displaying content

### ISSUE THREAD

**Issue by evkw** [ag-grid/ag-grid#6890]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Please see https://plnkr.co/plunk/IMWNHS3m6jbA93kV 

**Current behavior**
Using the ag-theme-material theme, the content of a groupRowRenderer innerRenderer is hidden when row checkbox is clicked and the row is not in the mouse hover state.

![CD335FFF-7993-49DD-980B-00E5EAB0D077](https://github.com/ag-grid/ag-grid/assets/15670238/db1c362d-141e-48d6-9304-ecca6b7cb4fe)

**Expected behavior**
Content should remain visible when row is selected via checkbox and not in hover state

**Please tell us about your environment:**
* Windows 11

* **AG Grid version:** 30.0.5

**Browser:**
* 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

**Comment by zoheil-ag** [comment]
Hello @evkw,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8945[Cell Rendering] When using groupRowRenderer and checkboxes in Angular, checked row groups are hidden unless hovered over**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
