### ISSUE TITLE
AlwaysShowScrollbar not working in firefox.

### ISSUE THREAD

**Issue by cjstolte** [ag-grid/ag-grid#6935]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible. 

**Current behavior**
Scroll bar disappears or is not existent even when using the "alwaysshowvertical/horizonalscroll" attributes to true. 

From further testing looks like this is an issue limited to firefox. Testing in edge and chrome appear to show the scrollbars

https://www.ag-grid.com/react-data-grid/scrolling-scenarios/ Plunker--> 
https://run.plnkr.co/preview/cll1wfv5u0006356ul4ypdzsf/

**Expected behavior**
The scroll bars should always show.

**Please tell us about your environment:**

WIndows, Firefox 116.0

* **AG Grid version:** X.X.X
AG V: 30.0.6

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Initially noticed with React implementation. But testing with online demos that all instances, JS, React, Angular, Vue, etc. seem to have issues.

https://www.ag-grid.com/react-data-grid/scrolling-scenarios/

**Comment by zoheil-ag** [comment]
Hello @cjstolte,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-AG-9053 [Scrolling] When using Firefox alwaysShowHorizontalScroll and alwaysShowVerticalScroll properties are not working**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by cjstolte** [comment]
@zoheil-ag Thanks for the update and the information. Sadly not ideal but I completely understand and can see the documentation regarding this as well as sand-boxing. Not ideal to tell every user to enable a windows feature to get it to work, but since its a user(s) requesting it always show that is what they will have to do haha. 

Might not hurt to add this to documentation if it wasn't already as it was frustrating trying to get it work based on existing documentation to then see it was truly working in other browsers (and can now confirm once I enable the windows feature for firefox).

**Comment by zoheil-ag** [comment]
Glad to hear that's worked for you @cjstolte.

Thank you for the feedback, we will look to make our documentation more helpful in this regard.

**Comment by harshalPWebiots** [comment]
still facing issue on ubuntu
