### ISSUE TITLE
Docs: Broken install link

### ISSUE THREAD

**Issue by sebammon** [ag-grid/ag-grid#6939]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When clicking the link [install with NPM](https://www.ag-grid.com/react-data-grid/npm/), the link is broken.

**Start page:**

<img width="861" alt="image" src="https://github.com/ag-grid/ag-grid/assets/50615191/866bcb83-a30b-422d-8ce9-92e5309de5b9">

**Broken page:**

<img width="737" alt="image" src="https://github.com/ag-grid/ag-grid/assets/50615191/55c669eb-069f-4fd1-bf62-0c355f851477">

**Expected behavior**

The link isn't broken and there are instructions.

**Comment by zoheil-ag** [comment]
Hello @sebammon,

Thank you for reporting this - much appreciated!

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-9065 [Docs] Install with NPM React link leads to empty page**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
