### ISSUE TITLE
[rowHeight] option is broken starting from v30.0.5 ag-grid for angular

### ISSUE THREAD

**Issue by vstepanenko** [ag-grid/ag-grid#6952]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Starting from ag-grid version 30.0.5 for Angular property [rowHeight] doesn't work correctly. Row height is applied to all the rows except the first one. First row height stays default (the one from css styles). So, the grid is displayed incorrectly.

The example with the issue is provided in plunker (see the first row in the grid):
https://plnkr.co/edit/xW3ihCmfP9fYIvnJ?open=app%2Fapp.component.ts&preview

**Expected behavior**
[rowHeight] option works correctly as it worked before version 30.0.5

**Please tell us about your environment:**
macOS Ventura Version 13.5

* **AG Grid version:** 30.0.5, 30.0.6

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

* **Language:** Angular, TypeScript

**Comment by zoheil-ag** [comment]
Hello @vstepanenko,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-9137 - [Regression] When setting rowHeight in infinite row model, the first row does not get affected**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by vstepanenko** [comment]
Additional clarification: It's not only the first row, it also depends on cacheBlockSize option. If [cacheBlockSize]="200" then the firsr row in each 200 items will not have proper height, e.g 0, 200, 400... In the plunker example I provided cacheBlockSize is set to 100, so rows with indices 0, 100, 200, 300... have incorrect height.
