### ISSUE TITLE
Ag-Grid for angular, "valueFormatter" is altering the values when exporting.

### ISSUE THREAD

**Issue by andrew962** [ag-grid/ag-grid#6960]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[x] support request => see 'Requesting Community Support'
```
Providing a Reproducible Scenario
https://plnkr.co/edit/qJSzpwrZyL3yu0Uv?open=app%2Fapp.component.ts&preview

Current behavior

The issue that is occurring is that when applying the "**valueFormatter**" property, it is not only modifying the value displayed in the cell, but it is also altering the value when exporting the grid. This contradicts the documentation which states, "Not used for CSV export or copy to clipboard, only for UI cell rendering."

Expected behavior
What I expect is for the "**valueFormatter**" not to modify the values when exporting.

Please tell us about your environment:
MacOS 13.4.1

Local
AG Grid version: 30.0.3
Reproducible example
AG Grid version: 30.0.6

Browser:
Google Chrome Google Chrome

Language:
Angular 16.1.4, Typescript 5.1.6

**Comment by zoheil-ag** [comment]
Hi @andrew962,

Thank you for getting in touch about this.

CellDataTypes are on by default (read about it [here](https://ag-grid.com/javascript-data-grid/cell-data-types/#enable-cell-data-types)). When cellDataTypes are enabled, and a valueFormatter is used we automatically set useValueFormatterForExport as `true` and hence export the value inclusive of the valueFormatter changes (read about it [here](https://ag-grid.com/javascript-data-grid/cell-data-types/#pre-defined-cell-data-types)).

So to clarify, the key to understanding this behaviour is this:

All the cell data types set the following (unless specified):

- useValueFormatterForExport = true.

Kind regards,
Zoheil

**Comment by fcaballero** [comment]
We're encountering the same issue with React. We recently upgraded from version 28 to the latest version, which has resulted in all our grids exporting formatted numbers instead of their actual values. According to the [documentation](https://ag-grid.com/react-data-grid/value-formatters/#use-value-formatter-for-export), it appears that one needs to explicitly enable this behavior, but it seems to be enabled automatically when using `valueFormatter` as you explained in the previous comment, which is somewhat unexpected.

I attempted to address this by setting `useValueFormatterForExport` in the `defaultColumnDef`. However, it appears that this setting gets overridden due to our use of `valueFormatter` in the column definitions. In my opinion, there may be a bug in this behavior. If one sets `useValueFormatterForExport: false` in the `defaultColumnDef`, I would expect this setting to be respected unless explicitly defined as `true` in the individual column definitions. It seems counterintuitive for it to be automatically changed solely because `valueFormatter` is utilized. If you believe this is not a bug, please provide an alternative solution that doesn't require us to refactor all of our column definitions.

Here is a plunk with the issue: https://plnkr.co/edit/8NHDEdTjYPJbRupt?open=index.jsx&preview

**Comment by AG-Zoheil** [comment]
Hi @fcaballero,

Thank you for your comment.

Currently the `cellDataTypes` would override any `defaultColDef` setting. This is not a bug, however what we are looking to change in the near future is to set `useValueFormatterForExport` to `true` by default in all cases, deprecate the property and introduce a new suppress property. This way you will be able to suppress it via the `defaultColDef` without the `cellDataTypes` overriding it.

In the meantime, the only options are to set it to `false` on a column level or to provide your [custom cell data types](https://ag-grid.com/javascript-data-grid/cell-data-types/#providing-custom-cell-data-types) to overcome this behaviour.

Kind regards,
Zoheil

**Comment by fcaballero** [comment]
Hi, Thank you for your reply, the custom cell data type made the trick, unfortunately the typing complains about using `useValueFormatterForExport` and forced me to use `as any`.

` Object literal may only specify known properties, and 'useValueFormatterForExport' does not exist in type 'DataTypeDefinition<any>'.`

```
dataTypeDefinitions: {
        number: {
          useValueFormatterForExport: false,
        } as any,
      },
```

Cheers

**Comment by AG-Zoheil** [comment]
Hi @fcaballero,

Your definition for the cellDataType is incorrect. For future cases, please have a look at the documentation I linked in my previous comment to make sure you define it properly.

For your use case this time you'll be able to use this:

```
dataTypeDefinitions: {
  number: {
    baseDataType: 'number',
    extendsDataType: 'number',
    columnTypes: 'numberType'
  }
},
columnTypes: {
  numberType: {
    useValueFormatterForExport: false
  }
},
```
Hope this helps!
