### ISSUE TITLE
[Documentation Verification] -- Row Model Server-Side with client side filtering

### ISSUE THREAD

**Issue by titus-anromedonn** [ag-grid/ag-grid#6963]
The documentation [here](https://www.ag-grid.com/angular-data-grid/row-models/#row-model-comparisons) states that you can have `client OR server` sorting and filtering when using the `Server-Side` Row Model. 

Can anyone from the team or community verify this? I have been unable to reproduce the client side filtering functionality when using server side. 

It appears as though the `getRows()` method, on the server side  datasource, always provides the current filters and sorting as metadata parameters under the `params.request` object and expects the server to fulfill the filtering and sorting functionality. This also appears to also trigger a fresh request on any filter change. 

Am I misunderstanding the documentation or should you still be able to do client side filtering using the `Server-Side` Row Model?

Thanks!

**Comment by zoheil-ag** [comment]
Hi @titus-anromedonn,

Thank you for raising this valid question.

Client-side sorting/filtering in SSRM is possible only when loading all the data at the given level. This is because you need to have loaded all the rows for all expanded levels if you are to sort them on the client. This can be activated by setting `suppressServerSideInfiniteScroll=true`. You can see this here: https://plnkr.co/edit/qYn4TtiHwUlQInQY?open=main.js.

Note all the rows are loaded at the start (when you scroll there's no more requests sent), and clicking a column header sorts the column without any server-side refresh. This isn't a setup we would necessarily recommend except for special circumstances, hence we would always direct users to server-side sorting/filtering in the first place (and in most of our documentation).

I hope this answers your question.

Kind regards,
Zoheil

**Comment by richardoey** [comment]
I think @titus-anromedonn has a point. After adding `suppressServerSideInfiniteScroll=true`, client-side **sorting** works, but **not the client-side filtering**. Even after adding `suppressServerSideInfiniteScroll=true`, filtering will request again data so client-side filtering never happens actually. 

I fork above plunk project and adding filtering on the 'Country' column. You can see the filtering here: https://plnkr.co/edit/TBhz8gFaWn5RnR7k?open=main.js 

You can try to use the filtering, but the filtering doesn't work properly.

**Comment by AG-Zoheil** [comment]
Hi @richardoey,

You are correct. I've edited my response above to reflect that it is only applicable for sorting and not filtering.

Thank you!
