### ISSUE TITLE
Column Grouping Resets

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#6989]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
On updating column definitions using **setColumnDefs** on **onColumnGroupOpened** event, the columnGroupShow state is reset.
1)Collapse the Sports Group
2)The group expands/open back when updating column definitions
https://plnkr.co/edit/BFPtn8gMLjt8Lq3j?open=index.tsx

In version before 30.0.0, there was no issue, the group expand state didn't reset.
https://plnkr.co/edit/WYd5Z9WHtMUruKIA?open=index.tsx

**Expected behavior**
Should be able to update column definitions on any grid event without affecting any other columns and its definitions

* **AG Grid version:** 
* 30.1.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React + TypeScript

**Comment by zoheil-ag** [comment]
Hello @melon2504,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-9222**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
