### ISSUE TITLE
bodyScroll event doesn't fire when I zoom the screen

### ISSUE THREAD

**Issue by hanguyenthanh** [ag-grid/ag-grid#6991]
I use bodyScroll for ag-grid :
 <ag-grid-angular id="dashboardGrid" #agGrid style="height: calc(100vh - 250px); width: 100%;  " class="ag-theme-balham"
      [gridOptions]="gridOptions" 
      [columnDefs]="columnDefs" 
      [rowData]="rowData"
      (gridReady)="onGridReady($event)" 
      (rowDataChanged)="onRowDataChanged($event)"
      (bodyScroll)="onBodyScroll($event)"
      [pagination]="false"  >
    </ag-grid-angular>

bodyScroll is fired if I dont zoom the screen, but If I zoom screen, the event is not fired.
Do you know how to fix it?

We have a license for AG-Grid

I tried to use ag-grid v25, v26

Thanks

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for submitting this on Github.

It seems like you are an enterprise user. As we do not provide support on Github but only take bug reports, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here, as it has been open for quite a while without any further interaction.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support and do NOT have an active AG Grid Enterprise licence, you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
