### ISSUE TITLE
First row height bug with infinite row model type

### ISSUE THREAD

**Issue by Kouty** [ag-grid/ag-grid#6993]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
After upgrading ag-grid  30.1.0, grids with rowHeight set and  rowModelType={'infinite'} have first row height not set, and renders incorrectly

**Providing a Reproducible Scenario**
https://plnkr.co/edit/4ZLilldvwstrHPaP?open=index.tsx

**Current behavior**
First row height is wrong

**Expected behavior**
First row height should be set.

**Environment:**
Ubuntu 22.04.3 LTS;
React 18.2.0;
Node v16.17.1;

* **AG Grid version:** 30.1.0

* **Browser:**
"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0"
'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'

* **Language:** TypeScript 4.9.5

**Comment by zoheil-ag** [comment]
Hello @Kouty,

Thank you for reporting this - much appreciated!

We already have this bug in our backlog and we are tracking it with the following reference: **AG-9137**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
