### ISSUE TITLE
AG Grid 30.1.0 Integrated Range Charting issue for Nested Data Structure

### ISSUE THREAD

**Issue by Vishwas-93** [ag-grid/ag-grid#7020]
<img width="498" alt="Screenshot 2023-09-06 at 11 40 21 PM" src="https://github.com/ag-grid/ag-grid/assets/25495706/bbedc894-e0d4-4dce-9cdf-a1c11d6b7cc1">

**I'm submitting a bug report**  (check one with "x")

**Customers of AG Grid**

We have been using AG Grid integrated charting and the latest upgrade to version 30.1.0 seems to broken the built-in charting feature for us.

Currently our data structure is nested. 

Example: column definition: [{ field: 'data.country', width: 150, chartDataType: 'category' }]
Example: Row Data: [{data:{country: 'Ireland'}}]

Trying to create an Integrated Range Chart displays no data at all. This is reproducible and here is a link to the Plunker

https://plnkr.co/edit/0lQe3pCTvrj8z0Kr?open=index.jsx

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Current behavior**
Does not show any data inside the charting component
https://plnkr.co/edit/0lQe3pCTvrj8z0Kr?open=index.jsx

**Expected behavior**
Needs to show the data inside the charting component as the data is being read into the grid even with the nested structure
https://plnkr.co/edit/7QS6EBadfVjL1R3P?open=index.jsx

* **AG Grid version:** 30.1.0

* **Browser:**
Any Browser

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
*Typescript/ Javascript

**Comment by AG-Zoheil** [comment]
Hello @Vishwas-93,

Thank you for reporting this.

Currently there's no way to implement complex object fields with integrated charts. This is due to a change from version 29.3.5. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference and description:
**AG-9042 [Charts] Allow integrated charts to work with complex object fields**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi @Vishwas-93,

Thanks for messaging about this. There was a label missing internally, we've now updated it. It might take some time, but you should be able to see it soon.

Kind regards,
Zoheil
