### ISSUE TITLE
`OverlayWrapperComponent.hideOverlay()` breaks React component lifecycle assumptions

### ISSUE THREAD

**Issue by mleibman-db** [ag-grid/ag-grid#7028]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Repro:**
`OverlayWrapperComponent.hideOverlay()` seems to not be handling consecutive/multiple calls to `showLoadingOverlay()`/`showNoRowsOverlay()` and `hideOverlay()` correctly. If multiple calls are made in the same frame / VM turn, previous overlay content stays in React's render tree. The actual DOM nodes are removed via a `clearElement(this.eOverlayWrapper)` call, but the React component remains in mounted, and none of its lifecycle hooks run.

This usually doesn't result in any visible issues since the DOM nodes **are** removed, but if components used in the overlay have any logic that relies on component lifecycle hooks, this introduces subtle and hard-to-debug bugs.

See [screen-capture.webm](https://github.com/ag-grid/ag-grid/assets/140462999/5c8b22ba-c15a-4855-bc28-37dfa6da7e6d) for a recording of a simple repro on https://www.ag-grid.com/examples/reactui/all-customisations/index.html.

**Current behavior**
React component used for displaying a spinner should remains in the render tree after `hideOverlay()` is called. The DOM node is removed directly w/o invoking a React update.

**Expected behavior**
React component used for displaying a spinner should get removed after `hideOverlay()` is called.

**Please tell us about your environment:**

* **AG Grid version:** latest

* **Browser:** all

* **Language:** all

**Comment by AG-Zoheil** [comment]
Hello @mleibman-db,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-9318**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
