### ISSUE TITLE
Multiple grid dropzones

### ISSUE THREAD

**Issue by saadimon** [ag-grid/ag-grid#7042]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
[https://plnkr.co/edit/o5agxAvDBbUKMPk1?preview](https://plnkr.co/edit/o5agxAvDBbUKMPk1?preview
)

**Current behavior**
Adding multiple grid based dropzones causes an error when trying to drop a row from one grid to another.

**Expected behavior**
I can drop a row from one grid to multiple other grids

**Please tell us about your environment:**
macOS Ventura 13.4

* **AG Grid version:** 18.1.2

* **Browser:**
Chrome

* **Language:*** [all]

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-9354**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
