### ISSUE TITLE
Row indexes are invalid in cellRenderer params after filtering the grid

### ISSUE THREAD

**Issue by styckalov** [ag-grid/ag-grid#7045]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Here is the [Plunkr ](https://plnkr.co/edit/9RmW1f47pU0zJxFX?open=index.tsx&preview).
To reproduce the issue you need to filter "Age" column with  "less than 20" value, and try to edit first, third or fourth record.
If you made all of the steps correctly editing will start in different cell.

![image](https://github.com/ag-grid/ag-grid/assets/38156321/6cabc8ff-92c5-45db-a56a-db45dd5e0701)

**Current behavior**
After filtering the grid some row indexes are invalid

**Expected behavior**
After filtering the grid all row indexes need to be up to date

**Please tell us about your environment:**
Windows 10, Webstorm, npm

* **AG Grid version:** 30.1.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

* **Language:** [all]

**Comment by AG-Zoheil** [comment]
Hello @styckalov,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-9317**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi @styckalov,

Just to update you we have adjusted our examples in our documentation to use the rowIndex from the node instead of the params as this will be the correct approach. This will be released in our next version.

Meanwhile if you wish to get your example working you need to get the rowIndex from the node.
I have adjusted the cellRenderer file in your original plunker - you can see it [here](https://plnkr.co/edit/owA3dwTJgksttgbS?open=main.js).

I hope that helps.

Kind regards,
Zoheil
