### ISSUE TITLE
Server-Side Data don't work well. I need help. 

### ISSUE THREAD

**Issue by shvezigor** [ag-grid/ag-grid#7061]
Hello.

I have some problems in the work of Ag-grid.

I'm trying to work with Server-Side Data.
I use ag-grid on Vue.

I'm interested in how the next call to the getRows function happens, because it's called only the first time. When I scroll, nothing happens.

In the examples, I saw that in the startRow and endRow parameters, the values are initialized, but in mine they are undefined

Thansk.

**Comment by shvezigor** [comment]
I use version 28.2.0. I think there is a bug in this version. All examples in the documentation come with the latest version.

**Comment by AG-Zoheil** [comment]
Hi @shvezigor,

Thank you for submitting this on Github.

I can see you have mentioned you're using AG-Grid version **28.2.0**, which is quite old. Our current latest version is **30.1.0**.

I would highly recommend upgrading the version of AG-Grid in your application so that you can benefit from all the improvements in functionality, stability, theming and performance we've made since the version you're using. This is even more so the case since you have mentioned your expected behavior is present in the latest version from our documentation.

Also, I'd recommend to upgrade the AG-Grid version sooner rather than later to avoid having even more changes to make as part of the upgrade process.

Kind regards,
Zoheil

**Comment by shvezigor** [comment]
Hello.
Tell me why this functionality works in version 27.3.0 and it does not work in versions 28.0.0 to 30.0.0?
Version 27.3.0. we have no right to use. It turns out that we bought a non-working version?

**Comment by AG-Zoheil** [comment]
Hi @shvezigor,

Thank you for your comment.

The grid naturally goes through changes with each version. At times these changes will have overarching effects on other parts of the grid. Most of the time this is intentional and documented and sometimes this can happen inadvertently.

AG Grid is committed to fixing bugs when identified in the latest current version. This means that there may be a bug introduced, that then gets fixed and hence it will only be present in certain version and not in version before or after it.

You've mentioned you have bought AG Grid. If you are still an active Enterprise user I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Kind regards,
Zoheil
