### ISSUE TITLE
Server-side row model: selected rows in the grid remain selected even if the row is removed

### ISSUE THREAD

**Issue by dturcotte** [ag-grid/ag-grid#7098]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

See this plunker reproducing the issue: https://plnkr.co/edit/Zfk2v7WaA6SRt1L2?open=index.jsx
(The plunker was branched off of this example from the docs https://www.ag-grid.com/react-data-grid/server-side-model-updating-refresh/#simple-example)

We're using server-side row model. There is app behavior that can cause rows to be removed from the dataset. When that happens, I clear all caches including calling `refreshServerSide({ purge: true })`. This causes the grid to request the rows again and the data is updated accordingly. 

However, if any of those rows were selected, they remain selected in the grid. `getSelectedRows` still returns the now-removed rows and `onSelectionChanged` is not called.

**Expected behavior**

A common use case for us is bulk deleting rows in the grid:
1. Enable rowSelection="multiple"
2. User selects some rows and clicks a "delete" button
3. After the delete request is successful, we refresh rows via `refreshServerSide({ purge: true })`
4. The rows are gone from the grid, and the rows should *no longer be selected*

**Please tell us about your environment:**

OSX, VSCode, yarn

* **AG Grid version:** X.X.X

30.2.0

* **Browser:**

'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 5.2.2

**Comment by AG-Zoheil** [comment]
Hello @dturcotte,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-9447**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hello,

We've had a more detailed look at this and can provide the following update:

Purge is designed to be used at a path level, not as a global wipe-out. The purge of rows should be separate from row selection, so if the previously selected rows get reloaded after the purge, they’re still selected.

If you'd like to clear selection state, you can just set an empty selection object, or deselect all rows. We would not recommend to link this to purge, and it’s documented already [here](https://ag-grid.com/react-data-grid/server-side-model-updating-refresh/#simple-example).

Therefore we will be closing this Jira.

Kind regards,
Zoheil
