### ISSUE TITLE
Regression: overflowed content not displayed beyond cell boundaries

### ISSUE THREAD

**Issue by Eugeno** [ag-grid/ag-grid#7130]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
1. Add `overflow: visible` to the cell.
2. Place any object within the cell that exceeds the cell's dimensions.

**Current behavior**
![image](https://github.com/ag-grid/ag-grid/assets/23382920/2ec25c52-800d-42ed-aa06-b603fc0bb8cb)

**Expected behavior**
This should behave as it did in version 30.1.0 and earlier:
![image](https://github.com/ag-grid/ag-grid/assets/23382920/d1e7bb79-fe65-4e4a-8d7a-ab3858e3443c)

* **AG Grid version:** 30.2.0

**Comment by AG-Zoheil** [comment]
Hi @Eugeno,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by Eugeno** [comment]
@AG-Zoheil here are two demos, where the only difference is the ag-grid version:
https://stackblitz.com/edit/stackblitz-starters-ntb7l9
https://stackblitz.com/edit/stackblitz-starters-e84t4j

As you can see, in the first one, the overflow works as expected (and it has been working this way for years), while in the second one, the content gets clipped.

**Comment by AG-Zoheil** [comment]
Hello @Eugeno,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-9607**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
