### ISSUE TITLE
Print bug when grid uses absolute position to hide other elements on page

### ISSUE THREAD

**Issue by jacobg** [ag-grid/ag-grid#7134]
Steps:
1) Design web page that has ag-grid along with other elements.
2) Print grid by hiding other page elements, and absolute position grid to top-left corner.

Expected behavior:  Grid prints properly on page.
Actual behavior: Each page break duplicates rows, and a row is squished 3/4 down the page. (see screenshot below)

Code sample: https://codesandbox.io/s/print-ag-grid-absolute-simpler-ywn2qs?file=/src/App.vue

<img width="1107" alt="24reO" src="https://github.com/ag-grid/ag-grid/assets/736985/e27b80e2-8d47-4d02-aabf-b5fdb4d7b4d0">

**Comment by jacobg** [comment]
Hi @AG-Zoheil ,

Thanks for the follow up.

The first 2 steps you list are all that is needed. Margins can be left at default. Please see screenshots below of first 3 pages of preview in Mac Chrome. First page looks fine, and prints rows 0-45. Page 2 rewinds to row 35, and continues to row 58. It then prints only part of row 59, and then skips to row 71-82. Page similarly rewinds to 71, and has similar pattern. Subsequent pages have the same issue. Are you seeing something different?


<img width="1500" alt="Screenshot 2023-10-12 at 10 35 16 AM" src="https://github.com/ag-grid/ag-grid/assets/736985/e4ab814e-fdbd-4abf-ba9d-bcd59b3245bc">


<img width="1505" alt="Screenshot 2023-10-12 at 10 35 24 AM" src="https://github.com/ag-grid/ag-grid/assets/736985/bde11318-84a5-42ec-9340-6a55215eee98">


<img width="1499" alt="Screenshot 2023-10-12 at 10 35 31 AM" src="https://github.com/ag-grid/ag-grid/assets/736985/4e9dff62-7d01-4773-a384-91ab84cd4827">

**Comment by AG-Zoheil** [comment]
My apologies, I see what you mean now.

I have added this bug to our backlog and we are tracking it with the following reference: **AG-9555**.

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by jacobg** [comment]
Thank you @AG-Zoheil !
