### ISSUE TITLE
className error with ag-grid-solid + SolidStart

### ISSUE THREAD

**Issue by davedbase** [ag-grid/ag-grid#7154]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Simple installing `ag-grid-solid` into our SolidStart codebase triggers the following error:

![Screenshot 2023-10-16 at 2 49 28 PM](https://github.com/ag-grid/ag-grid/assets/1168397/cd93c04a-0639-4387-946b-51153bd39ec7)

Here's a reproduction you can work off of: https://stackblitz.com/edit/github-1hzw7w?file=src%2Froutes%2Findex.tsx

**Expected behavior**
It should load ag-grid-solid and build the component.

**Please tell us about your environment:**
MacOS

* **AG Grid version:** X.X.X
Latest version + latest version of ag-grid-solid

* **Browser:**
Chrome/Brave

**Comment by davedbase** [comment]
@AG-Zoheil any word on a possible patch for the issue? I'm prototyping AG on Solid for a customer who might want to upgrade to Enterprise and this is a blocker to convincing them.

Thanks.

**Comment by davedbase** [comment]
@StephenCooper thanks for the quick reply!

Those are basic Solid apps using Vite and they work as expected. The issue I'm experiencing is related to SolidStart, the Solid meta-framework. The reproduction I sent provides an example for it.

I do believe this is packaging issue though. We're investigating on our end as well.

**Comment by seanlandsman** [comment]
The problem lies in the fact the project supplied defaults to using SSR and AG Grid is a client side only library.

If you take a look at this solid-start created project here (with SSR disabled) you'll see that the grid works fine: https://github.com/seanlandsman/ag-grid-solid-start

If you're going to use SSR you'll need to check and prevent rendering of the grid when not rendering to the client. The library will expect certain functionality to be available which won't exist when on the server.

**Comment by AG-Zoheil** [comment]
Hi @davedbase,

Thank you for you detailed reply.

At this point in time we are unable to take any feature requests via GitHub. This can change over time.

We thank you for your feedback and we apologise the proposed solution does not meet all of your requirements.

Kind regards,
Zoheil
