### ISSUE TITLE
AgGrid crashes when using useMemo with defaultColDef

### ISSUE THREAD

**Issue by sajinshrestha** [ag-grid/ag-grid#7158]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

Yes, we have a license for ag-grid-enterprise (version ^30.2.0) but I don't access to Zendesk.

**Current behavior**

When `defaultColDef` is used with the `useMemo` hook, AgGrid crashes with the 'Cannot read properties of undefined (reading 'some')' type error. However, when a plain object is used to define defaultColDef, the grid works as expected.

***Error***
```

TypeError
Cannot read properties of undefined (reading 'some')
SortService.sort
https://ftcssc.csb.app/node_modules/ag-grid-community/dist/ag-grid-community.auto.esm.js:52330:67
SortStage.execute
https://ftcssc.csb.app/node_modules/ag-grid-community/dist/ag-grid-community.auto.esm.js:52163:22
ClientSideRowModel.doSort
https://ftcssc.csb.app/node_modules/ag-grid-community/dist/ag-grid-community.auto.esm.js:51818:20
ClientSideRowModel.refreshModel
https://ftcssc.csb.app/node_modules/ag-grid-community/dist/ag-grid-community.auto.esm.js:51539:14
ClientSideRowModel.setRowData
https://ftcssc.csb.app/node_modules/ag-grid-community/dist/ag-grid-community.auto.esm.js:51918:10
GridApi.setRowData
https://ftcssc.csb.app/node_modules/ag-grid-community/dist/ag-grid-community.auto.esm.js:21804:31
GridApi.__updateProperty
https://ftcssc.csb.app/node_modules/ag-grid-community/dist/ag-grid-community.auto.esm.js:21663:29
eval
https://ftcssc.csb.app/node_modules/ag-grid-community/dist/ag-grid-community.auto.esm.js:5288:18
ComponentUtil.processOnChange
```

**Steps to Reproduce**
1. Go to https://codesandbox.io/s/ag-grid-packages-forked-ftcssc?file=/src/GridExample.tsx
2. Click on the 'Page Two' button to fetch new row data. A loading fallback component is displayed while the data is being fetched. 

**Expected behavior**
Using `useMemo` with defaultColDef should not crash the grid.

**Please tell us about your environment:**

* **AG Grid version:** 30.2.0

* **Browser:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

* **Language:** [TypeScript 4.8.4 | ES6 ]
* **React Version:**  18.2.0

**Comment by StephenCooper** [comment]
Thats an interesting issue, which we can look into more butI believe this change resolves the issue for this. It is adding a key that is the fix. 

```
const GridExample = ({ id, defaultColumnDef = {} }) => {
  const rowData = use(fetchData(id));
  return <Grid key={id} rowData={rowData} />;
};
```

https://codesandbox.io/s/ag-grid-packages-forked-hv4lnl?file=/src/GridExample.tsx:300-443

**Comment by AG-Zoheil** [comment]
Hello @sajinshrestha,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-9608**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
