### ISSUE TITLE
Add Column Filtering config option to allow applying with only the values filtered by Mini Filter

### ISSUE THREAD

**Issue by prdxs** [ag-grid/ag-grid#7163]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
When using the Set Filter for Column Filtering and using the Mini Filter to filter the column values you want to select, once you've filtered the values, when you apply, you don't really filter by the visible values.

**Expected behavior**
It would be very useful for my use case if, when using the mini filter to filter column values, you can just apply after filtering.

**Please tell us about your environment:**
MacOS Ventura 13.5

* **AG Grid version:** X.X.X
26.2.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

The mini filter is an enterprise feature. As we do not provide support on Github but only take bug reports, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here, as it has been open for quite a while without any further interaction.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support and do NOT have an active AG Grid Enterprise licence, you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
