### ISSUE TITLE
alwaysShowVerticalScroll doesn't work

### ISSUE THREAD

**Issue by haskelcurry** [ag-grid/ag-grid#7165]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Steps to reproduce**
On MacOS:  
1. Make sure to enable the scrollbars visibility in System Settings ▸ Appearance.
2. Open the "Make scrollbars always visible" documentation page on MacOS: https://www.ag-grid.com/javascript-data-grid/scrolling-scenarios/#make-scrollbars-always-visible
3. See that scrollbars are still not visible, even on the docs demo page:
<img width="791" alt="Screenshot 2023-10-18 at 17 54 30" src="https://github.com/ag-grid/ag-grid/assets/8557753/824b9897-849c-43ff-8ca7-382f59d04847">

**Current behavior**
alwaysShowVerticalScroll=true has no effect

**Expected behavior**
alwaysShowVerticalScroll=true has to make the scrollbars to be always visible

**Please tell us about your environment:**
MacOS Ventura 13.5.1, VIM

* **AG Grid version:** 30.2.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

* **Language:** TypeScript 5.1

**Comment by AG-Zoheil** [comment]
Hi @haskelcurry,

Thank you for raising this on Github.

We've attempted to replicate the behaviour you are describing. 

Please note that the default MacOS behaviour when the "Always show scrollbar" setting is on is to only show the scrollbar if the page is scrollable. For example, browser any other website that fits into your screen and doesn't need scrolling. You will see that no scrollbar is displayed. Due to this, AG Grid is unable to override this default behaviour.

So `alwaysShowVerticalScroll=true` on MacOS works in the following manner:

Page scrollable: Always hows vertical scrollbar even when not currently scrolling
Page not scrollable: Does not show scrollbar due to MacOS default behaviour

I hope the above clarifies the matter.

Kind regards,
Zoheil

**Comment by haskelcurry** [comment]
Hi @AG-Zoheil, thank you for your quick reply. I think that this doc page is a little bit misleading in this case, maybe it's better to add more items to the list in this demo?  So that the scrollbar becomes visible on MacOS with "Always show scrollbar" setting on?
