### ISSUE TITLE
RowHeight is changed by setting autoHeight to true

### ISSUE THREAD

**Issue by danielmalaton** [ag-grid/ag-grid#7172]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Suppose the `columnDefs` I have is:
```Typescript
columnDefs = [
  {
    field: 'x', wrapText: true, autoHeight: false,
  },
];
```
I want to change the `x` columns to have `autoHeight` true like:
```Typescript
columnDefs = [
  {
    field: 'x', wrapText: true, autoHeight: true,
  },
];
```

**Current behavior**
The `rowHeight` when `autoHeight` is `true` or `false` are **different**.

**Expected behavior**
The `rowHeight` when `autoHeight` is `true` or `false` are the **same**.
Two questions:
- Why the `rowHeight` between two case are different? 
- Can we make it the same?

**Specification**
* **AG Grid version:** 30.1.0

* **Browser:** Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by danielmalaton** [comment]
Hi @AG-Zoheil,

Thanks for getting back to me again!

I know the `autoHeight` feature with `wrapText` is: when text is not covered in one line, the `rowHeight` is adjusted to fit the text content.

But my question is: even if the text is covered within one line (the content is not cut off) that is `autoHeight: false` when I change it to `autoHeight: true`, it somehow modifies the `rowHeight` (expect it would not).

Here is the plunker example: https://plnkr.co/edit/SfLfeyl4LuH9C51S?open=main.js

When the `autoHeight` is `false`, the row height of the first row is `28px`
When the `autoHeight` is `true`, the row height of the first row is `29.1px`

**Comment by AG-Zoheil** [comment]
Hi @danielmalaton,

Thanks for bearing with us whilst we've looked into this.

The reason why the cell height is `28px` when `autoHeight` is **false**, is because the theme forces it to be so. When we remove the theme constraint to allow natural sizes to be applied, you end up getting the `autoHeight` adjusted value of `29.1px`. There is no way to enforce a size without manually setting the height, that's why the theme does that. If there was a way to guarantee the row to be `28px` tall without enforcing in theme we would do it.

You can try to add some CSS to make it less jumpy, like having
 
```
.ag-cell {
  line-height: 25px;
}
```
 
Doing this will make the row less "jumpy" when switching between `autoHeight` **true/false**, but the text will be slightly offset.

I understand this may not be an ideal solution, but I hope this helps.

Kind regards,
Zoheil
