### ISSUE TITLE
flushSync error when updating Grid UI on state update (useEffect)

### ISSUE THREAD

**Issue by cworsley4** [ag-grid/ag-grid#7187]
[x] bug report => see 'Providing a Reproducible Scenario'

**Providing a Reproducible Scenario**
https://codesandbox.io/s/boring-brook-7hkdll

This sandbox is trying to make a cell editable from a state update. It is doing so by calling `editCell` which is a method that will use the AG Grid API to start editing a cell that is not visible using...
 - ensureIndexVisible
 - ensureColumnVisible
 - setFocusedCell
 - startEditingCell

There are two buttons that call the same `editCell` method
 - "I WILL WORK", which will work every time
   - This button calls `editCell` when clicked. This does not update any state, which is key.
 - "flushSync error ONCE SCROLLING IS REQUIRED"
   - This button will NOT work once scrolling is required. When clicked it updates a counter (state) which triggers a `useEffect` hook on the <Grid> component, which will call `editCell`
   - Summary:
     - Click
     - Update state
     - useEffect fires
     - useEffect calls `editCell`

**Current behavior**
When calling `editCell` from an effect or state update, the behavior is erratic, and unpredictable. Sometimes the operation will complete as expected, but most of the time it does not.

**Expected behavior**
The two buttons on the page should have the exact same behavior.
 - The grid should make the cell specified ("summary" is specified in the Codesandbox) visible by scrolling to it
 - The grid should focus the cell
 - The grid should start the cell the editing without error

**Please tell us about your environment:**
CodeSandbox
* **AG Grid version:** 32.2.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

* **Language:** TypeScript X.X (whatever Codesandbox provides)

**Comment by cworsley4** [comment]
I have mitigated this by wrapping calls in setTimeout(callback, 0)

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

We have added this potential bug to our backlog to investigate further and we are tracking it with the following reference:
**AG-10560**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by cworsley4** [comment]
Wonderful! Thank you for putting this on the list. I’ll be tracking :)
