### ISSUE TITLE
Filter applies on check/uncheck during data updates

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#7226]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
In the following example, data updates occur over every few milliseconds. Filter for columns are applied using apply button via filter params.
https://plnkr.co/edit/xpLRPbsI8kreFgeg?open=index.jsx

But during data updates if we try to apply filter on a column say **Portfolio**, it's observed that just on check/uncheck of the values the filter event is triggered and gets applied instead of applying click on apply button.

In some cases the filter resets to default instantly in check/uncheck causing unable to set filter at all.

**Expected behavior**
Filter should be applied only on click of Apply button during high transactions of data updates.

* **AG Grid version:** X.X.X
30.2.1

* **Browser:**
Chrome 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React

**Comment by AG-Zoheil** [comment]
Hello @melon2504,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-9616**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
