### ISSUE TITLE
User Created Charts not working with nested data

### ISSUE THREAD

**Issue by chmolto** [ag-grid/ag-grid#7235]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
Charts not representing data from columns with nested fields

**Expected behavior**
It should represent data on the charts like non nested fields

* **AG Grid version:** X.X.X
Any version

* **Browser:**
Chrome

Here I provide I plunkr where you can select a range on columns that are not nested and data will be represented as usual, but if you select the columns I modified for the example which are nested (Gold for example) no data is represented.

https://plnkr.co/edit/LV0YjxmFlQAAhxJz?open=main.js

![image](https://github.com/ag-grid/ag-grid/assets/22659045/0aab5730-ce6c-48bc-9a62-9ccd940b81ab)

![image](https://github.com/ag-grid/ag-grid/assets/22659045/8f9dff09-7e43-433b-9f5b-30f5a8977364)

**Comment by AG-Zoheil** [comment]
Hi @chmolto,

Thanks for raising this on Github.

This is indeed already on our radar and list of things to fix. This happens due to the complex object field which isn't being recognised. We are currently working on a major release for our charts and are hoping to fix as many bugs as possible for it. Please keep an eye out for the next release. 

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out.

Thanks again for bringing this up with us.

Kind regards,
Zoheil
