### ISSUE TITLE
Flicker on master detail sticky header when scrolling 

### ISSUE THREAD

**Issue by Matthematic** [ag-grid/ag-grid#7245]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Currently if you open a master detail for a row and then scroll the container down, the row will stick to the top of the container. This is fine, but there appears to be a custom implementation of the sticky logic rather than css position:sticky, and this means the row has to be created again from scratch. This is slow enough that it causes some flicker since the row, for a split second, doesn't exist. You can see this in the following CodeSandbox: https://codesandbox.io/s/ag-grid-packages-forked-58jfmm?file=/src/index.js

Here is a gif:
 ![ag-grid jitter](https://github.com/ag-grid/ag-grid/assets/6292111/29ff453b-2a37-4458-be08-0964b52076f8)

And here is the individual gif frames before, during, and after the sticky logic is running:
<img width="566" alt="image" src="https://github.com/ag-grid/ag-grid/assets/6292111/53ff2332-6b3e-4f54-928f-ef7e72616326">
<img width="566" alt="image" src="https://github.com/ag-grid/ag-grid/assets/6292111/96465e20-2d66-4a83-99da-f97761965e4d">
<img width="560" alt="image" src="https://github.com/ag-grid/ag-grid/assets/6292111/c00146e0-54e9-4ade-9c00-9eac7397bdd0">

 ### **You can see here clearly that the flicker is caused by the row simply not existing. This can't be solved through traditional means like memoization since the row is being recreated in a completely separate place in the DOM.**

**Expected behavior**
Expect either of two options:
1. The row to seamlessly become sticky without flicker/jitter
2. There is an option to disable the sticky row feature. (I looked and didn't see one - correct me if I'm wrong)

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hello @Matthematic,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-9979**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

However please note, that you are able to disable the sticky row feature. Please see here where `suppressGroupRowsSticky={true}` has been utilised: https://plnkr.co/edit/yHAQuzp9XPwJE79a?open=index.jsx.

I hope this helps. Thanks again for bringing this up with us.

Kind regards,
Zoheil
