### ISSUE TITLE
TreeData mode node.group = false but the node has children

### ISSUE THREAD

**Issue by chris-ace** [ag-grid/ag-grid#7278]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Functions like `getRowStyle` get passed a `params` parameter. This object also holds a reference to the `node` that has a property `group`. Using the TreeData mode, `group` is `false` even though it has children.

We are currently trying to upgrade to v30 from an older version. In our code we used `group` before, but we had to migrate to TreeData mode and now it seems we have to refactor to `allChildrenCount` instead.

**Current behavior**
The following plunker demonstrates the behaviour:
https://plnkr.co/edit/2WCp4hsYFDbyWsoY?open=app%2Fapp.component.ts&preview
`app.component.ts` lines 44-49:
```
getRowStyle = (params) => {
  let style = {};
  if (!params.node.group) style["font-style"] = "italic";
  if (params.node.allChildrenCount > 0) style["font-weight"] = "bold";
  return style;
};
```
All rows are italic (group == false) even though some rows are bold (allChildrenCount > 0).

**Expected behavior**
`group` should be `true` when the node has children.
This is the documentation of the property:
```
/** `true` if this node is a group node (i.e. it has children) */
group: boolean | undefined;
```

**Please tell us about your environment:**
Windows 10, vscode v1.84.1, npm v10.1.0, node 20.9.0

* **AG Grid version:** "ag-grid-angular": "^30.2.1",
* **Browser:** Chrome
* **Language:** TypeScript 5.2.2, target "es2020"

**Comment by tonofre** [comment]
Having a similar issue with the group being set to false when using treeData and the node has children.  Ours seems to only happen when the rowdata is does not contain and filler groups, and our specific issue deals with trying to deselect from a parent level when the grid is filtered and the parent checkbox state is intermediate.  Both groupSelectsChildren and groupSelectsFiltered are set to true but when the selection processing checks if it should skip the row, group is false so the parent nodes end up getting selected when they should be skipped.
We also have grids using treeData where we do use filler groups for the parent nodes, and these appear to be setting the node.group correctly.
AgGridReact Currently in v28.2.1

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for getting in touch.

We've reviewed your suggestion and agree there is a need for clarifying how this is best implemented in our documentation. We have added a feature request for this. The correct approach would be to use `rowNode.hasChildren()` instead of `node.group`.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-10611**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by radekskowron** [comment]
This one is closed but where to find details of the hange? In v30.2.1 when using TreeData and groupSelectsFiltered=true unselecting filtered parent node in indeterminate state does not deselect filtered children. The reason seems to be node.group == false in selectionService

In https://github.com/ag-grid/ag-grid/blob/2c9244d2033c60d62ab975b6c031c70fe2a60dab/community-modules/core/src/selectionService.ts#L119

while hasChildren() is true. I am using v30.2.1 enterprise

**Comment by AG-Zoheil** [comment]
Hi @radekskowron,

Thank you for commenting on GitHub.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Kind regards,
Zoheil

**Comment by Juneeeeeeeeeee** [comment]
Why does `group == false` when the node is a group node indeed? When would this property to be true then?

**Comment by tonofre** [comment]
My issue is the same as [radekskowron](https://github.com/radekskowron).
My work-around so far is to loop through each node and check if it has children and force the group on via setGroup during onGridReady.  This gets past the original filtering issue.  However, we allow for items to be removed, and the parent level keeps its group setting, which appears to cause other issues since it no longer has children...
