### ISSUE TITLE
Export to CSV ag menu option is hidden in apple devices

### ISSUE THREAD

**Issue by mona456** [ag-grid/ag-grid#7296]
**I'm submitting a ...**  (check one with "x")
```
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

**Current behavior**
The export to csv option in ag menu should be seen in all apple devices as well
in desktop it is working fine 
![image](https://github.com/ag-grid/ag-grid/assets/102917906/6cbd5121-1b49-4b6f-a158-a99a88f7c90a)

**Expected behavior**
https://www.ag-grid.com/javascript-data-grid/csv-export/#security-concerns
this website clearly states that the export to csv is enabled by default.

I am using desktop and i see the export to csv option but when i open my website on safari ipad, i dont see the option to export csv.

i tried giving width and height but no luck, attached image

![286152978-c7ef253d-be68-4d39-aac0-eb09b7566ae4](https://github.com/ag-grid/ag-grid/assets/102917906/af7da795-bad8-4df8-8e7e-ea8165414990)

**Please tell us about your environment:**
![image](https://github.com/ag-grid/ag-grid/assets/102917906/a3c7a312-95c4-447e-985d-9ef6e7ca4001)

* **AG Grid version:** X.X.X
    "ag-grid": "^18.1.2",
 "ag-grid-angular": "25.3.0",
    "ag-grid-community": "25.3.0",
    "ag-grid-enterprise": "25.3.0",
    "@ag-grid-enterprise/excel-export": "^25.2.0",

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
*     "typescript": "~4.0.7"

**Comment by AG-Zoheil** [comment]
Hello @mona456,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10013**.

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
