### ISSUE TITLE
Ag grid -accessibility issue in detail cell Element uses  aria-busy true while loading

### ISSUE THREAD

**Issue by ChithiraMG** [ag-grid/ag-grid#7297]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

I was using detail cell in ag grid and its showing aria-required children issue in detail cell
![image](https://github.com/ag-grid/ag-grid/assets/101738825/8e3d0ba0-e934-4c99-9b24-bf0c3ea94d6f)
![image](https://github.com/ag-grid/ag-grid/assets/101738825/6f100796-70ab-4660-aafc-791ce286fd7f)

I have reproduced the same issue in code sand box:
https://codesandbox.io/p/sandbox/distracted-haslett-nxppd2?file=%2Fsrc%2FApp.tsx

Open code sandbox output in new tab and using Accessibility insights for web extension for checking accessibility issues,
run fast pass check

* **AG Grid version:** X.X.X
 "ag-grid-react": "^30.0.0"

**Comment by AG-Zoheil** [comment]
Hi @ChithiraMG,

Thank you for reporting this.
 
The error you see reported by Accessibility Insights for Web is a false positive. 

AG Grid is using a virtualized list to display rows. The use of a virtualized list allows the grid to display an unlimited number of rows without creating DOM elements for each row and cell in the dataset. The virtualization relies on using a much smaller number of DOM elements in order to display the rows visible in the grid at any one time (instead of all rows). This way if the grid is showing 30 rows, the grid creates DOM elements to show the 30 rows and when you scroll new data records are displayed using the DOM elements created before, only now showing a different row. This is explained here:
https://www.ag-grid.com/javascript-data-grid/dom-virtualisation/#inspect-the-dom
 
The virtualization of the list of rows requires that a container element is placed between the filter element and the actual options themselves. AG Grid implements its own custom keyboard navigation, focus handling logic and has the necessary accessibility attributes set to all the necessary elements to ensure they are announced correctly to fully provide the necessary accessibility support when using virtualization.
 
However, Accessibility audit tools such as Accessibility Insights for Web use static DOM analysis and assume that all elements of AG Grid are rendered in the DOM, which isn't the case due to virtualization. Even though AG Grid handles keyboard navigation, focus and accessibility announcements internally and these are correct in terms of the end-user experience, the accessibility audit tools report these as issues, while in fact when the user is using the grid these aren't actual issues.
 
This is why there's no actual accessibility issue, as AG Grid implements accessibility support for the virtualized list using custom code. This is why you can disregard this issue report as a false positive.

I hope this helps.

Kind regards,
Zoheil
