### ISSUE TITLE
Putting Grouping Columns all in the same row

### ISSUE THREAD

**Issue by lgnashold** [ag-grid/ag-grid#7329]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```
As a toy example, let's say I have 3 columns, "City", "Population", and "Neighborhoods". 

Ideally, I want the data to be laid out like this in three columns AG Grid: 
```

> San Francisco | 800,000 | Bernal Heights 
                          | The Mission  
                          | ...
> New York      | 8.5 mil | West Village 
                          | Bed Stuy
```
Since population and the city name are 1:1, they should be on the same row, whereas AG Grid defaults to something like this: 
```
> San Francisco 
    > 800,000
``` 
Expanding or collapsing the group should expand / collapse the list of neighborhoods. 

Note that in our real use case, each neighborhood would have multiple columns associated with it. 

Is there a way to accomplish this in AG Grid (React)? 

We saw [this previous question](https://stackoverflow.com/questions/68462823/how-to-group-by-2-columns-but-have-the-values-on-the-same-row), but the example given seems very hacky and not super robust.

**Comment by AG-Zoheil** [comment]
Hi @lgnashold,

Thank you for submitting this on Github.

Row Grouping is an enterprise feature. As we do not provide support on Github but only take bug reports, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this. Additionally, I'd encourage you to have a look at the example at the bottom of this section as it may display an implementation that meets your requirements: https://ag-grid.com/react-data-grid/grouping-multiple-group-columns/#hide-open-parents

In light of the above, I will be closing this issue here, as it has been open for quite a while without any further interaction.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support and do NOT have an active AG Grid Enterprise licence, you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
