### ISSUE TITLE
After successive grouping and ungrouping operations, the grouping column disappears.

### ISSUE THREAD

**Issue by styckalov** [ag-grid/ag-grid#7337]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

- Open the example: [plnrk](https://plnkr.co/edit/oTSw8TvnmO42egvM?open=index.jsx);
- Expand any row and make sure that Country column is presented;
- Ungroup rows using column header menu;
- Group rows by Country column again;
- Expand any row - Country column is missing;

![image](https://github.com/ag-grid/ag-grid/assets/38156321/7c7772bc-6457-4811-bf09-5bf054a035bb)
![image](https://github.com/ag-grid/ag-grid/assets/38156321/2cdc289e-1c85-40e0-9c42-59e1b3d977a3)

**Current behaviour**
  After successive grouping and ungrouping operations grouped column disappears.

**Expected behaviour**
   After successive grouping and ungrouping operations, column shouldn't disappear.

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

     31.0.0
* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
* **Language:** [all]

**Comment by AG-Zoheil** [comment]
Hello,

Thanks for reporting this on GitHub.
This would be expected behaviour of the manner in which the grouping occurs. In the original state, you've grouped via the colDef but you've chosen explicitly not to hide COUNTRY column. Later you group as a user via the column menu and the COUNTRY column is hidden as per default grouping logic. However, you can still show the COUNTRY column by changing its visibility in the column menu (click reset columns in the column menu).

There is a way however to implement your desired behaviour. You can utilise the following property: https://www.ag-grid.com/javascript-data-grid/grid-options/#reference-columnMoving-suppressRowGroupHidesColumns.

I hope this helps.

Kind regards,
Zoheil
