### ISSUE TITLE
Ag-Agrid accessibility issue with master detail expandable cells

### ISSUE THREAD

**Issue by zohaibkhan22** [ag-grid/ag-grid#7338]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

Plunker link: https://plnkr.co/edit/z5WC6xiJe0P7rifq?open=main.js

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

*When running an accessibility scan from axe deque on an ag-grid using the Master/detail cells, along side the enableCellTextSelection, we are seeing an issue with the expandable cell with the following error message: "Elements must only use supported ARIA attributes".

**Expected behavior**

*We should not be seeing any accessibility issues when running these accessibility scans

**Please tell us about your environment:**

*This is happening across with a variety of versions of chrome across both MAC and Windows PCs

* **AG Grid version:** X.X.X

*28.1.2

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* Language: ES6, React with typescript

**Comment by AG-Zoheil** [comment]
Hi,

Thank for you raising this on GitHub. This was rectified via **AG-7010** in `28.2.0`. Please upgrade your version to benefit from this fix.

Kind regards,
Zoheil

**Comment by zohaibkhan22** [comment]
Hi,

I was able to upgrade our Ag-grid version to 28.2.1. However, the issue is still persisting and being detected during our accessibility scans. Please let me know if there is any other steps I can take to rectify this issue. Thank you. 

Best Regards,
Zohaib

**Comment by zohaibkhan22** [comment]
Hi,

Just following up here. Thank you.

Best Regards,
Zohaib Khan

**Comment by AG-Zoheil** [comment]
Hi @zohaibkhan22,

I have raised this with the team. Please allow us some time to investigate and get back.

Please also note that due to the time of the year, there are leave of absences and reduced working hours in place so it may take a little longer than usual to get back.

We appreciate your understanding.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hello @zohaibkhan22,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10179**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
