### ISSUE TITLE
Ag grid column state accessibility issue

### ISSUE THREAD

**Issue by ChithiraMG** [ag-grid/ag-grid#7342]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Ag grid column state https://www.ag-grid.com/react-data-grid/column-state/ is giving accessibility issues while doing fastpass using accessibility insights for web

accessibility issue
![image](https://github.com/ag-grid/ag-grid/assets/101738825/73f77ec5-d98d-4feb-9949-3e3883cf4c11)

![image](https://github.com/ag-grid/ag-grid/assets/101738825/84879e72-3fb3-4b7d-8464-fef297548b7e)

**Providing a Reproducible Scenario**
https://www.ag-grid.com/examples/tool-panel-columns/simple/packages/reactFunctional/index.html

aggrid: https://www.ag-grid.com/react-data-grid/column-state/

**Comment by AG-Zoheil** [comment]
Hi @ChithiraMG,

Thank you for reporting this.

AG Grid has a number of advanced rendering features such as virtualized rows and columns, pinned columns, pinned rows, sticky rows, etc. In order to present these types of rows/columns, AG Grid uses a number of containers, which are children of the main AG Grid viewport. The DOM structure to represent these containers is fully HTML compliant but in order to implement row and column virtualization uses a specific structure which accessibility audit tools cannot recognize.
 
Accessibility audit tools rely on static DOM analysis and expected a particular items container structure. These tools don't take into account the fact that AG Grid uses valid HTML and manages its own keyboard navigation and rendering which provides full support for accessibility.
 
This is why even though this is marked as an issue by Accessibility audit tools, this isn't an actual issue - the HTML structure is correct, keyboard navigation is fully supported and correct and the announcements generated by screen readers are correct.
 
This is why these reported issues are false positives and there is no actual impact on the accessibility experience of AG Grid - it is actually fully accessible. Please mark this issue as closed on your end.

Kind regards,
Zoheil
