### ISSUE TITLE
Drag handles incorrectly displayed after filtering if rowDragManaged=true

### ISSUE THREAD

**Issue by pmOWI-App** [ag-grid/ag-grid#7343]
**I'm submitting a ...**
```
[X] bug report
[] feature request
[] support request
```

**Providing a Reproducible Scenario:**
It can be reproduced by opening the 'Row Dragging Documentation' at https://www.ag-grid.com/javascript-data-grid/row-dragging/ and looking at the first demo on the page. After filtering 'Country' for anything, the drag handles should disappear for every row that matched the filter. However that is only the case for rows that were previously displayed. After deleting the filter, all drag handles disappear, except for the rows that previously matched the filter. The expected behavior would be that they all reappear.
We could also reproduce this behavior in our angular-application with drag handles and rowDragManaged enabled.
We could not reproduce this behavior after setting rowDragManaged=false.

**Current behavior**
Drag handles are not always disappearing after filtering. Drag handles are not always reappearing after deleting the filter.

**Expected behavior**
Expected behaviour. Drag handles should disappear after filtering. Drag handles should reappear after deleting the filter.

**Please tell us about your environment:**

* _Testing against https://www.ag-grid.com/javascript-data-grid/row-dragging/ :_
Operating system: Windows
**Language**: all
**AG Grid version**: 31.0.0 / 31.0.1
**Browser:** Tested with Chrome, Firefox and other Chromium based browsers (Edge, Brave)

* _Testing against our application:_
Operating system: Windows
IDE: vscode
Framework: angular
**Language**: typescript
**AG Grid version**: 31.0.0
**Browser:** Tested with Chrome, Firefox and other Chromium based browsers (Edge, Brave)

Image from https://www.ag-grid.com/javascript-data-grid/row-dragging/ :

![Screenshot 2023-12-13 104347](https://github.com/ag-grid/ag-grid/assets/153720081/bcc8e412-3ce0-4c0e-8748-49459ddeef5c)

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: AG-10109

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
