### ISSUE TITLE
Cannot read properties of undefined (reading 'setRowData')    at GridApi.setRowData

### ISSUE THREAD

**Issue by gauravpatni123** [ag-grid/ag-grid#7344]
When grid is loading then i am getting the below error in the console.

TypeError: Cannot read properties of undefined (reading 'setRowData')
    at GridApi.setRowData (ag-grid-community.auto.esm.js:31080:37)
    at ag-grid-community.auto.esm.js:4225:39
    at Array.forEach (<anonymous>)
    at ComponentUtil.processOnChange (ag-grid-community.auto.esm.js:4222:14)
    at AgGridAngular.ngOnChanges (ag-grid-angular.js:1350:13)
    at AgGridAngular.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:1521:14)
    at callHook (core.mjs:2444:18)
    at callHooks (core.mjs:2403:17)
    at executeCheckHooks (core.mjs:2335:5)
    at refreshView (core.mjs:10335:21)

AG GRID version : 29.0.0
Angular version :  15 
Browser : Chrome
Language : Typescript

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by gauravpatni123** [comment]
This problem is coming for server side grid, I am not sure if this can be setup in the Plunker . & it won't be possible for me the share the code for the current application. Please let me know if something else i can do on this one.

**Comment by AG-Zoheil** [comment]
Hi @gauravpatni123,

are you able to replicate this with any of the SSRM examples from our website? I'm afraid without a reproducible example we would struggle to support. You can also create a mini-project and share the zip file.

As SSRM is an enterprise feature, if you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for submitting this on Github.

SSRM is an enterprise feature. As we do not provide support on Github but only take bug reports, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here, as it has been open for quite a while without any further interaction.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support and do NOT have an active AG Grid Enterprise licence, you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
