### ISSUE TITLE
chrome86

### ISSUE THREAD

**Issue by bob70510** [ag-grid/ag-grid#7346]
Using Chrome version 86 may encounter issues like Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': '.ag-filter-toolpanel-group-item:not(.ag-filter-toolpanel-group-wrapper, .ag-hidden)' is not a valid selector.

**Comment by AG-Zoheil** [comment]
Hi @bob70510,

Thank you for raising this on GitHub.

Please see our browser support policy here: https://www.ag-grid.com/javascript-data-grid/supported-browsers/#desktop-browsers.

In line with the above, current versions of AG Grid do not support Chrome 86 as this version is more than 3 years old. We highly recommend to upgrade to a newer version of Chrome for security reasons as there may be exploits which are well-publicized for Chrome 86 which may be used by malicious users that are patched in later Chrome versions.

However if you do choose to remain on Chrome 86 you would need to use an AG Grid version that supports that version of Chrome, which in this case would be `24.1.0`.

However, again, we would highly recommend using the latest version of AG-Grid in your application so that you can benefit from all the improvements in functionality, stability, theming and performance we've made since the version you're using.

Kind regards,
Zoheil
