### ISSUE TITLE
I am using aggrid master detail. the master detail arrow does not work on tab change

### ISSUE THREAD

**Issue by digish777** [ag-grid/ag-grid#7365]
I am using ag-grid master detail. the master detail arrow does not work on tab change.
I have placed the ag-grid inside angular material tab control. the master detail works on the open tab. but once the tab is changed. the master detail arrow disappears.  and the detail section is no more available.

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

Master Detail is an enterprise feature. As we do not provide support on Github but only take bug reports, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/hc/en-us) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here, as it has been open for quite a while without any further interaction.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support and do NOT have an active AG Grid Enterprise licence, you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
