### ISSUE TITLE
Docs site scrolls when typing search query

### ISSUE THREAD

**Issue by Den-dp** [ag-grid/ag-grid#7366]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- navigate to https://www.ag-grid.com/angular-data-grid/getting-started/
- scroll the page
- start typing in search widget

**Current behavior**
Docs site scrolls when typing a search query

https://github.com/ag-grid/ag-grid/assets/1770529/0b2ac12a-7af4-42a9-9143-071117215b0c

**Expected behavior**
Typing a search query must not interfere with current scroll position

**Please tell us about your environment:**
Windows 10

* **Browser:**
Google Chrome

**Comment by AG-Zoheil** [comment]
Hello ,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: AG-10165

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
