### ISSUE TITLE
Issue with locale text for 'advancedFilterGreaterThanOrEqual'

### ISSUE THREAD

**Issue by uni-vinay-p** [ag-grid/ag-grid#7368]
I'm trying to change the locale text for **'advancedFilterGreaterThanOrEqual'** from **'>='** to **'Greater than or equal to'** for a custom date filter. However, when I apply the filter, I see the `param.newValue` inside the `valueParser` as **'or'** that is the third string in the locale text instead of the date.

Here's an example of my custom date filter:

```typescript
export const CustomGridDataTypeDef = {
  customDate: {
    baseDataType: 'date',
    extendsDataType: 'date',
    valueParser: (params: any) => {
      if (params.newValue != null) {
        if (params.newValue.match('\\d{4}-\\d{2}-\\d{2}')) {
          const dateParts = params.newValue.split('-');
          return new Date(parseInt(dateParts[0]), parseInt(dateParts[1]) - 1, parseInt(dateParts[2]));
        } else if (params.newValue.match(/^\d{2} \w{3} \d{4} \d{2}:\d{2}:\d{2}$/)) {
          return new Date(params.newValue);
        }
      }
      return null;
    },
    valueFormatter: (params: any) => {
      return params.value == null ? '' : new Date(params.value).toLocaleDateString();
     }
  }
};
```

I expected to see the date when I apply the filter, but instead I see 'or'. 

Please let me know if there's a way to fix this or if there's something I'm doing wrong.

**Comment by AG-Zoheil** [comment]
Hi @uni-vinay-p,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

Advanced Filter is an enterprise feature. As we do not provide support on Github but only take bug reports, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/hc/en-us) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here, as it has been open for quite a while without any further interaction.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support and do NOT have an active AG Grid Enterprise licence, you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
