### ISSUE TITLE
Vue 3 - Attempting to mutate prop "params". Props are readonly.

### ISSUE THREAD

**Issue by pawel-ged-thecodest** [ag-grid/ag-grid#7386]
Hello, i have issue when im trying to update columnDefs with the same renderers. When I use this when the previous column declaration does not contain this column, everything is OK and I see that the custom renderer calls the 'refresh' method. But when I call it twice in a row or when this column already exists, I get an error with the title. It seems that the component is not re-rendered and only the props passed to it are modified. Please help me solve the problem.
```
this.gridApi.setGridOption(
     'columnDefs',
    [
          {
            headerName: 'Entity',
            field: 'entity',
            cellRenderer: 'NewCellRenderer'
          }
        ]
)

```
```
Uncaught TypeError: 'set' on proxy: trap returned falsish for property 'params'
    at DynamicComponent.processMethod (ag-grid-vue3.js?v=9bcdad97:216:55)
    at DynamicComponent.refresh (ag-grid-vue3.js?v=9bcdad97:236:24)
    at CellComp2.refreshCellRenderer (chunk-FFDIUAID.js?v=9bcdad97:32080:38)
    at CellComp2.setRenderDetails (chunk-FFDIUAID.js?v=9bcdad97:31940:73)
    at Object.setRenderDetails (chunk-FFDIUAID.js?v=9bcdad97:31903:24)
    at CellCtrl2.showValue (chunk-FFDIUAID.js?v=9bcdad97:27229:21)
    at CellCtrl2.refreshCell (chunk-FFDIUAID.js?v=9bcdad97:27467:14)
    at CellCtrl2.refreshOrDestroyCell (chunk-FFDIUAID.js?v=9bcdad97:27447:14)
    at CellCtrl2.onColDefChanged (chunk-FFDIUAID.js?v=9bcdad97:27822:14)
    at chunk-FFDIUAID.js?v=9bcdad97:38863:29
```

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by pawel-ged-thecodest** [comment]
Thank you for your interest in the problem. I noticed that the problem occurs when the 'auto-params-refresh' prop is set in the grid. I can't find in the documentation what exactly this property does, but it was added in the old version of ag-grid and vue 2.

steps to reproduce:
1. click on refresh button above grid

https://plnkr.co/edit/WJbqusiBaAprTXQJ?open=main.js

**Comment by AG-Zoheil** [comment]
Hello @pawel-ged-thecodest,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug. It seems like this approach is not supported in Vue 3.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10307.**

We can suggest to use an approach like the example on our website to manually capture the refresh yourself. See the implementation in this example: https://www.ag-grid.com/vue-data-grid/component-cell-renderer/?#complex-cell-renderer-example

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
