### ISSUE TITLE
Custom cell data types not working with dateString

### ISSUE THREAD

**Issue by AnnMarieW** [ag-grid/ag-grid#7398]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
The [custom cell data type](https://www.ag-grid.com/react-data-grid/cell-data-types/#providing-custom-cell-data-types) is not working with  the predefined `dateString` data type.

**Providing a Reproducible Scenario**
This example includes columns with 2 different string date formats.  The custom cell data type for the dateString is based on the date type definition from the [Overriding the pre-defined cell data types](https://www.ag-grid.com/react-data-grid/cell-data-types/#overriding-the-pre-defined-cell-data-type-definitions)  example in the docs.

https://plnkr.co/edit/KaJMpnz2R1LNXFUo?open=index.jsx

**Current behavior**
In the column with the custom cell data type, the filter is a text filter, rather than a date filter.  After editing a cell, the cell is blank.

**Expected behavior**
The cell should display the new date in the correct format after editing  and the filter should be a date filter.

**Comment by AG-Zoheil** [comment]
Hi @AnnMarieW,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10260**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi @AnnMarieW,

Thank you for your comment.

Apologies, our original fix seems to only have resolved the issue with the actual filter - ie " the filter is a text filter, rather than a date filter". I've raised another item in our backlog to address the remaining problem which will be released in our next version.

Thank you your patience.

Kind regards,
Zoheil
