### ISSUE TITLE
Cell value is set to null for a number cell when invalid value is entered by user instead of disregarding the invalid value

### ISSUE THREAD

**Issue by smohadjer** [ag-grid/ag-grid#7403]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
If user is editing a cell of type number and enters a character instead of a digit, the field replaces existing number with null value showing empty field. This can be reproduced in your examples on this page: https://www.ag-grid.com/javascript-data-grid/provided-cell-editors-number/

Cell definition:
````
    {
      field: 'age',
      editable: true,
      cellDataType: 'number',
      cellEditor: 'agNumberCellEditor',
      cellEditorParams: {
        min: 0,
        max: 100
      }
    }
````

**Expected behavior**
If an invalid value such as a character is entered into a cell of type number, the grid should not accept the value and show the existing value after editing is done instead of removing the existing number and displaying the cell empty.

**Comment by AG-Zoheil** [comment]
Hi @smohadjer,

Thank you for raising this on GitHub.

In the current implementation of our logic when entering any value into a cell the new value replaces the old value. However due to a character being entered in a cell with the `cell data type number` the value **thereafter** gets rejected and you end up with a blank value. We do have a feature request to support this in a better way. You can find this with the following reference in our pipeline: **AG-3848**.

In the meantime you can use `ESC` to prevent the old value from being lost (pressing escape before leaving the cell will revert to the old value). Alternatively you can build your own cell editor with a logic more desirable to your use case.

Kind regards,
Zoheil

**Comment by smohadjer** [comment]
But users won't know the value they enter is invalid before they press the enter on keyboard. Is there a way to render the input field as error field with red border when a character is entered into a number field? I see that this happens if I enter an invalid number (above 100 for example), but not when I enter an alphabetic value which seems like another bug.

**Comment by AG-Zoheil** [comment]
Thanks for the feedback @smohadjer, your suggestion is also included in **AG-3848**.
