### ISSUE TITLE
Initial state for hidden columns

### ISSUE THREAD

**Issue by Eugeno** [ag-grid/ag-grid#7407]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
https://plnkr.co/edit/z4KLF6Lh23UHqJgf?open=main.js
1. Make 'Country' visible
2. Press 'Recreate grid'

**Current behavior**
Column is hidden

**Expected behavior**
'Country' is visible

* **AG Grid version:** 31.0.1

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

We have already added this bug to our backlog and we are tracking it with the following reference: **AG-10205**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
