### ISSUE TITLE
"suppressColumnVirtualisation" doesn't work after setting "autoHeight: true"!

### ISSUE THREAD

**Issue by angela-huang** [ag-grid/ag-grid#7408]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
https://codesandbox.io/p/sandbox/ag-grid-packages-forked-rn74d6

**Current behavior**
 Rendered all columns.
![ag-grid-bug](https://github.com/ag-grid/ag-grid/assets/11454043/94c8b158-f060-447b-b87e-8e3944c9602e)

**Expected behavior**
 Only render the content within the visible area.

* **AG Grid version:** X.X.X
"@ag-grid-community/client-side-row-model": "^30.2.0",
 "@ag-grid-community/core": "^30.2.0",
 "@ag-grid-community/react": "^30.2.0",
 "@ag-grid-community/styles": "^30.2.0",

* **Browser:**
chrome 120.0.6099.131(64bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "^4.5.4"

**Comment by AG-Zoheil** [comment]
Hi @angela-huang,

Column virtualisation is the insertion and removal of columns as the grid scrolls horizontally. Setting the grid property `suppressColumnVirtualisation=true` will turn this behaviour off. In your codesandbox example you can see in the console that the ValueFormatter is called 900 times which shows the suppressing of column virtualisation was successful.

It sounds to me like you do **not** want to suppress the virtualisation, in which case you should set it to false or just leave it as the default state.

However please note the following important detail when using autoHeight: "Columns with Auto Height will always be rendered because the grid needs to set the height of the row. Setting autoHeight=true adds size listeners to cells and stops Column Virtualisation"

You can read more about it in our documentation [here](https://ag-grid.com/javascript-data-grid/row-height/#auto-row-height).

I hope this clarifies the matter.

Kind regards,
Zoheil

**Comment by angela-huang** [comment]
Yes, all columns need to have autoHeight enabled. All right, then I'll try other ways. Anyway, very thanks for your apply.

**Comment by dsowza** [comment]
Versions: Angular version 17 and Nebular 13, most Cell Renderers are pipes, masks and buttons.

After updating from version 26 to 31, I’ve experienced performance issues that were not present in the earlier version. To achieve comparable performance, I had to enable the following options:

- suppressColumnVirtualisation=true: This is essential to eliminate lag during horizontal scrolling.
- suppressAnimationFrame=true: This prevents the incremental display of cell renderers, which used to be instantaneous prior to the update.

Without these options, the rendering performance degrades and become lazy. All other data, excluding cell renderers, loads instantly as before. Additionally, **pagination** appears to be less responsive than in the previous version.
