### ISSUE TITLE
Ag grid - ARIA attribute is not allowed: aria-expanded="true" in detail cell

### ISSUE THREAD

**Issue by ChithiraMG** [ag-grid/ag-grid#7409]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

AG grid detail cell is showing aria-expanded attribute issue in the first column as given below.

![image](https://github.com/ag-grid/ag-grid/assets/101738825/1e14ff35-e8f9-42e9-b1da-7b8ee1373b9a)

Detail cell expanded view.
![image](https://github.com/ag-grid/ag-grid/assets/101738825/11fadd46-034c-4abd-b273-7cf4ba55c880)

Not able to repro in code sandbox, can you please help me understand if it's a false positive issue or any fix available?

**Comment by AG-Zoheil** [comment]
Hi @ChithiraMG,

Thank you for raising this on GitHub.
 
The aria-expanded attribute is correctly used to indicate the expanded/collapsed state. This attribute is announced by screen readers when focusing a master row for example. This is a valid attribute as listed in the ARIA specification here:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded
 
The Accessibility insights tool is flagging this as an issue because the aria-expanded attribute is only valid for a limited number of HTML elements:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded#associated_roles
 
AG Grid uses DIV elements to represent rows and the use of aria-expanded is correct logically and serves to achieve the functional purpose even if the ARIA standard doesn't allow using aria-expanded on HTML elements apart from the ones in the list above.
 
This is why this violation doesn't lead to any breakdown in accessibility support - actually this is correctly announced by screen readers. The fact this is flagged as an ARIA violation but actually works correctly indicates the ARIA standard needs to be enhanced further to support the use of the aria-expanded attribute on other HTML elements such as DIV.
 
In any case, this is by design and this attribute is correctly added and works as expected.

I hope the above clarifies the matter.

Kind regards,
Zoheil
