### ISSUE TITLE
Update cellValue on the fly

### ISSUE THREAD

**Issue by AliakseiBarkouski** [ag-grid/ag-grid#7410]
**I'm submitting a ...
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'

**Requesting Community Support**

I want to use a different set of data depending on what value was selected in another cell.
However, AgGrid does not change the data until we either press Enter or remove focus from the current line

```const [columnDefs] = useState<ColDef[]>([
{ field: 'firstName', editable: true},
    {
      field: 'lastName',
	  editable: true,
	  cellEditor: myCustomEditor,
      cellEditorParams: (rowData) => {
        //here I want to see the edited value of a 'firstName' cell immediately after editing that cell. Because here I need to decide which data set I want to use when editing this cell.
        console.log(rowData.data.firstName);
      }
      },
  ]);
```

https://plnkr.co/edit/0KsMFEiGjtozJqCS?preview

AG Grid version: X.X.X
 "ag-grid-community": "^31.0.0",
 "ag-grid-enterprise": "^31.0.0",
 "ag-grid-react": "^31.0.0",

Browser:
chrome 120.0.6099.131(64bit)

Language: [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "^5.0.2",

**Comment by jayakumar-innominds** [comment]
Above issue is reproducible when editType="fullRow" . 

Attaching code sandbox link where issue is reproducible. This is a fork of the example given in agGrid documentation.
https://codesandbox.io/p/sandbox/sample-aggrid-add-row-xvtxj8?file=%2Fsrc%2Findex.js%3A94%2C28

Here changing country is not updating the options of city column
![image](https://github.com/ag-grid/ag-grid/assets/149458683/d9b16fe9-e8ad-4515-92be-fecd3c9864c9)
Here when USA is selected, city column should be cleared and the cities of USA should be shown as options, but that doesn't happens

**Comment by AG-Zoheil** [comment]
Hi @jayakumar-innominds,

Your codesandbox brings up a reference error. However based on your description I've forked the example and added editType=fullRow to [this plunker](https://plnkr.co/edit/OciX5v7K3GVbYsdN?open=index.jsx) and it is working as expected. Can you confirm that is the case for you?

Alternatively, if there is something else you are setting differently, please fork it and add your adjustments.

Thank you!

**Comment by jayakumar-innominds** [comment]
can you replace agRichSelectCellEditor with agSelectCellEditor for all the cellEditors and check.
i have forked above one and issue is reproducible in this https://plnkr.co/edit/HMhzfn8NabrJKFWY?open=index.jsx.

Please check

**Comment by AG-Zoheil** [comment]
Hello,

Thanks for the reproduction. We've had a closer look at this.

For **agRichSelectCellEditor** when you change the value of the country, it doesn't just change the value of the cell, but the value of the current editor for cities.
The reason why this works with **agRichSelectCellEditor** is because, the whole editor is terminated and then it has to be restarted to show it correctly. This is not the out-of-the-box behaviour with **agSelectCellEditor**.
 
Generally we would not recommend to have a full row editor when you have co-dependent values like this. There is likely a way to make this work but it would involve a lot of customisation and falls outside of the remit of support that is provided via GitHub.

Thanks again!
