### ISSUE TITLE
Long pressing ctrl+C in range selection produces a flicker effect. 

### ISSUE THREAD

**Issue by gautamkr04** [ag-grid/ag-grid#7426]
**Long pressing ctrl+C in range selection produces a background  flicker effect. ....**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- when long hold on cltl+C on range selection the selection background with show different background color.
- It is reproducible on document [[url](https://www.ag-grid.com/javascript-data-grid/range-selection/)](url)  preview. 

![ScreenRecording2024-01-11at6 28 19PM-ezgif com-video-to-gif-converter](https://github.com/ag-grid/ag-grid/assets/132537217/924130ac-2b7e-4110-83c3-e4488ca0820b)
following the steps below:
- Go to the link 
- Preview the first example given
- Select the rows and column
- long press clt+c , selction color will start showing different background effect.

If reporting a bug make sure to state.

Current behaviour.

Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

when long hold on cltl+C on range selection the selection background with show different background color

**Expected behavior**

Display a consistent background .

**Please tell us about your environment:**

* **AG Grid version:** 30.2.1

* **Browser:** Chrome  Version 120.0.6099.199 (Official Build) (arm64)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10294**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
