### ISSUE TITLE
Inconsistent resize handle size (css)

### ISSUE THREAD

**Issue by csisy-btw** [ag-grid/ag-grid#7429]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[ ] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

https://plnkr.co/edit/V8xsqMATty4HTkoU?preview

To clarify the issue, a red border has been drawn around the resize handle.

**Current behavior**

In my opinion, there are multiple problems with the current styling of the resize handle:
- As you can see, the group cells do not have `overflow: hidden` style, which causes the resize handle to "leak through" to the next header cell
- On the other hand, non-group header cells have `overflow: hidden` which causes the resize handle to be clipped
- The width of the resize handle and the drawn area can be out of sync. The resize handle is hard-coded to be `8px` wide, so if the value of `--ag-header-column-separator-width` is higher than 4, the drawn area is wider than the actual area which can be used by the user to resize the column

**Expected behavior**

- Allow the users of the library to properly customize the size of the resize handle (e.g. use a single css var to the invisible resize area and the drawn area)
- This also means that instead of the hardcoded `width: 8px` and `right: -4px`, the right value could be `0` and the drawn area's `left` can be omitted (or better, changed to `inset: 0` so the area that is used to resize the column matches the visible area of the resize handle)

**Please tell us about your environment:**

* **AG Grid version:** `31.0.1`

* **Browser:**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`

* **Language:** `TypeScript 5.2`

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10616**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
