### ISSUE TITLE
Ag-grid Enterprise 30.1.0 : Issue with row grouping and row selection performance

### ISSUE THREAD

**Issue by KuveraAman** [ag-grid/ag-grid#7446]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**
This issue is reproducible in Ag-grid enterprise version (paid for the year 2023 - 2024)

**Providing a Reproducible Scenario**
Using Vanilla JS: Try loading 3 row groups with 7 or more columns. Every column has a custom inline editor, and few have custom renderers as well.  The row model of the grid is set to client-side. Enable row selection for every row as well and the first column is pinned to the left.

Each of the row group has the following number of rows respectfully, 400, 4000, 44. Once the said scenario is set up the following issues occur:
 - Row group with 3000+ child rows take 7 seconds to load into DOM.
 - select all for the same data takes 10-12 seconds. 
 - There is not support for loading icon as well in these scenarios which makes the screen look frozen/not responsive.

**Current behavior**
 - Row group with 3000+ child rows take 7 seconds to load into DOM.
 - select all for the same data takes 10-12 seconds. 
 - There is not support for loading icon as well in these scenarios which makes the screen look frozen/not responsive.

**Expected behavior**
The grid should perform better in this scenario or there should be a support for a row-group level loading icon which gives a visual representation of some action being executed (as the screen freezes in current scenario, leaving the UI completely not usable.

**Please tell us about your environment:**
- Windows 10
- VS Studio

* **AG Grid version:** X.X.X
Enterprise 30.1.0

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0'

* **Language:** Vanilla JS

**Comment by AG-Zoheil** [comment]
Hi @KuveraAman,

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Additionally, providing a reproducible scenario (e.g. by forking a plunker from one of our documentation examples) along with your description would help us support in a much more efficient manner. In line with this, I'll be closing this issue here and we'll be awaiting your contact via Zendesk.

Kind regards,
Zoheil
