### ISSUE TITLE
Ag-grid Enterprise - 30.1.0 : warning message in console regarding getSelectedRows()

### ISSUE THREAD

**Issue by KuveraAman** [ag-grid/ag-grid#7447]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**
Enterprise version 30.1.0 

**Current behavior**
The following error message is shown in console when using serverside model and select all functionality of ag-grid rows. But the expected output is received from the grid api function used ( getSelectedRows())
![image](https://github.com/ag-grid/ag-grid/assets/156903589/e2e7f118-492a-400c-baf0-b128e0dcc732)

**Expected behavior**
Warning message should not show as the expected outcome is achieved.

**Please tell us about your environment:**
Windows 10
VS studio

* **AG Grid version:** X.X.X
30.1.0

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Vanilla JS

**Comment by AG-Zoheil** [comment]
Hi @KuveraAman,

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Additionally, providing a reproducible scenario along with your description would help us support in a much more efficient manner. In line with this, I'll be closing this issue here and we'll be awaiting your contact via Zendesk.

Kind regards,
Zoheil
