### ISSUE TITLE
rowData contains Data for children         How do you present it without processing the data Tree table？

### ISSUE THREAD

**Issue by zhangqiankunai** [ag-grid/ag-grid#7448]
data as follow：
     const originalData = [
  {
    id: 1,
    name: 'Parent 1',
    children: [
      {
        id: 2,
        name: 'Child 1.1',
        children: [
          {
            id: 4,
            name: 'Grandchild 1.1.1'
          }
        ]
      },
      {
        id: 3,
        name: 'Child 1.2'
      }
    ]
  },
  // 更多节点...
];

 I used a different component before,    Now to replace AG Grid ， So how do you generate a tree table without dealing with the data structure？In a hurry！
I don't know if I'm saying that correctly
My logic depends on this data structure

**Comment by AG-Zoheil** [comment]
Hi @zhangqiankunai,

Thanks for getting in touch with us. This functionality is only available in the enterprise version of our datagrid. On our documentation page you can identify enterprise features by the red _**e**_ sign next to them.

If you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Additionally, providing a reproducible scenario along with your description would help us support in a much more efficient manner. In line with this, I'll be closing this issue here and we'll be awaiting your contact via Zendesk.

Do let us know if you have any other questions.

Kind regards,
Zoheil

**Comment by zhangqiankunai** [comment]
yes
