### ISSUE TITLE
Transform attribute added in Safari browser but not recognized in other browsers (Chrome, Edge)

### ISSUE THREAD

**Issue by AbhinanduReddy** [ag-grid/ag-grid#7451]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- Go through the following link (https://www.ag-grid.com/react-data-grid/filter-text/) in Safari and Edge or any other browser to compare with safari 
- Inspect the header of the grid.
-  You will observe that `transform: translateZ(0px)` is added to the style in safari but not in Edge/Chrome.

**Safari Browser**
![safari](https://github.com/ag-grid/ag-grid/assets/43111492/ee839fcc-83a4-4a2b-aa48-6884518ab33d)

**Edge Browser**
![Screenshot (2)](https://github.com/ag-grid/ag-grid/assets/43111492/fbcefd87-79c6-4f80-a562-b6eb96505dc2)

**Current behavior**
`transform: translateZ(0px)` attribute is added to the header div element in safari browser as shown in the image but not in other browsers

**Expected behavior**
attributes should be consistent in all the browsers, removing `transform: translateZ(0px)` attribute will work

**Problem**
Is there any reason attributes are added like this, because of this stacking context issues are rising differently in Safari and other browsers. Can it be fixed?

* **Browser:**
Safari, Chrome, Edge

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10639**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
