### ISSUE TITLE
Column width not restored when applied through initialState

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#7462]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Can see a similar issue reported in #7450 

**Current behavior**
The following example is w.r.t a sample example provided for reply to[ #7445](https://github.com/ag-grid/ag-grid/issues/7445#issuecomment-1898300123)

On auto sizing all columns under column menu or changing width of the columns, on reload widths of the columns are not restored.
https://plnkr.co/edit/d0UzVWMBQgpUzgB2?open=index.jsx&preview

**Expected behavior**
Column widths should be restored when applied through initialState

* **AG Grid version:** X.X.X
31.0.2

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]w.r.y
React

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10388**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
