### ISSUE TITLE
Rows flickering on applyTransactionAsync

### ISSUE THREAD

**Issue by fcaballero** [ag-grid/ag-grid#7472]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- A description: After updating the data by using `applyTranscationAsync` the rows start flickering, the reason seems to be AgGridReact doesn't like inline values for either `rowStyle` or `getRowClass`. In the plunker example, press the button `Start Update` to see the issue. 

```jsx
  <AgGridReact rowStyle={{ border: 'none' }} getRowClass={() => {}}/>
```
- A plunker: https://plnkr.co/edit/wVYH6HvGoihY9h5f?preview

Temporal workaround (if anyone else is facing the same problem):
Make sure rowStyle or getRowClass are not inline values

```jsx
const rowStye = { border: 'none' };
const getRowClass = () => { /* Do something*/}
const MyGrid = () => {
  ....
  return <AgGridReact rowStyle={rowStyle} getRowClass={getRowClass}/>
```

**Please tell us about your environment:**:

* **AG Grid version:** 31.0

* **Browser:** Chrome

* **Language:**  TypeScript 4.8.3

**Comment by StephenCooper** [comment]
Hi @fcaballero,

It sounds like you managed to resolve your issue. We do recommend that for object properties and callbacks that you use `useMemo` and `useCallback` to provide stable references.

This is outlined in our Best Practices documentation: https://ag-grid.com/react-data-grid/react-hooks/#object-properties

Otherwise the grid will re-render as you could be passing in a new value for the rowStyle object.
