### ISSUE TITLE
[React] v.31.0.2 Cannot Read properties of null (reading "getColId")  

### ISSUE THREAD

**Issue by vitaliizharkov26** [ag-grid/ag-grid#7486]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
I have encountered an issue with updating the ag-grid to 31.0.2, may it be similar to this? 
https://github.com/ag-grid/ag-grid/issues/7395

So, on mount VERY randomly I got this error, I have checked 31.0.1, and it also occurs there.
On 30.2.1 everything is ok.

Maybe someone knows the reason why it can happen? 
![image](https://github.com/ag-grid/ag-grid/assets/71453812/a620d702-f1cf-4afe-8a1a-9ad81d690f3e)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by vitaliizharkov26** [comment]
@AG-Zoheil 
Sorry for the delay, I was investigating & fixing the issue on my side, and as @jpfortier said - the issue is related to the columnDefs and their field/colId property.

Here is a reproducible scenario: 
https://codesandbox.io/p/sandbox/ag-grid-packages-forked-2ddy9j?file=%2Fsrc%2Findex.tsx%3A35%2C24
Note that "handleRemove" is not memorized, so my assumption is that is also related to the rerenders, but I don't think that it should result in an ag-grid error.

The error is gone if "field" is added to a column.

**Comment by FredLavoie** [comment]
This may or may not be related, but I get the `TypeError: Cannot read properties of null (reading 'getColId')` error when running my tests, but not when running the app locally (no errors in my console). The tests still pass because it's just a type error though.

This is happening from upgrading ag-grid-community and ag-grid-react to from v30.0.0 to v31.0.2.

**Comment by StephenCooper** [comment]
I am taking a look into this. 

In the provided reproduction the missing memoization is key. While I agree the grid should not fail this will lead to worse performance as it will force the grid to respond to a new set of column definitions on every render. 

Field and coldId are used to identify common columns when a new instance of the array is provided to `columnDefs` which is why they are helping to avoid the issue.

**Comment by StephenCooper** [comment]
So after a bit more investigation I have found the following. 

The following code causes a loop as we are setting a state variable inside the effect but the dependency array contains `handleRemove` which then has a new reference on every render causing the effect to run again and loop.

```
  const handleRemove = () => { };

  useEffect(() => {
    setColumnDefs([... ]);
  }, [handleRemove]);
```

We have made a change in our code that now leads this to break, with the error you have seen. We can resolve this but the grid would still not be stable. On previous versions you do not get the error thrown but the grid is still updating columns on every render. 

This can be verified by setting the `debug` flag on the grid and seeing the columnDef property is constantly being updated.

The loop also only happens because neither a field or colId is provided so AG Grid has to then fallback to comparing by instance. In this case as the columnDef is new every render the grid will treat this as a new column on every render.

I would be interested to know if there is any reproduction available for the other cases that are seeing this error?

**Comment by vitaliizharkov26** [comment]
@StephenCooper  It makes sense, thanks for the clarification. The only problem is that it was not reflected in changelogs in v31. 
Overall I didn't encounter any other scenarios except multiple re-renders due to bad memorization

**Comment by chrisvander** [comment]
I'm having this problem but with dynamically created columns based on data. If a new column is created, a new ColDef is created with it, along with a new `colId`. When that occurs, the error throws.

I'm also noting that as these errors stack up, the grid gradually slows the page to a crawl. Not sure why that's the case yet.

**Comment by StephenCooper** [comment]
@jared-jewitt Thanks for the example. I have run this against our next release candidate and the issue is fixed. 31.1 is scheduled for release next week.

**Comment by antonarbus** [comment]
issue is gone at 31.2.0 for me 👍
