### ISSUE TITLE
Tabbing infinite loop issue with nested grids that are 3 or more levels deep.

### ISSUE THREAD

**Issue by tom-fitts** [ag-grid/ag-grid#7506]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Tabbing infinite loop issue with nested grids that are 3 or more levels deep.

Issue occurs with nested grids 3 or more levels deep with each grid having multiple rows. User can never tab off a child grid that has children. An infinite tabbing loop occurs between inner nested children.

A simplified test can be reproduced when there are 3 nested grids, with each grid having 2 rows. Expand the first row of the top parent (Grid A), and expand the first row of the child grid (Grid B). You now see the 3rd nested grid (Grid C). Keep all other rows collapsed including the 2nd row of Grid A and the 2nd row of Grid B.

Now click on the last cell of the collapsed 2nd row of Grid B so it is in focus and tab off. Notice that the cell focus loops back up to the 1st row of Grid C. Expected behavior is the tab should go to the next row of Grid A.

This can be reproduced on the Auto Height example of nested grids from the AG-Grid website with a slight modification in Plunker. Here is the link to the Plunker example:

https://plnkr.co/edit/4uFwN4wmFzj6aENV?open=main.js&previewhttps:%2F%2Fplnkr.co%2Fedit%2F4uFwN4wmFzj6aENV%3Fopen=main.js&preview

1. Run the grid and collapse all rows.
2. Now expand the first row of the top grid, then expand the first row of child grid.
3. Now scroll down and click on the cell with the value "level2 -444_New". Make sure this row is collapsed. 
4. Tab off of this cell.

**Current Behavior:** Notice cell focus incorrectly moves up to the header row cell A3 of the 3rd nested child grid. 
**Expected Behavior:** The cell focus should be on the first cell of the next row of the parent grid (level1-111_Row2).

**AG-Grid Version:** ag-grid-react: 28.2.1

**Comment by AG-Zoheil** [comment]
Hello @tom-fitts,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10522**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
