### ISSUE TITLE
Shift+Tab not tabbing back into nearest inner nested grid from parent grid with nested grids 3 or more levels deep.

### ISSUE THREAD

**Issue by tom-fitts** [ag-grid/ag-grid#7507]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Shift+Tab not tabbing back into nearest inner nested grid from parent grid with nested grids 3 or more levels deep.

Issue occurs with nested grids 3 or more levels deep, user is not able to tab back into an inner nested grid that is more than 1 level deeper than the parent.

A simplified test can be reproduced when there are 3 nested grids, with the top parent having two rows. Expand the first row of the top parent (Grid A), and expand the first row of the child grid (Grid B). You now see the 3rd nested grid (Grid C). 

Now click on the first cell on row 2 of Grid A to give it focus. Perform Shift+Tab to tab backwards. 
**Current Behavior:** Cell focus is initially lost after the first Shift+Tab. Perform Shift+Tab again and cell focus incorrectly moves back to the last cell of Grid B above the previous cell focus position.
**Expected Behavior:** Tab focus should move back into the last cell of the last row of Grid C above the previous cell focus position.

This can be reproduced on both examples from the nested grid documentation on the AG-Grid website: https://www.ag-grid.com/javascript-data-grid/master-detail-nesting/

Here are the steps:
1. Expand the first row of the parent grid, then expand the child grid. You should now have 3 levels of grids displayed.
2. Click on the first cell of row 2 on the top parent to give it focus. (level 1-  111).
3. Perform Shift+Tab to tab backwards.
**Current Behavior:** Cell focus is initially lost after the first Shift+Tab. Perform Shift+Tab again and cell focus incorrectly moves back to the cell with the value "level 2 - 444", which is the last cell on the expanded level 2 grid above the previous cell focus position.
**Expected Behavior:** Tab focus should move back into the last cell of the nearest level 3 grid above the previous cell focus position, which is the cell with the value "level 3 - 6666".

**AG-Grid Version:** ag-grid-react: 28.2.1

**Comment by AG-Zoheil** [comment]
Hello @tom-fitts,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10522**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
