### ISSUE TITLE
enableCellTextSelection marks more cells than expected on Firefox

### ISSUE THREAD

**Issue by amuttsch** [ag-grid/ag-grid#7517]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

I have enabled `enableCellTextSelection` and `ensureDomOrder`, however in Firefox I get a strange behavior if I start the selection in the middle of the cell. When I drag the mouse down, cells above the actual selected cells are marked. See the video for an example.

https://github.com/ag-grid/ag-grid/assets/5488288/b0f11304-4095-4935-9597-d7a5ca058886

Pluncker: https://plnkr.co/edit/QAXQSN8B2dbunetu?open=main.js

**Expected behavior**
The text selection is not janky. On Safari, it works much better and does not select cells above.

**Please tell us about your environment:**
MacOS, Firefox

* **AG Grid version:** 31.0.3

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0

* **Language:** all

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10566**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Please note that after investigation we've identified that this is not an AG Grid bug but a FireFox issue.

We have therefore raised it with Mozilla and this can be tracker here: https://bugzilla.mozilla.org/show_bug.cgi?id=1913308

We will be closing the item from our backlog.
