### ISSUE TITLE
AG Grid React width issue when using applyColumnState

### ISSUE THREAD

**Issue by SoumyanilCBNITS** [ag-grid/ag-grid#7518]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
You can check your example from here - https://www.ag-grid.com/angular-data-grid/column-state/#save-and-apply

1. Reorder column, save state
2. Reorder the column, and restore the state, it works!
3. Resize the column, save the state
4. Resize the column, and restore the state, it doesn't work.

We have a similar setup in our development except we are fetching the state from the backend. We are not using width in any of our column definitions but had `flex: 1` in the default column definition, and it worked up until yesterday. For some reason, it stopped working today, and I tried doing it without `flex: 1` and it's still not working.

**Expected behavior**

Should apply width when we are setting set through applyColumnState

**Please tell us about your environment:**
MacOS, VSCode, NPM

* **AG Grid version:** 31.0.0

* **Browser:**
Chrome

* **Language:** TypeScript

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10388**

This should be fixed in the next release.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
