### ISSUE TITLE
Apply column state - Example not working in chrome

### ISSUE THREAD

**Issue by Alexander-Ruedi** [ag-grid/ag-grid#7520]
**I'm submitting a ...**
```
[x] bug report 
[] feature request
[] support request
```

**Providing a Reproducible Scenario**
https://www.ag-grid.com/examples/column-state/save-apply-state/packages/vanilla/index.html
https://www.ag-grid.com/examples/column-state/save-apply-state/packages/reactFunctional/index.html

**Current behavior**
Works fine on Microsoft edge, doesn't work on Chrome:
"Reset state" button does not reset the grid
"Restore state" button does not restore the saved state

**Expected behavior**
"Reset state" button should reset all changes to grid (same as reloading the page)
"Restore state" button should apply the saved state

**Please tell us about your environment:**
Doesn't work with
Chrome 121.0.6167.86
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'

Works with:
Microsoft Edge 121.0.2277.83
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0'

* **AG Grid version:** 31.0.3

* **Language:** all

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

We've already added this bug to our backlog and we are tracking it with the following reference: **AG-10388**

This should be fixed in the next release.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by Alexander-Ruedi** [comment]
Thanks a lot for the quick reply.

Is there a reason why I can't see the ticket AG-10388?

**Comment by AG-Zoheil** [comment]
Hi @Alexander-Ruedi,

I'm glad to hear the original issue has been resolved for you.

We have not been able to get the codemod ready yet for the latest release. We anticipate this to be available at some point next week.

Apologies for the inconvenience.

Kind regards,
Zoheil
