### ISSUE TITLE
Column Group closed state not restored through initialState

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#7524]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

In the following example as per official documentation, collapse/close the column group and do some sorting/filtering. On recreating grid using **initialState**, column group collapsed state isn't restored. As per state I can see only an **openColumnGroupIds** being saved within **columnGroup** object.

https://plnkr.co/edit/aSbDVvdk1FtmysEj?open=index.tsx&preview

**Expected behavior**

Initial State should also store state of column groups which are **closed/collapsed** within **columnGroup** 

* **AG Grid version:** X.X.X

31.0.3

* **Browser:**

All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* React

**Comment by AG-Zoheil** [comment]
Hello @melon2504,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10575**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
