### ISSUE TITLE
Calling `sizeColumnsToFit` after `autoSizeAllColumns` does not fit the grid

### ISSUE THREAD

**Issue by danielmalaton** [ag-grid/ag-grid#7526]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/qZNIUB0PEb2hIcQL?open=main.js
- columnDefs: we have 4 columns, the first column has `50px` width and `suppressSizeToFit`. The others do not define the `width`
- We have button to do some actions
  - Call `autoSizeAllColumns()`
  - Define `columnLimits`
  - Call `sizeColumnsToFit({ columnLimits })` 

**Current behavior**
- The grid looks weird
  - Do not fit the grid horizontally
  - The scrollbar sometimes flickers

**Expected behavior**
- Should fit the grid horizontally
- The scrollbar should not flicker

Note that: If the cell content of the second column is not cut off, everything works fine

**Please tell us about your environment:**

* **AG Grid version:**

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10580**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by danielmalaton** [comment]
Any progress on it? I saw the changelog that release a fix but it does not seems to work fine

**Comment by AG-Zoheil** [comment]
Hi @danielmalaton,

Can you see if this example works for you (running on `31.1.1`)?
https://plnkr.co/edit/DsYx8PmRwPcPoEGS?open=main.js

Kind regards,
Zoheil

**Comment by danielmalaton** [comment]
issue:
1. Resize column to the right until horizontal scrollbar appears
2. Hit button
3. The grid does not fit well

https://github.com/ag-grid/ag-grid/assets/106505755/77c2daf5-541b-4517-9e0b-7f0b29b07642

**Comment by AG-Zoheil** [comment]
Hello,

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11119**

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by danielmalaton** [comment]
Please kindly fix it asap
