### ISSUE TITLE
Grid State is not applying column width of state to columns after Recreation

### ISSUE THREAD

**Issue by LukivondemKaff** [ag-grid/ag-grid#7527]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
https://www.ag-grid.com/react-data-grid/grid-state/  is your own example.
Tried it with Edge Version 120.0.2210.160 (Offizielles Build) (64-Bit).

**Current behavior**
If the user resizes the column width and presses the recreate grid with current state button, then It does not apply this to the size. 
Really strang is that in the Athlete column It was then changed to 200 instead of 150 (ColumnDef) and the manipulated by the user 280. You can see it in the logs. The actual width is printed before the destroy and after the recreation of the grid it changes again to 150 ot 200 for the Athlete column. 

**Expected behavior**
The Columd Width should be applyed as the latest state

**Please tell us about your environment:**
. Tryed it on your website and plunker (linked from your website)
I have the same behavior in my Project. 

* **AG Grid version:** 31.0.3

* **Browser:**
Edge Version 120.0.2210.160 (Offizielles Build) (64-Bit)

* **Language:** as in your example

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

We have already added this bug to our backlog and we are tracking it with the following reference: **AG-10388**

This should be fixed in the next release.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by LukivondemKaff** [comment]
Thank you Zoheil, 
sorry I did not check that before :-(.
Glad you are working allready on it. 
Thanks I have the notification aactivated. 
Kind regards
Lukas
