### ISSUE TITLE
ag-grid error refused to load font causing css breaking issue

### ISSUE THREAD

**Issue by mohitPanwar1996** [ag-grid/ag-grid#7543]
<img width="1293" alt="Screenshot 2024-02-05 at 12 15 40 PM" src="https://github.com/ag-grid/ag-grid/assets/154788387/cfcb9cae-2591-410a-b5de-8651f884f87e">

I am getting this error while using ag-grid in production 

Refused to load the font 'data:font/woff2;charset=utf-8;base64,d09GMgABAAAAABkcAAsAAAAANDgAABjKAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHIkuBmAAi2IKwkC1WQE2AiQDgjgLgR4ABCAFhEYHhSwbbCxFRoaNA5AAd3UjKjipERWchuz/OsEcw5oG2b/YSMJ1vzTP0uIUhDB6moOzW4Im6BqI0CXBRVkyL/LeDfcz+XvKIUlo8vDfful9M383SMYAlgLAqg4QfYVjiUKikBGqp7pVbPPXXPhvA5fwAWOyu+EjmqkEQlVVIatEjaiib9Qfwjn/r806tKTlgpUxpBIoeJngVVwnhk0Qnxi2dMyEOUxZO9N05jR7TOG9JROjEwO+wLP5fsuETRV2q0jkVATJmW7V+ZlpfaZ1YBair7eCRERaTxz5PxAMr3TwYfQb905f/5IzBzYKs38SGJbdtbl8Oukrke/0pNNfCBWgElgCS1AjgGDL/Q3T6CAlVIJPUP7zx1...+FYkwSXMJbFuOdFwhcszWjcKIb01NXFtdsQSGSDjNK1eyxu1+LESYWNg4uHj4BIRECiUJHY/FEMpXOZHP5QrFUrlRr9Uaz1e50e/3BcDSeTGfzhWFiQi3bcT0/cOvOvQePnjx746133vvgo08+r50jh0votHimSk/iRR7rDRUEAQYF51Y9PF6E146XzXMNmvPACzwZFEy9Jy14HJUrhFV5FzpwaqL3DEwbX2HpKW9DkyQNgmYCHVcKhnMew56P4ZWJyQwKv7LVzcOjLjzQbOGPTQ46z8Yvu7IVSlQVUSnLxI2Pyg2XOElUpdxppQpFFcfdCK2NJ7fZx9L3fo2TPqlsMir5QqgJd6il0SHwQlxF4hSOlSJ1O3OWw0T6w3DTFRGmhq09CESRSuVmMskxx+18F7CjMbygN66FtoPELNrmBlgk0hU+OzKIDQTOYsduYxjZVrAkR6TN8rSEjKiceJWsUtH5IEPNSZDwGFnIQDDzqrPUPNUropU5a70GAAA=' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

I am unable to reproduce this issue in the local.

Can anyone help me on this due to this the css of the grid is breaking resulting in the box like icons rather than original grid icons i want to know why this is happening and what is the solution for this.

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by MukeshJitSinghBaidwan** [comment]
Has this been resolved? I am facing same issue with ag grid. The fonts wont load due to CSP issue. Is there any alternate way I can load the fonts?

**Comment by pavan6014** [comment]
I am getting error "**Refused to load the font 'data:font/woff2;charset=utf-8;base64,d09GMgABAAAAABJ0AAsAAAAAJ2gAABIjAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHIkuBmAAi2IKqHChZAE2AiQDgjgLgR4ABCAFhEYHhSsbdiJVBDYOABJzRUD2/3XyZChr0A8dMuIgaNGSwoZJwnMhJOiNBx1PI4tUlx68riIWf/imgpi0poPyf6NIBoaWDaUkqNbI3rsHUqiRwAEF6XVkKkJFqAhPQkbICDsGzUXOQnJEmGQTPqL/V9yyIlI1qpKcqa5RgMb1B9zWP5xRCRYid58aYGw2/rMuhhGNkeyiQryo3FUFdgfApM6UgneSnTzUnxLCGhA8gaHIWqRVXosIhmsnGtzmqFDF6h8bkm8ayr2OPMzvHpLY/tT8U3qbPSz2JRmzJb/tddeBwCRY4gnhKxHw/6/1agNMNzghoePj9Js37/+de9+dxdBkPtFkQpMJTQDZtqyId7M5p7sFJNXaKm...V/qCDrDU6JmsLaqnbrPTF/hxJGOJGITHzETwLfbs2fFqwfDq6P8UQylc5kc/lCsVSuVGv1RrPV7nR7/cFwNJ5MZ/PFcrVWVE3ohmnZjutttrv94Xg6X663++PJ03WLEMaoFNGS8BGqyrruY3VHDtlRPnQjqt1MlNzXSjZ9XEv+aecZEnsy0ikxGt3tW9hYKn7hJIv2JeW66/F72CauZ07YFJ2RP3BStodOpdZ9V+d91+zAU3WHtDm3fTKZgsoL+lPaUl8z1nE/qT8KKZ/RPszGWu0gaiqHu15aOThoG8IU7Cgnbvm5HmdBnzieTLhJU9rRwUTcTjS1CngYv4ZWD5g2dsDCdM5iPeYsa/KHRc2zpf2S+LCkWeyg5FZPitKcBJkbVfntSL9qZsK9hHC9U44PNcXRDirOdFYndSt6L2tOpXZ8jlWHT57NzqOZ6FbuTIkGVZ/uri2F+KTxZX0ugBBBgcAggQDDGio4yDDCF6xgA72HCRoU2MIMAXYLAAA=' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' *.eu1.sws.siemens.com". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback**." in AWS environment.

![image](https://github.com/user-attachments/assets/e5cc982e-7936-4c9a-9ea7-5b9b1192beb2)

No luck even after trying solutions from this URL https://www.ag-grid.com/javascript-data-grid/security/#font-src.

Getting below errors now:

**Getting Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.**

**Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.**
