### ISSUE TITLE
Column widths are not restored after applying saved ColumnState

### ISSUE THREAD

**Issue by smorandi** [ag-grid/ag-grid#7545]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

When restoring the column-state, the column widths are ignored. This used to work in earlier versions. Please check your own example under: https://www.ag-grid.com/javascript-data-grid/column-state/

**Current behavior**
Columns widths are *not* restored

**Expected behavior**
Well, they should be restored

* **AG Grid version:** 31.0.3

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

We've already added this bug to our backlog and we are tracking it with the following reference: **AG-10388**

This should be fixed in the next release.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by MisterOneTwo** [comment]
Thank you Zoheil!

**Comment by WKampel** [comment]
Any updates on this?

**Comment by AG-Zoheil** [comment]
Hi @WKampel,

This bug has been fixed and will be released in our newest version next week.

Thank you for your patience.

Kind regards,
Zoheil
