### ISSUE TITLE
[React] v30.2.1 updating rowClass prop crashes the grid

### ISSUE THREAD

**Issue by varunpatil-dr** [ag-grid/ag-grid#7565]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

https://github.com/ag-grid/ag-grid/assets/95273665/b05cb2ad-31fa-4363-b920-a57c64a51425

```
clone https://github.com/varunpatil-dr/ag-grid-crash-poc

npm ci
npm start

click on "Click to crash" button
```

**Current behavior**
when `rowClass` is changed, the app crashes with error `rowNodes.forEach is not a function`

**Expected behavior**
grid should rerender with the updated `rowClass` value

**Please tell us about your environment:**

MacOS, VSCode, npm `v9.5.0`, node `v18.14.2`, create-react-app developement server.

* **AG Grid version:***  `30.2.1`
The issue isn't reproducible on `31.0.3`

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'

**Comment by AG-Zoheil** [comment]
Hi @varunpatil-dr,

Thank you for submitting this on Github.

I can see you have mentioned you're using AG-Grid version `30.2.1`. Our current latest version is `31.0.3`.
I'm afraid we do not fix issues for past releases so I can only highly recommend upgrading the version of AG-Grid in your application so that you can benefit from all the improvements in functionality, stability, theming and performance we've made since the version you're using.

Also, I'd recommend to upgrade the AG-Grid version sooner rather than later to avoid having even more changes to make as part of the upgrade process.

Kind regards,
Zoheil
