### ISSUE TITLE
Wrong type value in ColumnEventType

### ISSUE THREAD

**Issue by uncaught** [ag-grid/ag-grid#7588]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
- The type `ColumnResizedEvent['source']` (`ColumnEventType`) does not contain `gridOptionsUpdated`, but that value is used in the event when the column definitions were updated, triggering a resize of a column.

**Expected behavior**
- Either include `gridOptionsUpdated` in the type or use the defined `gridOptionsChanged` when firing the event.

**Please tell us about your environment:**
- Ubuntu 22 on Windows 10 WSL
- PhpStorm
- Create-react-app / webpack

* **AG Grid version:** 31.0.1

* **Browser:** Irrelevant

* **Language:** TypeScript 5.3

![image](https://github.com/ag-grid/ag-grid/assets/10322643/b21f35fa-eeb9-4e01-a6b5-a2f7833d7ff3)

**Comment by AG-Zoheil** [comment]
Hello @uncaught,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10666**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
