### ISSUE TITLE
onStateUpdated does not fire if rowData is empty

### ISSUE THREAD

**Issue by AndreiMitrofanov1** [ag-grid/ag-grid#7618]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
1. Create a simple grid
2. Add stateUpdated listener
3. Set row data as `[]`
4. Change sorting/filtering/anything that normally triggers onStateUpdated

**Current behavior**
onStateUpdated does not fire if rowData is empty

**Expected behavior**
onStateUpdated fires when grid state changes despite rowData emptiness

[Playground with example](https://stackblitz.com/edit/stackblitz-starters-rvltgc?file=src%2Fmain.ts)

* **AG Grid version:** ag-grid-angular 31.0.1
* **Browser:**: Chrome 120
* **Language:** TypeScript 4.9.5

**Comment by AG-Zoheil** [comment]
Hi @AndreiMitrofanov1,

Thank you for submitting this on GitHub.

This behaviour was implemented in version `31.0.2` of our grid.

I would highly recommend upgrading the version of AG-Grid in your application so that you can benefit from all the improvements in functionality, stability, theming and performance we've made since the version you're using.

Kind regards,
Zoheil
