### ISSUE TITLE
[React 31.0.3] Autogrouped columns have duplicate nested gridcell elements

### ISSUE THREAD

**Issue by jake-collibra** [ag-grid/ag-grid#7626]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Autogrouped columns produce cells with two nested elements with identical `gridcell` roles. This is breaking many of our tests that are trying to select cells with `findByRole('gridcell', { name: 'cell content' })`, as there are now multiple elements that match that selector.

![image](https://github.com/ag-grid/ag-grid/assets/94395089/7010f371-c2d0-4173-9cff-d4b198815e33)

**Expected behavior**
There is only one `gridcell` element per cell.

**Please tell us about your environment:**
macOS 14.3.1, IntelliJ IDEA 2023.1.3 (Ultimate Edition), yarn 1.22.19

* **AG Grid version:** 31.0.3

* **Browser:** Chrome 121.0.6167.184

* **Language:** TypeScript 5.3.3

**Comment by AG-Zoheil** [comment]
Hello @jake-collibra,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10748**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
