### ISSUE TITLE
[BUG] chartThemeOverrides: 'bar' overrides column charts, while 'column' does nothing.

### ISSUE THREAD

**Issue by BaconEggsRL** [ag-grid/ag-grid#7628]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
Modify the example plunker [here](https://www.ag-grid.com/javascript-data-grid/integrated-charts-customisation/#common-overrides), adding the following theme override to Line 19 (above 'common'):
```
bar: {
      series: {
        fillOpacity: 0.7,
        strokeWidth: 2,
        strokeOpacity: 0.7,
        label: {
          enabled: true,
          fontStyle: 'italic',
          fontWeight: 'bold',
          fontSize: 12,
          fontFamily: 'Arial, sans-serif',
          color: 'white',
        },
      },
    },
```
(Link to already modified Plunker:)
https://plnkr.co/edit/6YGrEN4uLRrKV7DP?open=main.js&preview

**Current behavior**

The 'bar' theme override is applied to 'column' chart types and 'bar' chart types.
'column' theme override does not apply to any chart types.

**Expected behavior**

chartThemeOverrides: 'bar' should override bar charts, and 'column' should override column charts.

**Please tell us about your environment:**

Windows 10

* **AG Grid version:** Latest (31.0.3). Worth noting I did not see this issue in 29.3.5 which I was upgrading from.

* **Browser:** Chrome

* **Language:** [all | TypeScript X.X | **ES6/7** | ES5]

**Comment by AG-DavidG** [comment]
Hi @BaconEggsRL 

Thank you for bringing this up with us. 

We originally had separate `bar` and `column` series in AG Charts. In Version 9 of Charts (version 31 of AG Grid) this was changed to a single `bar` series with a differentiating `direction` property. This is why bar overrides apply to both, and column does not.

We have added a ticket in our backlog to allow the theme overrides to be targeted based on the series direction.

You can track it with this reference:
AG-10753 - [Charts] Allow `chartThemeOverrides` of 'column' to override horizontal bar series

You can follow the status of feature requests, bugs and releases using our pipeline:
https://charts.ag-grid.com/pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-10753) on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/

Thanks again for bringing this up with us - we appreciate your time!
