### ISSUE TITLE
PaginateChildRows false not working with groupRemoveSingleChildren

### ISSUE THREAD

**Issue by anuragkhanra** [ag-grid/ag-grid#7644]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
[https://codesandbox.io/p/sandbox/ag-grid-packages-forked-8tf99w](https://codesandbox.io/p/sandbox/ag-grid-packages-forked-8tf99w)

**Current behavior**
- In group column default behaviour of PaginateChildRows is work as expected false.
- But if groupRemoveSingleChildren is set to true, even with explicitly mentioning `groupRemoveSingleChildren={true}` , `paginateChildRows` is not working and expanded rows are pushed to the next page.

**Expected behavior**
- PaginateChildRows should work as expected with false, i.e, display all child rows in the same, irrespective of `groupRemoveSingleChildren` field set to  `groupRemoveSingleChildren={true}` 

**Please tell us about your environment:**

* **AG Grid version:** "^31.1.0"

* **Browser:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'

* **Language:** [all | REACT 18 | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hello @anuragkhanra,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10801**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
