### ISSUE TITLE
For async values, the dropdown does not adjust according to the height of the grid

### ISSUE THREAD

**Issue by anandjha96** [ag-grid/ag-grid#7656]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
https://www.ag-grid.com/react-data-grid/provided-cell-editors-rich-select/#async-values

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

For async values, the dropdown does not adjust according to the height of the grid. If you double click on dropdown of last cell, after loading... text appears the dropdown options are cut off from screen and are not even scrollable. Please fix this.

**Expected behavior**

This should work like normal dropdown of AG GRID where if its the last cell/ cell's height is not adequate then it switches the position of dropdown to upwards rather than downwards.

**Please tell us about your environment:**

IDE: VSCODE
PACKAGE MANAGER: NPM

* **AG Grid version:** 31.1.0

* **Browser:**

GOOGLE CHROME

* **Language:** [all | TypeScript 5.3 | ES6/7 | ES5]
TYPESCRIPT 5.3 
ES6

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: AG-10846

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
