### ISSUE TITLE
When clicking on the Page Label, the page size dropdown opens

### ISSUE THREAD

**Issue by Kuldeep-knoldus** [ag-grid/ag-grid#7675]
**Issue Description:**
**When clicking on the Page Label, the page size dropdown opens, but it should only open when the user clicks on the dropdown value**

- **Technology**: Angular
- This issue is related to `paginationPageSizeSelector`.

**Acceptance Criteria:**
1. The page size dropdown should not open when clicking on the Page Label i.e. **"Page Size:"**.
2. The page size dropdown should only open when the user clicks on the dropdown value.
3. Ensure that the dropdown remains closed when clicking anywhere outside of it, including clicking on other elements of the page.
4. Test the functionality across different browsers and ensure consistent behavior.

Reference Image:
![image](https://github.com/ag-grid/ag-grid/assets/76957624/e74df6a7-5c45-4c33-b0c7-8a3c5b1bdcfe)

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10902**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
