### ISSUE TITLE
GroupCheckboxSelectionCallback does not conditionally work for groupRows

### ISSUE THREAD

**Issue by arpitmohapatra** [ag-grid/ag-grid#7677]
I'm submitting a support request

Please find the below test link:
https://plnkr.co/edit/nbM4VBgLnH1maO2l?open=app.component.ts (Please look at line 70)

public groupRowRendererParams: any = {
    checkbox: true,
    // Below does not work
    /*
    checkbox: (params) => {
      if (params.value === "test") {
        return true;
      }
      return false;
    },
    */
}
checkbox display does not work with the GroupCheckboxSelectionCallback

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10883**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
