### ISSUE TITLE
Animations don't look right when setting empty rowData with getRowId option

### ISSUE THREAD

**Issue by daryakalenik** [ag-grid/ag-grid#7682]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

1. Open https://plnkr.co/edit/Hhbf3IBkzdh5YKe0?open=lib%2Fscript.js
2. Load the preview
3. Use input above the grid to search for a value - type (or just copy) name from the grid - for example 'Mila Smith' or 'Nora Thomas'
4. Click search button
5. Grid should show only one row and the detail grid should be open (it will also load some data)
6. When data is loaded search for another value - this time type something non-existent - for example '11111'
7. You should see that animations don't work as intended - the row dissapears and then the details grid is collapsed - all this actions are visible to user

**Current behavior**
As was said above, animations don't look right. I think that user should not see these operations happening

**Expected behavior**
The bug appears when grid has getRowId option - you can remove/comment it to see the ok-looking animations. So the expected behavior - the behavior without getRowId option

Angular 17.2,0, AG Grid 31.1.1
Windows 10 (but it also work the same way on macOs)

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

* **Language:**
TypeScript 5.3.3

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10906**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
