### ISSUE TITLE
There is a flickering issue in the horizontal scroll bar

### ISSUE THREAD

**Issue by sandeepsp2507** [ag-grid/ag-grid#7685]
**Current behaviour.**
 There is a flickering issue in the horizontal scroll bar

**Expected behaviour.**
 There should be a fixed scroll bar, or if it's not needed, there shouldn't be a scroll bar at all

* **AG Grid version:**30.2.1

please find the below attachment for more details, please let me know if any additional details required

https://github.com/ag-grid/ag-grid/assets/48769105/53e3a0db-f585-4663-ada0-90768f843e8e

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by sandeepsp2507** [comment]
Hi,

The Example is in the attachment please find it 

https://github.com/ag-grid/ag-grid/assets/48769105/36c4bc89-945b-4772-85a0-4d986692d2de

Thank you
Sandeep

**Comment by AG-Zoheil** [comment]
Thanks @sandeepsp2507.

For us to be able to effectively investigate this we need a sample reproducing the issue. As you know the grid can be configured in countless ways which is why a video alone will not be sufficient.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by pawelzysk** [comment]
Hi,
Please reopen this issue. I was able to reproduce the problem, and here's a link to the Codesandbox where it occurs: [link](https://codesandbox.io/p/sandbox/client-paging-forked-6gfl7g?file=%2Fapp.component.ts).

**Comment by somuda86** [comment]
@sandeepsp2507 We are having same issue , what was your solution/workaround if you could kindly tell us. Its happening for us on 67% zoom level in every chromium browser

**Comment by AG-Zoheil** [comment]
Hi @pawelzysk,

Thank you for providing the link. Can you please provide more information on how to reproduce it - I am unable to see the flickering. What resolution and/or screen size are you using, does it occur in all browsers, are you on a Mac or a Windows machine?

Looking forward to hear back from you.

**Comment by pawelzysk** [comment]
Hi @AG-Zoheil ,

Google Chrome - Version 124.0.6367.119 
Mac OS Big Sur - Version 11.3.1

**Comment by sandeepsp2507** [comment]
> @sandeepsp2507 We are having same issue , what was your solution/workaround if you could kindly tell us. Its happening for us on 67% zoom level in every chromium browser

@somuda86, currently I have done Ellipsis for the text in the cells.

**Comment by somuda86** [comment]
@AG-Zoheil We had to increase grid height by 10px or override vertical scroll bar of ag grid to display:none to reslove this. I think its not ideal.

**Comment by somuda86** [comment]
@AG-Zoheil Can we open this bug again?

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11587**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by pufok** [comment]
@AG-Zoheil 
Hello,
You resolved the problem with horizontal scroll, but vertical still has similar problem. Do you have it somewhere in your backlog to fix it?

**Comment by sabahang** [comment]
If this issue is still occuring for you please provide a code sample with version 32.1.0+ of the Grid (this is when we introduced a bug fix for this issue) and we are happy to look into it. The Codesandbox provided above is using version 31.3.1 which is before the fix was introduced

**Comment by pufok** [comment]
We see this problem on: 32.3.1 - horizontal is working well (issue resolved), but vertical scroll is still "dancing", when you start to use it. Can you check on your side if this didn't come back, if it was working after the fix in 32.1.0?

**Comment by sabahang** [comment]
@pufok we are not able to reproduce the issue anymore. If you think this is not the case please provide a live example with version 32.1.0+ and we will look into it. It might be useful to also send a GIF or clip of the issue if possible
