### ISSUE TITLE
AG-Grid Group Expand and Collapse issue

### ISSUE THREAD

**Issue by Padilipu** [ag-grid/ag-grid#7692]
Hello Team,
We are currently working on implementing single-level grouping in ag-Grid’s group cell renderer. The requirements are as follows:

**Scenario 1:**

1: When any one node is expanded, we need to display a specific set of columnDef and rowData.
2: When any one node is collapsed, we need to display the same set of columnDef and rowData as mentioned in point 1. (Please refer to the screenshot of the header below when any one of the nodes is expanded or collapsed.)
**Screenshot of the header below when any one of the nodes is expanded or collapsed**
![image](https://github.com/ag-grid/ag-grid/assets/161824687/50ed170a-3bd5-4f15-a235-6248a283c857) 

**Scenario 2:** 

3. When all nodes are expanded, we need to display a different set of columnDef and rowData. 
4. When all nodes are collapsed, we need to display the same set of columnDef and rowData as mentioned in point 3. (Please refer to the screenshot of the header below when all the nodes are collapsed.)
**Screenshot of the header below when all the nodes are collapsed**
![image](https://github.com/ag-grid/ag-grid/assets/161824687/190f733e-29f9-4368-8d6f-88bf5af27d8d)
 
**Our Implementation**: 
Whenever we expand or collapse a node, we update our grid data by setting a new columnDef and rowData.

**Problem:** 
The issue arises when we expand any one node, all the nodes get expanded. However, the same behavior is not observed when we collapse any of the nodes.

Could you please provide your suggestions on how to proceed to fix this issue? 

We are using the following version of ag-Grid Enterprise in our application: “ag-grid”: “18.1.1”.

**Comment by AG-Zoheil** [comment]
Hi 

Thank you for submitting this on Github.

I can see you have mentioned you're using AG-Grid version `18.1.1`, which is really old (from six years ago). Our current latest version is `31.1.1`.

I would highly recommend upgrading the version of AG-Grid in your application so that you can benefit from all the improvements in functionality, stability, theming and performance we've made since the version you're using.

Also, I'd recommend to upgrade the AG-Grid version sooner rather than later to avoid having even more changes to make as part of the upgrade process.

Kind regards,
Zoheil
