### ISSUE TITLE
Enable / Disable paginationAutoPageSize results in warning - Vue

### ISSUE THREAD

**Issue by jgreer9514** [ag-grid/ag-grid#7702]
Bug: 
Setting  gridApi.value.setGridOption("paginationAutoPageSize",true) and then gridApi.value.setGridOption("paginationAutoPageSize",false)

Results in:

AG Grid: The paginationPageSize grid option is set to a value that is not in the list of page size options.
                Please make sure that the paginationPageSize grid option is set to one of the values in the 
                paginationPageSizeSelector array, or set the paginationPageSizeSelector to false to hide the page size selector.

Grid must be configured with:                 
                pagination="true"
                paginationPageSizeSelector="[25, 50, 100]"

**Current behavior**
I have a context menu setup to enable / disable auto pagination on a right button click.  The warning shows in console when setting it to true and false.  The paginationPageSizeSelector has default values set by default so the warning should not apply.  

**Expected behavior**
No Warning.

**Please tell us about your environment:**
Vue

* **AG Grid version:** 31.1.1
Latest Version

Reproduce here:
https://codesandbox.io/p/sandbox/cool-tdd-s3l69m?file=%2Fmain.js

Right click and click Alert entry twice will result in the warning.

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10954**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
