### ISSUE TITLE
autoWrap=true

### ISSUE THREAD

**Issue by awdorrin** [ag-grid/ag-grid#7704]
In addition to setting 'white-space': 'normal', autoWrap should set 'word-break': 'normal' 
or there should be an additional wordBreak=true option.

Our current implementations have been to use:
`cellStyle: { 'white-space': 'normal', 'word-break': 'normal' },`

**Comment by AG-Zoheil** [comment]
Hello @awdorrin,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11253**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
