### ISSUE TITLE
Pinned columns are moved when resizing

### ISSUE THREAD

**Issue by RickyLeRoi** [ag-grid/ag-grid#7774]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
```

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
[link to sandobox](https://codesandbox.io/p/sandbox/ag-grid-packages-forked-8m3dd2)
Try to resize the grid (with "SizeDown" button or dragging the codesandbox panel).
To restore original state, click on SizeUp button and after 5 second the original column state will be restored.

**Current behavior**
When the grid is narrowed in width, the left-pinned columns that do not fit the new dimensions are unlocked starting from the first ones. No event is triggered, nor onColumnEverythingChanged.
When the grid returns to its original size, the unlocked columns remain in the incorrect position

**Expected behavior**
When the grid is narrowed in width, the columns should remain in place maintaining their attributes. When something happen to the columns, at least an event should be triggered (like onColumnEverythingChanged).

**Please tell us about your environment:**
Windows, react 16 
macOS, react 18

* **AG Grid version:** X.X.X
31.1.0 / 31.1.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Javascript, ES5/6

**Comment by AG-Zoheil** [comment]
Hi,

This is due to you applying the old columnState.

See this working [here](https://codesandbox.io/p/sandbox/ag-grid-packages-forked-8m3dd2?file=%2Fsrc%2Findex.js%3A52%2C5-57%2C14&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu11yxsm0006356g35d7aa3u%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu11yxsl0002356ge32f7qyi%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu11yxsl0003356g5zh0nk08%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu11yxsl0005356gethj96od%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu11yxsl0002356ge32f7qyi%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu11yxsl0001356g52sl7l8o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A52%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A57%252C%2522endColumn%2522%253A14%257D%255D%257D%255D%252C%2522id%2522%253A%2522clu11yxsl0002356ge32f7qyi%2522%252C%2522activeTabId%2522%253A%2522clu11yxsl0001356g52sl7l8o%2522%257D%252C%2522clu11yxsl0005356gethj96od%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu11yxsl0004356gfpl6q4cs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu11yxsl0005356gethj96od%2522%252C%2522activeTabId%2522%253A%2522clu11yxsl0004356gfpl6q4cs%2522%257D%252C%2522clu11yxsl0003356g5zh0nk08%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu11yxsl0003356g5zh0nk08%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) with that part commented out.

Kind regards,

**Comment by RickyLeRoi** [comment]
Hi AG-Zoheil,
As I wrote in the bug description
"To restore original state, click on SizeUp button and after 5 second the original column state will be restored."
Apply old column state was just a workaround to show the behaviour.
Even on your plunker, when you resize the grid, you lost the "pinned" status on columns that is not restored when you return to 100%.
Please review the state of this ticket.
Thanks
Riccardo

**Comment by AG-Zoheil** [comment]
Hi @RickyLeRoi,

Thank you for getting back.

Yes, you are right to say that it does not get restored - that is the default. Hence I was merely commenting on the delay in your original question.

As regards to it not getting restored, then this is due to the implementation of AG-3915 in v31 which was implemented to prevent an invalid state.

We do have a feature request to implement the restoration of the pinned state: AG-9852.

I hope the above clarifies the issue.

Kind regards,
Zoheil

**Comment by RickyLeRoi** [comment]
Thank you
is it correct in your opinion if I try to fix temporarely with this?
`    // TODO remove when AG-9852 is completed
params.api.eventService.allSyncListeners
        .get('columnContainerWidthChanged')
        .add(({api, columnApi, context, type}) => {
            let columnState = /*func to get column state enriched with colDef in every column*/;
                for (const colState of columnState) {
                    if (!!colState.colDef.pinned)
                        colState.pinned = colState.colDef.pinned;
                }
                /* func to apply columnState and order via api */
});
`

**Comment by AG-Zoheil** [comment]
Hi @RickyLeRoi, this could work as a temporary solution however I can't really comment on direct feasibility for your project.

Thanks for bearing with us until this is implemented!
