### ISSUE TITLE
Angular - Can't find stylesheet to import. starting in v 31.2.0

### ISSUE THREAD

**Issue by kbrilla** [ag-grid/ag-grid#7780]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
```
✘ [ERROR] Expected '.
  ╷
2 │ @use 'ag-grid-community/styles as ag;
```

**Expected behavior**
works just fine

**Please tell us about your environment:**
MacOS
Node v20.11.1
 "@angular/cli": "~17.2.0",
"ag-grid-community": "31.2.0",

* **AG Grid version:** 31.2.0
Works fine on 31.1.0

**Comment by sk-tjdownes** [comment]
We are experiencing the same issue, starting in 31.2.0

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by seanlandsman** [comment]
While we work on a fix for this you can workaround this by provide a path - for example: `@use "node_modules/ag-grid-community/styles" as ag;`

**Comment by AG-Zoheil** [comment]
We have added this bug to our backlog and we are tracking it with the following reference: **AG-11114**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.
