### ISSUE TITLE
lbLastRowOnPage is `?` in 31.2.0

### ISSUE THREAD

**Issue by Eugeno** [ag-grid/ag-grid#7788]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://www.ag-grid.com/angular-data-grid/server-side-model-pagination/

**Current behavior**
![image](https://github.com/ag-grid/ag-grid/assets/23382920/1646a60a-8c75-404f-bf92-5ae6fa06ddb8)

**Expected behavior**
as it was in 31.1.1:
![image](https://github.com/ag-grid/ag-grid/assets/23382920/ab49a11b-5fe4-49d9-b95e-7de3abb9f0e4)

**Please tell us about your environment:**

* **AG Grid version:** 31.2.0

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11123**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by Eugeno** [comment]
Such an unobvious search, btw:
![image](https://github.com/ag-grid/ag-grid/assets/23382920/b2ff77dc-4fe2-4672-9592-c005d15ed735)
![image](https://github.com/ag-grid/ag-grid/assets/23382920/ca7ba6b5-0f3b-4a18-aa93-a2c7615f885c)

**Comment by AG-Zoheil** [comment]
Thanks for making us aware of this @Eugeno - we will rectify this to enable simpler searches (ref: AG-11156).
