### ISSUE TITLE
AG Grid Upgrade Issue - Tab Navigation Problem

### ISSUE THREAD

**Issue by william-961** [ag-grid/ag-grid#7792]
- Description:

After upgrading **AG Grid** to version **31.1.1**, I encountered an issue with tab navigation. Previously, navigating using tabs worked properly. However, in the new version, whenever I change data in a cell and move to the next tab, the focus is lost.

This is the registered ID, and it is fixed for each row
![image](https://github.com/ag-grid/ag-grid/assets/98186434/463474b5-bedf-4a00-b3d3-e7d88bd293f4)

- Problem:

Navigating using tabs is no longer functioning as expected after upgrading AG Grid to version 31.1.1.

- Request:

Could someone please investigate this issue and provide guidance on how to resolve it?

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by william-961** [comment]
This is my GitHub repository URL: https://github.com/william-961/AgGridExample.git. The issue occurs when you update and then use the tab key to move to the next cell; it becomes unfocused

**Comment by sabahang** [comment]
Hi @william-961 

Having looked at your provided sample we are not convinced this is an issue with AG-Grid. In order to continue investigation we would need an isolated example 

We can only investigate issues that are AG Grid-related and that have been isolated. For instance, if your issue is wrapped in your own logic, we will try to diagnose, but you might find that we come back to you asking for a simplified version of the project showing only the issue in a simpler scenario.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,

**Comment by sabahang** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again

Regards
