### ISSUE TITLE
Cell editing cannot be opened if stopEditingWhenCellsLoseFocus is set to true

### ISSUE THREAD

**Issue by dongnguyenvie** [ag-grid/ag-grid#7809]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- i use this code https://ag-grid.com/javascript-data-grid/cell-editing-start-stop/#single-click-editing
- i set `stopEditingWhenCellsLoseFocus=true` 
- I just clicked the "edit icon" in the cell, the cell change to edit mode then to view mode immediately. expect: keep edit mode

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:
- [plunker link](https://plnkr.co/edit/6vYeMj6yo5nps6DI?open=index.tsx)

**A trick to solve the issue**
```
    api.refreshCells({
      force: true,
      rowNodes: [node]
    });

    setTimeout(() => {
      api.startEditingCell({
        rowIndex: node.rowIndex,
        colKey: column.getId()
      });
    }, 0);
```

* **AG Grid version:** 31.2.0

**Comment by AG-Zoheil** [comment]
Hello @dongnguyenvie,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11247**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by chrisvander** [comment]
I have this issue as well; inside of a custom cell renderer I call "startEditingCell" and nothing happens. This appears to be a regression from a previous version. Unfortunately, the above workaround does not work for me, it seems that the cell renderer loses any internal state and resets. I have to disable `stopEditingWhenCellsLoseFocus`.
