### ISSUE TITLE
Misnomer with theming variable --ag-cell-horizontal-border

### ISSUE THREAD

**Issue by ventralnet** [ag-grid/ag-grid#7815]
The theming variable to adjust the vertical cell border is named --ag-cell-horizontal-border

This should be --ag-cell-vertical-border

**Comment by AG-Zoheil** [comment]
Hi @ventralnet,

Thanks for getting in touch.

The logic behind the name was that `--ag-cell-horizontal-border` changes the border between two horizontally adjacent cells, but we understand this has confused people because the border itself is vertical.

We are aware of this and will be making the required changed in our next major release (this summer) as this will be a breaking change.

Kind regards,
Zoheil
