### ISSUE TITLE
Enabling pagination configuration results in abnormal pagination display.

### ISSUE THREAD

**Issue by sevent777** [ag-grid/ag-grid#7826]
**I'm submitting a bug report

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- enabling pagination configuration results in abnormal pagination display.
- [A plunker](https://plnkr.co/edit/RgRF5wOlA1S2UtWs?open=index.jsx)

**Current behavior**
Enabling pagination configuration, pagination don't work

**Expected behavior**
Enabling pagination configuration, pagination work normally

* **AG Grid version:** 31.0.2

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11314**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
