### ISSUE TITLE
Column hover highlighting doesn't work when highlighting over column headers when dynamically changing `columnHoverHighlight` to `true`

### ISSUE THREAD

**Issue by jkillian** [ag-grid/ag-grid#7829]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Plnkr Link: https://plnkr.co/edit/HwMLdiSAxf07WD7N?open=index.tsx

**Current behavior**
1. Create a table with `columnHoverHighlight={false}`
2. Afterwards, toggle the setting to `columnHoverHighlight={true}`
3. Observe that hovering over a cell causes the whole column to be highlighted, but hovering over the a column header does not.

**Expected behavior**
After `columnHoverHighlight={true}` is set, hovering over either a cell or column header should cause the column hover highlight to be displayed.

**Cause**
I don't know the full AGGrid lifecycle in depth, but it seems that this code only gets run at table initialization for column headers, which means that when `columnHoverHighlight` changes, the event listeners never get added:

https://github.com/ag-grid/ag-grid/blob/c708e50476a7cd032e641de15fab44c8cb552a54/community-modules/core/src/headerRendering/cells/hoverFeature.ts#L21-L25

**Please tell us about your environment:**

* **AG Grid version:** 31.2.0

* **Browser:** 
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'
(And all browsers I think)

* **Language:** Tested in the React version of the library

**Comment by AG-Zoheil** [comment]
Hello @jkillian,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11318**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
