### ISSUE TITLE
Reverse Tab from First Header Cell Loses Focus on Nested Grid Containing Several Columns and Horizontal Scroll.

### ISSUE THREAD

**Issue by tom-fitts** [ag-grid/ag-grid#7841]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Reverse Tab from First Header Cell Loses Focus on Nested Grid Containing Several Columns and Horizontal Scroll.

Issue occurs on a child nested grid containing several columns and a horizontal scroll. Steps to reproduce:
1. Scroll all the way over to the right of the child grid.
2. Click the last header cell of the child grid.
3. Reverse tab (Shift->tab) all the way back to the first header cell of the child grid.
4. The next reverse tab will lose focus. The expected behavior is for focus to now be on the last cell of the parent grid.

This can be reproduced with any nested grid example from the AG-Grid website with a slight modification in Plunker. Here is the link to the Plunker example:

https://plnkr.co/edit/spIDQNlwKcgGhGRr?open=main.ts&preview

1. Run the example and scroll all the way to the right of the child nested grid.
2. Click on the last header cell, which is labeled "New Column 5".
3. Reverse tab (Shift->tab) all the way back to the first header cell of the child grid, which is labeled "A2".
4. Now on the next reverse tab focus is lost.

Current Behavior: Notice cell focus is lost when reverse tabbing off the first header cell of the child grid.
Expected Behavior: The cell focus should be on the first cell of the next row of the parent grid.

AG-Grid Version: ag-grid-react: 28.2.1

**Comment by AG-Zoheil** [comment]
Hello @tom-fitts,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10522**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
