### ISSUE TITLE
For checkbox cell, the cellValueChanged event will not be fired once in the inline cell edit mode

### ISSUE THREAD

**Issue by dylannnn** [ag-grid/ag-grid#7898]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- For an editable check box cell, click on the empty space of this cell, it will enable the inline editing mode
- Check or un-check the checkbox
- Watch the console log

- Exit the inline editing mode for the cell
- Check or un-check the checkbox
- Watch the console log

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
For a check box cell, once enabled the editing and in the inline editing mode, the aggrid will not fire the **cellValueChanged** event

**Expected behavior**
For a check box cell, once enabled the editing and in the inline editing mode, the aggrid will still fire the **cellValueChanged** event

**Please tell us about your environment:**
plunker: https://plnkr.co/edit/rUXExgY8NF3KQ0k7?open=app.component.ts

* **AG Grid version:** ^31.2.1

* **Browser:**
Chrome/Firefox/Safari

* **Language:**
all

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11478**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
