### ISSUE TITLE
Custom filter rendered over table when setFilterModel is set on startup

### ISSUE THREAD

**Issue by holomekc** [ag-grid/ag-grid#7926]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When using setFilterModel() to set an initial filter on startup the custom filter component is rendered over the table at the bottom:
![image](https://github.com/ag-grid/ag-grid/assets/30546982/87a89a23-272d-4c22-b8e9-cc606bc15e09)
![image](https://github.com/ag-grid/ag-grid/assets/30546982/e49581e7-7d22-4025-9927-d08d592cdda8)

A click on the filter button in the table header fixes the issue and the filter behaves as usual, but on the next page reload the issue appears again.

**Expected behavior**
As in earlier versions the filter is not rendered over the table.

**Please tell us about your environment:**
Mac OSX Sonoma 14.4.1
IDE IntelliJ
Angular 17.3.7

* **AG Grid version:** X.X.X
31.3.1

* **Browser:**
Chrome

* **Language:** [TypeScript 5.4.5]

**Comment by sergioorlov** [comment]
I've the same problem...

**Comment by holomekc** [comment]
Hi @sergioorlov 
My ugly workaround is to adjust the custom filter with a property called hidden, which is initially set to true and is hiding the filter (display: none) and then set the value to false in the onOpened() hook. It is super ugly, but maybe helps until the issue is fixed.

**Comment by sergioorlov** [comment]
> Hi @sergioorlov My ugly workaround is to adjust the custom filter with a property called hidden, which is initially set to true and is hiding the filter (display: none) and then set the value to false in the onOpened() hook. It is super ugly, but maybe helps until the issue is fixed.

Thanks for your hack, but I'll return previous version for now and awaiting when ag-grid developers fix this problem )

**Comment by Kramy** [comment]
I found a similar case when we add a custom column filter to a grouped column that also has a column filter.

I've created a reproducible scenario [here](https://github.com/Kramy/testag3131).

**Comment by sergioorlov** [comment]
@AG-Zoheil when will be fix it ?

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: AG-11633

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
