### ISSUE TITLE
Expanding the column group will not recalculate the table width

### ISSUE THREAD

**Issue by liaokongVFX** [ag-grid/ag-grid#7928]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
Expanding the column group will not recalculate the table width。
![bug](https://github.com/ag-grid/ag-grid/assets/13622183/d1228459-cd0f-4e82-a73b-e2fd962fa80d)
Reproduction URL：
https://www.ag-grid.com/javascript-data-grid/column-groups/

**Current behavior**
Expanding the column group will not recalculate the table width。Only by manipulating the table can it be recalculated.

**Expected behavior**
After expanding the column group, if the table width is greater than the page width, a scrollbar will be displayed.

**Please tell us about your environment:**
windows 10

* **AG Grid version:** X.X.X
    "ag-grid-community": "^31.3.1",
    "ag-grid-vue3": "^31.3.1",

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

* **Language:** 
all

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11529**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by liaokongVFX** [comment]
> Hello
> 
> Thank you for reporting this - much appreciated!
> 
> Based on your description we've now reproduced this issue as a bug.
> 
> We have added this bug to our backlog and we are tracking it with the following reference: **AG-11529**
> 
> We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
> 
> See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page: https://www.ag-grid.com/ag-grid-pipeline/
> 
> The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).
> 
> Thanks again for bringing this up with us.
> 
> Kind regards, Zoheil

Thank you for your reply. In the custom headerGroupComponent component, using params. setExpanded to expand column groups can also cause the above issue. We look forward to fixing it together. Thank you!
