### ISSUE TITLE
Flashing scrollbars with autoPagination + autoSizeAllColumns

### ISSUE THREAD

**Issue by DBolderman** [ag-grid/ag-grid#7932]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

It is possible to get flashing scrollbars when you have rowgroups combined with the `paginationAutoPagesize` option and usage of `gridApi.autoSizeAllColumns()` or `gridApi.autoSizeColumns()`. 

When the width of the grid aligns with the right corner of the last column, and you open the latest visible rowgroup at the bottom, the scrollbars can't make up their minds anymore. The last visible row is constantly hidden - visible - hidden - visible - ...

When this occurs it's (almost) impossible to close the rowgroup again (or open another one) because the flashing blocks click actions inside the grid.  

![flashing-scrollbars](https://github.com/ag-grid/ag-grid/assets/159419754/fd8887fb-0f1c-4723-a7f6-70b608efd732)

Plunker example used in the GIF: https://plnkr.co/edit/Zqb2vvvloxU9Isgr?open=main.js

**Expected behavior**

The expected behaviour is that only the vertical scollbar appears when you open a rowgroup.

**Please tell us about your environment:**

* **AG Grid version:** 31.3.1 (Vue)

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

* **Language:** ES6/7

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11587**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
