### ISSUE TITLE
Incorrect Checkbox Icon Rendering for Boolean Values in Grouped Columns

### ISSUE THREAD

**Issue by christophkiser** [ag-grid/ag-grid#7972]
**I'm submitting a ...**
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

YES

**Providing a Reproducible Scenario**
When grouping a column that contains boolean values, the icons in the group node are not rendered correctly. Specifically, instead of displaying a checkbox with a check mark for TRUE values and an empty checkbox for FALSE values, the grid renders an empty checkbox for both TRUE and FALSE values.

[Plunker-Link](https://plnkr.co/edit/ZjzcvcNWJnFuevFB?open=app.component.ts&preview)

**Current behavior**
If I group a column that contains boolean values, the checkbox icon for 'TRUE' and 'FALSE' are both rendered as empty checkboxes (FALSE) in the grouping node.
<img width="381" alt="Screenshot 2024-05-15 at 10 23 53" src="https://github.com/ag-grid/ag-grid/assets/49731352/49191553-0fed-4cba-8bea-aba88f84ed0d">

**Expected behavior**
The grouping node for the booleans of 'TRUE' should show an checkbox with an check mark in it. The same way as it is shown if the column is not grouped.
<img width="544" alt="Screenshot 2024-05-15 at 10 25 05" src="https://github.com/ag-grid/ag-grid/assets/49731352/39f84303-9038-47ea-b51f-63592f2fb17f">

**Please tell us about your environment:**

* **AG Grid version:** 31.1.1
I installed the newest version (31.1.1) and still have the same issue.

* **Browser:**
Chrome, Safari, Firefox

* **Language:** 
TypeScript (Angular)

**Comment by sabahang** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-11649 [Row Grouping] When grouping columns with boolean values, group row checkbox icons render incorrectly

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,

**Comment by christophkiser** [comment]
Thank you for the update and for reproducing the issue!

I tried to follow up on this by checking the AG-11649 issue on the product pipeline page, but I wasn't able to locate it in the pipeline or any of the release notes. Could you please confirm if it's been added, or if there might be an alternative way to track its progress?

Kind regards,
