### ISSUE TITLE
Set Filter with excelMode

### ISSUE THREAD

**Issue by RomanZaidulin** [ag-grid/ag-grid#7984]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Good afternoon! I have plugged your library into my project and tried to use excelMode filter parameter. I noticed a strange behavior when setting a filter. Repeated attempt to set the filter resets the filtered values. But without excelMode everything works fine, the filter is not reset when clicking again. Here is a sample code that reproduces this situation. 
https://codesandbox.io/p/sandbox/set-filter-api-forked-7pcxnc?file=%2Fsrc%2Findex.tsx%3A117%2C7

AG Grid version: 31.3.2
I installed the newest version (31.3.2) and still have the same issue.

Browser:
Chrome

Language:
TypeScript (React)

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11650**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
