### ISSUE TITLE
Multiple grids in the same Vue component fail to load data after upgrade to v31

### ISSUE THREAD

**Issue by mbokil** [ag-grid/ag-grid#7990]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
<img width="1166" alt="v31" src="https://github.com/ag-grid/ag-grid/assets/1885868/617c543c-2acb-4986-89c4-43000dae9302">
<img width="1162" alt="v30" src="https://github.com/ag-grid/ag-grid/assets/1885868/0c8d3e87-1219-4c79-a20d-5f971cce4034">

**Current behavior**
Multiple grids in the same component fail to load data. Only the last grid loaded appears to load data. Note that this behavior started after upgrading from v30 to v31. Rolling back to v30 fixes the issue and is our current workaround.

**Expected behavior**
Multiple grids in the same component load data using separate gridOptions.

**Please tell us about your environment:**
macOS, NPM, Node/Express 18, Vite 5.2.11, Vue 3.2.47, script setup compiler hint

* **AG Grid version:** X.X.X
31.3.2

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11657**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
