### ISSUE TITLE
Ag Grid SSRM Row Group performance

### ISSUE THREAD

**Issue by Rikenunes8** [ag-grid/ag-grid#7993]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hi,
I'm using Ag Grid Enterprise JavaScript 31.0.1 and I am having issues developing the Row Grouping for Server-side mode (SSRM) due to the overwhelmed number of requests made to expand the groups.

**Our requirements are:**
- Row Group for multiple levels over a pagination of 100 rows (paginating child rows with `paginateChildRows = true`)
- Load the grid with all the groups and subgroups expanded (I'm aware of `isServerSideGroupOpenByDefault` property, but making it `return true` to open every group can potentially overwhelm our server with thousands of requests that is completely undesired)

**Is there any way to lazy expand all the groups and subgroups, avoiding this huge quantity of requests at a time?** 

I would really appreciate to find a solution to this issue. That's the only thing holding us back from purchasing the license and start using it in production.
Thanks in advance!

**Comment by AG-Zoheil** [comment]
Hi @Rikenunes8,

Thanks for getting in touch with us. This functionality is only available in the enterprise version of our datagrid. On our documentation page you can identify enterprise features by the red _**e**_ sign next to them.

You can read about getting started with both community or enterprise versions of our grid on [this page](https://ag-grid.com/javascript-data-grid/getting-started/). Further information about AG Grid licences can be found [here](https://ag-grid.com/license-pricing/).

We do not provide support for enterprise features via GitHub. However, especially since you are already evaluating us, I would encourage you to contact our CX Team via info@ag-grid.com. They will be able to help you with any licencing questions you may have and also re-direct any technical doubts you may still have about the product. `isServerSideGroupOpenByDefault` does not send requests in the way you've described above - so it may still well be a perfectly fine approach to your use case.

I hope this helps.

Kind regards,
Zoheil
