### ISSUE TITLE
header moving with scroll on using domlayout="autoHeight"

### ISSUE THREAD

**Issue by bharatprj28** [ag-grid/ag-grid#8006]
**Customers of AG Grid**

datagrid header moving with scroll when I am using domLayout="autoHeight" props. 
It should not move, should be sticky, found the same issue reported by someone - https://github.com/ag-grid/ag-grid/issues/7005,
but didn't got the solution in that. it is closed without proper solution.
let me know some solution to sticky header with domLayout="autoHeight" props. 

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- add domlayout="auotHeight" props to grid 
- set maxHeight for grid container
- see grid header with scroll some row of grid.
- A plunker - https://plnkr.co/edit/drBum33My4UrYbwC?open=index.tsx

Current behaviour.
Header moving with scroll on using domLayout="auotHeight"

**Current behavior**
Header moving with scroll on using domLayout="auotHeight"

**Expected behavior**
Header should be sticky, should not move with scroll

**Please tell us about your environment:**
windows

* **AG Grid version:** X.X.X
@ag-grid-community/core@29.3.5
@ag-grid-community/react@29.3.5

* **Browser:**
Chrome

* **Language:** Typescript

**Comment by sabahang** [comment]
Hello,

Thank you for bringing this up with us. 

The functionality you described wasn't part of the requirements when we built this feature. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-936 [Column Headers] Allow sticky (frozen) column header row when using domLayout=autoHeight and scrolling down with the browser vertical scrollbar**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by Rlamotte** [comment]
@sabahang I totally need this feature, do we have a way to upvote tasks on your backlog ?

**Comment by AruljothySundaramoorthy** [comment]
@sabahang 

I've also needed this feature, coz I have an use case like this to freeze the header when scrolling the data

**Comment by Abhid14** [comment]
Yup I too need sticky headers while scrolling. Its strange we don't have a standard way to achieve this 🥲

**Comment by AruljothySundaramoorthy** [comment]
Hey @Abhid14 @Rlamotte  @sabahang @bharatprj28  , i have made some CSS things which will provide a scrollable functionality with sticky header, try the below its working for me

```
:host ::ng-deep {
  .auto-height-grid {
    display: flex;
    flex-direction: column;
    height: 100vh;
  }

  .ag-header {
    position: sticky;
    top: 0;
    z-index: 2;
    background-color: #fff;
  }

  .ag-root-wrapper-body {
    flex: 1;
    overflow: hidden;
  }

  .ag-body {
    height: 100%;
    overflow-y: auto !important;
  }

  .ag-body-viewport {
    height: auto !important;
    max-height: calc(100vh - 50px);
    overflow-y: auto !important;
  }

  .ag-body-vertical-scroll {
    width: 8px !important;
    max-width: 8px;
    min-width: 8px;
    overflow-y: auto !important;
    position: absolute;
    right: 0;
  }

  .ag-center-cols-container {
    height: auto !important;
  }
}
```

Hope this will fix the issue🤞

**Comment by Abhid14** [comment]
Thank you @AruljothySundaramoorthy for helping us with this issue I will give it a spin and get back on this thread.

**Comment by divyaadurai** [comment]
Hi @sabahang, is there any update on this issue. I still see AG-936 is in backlog.
