### ISSUE TITLE
aggrid-vue3 31.3.2 Context will be watch deep ? true Can there be a different implementation method? Due to the Vue mechanism, variables that have been deep will be updated regardless of whether there is a value change, resulting in performance consumption

### ISSUE THREAD

**Issue by changjiaqio** [ag-grid/ag-grid#8007]
![企业微信截图_3b57ef4b-2563-4a80-a2ad-fce554b429f0](https://github.com/ag-grid/ag-grid/assets/97518513/f7ba76c2-5255-4849-b93e-e3b261da4a52)
![企业微信截图_1cc0c478-df34-421d-a7a3-0b61cb57a91a](https://github.com/ag-grid/ag-grid/assets/97518513/b634989c-7e09-4e02-b742-9d2c5706031e)
Can there be a different implementation method? Due to the Vue mechanism, variables that have been deep will be updated regardless of whether there is a value change, resulting in performance consumption

**Comment by changjiaqio** [comment]
![image](https://github.com/ag-grid/ag-grid/assets/97518513/b482a66d-48a5-4350-aaa5-ef32d49612c7)

**Comment by changjiaqio** [comment]
![image](https://github.com/ag-grid/ag-grid/assets/97518513/4dac75ed-2d95-430d-a31e-b2d0be4869b9)
When updating values during tab switching, deep listening will be triggered

**Comment by sabahang** [comment]
Hello!

Thank you for reporting this behavior - much appreciated!

We're keen to look into this but we need to be able to reproduce the issue you've described.

Please provide the following (as per our bug template in Github):
1. A live example (plunker, stackblitz, etc) or link to a repo showing the issue
2. A list of steps to follow to reproduce the issue
3. Descriptions of current behavior and expected behavior

We're looking forward to your response to we can investigate this further.

Thank you!

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
