### ISSUE TITLE
Pagination issue when sorting applied on empty grid

### ISSUE THREAD

**Issue by sarjak** [ag-grid/ag-grid#8010]
**I'm submitting a** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
* Open the [Plunker link](https://plnkr.co/edit/BJat81DwRmvalmky?open=main.ts&preview)
* Filter the 'Athlete' column in a way to get no records in grid. Hence, the pagination is set to **0 to 0 of 0**.
* Now apply sorting in any column in the grid, the pagination resets to pageSize.

**Current behaviour.**
The pagination gets set to the pageSize of the grid even when there are no records.

**Expected behaviour.**
The pagination should be set to **0 to 0 of 0** when there are no records to display.

* **AG Grid version:** 31.3.2

* **Browser:** Google Chrome

**Comment by sabahang** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-11692 [SSRM][Pagination] Pagination total count is wrong when grid is filtered with no matching rows and sorting

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
