### ISSUE TITLE
ag-grid copy paste to create new row in the grid - Need Help

### ISSUE THREAD

**Issue by san22230165** [ag-grid/ag-grid#8012]
Hi Team,
 I have a requirement in angular **ag-grid** like:
 if i copy a row in the grid and paste in the same grid, it should create a new row, which is pre-filled with the copied row values.

I analyzed, currently there is no event like rowCopied. Please help.

**Comment by sabahang** [comment]
Hello!

We're keen to look into this but we need to be able to reproduce the issue you've described.

Please provide the following (as per our bug template in Github):
1. A live example (plunker, stackblitz, etc) or link to a repo showing the issue
2. A list of steps to follow to reproduce the issue
3. Descriptions of current behavior and expected behavior

We're looking forward to your response to we can investigate this further.

Thank you!

**Comment by san22230165** [comment]
Hi Sabahang,

Thanks for your reply.

Current behavior - When a row is pasted the cell style of the copied row is not carried over to the new row

Expected behavior - Content which is pasted to the new row in the grid should take the style of the copied row as well

We are looking for work-around

**Comment by sabahang** [comment]
Hi @san22230165 

I'm not sure I can understand the specifics of the requirement you mention. Your initial question was around "creating a new row" and your second comment was regarding "carrying over style".

Here is one example from our docs where it can be seen that cell styles carry over with paste: 
https://ag-grid.com/javascript-data-grid/clipboard/#processing-data-from-clipboard

Here is Clipboard events with an example: 
https://ag-grid.com/javascript-data-grid/clipboard/#clipboard-events

Since the grid offers many features and it is difficult to accurately understand specific requirements, if anything is not already offered please use the following guideline to provide us with an exact write up of what is it that you need:

1. Locate an example in our documentation: https://www.ag-grid.com/javascript-grid-range-selection/
2. Select the Framework you’re using from the icons on the top-right of the page
3. On the left top of the example frame, click the bottom button to open it in Plunker or CodeSandbox.
4. Update the example code so the issue is reproduced
5. Keep your code as simple as possible, only show the behavior that demonstrates the issue.
6. Save the plunker (Click the Save button in the top-left corner)

Send us:

- The link to the reproducible scenario (Copy the URL from the browser
- A list of steps to follow 
- A description of the actual and desired behavior basedo n example

Plunker/CodeSandbox is the simplest way to provide a scenario because you can directly modify one of our documentation examples. However, if you prefer, you can use any other web-based tool such as stackblitz, etc.

**Comment by san22230165** [comment]
Hi Sabahang,
 
As per your request, I have created a simplified demo of my issue. Now if you see that first row has blue color text and when I copy and paste it to second row it does not show that color. In my project initially I have to keep the flag as false and based on the calculation it changes its color and when that row is copied and pasted it does not carry over the style as the flag for it is still false.
 
So, I want to know how can we copy those flags also with the data.

Plunker for demo -
https://plnkr.co/edit/CUwG1oumsTNfKevh?open=app.component.ts

**Comment by sabahang** [comment]
Hi @san22230165 

You are using an object property to decide styling options. Therefore, when you copy to clipboard you'll also need to carry over your entire row object not just the cell value (which i what normally gets copied)

You'll need custom code to copy and process your entire row objects. Here is an example:

https://plnkr.co/edit/yU8R0rRG1mfcQtaU?open=app.component.ts

We don't offer support support on Github so if you will need any further changes to this code you'll have to reach out to us on our official support channels
