### ISSUE TITLE
lockPinned not working when window is resizing

### ISSUE THREAD

**Issue by GeorgianStan** [ag-grid/ag-grid#8015]
Hi,

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
[Plunker](https://plnkr.co/edit/SDwJNT80dT8mD1iF?open=main.ts) - If the window is resized, the first column will be unpinned, even if it has `lockPinned` set to true.
[Video](https://streamable.com/s1eb6l?src=player-page-share)

**Current behavior**

Currently, when the window is resized, the pinned columns are automatically unpinned to make room for horizontal scrolling. 
I would expect that **only** the columns that do not have `lockPinned` set to `true` to do this.

**Comment by AG-Zoheil** [comment]
Hi @GeorgianStan,

Thanks for getting in touch via GitHub.

When the total width of the pinned columns reaches the the grid viewport width, the user is unable to see any of the unpinned columns. This is why in such cases by default, AG Grid unpins pinned columns starting from the left to the right.
 
You can override this behavior using the `processUnpinnedColumns` callback:
https://www.ag-grid.com/javascript-data-grid/grid-options/#reference-columnPinning-processUnpinnedColumns

I hope this helps.

Kind regards,
Zoheil

**Comment by binerdy** [comment]
@AG-Zoheil 

Thanks for the explanation.

What is the expected behaviour when I increase the windows size again (after what is described above)?
I would expect the state to go back to its original state.

Ideally, when restoring the window size again, originally pinned column become pinned again and are in the original order as before decreasing the window size.

Kind regards,
Alan

**Comment by AG-Zoheil** [comment]
Hello @binerdy,

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-9852**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by HaroldCarterAnsys** [comment]
Hey there!

It's not obvious to an existing ag-grid user that this is an expected behaviour as the [documentation](https://www.ag-grid.com/javascript-data-grid/column-pinning/#resizing-pinned-sections) is not linked clearly enough to cover this (needs to be referenced in all resize events [documentation](https://www.ag-grid.com/javascript-data-grid/grid-api/#reference-columnSizing-sizeColumnsToFit))

Additionally mutating config for no direct reason (helper functions) should consistently provide a dev message to the console; as without this Devs will burn time tracing this down. 

Because this is triggered by an internal event queue instead of a function call, debuggers can disconnect making manual debugging more difficult. not suggesting that needs to change, but it can't be relied on as a backup for the documentation; as it's also quite difficult to navigate.

callstack :

> `listenForResize`
> `onCenterViewportResized`
> `keepPinnedColumnsNarrowerThanViewport`


so, please be mindful in future of existing customers when making these changes and cover this with documentation from both new and existing customer perspectives.

this was internally raised as a bug because to an external perspective looks exactly like a bug.

kindest regards,
Harold.
