### ISSUE TITLE
ag-grid with autoHeight and fixed rowData does not recalculate pinnedToBottom row heights

### ISSUE THREAD

**Issue by andreirogobete** [ag-grid/ag-grid#8024]
**I'm submitting a:
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- Set ```autoHeight``` to ```true``` in the ```defaultColDef``` configuration
- In gridOptions, set ```rowHeight``` to 1
- In CSS, style the ```.ag-cell``` class with a line height (ex: ```2em```);

This should enable the grid to compute the row heights based on the given line height of the cell.

Reproducible example:
[Plunkr](https://plnkr.co/edit/vytKZNN1XMAQ3lXj?open=app.component.ts)

**Current behavior**
The pinned to bottom row height is not computed based on the line height of the ```.ag-cell``` provided value, but only the normal rows are computed

**Expected behavior**
The pinned to bottom row height should also be recomputed just like normal row data

**Please tell us about your environment:**
A simple angular application running locally

* **AG Grid version:** X.X.X
"@ag-grid-community/angular": "^31.3.2",

* **Browser:**
Chrome

* **Language:** [TypeScript 4.9.5]

**Comment by sabahang** [comment]
Hello,

Thank you for bringing this up with us. 

The functionality you described wasn't part of the requirements when we built this feature. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-4447 [Row Pinning] Allow autoHeight to work with pinned rows**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!
