### ISSUE TITLE
Number Cell Editor does not automatically enter into editing mode in Safari

### ISSUE THREAD

**Issue by ryansereno** [ag-grid/ag-grid#8037]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Using Safari, open the example number cell editor in the docs
https://www.ag-grid.com/vue-data-grid/provided-cell-editors-number/#enabling-number-cell-editor

**Current behavior**
When focusing on a cell with a single click or with an arrow key, and then typing numbers- ie. 1234, only the first number/keystroke is entered, and editing mode is not automatically enabled.

**Expected behavior**
The cell should go into editing mode and allow the full number to be entered; this is the correct behavior that is seen in Chrome.

You can also try the text editor cell, with safari, which behaves correctly.
Single click or arrow key focus on cell, then type a value, causes the cell to enter into editing mode:
https://www.ag-grid.com/react-data-grid/provided-cell-editors-text/#enabling-text-cell-editor

**Please tell us about your environment:**
Safari, Mac OSX Sonoma 14.4.1

* **AG Grid version:** 
    "ag-grid-vue3": "31.3.1",

* **Browser:**
Safari, Version 17.4.1

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11858**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
