### ISSUE TITLE
Single click edit is not working as expected

### ISSUE THREAD

**Issue by deepakraj8298** [ag-grid/ag-grid#8041]
Hi Team,

I am facing one issue, in single cell we have two input fields which is getting rendered using cell renderer and we have custom cell editor.
now refer attached image there if user clicks on row1.1 then it should be editable on single click.
i am using  afterGuiAttached?() for single cell with single input it is working fine but wherever we have two input fields then it is selecting the first input even if we are clicking on second input within same cell.

Currently using AG-Grid - "ag-grid-enterprise": "18.1.1"

<img width="401" alt="entervalue" src="https://github.com/ag-grid/ag-grid/assets/32891914/809d5482-bda4-43b9-8804-69e301b5c786">

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for submitting this on Github.

I can see you have mentioned you're using AG-Grid version `18.1.1` which is quite old. Our current latest version is `31.3.2`.

I would highly recommend upgrading the version of AG-Grid in your application so that you can benefit from all the improvements in functionality, stability, theming and performance we've made since the version you're using. If you need help with licencing please contact us via info@ag-grid.com.

Kind regards,
Zoheil
