### ISSUE TITLE
groupDisplayType custom not working in pivotMode

### ISSUE THREAD

**Issue by SietsevTilburg** [ag-grid/ag-grid#8088]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Here is a plunker reproducing the issue: https://plnkr.co/edit/nT2Va4YAsBgDTGWM?open=main.js&preview

When you disable the pivotMode in this plunker the customGroup will work.

**Current behavior**
Currently the custom columnDef for the rowGroup gets ignored in pivotMode.

**Expected behavior**
I expect it to have the same behaviour as the grid non pivotMode, because in the documentation of the pivot mode there is a section about groupDisplayType="multipleColumns". So I expect custom to also be a option as it is still a grid?

**Please tell us about your environment:**

* **AG Grid version:** 31.3.1 and 31.3.2 (Tested on these versions)

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

* **Language:** [all | Javascript | vue2/3]

**Comment by sabahang** [comment]
Thanks for your inquiry @SietsevTilburg 

I have tried to understand your use case but would need more information to be able to give any answer at this point. 
Your plnkr lacks any pivot rows and also as per documentation a Custom Group Column needs a cellRenderer. I have modified your plnkr to add the above: https://plnkr.co/edit/bFr9TaB691OhL1dl?open=main.js however I'm still failing to see what exactly is your desired result.

To investigate this further please follow the steps below:

1. Use the above given plnkr as a base example, fork it 
2. Update the example code so the issue is reproduced
3. Keep your code as simple as possible, only show the behavior that demonstrates the issue.
4. Save the plunker (Click the Save button in the top-left corner)

Send us:

- The link to the reproducible scenario (Copy the URL from the browser)
- **A list of steps to follow to reproduce the issue**
- **A description of the actual(incorrect) and expected(correct) behavior**

**Comment by SietsevTilburg** [comment]
Thanks for the response @sabahang

Plunker: https://plnkr.co/edit/Qa00OjbqvDSAZEpN?open=main.js&preview

1. Set pivotMode="false"
2. Set pivotMode="true"

What I want to do is edit the headerName, add custom styling (cellStyle) and remove the count from the rowgroups in a pivotGrid. Currently I have this working in pivotMode="false" or when prop is not added as seen in the plunker when disabling the pivotMode or removing the prop from the grid. But as soon as pivotMode=true the custom headerName/styling and all other props don't have any effect on the rowgroups. It just says group in the headerName of the rowgroups.

I expect a custom group column to also work for a pivot grid, but as of now it does not seem to use the custom group column and just ignores it.

**Comment by AG-Zoheil** [comment]
Hi @SietsevTilburg,

We generally advise against this kind of definition. During pivot mode the grid defaults back to the auto generated group column. You can find more details about Custom Group Columns here: https://ag-grid.com/javascript-data-grid/grouping-custom-group-columns/.

Kind regards,
Zoheil
