### ISSUE TITLE
ag-grid auto resize API does not resize properly when the columnDefs and rowData are both set in useEffect()

### ISSUE THREAD

**Issue by kfaiczak** [ag-grid/ag-grid#8093]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Plunker scenario
https://plnkr.co/edit/C4xTfCUV2UigjGOR

We have multiple sets of data
we want to update the columnDefinitions and the RowData when we switch

both buttons call the same function Update() to switch the data
onRowDataUpdated() is called in all cases when we switch the data
event.api.autoSizeAllColumns(false); is called from there

if we switch the data from the parent (via prop and useEffect()) it fails to resize the columns, when we call the autoSizeAllColumns()  (sporadically it does actually work but mostly it fails and you get "Column...")

if we switch it from a local button calling the Update() directly then the columns always resize properly

This is a simplified example (in our case data/defs are coming in as props from the network) useEffect is used to load to state variables as is done here
everything works fine except for the resize on the update
the 'first time always works' but that is due to the autoResizeStrategy
we could of course create a new Ag-Grid each time (add key=uuidv4()) but then it flashes miserably and is inefficient

**Current behavior**
when updating the rowData and columnDefs from UseEffect() the api call to autoSizeAllColumns(false) should resize the columns correctly from onRowDataUpdated() event
(Note: if the columnDefs don't change .. just the rowData then the columns do get resized correctly, but changing them both the columnDefs headers are truncated with ...)
Sometimes it does actually resize correctly (but that is rare 1 in 20?)

**Expected behavior**
Updating the rowData and columnDefs from useEffect() should be the same as updating it from a local function, ie data is updated and the resize works the same in either case (column resized so headerNames + data fits)

**Please tell us about your environment:**
MAC Sonoma 14.5
Chrome 125.0.6422.142 (Official Build) (arm64)

* **AG Grid version:** X.X.X
ag-grid-community@31.3.2
ag-grid-react@31.3.2

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'

* **Language:**
React 18.3.1

**Comment by StephenCooper** [comment]
Hi,

While we investigate an solution there are two potential workarounds. Either using layout effect which has the impact of rendering the grid changes synchronously so that the headers are rendered before the grid event is fired.

The other option is to run the update in a setTimeout.

```ts
 // useLayoutEffect(() => {
    useEffect(() => {
        Update()
        // setTimeout(() => Update())
    }, [count])
```

We have plans to remove the need for these work arounds and hide the complexity of React rendering async / sync from you.

**Comment by StephenCooper** [comment]
We have added this to our backlog and we are tracking it with the following reference AG-11977
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
You can get an update on the status of this item on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).
 
Thanks again for bringing this up with us.
