### ISSUE TITLE
Calendar Icon doesn't show in chrome based browsers

### ISSUE THREAD

**Issue by Axeltherabbit** [ag-grid/ag-grid#8094]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
I'm using React with vitejs. 
I'm also using tailwind, maybe that's the cause of the missing icon?

```
import { AgGridReact } from 'ag-grid-react'; // React Data Grid Component
import "ag-grid-community/styles/ag-grid.css"; // Mandatory CSS required by the grid
import "ag-grid-community/styles/ag-theme-quartz.css"; // Optional Theme applied to the grid
```

cell definition: 

```
{
    field : DISPLAYCOLUMNS.PLANNED_START,
    cellDataType : "date",
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
        min: '2024-01-01',
    },
    editable: true,
    valueFormatter: (params: {value : string}) => {
      const date = new Date(params.value);
      return date.toISOString().split('T')[0]; // Format to "YYYY-MM-DD"
    },
    valueParser: (params: {newValue : string}) => {
        return new Date(params.newValue);
    },
    singleClickEdit: true
    }
```

**Current behavior**
No calendar icon on chrome based browsers, I've the icon on Firefox.

**Expected behavior**
Calendar icon shows on cell edit

**Please tell us about your environment:**
Windows

* **AG Grid version:** X.X.X
    "ag-grid-community": "^31.3.2",
    "ag-grid-react": "^31.3.2",

* **Browser:**
Chrome based browsers.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Should be a css issue

Firefox on the left side, Chromium on the right side
![Screenshot (345)](https://github.com/ag-grid/ag-grid/assets/28351404/cfaa7269-9995-41f6-b21c-72087effd4b5)

**Comment by sabahang** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please follow the steps below:

1. Locate an example in our documentation: https://www.ag-grid.com/javascript-grid-range-selection/
2. Select the Framework you’re using from the icons on the top-right of the page
3. On the left top of the example frame, click the bottom button to open it in Plunker or CodeSandbox.
4. Update the example code so the issue is reproduced
5. Keep your code as simple as possible, only show the behavior that demonstrates the issue.
6. Save the plunker (Click the Save button in the top-left corner)

Send us:

- The link to the reproducible scenario (Copy the URL from the browser)
- A list of steps to follow to reproduce the issue
- A description of the actual(incorrect) and expected(correct) behavior


Plunker/CodeSandbox is the simplest way to provide a scenario because you can directly modify one of our documentation examples. However, if you prefer, you can use any other web-based tool such as stackblitz, etc.

PS: Also your screenshots won't open. Please provide them again

**Comment by Axeltherabbit** [comment]
Hello, 

I'm not sure why you can't see the screenshot, I can see it, try this url, please: [url](https://private-user-images.githubusercontent.com/28351404/340239036-cfaa7269-9995-41f6-b21c-72087effd4b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDk0OTUsIm5iZiI6MTcxODgwOTE5NSwicGF0aCI6Ii8yODM1MTQwNC8zNDAyMzkwMzYtY2ZhYTcyNjktOTk5NS00MWY2LWIyMWMtNzIwODdlZmZkNGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE0NTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYTdkMjVlZjk4ZTExOGExMzUzNjg0ZjViY2IzYzE3ZjgwNjMyMDM2OTE1MDcxNDVkYjA4ZmNlMTJjOTEwODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7nBZkoHgwk5phLE7tNZg_QUP3RyVbcyejy-meLVzgks)


I'll try to create a reproducible example later next week.

**Comment by Axeltherabbit** [comment]
Hello,

Here is a reproducible example, I didn't use Tailwind, so I guess tailwind is not the cause:

https://codesandbox.io/p/devbox/calendarbug-cm6l2y

**Comment by sabahang** [comment]
Hi @Axeltherabbit 

I have used a close approximation of your code in a different example and as you can see icons are loading.

Please see it here:
https://plnkr.co/edit/CVWA1z3dMQRQnajs?open=index.tsx

I suspect the issue is somewhere in your code. We cannot troubleshoot your code but if you examine it closely you should be able to find the part responsible for not showing the icon

Hope this helps

**Comment by Axeltherabbit** [comment]
Thanks, it was due to some problem on my index.css
