### ISSUE TITLE
Adding a new row with the same name as an existing row causes the grid to override the current row.

### ISSUE THREAD

**Issue by Maddy-O** [ag-grid/ag-grid#8097]
I am currently working on a feature where I need to add new rows to the grid in tree data mode. The rows can have the same name as the existing ones in the grid. However, I am encountering an issue where adding a new row with the same name as an existing row causes the grid to override the current row, and I receive the following warning in the console: "duplicate group keys for row data, keys should be unique."

For instance, I want to add another row named "Cash" under the "Total Super Senior Debt" group, but the grid is not allowing me to do so due to the duplicate key issue. Below is the relevant screenshots.

![Add row](https://github.com/ag-grid/ag-grid/assets/95930594/6486b610-b5a4-4659-a61b-7bb665e27ee5)

![duplicate row](https://github.com/ag-grid/ag-grid/assets/95930594/74bd9df6-0498-44b3-b120-56ae24c5c965)

Could you please confirm whether ag-Grid supports such a functionality? If so, I would greatly appreciate any guidance or instructions on how to implement this feature effectively.

**Comment by sabahang** [comment]
@Maddy-O have you explored the following part of the documentation?
https://www.ag-grid.com/javascript-data-grid/column-definitions/#column-ids

Grid can use different values as ID to ensure uniqueness. 

Hope this helps. It would be much easier to understand your use case if you provided a plnkr live example

I'm closing the issue as hopefully the above helps but if your issue is not resolved we can reopen it when you will have a concrete example and steps to reproduce

**Comment by Maddy-O** [comment]
@sabahang For better reference, I am attaching a short video about what I want to achieve. In this video, I am trying to add a new row, ABL, which is already present in the grid. The first time I add the row, it overrides the data. The second time, it adds the row. The third time, it does not add the row, but on the fourth attempt, it adds the row again. This random behavior is a bit confusing.

https://github.com/ag-grid/ag-grid/assets/95930594/5d2850b5-2177-4cd4-8247-5f4ec183544b

 I would greatly appreciate any guidance or instructions on how to implement this feature effectively.
