### ISSUE TITLE
Excel Export - Hyperlinks using multiple parameters causing Err:508

### ISSUE THREAD

**Issue by Eugeno** [ag-grid/ag-grid#8105]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I discovered that I cannot fully utilize the [Excel Export - Hyperlinks](https://ag-grid.com/angular-data-grid/excel-export-hyperlinks/) feature. The issue lies with the `HYPERLINK` function, which has a second parameter that I would like to use to achieve something like this:
`=HYPERLINK("https://somesite.com/section/sub/item1"; "item1")`
The problem is that with the `autoConvertFormulas` flag (without which this feature doesn't make sense), the semicolon in the formula is converted to a vertical bar: `=HYPERLINK("https://www.google.com"| "link")`, causing it to display as `Err:508` in the table.
[plunker](https://plnkr.co/edit/FdAUu77MMu4d4YvN?open=app.component.ts&preview)

* **AG Grid version:** 31.3.2

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12040**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
