### ISSUE TITLE
BUG: rowDragEnd event not fired when cursor is outside the grid, while managed row dragging does reorder the rows

### ISSUE THREAD

**Issue by evpaassen** [ag-grid/ag-grid#8128]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

### Plunker: https://plnkr.co/edit/q4kiJiaJdRfZ2W4s?open=main.ts

This is just the managed row dragging example, with added event callbacks that log relevant dragging events.

Steps to reproduce:
1. Grab a row.
2. Drag it up, somewhere between the other rows. Don't let go yet!
3. Move the mouse cursor outside of the grid (e.g. to the left or to the column headers). Observe that the drag 'ghost' changes to a 🚫 icon.
4. Let go. Observe that the rows have been reordered by managed dragging.
5. Look at the browser console to see what events have fired.

**Current behavior**
The rows have been reordered by managed dragging, but when looking at the browser console the grid only fired a `rowDragLeave` event, because the cursor left the grid while dragging.

Since the `rowDragEnd` event has not been fired, the application code itself has no way of detecting that the row order has changed.

**Expected behavior**
Whenever the row order is changed by dragging, a `rowDragEnd` event is fired.

So there are two options when a row was dropped outside the grid:
1. DO reorder the rows as is currently the case, and DO fire a `rowDragEnd` event.
2. Do NOT reorder the rows and do NOT fire a `rowDragEnd` event.

I'm quite sure this did work correctly with AG Grid 29, but since then the drag position handling was reworked in 3080071a41a4575b1913f481adcad33718bcbc97, which might have caused the issue.

**Please tell us about your environment:**

* **AG Grid version:** 31.3.2 (latest at the moment of writing)

* **Browser:** Chrome 126
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'`

* **Language:** all

**Comment by AG-Zoheil** [comment]
Hi @evpaassen,

Thank you for raising this on GitHub.

Please note the following:

When a `rowDrag` event occurs outside of the grid, the grid doesn't get notified by the browser. This is because events get fired for the element where the drop occurs. Instead a `rowDragLeave` event is fired when the bounds of the grid are left. If you want to notify the grid that a drag or drop is happening outside of the grid, you need to handle the browser drop event over the element where the drop occurs (the HTML body for example, if you want to be sure you'll catch this event) and invoke grid API to notify the grid that the drag has ended.
 
This needs to be implemented using application-level code handling drag/drop events in the page outside of the grid because AG Grid isn't responsible for drag & drop across the entire page, but instead only over its own bounds. 
 
Alternatively, you can set `suppressMoveWhenRowDragging` to `true` to prevent the row from moving so if a user drops it over the column header row or outside of the grid, the dragged row position doesn't change.

I hope this helps.

Kind regards,
Zoheil

**Comment by EliottPal** [comment]
This issue stills happens in August 2025.
Pretty annoying to see that we cannot detect the rowDragEnd event even tho the row does move.

The _suppressMoveWhenRowDragging_ gives a different behaviour to the grid that I don't want. I jsut wish there was a way to detect this event.

**Comment by ryansereno** [comment]
November 2025, running into this same issue
The grid is visually correct- row gets correctly moved; but no way to handle the result of the move.

@evpaassen or @EliottPal were you able to find a workaround for this? Other than suppressMoveWhenRowDragging?

**Comment by ryansereno** [comment]
Update:
This appears to be working for me

```js
function onGridReady(params) {
  const headerElement = document.querySelector(".ag-header");
  if (headerElement && gridApi.value) {
    gridApi.value.addRowDropZone({
      getContainer: () => headerElement as HTMLElement,
      onDragStop: (params) => {
        const draggedNode = params.node;
        if (draggedNode?.data) {
        //handle drop event here
        }
      },
    });
  }
}

```
