### ISSUE TITLE
DOM destroyed

### ISSUE THREAD

**Issue by lxp-eng** [ag-grid/ag-grid#8133]
Table scrolling will destroy the first few rows of elements, which is not optimized for rowSpan. Merging rows usually involves the cells in the first row covering the cells below. However, when the first row is destroyed, the merging effect of the cells below is lost. Moreover, if the merged cell text is displayed in the middle, it will flicker and disappear

**Comment by lxp-eng** [comment]
https://plnkr.co/edit/?open=main.js&preview

**Comment by lxp-eng** [comment]
[](https://plnkr.co/edit/?open=main.js&preview)    This is a demo on your official website；You change line 74 of main.js to return 40;And add display: flex,alignt-item:center to. cell-span in style.css;Rolling the table has an effect. When the scroll bar scrolls to a certain extent, it will lose the style and effect of merged cells

**Comment by lxp-eng** [comment]
[](https://plnkr.co/edit/?open=main.js&preview)     This is a demo on your official website；You change line 74 of main.js to return 40;And add display: flex,alignt-item:center to. cell span in style.css;Rolling the table has an effect. When the scroll bar scrolls to a certain extent, it will lose the style and effect of merged cells;

**Comment by lxp-eng** [comment]
https://plnkr.co/edit/?open=main.js&preview

**Comment by lxp-eng** [comment]
![Snipaste_2024-06-27_09-24-40](https://github.com/ag-grid/ag-grid/assets/73985598/17c922b6-4d88-4895-b4c8-5acab8d6b32a)
This is a demo on your official website；You change line 74 of main.js to return 40;And add display: flex,alignt-item:center to. cell span in style.css;Rolling the table has an effect. When the scroll bar scrolls to a certain extent, it will lose the style and effect of merged cells

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-5975**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
