### ISSUE TITLE
[CRITICAL] V32 error with zone.js framewroks like Angular

### ISSUE THREAD

**Issue by leonelvsc** [ag-grid/ag-grid#8229]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Usage of ag-grid v32 with zone.js broke the app with error
`main.esm.mjs:1492 AG Grid: Unknown API function: 'then' on GridApi.`

looking at implementation i see that you now use a `Proxy` for checking if the method exists, well there should be a safelist of methods that should return undefined like `then`.

Zone.js that throws error from Proxy handler get method is

```
function resolvePromise(promise, state, value) {
            const onceWrapper = once();
            if (promise === value) {
                throw new TypeError(TYPE_ERROR);
            }
            if (promise[symbolState] === UNRESOLVED) {
                // should only get value.then once based on promise spec.
                let then = null;
                try {
                    if (typeof value === 'object' || typeof value === 'function') {
                        then = value && value.then;
                    }
```

value.then executes the new Proxy get method

**Expected behavior**

Should not throw an error for safe methods like `.then` for checking if it's a Promise, or not throw error just a console warning and return undefined

Ag v32

Typescript Angular v18

Repro: https://stackblitz.com/edit/stackblitz-starters-mtzipd?file=src%2Fmain.ts ( open in new window if you don't see the "console" button )

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12047**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
