### ISSUE TITLE
Security issue: CVE-2024-39001

### ISSUE THREAD

**Issue by agrt56** [ag-grid/ag-grid#8261]
**I'm submitting a
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

A security issue has been reported with AG Grid version 31.3.2 (CVE-2024-39001):
https://www.tenable.com/cve/CVE-2024-39001

Are previous versions (<31.3.2) also affected and has this issue been fixed in the most recent 32.0.0. update? 

* **AG Grid version:** 31.1.0, Angular

* **Language:** TypeScript

**Comment by AG-Zoheil** [comment]
Hi @agrt56,

Thank you for raising this on GitHub. Please note that we are aware of the issue and are looking to release a patch for version 32 next week which will include a fix for this.

Kind regards,
Zoheil

**Comment by madhavsarpalJG** [comment]
Hi @AG-Zoheil , 
Just wanted to make sure that the patch will also include resolution for similar but newer [CVE-2024-38996](https://github.com/advisories/GHSA-876p-c77m-x2hc).

Regards
Madhav

**Comment by AG-Zoheil** [comment]
Hi @madhavsarpalJG ,

Thank you for your comment.

Correct - both issues will be addressed.

**Comment by madhavsarpalJG** [comment]
@AG-Zoheil One more question - will there be a patch for version 31 as well? Asking since we are on 31 and have not yet migrated to 32.

Regards

**Comment by AG-Zoheil** [comment]
Hi @madhavsarpalJG,

The patch will be for version 32 only. If you have not yet upgraded I'd advise to wait for the patch to be released this week and upgrade straight to that version.

Thanks!

**Comment by Blackbaud-PaulCrowder** [comment]
@AG-Zoheil could you backport this fix to version 31? Our organization has a large footprint of applications that use AG Grid, and we will not be ready to migrate to 32 and address breaking changes for another few months. Since this is a critical issue, we have a very short timeframe in which we must remediate this issue, and without an official backport we will have to fork AG Grid, incorporate the fix, and file a significant amount of paperwork to document our remediation procedures. We're willing to contribute this via a PR as a way to move this forward.

**Comment by AG-Zoheil** [comment]
Hi @Blackbaud-PaulCrowder,

Thank you for your comment.

Whilst I can empathise with your constraints of upgrading, I'm afraid we will not be patching any previous versions. In principle our patches are only released for the latest version (`v32` for this patch).

Our recommendation to all our users regardless of which historic version of the grid they are running would always be to upgrade to the latest available version of AG Grid.
It is with this in mind that we "only" release two major versions (with breaking changes) a year to help mitigate some of the toll that upgrading takes. Furthermore we've introduced codemods since `v31` to help with the migration.

Please also keep in mind that, besides the usual new features and bug fixes, a lot of under-the-hood work goes in to our releases including things such as performance and security improvements. Therefore we can only emphasise to upgrade at your earliest possible convenience.

Kind regards,
Zoheil

**Comment by Blackbaud-PaulCrowder** [comment]
@AG-Zoheil That decision puts my organization in a very awkward position. We have less than 30 days to remediate this vulnerability, but because of the breadth of applications we manage we will not be able to upgrade to 32 for 2-3 months. We understand the value of staying current on dependencies; my team manages [its own open-source project](https://developer.blackbaud.com/skyux/) that has a semi-annual release schedule for major versions, and we encourage our consumers to upgrade as soon as possible. Having said that, we recognize the variability of our consumers' own schedules, so we continue to maintain previous versions and update them when critical vulnerabilities are discovered.

The practice of backporting critical fixes is not uncommon. I've looked at the commit where the fix was incorporated, and it is limited to just a few files (most of which are unit tests). As I said before, my team is happy to submit a PR with the changes in your version 31 branch. I ask that you reconsider this decision for the benefit of the open-source community who find significant value in AG Grid.

**Comment by AG-Zoheil** [comment]
Hi @Blackbaud-PaulCrowder,

We appreciate the concerns & challenges of your organisation that you've outlined.

From your reply, it seems that you are one of our enterprise clients. Can I please encourage you to contact us via our dedicated [support portal](https://ag-grid.zendesk.com/hc/en-us). In general this would be the point of contact we recommend all enterprise clients to go to for any issues or suggestions. Once we receive your request via Zendesk, our team of specialists will aim to support you as best as possible to find a solution to the task at hand.

We're looking forward to hearing from you on Zendesk.

Thank you

**Comment by trd-warren** [comment]
I hope this will patched in `v31`. We are using it in a Vue 2 project, migrating from Vue 2 to 3 to migrate AG Grid to v32 will cause more problems.

**Comment by AG-Zoheil** [comment]
Please note that we can confirm that our findings are in line with the EPSS rating of the vulnerability that stands at just 0.05% (independently verified here: https://www.cvedetails.com/cve/CVE-2024-39001/), meaning this vulnerability is extremely unlikely to be exploited.
 
We acknowledge that there may be regulatory pressures to resolve this reported vulnerability despite the extremely low risk involved. Therefore we have provided patches for our latest version (`v32`) and the version it was reported in (`v31`). Therefore, in your case, you only need to upgrade to `31.3.4` for a solution to the vulnerability issue.

Thanks

**Comment by Archer03** [comment]
Hi @AG-Zoheil
I still got this issue from ag-charts-community: 9.3.2
Version Affected [5.0.0, 10.0.2]

so it dose help if upgrade to v31.3.4 or v32

**Comment by jpsla94** [comment]
> Hi @AG-Zoheil I still got this issue from ag-charts-community: 9.3.2 Version Affected [5.0.0, 10.0.2]
> 
> so it dose not help if upgrade to v31.3.4 or v32

Hello @AG-Zoheil,

Any update regarding this?

Best regards,
João Lola

**Comment by AG-Zoheil** [comment]
Hi @Archer03 and @jpsla94,

We offer two products: **AG Grid** and **AG Charts**.

`31.3.4` and `32.0.2` were patches provided for **AG Grid**.

**AG Charts** has been addressed via patch `9.3.2` for version 9 and patch `10.0.2` for version 10.

As long as you are using one of the correct versions above (or later versions that have been released since) you should have the fix.

Hope that clarifies it.

Thanks!

**Comment by AndrewN93** [comment]
Hello @AG-Zoheil,

We are currently using several major dependencies in our project that rely on Ag-Grid version 28. However, our security scanning tools have reported an issue with this version.

Will there be a patch for v28 similar to those released for the newer versions? 

Thank you!

**Comment by AG-Zoheil** [comment]
Hi @AndrewN93,

Thank you for your comment.

Please refer to my comment here: https://github.com/ag-grid/ag-grid/issues/8261#issuecomment-2268364662.

We have provided patches for our latest version (`v32`) and the version it was reported in (`v31`) - there will be no further patches.

Thanks!
