### ISSUE TITLE
Issue with ag grid vertical scroll

### ISSUE THREAD

**Issue by santoshkumar-maddela** [ag-grid/ag-grid#8268]
Hi Team,

I am facing issue with aggrid tree view when we use vertical scroll bar. Please find below screen recording. and coldef along with gridoptions. I am using aggrid 31.2.1 ("@ag-grid-community/core": "^31.2.1",);

` colDef = [
      {
        headerName: "expandCollapse",
        cellRenderer: "ExapndCollapseRenderer",
        cellRendererParams: { gridApi: gridApi },
        pinned: "right",
        width: 45,
        maxWidth: 45,
        resizable: false,
        cellStyle: {
          border: "none !important",
          background: "white",
          color: "black",
        },
        lockPinned: true,
        cellClass: "lock-pinned",
      },
      {
        headerName: "threeDots",
        cellRenderer: "ClickableCellRenderer",
        cellRendererParams: {
          gridApi: gridApi,
          action: props.action,
          searchPanelType: props.type,
        },
        pinned: "right",
        resizable: false,
        minWidth: type === "hierarchy" ? 45 : 70,
        width: type === "hierarchy" ? 45 : 70,
        cellStyle: {
          border: "none !important",
          background: "white",
          color: "black",
          margin: 0,
        },
        lockPinned: true,
        cellClass: "lock-pinned",
      },
    ];

gridOptions = {
    headerHeight: 0,
    excludeChildrenWhenTreeDataFiltering: true,
    rowStyle: { background: "white", border: "none" },
    icons: {
      groupExpanded: `<img src="${collapseIcon}" style="height: 16px; width: 16px;padding-right: 2px"/>`,
      groupContracted: `<img src="${expandIcon}" style="height: 16px; width: 16px;padding-right: 2px"/>`,
    },
    rowSelection: "single",
  }; 
`

https://github.com/ag-grid/ag-grid/assets/156076198/92120797-c91a-42b3-9d85-c334fd9fd9be

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by santoshkumar-maddela** [comment]
Hi Zoheil,

Thank you for responding. I tried to replicate the scenario in the plunker but due to huge data I am unable to proceed. I just created plunker with small json Data. And attaching actual data. Please check.

https://plnkr.co/edit/mCehoQO10BlXIRta?open=index.tsx

<img width="505" alt="Screenshot 2024-07-08 at 7 24 20 PM" src="https://github.com/ag-grid/ag-grid/assets/156076198/c5c8b0b3-08e8-49da-96a3-1aa83d65ccef">


[data.txt](https://github.com/user-attachments/files/16139422/data.txt)

Thank you.

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for reporting this and supplying the data - much appreciated!

Whilst we were unable to get the scroll bar to break for us like it happens in your video we've been able to reproduce the issue with the row borders and added it as a bug to our backlog.

We are tracking it with the following reference: **AG-12050**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
