### ISSUE TITLE
Error when updating ag-Grid from version 31.1.1 to 32.0.0

### ISSUE THREAD

**Issue by ajnabibaalveer** [ag-grid/ag-grid#8272]
``### Issue Description
I am encountering an error while updating ag-Grid from version 31.1.1 to 32.0.0.

### Steps to Reproduce
1. Update ag-Grid from version 31.1.1 to 32.0.0.

### Expected Behavior
In ag-grid-react version 31.1.1, there was a `bundle` folder present.

### Actual Behavior
After updating to ag-grid-react version 32.0.0, the `bundle` folder is no longer present. Additionally, the `ag-grid-react-min.js` file has been removed
I'm looking for guidance on:
- The replacement for `ag-grid-react-min.js` file in version 32.0.0.
- Instructions on how to correctly configure and run the updated code snippet in the new version.

### Additional Information
- Old version example: [Plunker link](https://plnkr.co/edit/Lf4oF1OSsq3BbeeJ?open=Hello.js&deferRun=1&preview)
- New version example: [Plunker link](https://plnkr.co/edit/OesheNK6uDIe6wrL?open=index.jsx&preview)

I believe this change has caused the issue. Please advise on how to correctly handle these changes in the new.

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12124**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by ShivanandPrajapati** [comment]
@AG-Zoheil ,

Thank you so much for resolving this bug so quickly! I really appreciate your prompt response and effort in fixing the issue in the release of 33.0.3.
