### ISSUE TITLE
can't import locales for javascript with import type modules

### ISSUE THREAD

**Issue by eldala07** [ag-grid/ag-grid#8311]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hello,
I'm trying to use the AgGrid localization, and when I check the preview from the docs for
- Language: Javascript
- Import type: Modules

the exemple is broken.

It comes from the `AG_GRID_LOCALE_DE` which is not imported.
I tried to import it, but it looks like it is not exported for this configuration.

**Current behavior**

Select
- Language: Javascript
- Import type: Modules

in the first example of the localization page of the documentation ([https://www.ag-grid.com/react-data-grid/localisation/](https://www.ag-grid.com/react-data-grid/localisation/))

Notice the preview is broken - just a black preview.

![image](https://github.com/ag-grid/ag-grid/assets/29813976/fbaf1a47-4c2e-4c43-8486-404c5c8494cc)

There is also an error message on the next section from the docs:

![image](https://github.com/ag-grid/ag-grid/assets/29813976/551fab21-6c8d-48d1-901b-a0ab255cc4f9)

Error message:
>Example Error: Error: (SystemJS) AG_GRID_LOCALE_DE is not defined ReferenceError: AG_GRID_LOCALE_DE is not defined at execute (https://www.ag-grid.com/examples/localisation/customLocalisation/modules/reactFunctional/index.jsx!transpiled:87:57) Error loading https://www.ag-grid.com/examples/localisation/customLocalisation/modules/reactFunctional/index.jsx

**Expected behavior**

Example is working and locales can be imported in the configuration:
- Language: Javascript
- Import type: Modules

**Please tell us about your environment:**

- Ubuntu 22.04.4 LTS 
- IntelliJ IDEA 2024.1.4 (Ultimate Edition) Build #IU-241.18034.62, built on June 20, 2024

**AG Grid version:** 32.0.1

**Browser:**

'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 OPR/111.0.0.0'

**Language:**
ES6

**Comment by JarFrank** [comment]
I am experiencing the same behavior with Angular. I'm not sure if that is related but I have issues with accessing locales in my angular project
![image](https://github.com/ag-grid/ag-grid/assets/39670453/1fddcd0c-382a-48a8-bfa9-2a1e34e1d581)

**Comment by StephenCooper** [comment]
As a workaround please pin the version of `@ag-grid-community/locale` to 32.0.0 as there is an issue with 32.0.1.

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12239**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
