### ISSUE TITLE
Pinned row no longer updates in v32 (when using getRowId)

### ISSUE THREAD

**Issue by jritzi** [ag-grid/ag-grid#8319]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
[Plnkr on v32, forked from Row Pinning example](https://plnkr.co/edit/lAA79wL3G2sOJkYS?preview)

To reproduce the issue:

1. Set up a grid with `pinnedBottomRowData` controlled by a prop and `getRowId`.
2. Change the prop to make the component re-render (press the "Randomize" button in the Plnkr).
3. The pinned row data does not update.

Removing `getRowId` resolves the issue, so this seems to be related to the v32 change to use row ids for pinned rows.

**Expected behavior**
[The same Plnkr on v31](https://plnkr.co/edit/rXd9BR4Izlf9vX6c?preview)

The pinned row data should update.

**Please tell us about your environment:**

* **AG Grid version:** 32.0.1

* **Browser:** 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

* **Language:** all

**Comment by leonelvsc** [comment]
same here

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12193**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
