### ISSUE TITLE
Preserve tree data expanded state (v32)

### ISSUE THREAD

**Issue by paulovirote** [ag-grid/ag-grid#8320]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hi AG Grid team!

We're upgrading the lib from 29 to 32 but it seems that one specific behavior has changed since the previous version: when adding/removing entries of the same level the expanded state is not properly preserved.

Example forked from the Tree Data docs: https://codesandbox.io/s/org-hierarchy-forked-47f7p6

In the video below, you can see that we can add data without much trouble, but when we're adding and deleting at the same time the group state is reset (sorry for the ugly code, I was really trying to find a way to reproduce this behavior consistently).

https://github.com/ag-grid/ag-grid/assets/10167527/8fc2f906-a99c-44c4-ac90-8a0380d882da

I do not see this issue in version `31.3.2`, but the tree view levels are also not as reactive as v32 (and I think it's much better now, thanks for that!).

**Current behavior**
Expanded/collapsed rows are always reset when new data is added.

**Expected behavior**
Expanded/collapsed rows should remain if they are still present and ID did not change.

**Please tell us about your environment:**

macOS Sonoma 14.5, Visual Studio Code, yarn

* **AG Grid version:** 32.0.1

* **Browser:** 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

* **Language:** TypeScript 5.3

**Comment by AG-Zoheil** [comment]
Hi @paulovirote,

Thank you for reporting this.

I'm afraid we are having some trouble with your codesandbox link - it is returning 404 - would you be able to create a new fork and share again please so we can have a look?

Many thanks!

**Comment by paulovirote** [comment]
@AG-Zoheil sorry about that, you can try again now. Just a reminder that the `add + remove` behavior mentioned starts on the third level (Esther and Francis using the sample data). Thanks!

**Comment by sidney-reis** [comment]
Hey @AG-Zoheil , I'm having this issue after updating to 32.
Any chance this is looked at? Thank you!

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12591**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
