### ISSUE TITLE
[CVE-2024-38996] issue ag grid v32.0.1

### ISSUE THREAD

**Issue by jpsla94** [ag-grid/ag-grid#8321]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```
I have upgraded to version 32.0.1 yesterday in order to fix vulnerability CVE-2024-38996. After upgrading, I generated a new security report and this issue still shows up. Can you kindly confirm that it has been fixed? Or are there other modifications I need to perform?

* **AG Grid version:** 32.0.1

* **Browser:** chrome 126.0.0.0

* **Language:** TypeScript 5.3.3

**Comment by AG-Zoheil** [comment]
Hi @jpsla94,

Thanks for getting in touch via GitHub.

We can confirm that this was fixed in `32.0.1`.
You can see this here: https://plnkr.co/edit/Z26jcSMu6pj7S0Bx?open=main.js

Kind regards,
Zoheil

**Comment by jpsla94** [comment]
Thank you for your reply @AG-Zoheil. But if it is fixed, why still shows up in the security report after upgrading?

**Comment by AG-Zoheil** [comment]
Hi @jpsla94,

A further patch was released `32.0.2` for stability and security - please upgrade to this latest version.

Kind regards,

**Comment by stevendarby** [comment]
are there any plans to patch 30.x?

**Comment by jimcward** [comment]
yes, please consider patching 31.x and 30.x - there are often breaking changes between releases that we would need to schedule a not-insignificant amount of time to fix up in a large app, thanks!

**Comment by AG-Zoheil** [comment]
We can now confirm that our findings are in line with the EPSS rating of the vulnerability that stands at just 0.05% (independently verified here: https://www.cvedetails.com/cve/CVE-2024-39001/), meaning this vulnerability is extremely unlikely to be exploited.
 
We acknowledge that there may be regulatory pressures to resolve this reported vulnerability despite the extremely low risk involved. Therefore we have provided patches for our latest version (`v32`) and the version it was reported in (`v31`).
 
As usual, we'd recommend upgrading the version of AG Grid in your application so you can benefit from all the improvements in functionality, stability, security, theming and performance we've made since the version you're using.

Also, I'd recommend to upgrade the ag-Grid version sooner rather than later to avoid having even more changes to make as part of the upgrade process. We do our best to avoid making breaking changes to API and behaviour and we rigorously log the ones that are unavoidable.

Thank you for your continued trust in AG Grid.

**Comment by vkravchuck-mdx** [comment]
@AG-Zoheil Hi! Thank you for your response!
I see that you left a link to another vulnerability (to CVE-2024-39001)
I want to ask again whether CVE-2024-38996 will also be fixed in patch v31?

**Comment by AG-Zoheil** [comment]
Hi @vkravchuck-mdx,

Both have been fixed.

Thanks!
