### ISSUE TITLE
[suppressServerSideInfiniteScroll]="true" throws an error when rowData is empty array in 32.0.1

### ISSUE THREAD

**Issue by SaulFein** [ag-grid/ag-grid#8332]
**I'm submitting a ...**  
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Grid throws an error when  [suppressServerSideInfiniteScroll]="true" and the grid returns rowData as []. I just upgraded my app and found this setting to be the culprit. If a filter returns data it works fine but if it is empty there is an error and this was not the case in version 31.

I created a plunkr from the AG grid docs (https://www.ag-grid.com/angular-data-grid/server-side-model-datasource/) and modified it to return a empty array and [suppressServerSideInfiniteScroll]="true". 
https://plnkr.co/plunk/fc2CqGPIRFRDRoKy
<img width="386" alt="image" src="https://github.com/user-attachments/assets/92ed6b7e-5acc-484b-a172-c875234781e1">
**Expected behavior**
Not throw and error and get stuck with the loading spinner and just show an empty grid when rowData = []

* **Environment:** Windows 10, VS Code

* **AG Grid version:** 32.0.1

* **Browser:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

* **Language:** [TypeScript 5.4.3]

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12084**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
