### ISSUE TITLE
While resizing, misalignment of menu/resize icon on column with header checkbox

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#8336]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Following example has "Athlete" column with header checkbox. Now try to resize the column. Its observed that the resize handler icon overlaps menu icon and aligns it before menu icon
https://plnkr.co/edit/9yWE17S1SCVsvFOv?open=index.tsx&preview

![Gif](https://github.com/user-attachments/assets/3bda5f97-41cd-49f7-8f74-6023b5abbe1c)

**Expected behavior**
Menu Icon & Resize Icon should align as it happens for other column

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
32.0.1

* **Browser:**
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11786**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
