### ISSUE TITLE
Cell editing in tree data works only on the deepest level

### ISSUE THREAD

**Issue by dominikkurenda** [ag-grid/ag-grid#8372]
[x] bug report 

Version 32.0.2
Cell editing in tree data works only on the deepest level

https://plnkr.co/edit/z6oo9UUCPreYG3fq?open=main.ts

![image](https://github.com/user-attachments/assets/6fe3ef81-a9b5-4641-9865-3f887b639504)

Eariler you could edit all rows despite they level in tree.

**Comment by chrisvander** [comment]
Seconding this issue. Same problem, custom cell editor.

**Comment by chrisvander** [comment]
They've reproduced it and are working on it under issue number [AG-12410](https://www.ag-grid.com/pipeline/)

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12410**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by soloveynchub** [comment]
Hello, @dominikkurenda !
I have some problem, maybe you can help me with this code:

```
columnDefs.push({
          headerName: 'Руководитель отдела',
          field: 'Руководитель отдела',
          cellRenderer: (paramses) => {
            // Проверяем, является ли строка группирующей
            if (paramses.node.group) {
              const value = paramses.value || 'Руководитель не выбран';
              const className = value === 'Руководитель не выбран' ? 'no_head' : 'have_head';
              return `<span class="${className}">${value}</span>`;
            }
            return paramses.value; // Не отображаем поле "Руководитель отдела" для сотрудников
          },
          editable: (paramses) => paramses.node.group, // Разрешаем редактирование только для групп
          cellEditor: 'agRichSelectCellEditor',  // Используем agRichSelectCellEditor для автопоиска
          cellEditorParams: {
            values: departmentHeads, // Динамически загруженные ФИО
            searchEnabled: true,  // Включаем функцию поиска
            cellEditorPopup: true, // Попап для выбора из списка
            allowTyping: true,
            filterList: true,
            highlightMatch: true
          }
        });
```
