### ISSUE TITLE
Set Column Filter - asynchronous loading of complex object values

### ISSUE THREAD

**Issue by matejdostal** [ag-grid/ag-grid#8374]
Currently it's not possible to asynchronously load complex objects as values into Set filter, because params.success function in filterParams.values callback expects string[].

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for submitting this on Github.

Supplying async values (https://ag-grid.com/javascript-data-grid/filter-set-filter-list/#asynchronous-values) is an enterprise feature. As we do not provide support on Github but only take bug reports, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/hc/en-us) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here.

Kind regards,
Zoheil
