### ISSUE TITLE
firstDataRendered event fires before the gridReady event fires

### ISSUE THREAD

**Issue by vikashkumar29** [ag-grid/ag-grid#8414]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[X] support request => see 'Requesting Community Support'
```
**What happens:**

With the latest ag-grid version used with angular, I observe that firstDataRendered event is fired before the gridReadyEvent, This was not with version 31.0.3. 

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- I am upgrading from ag-grid 31 to 32
- I bind my grid with a list of elements, then firstDataRenderd event is fired before the gridReady event.

I took the plunger of RowDataUpdated and modified a bit to show the behavior:
https://plnkr.co/edit/DfxopCavY9NIDbiv?open=app.component.ts

**Current behavior**
gridReady event fires after firstDataRendered

**Expected behavior**
As of ag-grid version 31, gridReadyEvent should be fired before firstDataRendered

* **AG Grid version:** X.X.X
 "ag-grid-angular": "32.0.2",
 "ag-grid-community": "32.0.2"

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0'
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
TypeScript 5.5.4

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12433**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
