### ISSUE TITLE
Initial State Filter Model Not Applied Correctly with Server-Side Row Model

### ISSUE THREAD

**Issue by lukasirsak** [ag-grid/ag-grid#8416]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
When initializing an AG Grid with server-side row model and setting an initial filter state, the onGridReady event is fired twice. The first time it is called, the params.request.filterModel does not contain the expected filter data from the initial state. This results in the server-side data request being made without the intended filter, causing incorrect data to be fetched and displayed initially.

**Expected behavior**
params.request.filterModel in getRows should contain the filterModel from initialState on the first run.
onGridReady should be called only once, when the AJAX call is finished.

**Example code**
```
<script setup>
import { ref } from 'vue';
import { AgGridVue } from '@ag-grid-community/vue3';
import { ModuleRegistry } from '@ag-grid-community/core';
import { ServerSideRowModelModule } from '@ag-grid-enterprise/server-side-row-model';
import { SetFilterModule } from '@ag-grid-enterprise/set-filter';

ModuleRegistry.registerModules([ServerSideRowModelModule, SetFilterModule]);

const grid = ref();

const initialState = {
  filter: {
    filterModel: {
      name: {
        values: [1],
        filterType: 'set',
      },
    },
  },
};

const gridOptions = {
  columnDefs: [
    {
      field: 'name',
      filter: 'agSetColumnFilter',
      filterParams: {
        values: (params) => {
          // Faking Ajax request
          setTimeout(() => {
            params.success([
              { value: 1, label: 'Option A' },
              { value: 2, label: 'Option B' },
            ]);
          }, 100);
        },
        valueFormatter: (option) => {
          return option.value.label;
        },
      },
    },
  ],
  rowModelType: 'serverSide',
};

const onGridReady = () => {
  grid.value?.api?.setGridOption('serverSideDatasource', getServerSideDatasource());
};

const getServerSideDatasource = () => {
  return {
    getRows: (params) => {
      // First time filterModel is empty, second time it's updated correctly.
      console.log(params.request.filterModel);

      params.success({
        rowData: [{ name: 'Sample' }],
        rowCount: 1,
      });
    },
  };
};
</script>

<template>
  <AgGridVue
    ref="grid"
    :initial-state="initialState"
    class="ag-theme-alpine h-full"
    :grid-options="gridOptions"
    @grid-ready="onGridReady"
  />
</template>

```

**Console log results**
<img width="532" alt="Snímka obrazovky 2024-07-26 o 20 58 26" src="https://github.com/user-attachments/assets/ba9a32fb-ec2c-4f3a-a195-b1f012d6e5da">

**Please tell us about your environment:**
Vite

* **AG Grid version:** 
31.3.2, 32.x.x also

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

* **Language:** 
all

**Comment by sabahang** [comment]
Hello,

Thank you for bringing this up with us. 

The functionality you described wasn't part of the requirements when we built this feature. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-12229**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!
