### ISSUE TITLE
Calling getSelectedRows required rowSelected event

### ISSUE THREAD

**Issue by cah-ken** [ag-grid/ag-grid#8424]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

https://plnkr.co/edit/GPjFclbpId2fDhC2?open=app.component.ts&preview

**Current behavior**
In the plunker, selecting a row displays the selected make as well as toggles the disabled property of the Edit button based on the selected row's canEdit property.  However, if you remove the (rowSelected) event on the grid, those functions stop working.

**Expected behavior**
The rowSelected function is an empty function.  It provides no functionality yet it seems to be required for calling the gridApi's getSelectedRows function.  The getSelectedRows function worked without the event pre version 31, but I haven't found in the documentation if it's a new requirement.  Is this working as intended?

**Please tell us about your environment:**
Windows,

* **AG Grid version:** 32.0.2

**Comment by sabahang** [comment]
Hi @cah-ken 

In the provided example, there is nothing to trigger Angular change detection if rowSelected is not used. Therefore nothing will update in the component. This is nothing to do with AG Grid, and is the standard behaviour of Angular change detection.
 
Note that prior to v31, the grid was sometimes over-eager in triggering change detection. This was fixed in v31.
