### ISSUE TITLE
In server side data mode, the export CSV functionality is malfunctioning in groupHideOpenParents mode.

### ISSUE THREAD

**Issue by Darkells** [ag-grid/ag-grid#8530]
Requesting Community Support
I'm very pleased that the project team quickly added support for groupHideOpenParents in server side mode, and the new feature's styling looks fantastic. However, I've encountered an issue with the CSV export functionality.

Current behavior
In server-side data mode, when configuring groupHideOpenParents, the feature works as expected, but there seems to be an issue with the CSV or Excel export functionality.

Expected behavior
I try to configure multipleColumns in server side data mode, the expected functionality works very well, but the CSV export results in blank data.

Please tell us about your environment:
react

AG Grid version:
v32.1.0

Browser:
Google

Language:
Typescript

**Comment by Darkells** [comment]
I am currently trying to reproduce the issue with simulated data. I will provide the relevant screenshots shortly.

**Comment by AG-Zoheil** [comment]
Hi @Darkells,

Thank you for submitting this on Github.

SSRM and row grouping are enterprise features. As we do not provide support on Github, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/hc/en-us) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here.

Kind regards,
Zoheil
