### ISSUE TITLE
[Cell Editing] [React] singleClickEdit & rowClassRules stops the editing

### ISSUE THREAD

**Issue by vitaliizharkov26** [ag-grid/ag-grid#8537]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I use this code https://ag-grid.com/javascript-data-grid/cell-editing-start-stop/#single-click-editing

Plunker: https://plnkr.co/edit/XPocf6sYYoUHHq2G?open=index.tsx
Video: https://github.com/user-attachments/assets/7b44cb68-4a62-4fb4-beff-494feac63af3

**Current behavior**
The issue is reproducible when using singleClickEdit and rowClassRules. Clicking on the cell will cause the editing to stop. (With singleClickEdit = true)

**Expected behavior**
I suspect it's a bug, in this scenario, it should not terminate the editing

* **AG Grid version:** X.X.X
Latest (32.1.0)

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'

* **Language:** React

**Comment by ava-utting** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-12462 When updating with row styling properties in React, focus is lost**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Ava
