### ISSUE TITLE
Cell component height is not calculated when Cell Text Selection is enabled

### ISSUE THREAD

**Issue by nbran** [ag-grid/ag-grid#8561]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**

1. https://plnkr.co/edit/u00VSEH747sKqgwf?open=index.tsx
2. https://plnkr.co/edit/Nue4NoBSZLReLAzZ?open=index.tsx

Forked from: [Cell Components documentation](https://www.ag-grid.com/react-data-grid/component-cell-renderer/)

**Current behavior**
When the grid is configured for [Cell Text Selection](https://www.ag-grid.com/react-data-grid/selection-overview/#cell-text-selection) with `enableCellTextSelection=true` and `ensureDomOrder=true`, the grid adds a div wrapper with a `ag-cell-wrapper` class that does not calculate the height of the cell correctly (first Plunker example). However, the cell height is correctly calculated if the cell component contains text (second Plunker example). 

**Expected behavior**
The height of the component cell should be calculated correctly when Cell Text Selection is enabled.

**Please tell us about your environment:**
Ubuntu 22, VSCode, NPM, React, Vite

* **AG Grid version:** 
  * 32.1.0

* **Browser:**
  * Mozilla/5.0 Gecko/20100101 Firefox/129.0
  * Brave 1.68.141 Chromium: 127.0.6533.120

* **Language:**
  * Typescript 5.5.4

**Comment by nbran** [comment]
Screenshots to help illustrate the issue:

**Current behavior** 

(`gridOptions.enableCellTextSelection` and `gridOptions.ensureDomOrder` set to `true`)

![image](https://github.com/user-attachments/assets/b226e95b-a4b2-4f3f-9663-9ecf11c3b88e)

**Expected behavior**

(`gridOptions.enableCellTextSelection` and `gridOptions.ensureDomOrder` not set)

![image](https://github.com/user-attachments/assets/2bfe778a-817e-44e9-949f-b12dbfadb3b4)

**Comment by nbran** [comment]
Thanks for the reply and for the suggestion. It's addressable with CSS but as you said, it seems like something that should be addressed by AG Grid as it is inconsistent and results in erratic output.

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-13113**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

In the meantime you can work around this by adding a non breaking space at the end of the cell.
See: https://plnkr.co/edit/QXiCsYrkix91CNPu?open=index.tsx

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by kiril-matev** [comment]
Hello @nbran,

You can resolve this by adding a non-breaking space at the end of the cell as shown below:
See: https://plnkr.co/edit/QXiCsYrkix91CNPu?open=index.tsx
