### ISSUE TITLE
Unpinning column by dragging cause wrong column state

### ISSUE THREAD

**Issue by danielmalaton** [ag-grid/ag-grid#8572]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
**Plunker**: https://plnkr.co/edit/sRQIfFH4JIjeA399?open=main.js
**Context:** 
- We have four columns that are left pinned
- We log the column state after moving columns via UI

**Reproduce**: Move the `Total` out of the left pinned range, make it unpin

**Current behavior**
- The column state order is:
  - `total`
  - `rowNum`
  - `athlete`
  - `age` 

**Expected behavior**
- The column state order is:
  - `rowNum`
  - `athlete`
  - `age` 
  - `total`

**Please tell us about your environment:**

* **AG Grid version:** 32.1.0

* **Browser:** Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ava-utting** [comment]
Hi,

Thanks for reaching out.

The issue you have reported is actually expected behaviour for the grid.
The order in the pinned columns container does not affect the order in the grid.
In this test case, the column state reflects the order as described in the column definition. 

For example:
1. Open this sample https://plnkr.co/edit/n1HxqVU4tyEIeS1y?open=main.js&preview
2. Open console 
**Actual and Expected:** ['athlete', 'sport', 'age']  
This is the order as shown in the column definitions as opposed to the 'visual' order we can see with the pinned columns.

Please let us know if you have any other questions.

Regards,
Ava
