### ISSUE TITLE
Major memory leak - v32

### ISSUE THREAD

**Issue by paulovirote** [ag-grid/ag-grid#8587]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hi AG Grid team!

After migrating from version 29 to 32 we started to notice a major increase in the memory consumption of the app. After some investigation we've noticed that it was due to the fact that memory seems to not be released properly when the table is destroyed. This is a major problem and I assume other people may also be facing it.

Here's a video from the codesandbox just showing that the consumption keeps going up:

https://github.com/user-attachments/assets/d806ef91-60cb-4b9f-82dd-b7f2b860d9c0

You can see that even forcing the garbage collector doesn't do much about it. Here's the video example forked from the official docs: https://codesandbox.io/p/sandbox/aggrid-memory-sample-gmryq8

We already tried manually calling the `destroy` function (docs says this is not necessary though) during the unmount but it doesn't change anything. If there are any suggestions on how to fix this without requiring an update from your side we're also happy to take it.

I also understand you guys have a list of priorities, but if this is confirmed as an issue it would be really good if this could have a higher priority as one of the biggest reasons to use AGGrid is the performance.

**Current behavior**
Memory consumption keeps going up.

**Expected behavior**

Memory should be properly released when the table is destroyed.

**Please tell us about your environment:**
macOS Sonoma 14.5, Visual Studio Code, yarn

**AG Grid version:** 32.1.0

**Browser:** 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Language:** TypeScript 5.3

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12636**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by paulovirote** [comment]
they've targeted for next release 🙌🏻 
![Uploading Screenshot 2024-09-04 at 15.26.14.png…]()

**Comment by ankitmehta22** [comment]
Was this fixed? Is there a workaround for this?

**Comment by ankitmehta22** [comment]
Also I tried your example using 29.3.5 and it gives the same error. @paulovirote Which version of AgGrid did you have where this was not an issue?

**Comment by paulovirote** [comment]
@ankitmehta22 it seems that it's planned for the next release
<img width="1153" alt="Screenshot 2024-09-09 at 12 34 28" src="https://github.com/user-attachments/assets/2e382f20-226d-4cf8-855e-a8fed8c64842">

**Comment by kiril-matev** [comment]
This was fixed in v32.2.0, as indicated in the changelog:
https://www.ag-grid.com/changelog/?searchQuery=12636

Please upgrade to v32.2 or later to resolve this issue.

**Comment by SebastianVeile** [comment]
Has this bug been reintroduced in version v33? I can reproduce it just the same. But if i downgrade to v32.2 it is solved

**Comment by AG-Zoheil** [comment]
Hello @SebastianVeile 

Thank you for reporting this - much appreciated!

We will investigate this further and have added it to our backlog with the following reference: **AG-14198**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi @SebastianVeile,

We've investigated this further and had a closer look by comparing v32.3 with v33 and we do not believe there is an issue.

Please see the two in comparison below:

v32.3: https://plnkr.co/edit/edbqvXQTMP2VavBo?open=main.js&preview
v33: https://plnkr.co/edit/KJ7Q46yxgnXgHizi?open=main.js

Kind regards,
Zoheil

**Comment by qianyuhouse** [comment]
is there anything way to resolve this problem without upgrade?
