### ISSUE TITLE
Tab Navigation Fails to Enable Editing on First Cell of Second Row in Full Row Editing Mode

### ISSUE THREAD

**Issue by edlnr** [ag-grid/ag-grid#8592]
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

This is happening in `fullRow` edit mode.

**Current behavior**
When editing the last cell of the first row and pressing the Tab key, the next cell in the second row is selected, but it is not enabled for editing. The expected behavior is that the first cell of the second row should be selected and immediately enabled for editing. Instead, the second row is selected, but no cell is in editing mode. Pressing Tab again will then select and enable editing for the second cell of the second row.

**Expected behavior**
The first cell of the second row should be selected and automatically enabled for editing when pressing Tab after entering a value in the last cell of the first row. This behavior is consistent with how tab navigation and cell editing are expected to function within AG Grid.

**Providing a Reproducible Scenario**

1. Start editing the last cell of the first row.
2. Press the Tab key to move to the next cell.

**Expected Result:** The first cell of the second row should be selected and enabled for editing.
**Actual Result:** The second row is selected, but no cell is enabled for editing. Pressing Tab again selects and enables editing for the second cell of the second row.

You can reproduce this behavior in the following CodeSandbox forked from your **Full Row Editing** example: [CodeSandbox Example](https://codesandbox.io/p/sandbox/full-row-editing-forked-lv3d47)

**Please tell us about your environment:**

Operating system: any
Browser: any
AG Grid version: 32.1.0

**Comment by ava-utting** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-12656 [When tabbing to a new row with full row editing in React, focus is lost]**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Ava
