### ISSUE TITLE
Expanded Master Detail provide wrong classname

### ISSUE THREAD

**Issue by arieffikhrie** [ag-grid/ag-grid#8646]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

From the example of [Master Detail](https://www.ag-grid.com/javascript-data-grid/master-detail/#enabling-master--detail) in the docs. When 2nd item is expended, i'm expecting the classlist for the `.ag-row` would still have class `.ag-row-odd`, but then it became `.ag-row-even`. This bug occurs on on any of expanded group, the classname changed to `.ag-row-even`.

![image](https://github.com/user-attachments/assets/bb0a6c94-2b86-46ee-875d-25c989281c4e)

**Comment by sabahang** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now submitted this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-13074 [Master Detail][Row Grouping] Classlist for the row doesn't reflect correct .ag-row-odd/even class when row expand**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

Kind regards,
