### ISSUE TITLE
Unable to use Angular signal store for AG-Grid ServerModel Row Type

### ISSUE THREAD

**Issue by SrikanthP0548** [ag-grid/ag-grid#8657]
**I'm submitting a ...**  (check one with "x")
```
[] support request => see 'Requesting Community Support'
```
**Framework**
Angular - v18+

**Providing a Reproducible Scenario**
https://stackblitz.com/edit/stackblitz-starters-nv8tjl

**Current behavior**
After updating the signal store, ag-grid data is not updating, it keeps on loading forever. 

**Expected behavior**
Expected after updating the signalStore it should render the data in grid.

* **AG Grid version:** X.X.
AG-Grid Version: 32.1.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Here is screenshot for reference.

![image](https://github.com/user-attachments/assets/d97daa1e-a4cc-4b40-a3dd-b78ef53243ea)

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for submitting this on Github.

SSRM is an enterprise feature. As we do not provide support on Github, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/hc/en-us) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here, as it has been open for quite a while without any further interaction.

Kind regards,
Zoheil
