### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by alixroyere** [ag-grid/ag-grid#8679]
**I'm submitting a ...**  
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

We are customer of AG Grid _but I've lost the zendesk account due to leaving and coming back to the company_ 👀

**Providing a Reproducible Scenario**
In your own demo: https://www.ag-grid.com/javascript-data-grid/localisation/ 
Right click on grid header > Spalten auswählen (= Choose Columns; this one is translated!) > See untranslated pop up title

![image](https://github.com/user-attachments/assets/0bcaf80d-07a4-4404-8bd8-892690b4ebc8)

This is german and we are using french translation, but I suppose that the missing key is global

**Current behavior**
There is a missing translation for "Choose columns" title in pop up to filter columns to display.

**Expected behavior**
Fix key and value in translation files. Or at least provide the key to locally fix that

**Please tell us about your environment:**

* **AG Grid version:** latest (now is 32.1.0)

* **Browser:** Doesn't matter

* **Language:** Doesn't matter

Thank you

**Comment by AG-Zoheil** [comment]
Hello @alixroyere,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12826**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
