### ISSUE TITLE
With new selection API (32.2.0), checkbox selection cannot be enabled together with Cell selection

### ISSUE THREAD

**Issue by jlpstolwijk** [ag-grid/ag-grid#8768]
**I'm submitting a ...**  (check one with "x")
```
x bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
Behavior of 32.2.0 with new selection API: checkbox selection cannot be enabled together with Cell selection:
https://plnkr.co/edit/qMPalnNVVGgHgurQ?open=app.component.ts&preview

Behavior of 32.1.0 and before: checkbox selection and range selection can be enabled together (try selecting some rows and selecting a range):
https://plnkr.co/edit/YI4AmslZnCuyVThL?open=app.component.ts&preview

**Current behavior**
checkbox selection cannot be enabled together with Cell selection:

**Expected behavior**
 checkbox selection and range selection can be enabled together

**Please tell us about your environment:**
Angular 18.2.4

* **AG Grid version:** 32.2.0

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'
(Chrome for Windows 128.0.6613.138)

* **Language:** 
Typescript 5.5.4

**Comment by Eugeno** [comment]
I've encountered the same issue. It's necessary to have both the ability to select multiple rows (for subsequent processing) and the ability to select a portion of the table for copying its contents or exporting it.

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

As of version `32.2` we have made row selection and cell/range selection mutually exclusive due to the clashes and causes of inconsistency in behaviour when having both enabled at the same time.

However, please note that we are considering introducing an option to allow cellSelection + **rowSelection with checkboxes only**. Selection of one type would reset (undo) the selection of the other type, but both would be possible (enabled) at the same time.
 
This would allow users to utilise both types of selection whilst still protecting the grid from inconsistencies.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12929**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by jlpstolwijk** [comment]
Thanks for your reply! It sounds as if AG-12929 is exactly what I need. Would be great if this could be picked up; until then, I have to stick with the old selection api…
