### ISSUE TITLE
[Cell Editing] [React] Old data inside CellEditor

### ISSUE THREAD

**Issue by vitaliizharkov26** [ag-grid/ag-grid#8770]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Providing a Reproducible Scenario
I use this code https://ag-grid.com/javascript-data-grid/cell-editing-start-stop/#single-click-editing

Plunker: https://plnkr.co/edit/TEEFth3tldXvcPCN?open=index.tsx
Video: https://github.com/user-attachments/assets/e614f6cd-7c89-468b-9823-9e0fe6c7cdc1

Current behavior
In this scenario, the problem arises when I navigate to the next cell (for example, moving from "Athlete" to "Country" via Tab), instead of receiving Athlete = 123, I get an old valueю (In this scenario I'm expecting the updated value, also if my previous cell updates the next cell it's will not be reflected (I'm not getting the Country = Update value)) 

Expected behavior
I should get the latest data inside the cellEditor

AG Grid version: X.X.X
32.1.0

Browser:
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'

Language: React

**Comment by StephenCooper** [comment]
This is happening due to the async nature of React rendering triggered by setState.

If you wish to follow this pattern of updating the entire row data then you can wrap your update with `flushSync` to force this update to be run synchronously. 

https://plnkr.co/edit/8ae0dQ5yWz0rub8m?open=index.tsx

Normally we would expect valueSetters to be used to directly update data as outlined [here](https://www.ag-grid.com/react-data-grid/value-setters/).
